### ISSUE TITLE
115网盘分享导入提示失败，文件夹都为0B文件夹

### ISSUE THREAD

**Issue by MuMu360121** [liupan1890/aliyunpan#100]
![image](https://user-images.githubusercontent.com/1499007/124741681-8c58b900-df4e-11eb-88b6-93b4a7bb2617.png)

**Comment by YKYCYKYC** [comment]
可能这些文件不在阿里服务器中

**Comment by liupan1890** [comment]
请回复我一下115分享链接
比如链接为：https://115.com/s/swnfm6a399k 
如果涉及隐私，请回复我https://115.com/s/swnfm6a3 ---去掉最后3位

这个提示导入秒传任务失败
1.可能是因为分享链接内包含的某一条文件名/数据 格式不兼容
2.可能包含的文件夹太多，在创建文件夹时出错了（这种错误直接重新尝试导入一般就好了）

总之，跟这一条连接有关，所以需要你回复我具体的链接，我试一下，看到底是哪里的问题

**Comment by MuMu360121** [comment]
> 请回复我一下115分享链接
> 比如链接为：https://115.com/s/swnfm6a399k
> 如果涉及隐私，请回复我https://115.com/s/swnfm6a3 ---去掉最后3位
> 
> 这个提示导入秒传任务失败
> 1.可能是因为分享链接内包含的某一条文件名/数据 格式不兼容
> 2.可能包含的文件夹太多，在创建文件夹时出错了（这种错误直接重新尝试导入一般就好了）
> 
> 总之，跟这一条连接有关，所以需要你回复我具体的链接，我试一下，看到底是哪里的问题

https://115.com/s/swny74g3hgh?password=sdb6&#
IMDb.Top.250.BluRay.1080p.x265.10bit.MNHD-FRDS
访问码：sdb6

**Comment by liupan1890** [comment]
抱歉，开的issue太多，我没看到这条更新

我今天试了一下，使用v2.8.15可以正常的导入了（v1.6.29 应该就是因为文件夹太多导致的导入失败，一般多点几次导入有时能导进去）
![无标题sss](https://user-images.githubusercontent.com/67817756/129469395-8ba2374c-9736-45fa-9898-a3fd0340890c.png)

**Comment by liupan1890** [comment]
解释一下文件夹太多

当你点击导入按钮的时候，会立即一次性创建分享内所有的文件夹，针对这一条分享链接，是需要创建234个文件夹

几百个文件夹不是重点，重点是v1.6.29的并发我调的太高，阿里云盘限制同时最多执行20条左右，v1.6.29会同时执行100条左右

所以就会导入失败

v2里已经完全按照阿里云盘的限制，同时只有15条左右。所以可以正常导入了

**Comment by MuMu360121** [comment]
> 解释一下文件夹太多
> 
> 当你点击导入按钮的时候，会立即一次性创建分享内所有的文件夹，针对这一条分享链接，是需要创建234个文件夹
> 
> 几百个文件夹不是重点，重点是v1.6.29的并发我调的太高，阿里云盘限制同时最多执行20条左右，v1.6.29会同时执行100条左右
> 
> 所以就会导入失败
> 
> v2里已经完全按照阿里云盘的限制，同时只有15条左右。所以可以正常导入了

你好，V2在MAC上要怎么安装，我从问叔叔上下载解压拖到程序列表后，提示没有权限打开应用

**Comment by liupan1890** [comment]
常见问题
1.Mac系统下载后提示：已损坏，您应该将它移到废纸篓？

答：这是因为苹果系统要求程序被证书签名，一年688元，我没有买。请参照此链接方式二操作即可 https://blog.csdn.net/H_Zaiii/article/details/105730557


我想你应该说的是这个
