### ISSUE TITLE
导入115秒传链接可以支持文件夹分类么

### ISSUE THREAD

**Issue by yato534** [liupan1890/aliyunpan#101]
如标题所述，115网盘导入秒传链接时是可以根据链接名分类文件夹，求问作者小白羊是否支持呢？

![3](https://user-images.githubusercontent.com/54138808/124877245-7c4be280-dffd-11eb-9895-cb7cf84e8696.jpg)

如上，可以根据链接最后的名称类别分类创建文件夹导入

**Comment by liupan1890** [comment]
这个不支持。
因为现在生成115秒传链接的插件有很多，格式也不统一，尤其是可能会有一些手动拼接的，或者包含大量文件夹的链接
阿里云盘需要先一个一个的创建好文件夹，再执行导入操作，这个体验不好

总之不支持根据最后的文件夹路径去按路径导入

如果你想要按照文件夹路径去导入文件，最好是使用115分享链接

是的，如果是一条115分享链接，里面不管包含多少文件/文件夹。现在小白羊都可以正常的按照原始文件夹路径导入---如果没出BUG的话，都可以正常导入

**Comment by yato534** [comment]
好的，感谢作者解答

**Comment by liupan1890** [comment]
最新版v2.8.15已经支持单层文件夹了
如你截图上面的，都可以正确的识别保存了
