### ISSUE TITLE
断点续传 重启后不生效 

### ISSUE THREAD

**Issue by kedyao** [liupan1890/aliyunpan#103]
由于上传文件列表中文件 突然消失 但是ali.exe依旧在上传流量
于是重启客户端后  任务出现但不可续传  
文件大小16G

**Comment by liupan1890** [comment]
因为当前上传的断点续传数据（上传url）是内存保存的，并没有保存到数据库里。所以重启后断点就会失败

最开始这样设计是因为阿里云盘上传链接当时测试不出有效期。

之后的版本我会留意这个，修正为重启后也能断点续传（就是把上传url保存到数据库了）

**Comment by liupan1890** [comment]
已在v2.8.22中修正，现在重启客户端也可以断点续传了
