### ISSUE TITLE
115分享链接导入时，部分文件丢失。

### ISSUE THREAD

**Issue by oliverxu1** [liupan1890/aliyunpan#104]
想导入一个电视剧，有38集，但是导入完之后只显示了29集。
重试了很多次，每次都是一样的结果。
链接如下：
https://115.com/s/swn37jh36r1?password=k750&

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/125082976-696b0800-e0fa-11eb-89de-8ab8019f8a55.png)

**Comment by liupan1890** [comment]
115 秒传都是靠运气的。如图，并不是文件丢失了，而是这几个文件阿里云盘里没有相同的文件，无法秒传

**Comment by oliverxu1** [comment]
> 115 秒传都是靠运气的。如图，并不是文件丢失了，而是这几个文件阿里云盘里没有相同的文件，无法秒传

懂了，谢谢大佬。
