### ISSUE TITLE
请问4k视频在线播放的画质还是4k吗

### ISSUE THREAD

**Issue by xioFelix** [liupan1890/aliyunpan#105]
如题 谢谢

**Comment by liupan1890** [comment]
使用小白羊在线观看视频，实际上是直接调用MPV播放器直接播放视频文件，就等同于你把视频文件下载到你的电脑然后播放是一样的，所以视频本身是4K，小白羊播放自然也是4K

使用阿里云盘的在线播放，是阿里云盘先把文件转码（720,1080），然后可以选择播放哪个清晰度，比如你选择1080，那就是1080.你想看4K但是现在阿里云盘并未提供4K转码，最高就是1080

**Comment by xioFelix** [comment]
这太牛了 感谢作者 （但我为啥感觉和本地播放器的画质还差点啊）

**Comment by liupan1890** [comment]
因为当前MPV都是使用的默认配置，你追求画质，可以自己研究一下mpv的设置，比如硬解，比如画质，比如对比度之类，mpv播放器支持的非常多，也非常厉害的，但我都没设置，只是调用的默认参数。百度，mpv，就好了

**Comment by xioFelix** [comment]
好的好的感谢
