### ISSUE TITLE
建议也发布到 腾讯的柠檬精选

### ISSUE THREAD

**Issue by bitboxclub** [liupan1890/aliyunpan#107]
腾讯也出了个mac 清理工具，免费的，目前口碑还不错。
这个软件有个 柠檬精选 频道，里面都是些好用的mac 软件。
建议你也将软件发布到那里
柠檬精选页面
https://lemon.qq.com/lab/

发布页
https://lemon.qq.com/lab/form/index.html

**Comment by liupan1890** [comment]
等我发布了v2版本时，再提交吧，当前版本还是太简陋了
