### ISSUE TITLE
Mac 版在线播放问题

### ISSUE THREAD

**Issue by zion101** [liupan1890/aliyunpan#108]
Mac版在线播放时，默认情况下会放得很大，整个屏幕都不能完全显示那种 😂 好像没有适配视网膜屏的缩放

**Comment by liupan1890** [comment]
应该是你的视频分辨率很高，MPV默认窗口大小是视频分辨率大小，比如你看4K视频，那就会这样，那么下个版本我记着改一下这个设置，然后需要你自己点击全屏按钮全屏观看。记下了

**Comment by zion101** [comment]
> 应该是你的视频分辨率很高，MPV默认窗口大小是视频分辨率大小，比如你看4K视频，那就会这样，那么下个版本我记着改一下这个设置，然后需要你自己点击全屏按钮全屏观看。记下了

感谢回复！
我用的 15 寸 MacBook Pro，物理分辨率是 2880 x 1800，但我发现看普通的 1080P 的视频，显示就已经超出了屏幕。
![image](https://user-images.githubusercontent.com/2428630/125889406-53032404-381c-4659-9e46-db6227746b4f.png)
视网膜屏的 Mac 机器，都会有一个缩放，比如我的机型默认的缩放，其实相当于「逻辑分辨率」是 1440 x 900，如上图所示。目前软件好像没有处理好这里的逻辑，所以很多 Mac 机器可能都会遇到这个问题。辛苦作者了！

**Comment by liupan1890** [comment]
明天晚上我会上传一份v2.8.1.pre的mac版本，你试一下，看MPV播放大小问题是否已经被修正了

（原来版本是直接视频大小，没有管屏幕）、
(v2.8.1是强制最大占据屏幕的50%，理论上是修正了此问题，但我没有视网膜屏，无法真实的测试，所以需要你试一下，告诉我结果啊)

**Comment by zion101** [comment]
> 明天晚上我会上传一份v2.8.1.pre的mac版本，你试一下，看MPV播放大小问题是否已经被修正了
> 
> （原来版本是直接视频大小，没有管屏幕）、
> (v2.8.1是强制最大占据屏幕的50%，理论上是修正了此问题，但我没有视网膜屏，无法真实的测试，所以需要你试一下，告诉我结果啊)

好的没问题，不急！
