### ISSUE TITLE
单文件最大30GB可以绕开吗，这是阿里云盘的限制还是程序的限制

### ISSUE THREAD

**Issue by LucasZhao22** [liupan1890/aliyunpan#109]
如题

**Comment by liupan1890** [comment]
是阿里云盘官方限制，再阿里云盘帮助里有说明

绕靠也就是把大文件自动分割成30GB以内的小文件

这个还是你自己找一个这样的小工具吧，因为分割就需要合并，假如是小白羊自动上传分割下载合并，以后万一你以后不使用小白羊了，那你就不能合并了。

百度：文件分割

非常多，一般都是几十kb的小工具

**Comment by HUD-A** [comment]
直接winnrar分包啊，话说你是不是要传4K蓝光原盘？我都传了七八个了，顶着20mbps的速度（
