### ISSUE TITLE
开发者能做一个115sha1转存阿里云网盘的功能吗

### ISSUE THREAD

**Issue by ymg0827965** [liupan1890/aliyunpan#11]
现在115是用的阿里云的服务器，我用过一个脚本可以将阿里云网盘里有的资源通过115的sha1链接转存到自己网盘，开发者能加一个这个功能吗，主要那个脚本一次只能转存一个链接，太麻烦了，不知道能不能在小白羊里实现这个功能呢

**Comment by liupan1890** [comment]
呃，
我没太明白。
1. 你是阿里云网盘里有这个文件，然后想要我生成115的链接，然后拿这个链接在115里用脚本转存（保存到115里）？
2. 你是有一堆115的链接，想要我在小白羊里增加按钮，输入115链接转存文件到阿里云网盘里？

按照1文件保存到115去解释：
假设我能生成115的链接，（选中一堆文件，点一下，生成一堆115链接），然后你还是需要使用你说的那个脚本在115里一条一条的保存（看你使用的脚本的功能），小白羊并不能登录115账号，也不能往115里转存文件。

按照2文件保存到阿里云盘去解释（我感觉你应该是这个意思）：
实际上就是说你手里的115链接包含了（sha1|size|name）这3要素，根据这个就能尝试秒传到阿里云网盘，你想要批量的秒传，理论上当然是可以的，不过我近2年没用过115，你需要回复我几条115的链接，方便我开发和测试，因为我需要一条115链接，根据他的具体格式，编写转换的代码

**Comment by RheumGitHub** [comment]
> 呃，
> 我没太明白。
> 你是有一堆 115 的链接，想要我在小白羊里增加按钮，输入 115 链接转存文件到阿里云网盘里？
> 
> （我感觉你应该是这个意思）：
> 实际上就是说你手里的 115 链接包含了（sha1|size|name）这 3 要素，根据这个就能尝试秒传到阿里云网盘，你想要批量的秒传，理论上当然是可以的，不过我近 2 年没用过 115，你需要回复我几条 115 的链接，方便我开发和测试，因为我需要一条 115 链接，根据他的具体格式，编写转换的代码



作者理解的没啥问题，那个脚本是阿里云盘脚本，地址是https://bbs.tampermonkey.net.cn/forum.php?mod=viewthread&tid=427，然后我给几个转存链接吧
115://Love.of.Thousand.Years.2020.E30.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2651442842|FE16245E277A1076AF763B9E6E5329FB52D055C0|8FBD4E41C384195C6ACE44707C642A4AF424C33B|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E29.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2896270159|D34DA961E4DF6D3A92270E6C4200F424D0FC6590|64ADBBBA12E3AB2D6B1A77336548544B8068E8EA|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E28.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2798177972|CEA71FB4A732090183D21682CCDC4ECA0DE262FB|892C3B2621211361CD9803EFF8D4BC5B62AB5862|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E27.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2564680134|987587CC21A475053947AE4DF480E7ABE33A2B99|2A5013C3CFCBDF753B1958AA8714AF97515AF3C8|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E26.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2521596260|CA12AE828726F6950A5FA5C7DF15428B2121E618|7F73547EB6FBF4004A5065B6518CA47A8F0A4212|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E25.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2880680498|183C883FBAF4CFF22171C98D2D9BB09B621D374B|B9A15A1C18354A1A04D1A233A067130C0AF9C314|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E24.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2993653341|36C68702033A66556456DA6F40CAB680E04873BE|2A19E23FA3CD8687A6573851CEE44CC73C18F735|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E23.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|3202552154|2979585BD64E35133FE7FB2E893010F8C4FF3E37|66EE6AD6E88A248628481DDEF77CE292C554BFC1|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E22.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2935017221|A5CAA47DC737D00D4B58AEFFD5EE3A89ABE7B6AF|20AC0FBC4F2A842DA384009FD2C369B523B7F8C9|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E21.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|3148976597|93B234EBD586DBF1A967091961796EFE4CB5ADF7|0721BFEF033F7030809A9E604978883B2FB1E623|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E20.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2516915571|36D4E6F50A066F78CF4098343816A733046554A6|843CF6853A93C73B427CF6F70FBD49CBA2067E3C|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E19.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2394294784|03B7078FFEC7F28D6915A9E2924483C26A52F202|141332D9B080C800BB4211645F1B81782EE49484|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E18.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|3032044196|124343ED2CC78664A5CCC49996300079E4853991|82DCCE4F472B00608AAB88AFBC7F2D8742FF684D|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E17.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2644310714|FB9666707C4F9D05911EAB24384578751BACD057|B31283F514F85786E3DC3D7F9C64598D614D19BD|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E16.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2821558588|CE92EA5F173A598DF4FF5F049BB77FDFDA97FF66|E9263BD6D53D236B5113AFBF5C94609937D1B93F|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E15.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2546711711|FFCD028B52D6F39FF5FDF67ABB36D432636DB260|CA93B0241916958E20ECE56C3969E4305509800A|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E14.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2368632017|F31D18F6F95C5363543005CD9B8822CEA31E4985|7ACF71874858666F823AF0995CADF4E8E7E81AFE|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E13.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2652603230|631EDDCCEC564CFB966D69DB2419289EBF608960|9E9411F6B9FF7BC59F7363453310694B8063C6E9|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E12.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2991052681|DBEB05F0D1D3C25EBB34151F5E12B54DBDCF2A8B|CA1AF8AFFCF454BD0B8C9C7F34898349BF517C7D|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E11.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|3063920013|DB2CC1EE47F612712DD2E09F8BA90C775748DBC3|F88FEA5360B70F530074AA8C26629C48505DF738|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E01.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2866674753|ED59C8F6EF79A6D39AA665FD5BB65D8ADA27E9DF|52496677CBB07E84A0AD0B1545FE4FBF2A2388CF|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E09.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2891451068|A82B8636D3AFE592709E1FEA5430C8993E031FAA|7B1566035718E6E62773F4906B100BD4900CEE5E|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E08.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2426910696|92129A0593541CD4219D4E8ECAEAF0AF0FC0B29E|29F2B87FBEA91A60D778BDFA6B5854F0DB8EDFED|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E07.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2190749924|F4DC7E10CBB09D0A851132D3FB73B188374A9AAF|1CCC4EC3BA0284ED1446E0F90189E3985CB8EF65|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E06.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2243287193|FF1CDCA54DF89388C18F67A7ABEBAD958DAA1261|D5F678D702A8873812DA2BDDF400A91865E148C3|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E05.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2344279925|0B0113C86C0C6A59568B303120E4B1B7C2749F05|0CF9FE4A06F392F83AC62A4132C410A928AABB6A|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E04.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2772409604|7A74E25B171E876C8957FB44EDA4AF6612A47D05|6BFEC8C2041D39226E0E3A719491F6318FCBBAE3|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E03.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2731653768|6E9C557C659B55004D1BB281939680545E2C4695|8D6EF77BDAEF81D53A45561DA8EA18060FAB7940|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E02.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|2926211463|0A3791613D9D6D402E701BE5C9F45E73AA651AAE|7223E0B88EA1F7A8BCADC69CE14B4EF7B59A9600|三千鸦杀4k
115://Love.of.Thousand.Years.2020.E10.WEB-DL.2160p(4K).H265.AAC-Amber.mp4|3234162645|E0E5972711CCF94FBA122001A064DB2BCA3F1F45|D4FB201E1A5A5B6065F18411D61102AD8DA651AF|三千鸦杀4k
115://Together 2020 E01 Web-dl 4K H265 AAC-Amber.mp4|1126915728|7FF0041FEA6707ED3D7A44984009BF4F00BCDA9C|18DF8640582FF98E0B224354DA367B2CCCC7A8D3|在一起4k
115://Together 2020 E19 Web-dl 4K H265 AAC-Amber.mp4|1639147614|02D1CAC6A373B726B09966913F1FB764D46E64DD|1F3A3722CA7A89CFD84809506C21A84BA1BCBDE8|在一起4k
115://Together 2020 E18 Web-dl 4K H265 AAC-Amber.mp4|1563189895|33BFA14BFB71E111F357CD885D8690969A816837|547E9D699D63DEDBA5CEA24E478AE35CFF0653E5|在一起4k
115://Together 2020 E17 Web-dl 4K H265 AAC-Amber.mp4|1533913151|9718313054029073A47EF241BD2C0757B398179B|6D8CA6D2770F5931BB5D20E67FFC5C018F9AF456|在一起4k
115://Together 2020 E16 Web-dl 4K H265 AAC-Amber.mp4|1564738000|28904254CA99EB33E4A3844F5BA6B7D76E4C80DE|87458D59C9CFBE522492D31E142ACE4AB108188C|在一起4k
115://Together 2020 E15 Web-dl 4K H265 AAC-Amber.mp4|1452598571|A9CC418974EB01DBA5B9650B05D75906A0687B06|1905D2893757F58DBC81BC6B040A8794BAC588A6|在一起4k
115://Together 2020 E14 Web-dl 4K H265 AAC-Amber.mp4|1600823864|E5FE22E38E926D209CB94390B15AFFF1003CC757|981AB24755251D295E61F8A40C81BDC5CE943577|在一起4k
115://Together 2020 E13 Web-dl 4K H265 AAC-Amber.mp4|1345266456|73A4B312DB13437716A7305E78E32B66139CE3AD|806EE1BA66C4CA564761B64FF0BDF7E0F2993CF5|在一起4k
115://Together 2020 E12 Web-dl 4K H265 AAC-Amber.mp4|1250214065|B165C1D07D9C1575487DC742EBEDD32F3A2B7482|F5C4B54CF7779B3713469F38874EB80182E67B72|在一起4k

**Comment by liupan1890** [comment]
足够了，只是用来测试，有几条就够了，预计会在本周日跟随秒传链接功能一起上线

**Comment by liupan1890** [comment]
v1.6.5已经支持批量导入115链接了

但是经过测试，大部分文件都无法直接秒传成功，不是功能的问题，是115网盘和阿里云网盘数据本身并不互通

能够秒传成功，都是因为有别人把这个文件上传到了阿里云网盘了，冷门文件就会失败

测试用例：

``````
115://浪潮之巅第4版.吴军.pdf|9155421|9F204F996CFDE3E5B5125EFC9BCCE928866F4C1E|6D11CAAC5541E382202799CE8F3881E8D0CC06DC
``````

**Comment by LevineWoo** [comment]
强烈建议可以导入百度云的哇。百度云有会员账号。

**Comment by liupan1890** [comment]
> 强烈建议可以导入百度云的哇。百度云有会员账号。

百度不提供sha1码，无法实现此功能的。

**Comment by 69fl** [comment]
失效了诶

**Comment by WHYEX3** [comment]
> 这回复好像附不了文件，115sha1链接我还有很多

大佬有空能否帮个忙离线一下这个磁力链接的115链接，万分感谢
magnet:?xt=urn:btih:9C78DAA6DAD0A295525F67BC96AB81ABA11BE62A
