### ISSUE TITLE
mac版本提示二维码已失效

### ISSUE THREAD

**Issue by liujieyuu** [liupan1890/aliyunpan#111]
mac版本，二维码登录时，提示“二维码已失效”。刷新二维码点击后依然提示二维码已失效。使用cookie登录的时候，提示“登录失败，请重试”

**Comment by liupan1890** [comment]
我测试一下

**Comment by liupan1890** [comment]
我测试了一下我的mac是可以正常登陆的（扫码+Cookie）
然后根据我的经验，只要是Cookie不能登录，就说明是aliserver这个进程崩溃了

小白羊启动时会运行3个进程
参见 https://github.com/liupan1890/aliyunpan/issues/76

你可以试试退出小白羊，然后重新打开

终极的解决方案就是，等我发布下个版本，因为下个版本取消了3个进程，所以不会出现这种问题

**Comment by liujieyuu** [comment]
好的，谢谢，会持续关注你的版本迭代
