### ISSUE TITLE
能不能加入文件及文件夹详细信息统计功能

### ISSUE THREAD

**Issue by QiTianzu** [liupan1890/aliyunpan#112]
像百度云一样可以统计文件类型、位置、大小、修改时间、文件夹包含的文件和文件夹数目等信息。
刚刚上传了两个文件夹，包含139433个文件，3300个子文件夹，查看已上传完的任务个数是142733个，判断应该没有传错，可是因为这是我第一次用小白🐏上传，所以可以把已完成的任务数与上传的文件及文件夹数目进行比对判断传输是否出错，如果不是第一次上传又不记得之前传了多少就麻烦了，所以请考虑加入详细信息统计功能。

**Comment by liupan1890** [comment]
#### 1.像百度云一样可以统计文件类型、位置、大小、修改时间、文件夹包含的文件和文件夹数目等信息。

这个在哪里我可以看到？
我知道在百度云盘PC客户端里，在一个文件夹上右键能显示“文件夹大小和包含N个文件夹N个文件”
但统计文件类型是在哪里看？
位置是什么意思？这个文件夹在网盘里的完整路径吗？


首先是文件夹大小，文件夹内包含N个文件夹和N个文件功能，因为阿里云盘本身并不支持文件夹大小，所以现在是没有的。下个版本会增加这个功能，

统计文件类型,我试试看

位置不知道是什么

#### 2.如果不是第一次上传又不记得之前传了多少就麻烦了
你这样想，每次你执行上传（不管是选择一堆文件上传，还是上传整个文件夹，还是拖放一堆文件夹上传）。

都会创建一堆上传任务---这个一般不会出错，就是读取本地文件目录，所以我还没想到哪里会出错

然后是按照顺序去上传，只要你其中某一个文件上传失败了，在上传中队列中就会显示上传失败和错误信息
并且还会自动重试，重新上传

最后，你会看到上传中队列全是空的


反过来也就是说，你为什么要去统计，分析，是否全部成功上传了呢？你直接看一眼上传中队列不就知道是否全部上传成功了？所以感觉你提的功能跟你的上传操作，一点关系都没有啊

**Comment by liupan1890** [comment]
另外提示一下，当前如果你使用阿里云盘网页版，或者阿里云盘PC版，重复上传同一个文件，是会自动重命名的。

小白羊则是自动覆盖的

例如：
你上传D:\电影\xx.mp4到 网盘的'Move'文件夹，重复上传3次
如果是阿里官方，就会得到：move/xx.mp4,move/xx_20210715_97866.mp4,move/xx_20210715_54346.mp4 共3个文件

如果是小白羊，只会得到 move/xx.mp4一个文件

**Comment by liupan1890** [comment]
文件夹大小显示和统计功能已在v2.8.1.pre里实现
