### ISSUE TITLE
希望播放器可以换成MPV-EASY-Player，比较好操作一些

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#113]
https://github.com/422658476/MPV-EASY-Player
![MPV-EASY-Player](https://user-images.githubusercontent.com/38945550/125794800-463b97fb-f82d-4435-b83f-668f0734df17.png)

**Comment by liupan1890** [comment]
我不确定MPV-EASY-Player是否可以通过cmd命令传参启动。稍后我研究一下，争取替换掉windows上的mpv。这个issue别关，因为在做2.0版，会比较慢

**Comment by iD2073** [comment]
1.6.29版本中的播放器，太简陋了，在网上查询了快捷键，但是很多快捷键都不知道起什么作用，经常使用的制定功能快捷键也是失效的，很期待下个版本能解决这个问题，感谢liupan1890

**Comment by 232490026** [comment]
希望可以自己指定播放器打开,比如Mac下的IIna

**Comment by liupan1890** [comment]
已测MPV-Easy-Play不支持cmd命令，v2.8.1.pre开始已经整合了Potplayer皮肤

@iD2073 置顶快捷键是T，我在我的电脑上测试有效，已经在新版的设置里增加了常用快捷键的说明，之后还会再帮助里增加快捷键说明

@232490026 阿里云盘限制了下载链接使用时必须附带引用头，iina我不知道是否支持，我感觉是不支持的，因为iina是对mpv的封装，封装后很多命令行参数都不支持了，我稍后去测试一下，如果可以的话会增加iina的调用设置项
