### ISSUE TITLE
v1.6.29 阿里云分享链接导入失败

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#114]
![微信图片_20210715192247](https://user-images.githubusercontent.com/38945550/125798578-1973d31a-955f-4f53-85c1-e6e54748849f.png)

**Comment by liupan1890** [comment]
我抓包看了一下，并不是特例，是阿里云盘升级了分享接口（分享功能刚刚公测了，并且支持文件夹分享了），导致小白羊失效了

我会在下个版本修复此问题。这个issue先别关

**Comment by liupan1890** [comment]
在v2.8.15里已经修复了此问题，可以正常的导入阿里云盘的分享链接了，也支持包含文件夹的分享链接
