### ISSUE TITLE
希望能增加批量重命名中的数字序列号功能

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#116]
比如输入1.jpg   后面的文件就自动为   2.jpg    3.jpg  ……      如果输入    0001.jpg     后面的文件名就为  0002.jpg    0003.jpg  ……    辛苦了小哥

**Comment by liupan1890** [comment]
收到，明白，会安排！

**Comment by liupan1890** [comment]
批量重命名增加序号功能已在v2.8.28里提供
