### ISSUE TITLE
希望作者能提供一份阿里云盘接口文档？

### ISSUE THREAD

**Issue by wolong438** [liupan1890/aliyunpan#117]
作者能否提供一份阿里云盘的接口文档，我也想用阿里云接口写一个java版本的云盘练练手。很佩服作者能搞到阿里云盘的接口，厉害了。

**Comment by liupan1890** [comment]
我也没有阿里云盘的官方接口文档

我都是用Fiddler抓包，阿里云盘网页版，总结的

因为当前阿里云盘还在公测期间，接口参数时有改动，所以还是推荐你自己抓包看一下。另外所有的接口详细的调用参数都在
aliyunpan/aliserver/aliyun/
这个文件夹里，你一看就知道了，并不需要我一个一个的整理出具体的文档，看代码就知道了

**Comment by wolong438** [comment]
好的，非常感谢~
