### ISSUE TITLE
视频播放的时候左上角的标题能不能显示播放文件的名字，不然有时候自己都忘了看到哪一集了。

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#118]
![1626694609(1)](https://user-images.githubusercontent.com/38945550/126154678-f937db27-4a13-419e-b290-eea99a7268ef.png)

**Comment by WHYEX3** [comment]
![(YFO%MRPO34~GF@}3Y2(20](https://user-images.githubusercontent.com/47862806/126178338-c455ab02-3673-4bf7-b77b-8854b532b442.png)
我这里是电影有标题，普通视频没有标题

**Comment by liupan1890** [comment]
收到，我需要查一下mpv播放器是否支持设置标题的参数

1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的

2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）

3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了

**Comment by DifferentSparkler** [comment]
> 收到，我需要查一下mpv播放器是否支持设置标题的参数
> 
> 1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的
> 
> 2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）
> 
> 3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了

感谢大神认真的查看我们这些用户提出的一个个无理要求，并一一作出解答，请收下我的膝盖，一个人就写了比官方还好用的软件，可以@一下阿里官方，看看能不能加入官方团队。

**Comment by WHYEX3** [comment]
> > 收到，我需要查一下mpv播放器是否支持设置标题的参数
> > 1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的
> > 2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）
> > 3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了
> 
> 感谢大神认真的查看我们这些用户提出的一个个无理要求，并一一作出解答，请收下我的膝盖，一个人就写了比官方还好用的软件，可以@一下阿里官方，看看能不能加入官方团队。

#50 #53

**Comment by DifferentSparkler** [comment]
> > > 收到，我需要查一下mpv播放器是否支持设置标题的参数
> > > 1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的
> > > 2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）
> > > 3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了
> > 
> > 
> > 感谢大神认真的查看我们这些用户提出的一个个无理要求，并一一作出解答，请收下我的膝盖，一个人就写了比官方还好用的软件，可以@一下阿里官方，看看能不能加入官方团队。
> 
> #50 #53 事实上阿里已经主动找来过了

你是怎么知道的？

**Comment by WHYEX3** [comment]
> > > > 收到，我需要查一下mpv播放器是否支持设置标题的参数
> > > > 1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的
> > > > 2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）
> > > > 3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了
> > > 
> > > 
> > > 感谢大神认真的查看我们这些用户提出的一个个无理要求，并一一作出解答，请收下我的膝盖，一个人就写了比官方还好用的软件，可以@一下阿里官方，看看能不能加入官方团队。
> > 
> > 
> > #50 #53 事实上阿里已经主动找来过了
> 
> 你是怎么知道的？

#43 你看这3个issue都是阿里官方人员留的

**Comment by DifferentSparkler** [comment]
> 收到，我需要查一下mpv播放器是否支持设置标题的参数
> 
> 1.在下一个版本里，可以自由的选择是使用阿里云盘的在线预览，还是调用MPV播放，阿里云盘是会显示视频标题的
> 
> 2.在下个版本里，会修正偶发的，看视频时，文件的选中状态丢失的BUG，就是说，当你看完这一集，回到小白羊，这一集的文件还是保持选中状态不会丢失（当前偶尔会丢失选中状态，丢失了就真的不知道刚才看的是哪一集了）
> 
> 3.在下个版本里，增加了文件名颜色标记功能，所以比如你今天看了N集，不看了，要休息了，就点一下第22集标记为红色（最多8种颜色可选），这样明天打开小白羊，一眼看到那个红色的文件名，你就知道继续看哪一集了

个人感觉官方的视频预览做的也不好，周围有很大的白边，个人稍微有一点强迫症看着不舒服。最好 是可以自定义调动第三方播放器，感觉potplayer不错，希望大神可以尝试一下。
![image](https://user-images.githubusercontent.com/38945550/126481015-a59be8fd-9c48-4be4-b03c-1736160b7e06.png)

**Comment by liupan1890** [comment]
我会注意去掉白边的

potplayer 不支持定义 referrer 而阿里云盘的下载链接需要这个http头，否则拒绝访问。
仅此一项就绝杀了绝大部分播放软件了

我知道的就只有MPV和MPV的变种软件能够支持

VLC，PotPlayer，迅雷影音，QQ播放器，暴风，等等吧，都不支持设置referrer。所以都不能用

**Comment by iD2073** [comment]
![image](https://user-images.githubusercontent.com/87513821/126581459-f4e22039-e8dd-4acd-9997-2c4bcf3d6104.png)
这个和您说的是一个意思吗？我不太懂啊

**Comment by liupan1890** [comment]
http://223.110.xxxxxxxxxxxxxxxxxx/index.m3u8

这个是url，也就是说这里可以填阿里云网盘里文件的URL

比如你这个url，填了就能播放了

但是换成阿里云盘文件的url，就不能播放，因为阿里云盘拒绝访问
需要在http请求头同附带 referrer: https://www.aliyundriver.com 这句话才行
Potplayer不支持自定义附带这一句话

**Comment by liupan1890** [comment]
MPV播放时显示的文件名已在v2.8.1.pre里修正
