### ISSUE TITLE
建议增加“区间选择”功能

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#119]
在选择中，可以增加全选，反选，特别是“区间选择”功能，比如，选择第一个文件和第九个文件再按“区间选择”键就会把1和9之间的所有文件并包括1和9全部选上，结合键盘上的Shift和Ctrl键+鼠标也可以做选择操作，脱离Shift和Ctrl键只用鼠标也可以进行选择操作，

![image](https://user-images.githubusercontent.com/87513821/126297797-63dd6f89-abf8-4e60-8f25-98078186ae85.png)

**Comment by liupan1890** [comment]
选择第一个文件和第九个文件再按“区间选择”键就会把1和9之间的所有文件并包括1和9全部选上


当前v1.6.29本身就支持了点击1，按住shift，点击9，自动全选1-9

结合键盘上的Shift和Ctrl键+鼠标也可以做选择操作

当前v1.6.29本身就支持了常规的ctrl。shift键支持，跟windows上的文件管理器里操作一样


脱离Shift和Ctrl键只用鼠标也可以进行选择操作，

当前不支持，但计划在2.0版本里会跟阿里官方一样，支持鼠标拖选，不需要按键盘
只是开发进度很慢，现在没有上线而已，v1使用的flutter原生不支持鼠标拖选

1.所以区间这个按钮就没用了，不如shift或者鼠标拖选更加习惯
2.全选按钮也没有用了，因为当你点击“已选中 1/20”前面的蓝色小圆点，就是全选，如果已经全选就是全部不选

这个v1.6本身就是支持的

so，，，只有一个反选按钮是当前没有的功能

但是，反选====全选+按住Ctrl点击要去掉的文件。所以反选按钮实际也不需要，只是操作逻辑问题

**Comment by iD2073** [comment]
您可能很少实用这三个功能，但是在现实中，我是经常使用的，  比如在100张相片中选择10张不想要的相片，这样就可以先选中不要的，但是10张可不一定都是连续挨着的，这样前面的选择按钮就至关重要，如果采用键盘你就要用另一只手按住键盘功能键，有的时候如果不慎松开功能键，可能还要重新选择，如果采用我说的方式，单手一个鼠标很快找到不想要的相片然后反选这样就可以选中想要的相片，，，我觉得不如两种方式都保留最好，因为，全选，区间选，在整理文件中太实用了，

**Comment by iD2073** [comment]
在Directory Opus 这个资源管理器中，我说提议的功能都有，有的时候一只手啃着鸡腿，另一只手整理文件一点都不耽误事儿，反而电脑自带的那种需要按键盘的方式，有时确实不方便，一只手拿着东西，或端着一杯水，整理起文件总要拿起放下，总之在很多场景下，一个鼠标搞定的确实要比还要另一只手配合更便捷和方便，可能你没有习惯，比如晚上只有屏幕有光的时候，键盘上的按键上的按键都怕按错，

**Comment by iD2073** [comment]
区间是很实用的，比如有500个文件， 需要使用第50号文件到200号文件，先点选一个第50号文件   然后用滚轮滚动到第200号文件然后选中，点区间选，这样就选择上了需要的文件，当然结合键盘一样也可以选，如果此时你的另一只手在接电话或正在通过电话让你寻找网盘里的文件，这时候你的另一只手只能忙得不亦乐乎了，就是因为现实场景中，我遇到这样的事太多了，所以我比较强烈建议吧，再说我们是免费用你的软件，并不强求尊重你的选择，总之非常感谢你的付出和努力。

**Comment by iD2073** [comment]
框选确实很方便，但是有时也有不方便的地方，比如有500文件，每页显示100，要选择前150个文件，用框选按住鼠标左键向下拖当鼠标到达页面底部的时候视图会自动翻页，有的时候拖的太过可能会直接翻到第三页，这个时候还需要往回返很不方便，这也是框选的弊端，框选在当前页面选择时确实是最好的选择方式，但是遇到翻页的框选可能会不太方便。

**Comment by liupan1890** [comment]
你说得对，我日常基本用不到选择文件的功能，所以根本体会不到你的情景

#### 我用阿里云盘，并不是工作用，只是日常生活用。
比如看个电视剧（不需要多选文件，看哪集点哪集），下个游戏（整个文件夹下载），备份手机相册（整个文件夹下载）。我根本没有遇到过需要在一个文件夹里选择一部分文件下载的时候，就算偶尔遇到了，也是比如一堆视频+一个文本，直接全选，然后按一下Ctrl点击一下文本---只需要排除这一个文件

所以我根本不了解你需要区间功能做的事，没有这个体会，就感觉不重要。反过来如果我平时用到了，就会感觉很重要


#### 100张相片中选择10张不想要的相片
按一下全选，按下Ctrl，依次点击这10张，不能松开Ctrl。这个很难做到吗？

#### 你的另一只手在接电话或正在通过电话让你寻找网盘里的文件
因为我确实不是经常需要选择文件，所以体会不到你说的这一点，你是不是做设计的啊，需要整理很多图片？


#### 但是区间怎么定义呢？
我没用到过所以得详细的问一下，区间是怎么定义的
1.点击第一张。2，按住Ctrl点击第50张（必须按Ctrl），3.点击区间，自动勾选1-50
4.按住Ctrl点击第80张，5。按住Ctrl点击第100张，6点击区间。自动勾选80-100张

最终勾选了：1-50，80-100是吗？

因为当前想要多选必须按下Ctrl键，这样看就不合理了。看来我应该增加一个多选模式的按钮，点击多选模式后可以随意的点击增加选中文件。非多选模式下，点击就会自动取消其他文件的选中---当前指会这样必须按Ctrl才能增加选中


我稍后下个Directory Opus看看吧

**Comment by iD2073** [comment]
就是这样的操作，单手鼠标操作非常方便，我发的界面是手机版的“ES文件浏览器”。阿里云盘小白羊虽然后续的版本在单个页面可以用鼠标框选，但是区间选在选更多文件的时候就非常实用了，经常旅游拍照的用户往网盘里传相片，可以方便的整理相片。

你真猜对了，我是做设计的。   

![SVID_20210721_181800_1 mp4_20210721_184820](https://user-images.githubusercontent.com/87513821/126477009-afa58552-4c29-4274-8b35-40fb82c6ec54.gif)

**Comment by iD2073** [comment]
如果能把阿里云盘接入  Directory Opus 这个软件那就太牛了，不过不太可能。所以希望阿里云盘小白羊版，实现Directory Opus的大部份功能，同时可以管理本地磁盘文件和云盘文件，让用户使用阿里云盘就像用本地磁盘一样，那简直无敌了，偷笑

**Comment by iD2073** [comment]
Directory Opus 是收费软件，资源管理这方面是超级强，很多地方值得借鉴

**Comment by liupan1890** [comment]
等等我吧，我之后会研究一下这个软件，借鉴一下。现在还是在忙v2的制作。

**Comment by iD2073** [comment]
辛苦，辛苦，小哥

**Comment by liupan1890** [comment]
区间选择已在v2.8.28里提供
