### ISSUE TITLE
文件名排序的问题

### ISSUE THREAD

**Issue by Theergold** [liupan1890/aliyunpan#12]
![image.png](https://i.loli.net/2021/06/01/m5pNit1g3vLqVcA.png)
希望这些文件按照数字顺序排序而不是从先把开头是1的排一起然后再排开头是二的

**Comment by liupan1890** [comment]
收到，
当前排序问题，是因为直接采用的阿里网盘的按名称排序结果，我没注意到他不太准确，稍后我会试一下编写新的排序算法，实现正确的排序

**Comment by liupan1890** [comment]
已经基本修正了，试一下，有问题就继续发新的issue
