### ISSUE TITLE
建议新增“新建当前日期时间文件夹”

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#120]
建议新增“新建当前日期文件夹”在工具栏只显示“新建”点击后出现下拉菜单会有“新建文件夹”和“新建日期文件夹”对于需要按时间管理文件的朋友，非常实用，如下图

![image](https://user-images.githubusercontent.com/87513821/126304870-728b2815-6d38-40ed-a03f-7e387bcf8431.png)

**Comment by liupan1890** [comment]
收到，安排上！
但是感觉不如直接在点击创建文件夹按钮后，在输入框里自动填上日期方便

1.你的截图，是有一个下拉菜单，选择2个按钮之一，并且名称是固定死的（年月日时分秒）
所以操作时，1，点击下拉，2.点击新建日期文件夹。

2.我想的，是有一个下拉菜单，选择2个按钮之一，点击日期文件夹后，弹窗里，输入文件名的地方自动填写好了年月日时分秒
所以操作是，1.点击新建。2.点击确定//或者手动删除时分秒改格式 2.点击确定

你怎么看？

**Comment by iD2073** [comment]
> 收到，安排上！
> 但是感觉不如直接在点击创建文件夹按钮后，在输入框里自动填上日期方便
> 
> 1.你的截图，是有一个下拉菜单，选择2个按钮之一，并且名称是固定死的（年月日时分秒）
> 所以操作时，1，点击下拉，2.点击新建日期文件夹。
> 
> 2.我想的，是有一个下拉菜单，选择2个按钮之一，点击日期文件夹后，弹窗里，输入文件名的地方自动填写好了年月日时分秒
> 所以操作是，1.点击新建。2.点击确定//或者手动删除时分秒改格式 2.点击确定
> 
> 你怎么看？

我截图的那个“新建时间文件夹”上的时间是根据电脑系统时间自动生成的，只要一点击就自动生成了， 或者就有一个按钮，点击后弹出两个选项：1新建普通文件夹 2新建时间文件夹    选择1后要求输入文件夹名称    选择2在目录下自动生成 年月日时分秒的文件夹名

**Comment by iD2073** [comment]
或者在弹出需要输入文件夹名字的地方右侧加入一个插入当前日期的按钮，这样也可以，比如输入“张老三”然后按插入日期按钮，就会在文件夹名后加入一个时间，就会生成一个“张老三 2021-07-21 08-54-00”文件夹，如果不输入文件夹名，直接按确定按钮以当前时间为文件夹名，这样更方便

**Comment by liupan1890** [comment]
明白

**Comment by liupan1890** [comment]
已增加此功能
