### ISSUE TITLE
批量重命名只有替换功能，能不能添加增加功能

### ISSUE THREAD

**Issue by liveskai** [liupan1890/aliyunpan#121]
# 比如所有文件名最后都加上TXT

**Comment by iD2073** [comment]
这个可以替换的，比如1.jpg   你可以在批量改名时，前面输入“.jpg”  后面的输入“.jpg.txt”这样改就都加上txt了

**Comment by liupan1890** [comment]
当前v1.6的批量改名里，默认直接使用的js正则表达式替换
是支持增加前缀的，但不支持增加后缀，所以可以如上@iD2073 通过替换，变相的增加后缀

在v2的规划里，批量改名会改的简单一点，
1.可以直接选择 增加前缀/增加后缀/文字替换
2.可以选择使用正则表达式替换

也就是会增加你要的直接加后缀，等我慢慢实现！

**Comment by HUD-A** [comment]
类似与powertoys吗？

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/126456236-dc183580-31f4-4195-8344-d43448e5341a.png)

对，功能可能没有它这么全，等我做到了这里的时候再细研究

**Comment by liveskai** [comment]
> 这个可以替换的，比如1.jpg 你可以在批量改名时，前面输入“.jpg” 后面的输入“.jpg.txt”这样改就都加上txt了

# 文件名后缀都不一样就没法改

**Comment by liveskai** [comment]
> 当前v1.6的批量改名里，默认直接使用的js正则表达式替换
> 是支持增加前缀的，但不支持增加后缀，所以可以如上@iD2073 通过替换，变相的增加后缀
> 
> 在v2的规划里，批量改名会改的简单一点，
> 1.可以直接选择 增加前缀/增加后缀/文字替换
> 2.可以选择使用正则表达式替换
> 
> 也就是会增加你要的直接加后缀，等我慢慢实现！

# 后缀名都不一样无法改

**Comment by hummersyk** [comment]
用正则表达式替换的方式是可以增加后缀的，美元符号$就表示字符串的末尾位置，替换它就行了。

也就是说：左边就填一个英文符号$，右边填txt，就是楼主想要的效果了。

**Comment by liupan1890** [comment]
碉堡了，我竟然忘掉了批量重命名的扩展名前后增加字符的功能，下个版本会增加

**Comment by liupan1890** [comment]
已经在v2.8.30里提供此功能
