### ISSUE TITLE
[新功能]如果能添加查看文件夹大小和文件数的话，那将会绝杀

### ISSUE THREAD

**Issue by HUD-A** [liupan1890/aliyunpan#122]
或许可以再添加一个类似这个https://github.com/KDE/filelight/项目的功能（

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/126456846-fba8a00b-6b0f-486e-8e82-6ce3416975c6.png)
https://github.com/liupan1890/aliyunpan/issues/112

**Comment by liupan1890** [comment]
filelight，这个需要加个chart插件了。关键是文件统计起来，需要执行很长时间，我不知道这个功能是否有用，这个功能稍后再考虑吧

**Comment by Sailing168** [comment]
这个文件夹大小统计功能有必要的

**Comment by liupan1890** [comment]
> 这个文件夹大小统计功能有必要的

看图，已经做出来了啊

**Comment by ayacnc** [comment]
是新版的功能吧？1.6.29没找到

**Comment by liupan1890** [comment]
文件夹大小显示和统计功能已在v2.8.1.pre里实现
