### ISSUE TITLE
BUG反馈：从托盘打开程序的时候，程序不显示内容，直到鼠标移动上去

### ISSUE THREAD

**Issue by zw9629** [liupan1890/aliyunpan#125]
![bug](https://user-images.githubusercontent.com/31214590/126452428-40ff20aa-5372-4501-a92f-b46d09e0317c.gif)

**Comment by liupan1890** [comment]
这个是Flutter本身的问题，他对桌面消息处理的不及时，就是说，窗口显示了，应该收到了显示消息，程序应该会立即刷新UI

但Flutter对桌面支持不好，最基本的消息处理，不知道为什么就是不处理，要等几百毫秒才会刷新

下个版本已经切换到electron了，虽然托盘打开时也会闪一下屏，但是比Flutter反应快，很快会刷新了，基本可以忽略掉

so。。。等我下个版本就好了

**Comment by zw9629** [comment]
实在不想用electron版，内存占用大得离谱，程序磁盘占用也大，作者有没有想法考虑用go+sciter，sciter是个用html、css、js绘制用户程序的DirectUI（windows版）也支持MAC，底层用的其他技术技术，上层接口是一样的

**Comment by zw9629** [comment]
> 这是一时糊涂的问题，他对桌面消息处理的不及时，就是说，窗口显示了，应该收到消息了，程序应该立即刷新UI
> 
> 但 Flutter 对桌面支持不好，基本的消息处理，不知道为什么就是不处理，要等员工支持刷新
> 
> 下个版本已经到了电子了，虽然我自己打开时也会闪一下屏幕，但同时也会闪一下，快速反应，更新会更新，基本可以忽略掉
> 
> 所以。。。等我下个版本就好了
electron不好用。

**Comment by liupan1890** [comment]
1.Sciter 的体积是10MB以上，之前研究过
2.Flutter是谷歌推出的，并且推出2年了，推出桌面版本也将近一年了。然后，真的问题很多，非常多的最基本的东西Flutter没有完善，就我之前发布的7/8个版本，每一次Flutter版本更新发布，我都要自己替换掉Flutter源码里的滚动条源码，因为Flutter的滚动条没有适配桌面版本，一年了，滚动条，不适配。所以我是对Flutter很失望了，再加上之前测试linux版本，基本的界面都显示不全，感觉因为不是亲儿子，真的不受重视

3.Sciter 发布印象里也有好几年了，好几年了，之前做过Sciter 的程序，但是是纯粹的Sciter +JS的，没有配合go
我对这个的印象就是非常难开发，是指的工具不完善。不是指代码很难写。对Flutter失望后我需要快速的切换，Sciter 并不合适。另外弃用Flutter的另外一个特别重要的原因，特别重要比Flutter不完善还重要：：golang报毒

就是这么简单的小程序，也没有调用几个系统API，也没有自动更新功能，win10,win11都有报毒。我没法解决。因为这不是技术的问题，不是我修改源码的问题，是我没有像微软提交认证，没有像全世界几十种杀毒软件的官方网站提交资料认证

报毒导致一般的用户都无法使用了，至少有一半的用户不会设置/不能设置/懒得设置/杀毒软件信任

换成Sciter 配合golang，也会遇到报毒这个问题。只用Sciter 开发也一样，只用Flutter开发也一样，我绕不开误报的问题，我也不知道怎么解决误报

换成Electron就不一样了，不会误报。因为我会套用签名后的Electron，杀软一看就会自动信任，不会有误报


不知道其他人开发桌面程序是怎么做到不被误报的。

**Comment by liupan1890** [comment]
@zw9629  electron不好用

阿里云盘官方就是用的electron
另外，我常用的软件基本都是electron了
腾讯微云网盘也是，VSCode也是，QQ音乐/微信也用的CEF，感觉现在已经被chrome一统江湖了

**Comment by zw9629** [comment]
好的，我只是给个建议，真选择什么还是你自己定。
