### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by 812012566** [liupan1890/aliyunpan#127]
请问一下，打开黑屏怎么解决呢

**Comment by liupan1890** [comment]
这个问题第一次有人问，我之前也没遇到

黑屏是指真的黑屏没有任何文字，还是黑色命令框一堆文字？

索性预计这周日会发布v2，干脆直接用新版吧

v1.xxx 版本使用的Flutter
v2.切换为Electron了，虽然第一个版本功能还很简陋，但也可以试试看，功能以后会慢慢完善

**Comment by 812012566** [comment]
没用任何文字，第一次用就打不开，window7，另外一台电脑win7可以用，这个不知道怎么回事，希望周日的可以用，谢谢

**Comment by HHLT666** [comment]
win7旗舰版sp1，打开软件窗口全是黑色。

**Comment by liupan1890** [comment]
已经确认是Flutter本身的BUG，无法修复，请尝试v2.8.8 切换为electron就正常了
