### ISSUE TITLE
期待离线功能 急需

### ISSUE THREAD

**Issue by kahnli** [liupan1890/aliyunpan#128]
大概什么时间可以实现？老大，这个功能急需 

目前有什么可以代替的么？求推荐

**Comment by iD2073** [comment]
不是说6盘可以离线的吗？我用的离线是奇他网盘。离线可能是要看阿里支不支持，阿里不支持也不好实现

**Comment by QiTianzu** [comment]
> 不是说6盘可以离线的吗？我用的离线是奇他网盘。离线可能是要看阿里支不支持，阿里不支持也不好实现
6盘凉了

**Comment by liupan1890** [comment]
115，比特球

我现在真的来不及做离线，离线被安排在很晚很晚了，
本来v1功能差不多了，马上就轮到离线了，但是我🗡啊，不满意啊，切换Electron追求完美啊，折腾一个月还没重新做完v1的所有功能，所以离线功能，还有同步盘，重复文件扫描等等，都被延后了，如果你是现在急用，不要等我啦，短期内不可能上线的

**Comment by kahnli** [comment]
好可惜...最常用的一个功能

**Comment by wg96644364** [comment]
离线功能确实是挺实用的，不过还是一步步稳扎稳打好，期待作者一步步完善

**Comment by masss1** [comment]
期待大佬的离线功能
