### ISSUE TITLE
严重错误::无法连接到后台进程!!请退出程序后重新打开

### ISSUE THREAD

**Issue by QiTianzu** [liupan1890/aliyunpan#129]
![image](https://user-images.githubusercontent.com/50047003/126886090-ba417662-9955-46d3-8bd9-8b6b3a50ad27.png)
![image](https://user-images.githubusercontent.com/50047003/126885881-fd075bac-b8d7-4d89-ae53-32b3e9f6a1b4.png)
![126885944-7fa7416e-0388-44f6-826e-2ed43cd337ed](https://user-images.githubusercontent.com/50047003/126890569-b8f45ebb-7b41-4409-b1c0-a287a0cc63d8.png)
user.db有一百多兆大，把它删掉后再打开小白羊会重新生成一个新的，小白羊就能成功启动了，是因为传输任务列表里的历史记录太多了吗？

**Comment by QiTianzu** [comment]
![屏幕截图 2021-07-25 110222](https://user-images.githubusercontent.com/50047003/126886277-c0f1337d-c047-413a-b798-7eb627482bd3.jpg)

**Comment by liupan1890** [comment]
是的，因为当前采用的数据库是json数据库，如果你的上传任务很多，并且没有及时的清理  已上传完 里面的列表，会导致数据库文件体积很大，进而会导致启动很慢--需要完整的读取+解析所有的100MB的数据

在v2切换为indexedDB了，就不会有这个问题了
