### ISSUE TITLE
关于长图片预览放大倍数有限的问题

### ISSUE THREAD

**Issue by WHYEX3** [liupan1890/aliyunpan#13]
![image](https://user-images.githubusercontent.com/47862806/120337419-e1892580-c325-11eb-9305-2d28ccfbb869.png)
如图，对于长图片的预览最大只能到这样的大小，希望可以加一个自定义放大倍数的功能

**Comment by liupan1890** [comment]
嗯，实际上是因为flutter对滚动条的设计，我不是太习惯，预览我也没想这么多。。。。

稍后会先调整一下预览的放大倍数（当前是2倍，先调整为4倍）
之后会仔细的调整一下图片预览功能，现在的太简陋了，时间太赶，多包涵

**Comment by omy2000** [comment]
支持大佬

**Comment by liupan1890** [comment]
v1.6.5修正了此问题
