### ISSUE TITLE
软件支持32位吗？

### ISSUE THREAD

**Issue by bulabulalaen** [liupan1890/aliyunpan#130]
请问软件支持win10的32位吗？我调用任务管理器看的话好像不是32位的。

**Comment by liupan1890** [comment]
v1.6.29使用Flutter开发，不支持任何32位系统
v2.xxx切换为electron，会支持32位win7-win10

**Comment by bulabulalaen** [comment]
> v1.6.29使用Flutter开发，不支持任何32位系统
> v2.xxx切换为electron，会支持32位win7-win10

好的，感谢！
