### ISSUE TITLE
能否考虑提供排序选项，按名称排序时将文件夹视作文件一起排序

### ISSUE THREAD

**Issue by Anza7i** [liupan1890/aliyunpan#131]
目前情况好像是特殊处理排在首位

**Comment by iD2073** [comment]
这个应该加个勾选项，正常需要这种选项的情况比较少，有总比没有好，期待

**Comment by Anza7i** [comment]
> 这个应该加个勾选项，正常需要这种选项的情况比较少，有总比没有好，期待

是的，希望作者大大能加上

**Comment by liupan1890** [comment]
收到，安排，在v2里会在设置里面增加选项，可以自己选择文件夹是否参与排序

这样用到了就设置开启，不用了就关闭。默认是关闭的。

**Comment by Anza7i** [comment]
> 收到，安排，在v2里会在设置里面增加选项，可以自己选择文件夹是否参与排序
> 
> 这样用到了就设置开启，不用了就关闭。默认是关闭的。

谢谢作者，辛苦了。另外想请教下txt秒传成功的条件是只要 文件大小 和 sha1 这两个因素符合吗，传入的文件名会影响结果吗

**Comment by liupan1890** [comment]
最开始，我测试的是，传入的文件名对秒传操作无影响，阿里云盘官方api并不限制文件名，你传入什么文件名都可以成功

不过，我发现在创建文件夹时，
在最开始，阿里云盘对文件名中有路径分隔符'/' 时，并不特殊处理，所以你可以叫 ‘aa/bb’ ，这是一个文件夹的名字
不知道什么时候，阿里云盘升级为对路径分隔符进行处理，如果你传入'aa/bb' ，阿里云盘会创建'aa' 和'bb' 2个文件夹

所以如果你的文件名中包含 路径分隔符，我最近也没测试是否对秒传有影响


上面说的是秒传接口

然后就是解析秒传文件

如果你的文件名中包含特殊字符（比如一些不可见字符），可能生成秒传txt时，会导致最终导入时因为特殊字符的缘故格式化出错，最终导致导入秒传txt失败。这个我会再新的版本里注意这个问题。

**Comment by liupan1890** [comment]
文件夹参与排序功能已在v2.8.1.pre里实现
