### ISSUE TITLE
保险箱

### ISSUE THREAD

**Issue by int0828** [liupan1890/aliyunpan#132]
为什么不能使用保险箱

**Comment by liupan1890** [comment]
1. 我很重视保护用户的隐私
所以当前软件并没有上传数据的操作，以后当然也不会有（1.在解析秒传链接时需要上报秒传链接进行解析，2.在导入秒传链接时可以主动勾选上报分享链接数据，3.在用户使用聚合搜索时，需要上传搜索关键字），保护用户的隐私是基本的操守


2. 如果有人说我泄露了他的隐私怎么办？
你楞说就是因为用了小白羊之后隐私被泄露了，我怎么能跟你掰扯清呢？我感觉掰扯不清，有的人不讲理


3. 保险箱  小白羊以后也不打算增加保险箱功能
保险箱，更加涉及到用户的隐私了，我不敢增加这个功能，我怕以后真的有人自己不小心泄露隐私了，来跟我纠缠。为了杜绝这种情况，我就压根不提供任何保险箱相关的功能，这样，也就彻底无话可说了


所以，请谅解，不敢做。也请相信，我明白隐私的重要性，我不会去侵犯任何人的数据或隐私
