### ISSUE TITLE
秒传导入文件夹下无文件

### ISSUE THREAD

**Issue by liuweibangong** [liupan1890/aliyunpan#133]
请老师看看，我的秒传生成到一个txt  然后导入到另外的账号，可以建立文件夹，但是文件不导入。

**Comment by liupan1890** [comment]
我去试试，稍后回复

**Comment by liupan1890** [comment]
我刚刚测试

112个文件 84.6GB 生活大爆炸1-5季.1080P.H265.非凡科技

一个账号创建秒传txt

登陆另外一个账号，导入秒传txt

是可以正常导入的，所以功能是正常的

当你导入时，所有的文件，会显示在 “上传中” 页面里，一个一个的上传（秒传），成功或者失败都有显示

如果这个文件成功上传，就会移动到 “已上传”页面，如果这个文件上传失败，就会显示错误信息

所以你先看一下错误信息，再回复我。可能跟你的文件有关

如果在上传中和已上传都没有显示任何文件，可能是你复制秒传txt的内容时复制的不完整，格式不正确导致解析失败

总之：需要你回复详细的信息，我才能进步一部分析
