### ISSUE TITLE
文件计算sha1未结束时，移除任务，任务会在后台继续运行

### ISSUE THREAD

**Issue by Anza7i** [liupan1890/aliyunpan#134]
退出程序后，任务管理器中的磁盘占用恢复正常。

另外，当使用机械硬盘时，多个任务同时进行读取计算sha1，由于机械硬盘特性，速度下降得很厉害（190M/s => 30M/s），是否需要增加一个选项，当队列中任务有大于某个阈值（如1G）的任务进行计算时，其它大于阈值的计算任务等待，小文件按原先的来。用户可按自己的硬盘自行勾选。

降速是在本人电脑上测试的结果，不确定是否因为是SMR硬盘老化的问题，待确认。

**Comment by liupan1890** [comment]
文件计算sha1，有2处，第一是你勾选了下载完成后校验文件。第二是上传文件前计算sha1

##### 针对下载完成校验
当前是调用aria下载并直接校验，也就是aria执行校验操作。所以在执行校验时，无法中止校验。

在v2里改成了自己的校验（并且是先crc64校验，如果不支持---万一以后阿里云盘升级取消了crc64的数据，才sha1校验）
这样减少了CPU计算量，可以微微的加速一点

但默认还是推荐关闭下载后文件校验选项，没有啥作用，文件很少损坏

##### 针对上传前sha1校验--感觉你应该说的是这个
当前阿里云盘强制要求必须先计算出文件的sha1然后再上传（1.为了秒传 2.为了上传结束时校验文件完整性）

…… 移除任务，任务会在后台继续运行 …… 
计算文件sha1时，为了性能，直接采用的文件内存流复制，这个操作不能中止/取消。所以任务会在后台继续运行。

从程序上讲，确实是可以改成分段小内存缓存的方式，计算一部分，检测一下是否退出，再计算一部分这样操作，但会导致计算sha1变慢。

最后，我之后会再想想这里，怎么安排合适

##### 当使用机械硬盘时，多个任务同时进行读取计算sha1，由于机械硬盘特性，速度下降得很厉害

这个是真的，不是你个例。
1.机械硬盘读取小文件，因为寻址，会导致速度变慢
2.机械硬盘读取大文件，因为缓存，会导致前面读取还算快，后来变慢
3.机械硬盘读取多个文件，因为磁头要频繁再多个文件的多个地址切换（这里读一点，转到那边再读一点，时间都浪费在转磁头上面了，导致读取变慢）

这个并没有好的解决办法，软件也无法准确的检测用户是使用SSD还是机械（win上读取注册表可以根据硬盘ID里面的硬盘型号品牌粗略的判断，但读取注册表会被误报为病毒操作）

当你使用机械硬盘上传大量大文件时，应该主动调整同时执行的任务数，比如同时执行3文件。就可以解决这个问题了。跟增加额外一个选项，没有区别。

当你使用机械硬盘上传大量小文件时，可以重新调整为9文件

##### 是否需要增加一个选项，当队列中任务有大于某个阈值（如1G）的任务进行计算时，其它大于阈值的计算任务等待，小文件按原先的来

我明白你的意思，但大部分人不明白这个选项是干啥的，因为大部分时候都是直接仍在那让他自己上传，不会留意校验时间的问题。另外一般人的网络上传速度也就3MB/s，在此前提下，机械硬盘降速也在30MB/s以上，对大文件最终的上传时间，影响不大。上传用了5分钟，校验时快几秒慢几秒感觉不明显，并且是只有多个大文件同一时间启动上传时才可能明显增加几十秒。大部分时候，因为文件都是错开的（这个文件在上传，那个文件在计算）。这个选项优化的效果十分有限，所以就不加了

**Comment by Anza7i** [comment]
1.是的，指的是上传前的校验，我以为sha1计算是每次读取文件的一段并计算的。
2.并行上传的问题，我觉得说的很有道理哈，这种i情况靠限制上传数可以解决。

谢谢作者🤭
