### ISSUE TITLE
115秒传原理探讨

### ISSUE THREAD

**Issue by BrandonStudio** [liupan1890/aliyunpan#135]
## 115的秒传链接为什么能秒传到阿里云盘上？
- 是因为秒传链接对应的文件也被某个阿里云盘用户拥有吗？
    - 能否尝试在115网盘中上传一个随机生成的文件，然后生成秒传链接，测试该链接是否能传入阿里云盘中？由于我不是115网盘用户，因此无法开展此实验。
    - 如果上述实验中随机生成的文件可以传入阿里云盘，有哪些可能？
- 此外，是否可以参考115链接转换原理，通过某个磁力链查询接口解析文件大小并秒传磁力链，从而实现离线下载？

另外，能否打开Discussions？

**Comment by Anza7i** [comment]
我不是作者哈，秒传必须要文件大小和sha1，现有的磁力链查询接口应该做不到查出链内的所有文件信息。

**Comment by Anza7i** [comment]
115的文件能被传到阿里云，我的观点是：
1. 115用了阿里云的对象存储
2. 115秒传链接含有文件大小和sha1信息，满足阿里云秒传接口调用

我的简单测试结果是有1/3的文件无法转存到阿里云，还有待讨论研究。

**Comment by liupan1890** [comment]
1.秒传仅仅是秒传，跟115无关，不要过度猜测
并不是因为115怎么样，阿里云怎么样，所以能秒传导入115的部分文件，纯粹是巧合

2.阿里云盘使用阿里云OSS存储。阿里巴巴公司规模很大，没有必要因为115使用了阿里云OSS就自动的利用这些数据，帮助阿里云盘初始化。我认为这种基本的用户隐私阿里云盘不会去侵犯

3.我认为纯粹是因为当前阿里云盘用户太多，上传的文件太多，所以导致你上传时，会有很多文件可以秒传

4.当前网络中的大部分文件，确实都是重复的，而很少有原创的，我的意思是，比如我是人人字幕，我制作了“XX剧”发出来，结果全网不论你在哪个网站，看到的，搜到的，下到的，XX剧，竟然都是人人字幕制作的这一个文件。因为所有人都是直接复制粘贴，而很少有另外一个字幕组出来重新制作XX剧

5.随机115，应该在阿里云盘无法秒传，因为有很多文件，真的有很多文件，115有，阿里云盘无法秒传，我遇到的太多了

6.仅仅是因为百度云盘使用的是MD5,如果百度云盘也使用sha1，你会发现会有很多百度云盘秒传阿里云盘的脚本了
115一直使用的sha1,所以才有115秒传阿里云盘。就是这么巧合而已。

**Comment by liupan1890** [comment]
1. 磁力链接，是一个bt种子文件的sha1,所以无法使用磁力链接制作阿里云盘秒传连接（没有办法知道文件的sha1+size,知道bt种子文件的sha1+size有啥用，把bt种子秒传到阿里云盘有啥用）

2. bt种子里存储的是一个文件的分段sha1,从技术上无法把分段的sha1合并成完整文件的sha1
形象一点说就是，把一个文件分割成100个小文件，知道这100个小文件每一个的sha1和大小.但是据此不能计算出完整文件的sha1，因为需要完整的文件才能计算他的sha1。

所以，即使有bt种子文件，也无法制作秒传连接

3.唯一的方式就是，知道磁力连接了，解析下载到bt种子，再解析下载完整文件，然后再计算sha1,生成秒传连接（只有阿里云盘存在这个文件才能秒传成功，如果阿里云盘没有这个文件，秒传失败）

电驴连接、http连接、百度分享链接、百度秒传连接 同理，都无法通过技术转换为阿里云盘连接，只能先下载完整文件再去计算

115的分享链接，直接提供了文件的sha1,所以可以把115分享链接直接转换成阿里云盘秒传连接，同样需要阿里云盘已经有这个文件，才能秒传成功

阿里云盘已经有这个文件：：有别的人，已经真的，上传过这个文件

**Comment by liupan1890** [comment]
刚翻了翻才发现原来还有Discussions
不过现在我真的没时间管理啊，以后有时间了再开吧
