### ISSUE TITLE
如何多个分享链接批量保存到网盘？

### ISSUE THREAD

**Issue by bizheyandebing** [liupan1890/aliyunpan#136]
朋友分享的多个链接，如何一次全部保存到网盘中？如：
【01】朱伟专项
https://www.aliyundrive.com/s/
https://www.aliyundrive.com/s/
60课时学完高中英语
https://www.aliyundrive.com/s
2019英语冲刺课
https://www.aliyundrive.com/s/c
2019徐磊
https://www.aliyundrive.com/s/e
2019届高二暑...---罗杰
https://www.aliyundrive.com/s/eH

**Comment by liupan1890** [comment]
当前并不支持批量导入分享链接（实际上单条导入阿里云盘分享链接在近期也因为阿里云盘升级失效了不能正确导入，需要等我发布v2时修复）

在v2里会支持批量导入

**Comment by liupan1890** [comment]
这个功能本周开发时，尝试了一下，最终放弃了

当前阿里云盘的分享链接，支持最多15级文件嵌套和最多4000个文件，但以后阿里还会进一步放开限制

这样如果单条分享链接内包含很多文件时，会导致 导入分享链接时，单条链接需要较长时间解析文件列表

另外大家的网盘空间也有限，所以很多导入时都是需要先筛选一些文件最终保存的

所以，批量导入分享链接功能，最终还是放弃了，因为导入时间不可控，可能几十秒，可能要等十几分钟，这个体验不好。当前还是只提供单条分享链接的导入功能

**Comment by bizheyandebing** [comment]
辛苦啦  你的努力我们看得见
