### ISSUE TITLE
我是来催更的~

### ISSUE THREAD

**Issue by wenhairu** [liupan1890/aliyunpan#138]
割了半个月了~

**Comment by iD2073** [comment]
希望8月1日能出个版本吧，功能有缺陷大家也不会喷，先让大家尝尝鲜！

**Comment by liupan1890** [comment]
明天我肯定会上传的！！！！！！更新了测试截图，不来看一下？https://github.com/liupan1890/aliyunpan/issues/95

**Comment by wenhairu** [comment]
> 明天我肯定会上传的！！！！！！更新了测试截图，不来看一下？#95

棒棒棒~牛逼~~~

**Comment by liupan1890** [comment]
已更
