### ISSUE TITLE
拖动上传问题

### ISSUE THREAD

**Issue by liveskai** [liupan1890/aliyunpan#139]
![image](https://user-images.githubusercontent.com/54350655/127764764-1326ad04-dc6d-4ab0-95cf-d65a0b2cfae4.png)

**Comment by liupan1890** [comment]
收到，是因为我直接监听的列表，应该监听整个窗口才对

v2里会修正为整个窗口可以接收文件

**Comment by liupan1890** [comment]
已在v2.8.22中修正此BUG
