### ISSUE TITLE
有个Mac版本就好了

### ISSUE THREAD

**Issue by Jv0id** [liupan1890/aliyunpan#14]
有个Mac版本就好了

**Comment by liupan1890** [comment]
不同于6盘小白羊版采用的electron+golang
阿里云盘小白羊版采用的技术路线为flutter+golang
golang没问题，支持编译mac
flutter理论上也支持编译mac，但实际上当前flutter桌面技术非常不成熟，对mac实际上并没有什么支持。

我现在时间还是用在开发软件功能上，等下个月功能都稳定了我会着手适配mac，主要是一堆Swift看着就头疼，所以放在最后了

**Comment by liupan1890** [comment]
如果你懂mac的话也可以试着自己先着手适配工作

因为阿里云盘小白羊版的所有功能都和mac适配无关！直接可以使用编译

主要的适配工作是指：
1.适配程序启动后自动启动aliserver进程
2.适配mac托盘菜单和图标（以及点击菜单时显示窗口）

嗯，就是这么一点点工作，但是需要用Swift，调用mac系统的api来实现

**Comment by liupan1890** [comment]
v1.6.10 mac有了
