### ISSUE TITLE
在线播放闪退问题

### ISSUE THREAD

**Issue by yato534** [liupan1890/aliyunpan#140]
请教一下作者，点击在线播放会弹出播放框，然后迅速闪退，是什么原因呢
像这样
![image](https://user-images.githubusercontent.com/54138808/127794013-7959fe15-b40a-486d-b4bb-39c50525d117.png)

**Comment by liupan1890** [comment]
这个是程序的BUG，之后会修复

你可以先退出小白羊，然后再重新打开（为的是刷新token）

然后就正常了（提示“解析视频下载地址失败”）也是这个BUG。

**Comment by yato534** [comment]
@liupan1890 没用欸，旧版本和新版本都是一样闪退，退了重进也不行

**Comment by liupan1890** [comment]
v1.6.29也闪退吗？是所有的视频都闪退？是所有的时间都闪退（就是每天不管什么时候用）？

我这里测试是正常的啊。。。。

**Comment by yato534** [comment]
@liupan1890 是的。。。V1.2.29打开视频就是转个圈圈就没了，新版本还会弹出个播放框在闪退
![image](https://user-images.githubusercontent.com/54138808/127948947-463cbbb6-17b6-4c3e-b681-5380a77ee7d5.png)

难道是我电脑的问题么···

**Comment by liupan1890** [comment]
这个问题怪我没重视。
之前v1.xxx我一直没有遇到过这个问题
最近几天测试v.2xxx的时候我有一次遇到了这个问题，我以为是token失效的BUG，没在意（因为我当时重新登录一遍就好了），我还以为是v2的程序BUG呢

如果v1.6也同样出错，说明是调用阿里云盘的下载接口时，没有正确返回数据，最终导致不能播放

这个问题需要我抓包重现此情况，才能针对的修正。但是我今天在我的电脑上试了到多次了，都能正常播放

等我多测试几天，希望可以遇到这个错误

**Comment by yato534** [comment]
非常感谢

**Comment by liupan1890** [comment]
此问题应该已经修复，如果又遇到了，在开新的issue
