### ISSUE TITLE
个人觉得很多需要改进的地方

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#141]
![image](https://user-images.githubusercontent.com/87513821/127810225-9e1f80ad-b7af-4432-9dec-a6336b52e93e.png)
这个位置只放收藏夹就可以，把回收站放到“传输”功能区的最下面就可以，如下图，如果不看回收站，还以为是在那个目录下呢
![image](https://user-images.githubusercontent.com/87513821/127810559-22b20ddc-2847-4a30-a1c1-f48eeec764fe.png)
![image](https://user-images.githubusercontent.com/87513821/127811564-78d7363b-f4b8-4e9c-bda9-8e65ba4258ef.png)

2.以下图中的路径应该保留，当隐藏左侧目录树的时候，在文件区想返回上一目录都没有相关的按钮
![image](https://user-images.githubusercontent.com/87513821/127810942-bd636523-0f09-4e57-b2f0-deaa3b42c168.png)
![image](https://user-images.githubusercontent.com/87513821/127814380-e3627161-78e6-45db-b518-ffb620940eb3.png)

3.以下图当选择一个文件时功能栏是这样的（图一）当选择两个文件时是这样的（图二）选择一个文件时没有删除按钮
![image](https://user-images.githubusercontent.com/87513821/127811226-5659c440-d53c-4d54-a8fd-e58f8292f9d1.png)
![image](https://user-images.githubusercontent.com/87513821/127811278-4e01c7ae-19e1-497c-9afa-84f035b71d3a.png)

3.这样的功能个人感觉不如竖排像电脑上那个的菜单直观，而且还容易遮挡当前显示的文件名，
![image](https://user-images.githubusercontent.com/87513821/127811860-95444273-dae9-4873-839f-53389a93e341.png)

4.功能栏，个人建议尽量用两个字的功能，如“新建”子菜单包括“新建文件夹”和“新建时间文件夹”  。“导入”子菜单包含“导入秒传”“导入分享”。“导入秒传”再包含需要添加的菜单，“导入分享”的二级子菜单也是如此，这样功能布局整洁规矩。同时在文件右键也加入导入功能，
![image](https://user-images.githubusercontent.com/87513821/127812552-aeef0fa4-3289-464e-bba8-1d66c345c552.png)

**Comment by iD2073** [comment]
5.  下图的那些按钮建议图扁平单色按钮，如下图
![image](https://user-images.githubusercontent.com/87513821/127813147-c7ec9a6c-d90c-4ef0-a492-e77032de3bd4.png)

**Comment by Borber** [comment]
先实现功能, 后面大不了开放主题系统

筱维love筱雅 ***@***.***> 于2021年8月2日周一 下午2:21写道：

**Comment by liupan1890** [comment]
1.回收站位置，不可能放到队列页面的，回收站是网盘的功能，队列页面是队列，不能乱放，新手会找不到回收站在哪，最后还有一个相册的回收站呢

2.当前路径我之后会加上

3.选择一个文件时没有删除按钮（没有9个功能按钮）是为了强制你使用右键菜单。选中2个以上文件时显示的都是批量操作按钮

4.右键菜单，因为有9个菜单，竖排的形式，放不下。。。放不下啊啊啊啊啊啊。就是你一点击右键，半个屏幕都是菜单，所有文件都遮住了，如果只有3-4个菜单，我就直接鼠标移动上去显示了
遮挡当前显示的文件名：你不点右键，就看清楚了，找准了文件点击右键，遮挡文件名有什么影响呢？

5.按钮名，2个字好看但不只管，新手不容易明白，比如新建，新建什么？我想新建文件夹应该点哪里？相信我这都是经验，就2个字“新建”，新手会来问我怎么新建文件夹？他不会去点一下新建按钮试试能不能新建文件夹，他只会直接来提问：不能新建文件夹吗？

6.线框图标我的最爱不接受异议（因为按钮太多了，采用实体颜色方案，顶部按钮区域颜色太重太显眼），最难看的我感觉是右键菜单，但我没时间优化，太多功能在排队了，美观就不太重要了

7.你点击头像就能看到空间占用了，底部增加空间信息，太占空间了，小屏幕一般高度只有800px，非全屏状态下软件的高度一般也就600px 去掉顶部（相册一行）再去掉顶部（按钮一行），再去掉顶部（文件排序一行），已经没有多少空间了。要考虑到空间很宝贵，空间占用信息并不重要，能点击头像看到就可以了吧？


就喜欢你这种截图说话的，说的又好听，看的又清楚

**Comment by iD2073** [comment]
1.你说的回收站位置保留原位置你说的也有道理，必定还有一个相册，但是我感觉，排序可以，根目录、收藏夹、回收站，这样排序比较合理，，，现在有一个BUG就是最后一项经常显示缺失。

2。这个路径很重要，希望早日加上

4.右键菜单为什么竖排呢，其实，在右键菜单里加入常用的就可以了，下载，移动，复制，删除，像天翼云盘这样也不怎么占地方，右键时也不遮挡文件名，如下图：
![Snipaste_2021-08-02_21-57-36](https://user-images.githubusercontent.com/87513821/127873460-bda9037e-fd27-4d2a-94f7-106470c696b6.jpg)
 
5。关于按钮名的问题，那得多么笨的人不知道“新建”是什么意思呢？在阿里云盘里就一个十字，好像基本大家也都知道是什么意思了，现在的很多APP都在右下角或右上角弄那么一个，也都知道是什么意思，就比如阿里云盘的手机APP，在云盘里“新建”基本都知道是什么意思，因为在云盘里新建就只能有文件夹，只有有些可以扩展的功能比如什么word文档，新建txt文件的才会复杂一些，之前我提议的“新建时间文件夹”也算是个新功能。

6，实体颜色也不一定就是我标示的那么深的颜色，可以参考像天翼云盘按钮那样简单就很好的啊，其实我感觉线框图标更花哨了，或者把线框变淡一些也可以，有个界限区分就可以了，

7.我所图示的那个状态栏，不要太多信息，磁盘空间总大小，剩余大小，  然后，当前文件夹的概述，比如文件总数，文件夹数，文件数，这就可以了，这些文字信息都可以用图标显示，以后如果需要可以扩展，比如mp4文件多少个，jpg文件多少个，等等一些信息都可以显示在这里，不一定要加入我说的信息，也许后续还可以可以加入别的信息，

**Comment by iD2073** [comment]
就像天翼的右键菜单文本上下都有点宽了，可以再紧凑一些最好了，单色不花哨

**Comment by renshen1** [comment]
| |
LuYu Shan
|
|
***@***.***
|
不要发给我了
签名由网易邮箱大师定制
在2021年8月2日 ***@***.***> 写道：

就像天翼的右键菜单文本上下都有点宽了，可以再紧凑一些最好了，单色不花哨

**Comment by iD2073** [comment]
> | | LuYu Shan | | ***@***.*** | 不要发给我了 签名由网易邮箱大师定制 在2021年8月2日 ***@***.***> 写道： 就像天翼的右键菜单文本上下都有点宽了，可以再紧凑一些最好了，单色不花哨 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那是你订阅了这个网站的消息，是系统自动发给你的，你应该取消订阅好像就可以收不到邮件消息了，

**Comment by liupan1890** [comment]
1.最后一项经常缺失 确实是BUG，正常的在显示网盘/相册时会比较宽（不缺失），分享/队列/插件页面时比较窄，但是程序BUG页面切换时触发消息时灵时不灵，稍后我会修正

2.关于顶部按钮和右键菜单，我又有了新的想法，等我今晚发图咱们再讨论

**Comment by iD2073** [comment]
采用
![image](https://user-images.githubusercontent.com/87513821/127957108-dd95ba71-0e45-492e-bd12-c196349231b4.png)
就会出现打开视频文件出现视频窗口闪退现象 
![动画](https://user-images.githubusercontent.com/87513821/127957382-73394dbc-a11c-4a37-9d12-0f4936941200.gif)

当采用
![image](https://user-images.githubusercontent.com/87513821/127957421-c8b0dc52-0ea7-4964-ab47-50fc637e2761.png)
时，打开视频就会提示如下图：
![动画1](https://user-images.githubusercontent.com/87513821/127957618-414792c0-9e92-429a-9e6e-3b4741134698.gif)

**Comment by liupan1890** [comment]
最后就是这样了，先不改了，先做功能，UI下个月再说了
![无标题](https://user-images.githubusercontent.com/67817756/127966229-d9edb8f2-1fa7-4186-8276-5d615e76da67.png)

视频：应该软件BUG，退出小白羊后重新打开可能就好了，下个版本修复

**Comment by iD2073** [comment]
> 最后就是这样了，先不改了，先做功能，UI下个月再说了
> ![无标题](https://user-images.githubusercontent.com/67817756/127966229-d9edb8f2-1fa7-4186-8276-5d615e76da67.png)
> 
> 视频：应该软件BUG，退出小白羊后重新打开可能就好了，下个版本修复

好吧，改后的也可以，比之前的一条蓝色好多了，UI先这样吧，辛苦辛苦小哥，先把功能完善再考虑UI吧

那个新建日期和时间文件夹的功能，就合并成一个就可以了， 比如新建之后就像这样：2021-08-03 14-37-11  这样就可以了，以后拍相片传到云盘，按日期查找就非常方便了

**Comment by KHLFYY** [comment]
> 那个新建日期和时间文件夹的功能，就合并成一个就可以了， 比如新建之后就像这样：2021-08-03 14-37-11 这样就可以了，以后拍相片传到云盘，按日期查找就非常方便了
@liupan1890 
提个个人小建议，让日期/时间格式也能自定义一下，比如我就习惯直接打20210804这种日期……这个功能也不着急，作者先加油开发v2版本功能吧，辛苦了！

**Comment by liupan1890** [comment]
收到

**Comment by liupan1890** [comment]
此issue内讨论已基本实现，所以关闭了
