### ISSUE TITLE
期望从命令行登录和下载功能实现

### ISSUE THREAD

**Issue by yanght1001** [liupan1890/aliyunpan#143]
我的家庭NAS是Liunx 的 Debian 系统，使用的是 Arm CPU；我看咱们2.0版本目前已经可以运行到liunx 和arm上了，由于我的liunx没有界面的服务器版本，期望有命令行的实现；
1、使用用户名和密码进行登录。
2、展示目录结构
3、下载文件

这样的话，我就可以把网盘里面的视频资源直接下载到NAS里面的目录了，直接在家庭电视观看NAS里面的。

特别期望这个功能，感谢大神。

**Comment by liupan1890** [comment]
v2采用的是electron
electron不支持命令行，他就是个浏览器。可以通过命令行启动运行，但还是要显示界面操作。它并不支持你想要的命令行方式

所以，也就是需要我重头到尾重新换种语言开发一遍（比如用golang）

但是现在github上已经有很多命令行操作的阿里云盘的开源项目了，并不需要我去做了

搜索 “阿里云盘” 有很多的，py的，go的，nodejs的

**Comment by liupan1890** [comment]
另外仅针对下载

v2里已经提供了远程aria设置了，你不是没用过v2就来发issue了吧？

NAS 运行一个aria2  ---- 百度，巨多，各种教程

在win10上运行小白羊v2,设置远程aria，直接把你要的文件下载到NAS，不是很方便吗？

**Comment by yanght1001** [comment]
> v2采用的是electron
> electron不支持命令行，他就是个浏览器。可以通过命令行启动运行，但还是要显示界面操作。它并不支持你想要的命令行方式
> 
> 所以，也就是需要我重头到尾重新换种语言开发一遍（比如用golang）
> 
> 但是现在github上已经有很多命令行操作的阿里云盘的开源项目了，并不需要我去做了
> 
> 搜索 “阿里云盘” 有很多的，py的，go的，nodejs的

感谢，我已经在github找了一些命令行工具，也不错。解决了我的问题。

**Comment by yanght1001** [comment]
> 另外仅针对下载
> 
> v2里已经提供了远程aria设置了，你不是没用过v2就来发issue了吧？
> 
> NAS 运行一个aria2 ---- 百度，巨多，各种教程
> 
> 在win10上运行小白羊v2,设置远程aria，直接把你要的文件下载到NAS，不是很方便吗？

我下载了v2预览版，看到很多的插件都是开发中状态，没有仔细看设置里面的远程下载，没有看到也没有想到有这么体贴的功能，感谢
