### ISSUE TITLE
为什么同是视频文件有的点了右键里的“详情”，有的是这样的：图一 有的却是：图二   这样的？

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#144]
为什么同是视频文件有的点了右键里的“详情”，有的是这样的：图一
有的却是：图二   这样的？

![屏幕截图 2021-08-05 223423](https://user-images.githubusercontent.com/87513821/128368994-ad12372a-0959-4eec-9e40-ae52b2784a60.jpg)
![屏幕截图 2021-08-05 223832](https://user-images.githubusercontent.com/87513821/128368995-c664cf35-82cb-4ed0-b0c4-71a66b5eec84.jpg)

**Comment by liupan1890** [comment]
当前的判断逻辑是
1.是视频文件
2.有在线播放链接

走雪碧图（图一）

反之走普通文件（图二）

比如有的文件刚上传还没生成在线播放链接，那就走图二了
也可能是判断错了，你的图二那个视频，在阿里云盘官方网页版里，可以在线看吗？（如果可以说明是判断错了，BUG）

我网盘里的视频都是很久的，所以遇不到图二的这种状态，所以测试不了啊。

**Comment by iD2073** [comment]
我传的这些文件也都是很久上传的文件，网页端是正常播放的视频

**Comment by liupan1890** [comment]
那我下个版本改一下逻辑，.是视频文件 就走雪碧图，不判断预览链接了

方便的话，可以对图二的文件，创建秒传txt，然后贴给我，让我测试吗？不方便就算了。

**Comment by liupan1890** [comment]
我已经找到原因了，部分视频阿里云盘默认就是不提供预览信息，此BUG已在下个版本修复
