### ISSUE TITLE
播放器问题，不能用Potplayer吗？

### ISSUE THREAD

**Issue by zhuaohong** [liupan1890/aliyunpan#145]
大佬你好，请问能加上个在线播放调用本地播放器（例如potplayer）的功能不，因为我感觉mpv的各种功能用起来不方便，并且potplayer播放器在madvr滤镜的加持下看视频会更舒服点。麻烦大佬了。

**Comment by lyld1314** [comment]
同求可以调用本地的播放器，以前6盘的小白羊可以调用本体的恒星播放器，主要想投屏到电视看，MPV貌似不支持DLNA，望大佬考量一下

**Comment by liupan1890** [comment]
1.由于阿里云盘官方限制，播放器在播放云盘内的文件时必须附带上Referer=https://www.aliyundrive.com/ 的http头

2. 除了mpv以外，我没有测试出其他播放软件支持在命令行中设置附加Referer
---这个主要是我用过的播放软件并不多，只测试了Potplayer QQ影音，迅雷播放器，暴风影音，这几个都不支持

因为官方限制，所以Potplayer是不能用的，我也没办法。

比较可行的解决方案是本地开一个http代理，然后播放器通过代理访问云盘文件播放，代理自动附加Referer。但这个方式比较麻烦，一般人也不愿意用。我现在也没时间做这个。等2个月后我闲下来了，再试试吧

**Comment by liupan1890** [comment]
可能说的不明白
先用小白羊生成了视频文件的DownloadURL
调用MPV
``````
mpv.exe --Referer=https://www.aliyundrive.com/       DownloadURL........

可以，MPV支持Referer
``````

调用Potplayer

``````
potplayer.exe DownloadURL
``````

你看，不能设置Referer，因为Potplayer不支持在命令行里设置Referer(实际上Potplayer也不支持在界面里手动设置Referer)

因为没有Referer，阿里云盘拒绝访问，不能播放

**Comment by zhuaohong** [comment]
好的，多谢大佬解答。

**Comment by zhuaohong** [comment]
我在GitHub上找到了其他人开发的mpv简化版的项目https://github.com/422658476/MPV-EASY-Player
![image](https://user-images.githubusercontent.com/79396909/128507188-4bbc7e1d-8cac-4839-b412-df430136919f.png)
![image](https://user-images.githubusercontent.com/79396909/128507202-97a07ad3-925d-48f8-a149-21ce217493db.png)
感觉比原生的mpv要好用些，请问这个能替换吗？

**Comment by liupan1890** [comment]
不能，MPV-EASY-Player

1.MPV-EASY-Player 自己用QT开发了一套设置的UI，所以可以很方便的使用UI更改MPV的设置
2.MPV-EASY-Player 是用QT去调用MPV
3.MPV-EASY-Player不支持Referer命令行参数

``````
MPV-EASY-Player.exe --Referer=https://www.aliyundrive.com/       DownloadURL........

不支持
``````

4.MPV-EASY-Player 的目录里面有MPV，如果直接命令行调用MPV-EASY-Player里面的MPV（不通过.MPV-EASY-Player的QT程序），跟小白羊现在直接调用MPV是一样的，没有.MPV-EASY-Player的设置界面，没有.MPV-EASY-Player的自定义功能。

5.在小白羊v2里已经集成了MPV-EASY-Player的Potplayer皮肤。但没有集成MPV-EASY-Player的设置UI，因为不支持

**Comment by zhuaohong** [comment]
好的，谢谢了。

**Comment by iD2073** [comment]
我昨天测试了一下，替换为MPV EASY Player是可以用的，不过有些功能也未必就好，也不有太大区别，就是界面稍稍美观了那么一点点，替换PotPlayer播放器确实不能用，替换后的MPV EASY Player播放器，并不能更好的最小化 内置的可以做到的最小化窗口（图一），MPV EASY Player能做到的最小化窗口（图二）
![image](https://user-images.githubusercontent.com/87513821/128583806-250db4a4-5a26-471e-97d1-8dda03e72b08.png)
![image](https://user-images.githubusercontent.com/87513821/128583846-74c5fb53-b729-4aff-aa6b-5836d836b52e.png)

**Comment by liupan1890** [comment]
内置的，只能一直显示标题栏，或者一直不显示标题栏，没有鼠标移上去后才显示的功能（因为启动时命令就定死了，显示或者不显示）。实际上，MPV能够设置的功能并不多，比如一些滤镜之类，还是Potplayer功能多，但用不了就无解了

**Comment by TkzcM** [comment]
PotPlayer 最新版 cli 支持自定义 Referer
`PotPlayerMini64.exe URI /referer="url"`

**Comment by QiTianzu** [comment]
> PotPlayer 最新版 cli 支持自定义 Referer
> `PotPlayerMini64.exe URI /referer="url"`

替换了还是不行

**Comment by liupan1890** [comment]
我去研究一下，可以的话就替换了

**Comment by liupan1890** [comment]
自v2.8.15版本开始，可以使用Potplayer了，参阅github里的'使用Potplayer.md'
