### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by windfsy** [liupan1890/aliyunpan#146]
![N9PY2W(~L9}@YX911IYKZBL](https://user-images.githubusercontent.com/86504603/128599364-ec83d52b-7f7c-4860-8bf1-4944e7dae7b8.png)
![HBSZ$}SCZ7K$PJ5SL%DUIM0](https://user-images.githubusercontent.com/86504603/128599368-298e1429-7eb9-40ad-b973-09a3105e83d8.png)

**Comment by liupan1890** [comment]
在新版，加入了窗口过小时收缩的模式
![无标题](https://user-images.githubusercontent.com/67817756/128617964-3923b9be-68ff-4c95-8167-6bcce62ffaab.png)


这个跟拖动大小功能冲突，所以取消了拖动大小的功能（那个竖条）

在新版正确的应该是大小随整体窗口自动调整的
![无标题2](https://user-images.githubusercontent.com/67817756/128617985-d5742428-a5c3-40ab-89e3-dc6850972d49.png)

但因为BUG显示的不正常，等我今晚22点更新时你再试试看

**Comment by iD2073** [comment]
![动画1](https://user-images.githubusercontent.com/87513821/128618684-b010c2a3-df08-4ea2-b7b7-7a0f7ff40d65.gif)
其实这样的拖动真的是最合理的，很多软件都采用这种方式，辛苦小哥

**Comment by iD2073** [comment]
我觉得还是希望小哥能恢复原来的竖线形式，冲突肯定是可以解决的，如下图，这个软件能解决的问题，对于小哥来说也绝对不是问题，谢谢小哥，辛苦了
![1111](https://user-images.githubusercontent.com/87513821/128656041-e9b3ee53-b56d-47af-afc7-0c32dab1bf49.gif)

**Comment by liupan1890** [comment]
嗯，后期我会在抠细节！
