### ISSUE TITLE
能不能添加通过SHA1或MD5转存文件

### ISSUE THREAD

**Issue by liveskai** [liupan1890/aliyunpan#147]
能不能添加通过SHA1或MD5转存文件

**Comment by liupan1890** [comment]
1. 阿里云盘 https://api.aliyundrive.com/v2/file/create 接口需要提供 sha1 和 size
2. 阿里云盘 https://api.aliyundrive.com/adrive/v2/file/createWithFolders 接口需要提供sha1 和 size 和 文件指定区域数据

>能不能添加通过SHA1或MD5转存文件

最少需要 sha1+size ，至于md5一点用都没有

**Comment by liveskai** [comment]
> 最少需要 sha1+size ，至于md5一点用都没有

有SHA1和大小，可以吗

**Comment by liupan1890** [comment]
可以

阿里云盘 https://api.aliyundrive.com/v2/file/create 接口

**Comment by liupan1890** [comment]
如果你是说怎样通过小白羊

只要有SHA1和大小

自己拼接成

``````
aliyunpan://文件名|sha1|大小
``````

然后点击小白羊的 ‘导入秒传’ --  ‘aliyunpan://秒传’ -- 粘贴--解析链接 就好了

拼接时，文件名自己随便起一个，
sha1和大小你自己知道
这样就可以通过小白羊直接导入了


我总感觉你问的很奇怪，上面这些都是最基础的知识了，不需要问，自己看一眼就知道了啊，

如果你是想自己编程导入，就是掉用上面的阿里云盘接口
