### ISSUE TITLE
win7旗舰版sp1，打开软件窗口全是黑色。【如图】。是否缺少什么支持的组件？

### ISSUE THREAD

**Issue by HHLT666** [liupan1890/aliyunpan#149]
win7旗舰版sp1，打开软件窗口全是黑色。【如图】。是否缺少什么支持的组件？

https://inews.gtimg.com/newsapp_ls/0/13859759575/0

**Comment by liupan1890** [comment]
是Flutter的BUG，并非缺少什么组件。所以此问题无法修正

可以使用v2 支持win7 sp1 最好今晚再来下载，因为今晚我会更新v2.8.8

**Comment by HHLT666** [comment]
> 是Flutter的BUG，并非缺少什么组件。所以此问题无法修正
> 
> 可以使用v2 支持win7 sp1 最好今晚再来下载，因为今晚我会更新v2.8.8

谢谢回复。
