### ISSUE TITLE
兼容 linux arm

### ISSUE THREAD

**Issue by hmsjy2017** [liupan1890/aliyunpan#15]
希望兼容linux arm

**Comment by liupan1890** [comment]
嗯，arm现在看不是很理想，不是我懒得折腾，是flutter线路本身的问题

flutter的技术，是这样，可以理解为nodejs，用javascript（Dart）编写一遍代码，然后随处可以运行。所以如果从flutter本身来说是支持arm的，不论是linux的arm还是mac的arm。这个理论上都是支持的

但是具体到小白羊项目本身，他不是app，他是desk

1.涉及到阿里云盘本身功能的代码，都是通用的代码，可以支持到arm

2.涉及到窗口的代码（窗口的显示大小，默认显示位置，最大化，最小化，关闭按钮，标题栏拖动，托盘图标，任务栏图标，托盘菜单），都跟flutter无关了，flutter的桌面支持当前采用的是让开发者自己使用对应的编程语言单独编写对应系统的代码

小白羊现在只支持window
是因为我熟悉windows编程，c++调用win32api ，所以，都是我自己套的窗口代码（比如托盘菜单，完全是win32api）

小白羊以后计划会支持mac
是因为我计划会去学一下Swift编程和研究mac的系统api，实现托盘菜单等功能

小白羊以后应该会支持linux
是因为linux也需要我去学一下linux的系统api（GTK）用C++实现托盘菜单等功能

  
  
但是你提到的是arm

我没有arm设备，没有树莓派，也没有其他arm linux 设备，也没有arm mac

没有设备靠懵代码，那就不太现实了

另外小白羊也不会支持命令方式调用，只支持UI操作方式的，因为我没有精力把所有功能都重新写一遍命令行接口

小白羊本身是开源的，希望有其他人可以帮助你编译出适配arm的版本吧，我没有机子，没法真的去适配，编程本身就是扣细节的东西，虽说从系统层面上讲，x86和arm区别不大，但细节上总是会遇到兼容问题的，没有机子真的就是懵代码了

**Comment by liupan1890** [comment]
如果我是使用的electron开发界面，就没有这些事了，因为electron团队早就已经发布了各种arm版本了，我只需要写js就可以了，窗口的、托盘菜单的各种编程语言各种系统api，electron团队都撸了一遍了。可以直接用

但是，我是用的Flutter，没办法，按照当前Flutter官方的更新进度，等2年以后可能会出官方的支持，现在确实不成熟

**Comment by liupan1890** [comment]
v2.8.28已发布，可以自己打包各种linux arm 版本了，参见“linux打包.md”
