### ISSUE TITLE
关于2.8.8的使用体验

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/aliyunpan#150]
1、2.0版本的整体运行速度比1.0版本有了很大的提升
2、2.8.8增加了返回功能，很好用！
3、mpv播放视频的初始大小像是520p，希望能像1.0版本的mpv自适应大小

**Comment by liupan1890** [comment]
下个版本会在设置里增加一个设置，可以自己选择mpv初始大小

当前是默认最大屏幕的50%，可以鼠标移动到边框自由拖动大小
