### ISSUE TITLE
aria2 貌似有点问题

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#151]
1. 链接的时候，如果参数有问题，会一直加载
2. aria2下载没有速度，好像是403

![aria](https://user-images.githubusercontent.com/19268555/128637118-46c58aac-95a3-4fc1-b966-92f9e2cc0a9a.png)
![down](https://user-images.githubusercontent.com/19268555/128637120-7f198282-5f92-4b4d-a456-ed1eeca7aa97.png)
![image](https://user-images.githubusercontent.com/19268555/128637150-0453018e-942a-4f80-a222-8206278ce197.png)

**Comment by liupan1890** [comment]
我去测试一下

**Comment by liupan1890** [comment]
1. 链接的时候，如果参数有问题，会一直加载
这是BUG，已修正，重新下载替换就好了

2.aria2下载没有速度，好像是403
我测试是正常的，我新开了一台VPS测试的，完全正常。以前都是虚拟机测试的跟我同IP

分析一下：
1。阿里云盘当前只限制 referer和Time
小白羊调用aria下载时已经传递了referer参数，通过
小白羊创建的下载链接有效期是4小时--阿里云盘最高只支持4小时，通过
所以理论上，不会出现403的错误

怎样会403呢？
你在文件的详情里，点击创建下载链接，复制此链接直接提交到aria下载会出现403.因为你没有附加referer参数

可能还有其他原因，但我还没想到

**Comment by liupan1890** [comment]
![Uploading 无标题2.png…]()

**Comment by liupan1890** [comment]
![无标题2](https://user-images.githubusercontent.com/67817756/128661511-1b548d4b-16d8-4afc-919f-9b0eb0681aef.png)

**Comment by yayaleslie** [comment]
![image](https://user-images.githubusercontent.com/19268555/128708981-7d912fbf-938a-4da0-8271-311daee3bc6a.png)

aria2是连上了
![image](https://user-images.githubusercontent.com/19268555/128709104-60963aba-ad4d-4351-b3ca-1d54ee03eb8e.png)

然后这边也有链接
![image](https://user-images.githubusercontent.com/19268555/128709203-2c26195c-bfa5-4b45-bfe4-92bb2423cfcf.png)


但就是没速度，我用aria2直接下载获取到的链接，会报403，加上 --referer参数可以下载，这个参数是自己来设置吗？小白羊可否把这个参数自动加上呢
![image](https://user-images.githubusercontent.com/19268555/128709340-efbadd2b-577e-4506-bf02-88b1a7abbf5d.png)

**Comment by yayaleslie** [comment]
还有个小问题，现在视频查看详情是缩略图，怎么看 下载链接呢
![image](https://user-images.githubusercontent.com/19268555/128710453-cf8ffd46-8891-4902-98f2-190336d5a4f7.png)
不是视频的可以看到链接
![image](https://user-images.githubusercontent.com/19268555/128710587-6122d392-4027-405b-beae-12709df832c0.png)

**Comment by liupan1890** [comment]
嗯？？？我怎么蒙了？？

1.你在小白羊里设置，设置为远程模式（绿色），然后点击文件的下载按钮。好了，正常下载，会自动附加referer

这样才对


2.你在文件的详情里，点击复制下载链接，然后切换到AriaNG,新建任务，粘贴链接，粘贴referer


正常的，你并不需要按照2去操作。直接按照1操作就好了。所以视频详情里，不需要有复制下载链接的按钮

**Comment by liupan1890** [comment]
是不是你的aria设置有问题？我测试都是正常的，我确认在小白羊点击下载按钮，传递给aria的任务参数里，已经正确的附加了referer这个参数了啊
``````
['aria2.addUri', [downurl], { gid: info.GID, dir, out, split, referer, 'user-agent': userAgent, 'check-certificate': 'false', 'file-allocation': 'trunc' }],
``````

所有的参数都是一次整个的传递过去的，下载地址，referer

我猜测可能是你ariaNG设置的问题

**Comment by liupan1890** [comment]
你可以用命令行启动aria试一下

``````
aria2c --enable-rpc=true  --rpc-allow-origin-all=true --rpc-listen-all=true --rpc-listen-port=5277  --rpc-secret=S4znWT --rpc-secure=false
``````

小白羊里填对应的  IP:5277 密码S4znWT

然后直接用小白羊下载

如果能下，就说明是你ariaNG设置的问题，可能设置了默认的referer

**Comment by yayaleslie** [comment]
aria2 是网上一键脚本安装的，估计设置上有问题，我回头重装下再试试，辛苦大佬
