### ISSUE TITLE
作者使用过clouddrive吗？会考虑复刻其功能吗

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/aliyunpan#152]
http://d0.ananas.chaoxing.com/download/ca3424913f896b8290b454d72fdbeebc?at_=1628489487555&ak_=0f9a4ebd6a8b5a7205bc3786020f0a90&ad_=4a86a2bd46f88b6fb88d141c2d69abc9&fn=CloudDriveSetup-1.1.31.exe

这是一个云盘挂载本地的软件，挂载后可以建立本地家庭影院

**Comment by liupan1890** [comment]
我记一下，以后再研究

**Comment by iD2073** [comment]
我想问一下， 这个 CloudDrive 会不会泄露自己网盘内的隐私呢？我也在用，但是不敢把重要网盘挂上去

**Comment by d790043608** [comment]
没找到相关资料啊？

**Comment by d790043608** [comment]
> 我担心一下这个，CloudDrive 会不会泄露自己的网盘内的隐私？
我为什么不能注册
？

**Comment by testonlys** [comment]
> 
> 
> 我想问一下， 这个 CloudDrive 会不会泄露自己网盘内的隐私呢？我也在用，但是不敢把重要网盘挂上去

有这个可能，有个选项是把登录信息存到第三方服务器上

**Comment by testonlys** [comment]
是个基于 WinFSP(https://github.com/billziss-gh/winfsp/) 的

**Comment by inpowerchiu** [comment]
这个软件映射到本地磁盘后，观看视频的缓存默认生成到哪了？有大佬能讲下吗？

**Comment by KHLFYY** [comment]
> 这个软件映射到本地磁盘后，观看视频的缓存默认生成到哪了？有大佬能讲下吗？

略有了解，说的不对还请各位大佬指正。
这个就是把一个网盘目录映射成了本地磁盘，当你打开视频的时候，软件把视频边下载到本地的缓存文件夹。
缓存文件夹默认在C盘一个目录下，可以更改位置，具体在软件设置页面（桌面新建那个快捷方式）里有，英文写的，软件翻译一下就能找到。我软件卸载了，所以没法截个图。

**Comment by hummersyk** [comment]
我也觉得就是一个映射而已，初看好像挺酷的样子，细想还真没太大的意义。
还是客户端靠谱、功能更强大。

**Comment by CersOps** [comment]
之前有考虑过用CloudDrive，直接用potplayer打开视频文件会很方便。后来考虑到个人账号安全问题，就换成了webdav+Raidrive的方案。现在小白羊2能配合potplayer使用了，个人就没必要再用别的方案了。。。。。
