### ISSUE TITLE
上传的文件保存在哪？

### ISSUE THREAD

**Issue by Tonymti** [liupan1890/aliyunpan#153]
上传之后并没有找到上传的文件

**Comment by liupan1890** [comment]
1 针对v1.6.29 你在哪个目录下点击的上传按钮，就会保存到哪个目录下

比如你在 根目录/新建文件夹1 里面点击的上传按钮/拖放文件到窗口 就会把文件上传到 新建文件夹1里面

当你上传时，在上传中/已上传完 队列 有详细的上传记录

2 针对v2.8.8 
并未提供上传功能

**Comment by Tonymti** [comment]
但如果在主界面上方点的上传呢

**Comment by liupan1890** [comment]
就是说的在主界面上方点的上传啊，

在主界面，看一眼你当前在哪个文件夹里，点击上传就会传到这个文件夹里

![无标题root](https://user-images.githubusercontent.com/67817756/129468768-e906a750-2e23-48a2-8768-01f83c58a629.png)

如图，当前在根目录，此时点击上传，或者拖放文件上传，都是上传到根目录

**Comment by liupan1890** [comment]
![无标题sss](https://user-images.githubusercontent.com/67817756/129468791-391bb559-9dad-4e96-a57f-6c9a631b9e7b.png)

如图，当前在“生活大爆炸”文件夹下，此时点击上传，会上传到生活大爆炸里

**Comment by liupan1890** [comment]
这种问题，自己上传一遍不就知道了，不需要问吧？
