### ISSUE TITLE
建议播放器支持投屏功能

### ISSUE THREAD

**Issue by poemsiu** [liupan1890/aliyunpan#154]
建议播放器支持投屏功能，想投屏到电视上看

**Comment by iD2073** [comment]
目前内置的播放器都是别人的软件，这个好像不太可能吧！

**Comment by liupan1890** [comment]
当前使用的播放器并不支持投屏功能，以后有时间了想办法换个播放器试试。

**Comment by Royal520** [comment]
阿里云盘手机版自带了投屏

**Comment by liupan1890** [comment]
当前，在windows上，已经支持一些其他的播放器。但是，试过很多，发现，没有支持投屏的播放器

（支持投屏的播放器其实有，比如恒星播放器，但试了试，效果根本不理想，跟电视支持的协议有关，跟播放器支持的协议有关）

所以这个投屏功能已经被放弃了
