### ISSUE TITLE
可以添加播放时加载同文件夹下同名称的字幕文件功能吗

### ISSUE THREAD

**Issue by LucasZhao22** [liupan1890/aliyunpan#156]
如题，有些字幕没有压进去（压制太考验专业知识，而且很耗时间），如果能挂载那必是极好的
只支持srt字幕的挂载就行，ass恐怕可能有难度

**Comment by liupan1890** [comment]
#### 1.不管是什么格式的字幕

首先把字幕文件下载下来（点击一下下载按钮）
然后点击视频文件名，在线预览视频
最后把刚才下载下来的字幕文件拖动扔到播放窗口上

会自动加载播放，MPV还支持调整字幕的时间，如果字幕和视频不匹配（快了或者慢了），可以自己手动调整时间（加减秒）


#### 2.自动加载同文件夹下同名称的字幕文件

这个我是感觉作用不大
首先，大部分视频已经内置了字幕。并不需要加载字幕文件，MPV支持内置字幕

（我不知道你的情况，反正我看的视频99.9都是内置字幕的，没有字幕的叫生番，但我在各大视频网站上，都只能找到直接带字幕的视频，很少有提供不带字母的视频的，比如人人才提供有字幕和无字幕双版本，还有就是一些国外的论坛会发布一些生番，但基本等几天就有字幕组发布整合的视频了，所以一时之间我还真想不到去哪里找生番。我的意思是这个功能很少能用到）

然后，是找字幕并不容易
以前我确实遇到过一些电影因为太新，没有整合字幕，需要自己去找字幕，那时候还是射手，但是找字幕并不容易

因为太新，字母很少，尤其是每个字幕都需要是跟你的视频是同一版本的，不然时间就对不上。我当时就感觉体验非常不好。后来就发现，只要等最晚一周，就会有各种整合字幕的资源了，后来我就不看这种生番了

最后从技术角度去分析，还真不难，自动下载，然后加载就好了
但是吧，自动下载字幕涉及保存路径的问题，可以强制保存到临时文件夹
然后是需要等字幕下载完才能播放，这个会给人一个卡了几秒才播放的感觉。这个体验不太好

总之，还是你自己下载了拖放吧，我是感觉很少用到，拖一下也不是很麻烦，不是每个视频都要拖



#### 最后补充一下：
阿里云盘的在线播放，有的视频可以显示字幕，有的不显示，是阿里云盘转码程序的问题，有的视频明明有字幕，但阿里云盘认不出来，就不显示

所以，推荐你在小白羊的设置里设置为：强制播放原文件
这样MPV就可以显示字幕了。如果设置为：优先播放转码视频，就会可能明明有内置字幕却不显示

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/129020014-6bfac901-fd7a-4e52-b1ee-1aa3a76e17d6.png)


你看还有这种情况，就是字幕和视频名字没有完全一致，哪怕只差一个字符，程序也无法匹配到。所以这个“自动加载同文件夹下同名称的字幕文件”功能真的没啥用

**Comment by LucasZhao22** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/129020014-6bfac901-fd7a-4e52-b1ee-1aa3a76e17d6.png)
> 
> 你看还有这种情况，就是字幕和视频名字没有完全一致，哪怕只差一个字符，程序也无法匹配到。所以这个“自动加载同文件夹下同名称的字幕文件”功能真的没啥用

okk，了解，谢谢回复！
