### ISSUE TITLE
发现一个好用的工具共享给大家，作者也可以看下有没有启发

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#157]
使用方法
　1、下载应用，该应用和云盘应用是互相独立的。

　　2、注册账号，注册的是这个 clouddriver 应用，不是网盘。

　　3、登录账号，登录的是 clouddriver 账号，在注册成功后会跳转到登录页面。

　　4、该应用会打开一个本地网页服务作为配置：localhost:9798

　　5、选择云盘，这里选择阿里云盘即可，会弹出登录的二维码，用 app 扫码登录即可。

　　我的使用场景是用本地播放器，看云盘的视频资源，本地不用存，云盘空间足够大。
![Cloud Drive下载_云盘挂载本地硬盘工具Cloud Drive官方版下载1 1 34 - 系](https://user-images.githubusercontent.com/38945550/129232255-5d4c207a-5bcf-466e-9382-5449d9cb342a.png)

下载地址  http://www.xitongzhijia.net/soft/220806.html

秒传地址   ﻿{"DirList":[],"FileList":["CloudDrive_V1.1.34_XiTongZhiJia.zip|23495499|F7F35F7F3C7184261E95474AD3A8FE57EDE9BB39"],"Name":"","Size":23495499,"Message":""}

**Comment by iD2073** [comment]
我个人感觉，有些方面不如小白羊实用，无法导入别人分享的资源，打开视频就会占用全速网速，对软件不太懂，但是我有些担心会不会泄露隐私，我挂的都不是常用的阿里云盘

**Comment by DifferentSparkler** [comment]
如果作者可以把这个功能整合进来就完美了

**Comment by KHLFYY** [comment]
这条已经有过issue了 #152

**Comment by rapmq0** [comment]
不好用，文件一多就卡，还吃磁盘空间

**Comment by KHLFYY** [comment]
> 不好用，文件一多就卡，还吃磁盘空间

确实，本质还是下载到本地，边下边播。不如直接用阿里云盘或者小白羊在线放
