### ISSUE TITLE
无法登录,紧急求助

### ISSUE THREAD

**Issue by jing5460** [liupan1890/aliyunpan#16]
![image](https://user-images.githubusercontent.com/38358681/120803564-433fce80-c576-11eb-8b2c-daa02db92113.png)
![image](https://user-images.githubusercontent.com/38358681/120803799-813cf280-c576-11eb-8cfd-813b35d1cd78.png)

**Comment by liupan1890** [comment]
下载最新版试一下，今天更新的v1.6.5

**Comment by liupan1890** [comment]
说一下你的截图啊，
<br/>
当你双击`阿里云盘小白羊版v1.5.31.exe`的时候，会自动运行：
1.阿里云盘小白羊版v1.5.31.exe
2.data\aliserver.exe
<br/>
<br/>
你的第一张截图顶部显示：“严重错误，无法连接到后台进程”
一般是因为第一次运行时，win10要对aliserver.exe这个文件进行病毒扫描，大概会扫描10多秒，此时它是没有运行的，所以你无法登录。在第二次和以后运行时，就不会对aliserver.exe进行病毒扫描了，就不会出现此提示了
<br/><br/>
也可能是因为哪里有BUG，总之是aliserver.exe没能及时的启动起来，所以最后你扫码或者Cookie都无法登录

<br/>
<br/>
<br/>
另外：今天有一点特殊，阿里云网盘网页端升级了，导致扫码登陆就是会失败，需要升级最新的v1.6.5才能正常的扫码登陆
