### ISSUE TITLE
这是我对右键的想法，其实我还是觉得右键的传统方式更合理，详细解释如下：

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#160]
1. 这个界面是“小白羊”调整到最小的界面，我想调整到这么小的界面并使用的人还是比较少的吧！点击【下载】只下载到设定的指定文件夹（不包括父级目录路径）当鼠标移动到空心三角后会弹出【1路径下载】和【2自定义下载】或者就只保留1也可以。路径下载（下载包含就是包含父级目录）【2自定义下载】相当于给你一个弹窗让你选择下载位置，“比如桌面”等。

2. 复制的那个三角按钮可以增加曾经复制到的路径记录（最多包含5个曾经复制到的目录）移动的也是如此。应用场景如下：出去旅游拍了很多的相片，有老公的，有女儿的，有儿子的，有爸妈的，想分类，有这个功能就非常的便捷。

3. 其实【收藏】和【秒传txt】都可以移到上面的工具栏里也是可以的。

4. 【分享】我不知道你的思路，竖排显示未来可以增加更多功能。

![未标题-1-恢复的](https://user-images.githubusercontent.com/87513821/129577149-522b1f49-95cc-412e-9817-3b4670a4aafe.jpg)

**Comment by liupan1890** [comment]
这个设计好，便捷了很多，在下个/或者下下个版本会实现。也会在设置里增加选项，自己选择是横的还是竖的

**Comment by iD2073** [comment]
我觉得“标记”还是把文件夹变色就可以了，文件名还是不要变色了，

**Comment by iD2073** [comment]
这个按钮应该做为一个右键菜单的扩展，属于右键菜单的“更多”范畴的，和右键常用的功能重复的在这里都应该去掉，对文件夹和文件的操作，也可以把相关的功能放到这里面，比如可以把“标记”就可以放到这里面，标记功能并不太常用，
![image](https://user-images.githubusercontent.com/87513821/129647174-bb5ddbd4-5845-4692-9551-bdb56dadcf74.png)

**Comment by iD2073** [comment]
如果愿意增加，也可以增加个按颜色分类排序功能，

**Comment by rapmq0** [comment]
> 我觉得“标记”还是把文件夹和文件图标变色就可以了，文件名还是不要变色了，我罗列了两种标记方式，我个人比较喜欢第二种，见下图：
> 
> ![image](https://user-images.githubusercontent.com/87513821/129646217-5a42369c-326f-4b4f-b202-c949e700378f.png)

五颜六色的不美观啊

**Comment by iD2073** [comment]
> > 我觉得“标记”还是把文件夹和文件图标变色就可以了，文件名还是不要变色了，我罗列了两种标记方式，我个人比较喜欢第二种，见下图：
> > ![image](https://user-images.githubusercontent.com/87513821/129646217-5a42369c-326f-4b4f-b202-c949e700378f.png)
> 
> 五颜六色的不美观啊

那个属于个人标记行为，属于个人需要的功能，并不是所有的都五颜六色的

**Comment by iD2073** [comment]
秒传TXT文件可以保存到本地，也可以保存到网盘
![image](https://user-images.githubusercontent.com/87513821/129651437-19cfe7d6-27c8-4e77-8cd9-6c098f37984d.png)

**Comment by iD2073** [comment]
那个张三，李四等就是曾经移动过的目录，，那个路径就是当鼠标悬停X毫秒之后会显示这个目录具体是在哪里！

![image](https://user-images.githubusercontent.com/87513821/129652172-b7a2da97-e82b-4e5d-ad4d-e1c076964ff5.png)

**Comment by iD2073** [comment]
下图是百度云盘的软件，在界面中右键菜单，菜单是可以出现在界面以外的，
![image](https://user-images.githubusercontent.com/87513821/129655505-087f8a1c-7a30-4158-b558-c48c449966fb.png)

**Comment by rapmq0** [comment]
> 那个张三，李四等就是曾经移动过的目录，，那个路径就是当鼠标悬停X毫秒之后会显示这个目录具体是在哪里！
> 
> ![image](https://user-images.githubusercontent.com/87513821/129652172-b7a2da97-e82b-4e5d-ad4d-e1c076964ff5.png)

整这么复杂，点击移动直接显示选择目录的界面不就行了，移动过的历史目录在那个界面再显示才对，你这个太复杂了，不合适

**Comment by rapmq0** [comment]
而且一般都是在设置里选择下载目录，然后给个选项，是否每次下载都弹出目录选择框

**Comment by iD2073** [comment]
![image](https://user-images.githubusercontent.com/87513821/129661376-46a6a4e2-b66d-4e9d-817e-ae9d34a894e3.png)

**Comment by iD2073** [comment]
> 而且一般都是在设置里选择下载目录，然后给个选项，是否每次下载都弹出目录选择框

直接点击下载，就按默认设置的路径下载，如果想按网盘的结构路径下载就选下一级的路径下载，如果临时想把文件下载到桌面等地方，可以选自定义下载位置

**Comment by iD2073** [comment]
> > 那个张三，李四等就是曾经移动过的目录，，那个路径就是当鼠标悬停X毫秒之后会显示这个目录具体是在哪里！
> > ![image](https://user-images.githubusercontent.com/87513821/129652172-b7a2da97-e82b-4e5d-ad4d-e1c076964ff5.png)
> 
> 整这么复杂，点击移动直接显示选择目录的界面不就行了，移动过的历史目录在那个界面再显示才对，你这个太复杂了，不合适

正常移动只记录最后一次位置，我建议的功能那个可以记录多次，我比较喜欢这个功能，整理文件非常好用，这就像标记功能一样，我基本不用标记功能，但是总是会有人会用

**Comment by liupan1890** [comment]
@iD2073  
我需要认真看看，消化一下

但我现在没时间做这些，有太多功能在排队了

你应该在下个月再详细的跟我说这些，我那时候有时间正好就做了
现在我只是收藏一下这个issue，先别关闭，并不是不重视，而是我记住了理解了我不做，等下个月做的时候早就忘了，还是需要重新理解一遍对吧

容我些时间吧

**Comment by liupan1890** [comment]
### 1.说一下标记的区域啊，
我感觉仅图标变色。或者是方案二前面变色。都不够显眼
标记的作用是快速查找定位，并不是为了美观

比如按照方案二施行。
用户在快速查找文件时，2只眼睛，一只要盯着左边的前面颜色，另一只眼睛要盯着右边的文件名（因为会对很多文件标记为同样的颜色，并不是一个文件一个颜色，就算是一个文件一个颜色，用户也记不住具体的哪个文件是哪个颜色，只是大概的印象）

这个不合适，你不能把用户的注意力分裂。所以最开始就是设计的文件名变色

1.显眼，那么长的文件名都是红色的，一眼就看到了
2.集中，用户只需要看文件名




### 2.说一下那个红色小竖条啊，

那个是装饰用的，为的是提示一些新用户，v2有右键菜单了

1.如果不提示的话，大部分人不会知道v2可以用右键点击，因为v1是不支持右键的，老用户习惯了不用右键了，新用户不知道

2.还有有一点是给触摸屏用户的，点一下它就等于右键了，触摸屏的右键需要长时间按住才出，这样快一点

所以，这个竖条不能增加其他的功能，他只能用来触发右键菜单，而不是右键菜单的扩展（扩展那样确实太乱了）

因为作用仅仅是提示，再加上触摸屏用户非常少，所以把它弄得很小，因为弄大了太显眼，每一个文件都有这个按钮。
对用户是强刺激，这个是不合适的，要不弄大弄浅，要不弄小弄深。最后选择的小深

### 3.说一下保存位置
实际上，我并不理解“下载到桌面”这个需求，并不是说的“桌面”，是说的为什么不直接下载到固定的下载位置

设置里下载位置+按照网盘的完整路径 这多么科学合理可控？
为什么会有需要选择一个位置下载的需求呢？
你下载完再移动过去不一样吗？
下载时选择位置要点好几下鼠标，下载完移动也是点好几下鼠标，有什么区别呢？

所以这个功能我只会在设置里有这个设置项，用户愿意那就每次下载都选择吧，我也不跟用户犟，但是我还是推荐完整路径。下载完你再移动不一样吗--毕竟偶尔才有移动的需求

**Comment by rapmq0** [comment]
![QQ截图20210819075339](https://user-images.githubusercontent.com/83964337/129986575-67a7dba7-7220-4832-b225-f1abd8802ad7.png)
那么多下载器都已经铺好了路了，照着做一样的就行了，没必要再搞独特，用户习惯就是这样的，多余的东西也没人用

**Comment by liupan1890** [comment]
1.竖形右键菜单已在v2.8.28里提供
2.保存位置已在v2.8.28里恢复“每次下载都选择保存位置”设置，可以去掉网盘目录保存了
3.右键菜单中复制到，移动到的快捷历史功能
因为部分文件夹名很长，比如这个：
`盲侠大律师2020.全28集.国粤双语中字.2020.4K.WEB-DL.H265.AAC.@微信公众号SJJ279`
在实际开发时发现并不合适，另外，因为复制到和移动到功能交叉，
所以最终右键菜单中会有：
``````
复制到  盲侠大律师2020.全28集.国粤双语中字.2020.4K.WEB-DL.H265.AAC.@微信公众号SJJ279
移动到  盲侠大律师2020.全28集.国粤双语中字.2020.4K.WEB-DL.H265.AAC.@微信公众号SJJ279
``````
总之很不美观，所以未实现
