### ISSUE TITLE
删除下载记录的时候，有点问题

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#162]
![360截图17130414206260](https://user-images.githubusercontent.com/19268555/129734505-f658d85d-b751-43d0-9339-89318c6fe312.png)
![360截图1843070793104131](https://user-images.githubusercontent.com/19268555/129734490-282e46f6-f824-42a6-b7ea-d93ee1e14a17.png)
![360截图17040508332559](https://user-images.githubusercontent.com/19268555/129734500-e1fe7623-17a8-4786-8926-204a6579ad26.png)

同一个文件，删除记录会错位

**Comment by liupan1890** [comment]
收到，是BUG，应该是DownedID我忘了加时间了，下个版本会修正

**Comment by liupan1890** [comment]
在v2.8.18里已经修正
