### ISSUE TITLE
请问文件创建失败是我哪里弄错了嘛？

### ISSUE THREAD

**Issue by brkkad** [liupan1890/aliyunpan#164]
[图片](https://drive.google.com/file/d/1IMg5SVudSvE84NOrnJFH-CJc4bvRSXpc/view?usp=sharing)

**Comment by liupan1890** [comment]
根据图片

可能一：
因为你当时要秒传的文件很多，如果你设置了较高的同时下载任务数，可能会因为并发数太高导致失败

这种错误，不用管他，点击开始，重新上传就行了


可能二：你的网盘满了

可能三：当时你的网络不太好


其他的可能我就不知道了，你可以试一下v2.8.18，错误信息会多一点

**Comment by brkkad** [comment]
感谢回复我重新下载又好了
