### ISSUE TITLE
小白一个，看了大佬代码看不太懂。想请教下可以通过请求的方式获取直链吗

### ISSUE THREAD

**Issue by diudiubunuli** [liupan1890/aliyunpan#165]
阿里云盘网页版点击下载会有个get_download_url的请求。响应里面有个url，应该是文件下载地址。但是直接网页打开就显示403，请问下还需要什么请求参数吗 accesstoken之类的。

**Comment by liupan1890** [comment]
阿里云盘网页版点击下载会有个get_download_url的请求。响应里面有个url，应该是文件下载地址

>是的，没错

但是直接网页打开就显示403

>阿里云盘要求附带http头     Referer: https://www.aliyundrive.com/

>百度一下Referer 就明白了

>当你在阿里云盘网页版点击下载按钮时，浏览器会自动附加此Referer （因为你在www.aliyundrive.com这个网站上）

>自己复制下载链接，那就在下载时自己添加这个头，IDM新建任务时可以设置，Aria2c 创建下载任务时可以设置，迅雷创建下载任务时不能设置

**Comment by liupan1890** [comment]
> 阿里云盘网页版点击下载会有个get_download_url的请求。响应里面有个url，应该是文件下载地址
> 
> > 是的，没错
> 
> 但是直接网页打开就显示403
> 
> > 阿里云盘要求附带http头     Referer: https://www.aliyundrive.com/
> 
> > 百度一下Referer 就明白了
> 
> > 当你在阿里云盘网页版点击下载按钮时，浏览器会自动附加此Referer （因为你在www.aliyundrive.com这个网站上）
> 
> > 自己复制下载链接，那就在下载时自己添加这个头，IDM新建任务时可以设置，Aria2c 创建下载任务时可以设置，迅雷创建下载任务时不能设置
>
>>最后提示一下，这个下载链接默认都是15分钟内有效。必须在15分钟内开始下载，比如你现在复制了这个下载地址，然后立即暂停了，等2分钟以后点击继续下载，是可以继续下载的。但是等15分钟后再点击继续下载的话，是不可以的会403
