### ISSUE TITLE
迅雷云盘可以得到文件size，但好像拿不到sha1

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/aliyunpan#166]
迅雷云盘没有配额限制，于是我想使用迅雷云盘离线下载资源，然后通过接口导出需要的sha1和size，拼接成秒链格式，从而方便导入到阿里云盘中。

但在验证方案的时候我发现了一个问题，就是迅雷云盘的hash好像不是用sha1计算来的，但还是不甘心，于是发上来给大家看看
![](https://p.pstatp.com/origin/pgc-image/83484015560a47788d52d10142447ac1)

hash:2B1B40704C337A237FBF8748A5F2AC9542235CDC
size:898280799

拼接出的秒链：aliyunpan://S03E05 .mp4|2B1B40704C337A237FBF8748A5F2AC9542235CDC|898280799

**Comment by liupan1890** [comment]
这个思路放弃吧，

迅雷的hash都是迅雷的gcid
你可以用浏览器debug一下上传流程，会先计算出文件的gcid，赋值给hash

文件的gcid：
类似bt种子的计算的方式，
1.把一个文件按照一定的大小（比如4MB）分片（100MB的文件分成25片）
2.计算每一个分片的sha1
3.合并所有分片的sha1的数据，整体再sha1一次

得到了gcid

具体的算法或者流程，我也没细究。但是只要是分片sha1了，那就不可能根据这个流程或算法去倒推文件的sha1了。
只有完整的文件从头到尾才能计算sha1

so,不能得到sha1,不能实现秒传到阿里云盘

**Comment by Andrew201801** [comment]
哦哦，明白了，谢谢您！！
