### ISSUE TITLE
下载目录的问题

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#167]
我选择了6张图片，在网盘里的一个文件夹，下载目录也是设置好的。
下载完了以后在下载目录找了半天没找到，后来才发现是在我设置好的下载目录里把我网盘的目录又创建了一次，在文件夹里面。

**Comment by rapmq0** [comment]
我的图片在网盘里的目录是：图片/2021年/A组/A001.jpg
下载目录是：D:/图片
原本设想的是下载好的文件在：D:/图片/A001.jpg
但是事实是在：D:/图片/图片/2021年/A组/A001.jpg

**Comment by liupan1890** [comment]
就是这样设计的啊。。。。

在设置里有一个选项，“每次下载前提示选择下载位置”

v1.6.29可用。v2暂不可用

勾选这个选项，下载时会弹窗，然后选择D:/图片  好了，会下载到D:/图片/A001.jpg

**Comment by rapmq0** [comment]
第一代的那种下载保存方式就挺好的，不用专门加网盘目录的

**Comment by liupan1890** [comment]
第一代就是这样子的，就是有完整网盘目录的

区别是，第一代可以勾选，“每次下载前提示选择下载位置”，去掉网盘目录

第二代也可以勾选 “每次下载前提示选择下载位置”，去掉网盘目录，但是还没实现。仍在开发中
