### ISSUE TITLE
请问一下作者，啥时候出离线下载啊

### ISSUE THREAD

**Issue by gt562559842** [liupan1890/aliyunpan#168]
自己有个小nas 但是下载太慢了 裂开来

**Comment by fsnhljz** [comment]
NAS你可以找个“zx5253-webdav-aliyundriver1”，弄成webdav，然后同步，多方便

**Comment by liupan1890** [comment]
抱歉啊，我也不知道。当前排队的功能有很多，我开发也比较随性，想起什么来做什么。所以我也不知道具体的时间

**Comment by liupan1890** [comment]
等待阿里云盘官方”链接转存“功能公测后跟进
