### ISSUE TITLE
[v2优化建议]导入秒传 选择文件夹时直接定位到当前文件夹

### ISSUE THREAD

**Issue by KHLFYY** [liupan1890/aliyunpan#169]
v2预览版，导入秒传，弹出的选择导入位置 默认显示的好像是上回导入时选择的文件夹，
建议像v1.6这种，定位到当前打开的文件夹

**Comment by liupan1890** [comment]
对的，默认 是打开上次选择的位置

那我下回改一下

**Comment by liupan1890** [comment]
已经在v2.8.22中修正为当前文件夹
