### ISSUE TITLE
加个多线程吧

### ISSUE THREAD

**Issue by lanzhous** [liupan1890/aliyunpan#17]
单线程有点慢

**Comment by liupan1890** [comment]
慢主要是因为你操作的文件夹多，文件多，阿里云的限制多

列出文件：阿里云限制一次最多列出1千多个文件，大概在列2千多个文件时就会返回503---缓存溢出了，并且文件越多返回的越慢
批量操作（改名，回收站，移动）：阿里云限制一次最多操作100个文件，超过就会503

不过你的建议也确实很好，我会在下个版本里改进一些可以异步并发的操作，减少显示等待操作的时间

**Comment by liupan1890** [comment]
另外，一定不要跟百度网盘的分享操作去比较

比如你在百度网盘，点击一个文件夹，点击分享，是立即生成分享链接的，因为数据都在百度网盘的数据库里，特可以直接创建分享链接

而使用小白羊时，点击一个文件夹，点击分享，我需要遍历这个文件夹下所有的文件信息，然后统计，计算，合并，最后才可以创建分享链接。等待的时间主要都是在遍历文件信息了，因为我没有数据，需要从阿里云盘读取结果

所以仅从逻辑上就没有可比性了，肯定会慢的

**Comment by liupan1890** [comment]
v1.6.6已经修正了此问题，把大部分操作都改成多线程的了，经过对我网盘内的文件的一些测试（700G，1万+文件，300+文件夹），大部分操作改善比较明显，综合上看大概能减少一半的等待时间

如果是只操作几个文件，因为本身需要的时间太少了所以提升不太明显，主要还是大量文件操作提升很明显。等30秒和等1分钟感觉上差别巨大

**Comment by lanzhous** [comment]
感谢老大的回答，理解了，没想到阿里有这么限制，我单文件下载2M左右  用工具多线程可以跑满。我一次请求了12个文件下载，使用了最大任务数 才用20M左右宽带，多线程可能就能跑起来了。

**Comment by lanzhous** [comment]
加下载文件多线程~  目前单个文件下载最高就在3M左右。

**Comment by lanzhous** [comment]
能在设置加个下载多线程就好了~ 下载文件是单线程最高才3M宽带跑不起来！

**Comment by WHYEX3** [comment]
![image](https://user-images.githubusercontent.com/47862806/120896096-8f604100-c652-11eb-9bad-9166c74c53a5.png)
我这里貌似还算正常

**Comment by liupan1890** [comment]
> 能在设置加个下载多线程就好了~ 下载文件是单线程最高才3M宽带跑不起来！

针对单个文件，是2线程同时下载的
https://github.com/liupan1890/aliyunpan/blob/main/aliserver/data/Setting.go

然后你可以在设置里调整几个文件同时下载（比如默认3个文件同时*单文件2线程=最终是6线程同时下载的）

阿里云盘的下载速度一般都挺快，我实际测试2个线程，只下载一个文件，30MB/s ,我的宽带满了。

所以没有必要调整为单个文件*16线程之类的，调高线程数有时确实有用，但大部分时候作用不大。你调整同时下载的文件数也是一样的

**Comment by liupan1890** [comment]
@WHYEX3 额，然后就黑号了的样子
是怎么样子？我最近几天测试下载，大概下载了1TB的流量了---只有500G文件，重复下载，一直是正常的，但是我的移动宽带网络本身不稳定，下载速度在20MB/s-32MB/s之间晃悠

黑号是怎么表现？限速？怎么触发的黑号？

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120908521-ac6e3180-c69d-11eb-899e-a234bbd69305.png)
跑不起来，不知道为啥。

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120908647-d96f1400-c69e-11eb-9076-6e373a014967.png)
多线程就跑的起来

**Comment by liupan1890** [comment]
我刚刚上传了一次新的，你重新下载一便v1.6.6然后测试一下告诉我结果

原来：单文件2线程
新的：3文件同时下载时单文件4线程，4-7文件同时下载时单文件12线程，8-9文件同时下载时单文件16线程
默认的aria2c最高也就16线程了，测试一下告诉我速度有没有提升

**Comment by WHYEX3** [comment]
> 黑号是怎么表现？限速？怎么触发的黑号？
情况是这样的，我昨天看到这个issues之后尝试下载文件夹测试，速度正常，随后终止任务后并重新下载，就会显示部分任务一直在connecting或显示有速度但在网速监控工具看不到速度的情况，接下来出现文件列表刷新不出，尝试登录刷不出二维码和cookie登录失败的情况（网页版正常）..不过今天我并未成功复现，也许是其他原因造成的

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120917643-eada0f80-c6e2-11eb-8ea8-955dec0e1cd6.png)
还在只有20多M左右。9个任务一起下载的速度。好像下载也不是很稳定，官方限制了？我用浏览器单下一个文件也是在3M左右，用官方的客户端批量下载也在3M左右，只有用IDM才能跑起来。

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120917755-88cdda00-c6e3-11eb-83ce-2ff1d0cc48d6.png)
![image](https://user-images.githubusercontent.com/73158481/120917766-971bf600-c6e3-11eb-804c-ce2982549950.png)
以前挺快的，现在感觉只有多线程才跑的起来。

**Comment by lanzhous** [comment]
更新最新版的
![image](https://user-images.githubusercontent.com/73158481/120917883-2fb27600-c6e4-11eb-8b38-cd9468a41e3c.png)
开启最大9任务下载速度使用20M左右宽带。
![image](https://user-images.githubusercontent.com/73158481/120917973-9b94de80-c6e4-11eb-9a05-93ee2ab1a50a.png)
浏览器单线程最多1.5M-3M左右。
![image](https://user-images.githubusercontent.com/73158481/120917986-ab142780-c6e4-11eb-8056-5fda4d96e9c1.png)
现在感觉只有使用IDM多线程才跑的起来

**Comment by liupan1890** [comment]
idm开到了多少线程了？12线程？24线程？

我稍后再研究一下aria的多线程，是不是我设置的不对，9任务时每个应该是16线程，但你这截图感觉像单线程呢

我稍后再研究一下

**Comment by lanzhous** [comment]
IDM设置最大的32线程
![image](https://user-images.githubusercontent.com/73158481/120927826-ce56cb00-c714-11eb-8f12-19d90761b52f.png)
这速率就是单线程。
然后我今天试了批量。然后也出错了，。我挂了一会9个任务20M左右我看才下了20g左右就显示全部完成了。实际有60G的文件
但是他显示已经完成，文件也是还没合成的样子。

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/120928985-b46bb700-c719-11eb-8775-2e42c1ae9dda.png)

我看了一下，我的电脑上aria2c是正常的开启了16进程了。如图，左边 2文件正在下载，右图aria2c.exe进程的tcp链接有32条
你试一下你电脑上的，cmd看一下aria2c.exe进程的tcp连接数

**Comment by liupan1890** [comment]
命令行窗口中输入netstat -ano|findstr “8888”
其中8888就是任务管理器里显示的PID

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120929940-b6377980-c71d-11eb-915f-d8942c0ae2f2.png)
![image](https://user-images.githubusercontent.com/73158481/120929962-c94a4980-c71d-11eb-8a92-eadae07a7779.png)

**Comment by liupan1890** [comment]
如你截图所示，

1.9个文件同时下载

2.我是想让你数一下tcp连接个数，你的截图上我只能数到23条链接，剩下的没截到看不到了。
假设是27条，也就是每个文件3条链接，（3线程），并不是单线程在下载。所以并不是我代码调用aria2c时有问题。我正确的调用了，只是下载速度慢

3.截图中大量链接是CLOSE_WAIT,一般是服务器主动断开了这条链接---应该是你9个文件*16线程=144个链接，同时连接太多了，阿里云主动断开了（之前IDM，你是一个文件*32线程=32链接，现在是144个链接）


总之是阿里云服务器的限制，你可以是试试，同时只下载4个文件，看一下总速度，对比9个文件同时下载的总速度，看哪个快
如果都慢，我也是没办法，所以我一直在说，链接多了并没啥用因为会被阿里云的服务器限制

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/120983977-c8acc400-c7ac-11eb-8b79-41995346f485.png)
4个也大概在20M左右有时候突然到30m 一般一个文件也就是5M 应该算是有3线程了。
![image](https://user-images.githubusercontent.com/73158481/120984444-3e189480-c7ad-11eb-8c93-409cbea73dc8.png)
2任务在12M左右   单任务也不过了10M 不知道啥问题，我这边就是单任务在5M 超过6个任务时候就会下降。每个任务就不止5M了

**Comment by liupan1890** [comment]
在阿里云盘小白羊版设置里有个全局限速的选项，你没设置全局限速30M吧？
我测试过比如全局限速设置10MB，完了表现就跟你一样（一个文件就10M/s 2个文件就5MB/s 5个文件就2MB/s基本上是均分这10M）

暂时看，我也没有解决办法。因为这个可能是阿里云盘本身服务问题/或者说阿里云盘网络问题了，
我感觉20MB/s-30MB/s已经比官方客户端要快了吧？

**Comment by lanzhous** [comment]
![image](https://user-images.githubusercontent.com/73158481/121026872-150df900-c7d9-11eb-9df5-9d5305f1ffe3.png)
恩，多线程可能是多线程了。宽带不过还是跑步太起来，如果没啥解决办法~也可以，晚点试试一批下载多文件试试，上次的1.6.6版本批量出问题了。60G只下了20G的问题，但是提示全部完成，去看视频文件都是那种迅雷文件。试试5个任务 吧，9任务可能顶不住。

**Comment by liupan1890** [comment]
我记下了，我稍后会处理！
