### ISSUE TITLE
[bug]v2 导入秒传txt“解析文件时出错，内容不完整”

### ISSUE THREAD

**Issue by KHLFYY** [liupan1890/aliyunpan#170]
如题 v2导入v1.6生成的秒传txt，txt里Name是空，会导入失败（如图）
![image_116](https://user-images.githubusercontent.com/76054116/130256464-6c46fb4b-f382-4901-b865-7a86d0c4679b.png)

**Comment by KHLFYY** [comment]
![image_114](https://user-images.githubusercontent.com/76054116/130255434-c1baa787-3fe7-4a53-93b5-fc35ffe44d38.png)
![image_115](https://user-images.githubusercontent.com/76054116/130255440-909ae571-e23d-4ec7-9fcc-2bca5bcdf699.png)
v1.6可以成功使用

**Comment by KHLFYY** [comment]
刚看到 原来 #158 里有人提到过这个bug了

**Comment by liupan1890** [comment]
恩，是个BUG，下次发布时会修正

**Comment by liupan1890** [comment]
这个BUG只出现在 

在v1中查看秒传txt的内容时Ctrl+A全部复制，或者点击“复制全部文字”按钮，
然后在v2中粘贴到“导入链接”--“秒传(txt)” 中吧？

是没有正确处理utf8文件头的BUG，并不是因为Name为空导致的

下个版本中已修正这个问题

使用v1创建的秒传txt文件，在v2中直接打开，然后点顶部的击导入秒传txt按钮
![无标题](https://user-images.githubusercontent.com/67817756/130305480-b92b48b8-6d5e-4fee-9119-30394953ecba.png)
，可以直接导入，并不会出现这个界面
![130256555-ed52564e-4561-4247-bc68-4ee641333c2b](https://user-images.githubusercontent.com/67817756/130305449-ec973864-ac13-47b0-bdf1-fac1772e0d4f.png)

所以只出现在了v1和v2混用时，我没测试到位

**Comment by KHLFYY** [comment]
> 在v1中查看秒传txt的内容时Ctrl+A全部复制，或者点击“复制全部文字”按钮，
然后在v2中粘贴到“导入链接”--“秒传(txt)” 中吧？

是的

辛苦了，大佬加油

**Comment by liupan1890** [comment]
已经在v2.8.22中修正此BUG，同时也修正了一些其他原因（格式问题）导致的解析失败
