### ISSUE TITLE
作者您好，请问导入秒传出现错误，显示json转换失败是怎么回事？

### ISSUE THREAD

**Issue by bulabulalaen** [liupan1890/aliyunpan#171]
版本号1.6.29
![1](https://user-images.githubusercontent.com/53595830/130320157-2acd3fc9-7172-4dd5-af15-f07f26943845.jpg)

**Comment by liupan1890** [comment]
额，我也看不出哪里有问题来，我看着格式倒是正确的

1.可能json的字符串有特殊字符---我没看到
2.可能开头结尾有特殊字符（有些特殊字符不显示，比如换行，制表符，等等）
3.可能网络不好，重试一下就行了--v1.6.29需要联网格式化json字符串有时我服务器网络不好就会显示错误。v2开始是本地直接格式化的

**Comment by liupan1890** [comment]
忘了说解决方法了

https://www.bejson.com/

把内容粘贴进去，点击“格式化校验”

如果是内容有问题，就会提示哪里有问题。如果内容正确，就会提示“正确的JSON”

最后点击“复制”按钮，复制后，粘贴到小白羊

为的就是格式化一遍，确认内容格式正确

**Comment by bulabulalaen** [comment]
> 忘了说解决方法了
> 
> https://www.bejson.com/
> 
> 把内容粘贴进去，点击“格式化校验”
> 
> 如果是内容有问题，就会提示哪里有问题。如果内容正确，就会提示“正确的JSON”
> 
> 最后点击“复制”按钮，复制后，粘贴到小白羊
> 
> 为的就是格式化一遍，确认内容格式正确

好的，感谢！
