### ISSUE TITLE
1.6.29Mac版，提示无法连接后台进程。请退出重新打开!

### ISSUE THREAD

**Issue by weilezhu2021** [liupan1890/aliyunpan#173]
我下载了了1.6.29Mac版，但总提示无法连接后台进程。请退出重新打开。请问如何解决？谢谢！

**Comment by liupan1890** [comment]
说实话，我也不知道是为什么

提示无法连接后台进程:
小白羊v1.6.29启动时会自动运行aliserver这个进程，如果这个进程没有顺利运行，那就会提示这个错误。
但是为什么没有顺利运行，就是个迷了

试一下v2.8.22吧，v2不在需要运行aliserver了，自然不会出现这个错误提示

**Comment by weilezhu2021** [comment]
我去試試看。非常感謝你的及時回覆和提供如此出眾，好用的應用👍

      Hondy
