### ISSUE TITLE
关于新功能的建议

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [liupan1890/aliyunpan#175]
1.建议v2尽快支持深色的夜间模式吧 （因为自己的win10日常开深色配色 然后v2只有红白配色雀食有点辣眼睛...只能先用着v1了
） 其实v1的深色模式配色就挺舒服的，如果把这个套用到v2上不麻烦的话还是希望作者大大尽快吧，谢谢啦~
_2.v2的窗口不能自定义大小（就是拖动窗口改变大小 v1是可以的） 只能切换全屏和窗口模式，希望可以增加这个功能_
这个是我纯属自己眼瞎了，只是v2的标题栏无法这样，在窗口的其他位置进行操作是没用问题的

（以下是个人的亿点闲话）
P.S.作者大大的软件还是很好用的，非常不错的第三方端，先在这里口头支持一波；然后之前是想建议添加保险箱查看的功能来着——然后翻了issue之后发现作者大大因为注意用户隐私的原因就不打算作这个功能了，从这个角度考虑的话还是可以再好评一波的；既然作者大大开发也比较随性...如果愿意的话那能先把这个深色模式作了嘛 辛苦了~

**Comment by iD2073** [comment]
我也呼吁优先开发深色模式两次了，可能小哥太忙了吧！8.22版本以为会上线深色模式，但是还是失望了，我也是所有的软件有深色模式的已经全部设置了深色模式，所以就更期待小白羊能尽早适配深色模式，期待吧……！哎！哎！哎！小哥辛苦

**Comment by liupan1890** [comment]
收到

**Comment by iD2073** [comment]
> 1.建议v2尽快支持深色的夜间模式吧 （因为自己的win10日常开深色配色 然后v2只有红白配色雀食有点辣眼睛...只能先用着v1了
> ） 其实v1的深色模式配色就挺舒服的，如果把这个套用到v2上不麻烦的话还是希望作者大大尽快吧，谢谢啦~
> _2.v2的窗口不能自定义大小（就是拖动窗口改变大小 v1是可以的） 只能切换全屏和窗口模式，希望可以增加这个功能_
> 这个是我纯属自己眼瞎了，只是v2的标题栏无法这样，在窗口的其他位置进行操作是没用问题的
> 
> （以下是个人的亿点闲话）
> P.S.作者大大的软件还是很好用的，非常不错的第三方端，先在这里口头支持一波；然后之前是想建议添加保险箱查看的功能来着——然后翻了issue之后发现作者大大因为注意用户隐私的原因就不打算作这个功能了，从这个角度考虑的话还是可以再好评一波的；既然作者大大开发也比较随性...如果愿意的话那能先把这个深色模式作了嘛 辛苦了~

它的那个窗口调整区域，黄色标注的才可以调整，
![image](https://user-images.githubusercontent.com/87513821/130541051-d16b0356-10f1-4d64-82eb-3f1c219ffd07.png)

**Comment by liupan1890** [comment]
顶部不能调整大小的BUG，会在下次更新时修正

>而且这个窗口还有一个BUG就是，当记忆最大化时，双击标题栏只在最大化和满屏之间切换，并不能恢复到小窗口状态

这个是什么意思？
是说，先手动拖动窗口到最大，然后再双击标题栏。结果窗口一直是最大的状态（全屏/最大）是吗，
比如说屏幕大小1280，拖动窗口到1100，然后双击标题栏。窗口一直最大（全屏/1100）之间切换，不会变回800去，是这个意思吗？

**Comment by iD2073** [comment]
如下面这个文件，您导入到你的网盘即可     

2.gif|5872604|37D601C5E55CEDF80F6F0E58EC16123032F8C66A

可时我也建议当分享一个文件时可以直接生成像上面那样的简单的字符串，   #[直接发送给对方就可以直接导入了，生成的秒传文件，秒传文件也不太方便，

![image](https://user-images.githubusercontent.com/87513821/130559643-6eb1ed96-9c33-4723-998a-b75f3d5e5397.png)

**Comment by liupan1890** [comment]
明白了，这是个BUG，我会再下个版本中修正。当最大化时不需要保存窗口大小


关于“分享一个文件时可以直接生成像上面那样的简单的字符串”

小白羊并不提供创建秒传链接的功能。需要用户自己查找秒传脚本

至于秒传txt和秒传链接本质上有什么区别

区别1：他不叫秒传链接
区别2：秒传txt是用来扩展网盘空间的，不是用来分享的

用户非要拿秒传txt去分享，那是用户的操作，不可控。但小白羊并不提供分享操作

这样解释应该能Get到重点

**Comment by iD2073** [comment]
你的初衷可能确实不是用来分享的，可是每次给朋友发我都要到网页版用李恒道的插件，可以生成字符串发给朋友，这个并不能称为链接，而是用别一种方式分享而已，如果不属于侵权也可以生成  aliyunpan://文件名.zip|xxxxxxxx|xxxxxxxx   也可以实现单文件分享

**Comment by liupan1890** [comment]
不论以何种方式（链接/字符串/sha1特征码）分享都是分享，

划重点：小白羊并不提供分享功能

**Comment by liupan1890** [comment]
1.深色的夜间模式 已在v2.8.28里提供
2.窗口调整区域BUG  一直最大化BUG 已在v2.8.28里修正
