### ISSUE TITLE
【v2 优化建议】1.选择了文件时顶部按钮自动变化；2.点击刷新时收起目录树下子文件夹

### ISSUE THREAD

**Issue by KHLFYY** [liupan1890/aliyunpan#176]
v2.8.22  如题

### 1.选择了文件时顶部按钮自动变化
当选择文件后，将顶部按钮变为”下载“等按钮，就像v1.6一样，如图一
![v1.6的顶部按钮](https://user-images.githubusercontent.com/76054116/130451458-0caa38e4-8fc0-40ac-b2b3-2943228de3b9.png)

现在的v2版本是这样的（如图二）
![v2的顶部按钮](https://user-images.githubusercontent.com/76054116/130451580-849de890-f0b9-4e90-b63b-2e0a3feb7a20.png)

### 2.点击“刷新”时收起目录树下子文件夹
现在的v2版本，点击刷新按钮时，目录树中 它的子文件夹 没有自己收起，希望作者把v1.6的这个功能添加回来
![刷新按钮](https://user-images.githubusercontent.com/76054116/130452079-cb9a5767-4d96-4d15-b593-c2db50b130c8.png)

现在很多人都支持小白羊，大家纷纷提出自己的想法讨论；
作者也把小白羊小白羊已经越来越好了，辛苦了
您按照自己的规划开发就好，不要给自己太大压力

**Comment by liupan1890** [comment]
1.选择了文件时顶部按钮自动变化

当你多选时，就会变化了。单选一个文件，不会变化，因为只选中一个文件或者一个文件夹，要强制你用右键下载，而不是顶部下载按钮。只有多选时，才有顶部按钮

不然右键菜单就没有意义了


2.点击“刷新”时收起目录树下子文件夹

这个跟我说一下有什么用呢？

**Comment by iD2073** [comment]
有一个问题您说强制右键，右键确实有些时候方便，但是经常导致上面的功能按钮变化让自己发蒙。还有一些情况是，当多选文件后再鼠标右键后只有鼠标指针所在的文件是选中的状态，其他的都自动取消选择，这个也不符合文件操作的习惯啊！还有一个现象有时右键是有延迟的，建议在不选任何文件时显示上面图二        只要有选择文件时显示文件时显示上面图一      


1. 优先考虑上线深色主题模式
2. 希望能增加空白处右键菜单【上传】+【导入秒传】+【刷新】+【新建】
3. 建议增加Backspace快捷键为返回
4. 建议增加Ctrl+鼠标左键 可以拖动框选功能
5. 建议恢复 地址栏功能，并加入超长地址可以瀑布列表显示功能，

**Comment by KHLFYY** [comment]
1. 多选会变这个 是我自己没发现，您的意思我明白了；

    但是如果能更改一下，单选多选统一一下（都会变），我个人更加倾向于都会变；

    如果按照您的想法，单选不更改，这个整体逻辑也是能理解的。
---------------

2. 主要是打开几个目录后，目录树就会比较杂乱，

    刷新收起之后可以更方便的使用目录树查找别的文件夹；

    有时候我本次使用完毕后，就会点到根目录刷新收起全部，等到过一会使用网盘时也更好查找使用目录树。



     详细情况有一下几点：

                (1) 当打开的文件目录比较长（就是比较深的文件夹）的时候，目录树宽度大。

                (2) 当打开的文件夹下有很多子文件夹的时候，目录树比较长。
                     
    刷新收起可以缩短长度，一眼把同级别（和以上级）文件夹看全，方便查找其他文件夹。
      **刷新收起能让目录树更加 整洁 易用**

    希望您能考虑我的第二条意见

**Comment by liupan1890** [comment]
@iD2073 

1.右键是单个文件的功能
2.顶部是多个文件的功能

当你这样去理解时，就会比较清楚。
现在你选择了多个文件，就要点顶部，这个时候你点右键，就会取消其他选中，只选择一个，因为右键只是单个文件

因为当前批量改名功能并没有上线，所以当前右键设定为只单个文件。等以后批量改名功能上线了，就会修正为可以多文件右键了

这个问题和主要是我没预料到批量改名功能一个月了还没能做到，我错误的估算了自己的开发速度。



优先考虑上线深色主题模式
>会的
希望能增加空白处右键菜单【上传】+【导入秒传】+【刷新】+【新建】
>不要，空白处是哪？根本没有空白处啊，都占满了
建议增加Backspace快捷键为返回
>不要，增加用户学习难度
建议增加Ctrl+鼠标左键 可以拖动框选功能
>拖动框选我明白，就像阿里云盘官方版一样，那么为什么要按Ctrl+鼠标左键呢？官方是直接左键拖选。
这不是重点，
1.重点是仅仅框选选不了几个文件（一屏幕显示不了几个文件），所以不增加框选了，会增加你之前提到的“区间”按钮
2.既然是按键盘了，直接按Shift不就能框选了？（批量连续选中）

建议恢复 地址栏功能，并加入超长地址可以瀑布列表显示功能，
>会的

**Comment by liupan1890** [comment]
@KHLFYY 
问题1，好吧我想偷懒少打几个字
我自己使用中遇到的情况是这样
1.我先点击某个文件操作（点击xxxx 第27集.mp4 在线预览）
2.过了一混我需要导入文件(需要点击顶部导入秒传链接)

问题来了，按照单选和多选都变的模式。此时顶部没有“导入”
我需要
方案1.找到第27集.mp4 点击取消选中
方案2.点击全选（为了全部选中）点击全选（为了反选，既全部取消选中）

最终，没有任何文件选中了，显示了“导入按钮”了，我可以导入了

经常有这种情景，再比如一个文件夹内有100个文件，我习惯性滚动一下，点一下某个文件，再向下滚动

点一下某个文件有什么用吗？没有，纯粹是习惯，就像定位一样
我想要找第88个文件，此时滚动到了第44个，习惯性点一下44，我明白我需要继续滚动。点一下就是为了定位，心理暗示，习惯。没有任何意义

此时同上，我需要导入时，又要点2下全选，才能显示“导入”按钮

所以我设计为，单选上面不变，因为单选有右键，用不到上面，变或者不变是一样的，最多能满足强迫症习惯统一。

反过来按照现在的设计，不管之前操作了什么，如果只是单选状态，我还可以直接导入（新建/上传/导入）
即使是多选状态，我也不需要点击2次全选按钮，直接随便点击一个文件，就可以显示导入按钮了

so 是有实际需求的



问题2：刷新收缩
这个确实，我会再下个版本增加这个功能的

**Comment by iD2073** [comment]
关于顶部的工具栏，看你的解释，理解了，由于软件的设计目前也只能这样，没有资源管理器的那些模式所以目前的设计也是合理的，

【建议增加Backspace快捷键为返回】，这个功能其实资源管理器以及很多第三方资源管理软件Backspace都是返回功能，也包括大部分看图软件这个快捷键也都是返回功能，我想不需要什么学习，常用的自然懂，我也是按这个键没有反应才提出来的，百度云盘和天翼云盘这个键也是都是返回功能

【建议增加Ctrl+鼠标左键 可以拖动框选功能】这个功能也就是个辅助，如果以后上线【区间选】和【反选】，那前面所提的就忽略吧，

地址栏的功能，在其他帖子我已经发过了，希望能参考一下吧，自己ps的，嘻嘻

**Comment by liupan1890** [comment]
我看到了，我记得是回复了

**Comment by KHLFYY** [comment]
> @KHLFYY
> 问题1，好吧我想偷懒少打几个字
> ………………
> so 是有实际需求的
> 
> 问题2：刷新收缩
> 这个确实，我会再下个版本增加这个功能的

OK 作者辛苦 加油！

**Comment by KHLFYY** [comment]
@liupan1890  

还有个最近发现的问题：

v2创建秒传的速度明显慢于v1.6 

是因为v1.6直接创建，而v2需要列出文件的问题吗？

这个能不能想办法优化一下呢

**Comment by liupan1890** [comment]
帮我录个视频我看看是怎么回事

在我的电脑上，
使用v2,创建 秒传_根目录_12697文件_2.8TB.txt  （包含345个文件夹），从选中文件到点击创建，到保存完txt，总用时3秒多

使用v1同样的文件，转了2分钟还没创建好，仍在转圈，我就取消了

所以你提到  v2创建秒传的速度明显慢于v1.6  我就不知道是啥情况了，你给我录个像我看一下我应该就能知道是怎么回事了

**Comment by KHLFYY** [comment]
> 帮我录个视频我看看是怎么回事
> 
> 在我的电脑上，
> 使用v2,创建 秒传_根目录_12697文件_2.8TB.txt （包含345个文件夹），从选中文件到点击创建，到保存完txt，总用时3秒多
> 
> 使用v1同样的文件，转了2分钟还没创建好，仍在转圈，我就取消了
> 
> 所以你提到 v2创建秒传的速度明显慢于v1.6 我就不知道是啥情况了，你给我录个像我看一下我应该就能知道是怎么回事了

我又多试了几个，这应该是一种特殊情况。

**刚刚**保存的分享链接的文件（我是在网页端保存的），**并且没有在v2打开过该文件夹**，**立即**去创建秒传，用v2会比v1慢。是我太着急了哈哈哈哈哈哈哈。

我又试了几个正常情况的文件，确实是v2比v1快。

这个应该不是有问题，打开文件夹之后再创建秒传就可以了。

录屏如下：


https://user-images.githubusercontent.com/76054116/130759535-38d27141-82c9-4027-8aff-261c83874371.mp4

**Comment by liupan1890** [comment]
看录像，确实是有BUG。我应该明白问题出在哪了，应该是v2刷新时卡住了，我没这样用过（保存分享后，然后立即创建txt）

之后v2正常了是因为已经加载完缓存了

所以问题就出在，没有缓存时，创建txt，卡住了。所以应该就是BUG了，我稍后会调试一下看看，会修复这个BUG的

**Comment by liupan1890** [comment]
1. 点击刷新时收起目录树下子文件夹 已在v2.8.28里增加此功能

2.创建秒传时一直列文件中不显示的BUG 已在v2.8.28里修正
