### ISSUE TITLE
在加载大量文件时，提示词可能出错；线程反应迟钝

### ISSUE THREAD

**Issue by ptrzs3** [liupan1890/aliyunpan#177]
在加载大量文件时，小白羊提示“(文件数)/100 秒”，这里是不是应该把结果显示出来？而不是把公式显示出来？
从我开发Qt项目的经验，这可能是一个失误，当然也可能这是该项目的一个桩 ^_^

同样，在有大量小文件上传时，小白羊会出现假死，可能是受限于网络条件，或者应该多开几个线程？

但是不可否认，这是非常优秀的第三方客户端

**Comment by liupan1890** [comment]
1.小白羊提示“(文件数)/100 秒”
在v1里是一边加载一边显示的，但后来发现除了好看没啥用，并且因为频发刷新列表会有性能压力。所以v2里就直接等待全部加载完再显示了（v1加载中虽然显示也不能操作，因为数据不完整，强行操作可能会导致用户认为的文件错乱/丢失--假象）

这个其实是我偷懒，实在懒得做，一般人一个文件夹里也就几百个文件，2-3秒就差不多了。非要在这2-3秒里显示部分数据，没啥意义吧？遇到一个文件夹里有一万多文件的，用户心里自然有预期，会很慢。那就耐心等待，反正有加载中动画了。现不显示区别也不大，反正也不让你操作


2.在有大量小文件上传时，小白羊会出现假死
这个能否细说一下，我想应该是大量上传不能秒传的小文件吧？

说说你的电脑配置啦，上传多少个文件啦，是一直卡，还是特定时间突然卡？最好能帮我录个屏

因为我自己测试过几十次上传大量小文件了（2000多个图片/4000个封面/8000多个封面+歌词）
但我基本都是秒传的--测试过一次后面都是重复文件，都会秒传。

我能想到的可能是对小文件我没开多线程计算sha1,因为小文件sha1计算在我电脑上几百毫秒就出来了，也没显示卡--因为计算是一个后台进程，所以不应高影响主界面卡才对

对大文件，是后台进程再开3个独立线程去分别计算，所以大文件应该不会卡

**Comment by liupan1890** [comment]
另外有一点，如果是USB外挂的机械硬盘，确实会有卡顿，不过是整个电脑都卡顿，比如鼠标移动中突然没响应，过300毫秒突然快速移动这样，是机械硬盘读取特性，整个电脑都卡

**Comment by ptrzs3** [comment]
![Snipaste_2021-08-24_23-52-21](https://user-images.githubusercontent.com/87363142/130649333-f1a72b80-e57b-42f9-9e74-fc312981bd23.png)
![Snipaste_2021-08-24_23-52-43](https://user-images.githubusercontent.com/87363142/130649345-c351c4d9-196a-4190-a40c-7f27148aeaa3.png)


https://user-images.githubusercontent.com/87363142/130650774-e98d3a05-79da-4628-b955-eca3aaa457e2.mp4

可能是我一次性上传的文件太多了，达到了26万个，绝大多数文件体积小于700K，不可否认这是一个非常极端的情况
我的电脑性能可以保证的，R7 4800U，三星NVME固态硬盘，100M下行带宽

**Comment by liupan1890** [comment]
嗯，可能是文件确实有点多。我最多就测试过1万多个文件上传---因为我没有这么多的文件，所以没考虑到这个情况

我稍后会对这种20万文件的，进行测试，看是哪里卡，感觉是读取文件卡住了，不是硬盘卡住了，是小白羊解析计算20万个文件，生成20万条记录，保存20万条记录到数据库(浏览器的IndexedDB)。刷新20万条记录到UI，这个过程卡住了

稍后分析一下看是计算卡住了还是数据库保存卡住了

你上传完，最好在“传输”--“已上传完” 那里清空上传记录，因为26万条的话，估计数据库文件体积就比较大了。清空了就会释放掉，不然白白占用硬盘空间（C:\Users\用户名\AppData\Roaming\alixby\IndexedDB）

**Comment by liupan1890** [comment]
第一次创建上传任务时会卡，我知道了，那么，之后呢？刷新下载进度，文件上传，或者其他操作。应该都不卡了吧？如果还有哪里卡顿也说一下

**Comment by ptrzs3** [comment]
统计完成上传文件数之后就不再有任何卡顿

**Comment by liupan1890** [comment]
嗯，证实了，是IndexedDB的锅，写入20万条记录，IndexedDB需要分钟级别（大概是10万/分钟，这个具体跟文件名/路径/电脑性能等有关），当然生成20万条记录，本身也对性能要求较高，

1.以后我会把生成记录这个放到后台进程里去做
2.以后会尝试一下，替换掉IndexedDB，使用sqlite，写入速度更高（一开始不用sqlite是因为electron+sqlite，都是各个系统单独编译一遍很费劲的，但没想到有一次性上传20多万个文件的情景。。。）

**Comment by power12317** [comment]
路过提个醒，因为是用了electron，renderer进程是跑在chromium里的，所以你懂的会受到chromium的单域名最大6连接数限制，开同时上传50个文件没有意义，解决方法是把阿里云的上传域名加到命令行开关里 
参考：https://www.electronjs.org/docs/api/command-line-switches#--ignore-connections-limitdomains
我自行解包了在electron-main.js里添加了如下代码 然后多文件上传，50任务速度起飞 
e.commandLine.appendSwitch("ignore-connections-limit","bj29.cn-beijing.data.alicloudccp.com");
因为这个要指定域名 不排除以后阿里云盘会有别的域名 又得每次更新加上才能解除限制，或者就改electron的源代码默认全部无限制再编译了。。。

最后偷偷提一个建议 阿里云盘因为都是内地服务器，测试都在内地速度还可以，海外服务器上传真的慢如蜗牛 有时候单线程20kb/s都没有，所以希望能将大文件改成多线程上传，这样能大大加快海外的上传速度，如同上面提的同时开50个任务一样的快速。
PS：想改多线程上传的想法早就有了，但是解包后的代码实在啃不动，只好在这里提建议了/(ㄒoㄒ)/~~

**Comment by liupan1890** [comment]
1.同时开50个上传，是为了加速小文件上传，并不适用于大文件上传（就算解除了同域限制，当上传大文件时高并发作用也不大）

2.阿里云盘当前通过海外，速度真的慢的一批，测试日本vps都慢的不行


3.希望能将大文件改成多线程上传

这个无法实现，阿里云盘官方限制了，因为阿里云盘的上传，只支持顺序上传

大文件先分片，每个分片多大不限制你（当前都是10MB一片），
但是每一个分片本身只能一次性上传，既分片本身不能分成多线程
然后所有分片必须按照顺序一个一个的上传，既所有分片都不能乱序/并序/多线程上传

多线程只能是文件多线程，既同时上传多个文件。但每个文件本身只能单线程

我也不知道官方为什么这样去限制

**Comment by power12317** [comment]
感谢答复 
1、单分片上传过程当然不能实现多线程，因为我没测试过自己写脚本尝试多分片同时上传，单从接口上来看以为是可以多分片乱序并发上传的，所以并不知道阿里还有分片必须顺序上传的策略，这样确实做不到整个文件的多线程上传 
2、海外上传速度只能忍忍了，我尝试了绑host改节点的方式 有些节点能起飞 50个任务 最高跑到30mb/s 但是大概传了一段时间后就被限制到1mb/s了 之前大陆服务器上传也有这种情况 ，估计是阿里有一个流控策略，单账号或者单ip一段时间内上传超过多少G后限速。
3、我确实是海外服务器 200多个几百mb-1G的文件 其中也有几个快30G的文件同时上传 解除同域限制后 速度才能叠加得这么快，当然最后传完剩下几个最大的文件龟速上传，目前只能说一种无解状态了。
所以，上面我提的建议也确实没必要了，仅仅是我个人习惯问题。

目前感觉国内这些不限速网盘都很怕遇到大量无脑上传的用户，包括迅雷网盘的非白金会员一天20G限制 阿里云网盘的上传限速，还有百度云的海外上传龟速以及大量上传后限速等等 。。

**Comment by liupan1890** [comment]
下次更新时，解除同源策略的命令我也会加上的，对国内（绝大部分用户都是国内）虽然没啥用，但考虑到国外的话，尤其是几十个文件一起上传的时候，确实也能提速，所以会加上的

**Comment by liupan1890** [comment]
v2.9.15已经修复了此问题，不会再卡顿了
