### ISSUE TITLE
请问如何更换默认播放器

### ISSUE THREAD

**Issue by zhangsenpei** [liupan1890/aliyunpan#178]
设置中未找到播放器设置选项，仅有播放规格可选，我想换自己常用的播放器插帧观看

**Comment by liupan1890** [comment]
当前，仅支持更换为Potplayer，请参阅https://github.com/liupan1890/aliyunpan/blob/main/%E4%BD%BF%E7%94%A8PotPlayer.md

当前不支持其它播放器，是因为阿里云盘限制，其它播放器不能播放
