### ISSUE TITLE
导入大文件的秒传链接显示导入秒传任务失败

### ISSUE THREAD

**Issue by goodnighteveryone** [liupan1890/aliyunpan#179]
![image](https://user-images.githubusercontent.com/49894559/130741436-9465532a-3db7-4fcb-9a94-dd008543bae3.png)
秒传链接解析成功，但是显示导入任务失败

**Comment by liupan1890** [comment]
在v1.6.29 因为导入秒传链接时，会先创建里面的所有文件夹，因为创建文件夹速度太快太多，会导致阿里云盘拒绝访问，最终提示导入失败

解决方案1.重新点击导入，多次导入，有的时候就会成功了
解决方案2.下载v2.8.22版，v2里做了限流，可以一次成功，不会触发错误

**Comment by goodnighteveryone** [comment]
> 在v1.6.29 因为导入秒传链接时，会先创建里面的所有文件夹，因为创建文件夹速度太快太多，会导致阿里云盘拒绝访问，最终提示导入失败
> 
> 解决方案1.重新点击导入，多次导入，有的时候就会成功了
> 解决方案2.下载v2.8.22版，v2里做了限流，可以一次成功，不会触发错误

好的，麻烦啦，谢谢您
