### ISSUE TITLE
能否添加web版

### ISSUE THREAD

**Issue by SkfyZ** [liupan1890/aliyunpan#18]
想要挂载到服务器上

**Comment by liupan1890** [comment]
想要实现也不难的：
1.有一半的功能是golang开发的，所以你需要在你的服务器上手动运行data\aliserver.exe （linux？拉一份源码，用go命令发布成linux版本就行了）
2.有一般的功能（UI）是flutter开发的，你只需要自己拉一份源码，用flutter命令发布成web版就可以了

以上操作啊，都不涉及源码的改动，只是编译命令跑一下就行了
当然了，有一小部份功能会受影响，
比如上传文件，远程无法上传文件，浏览器不支持提供完整的文件路径和访问本地文件
其他细节我没认真想，可能需要实际使用的时候就全发现了

<br/>
<br/>
我自己不会支持web，因为我没有这个需求，也没有这个精力去维护一份特殊的web版本，只能你自己试一下了
