### ISSUE TITLE
potplayer 如何使用命令播放阿里云视频

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#185]
tip: 按照大佬的文档是用pot可以播放的，但是用链接直接播放不太行，不知道怎么设置 referer的

pot是可以播放 iso 视频的，但直接点击是不是跳转到播放器的，所以我想复制链接，在pot上播放，有什么方法吗
比如说命令什么的

**Comment by liupan1890** [comment]
cmd命令

``````
Potplayer.exe /referer=https://www.aliyundrive.com/ DOWNURL
``````

1.Potplayer.exe 可以直接在Potplayer.exe 所在文件夹里打开cmd，执行命令。否则需要输入完整的路径，例如：
``````
D:\Potplayer\Potplayer.exe /referer=https://www.aliyundrive.com/ DOWNURL
``````

2.DOWNURL 替换成你自己的URL （可以在 文件--详情--复制下载链接按钮）

3. 注意空格，注意完整，不要缺漏字符

``````
Potplayer.exe空格/referer=https://www.aliyundrive.com/空格DOWNURL
``````

**Comment by rapmq0** [comment]
我直接把自带的MPV播放器删了，下载下来看

**Comment by yayaleslie** [comment]
没成功，是不是还有什么条件，这个地址要不要引号
没引号：
![image](https://user-images.githubusercontent.com/19268555/131209146-73a789cf-2d9b-42f7-a3f5-ec097df30c87.png)


有引号：
![image](https://user-images.githubusercontent.com/19268555/131209114-387fdffa-3502-44c0-ab91-3e589804a6d9.png)
![image](https://user-images.githubusercontent.com/19268555/131209130-dff23b5a-adc5-4a40-af9d-e28481ee9a47.png)

**Comment by liupan1890** [comment]
需要有引号，我都给忘了哈

至于你第二张截图，有引号时，提示“该媒体无法播放”

说明Potplayer不支持联网播放ISO文件，是Potplayer本身的问题。跟调用参数无关

Potplayer的联网播放，并不是什么格式都支持的，毕竟联网和本地还是不一样的

**Comment by yayaleslie** [comment]
那应该是了，又试了个MP4是可以的，看来只能下载下来看了，哈哈
