### ISSUE TITLE
  有时候自己都忘记文件放哪个目录了，后面有没有计划添加一个搜索功能

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#186]
![360截图20210829153225265](https://user-images.githubusercontent.com/38945550/131242491-e8898985-5eac-4527-85b1-d68c949e1a10.jpg)

**Comment by liupan1890** [comment]
会的，后期会增加阿里云盘的搜索功能

**Comment by cynzsm** [comment]
这个是有必要  建议优先级提高一点

**Comment by liupan1890** [comment]
在v2.11.14里已经支持搜索文件了
