### ISSUE TITLE
大佬考虑开发安卓上的小白羊吗？

### ISSUE THREAD

**Issue by baishanshaonian** [liupan1890/aliyunpan#187]
安卓平台上的阿里云盘并不好用
---
如果考虑的话，希望可以把在线视频播放当重点来做，比如支持第三方播放器（Mxplayer等）。
一点小小的建议哦！

**Comment by liupan1890** [comment]
不考虑，因为当前使用的electron并不支持安卓，所以开发安卓的话要从头开始，没有这么多时间了

**Comment by gt562559842** [comment]
> 不考虑，因为当前使用的electron并不支持安卓，所以开发安卓的话要从头开始，没有这么多时间了

alixby不是用flutter写的吗 可以搞安卓啊

**Comment by rapmq0** [comment]
iOS的也不好用啊，官方简直太垃圾了，跟天翼客户端比简直烂的透彻
