### ISSUE TITLE
大佬，预览版新功能什么时候合入正式版

### ISSUE THREAD

**Issue by zys1346** [liupan1890/aliyunpan#189]
一些新功能，potplayer播放器、图片预览啥的都是刚需，现在的正式版不太好用，正式版计划啥时候更新啊

**Comment by liupan1890** [comment]
计划是把下周日的预览版最为第一个公测版发布到主页，届时就是比较稳定的版本了

也就是在下周日开始，会用v2替代v1。但这只是宣传/名字/叫法的区别

v1.6.29采用的是flutter / dart + golang 开发的
v2.8.28采用的是electron + typescript 开发的

如果你说的正式版计划啥时候更新啊，是说的是否会把potplayer播放器、图片预览这些功能，用golang开发更新v1.6.29到v1.6.30 这个操作不会有的，因为精力有限，electron更适合跨平台，以后不会再更新v1.6.29的功能和代码了，只开发v2.xxx了

**Comment by zys1346** [comment]
UI不会改变吗，V1版本的UI看着比现在的V2舒服😂

**Comment by liupan1890** [comment]
不会啊，以后就是这个样子啦

你感觉v1比v2的ui，哪里舒服？说一说，我参考一下

**Comment by zys1346** [comment]
整体的ui界面V1更精致，V2更像一个网页；V2的目录树与右边的界线可调应该会有吧；V2的设置与账户感觉放到左边更好；V2的目录树那里回收站、收藏夹的tab和根目录放在一行感觉很奇怪；个人很喜欢V1的左右型界面，各种功能的tab放在左边，右边是文件详细信息，可以预览进行各种操作，感觉这种逻辑更符合客户端。
自己的感觉，大佬酌情考虑吧

**Comment by iD2073** [comment]
我个人认为还是v2舒服一些

**Comment by oook18** [comment]
v2的就棒呀

**Comment by liupan1890** [comment]
> 整体的ui界面V1更精致，V2更像一个网页；

嗯，其实v2是故意做的像网页一样的，因为现在人都习惯用网页，这样上手快一点，

>V2的目录树与右边的界线可调应该会有吧

以后会有的

>V2的设置与账户感觉放到左边更好

账户设置放在右上角，一方面是习惯，就是大家都这样放，另外是左边想着让文件树尽量高一点，把账户/设置放在左边，占用上方空间，会压缩文件树的高度，找文件夹就需要多滚动。

>V2的目录树那里回收站、收藏夹的tab和根目录放在一行，

同理，放在把回收站放到根目录上方，也会导致文件树变矮需要滚动，是妥协之下强行挤下的


>V1的左右型界面，各种功能的tab放在左边，右边是文件详细信息

v2没变啊，只是顶部多出了账户和设置，感觉上不太纯粹了。实际主体还是文件的列表
