### ISSUE TITLE
1.6.6反复刷新依旧获取不到登录二维码，cookie登录失败

### ISSUE THREAD

**Issue by WHYEX3** [liupan1890/aliyunpan#19]
![image](https://user-images.githubusercontent.com/47862806/120896305-87ed6780-c653-11eb-9c34-5675882f9750.png)
![image](https://user-images.githubusercontent.com/47862806/120896326-99367400-c653-11eb-8d81-1584ef1b8772.png)

**Comment by liupan1890** [comment]
奇怪了，我这里测试了好几次，都是正常登录的

首先跟你解释一下，最近确实因为阿里云盘升级导致扫码登陆失败，但是v1.6.6已经修复了此问题（之前的版本仍然可以用Cookie登陆），我测试可以正常登陆

然后，看你的截图，显示的是二维码已失效+Cookie登陆失效，这样的情况我知道是因为什么：因为aliserver.exe没能访问https://www.aliyundrive.com/sign/in这个网页，就好像是根本不能上网，你是否开了代理软件之类？

你可以试试，右键点击任务栏托盘图标，彻底退出后，重新打开，可能就会恢复正常了

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/120898371-27fbbe80-c65d-11eb-9652-b00a476f9f84.png)

如上图，当你双击`阿里云盘小白羊版v1.6.6.exe`后，应该会运行：
``````
阿里云盘小白羊版v1.6.6.exe
aliserver.exe
aria2c.exe
``````
这3个进程，你可以看一下你的任务管理器里，是否有这3个进程，有时候可能aliserver.exe没能正确的运行，此时就会出现如你截图这样，无法显示二维码，无法Cookie登录。

也就是我上面说的"aliserver.exe就好像根本不能上网”--aliserver.exe没有运行

**Comment by WHYEX3** [comment]
我并没有使用代理软件，不过今天打开已恢复正常（没成功复现昨天的情况），感谢指导
