### ISSUE TITLE
批量改名没有随机命名的功能

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#190]
![QQ截图20210830100446](https://user-images.githubusercontent.com/83964337/131275454-af4b0c88-ef79-4c26-8db0-a3b1042a8503.png)
有随机命名的需求，希望能加一个，现在我用的是别的软件在本地改好之后再上传
![QQ截图20210830100454](https://user-images.githubusercontent.com/83964337/131275496-d5e5553f-7cb2-41cc-9018-15561731a1f5.png)

**Comment by liupan1890** [comment]
收到

**Comment by iD2073** [comment]
这个随机重命名真不知道有啥用，还不如序号好，现在有的需要好像只能添加前后需要，不能只用序号命名

**Comment by rapmq0** [comment]
> 这个随机重命名真不知道有啥用，还不如序号好，现在有的添加序号功能好像只能在源文件前后添加，不能只用序号命名

有些东西不适合序号排序，只适合乱序

**Comment by liupan1890** [comment]
嗯，对哦，下个版本会支持用序号替换的功能（就是只用序号命名）
