### ISSUE TITLE
加个悬浮窗功能吧

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#191]
几个厂商的客户端都有悬浮窗功能，迅雷，百度网盘，天翼云盘，可以看到整体下载进度和速度，不想要的话可以隐藏

**Comment by liupan1890** [comment]
Electron是比较占内存的，一个悬浮窗会增加10MB以上的内存和大量的线程间通讯资源

而我自己又不喜欢悬浮窗这个东西

他有啥用？看速度？
对啊，但是看速度有啥用？是能加快上传速度还是能保证上传不出错？

单纯因为我不喜欢，所以我不加这个，似乎是合理的哈

**Comment by rapmq0** [comment]
上传下载完成给通知提示的功能吧
