### ISSUE TITLE
全局上传速度限制功能

### ISSUE THREAD

**Issue by MoonAsked** [liupan1890/aliyunpan#192]
看了下以前的issues和最新的应用版本似乎没有提及这个功能，大佬啥时候有空能实现下，家里只有100M宽带上传1MB/S满载啥事都做不了

**Comment by iD2073** [comment]
我家100M宽带，下载稳到16MB/S，上传稳到3.5MB/S.左右，

**Comment by MoonAsked** [comment]
> 我家100M宽带，下载稳到16MB/S，上传稳到3.5MB/S.左右，

我家可能光猫型号老了，套餐是200M的，限制到100M，下载10MB/S，上传1MB/S，一上传东西家就全部断网

**Comment by liupan1890** [comment]
你这情况也是没办法了，，，，

临时的解决办法
方式1：在你的路由器里设置一下，对你的电脑限速（上传速度）---操作最简单
方式2：在你的电脑上装个限速软件，就可以限制每一个软件的上传速度了--限速软件有很多随便找一个

关于在小白羊里实现限速

因为当前小白羊是按照阿里云盘的官方网页版，以10MB为最小的分片，去上传的，很难做到限制上传速度1MB/s啊

正常的限速是这样实现的

1.读取100KB数据，扔过去--一个上传请求
2.计算一下是否需要等待
3.重新读取100KB数据，扔过去

如果每次2.计算一下是否需要等待，都是等待1000毫秒，那就是100KB/s
如果每次2.计算一下是否需要等待，都是等待200毫秒，那就是500KB/s

但现在是10MB整体扔过去，最低限速10MB/s，等于没限

为什么要10MB一个呢，是出于性能/文件大小/普遍的网络速度 去综合考虑的

我现在还是主要在做功能，这个限速我现在还没有好的办法去实现，先记一下，以后再研究

**Comment by MoonAsked** [comment]
> 你这情况也是没办法了，，，，
> 
> 临时的解决办法
> 方式1：在你的路由器里设置一下，对你的电脑限速（上传速度）---操作最简单
> 方式2：在你的电脑上装个限速软件，就可以限制每一个软件的上传速度了--限速软件有很多随便找一个
> 
> 关于在小白羊里实现限速
> 
> 因为当前小白羊是按照阿里云盘的官方网页版，以10MB为最小的分片，去上传的，很难做到限制上传速度1MB/s啊
> 
> 正常的限速是这样实现的
> 
> 1.读取100KB数据，扔过去--一个上传请求
> 2.计算一下是否需要等待
> 3.重新读取100KB数据，扔过去
> 
> 如果每次2.计算一下是否需要等待，都是等待1000毫秒，那就是100KB/s
> 如果每次2.计算一下是否需要等待，都是等待200毫秒，那就是500KB/s
> 
> 但现在是10MB整体扔过去，最低限速10MB/s，等于没限
> 
> 为什么要10MB一个呢，是出于性能/文件大小/普遍的网络速度 去综合考虑的
> 
> 我现在还是主要在做功能，这个限速我现在还没有好的办法去实现，先记一下，以后再研究

OK
