### ISSUE TITLE
8月30日小白羊v1.6.29不能登录/刷新二维码失效的问题

### ISSUE THREAD

**Issue by touzi-xiansheng** [liupan1890/aliyunpan#193]
![image](https://user-images.githubusercontent.com/64883693/131309405-f76ac191-5d73-43f8-999a-95d36b6324b6.png)
尝试管理员模式也没用

**Comment by liupan1890** [comment]
我试了一下我电脑上正常

如图，是因为aliserver.exe这个文件没有正常运行

再win10/win11上，aliserver.exe 已经被误报为病毒，部分用户（跟windows defender版本有关）会遇到此文件被自动删除/禁止运行的情况，需要自己添加信任后才能正常运行。你可以看一下你的aliserver.exe还在吗
``````
\阿里云盘小白羊版\data\aliserver.exe
``````


如果不是因为误报，那也有可能是aliserver.exe进程出错崩溃了，彻底退出后重新打开一般就正常了

**Comment by touzi-xiansheng** [comment]
老哥还是不行，我的 windows defender 之前就被我关了。
![image](https://user-images.githubusercontent.com/64883693/131313204-1994b287-1a79-4407-ba5e-d8f767418dda.png)
我重启一遍，把代理关了还是一样。使用 cookie 也登录不上
![image](https://user-images.githubusercontent.com/64883693/131313347-3f7f5c22-a10e-4e97-ba8f-f8725c5fc047.png)
二维码也是一直失效的
![image](https://user-images.githubusercontent.com/64883693/131313533-ce84f7e9-c170-4682-ae6f-790dcbcfef73.png)

**Comment by 0yake0** [comment]
同样的问题。。

**Comment by wdd8866** [comment]
我也是。。

**Comment by MOIX-1192** [comment]
同样的问题 使用COOKIE无法登陆
2.8版本调用官方接口可以登录
![](https://files.catbox.moe/63j5gu.png)

**Comment by iD2073** [comment]
我也是同样的问题，昨天用着还正常

**Comment by bianchen-xiaobai** [comment]
多试几次，我前几分钟试了七八次还这样，刚刚莫名其妙登上了

**Comment by 0yake0** [comment]
可能是阿里网盘的问题，我刚刚也莫名其妙登上了

**Comment by wdd8866** [comment]
> 多试几次，我前几分钟试了七八次还这样，刚刚莫名其妙登上了，扫码登上的

卧槽，可以了

**Comment by LucasSu520** [comment]
还是不行

**Comment by LucasSu520** [comment]
现在可以登陆了，但是好想不能创建秒传了！

**Comment by liupan1890** [comment]
额。。。已经确认了，和阿里云盘有关，也和代码有关，

在v1.6.29 一直到v2.8.28 都用到了阿里云盘的token刷新接口 https://websv.aliyundrive.com/token
结果今天下午，这个接口出问题了，不知道是单纯的间歇性故障了，还是阿里云盘在升级这个接口，还是怎么样，总之，今天下午这个接口无法正确的调用，会返回500错误
``````
<h1>unexpected end of file</h1>
<h2></h2>
<h2>D75487B0-94CB-4E73-9CAC-0B7B6DEF86A1</h2>
``````

在今晚更新的v2.8.30版本中，已经取消了这个接口的使用了，所以就不会受到这个影响了

但v1.6.29及以前的版本，因为已经不再更新维护了，所以

1.假设阿里云盘修正了这个接口websv.aliyundrive.com 那就可以继续正常使用
2.假设阿里云盘不修正，那就不能正常使用了，只能使用最新的v2.8.30及以后的版本了

**Comment by liupan1890** [comment]
接口已恢复正常
