### ISSUE TITLE
阿里云盘离线下载功能正在进行内测，作者大佬还会开发离线下载功能吗？

### ISSUE THREAD

**Issue by bms8889990** [liupan1890/aliyunpan#194]
看到有内测用户已经用上了阿里云盘的离线下载功能（官方称作链接转存）。不知道作者后续还会开发离线下载的功能吗？
https://www.bilibili.com/video/BV15f4y1G7zi

**Comment by liupan1890** [comment]
对啊，这不就连接上了，以后离线下载会直接调用阿里云盘的链接转存功能，

自己开发离线下载受限于自己的服务器，肯定速度没有保证。直接调用阿里云盘本身的链接转存，速度就快了

**Comment by liupan1890** [comment]
当前阿里云盘内测是支持了http https 磁力

据说以后还会更多（也就剩下电驴/ftp了）

等阿里云盘开放链接转存功能时，我会及时跟进的。

**Comment by omy2000** [comment]
阿里现在是又打又拉啊，很多视频在官方app都播放受限了。
