### ISSUE TITLE
导入小白杨txt秒传好像有点问题 

### ISSUE THREAD

**Issue by a936919** [liupan1890/aliyunpan#195]
导入自己创建的小白杨txt秒传 会出现这个
![Snipaste_2021-08-30_18-15-23](https://user-images.githubusercontent.com/41937411/131324356-f530fc92-ec18-426c-98c9-0a29bb22a01a.png)

**Comment by liupan1890** [comment]
嗯，是的，是v2.8.28的BUG，已经在v2.8.30里修正此BUG，可以顺利的导入了
