### ISSUE TITLE
建议右键菜单的子菜单鼠标滑过弹出，现在需要再点一次才弹出

### ISSUE THREAD

**Issue by at2008** [liupan1890/aliyunpan#196]
现在需要再点一次才弹出，建议鼠标滑过弹出，是不是更合适点？

**Comment by iD2073** [comment]
我发现经常点右键需要点两三下才能出现右键，也不知道是什么问题，

**Comment by liupan1890** [comment]
额，我测试正常弹出啊？

说一下细节
1.在左侧树，必须在文件名上点击右键，才有右键菜单，空白处点击是没有。具体说就是鼠标移动到文件名上，文件名底下会出现浅灰色/浅红色 的背景，只有在背景范围内点击才有

2.在右侧，是文件这一整行都可以点击
从左侧勾选按钮到右侧滚动条之间都可以点击

但如果比如只有一个文件，那么这个文件下面会有大片空白区域，这个区域不能点击右键

**Comment by at2008** [comment]
> 建议鼠标滑过弹出，是不是更合适点？
> 
> > 是的，但并不是我专门做的点击弹出，是使用的UI库本身只支持点击弹出，因为没有时间改就这样发出来了。等以后有时间会修改一下这个UI库，更正为滑动弹出
> 
好的，明白了，理解
