### ISSUE TITLE
【建议】在导入阿里云盘分享链接时候，如果里边有秒传txt，建议支持可选秒传txt直接解析，方便快速导入

### ISSUE THREAD

**Issue by anysoft** [liupan1890/aliyunpan#197]
在导入阿里云盘分享链接时候，如果里边分享的是秒传txt文件
建议再保存分享的同时支持可选秒传txt直接解析，方便快速导入。
而无需保存到网盘再打开解析。

另外我这边有一个秒传文件超过了512KB，大概是1.8MB点导入秒传后结果一片空白
分享链接如下：
https://www.aliyundrive.com/s/Aa2w9HfaWMD

小白羊版本：
v2.8.29

**Comment by liupan1890** [comment]
1.如果分享的是秒传txt，直接解析

逻辑上确实很方便，但实际操作中，也有问题

1.分享链接，里面的秒传txt，文件名必须是以 “秒传_” 开头才能识别（无法根据文件内容识别），并且也无法保证一定能识别成功，比如恰好有别的插件生成的文件也是“秒传_”开头就会误报

这样，部分文件成功，部分文件无法成功，跟用户的感觉就会很乱---到底行不行？

2.分享链接里面必须只包含一个秒传文件，不能有其他的文件，因为会造成混乱

假设有人分享了100个秒传txt文件，如果一次性全部解析会爆卡，如果每个文件名后面都有解析按钮，又因为文件名长度不可控造成UI上的遮挡

3.秒传txt功能是用来帮助用户节省网盘空间的，而不是用来分享的

小白羊并不以任何形式提供分享功能，这个是底线



2.另外我这边有一个秒传文件导入秒传后结果一片空白

这个是v2.8.28的BUG，已经在v2.8.30里修复
