### ISSUE TITLE
/v2/file/createWithFolders 接口问题

### ISSUE THREAD

**Issue by xuzhiguang** [liupan1890/aliyunpan#199]
网页版已经用 /v2/file/createWithFolders 代替了 /v2/file/create。

意味着 /v2/file/create 可能在不久的将来就会下线了。

但是 /v2/file/createWithFolders 接口中加了 proof_code 字段，望大佬能够看看怎么计算出来的

（还是希望官方能够出个开发者中心，给出稳定的接口）

**Comment by liupan1890** [comment]
>接口中加了 proof_code 字段，望大佬能够看看怎么计算出来的

``````typescript
  static async GetBuffHashProof(access_token: string, buff: Buffer) {
    if (buff.length == 0) return { sha1: 'DA39A3EE5E6B4B0D3255BFEF95601890AFD80709', proof_code: '' };
    let hash = await sha1(buff);
    hash = hash.toUpperCase();
    const m = unescape(encodeURIComponent(access_token));
    const buffa = Buffer.from(m);
    const md5a = await md5(buffa);
    const start = Number(BigInt('0x' + md5a.substr(0, 16)) % BigInt(buff.length));
    const end = Math.min(start + 8, buff.length);
    const buffb = buff.slice(start, end);
    const proof_code = buffb.toString('base64');

    return { sha1: hash, proof_code };
  }
``````

**Comment by xuzhiguang** [comment]
> > 接口中加了 proof_code 字段，望大佬能够看看怎么计算出来的
> 
> ```ts
>   static async GetBuffHashProof(access_token: string, buff: Buffer) {
>     if (buff.length == 0) return { sha1: 'DA39A3EE5E6B4B0D3255BFEF95601890AFD80709', proof_code: '' };
>     let hash = await sha1(buff);
>     hash = hash.toUpperCase();
>     const m = unescape(encodeURIComponent(access_token));
>     const buffa = Buffer.from(m);
>     const md5a = await md5(buffa);
>     const start = Number(BigInt('0x' + md5a.substr(0, 16)) % BigInt(buff.length));
>     const end = Math.min(start + 8, buff.length);
>     const buffb = buff.slice(start, end);
>     const proof_code = buffb.toString('base64');
> 
>     return { sha1: hash, proof_code };
>   }
> ```

大佬是怎么得知这个算法的

**Comment by liupan1890** [comment]
浏览器，打开阿里云盘网页版，F12,动态调试一看流程就知道了啊
