### ISSUE TITLE
奶牛 

### ISSUE THREAD

**Issue by d790043608** [liupan1890/aliyunpan#20]
期待离线下载！  tv版才是真的急急急

**Comment by d790043608** [comment]
播放直接点就开了 加点东西？

**Comment by d790043608** [comment]
持续关注

**Comment by Andrew201801** [comment]
？你说了些肾摸东西？
请讲普通话

**Comment by liupan1890** [comment]
> 播放直接点就开了 加点东西？

你的意思是增加一个播放按钮？我是参照官方来的，官方就是一点击文件名就直接播放，点击空白处是选择文件

不仅仅是官方，百度网盘客户端也是这样做的

这成了大部分人的潜意识操作习惯了，这个无伤大雅吧

**Comment by liupan1890** [comment]
> 期待离线下载！ tv版才是真的急急急

你想多了，tv是安卓，不会支持安卓的，只支持PC，现在是windows only，正在着手mac

**Comment by d790043608** [comment]
> > 播放直接点就开了 加点东西？
> 
> 你的意思是增加一个播放按钮？我是参照官方来的，官方就是一点击文件名就直接播放，点击空白处是选择文件
> 
> 不仅仅是官方，百度网盘客户端也是这样做的
> 
> 这成了大部分人的潜意识操作习惯了，这个无伤大雅吧

点一下没反应 又点一下出来三个播放窗口！

**Comment by d790043608** [comment]
> ？你说了些肾摸东西？
> 请讲普通话

中.中.中

**Comment by d790043608** [comment]
> > 期待离线下载！ tv版才是真的急急急
> 
> 你想多了，tv是安卓，不会支持安卓的，只支持PC，现在是windows only，正在着手mac

离线呢？

**Comment by liupan1890** [comment]
离线功能得排队啊，还没做到呢

**Comment by Andrew201801** [comment]
> > > 播放直接点就开了 加点东西？
> > 
> > 
> > 你的意思是增加一个播放按钮？我是参照官方来的，官方就是一点击文件名就直接播放，点击空白处是选择文件
> > 不仅仅是官方，百度网盘客户端也是这样做的
> > 这成了大部分人的潜意识操作习惯了，这个无伤大雅吧
> 
> 点一下没反应 又点一下出来三个播放窗口！

这个应该和网速有关系，以前用6盘小白杨也这样，播放器得缓存10秒的视频才会开始播放

**Comment by Andrew201801** [comment]
> > ？你说了些肾摸东西？
> > 请讲普通话
> 
> 中.中.中

哈哈哈，你好可爱
