### ISSUE TITLE
建议可以拖动移动文件

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#201]
同一目录内有一文件和文件夹，想把这个文件移动到当前目录的一个文件夹里，但是只能选择移动之后选择目录才行，要是能直接拖进去就很方便了

**Comment by Borber** [comment]
+1 目前确实需要这个, 移动的体验不是很好, 官方web是支持的

**Comment by liupan1890** [comment]
收到，以后试一下

不过拖放肯定有局限，只能一个页面里，既一个文件夹里包含的子文件夹+子文件总数量=12个以内的时候，操作很方便

总数超过12个，就显示滚动条了，假如拖放的文件在最底部，要放入的文件夹在最顶部，拖放时要涉及到页面滚动

页面滚动这个操作，并没有好的体验，最终就导致拖放效果很差了


（12个跟用户的屏幕大小，调整的小白羊窗口大小有关，12个是平均值）

**Comment by liupan1890** [comment]
在v2.11.28里已经支持，拖动右侧文件列表选中文件，到右侧文件树上，移动文件功能了
