### ISSUE TITLE
希望添加网盘已经占用容量刷新功能 

### ISSUE THREAD

**Issue by zip11** [liupan1890/aliyunpan#202]
①大量导入秒传资源后，想看已经占用容量需要重启软件，网盘容量已经占用容量希望添加手动刷新功能

②测试版 2.8.30 aria2远程下载，每次只能导入一个文件的下载任务，下载大量文件的话，需要电脑上的小白羊持续导入不能关闭，希望可以批量导入，这样晚上挂机下载就可以关闭电脑了

**Comment by liupan1890** [comment]
1.容量刷新
收到，以后会增加点击头像自动刷新一次。
现在，如果你是多个账号的话，切换一下就会刷新了，（比如登陆了2个账号，先点击账号2，再点击账号1，账号1就刷新了）

2.aria2远程下载，每次只能导入一个文件的下载任务

实际上跟阿里云盘有关，阿里云盘当前限制下载地址最长是4小时内有效，再考虑到下载需要用的时间，

所以，如果一次性把所有文件的下载地址发给aria，可能下着下着剩余的任务就全部失败了。另外，很多人的远程aria并不是只给小白羊用，如果一次把所有文件都发给aria，会导致他们不能下载其他文件（需要排队）

所以这个功能，只有设计为，下载哪个，发送哪个才合适

（如果你再小白羊里设置的是同时4文件下载，那就会把4个文件都发给aria，最多可以设置为50文件同时下载，所以最多可以一次发过去50个文件）

**Comment by zip11** [comment]
> 1.容量刷新
> 收到，以后会增加点击头像自动刷新一次。
> 现在，如果你是多个账号的话，切换一下就会刷新了，（比如登陆了2个账号，先点击账号2，再点击账号1，账号1就刷新了）
> 
> 2.aria2远程下载，每次只能导入一个文件的下载任务
> 
> 实际上跟阿里云盘有关，阿里云盘当前限制下载地址最长是4小时内有效，再考虑到下载需要用的时间，
> 
> 所以，如果一次性把所有文件的下载地址发给aria，可能下着下着剩余的任务就全部失败了。另外，很多人的远程aria并不是只给小白羊用，如果一次把所有文件都发给aria，会导致他们不能下载其他文件（需要排队）
> 
> 所以这个功能，只有设计为，下载哪个，发送哪个才合适
> 
> （如果你再小白羊里设置的是同时4文件下载，那就会把4个文件都发给aria，最多可以设置为50文件同时下载，所以最多可以一次发过去50个文件）

谢谢你的解答，aria2远程功能很不错，   让我利用宽带闲时利用低功耗nas，下载文件很不错，谢谢了
