### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by 0yake0** [liupan1890/aliyunpan#203]
新版播放时画面会被挤压，1629版没有这种情况。

作者有增加“使用potplayer”播放功能的想法么？

**Comment by 0yake0** [comment]
使用转码播放会出现这种问题，原始视频模式不会。

**Comment by liupan1890** [comment]
被挤压是什么意思？高宽比错误？就是画面可以随意的拉成正方形（正确的应该是长方形）？

是一播放高宽比就错误并且一直是错误的，手动调整也不行？

还是一播放默认是正确的高宽比，但是想要调整窗口大小时，会出现高宽比错误？

最好截个图我看一下

另外v2.8.30支持Potplayer啊，参阅首页”使用PotPlayer.md“

**Comment by 0yake0** [comment]
![原始](https://user-images.githubusercontent.com/34828910/131639376-7de318c3-534c-47f3-9abb-3ff798494bd9.png)
![解码](https://user-images.githubusercontent.com/34828910/131639388-e243aea4-e041-4cc0-9d2d-cf911e31f9c8.png)

**Comment by liupan1890** [comment]
我在我的电脑上测试，结果是，转码和原始，MPV都可以保持宽高比，

所以，我感觉，是因为阿里云盘在转码的时候，转错了高宽比了，所以转码视频在播放时，宽高比错误

如果是阿里云盘转码错误，那会跟这个视频文件有关，别的视频都是正常的，只有这个视频或者其他个别的视频播放时是错误的，这样的话，也没有修正的办法，只能观看原始文件

反正我网盘里的视频，在观看是，转码和原始都是正确的


如果你的所有视频都是错误的，请继续留言

如果只是这一个视频有问题，那就确认是阿里云盘的事，可以通过更换为Potplayer，解锁宽高比限制。
MPV播放器有个快捷键 Shift+A,可以切换宽高比
