### ISSUE TITLE
请问云盘里有文件 但无法下载是什么情况 

### ISSUE THREAD

**Issue by leeaung** [liupan1890/aliyunpan#204]
用小白羊秒传链接保存的文件 保存成功 也能够在线播放 为什么就是不能下载呢?
小白羊提示aria2c创建文件大小时失败 官方客户端显示下载失败
从来没有用过aria2c 不懂这个
有办法能下载吗? 是高清的韩剧 不像是违规资源 想放到本地保存

**Comment by leeaung** [comment]
{
  "Name": "包含 0个文件夹，27个文件，共53.4GB",
  "Size": 57383797639,
  "FileList": [
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E01.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3045594864|03CD4FB274F59ECF6A589530EF58140FE59F3A08",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E02.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3198515281|BF1580CADE62D63450C9ACD3903079E4F9FF89F4",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E03.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3183961711|D9858EF5C9B5E79B9317DA53C71A49BE089F146F",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E04.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2607323730|9FEC4D5ECC0BEEBDB44FF90895E23BD6BADAB84C",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E05.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2894322868|BC151C5D142FEF3FC9A8B244DFC68BBA77501A57",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E06.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2976910485|67AEBCC03E96BAEC22B7BF22D476008331AB95B8",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E07.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2571071892|254833E9916EDC549B7DBB4F01E31EB2C52C8F54",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E08.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2449139493|73E696795C81F32449EBFCECA1AD7F14C12E3385",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E09.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2438670154|0507069E0A98A7BB0896A64526EEF99918410145",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E10.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3107949314|275D566EB080C7031B22A86D7C1545128FD9A8AB",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E11.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2544388256|36DC5FA1A2A50D71D1BDB5354B27306E9462CDDB",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E12.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2213442005|2328DF21506FC78CCA98BA3D87F05D92B1E2209F",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E13.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3230843681|8DBEEC71346EE4D1A532FD212C489CABB6751635",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E14.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3376528704|E5C702674352021B995F5AF84073F7081A1A7FDB",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E15.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3326267950|48C3FA5452E9F3ED303091D5AFE7923F490D4331",
    "\t\t\t\t\"看见味道的少女.A.Girl.Who.Sees.Smells.S01E16.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2439539034|96E19F79752B6071362F2C674047F92BDEC590CF",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep01.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1151762130|47AF42D6001370FA75BE3FBECCB043595B458B16",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep02.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1417827240|36B8FC096A92A55AEA2F6DCE00875A6DA2FE8461",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep03.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1148662755|B9A71FBA1EA320CEB06E17F9A5302E2A636E33F1",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep04.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1135732009|0E906AF411E4C762E0F9D6907219B6D95AB49D80",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep05.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1028102906|1C1F1DCA95272199E9B8A840374C773707C45156",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep07.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1023724579|3C0EEAC0F37ADD9064A28EC30040C20B607F10B0",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep10.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|1038700049|36549C40D22D23A9655DF5B4611B7C44C9DE502A",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep12.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|914211184|6998A32742F7B25FA0581239E3137E7DE8D4736E",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep14.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|993414570|60CC87E5CAAE063F198EFD3306275CE9558C1893",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep15.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|960654930|1F74FB4E97F712CC61F5E3BF8345C724BF8BB90E",
    "\t\t\t\t\"内在美.Beauty.Inside.2018.Ep16.WEB-DL.1080p.H264.AAC-HDSWEB.mp4|966535865|3E6F87EA23EC1110AD11DC0352178EDF6DF32DD0"
  ],
  "DirList": []
}

**Comment by leeaung** [comment]
> 
> 
> 是特定的几个文件不能下载？那你把不能下载的这个文件创建秒传txt回复给我，我测试一下
> 
> 是你的全部文件不能下载？是否跟下载保存位置有关，换个其他的保存位置试试，比如原来是下到D盘，换成E盘试试

麻烦你看看 第一次导出秒传链接 不知道对不对 前面好多\t

**Comment by leeaung** [comment]
> 
> 
> 是特定的几个文件不能下载？那你把不能下载的这个文件创建秒传txt回复给我，我测试一下
> 
> 是你的全部文件不能下载？是否跟下载保存位置有关，换个其他的保存位置试试，比如原来是下到D盘，换成E盘试试

感谢你的帮助  你的话提醒了我 还有刚才导出的秒传链接 前面很多的\t和 " 是文件名问题 我把前面的空格和 " 删了 就能够下载了

**Comment by liupan1890** [comment]
嗯，下个版本，我会把这些\t主动清理掉

**Comment by liupan1890** [comment]
忘了问了，你的秒传文件怎么来的？
因为使用小白羊创建秒传Txt的话，不应该是这样的啊

``````
"\t\t\t\t"内在美.Beauty.Inside.2018.Ep15.WEB-DL.1080p.H264.AACHDSWEB.mp4|960654930|1F74FB4E97F712CC61F5E3BF8345C724BF8BB90E",
``````
注意前面的\t ，在创建秒传txt时,\t我也忘了清理没清理，所以这个不是重点

"内在美  注意前面的引号，这个是重点，因为小白羊里创建txt时已经转义了啊，应该是   \"内在美  才对，

所以，你的这个秒传txt，是自己编写的？别人发给你的？

**Comment by leeaung** [comment]
我去找了一下 导入的是韩剧_17299.json里面的内容 里面的文件名就带 " 
`{
			"dir_name": "A.Girl.Who.Sees.Smells.S01.Complete.1080p.NF.WEB-DL.DDP2.0.x264-Ao看见味道的少女",
			"files": [
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E01.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3045594864|03CD4FB274F59ECF6A589530EF58140FE59F3A08|84832C68E57307636738B61D9946AF8EF097A54C",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E02.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3198515281|BF1580CADE62D63450C9ACD3903079E4F9FF89F4|CDBB0B8B8BD61980617677B17CAD2359BB22D4F6",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E03.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3183961711|D9858EF5C9B5E79B9317DA53C71A49BE089F146F|B940AE878D652A2EAF4BCB6BB0D51396ADDE31EE",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E04.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2607323730|9FEC4D5ECC0BEEBDB44FF90895E23BD6BADAB84C|2EC4E70CC0D61E8FA9A40A6D9FBB6B7BC83D9D68",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E05.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2894322868|BC151C5D142FEF3FC9A8B244DFC68BBA77501A57|CB21AABD2B5DD914E7BC02B90E6A05D1E64A3194",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E06.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2976910485|67AEBCC03E96BAEC22B7BF22D476008331AB95B8|2FD8C9BDA680EF561A79B23C05B2443A1C4759FF",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E07.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2571071892|254833E9916EDC549B7DBB4F01E31EB2C52C8F54|94BECC848339616136BDC0A6320FE1E2A4701119",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E08.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2449139493|73E696795C81F32449EBFCECA1AD7F14C12E3385|D36FF59D208064B1E2E0DFB80EB307DFBD038D87",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E09.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2438670154|0507069E0A98A7BB0896A64526EEF99918410145|4A517F90D641F99C5D6A4685983450F23E59AD6D",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E10.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3107949314|275D566EB080C7031B22A86D7C1545128FD9A8AB|6B44171E87EE5879A5B1EC8108F8E44BD788C772",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E11.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2544388256|36DC5FA1A2A50D71D1BDB5354B27306E9462CDDB|0CBF1E4BF5E66F78F7BE31B8DEBC8935D120C90E",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E12.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2213442005|2328DF21506FC78CCA98BA3D87F05D92B1E2209F|FC21C26EA34FEB9AD185F3D4613C1E77D7D8EA91",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E13.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3230843681|8DBEEC71346EE4D1A532FD212C489CABB6751635|38B4650B775884375576FA10B5E2B58A4F2CC14C",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E14.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3376528704|E5C702674352021B995F5AF84073F7081A1A7FDB|28101E6AD51A85DB85E64223023A076E8BB20BCB",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E15.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|3326267950|48C3FA5452E9F3ED303091D5AFE7923F490D4331|58D6C1EA5A2F72C0B717A444D1420215E14F55D4",
				"看见味道的少女.A.Girl.Who.Sees.Smells.S01E16.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv|2439539034|96E19F79752B6071362F2C674047F92BDEC590CF|BB0B6FC1518A5D021F4AAC7672BC67D1335E717F"
			],
			"dirs": [
			]
		},`
不知道源文件为什么会有 " 符号 Windows不允许用这个做文件名的

**Comment by liupan1890** [comment]
收到，我会在下个版本里注意清理一下的
