### ISSUE TITLE
导入秒传文件后，上传中出现「秒传失败，创建文件失败」

### ISSUE THREAD

**Issue by GB1818** [liupan1890/aliyunpan#205]
秒传文件的文件夹结构是创建好了的，就是会在上传中出现「秒传失败，创建文件失败」的问题，即没有创建文件。
等一段时间后，点「开始全部」有一些可以上传成功，其他不行。
这样循环点击下去，要等很久才可以全部文件上传成功了。

小白羊版本：v2.8.30
导入的秒传文件：https://www.aliyundrive.com/s/mXQ3qcEgJjj

![4X840`T %XC4TUKFF{YZ49T](https://user-images.githubusercontent.com/29467754/131756658-5bcf42f5-614d-41ad-b495-4da18d8ddeeb.png)

**Comment by liupan1890** [comment]
这个问题，我也摸不到头脑。。。。我测试了一下导入上面的秒传，是一次就成功了，没有出现失败的错误

我感觉像是网络问题，

首先吧，创建文件时，是去调用阿里云盘的秒传接口。

失败时，秒传接口会返回具体的错误信息，最后显示出来

只有返回503的时候，才会显示创建文件失败（此时没有错误信息）

503是阿里云盘服务器临时性有问题，这个不是整个阿里云盘都有问题，而是离你最近的这一台节点，有问题

下个版本我会让他显示出具体的http状态码，就可以准确地判断了。现在只能是推断，感觉是网络问题

**Comment by liupan1890** [comment]
你先用者试试看，如果频繁的，每天都这样，你再继续留言，我再研究看看到底是怎么回事，如果只是今天这样，可能明天又恢复正常了（因为我测试时就没出错啊）

**Comment by zzh151223** [comment]
这个应该是阿里云的一些限制，我刚刚上传了大量文件，然后也是创建文件失败，换个账号又是正常的

**Comment by anysoft** [comment]
> 关掉科学上网就正常了，应该是网络问题。

不是网络问题，应该是阿里限制了。可以尝试吧上传下载个数设置为1再秒传，就不会出现这种问题。

另外建议导入秒传时候界面能不能最小化一下，后台秒传，目前挡住界面，无法进行任何操作

**Comment by anysoft** [comment]
@liupan1890  我可以说是账号上传下载太多被限制了么。。。
换个号同电脑秒传一切正常。。。。。。。。。。

**Comment by anysoft** [comment]
@liupan1890  上传下载线程数可以再设置配置，秒传是先创建任务然后上传，这个并行任务也是跟配置那个共用么？

**Comment by at2008** [comment]
> 你先用者试试看，如果频繁的，每天都这样，你再继续留言，我再研究看看到底是怎么回事，如果只是今天这样，可能明天又恢复正常了（因为我测试时就没出错啊）

感觉是阿里限制，可能是接口调用频率、间隔？
关掉代理，设置单线程，都无效；

**Comment by at2008** [comment]
> > 你先用者试试看，如果频繁的，每天都这样，你再继续留言，我再研究看看到底是怎么回事，如果只是今天这样，可能明天又恢复正常了（因为我测试时就没出错啊）
> 
> 感觉是阿里限制了，可能是接口调用频率、间隔？
> 关掉代理，设置单线程，都无效；
> 今天没导入完整过。一般前20个，或40个可以导入，后面就都失败了。

今天又可以秒传导入了。

**Comment by at2008** [comment]
> > > 你先用者试试看，如果频繁的，每天都这样，你再继续留言，我再研究看看到底是怎么回事，如果只是今天这样，可能明天又恢复正常了（因为我测试时就没出错啊）
> > 
> > 
> > 感觉是阿里限制了，可能是接口调用频率、间隔？
> > 关掉代理，设置单线程，都无效；
> > 今天没导入完整过。一般前20个，或40个可以导入，后面就都失败了。
> 
> 今天又可以秒传导入了。

第三次反馈，晚上10点多，一次导入3000+文件，又失败了

**Comment by anysoft** [comment]
我猜测
是秒传接口频度太高，我们假设我们真有文件上传，秒传，那么会算hash，需要消耗时间，1GB大概十几秒？所以在客户端秒传会显示一个速度，大概是几十mb每秒。
而用秒传文件，几百gb瞬间调用秒传接口，这时候折算是不是1gb+每秒？这样肯定就会封了。

所以我建议秒传增加一个计算判断逻辑，
1.可以设置秒传文件"速度"，让比如不超过60mb的"上传"(hash检验)速度，也就是上传1gb文件，我们在上次秒传接结束后等待几秒～十几秒(具体间隔时长=根据size/配置的速度)这样接口就应该不会封了(事实上这个速度我们可以用大文件秒传测试得出)

2.另外可以配置，同时并发的秒传任务个数，官方客户端默认应该是3个。


我们可以确定笔阿里有限制，这个也是必须的，哪家大厂接口没限制逻辑？
我们不清楚具体的逻辑，但是我们可以尽量的模拟成官方客户端的样子(频度，时间间隔，流程)。这样确保小白羊的功能正常，然后就可以配置化的不断在边缘试探😎

@liupan1890

**Comment by liupan1890** [comment]
额，收到了，我会再下个版本调低并发频率的

其实在v1.6.29的时候吧，没有限制频率，导致导入秒传时会遇到创建文件夹失败

然后我在v2.8.1-v2.8.19里都严格的限制了15次/秒

后来测试感觉阿里云盘还可以提高，在v2.8.30里修改为20次/秒了

可能这个20次正好时阿里的阈值附近，因为我当时测试了几千个文件也没触发。你这里确触发了

会在下个版本恢复为15次/秒

**Comment by liupan1890** [comment]
> @liupan1890 上传下载线程数可以再设置配置，秒传是先创建任务然后上传，这个并行任务也是跟配置那个共用么？

不是的，在设置里的，设置的时同时下载或上传的任务数

但是这个上传是真正上传，有流量的上传

因为有秒传链接导入，默认设置的是4任务同时处理，

好多人也没有修改设置，再导入秒传链接时就会很慢，

所以在v2.8.2X好像是，我就修改为秒传任务单独计算了，

秒传任务是50个任务同时进行，不受设置里的限制

**Comment by anysoft** [comment]
> > @liupan1890 上传下载线程数可以再设置配置，秒传是先创建任务然后上传，这个并行任务也是跟配置那个共用么？
> 
> 不是的，在设置里的，设置的时同时下载或上传的任务数
> 
> 但是这个上传是真正上传，有流量的上传
> 
> 因为有秒传链接导入，默认设置的是4任务同时处理，
> 
> 好多人也没有修改设置，再导入秒传链接时就会很慢，
> 
> 所以在v2.8.2X好像是，我就修改为秒传任务单独计算了，
> 
> 秒传任务是50个任务同时进行，不受设置里的限制
15次/秒，50个并行？
15*50？

**Comment by liupan1890** [comment]
在上传队列对秒传任务单独计算并发数，同时执行50个秒传上传任务

在上传队列对非秒传任务单独计算并发数，同时执行4个（设置里）个上传任务

真正执行时，网络请求库，会对网络请求做QPS限制，限制为20次/分钟（上面都写错了，是分钟）

所以如果你导入3000个文件的秒传任务，实际上是20个任务/分钟左右上传成功

**Comment by anysoft** [comment]
> 在上传队列对秒传任务单独计算并发数，同时执行50个秒传上传任务
> 
> 在上传队列对非秒传任务单独计算并发数，同时执行4个（设置里）个上传任务
> 
> 真正执行时，网络请求库，会对网络请求做QPS限制，限制为20次/分钟（上面都写错了，是分钟）
> 
> 所以如果你导入3000个文件的秒传任务，实际上是20个任务/分钟左右上传成功
> 
> 但是QPS不是这样死板的，他是动态计算的，所以简单理解为20个任务/分钟左右上传成功也不准确
> 
> 总之：会再下个更新时调整QPS的

我临时把asar打开编辑了下
app.js
搜索
url.indexOf("api.aliyundrive")
定位前边的(e = 20, t = 0)，改成(e = 10, t = 0)。目前看上传列表是每秒10个秒传任务，很稳定，没创建失败的了。

**Comment by liupan1890** [comment]
嗯，在v2.8.1-2.8.20一直是15，也很稳定，你试试15吧，高一点就快一点

**Comment by anysoft** [comment]
> 嗯，在v2.8.1-2.8.20一直是15，也很稳定，你试试15吧，高一点就快一点

并不常用，不急用 稳定点好😊
坐等下个版本

**Comment by anysoft** [comment]
> 嗯，在v2.8.1-2.8.20一直是15，也很稳定，你试试15吧，高一点就快一点

还是做成可配置化吧。我10个被封了，然后我换成5个就好了，官方的应该是三个并行，然后接口应该有区间限频，比如一秒5次，一分钟150次这种，最好是配置化，贴近官方配置再慢慢调高。

**Comment by GB1818** [comment]
> > 嗯，在v2.8.1-2.8.20一直是15，也很稳定，你试试15吧，高一点就快一点
> 
> 还是做成可配置化吧。我10个被封了，然后我换成5个就好了，官方的应该是三个并行，然后接口应该有区间限频，比如一秒5次，一分钟150次这种，最好是配置化，贴近官方配置再慢慢调高。

**Comment by GB1818** [comment]
> > 嗯，在v2.8.1-2.8.20一直是15，也很稳定，你试试15吧，高一点就快一点
> 
> 还是做成可配置化吧。我10个被封了，然后我换成5个就好了，官方的应该是三个并行，然后接口应该有区间限频，比如一秒5次，一分钟150次这种，最好是配置化，贴近官方配置再慢慢调高。

抱歉误删了，你的回复：
**「还是做成可配置化吧。我10个被封了，然后我换成5个就好了，官方的应该是三个并行，然后接口应该有区间限频，比如一秒5次，一分钟150次这种，最好是配置化，贴近官方配置再慢慢调高。」**

我最近使用秒传出现这个问题，只要重启一下小白羊，无论多少文件都能正常上传完（最多时3199个文件）。

**Comment by liupan1890** [comment]
嗯，下个版本里会对此进行更多的测试，找到合理的频次，修正这个问题的
