### ISSUE TITLE
【功能建议】不同文件夹不同排序方式

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/aliyunpan#207]
目前的文件排序方式是全局的，也就是说选定了一种排序方式，那么所有文件夹的排序方式就都是那种了。

但使用中发现有不同文件夹不同排序方式的需求，例如：
A文件夹是美剧，那就希望A文件夹按照文件名来排序。
B文件夹里放的是自己做的markdown笔记，就希望按照创建时间来排序。

不知道我有没有表述清楚 : )

**Comment by liupan1890** [comment]
嗯，表达的很清楚了，我看明白了

实际上是这样，这个功能开发起来很简单，但是实际使用时，我又怕用户会混乱

1.这么简单的功能不值得在设置里增加一个选项：是否独立排序
2.这个文件夹这么排，那个文件夹那么排，有的人用的时候并不会专门留意，会突然发现：哎？怎么排序不对？是BUG吧？实际上是独立的排序了

3.独立排序需要继承，既父文件夹是按照文件大小排序的，那么默认子文件夹应该也自动按照大小排序，除非用户手动选择了文件名排序，这个继承，意味着需要一级一级的向上查找排序方式，当前的目录模式并不能很好的按级查找


这个功能我需要仔细想一想怎么安排才合适


但现在我没时间，我需要先做一些不能用的功能（比如相册），等以后软件所有功能都做完了，才有时间去优化细节--独立排序

所以，需要耐心等等了

**Comment by iD2073** [comment]
让每个目录都能记忆最后一次设定的排序，不知道能不能实现，但是这个应该会有一个本地的配置记录文件，如果没有也不太可能会在退出再登录时记忆以前的设置，我对这个功能基本很少用到不同排序，我感觉容易蒙圈

**Comment by Andrew201801** [comment]
好的，谢谢开发大大把这个功能加上小本本！

对于担心用户会混乱，我觉得应该没有什么大的问题，也不用加开关，理由如下：

1、windows的文件管理器就是独立排序的，大部分人（缺少数据支持）应该习惯了这样的设计

2、在同一排序下，一个文件夹的排序方式的修改会影响到另一个文件夹，这不一定是用户想要的或说能预见的，另一方面，独立排序做出来后，最开始每个文件夹的排序方式是一样的（例如按照文件名），而随着用户的使用，ta针对某些需要修改排序方式的文件夹，所作出的修改的行为是主动且能预见行为后果的.

**Comment by liupan1890** [comment]
收到，以后会加上独立记忆排序方式的---就是不知道哪个版本了，加上时会公告的

**Comment by liupan1890** [comment]
v2.9.15已经增加了独立排序设置
