### ISSUE TITLE
大佬，您这么搞，不会像百度一样收到阿里的警告吗？

### ISSUE THREAD

**Issue by Sunshagon** [liupan1890/aliyunpan#208]
另外，您可不可以加一个让下载完的文件可以双击打开的功能啊，已经设置一个下载完就会提示的音效。

**Comment by liupan1890** [comment]
1.阿里云盘官方已沟通过，官方是支持第三方自己DIY扩充网盘功能的。

2.下载完的文件可以双击打开的功能

下载完的文件，右面有3个按钮，打开文件，打开文件夹，删除。所以不需要双击，直接点打开文件按钮即可

3.设置一个下载完就会提示的音效
已经有人提过了，以后会增加的

**Comment by AhmadHomnYoua** [comment]
这个可以哎，阿里这波做的比百度好。

**Comment by liupan1890** [comment]
嗯，对的，沟通时，我问道是否会因为调用阿里云盘的API在成侵权，是否”阿里云盘小白羊版“这个名字因为包含”阿里云盘“需要整改，阿里专员的话是：
>你来信提到的情形，不是我们的思考方式，开发者能够使用阿里云盘、智能存储的接口，本来就是我们业务的一部分，反过来我们很感谢你尝试

阿里比百度开放，关键是交流态度，十分友善，不像百度

**Comment by iD2073** [comment]
这要是全面放开分享格式，这不是要吊打各家网盘，

**Comment by AhmadHomnYoua** [comment]
希望能保持下去，后续推行付费模式，慢慢发展起来抗衡一下百度，，，一家独大太享受了

**Comment by weicen** [comment]
等你做大了再看，阿里杀鸡取卵做的还少么？

**Comment by shawlj** [comment]
作者抢先一步布局阿里云盘GUI，未来大有可为
