### ISSUE TITLE
想问接下来会考虑出安装版而非便携版嘛？

### ISSUE THREAD

**Issue by AhmadHomnYoua** [liupan1890/aliyunpan#209]
rt

**Comment by iD2073** [comment]
懂的人，基本可以不考虑制作成安装形式，对于不懂电脑程序的人需要出一下安装包，有很多人把快捷方式删掉就当成卸载的人也是大有人在。

**Comment by liupan1890** [comment]
额，是这样，如果出安装版，那就要一视同仁

win要打包成exe
mac要打包成dmg
linux要打包成rpm/deb

win上，打包需要买签名，不签名也可以，但会被误报病毒，也会下载时会被提示风险甚至被拦截
mac上，打包需要买签名，不签名不能打包
linux上，因为打包格式众多，即使打包了也有人无法使用，所以除了打包的，还必须提供zip版本

你看，没一个省心的

当前，打包成zip，为了兼容，都是win上打包win，mac上打包mac，ubuntu上打包linux，但是每个系统都不用配置打包环境（因为每个系统都可以直接创建zip压缩包）

如果更换为打包安装版，那么win上没事，mac和ubuntu必须安装一些打包用到的软件/环境

当前，打包成zip，一次大概需要半小时

如果更换为安装版，估计半小时是不够的

所以，考虑到大家已经被迫习惯了解压缩替换的操作，就不转换为安装版了

另外，安装版的优势不知道是什么？
是可以自动把文件解压到Program Files（或Applications）里面吗？这个自己解压后挪一下就好了
是更好的压缩比吗？当前zip在70-100MB，换成安装版最多可以优化为60-80MB？
是便捷的安装体验吗？不管zip还是安装版，一周一更，没有任何好的安装体验的（不会考虑自动升级功能，因为像广告，我自己比较讨厌自动升级功能）


其他的优势是什么？

**Comment by AhmadHomnYoua** [comment]
有道理，之前不懂，还以为做成安装版很容易呢，无知了，hh，说优点的话，可能是习惯了走个安装的过程吧，也没啥实质内容，这么复杂的话，那就直接压缩版吧。感谢科普+回复。

**Comment by abcfy2** [comment]
electron-builder应该可以支持各种环境的构建，Linux下可以打包AppImage，其他系统既可以打包成安装包，也可以打包成zip

**Comment by liupan1890** [comment]
> electron-builder应该可以支持各种环境的构建，Linux下可以打包AppImage，其他系统既可以打包成安装包，也可以打包成zip

1.windows上，需要自己购买证书签名，不签名会被拦截/误报。
2.打包mac时，也必须提供自己购买的苹果开发者证书签名，不提供无法打包
3.linux 有的linux不支持AppImage，所以稳妥起见还是要提供zip

总结：使用 electron-builder 打包跟我上面说的没有区别
