### ISSUE TITLE
关于分享文件 链接为网址的潜在危险

### ISSUE THREAD

**Issue by kedyao** [liupan1890/aliyunpan#21]
以下仅为个人观点 仅供参考
以历史为鉴
1.网址就有服务器 总有不怀好意的人进行攻击 服务器等也会造成分享链接不可访问等情况 
到最后无法进行服务等 被迫关闭
2.当官方重视这个过审核的分享功能 作者如果被官方警告  
被迫关闭分享链接  所有已分享的文件都将失效 

所以
建议同115一样的 一行行的文件特征直链   
另外
虽然直接分享支持文件夹+文件递归 那可能在有一天 有一个爱好分享的伙伴 会分享几万加的数据   造成官方的API爆炸

**Comment by liupan1890** [comment]
嗯，很中肯，会再下个版本更新时提供完整直连

**Comment by d790043608** [comment]
能不能加入永久直连获取！

**Comment by liupan1890** [comment]
> 能不能加入永久直连获取！

阿里云盘的所有下载地址均有时效，没有永久直连

虽然通过架设一个代理网站，变相提供永久的直连，技术上可行，但我不会提供此功能

**Comment by liupan1890** [comment]
已关闭创建分享链接的功能，仅保留导入115秒传链接功能
