### ISSUE TITLE
2.8.30导入分享链接保存不完整

### ISSUE THREAD

**Issue by Thessalhydra** [liupan1890/aliyunpan#210]
https://www.aliyundrive.com/s/78YBpkJeaLp
导入后提示保存成功，打开文件夹只有ass文件，mkv保存不进去

**Comment by liupan1890** [comment]
是不是你刚导入就打开文件夹，查看只有ass，但是刷新一下就会出现mkv，因为阿里云盘分享链接导入是异步导入，那个mkv体积大，需要多1秒才成功，正巧你已经打开文件夹查看了，此时需要手动刷新
