### ISSUE TITLE
小白求问，导入的115的sha1链接，这个错误的意思是指阿里网盘内不存在这个资源吗

### ISSUE THREAD

**Issue by GJG666** [liupan1890/aliyunpan#211]
![image](https://user-images.githubusercontent.com/36781028/132085146-8ad7fdca-5794-4016-b8b1-6588062dc320.png)

**Comment by liupan1890** [comment]
是的，没有人往阿里云盘上传过这个文件，所以无法秒传上去。

换别的文件吧

**Comment by GJG666** [comment]
> 是的，没有人往阿里云盘上传过这个文件，所以无法秒传上去。
> 
> 换别的文件吧
> 
> 注：早期阿里云盘限制单个文件最大30GB，你的这个文件是41GB，所以很容易遇到这样的情况，因为没有人可以上传超过30GB的文件。最近几周阿里云盘才取消的此限制

明白啦，感谢回复!
