### ISSUE TITLE
aria2c创建文件夹失败

### ISSUE THREAD

**Issue by zzh151223** [liupan1890/aliyunpan#212]
好像会和其它程序的aria2冲突，然后就一直这样了

**Comment by moudatuo** [comment]
一样的问题，原来老版本好好的，换了新版本就这样了，然后换回老版本，也一样出错，一样的保存

**Comment by zzh151223** [comment]
刚才把两个冲突的程序打开，弹了个已兼容模式运行，现在好了，可以下载了

**Comment by moudatuo** [comment]
@zzh151223 怎么解决的，能说一下么？

**Comment by moudatuo** [comment]
> 好像会和其它程序的aria2冲突，然后就一直这样了

怎么解决的，能说一下么？

**Comment by liupan1890** [comment]
>好像会和其它程序的aria2冲突，然后就一直这样了

1.aria2c每个运行的端口都不一样，不会和别的程序的aria2c冲突的
2.假设是冲突导致的创建文件夹失败，重新点击开始，会重新创建（冲突只是恰好2个程序在同一秒钟同时要创建文件夹，可能会冲突，低于亿分之几的概率）。总之重新开始就会成功了

3.一般创建文件夹失败，可能是因为没有写入权限，或者要创建的文件夹名里包含特殊字符

因为没有截图，我也看不到具体的文件夹名。

但很少有创建文件夹失败的时候呢


@moudatuo   你也遇到了创建文件夹失败吗？

**Comment by moudatuo** [comment]
是的，说是创建文件夹失败，但其实好像是创建文件失败，我下载的根本不需要创建文件夹

**Comment by zzh151223** [comment]
把aria2冲突的程序再开一个，就会小白羊就会弹窗提示以兼容模式运行然后就可以了

> @zzh151223 怎么解决的，能说一下么？

**Comment by moudatuo** [comment]
好像是115导入的时候新建的文件夹会有这种问题，文件夹名称是很普通没有特殊字符，自己在网盘手工创建的文件夹，然后文件移动进去下载就没问题

**Comment by liupan1890** [comment]
> 好像是115导入的时候新建的文件夹会有这种问题，文件夹名称是很普通没有特殊字符，自己在网盘手工创建的文件夹，然后文件移动进去下载就没问题

可能是文件夹名中包含了不可见的特殊字符（ \f \n \r \t \v \b ）导致创建文件夹失败（另外window 文件名不能含有 < > : " / \ | ? *  不能空格开头）

我会在下个版本中对导入秒传时的文件路径再处理一下，清除掉这些特殊字符

**Comment by zzh151223** [comment]
> > 好像是115导入的时候新建的文件夹会有这种问题，文件夹名称是很普通没有特殊字符，自己在网盘手工创建的文件夹，然后文件移动进去下载就没问题
> 
> 可能是文件夹名中包含了不可见的特殊字符（ \f \n \r \t \v \b ）导致创建文件夹失败（另外window 文件名不能含有 < > : " / \ | ? * 不能空格开头）
> 
> 我会在下个版本中对导入秒传时的文件路径再处理一下，清除掉这些特殊字符

我看了下是文件夹名后面多了个空白字符，不知道是什么，从115提出来是没有空白字符的

**Comment by zzh151223** [comment]
> > > 好像是115导入的时候新建的文件夹会有这种问题，文件夹名称是很普通没有特殊字符，自己在网盘手工创建的文件夹，然后文件移动进去下载就没问题
> > 
> > 
> > 可能是文件夹名中包含了不可见的特殊字符（ \f \n \r \t \v \b ）导致创建文件夹失败（另外window 文件名不能含有 < > : " / \ | ? * 不能空格开头）
> > 我会在下个版本中对导入秒传时的文件路径再处理一下，清除掉这些特殊字符
> 
> 我看了下是文件夹名后面多了个空白字符，不知道是什么，从115提出来是没有空白字符的

小白羊版看不出来，在app可以看到，是换行符，目前解决办法是批量重命名，删除文件夹名最后1个字符

**Comment by liupan1890** [comment]
等下个版本会自动处理这些特殊字符（其实v2.8.30本身已经处理了一部分特殊字符了，但不够全面）。就不需要你自己重命名了

为什么会有换行呢，这就要问创建115秒传链接的人了，（或者之后复制粘贴分享出来的人）

这不重要，自动清理一下就好了
