### ISSUE TITLE
返回上级时能返回之前位置吗，整理文件返回时每次都要下拉寻找

### ISSUE THREAD

**Issue by vtrayy** [liupan1890/aliyunpan#214]
如题

**Comment by liupan1890** [comment]
>整理文件返回时每次都要下拉寻找

寻找什么？

因为你说了下拉，我理解的是，你的文件夹是这样  `根目录`--`第一级`--`第二级`--`第三级`
在第三级里，你想直接返回到第一级，是这个意思吗？

不同层级的目录，快速跳转，应该使用左边的文件夹树，直接点击你想要的文件夹就可以了，而不是通过点击返回上级按钮


返回上级按钮只能返回上级，

>返回之前的位置

比如你现在是在第三级，之前的位置不就是第二级吗？因为你先从第二级，进入的第三级

**Comment by liupan1890** [comment]
这种问题吧，感觉说不清楚，你应该给我一个操作录像，让我知道你具体的需求，具体的操作步骤，我明白了你的使用情况，才能明白功能设计

**Comment by iD2073** [comment]
其实他说的是下图1的功能，现在具备的返回其实是2的功能，标注见下图：
![image](https://user-images.githubusercontent.com/87513821/132125441-13066f13-09ef-4218-b579-d210c5c947b5.png)

**Comment by KHLFYY** [comment]
我觉得 @vtrayy 说的那种返回（即1的功能）应该不是有很大需求吧（我个人是没有这种需求）

在文件资源管理器里的返回，一般是 复制剪切再粘贴 这种移动文件的时候会用到 返回 的功能 

但是小白羊（等网盘）是不支持（也没有必要支持）这种移动文件的方式

个人看法，觉得没有这个功能的需求

**Comment by vtrayy** [comment]
> > 整理文件返回时每次都要下拉寻找
> 
> 寻找什么？
> 
> 因为你说了下拉，我理解的是，你的文件夹是这样 `根目录`--`第一级`--`第二级`--`第三级`
> 在第三级里，你想直接返回到第一级，是这个意思吗？
> 
> 不同层级的目录，快速跳转，应该使用左边的文件夹树，直接点击你想要的文件夹就可以了，而不是通过点击返回上级按钮
> 
> 返回上级按钮只能返回上级，
> 
> > 返回之前的位置
> 
> 比如你现在是在第三级，之前的位置不就是第二级吗？因为你先从第二级，进入的第三级

是我说得不够清楚,情况没那么复杂。我的情况是这样：假设根目录下有a、b、c一直到z个文件夹，我从a文件夹一直整理到z文件夹，从根目录的a文件夹点进去整理完返回，界面是原来初始位置；点进b文件夹整理返回，界面是原来初始位置。整理到c时需要下拉一点点从c点进去，整理到y返回时，界面还是初始位置，我要下拉到最后找到z。我知道z可以通过目录树点进去，但是有2个问题：1.新版本的目录树是默认是隐藏的，每次使用都要点出来，然后再点文件夹进去，再点击一下目录树才消失，之后才能操作文件，对比返回上一级点下一个文件夹步骤多一点，而且后者感觉连贯；2.我并不都是要点进文件夹，我可能要直接操作整个文件夹。比如创建秒传、移动z文件夹到a文件夹。这时候我希望在y文件夹中返回上级，位置是点进去之前的位置，然后可以直接操作整个z文件夹。

**Comment by vtrayy** [comment]
> 这种问题吧，感觉说不清楚，你应该给我一个操作录像，让我知道你具体的需求，具体的操作步骤，我明白了你的使用情况，才能明白功能设计

才发现一个问题，我一直以为新版本的目录树是隐藏的，每次用都要点出来，所以很少用。点了全屏后才发现目录树可以一直存在，然后测试关了全屏拉伸界面到一定程度才可以“只需点一次就可以永久存在”，旧版本我界面拉伸到最小目录树都可以一直存在。

**Comment by liupan1890** [comment]
@vtrayy  问一下你的屏幕是多大的？就是多少寸的屏幕或者多少分辨率？

一般常见笔记本是14寸-17寸，一般常见电脑是22寸-27寸
一般常见分辨率是1980*1080

因为默认第一次启动小白羊是屏幕分辨率*0.677  如果你的屏幕分辨率超过1366*768 理论上，你第一次运行时就会直接一直显示左边的目录树，也就是不会让你误解需要点击才显示目录树

只有分辨率较低时，才会自动隐藏目录树，此时需要点击才能显示出来

所以我需要问问你，是你的屏幕真的很小，还是程序有BUG第一次运行时没有显示目录树？

另外：目录树上也是可以右键菜单的，


>2.我并不都是要点进文件夹，我可能要直接操作整个文件夹。比如创建秒传、移动z文件夹到a文件夹

这种直接在目录树上对应的文件夹名上右键菜单最方便

**Comment by vtrayy** [comment]
> @vtrayy 问一下你的屏幕是多大的？就是多少寸的屏幕或者多少分辨率？
> 
> 一般常见笔记本是14寸-17寸，一般常见电脑是22寸-27寸
> 一般常见分辨率是1980*1080
> 
> 因为默认第一次启动小白羊是屏幕分辨率_0.677 如果你的屏幕分辨率超过1366_768 理论上，你第一次运行时就会直接一直显示左边的目录树，也就是不会让你误解需要点击才显示目录树
> 
> 只有分辨率较低时，才会自动隐藏目录树，此时需要点击才能显示出来
> 
> 所以我需要问问你，是你的屏幕真的很小，还是程序有BUG第一次运行时没有显示目录树？
> 
> 另外：目录树上也是可以右键菜单的，
> 
> > 2.我并不都是要点进文件夹，我可能要直接操作整个文件夹。比如创建秒传、移动z文件夹到a文件夹
> 
> 这种直接在目录树上对应的文件夹名上右键菜单最方便



> @vtrayy 问一下你的屏幕是多大的？就是多少寸的屏幕或者多少分辨率？
> 
> 一般常见笔记本是14寸-17寸，一般常见电脑是22寸-27寸
> 一般常见分辨率是1980*1080
> 
> 因为默认第一次启动小白羊是屏幕分辨率_0.677 如果你的屏幕分辨率超过1366_768 理论上，你第一次运行时就会直接一直显示左边的目录树，也就是不会让你误解需要点击才显示目录树
> 
> 只有分辨率较低时，才会自动隐藏目录树，此时需要点击才能显示出来
> 
> 所以我需要问问你，是你的屏幕真的很小，还是程序有BUG第一次运行时没有显示目录树？
> 
> 另外：目录树上也是可以右键菜单的，
> 
> > 2.我并不都是要点进文件夹，我可能要直接操作整个文件夹。比如创建秒传、移动z文件夹到a文件夹
> 
> 这种直接在目录树上对应的文件夹名上右键菜单最方便

为了测试这个问题，我删掉了原来的文件夹，将小白羊解压到另一个地方打开，发现左侧目录树没有显示，点出来也不能一直显示。同时有个疑惑，登录信息不是保存在解压文件夹内的么，为什么我删掉原来文件夹解压在另一个地方，运行后账号信息还有。笔记本大小没记错的话是15.6寸，win10显示分辨率1920×1080，缩放和布局125%

**Comment by liupan1890** [comment]
在v1.6.28里，所有数据是保存在解压文件夹内的

在v2开始，因为使用了Electron所有数据是保存在C:\Users\用户名\AppData\Roaming\alixby里面的

**Comment by vtrayy** [comment]
> 在v1.6.28里，所有数据是保存在解压文件夹内的
> 
> 在v2开始，因为使用了Electron所有数据是保存在C:\Users\用户名\AppData\Roaming\alixby里面的
> 
> 下个版本我调整一下吧，确保第一次默认显示文件树

感谢解答。既然不能通过删除文件夹完全卸载，能否提供一个uninstall.exe呢

**Comment by liupan1890** [comment]
嗯，会在正式版本里加uninstall.exe

**Comment by ybbluesky** [comment]
> Roaming
其实把用户文件放在软件目录更绿色呀，其实不太希望v2改了存放地点，还是给v1一样最好

**Comment by liupan1890** [comment]
首先是开发的问题

v2用的是electron，本身会创建一堆的缓存文件。因为这些文件都是自动创建的，并且对electron的运行很重要，不能让用户在electron运行时手动删除这些文件。所以所有的electron程序（比如阿里云盘官方PC版），都会遵守electron的默认约定，让electron自动的将这对文件保存在C:\Users\用户名\AppData\Roaming\下

可以在启动时通过启动参数强制修改保存位置，但大家都不这样做，而是都遵守默认约定，
约定这个东西吧就不好说了，但如果是把这些文件保存到解压目录下，确实会遇到一些奇奇怪怪的问题，比如因为解压路径+缓存文件，最后的路径名过长，导致无法保存文件之类，比如用户手动删除文件释放空间之类

v2的数据库呢也是使用的electron内置的数据库，数据库文件也是electron自动管理保存在C:\Users\用户名\AppData\Roaming\下的。因为已经在Roaming保存了一堆文件了，就算把数据库单个文件保存到解压目录，也没意义，反而会因此导致有的用户升级版本时误删数据库，不能直接继续使用（需要重新登陆）

v1使用的flutter，并没有这一堆缓存文件，所以就直接把数据库文件放到解压目录了

**Comment by iD2073** [comment]
我觉得像v2这样保存登录信息挺好的，免得每次更新都要重新登录一样，那样太麻烦，知道了保存的路径，想彻底删除的自己可以找到相关的路径删除即可，真的不有必有纠结这些。

**Comment by liupan1890** [comment]
在v2.12.05上线的帮助文档里，已经提供了卸载的帮助说明
