### ISSUE TITLE
potplayer复制进去还是以默认方式播放

### ISSUE THREAD

**Issue by xuxudong1110** [liupan1890/aliyunpan#215]
7月29日的版本，是不是版本不对，32位和64位都试过了，
![image](https://user-images.githubusercontent.com/49015852/132150003-33333aba-14c2-4e86-91b5-e3263228ea31.png)

**Comment by JinxAgain** [comment]
PotplayerMini.exe 改成 Potplayer.exe

**Comment by liupan1890** [comment]
我写的教程说的这么不清楚吗？我去改改，划重点

**Comment by DifferentSparkler** [comment]
建议你还是不要换了  我自己换过potplayer试用了几天还是改回MPV了  MPV播放原始文件更流畅   用potplayer经常出现一些小问题

**Comment by xuxudong1110** [comment]
是我肤浅了，我怕改了没有用，谢谢作者大佬和楼上的朋友。
