### ISSUE TITLE
建议增加一个小功能，多选时能以每个一级目录创建各自的秒传文件

### ISSUE THREAD

**Issue by hejie132500** [liupan1890/aliyunpan#217]
如题，比如电视剧目录里有多个文件夹，每个文件夹对应一部电视剧，多选后可以直接按一级目录生成各自的秒传文件，这就很方便了，目前我是把生成的秒传文件下载到本地，然后拆分成多个单文件，然后上传保存，Python代码如下：
```python
import json
import os

# 创建存放拆分后的秒传文件的目录
dirStr = os.path.dirname(os.path.abspath(__file__)).replace("/", "\\") + '\\秒传文件'
dirStr = dirStr.strip()
is_exists = os.path.exists(dirStr)
if not is_exists:
    os.makedirs(dirStr)

print(F'''
    ------------------------------------------------------------------------------------
    此脚本作用于 “阿里云盘小白羊版v2.8.30” 生成的秒传文件，选中多目录并生成秒传链接
    后，将生成的秒传文件下载到本地并拖入本窗口，就可以按一级目录拆分成多个秒传文件。
    
    拆分后的秒传文件将保存于下面的目录：
    {dirStr}
    -------------------------------------------------------------------------------------
    
    ''')
url = input("输入要拆分的秒传文件地址或直接拖入文件")
file = open(url, 'r', encoding='utf-8-sig')
source = json.load(file)

# 拆分并保存文件
for item in source["DirList"]:
    newFile = dirStr + "\\" + item["Name"] + ".txt"
    f = open(newFile, 'w', encoding='utf-8-sig')
    item = str(item).replace("\'", "\"")
    f.write(item)
    f.close
    print("保存秒传文件", newFile)
input("\n\n秒传文件拆分完成！")
```

**Comment by iD2073** [comment]
这个确实是很好的建议，很需要

**Comment by liupan1890** [comment]
这个功能确实非常方便，增加起来也不麻烦

但是，有个观念的问题

### 1.我自己并不推荐大家过多的使用秒传txt功能去分享

个人保留，那么不需要拆分目录，直接一整个txt文件就可以了。因为当前导入秒传txt文件，支持TB级，和数万文件级别的导入，导入时也可以随意的勾选文件/文件夹。所以并没有拆分txt文件的必要

确实有必要的时候，自己一个文件夹一个文件夹的去创建就好了

为了抑制使用秒传txt功能去分享，所以不会增加此功能

### 2.我自己并不推荐大家过多的使用秒传txt功能

最开始秒传txt功能是因为我网盘空间不够用所以开发出来的，当时阿里云盘自己也是使用的秒传接口

然后几个月后，阿里云盘已经推出了新的秒传接口，新的秒传接口已经不能使用sha1实现秒传了

按照这样去看，总有一天，旧的秒传接口会被停止使用。那么总有一天，大家创建的秒传txt文件会全部失效。这个是阿里云盘的功能更新，并非我可以预料，也不是我能够控制的

所以，当前我已经不再安排对现有的秒传txt功能做功能上的升级了。

并不是不让用了/不能用了，而是不能再推荐大家用了，避免最后大家一些重要的文件可能无法恢复

最后，在v2正式版推出时，我也会在github首页/小白羊使用帮助里对此明确说明

**Comment by liupan1890** [comment]
> 这个确实是很好的建议，很需要。最希望能增加导入别人的阿里云盘分享的链接，可以直接生成秒传文件，这样就不用保存到自己的网盘了，等以后什么时候需要的时候再导入就可以了，

之前有人提过，我当时解释了一下

阿里云盘分享里并不包括sha1值，所以想要实现阿里云盘分享链接创建秒传txt

必须先把分享链接保存到自己的网盘里，然后才能创建秒传txt

又因为阿里云盘分享链接的保存是异步的，极端情况下可能需要数分钟后才能保存完全部的文件

所以自动保存分享链接+自动创建秒传txt，并没有好的体验。

最终还是让用户自己保存，自己创建txt

**Comment by hejie132500** [comment]
> 这个确实是很好的建议，很需要。最希望能增加导入别人的阿里云盘分享的链接，可以直接生成秒传文件，这样就不用保存到自己的网盘了，等以后什么时候需要的时候再导入就可以了，

作者的担心不无道理，的确有人直接分享秒传文件，这点背离了阿里的分享功能，我个人提这这个仅是个人需要，你如有类似的需求，可用上面的python3脚本

**Comment by hejie132500** [comment]
> 这个功能确实非常方便，增加起来也不麻烦
> 
> 但是，有个观念的问题
> ### 1.我自己并不推荐大家过多的使用秒传txt功能去分享
> 
> 个人保留，那么不需要拆分目录，直接一整个txt文件就可以了。因为当前导入秒传txt文件，支持TB级，和数万文件级别的导入，导入时也可以随意的勾选文件/文件夹。所以并没有拆分txt文件的必要
> 
> 确实有必要的时候，自己一个文件夹一个文件夹的去创建就好了
> 
> 为了抑制使用秒传txt功能去分享，所以不会增加此功能
> ### 2.我自己并不推荐大家过多的使用秒传txt功能
> 
> 最开始秒传txt功能是因为我网盘空间不够用所以开发出来的，当时阿里云盘自己也是使用的sha1+size的秒传接口
> 
> 然后几个月后，阿里云盘已经推出了新的秒传接口，新的秒传接口已经不能使用sha1+size实现秒传了
> 
> 按照这样去看，总有一天，旧的秒传接口会被停止使用。那么总有一天，大家创建的秒传txt文件会全部失效。这个是阿里云盘的功能更新，并非我可以预料，也不是我能够控制的
> 
> 所以，当前我已经不再安排对现有的秒传txt功能做功能上的升级了。
> 
> 并不是不让用了/不能用了，而是不能再推荐大家用了，避免最后大家一些重要的文件可能无法恢复
> 
> 最后，在v2正式版推出时，我也会在github首页/小白羊使用帮助里对此明确说明

感谢你的超详细解释，提出这点仅个人需求，写完脚本后想到可能别有也会有类似的要求就提出来了。

的确有人直接分享秒传文件，这导致了一些违法的内容可以直接跳过官方的分享机制进行传播
