### ISSUE TITLE
请问未来有没有考虑新增linux下的命令行版本？

### ISSUE THREAD

**Issue by ChenDY2233** [liupan1890/aliyunpan#218]
如题，
1、命令行版本更方便用于挂机上传文件，比如可以夜间挂着上传任务。
2、更方便使用脚本，用于定期备份等。

**Comment by liupan1890** [comment]
并不会推出命令行版本，因为当亲github上已经有很多命令行工具了，做的都挺不错的

命令行工具，一般体积只有几兆，并且也都是绿色版本无需安装，

小白羊是UI版本，优点是操作方便，

这是2种方向，所以并没有任何命令行方面的功能支持

**Comment by ChenDY2233** [comment]
- [ ] 好的明白，谢谢回复

**Comment by hejie132500** [comment]
>     * [ ]  好的明白，谢谢回复

issue结束就把它结束啊😂
