### ISSUE TITLE
远程 aria2 能否支持 secure 参数

### ISSUE THREAD

**Issue by sukanka** [liupan1890/aliyunpan#219]
## 问题描述
像  ariaNg 连接 aria2 那样，能够通过 https/wss 连接aria2。我给本地的aria2 启用了 secure, 
![Screenshot_20210907_143243](https://user-images.githubusercontent.com/31362108/132295678-cc6b34c1-ba0f-47fc-a2a1-390e286e56e4.png)
但是在小白羊里面无法连接。
![Screenshot_20210907_143409](https://user-images.githubusercontent.com/31362108/132295890-42c0465b-f89b-434b-a7ee-be417e2c4b9d.png)
用 localhost 提示没有设置 ip 和端口号。
![Screenshot_20210907_143507](https://user-images.githubusercontent.com/31362108/132295961-b2d965bc-da00-4353-9e82-4e0e37dbfe19.png)
## 需求
加入对通过 https/wss 连接 aria2 的支持.

**Comment by liupan1890** [comment]
嗯，
问题一：https/wss

是不支持https的，只支持http。

问题二:locahost 提示错误

换成127.0.0.1就可以了

**Comment by liupan1890** [comment]
能说一下为什么想要https吗？

1.https需要自己配置服务器端
你必须自己配置vps上架设nigin反代，才能启用https，大部分人也不会去配置

2.https意义是什么？

**Comment by sukanka** [comment]
其实是因为我用的自己部署的 [AriaNG](https://aria.sukanka.com/#!/downloading) 面板, 网页启用了 https（因为强迫症，http的话网页会提示不安全）, 就不能通过 http/ws 连接 aria2，只能通过 https/wss，所以我给本地的 aria2 也安排上了 https/wss。

**Comment by sukanka** [comment]
本地 https 也不算很麻烦，
1. 安装 mkcert： sudo pacman -S mkcert
2. 生成证书：mkcert localhost
3. 改 `aria2.conf`
```
# 是否启用 RPC 服务的 SSL/TLS 加密,
# 启用加密后 RPC 服务需要使用 https 或者 wss 协议连接
rpc-secure=true
# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件,
# 使用 PEM 格式时，您必须通过 --rpc-private-key 指定私钥
rpc-certificate=/home/sukanka/.local/share/mkcert/localhost.pem
# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件
rpc-private-key=/home/sukanka/.local/share/mkcert/localhost-key.pem
```

**Comment by liupan1890** [comment]
1. AriaNG 也支持http协议，所以可以关闭aria2c的https，直接使用http
2. 针对aria2来说，https并没有实际意义。就好比你拿了一块钱，非要放进保险箱，没有实际的意义
其实小白羊的aria远程下载，更推荐你单独开启一个aria2c实例，而不是混合使用

方案一：配置开启一份 AriaNG ，自己网页管理 AriaNG 的自己手动添加的下载任务，并配置小白羊远程链接，自动下载小白羊的任务

这种（应该就是你当前在使用的），并不好，因为你自己会频繁的手动添加删除任务，有时候误操作，把小白羊自动创建的任务删除或暂停了，会导致小白羊界面混乱

方案二：配置开启2份 AriaNG 
第一个实例呢，就是你自己平时手动下载的，网页管理，开启https

第二个实例呢，只给小白羊下载用。不开启https 

这样最好了


>本地 https 也不算很麻烦

会的不难，就好比我一直说，小白羊开发起来其实很简单，只是靠时间堆出来的，大部分程序员只要肯花时间都可以很轻松的开发出小白羊来，并没有什么艰难的技术在里面，这是真的，但是也有很多人不会typescript

其实大部分使用aria的都应该会配置https，但是我自己从来也没配置过aria的https，纯粹是感觉没用

我不增加https功能是因为我感觉没用懒的加，这是实话，但并不是不重视用户的反馈，你能理解吗

**Comment by sukanka** [comment]
好的。确实，您说的方案一有道理，有时候会误删。我还是用方案二吧。小白羊就用小白羊的aria2实例了，浏览器下载就用我原本的aria2实例，这样两个不混淆！感谢您的指点。
