### ISSUE TITLE
关于115解析

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#22]
大佬，关于115链接：
现在115分享链接 都不带 前缀 115:// ，要是能加个勾选框，自动加上115前缀就好了
![image](https://user-images.githubusercontent.com/19268555/120968790-e3c30800-c79b-11eb-902b-752131ecd01c.png)

另外，在解析链接这个输入框中，输入法切换中英文不好使【win10 用的搜狗输入法】

**Comment by liupan1890** [comment]
收到

1. 115链接，我在下个版本会处理一下，
因为我很少用，就测试了一个脚本115转存助手ui优化版v2.2
原来有很多链接不给加115前缀的啊，这个真不科学：你怎么确定这就是115呢，稍后我看怎么处理合适

2. 在解析链接这个输入框中，输入法切换中英文不好使
界面是flutter，对桌面的支持并不完善，这个我也没办法，没经验，只能先这样了，估计等一两年后flutter官方就修复此问题了
不是我黑他，flutter官方更新的超级慢的，很多小bug都等很久了还不改

**Comment by omy2000** [comment]
支持大佬

**Comment by liupan1890** [comment]
> 大佬，关于115链接：
> 现在115分享链接 都不带 前缀 115:// ，要是能加个勾选框，自动加上115前缀就好了
> ![image](https://user-images.githubusercontent.com/19268555/120968790-e3c30800-c79b-11eb-902b-752131ecd01c.png)
> 
> 另外，在解析链接这个输入框中，输入法切换中英文不好使【win10 用的搜狗输入法】


现在你直接粘贴这种无头的链接就可以了，解析时会自动补全

另外回复我一下，这种无头链接你是用什么插件生成的，把插件网址回复给我，我去确认一下链接的格式是否准确

**Comment by yayaleslie** [comment]
这个不是插件生成的，链接都是别的大佬分享的，都不带前缀，像这种
![image](https://user-images.githubusercontent.com/19268555/121716738-fa0df280-cb12-11eb-8213-ff7e704c83c1.png)
我觉得可以加个勾选框，勾选了默认加上115前缀

**Comment by liupan1890** [comment]
当前并不需要勾选框了，你直接粘贴进去点击解析就可以了，可以自动识别出来

**Comment by yayaleslie** [comment]
大佬 厉害
