### ISSUE TITLE
2.8.30 在win7上运行会花屏

### ISSUE THREAD

**Issue by midpoint** [liupan1890/aliyunpan#221]
如题。

**Comment by liupan1890** [comment]
能帮我截个屏吗？我看看

**Comment by liupan1890** [comment]
因长期未回复关闭

花屏问题很少见，其实可以通过更换electron的版本解决。请参阅https://github.com/liupan1890/aliyunpan/blob/main/linux%E6%89%93%E5%8C%85.md

按照步骤更换electron为其他版本（例如v13.X  小白羊本身用的是v12.0.9）
