### ISSUE TITLE
同步盘功能

### ISSUE THREAD

**Issue by liuluping0106** [liupan1890/aliyunpan#224]
大佬好啊，请问什么时候能支持同步盘功能啊，十分期待！！！

**Comment by liupan1890** [comment]
初步计划是在2周后会开发同步盘功能

**Comment by liuluping0106** [comment]
大佬，还有个小小的建议，能不能支持ui换色啊，这个大红看时间长了总觉得不太舒服。

**Comment by Borber** [comment]
> 初步计划是在2周后会开发同步盘功能

赞

**Comment by liupan1890** [comment]
> 大佬，还有个小小的建议，能不能支持ui换色啊，这个大红看时间长了总觉得不太舒服。

说一个颜色，以后优先安排

**Comment by liuluping0106** [comment]
> > 大佬，还有个小小的建议，能不能支持ui换色啊，这个大红看时间长了总觉得不太舒服。
> 
> 说一个颜色，以后优先安排

哈哈，这么好么。那要我说，当然是蓝色！

**Comment by iD2073** [comment]
![image](https://user-images.githubusercontent.com/87513821/132521206-bb37ca97-d020-4ba5-bbcb-ed4aed2a3e2d.png)
![image](https://user-images.githubusercontent.com/87513821/132521314-a294ed7e-dcf2-451d-bed5-6960329ce2bd.png)
这人蓝色就很舒服，深色模式，也换成这个蓝色也不错，

**Comment by liupan1890** [comment]
嗯，等以后做到皮肤时，会优先安排蓝色的，深色模式和浅色模式的皮肤会保持一致（都是红色/或者都是蓝色）
