### ISSUE TITLE
阿里云网页秒传脚本失效，秒传已死

### ISSUE THREAD

**Issue by sailing178** [liupan1890/aliyunpan#227]
https://bbs.tampermonkey.net.cn/thread-427-1-1.html
![image](https://user-images.githubusercontent.com/89731041/132542485-389d95bd-17ce-4468-b8ba-717be6035bd0.png)

**Comment by sailing178** [comment]
# #225

**Comment by MOIX-1192** [comment]
https://bbs.tampermonkey.net.cn/thread-955-2-1.html 秒传绕过了审核 被封也是迟早的事 唉还是那些搞颜色的人害得

**Comment by rapmq0** [comment]
秒传凉了，以后分享文件都得看阿里的脸色了

**Comment by gt562559842** [comment]
> 秒传凉了，以后分享文件都得看阿里的脸色了

我说怎么今天导入的文件都没有

**Comment by hejie132500** [comment]
传播不合规的文件并不是秒传被封的原因吧，文件在上传之后就审核，审核不过就自动删除，就没有秒传的事了，以后秒传真的被封只有可能是因为都去用秒传了，就会少很多付费扩容的用户，所以你懂的

**Comment by Anza7i** [comment]
阿里云盘靠不住，溜了溜了

**Comment by KHLFYY** [comment]
> 传播不合规的文件并不是秒传被封的原因吧，文件在上传之后就审核，审核不过就自动删除，就没有秒传的事了，以后秒传真的被封只有可能是因为都去用秒传了，就会少很多付费扩容的用户，所以你懂的

确实 一方面是绕过审核的问题 另一方面是不用官方分享链接可能那边不愿意

但是我觉得最主要的还是因为**秒传节约空间容量**的问题

**Comment by ChloeKurumi** [comment]
> 传播不合规的文件并不是秒传被封的原因吧，文件在上传之后就审核，审核不过就自动删除，就没有秒传的事了，以后秒传真的被封只有可能是因为都去用秒传了，就会少很多付费扩容的用户，所以你懂的

是被举报的，就是这个人，举报之后还炫耀
https://t.bilibili.com/556264183990884490
