### ISSUE TITLE
【功能建议】增加下载完成后删除文件功能

### ISSUE THREAD

**Issue by breathiness** [liupan1890/aliyunpan#228]
现在下载分享的资源时，文件下载后经常会需要手动再删除掉文件。
能否增加功能选项，可以选择在文件下载后自动删除对应的文件呢？

**Comment by liupan1890** [comment]
当前版本对分享功能并没有细致的去开发，以后会增加直接下载分享链接内的文件（不需要转存），这样也就不用下载后删除了
