### ISSUE TITLE
能否提供完整的项目编译过程？

### ISSUE THREAD

**Issue by abcfy2** [liupan1890/aliyunpan#229]
作者你好，非常喜欢你的软件，想请教下如何从源码构建出最终的成品包？谢谢

**Comment by liupan1890** [comment]
v1.6.28时开源的，完整的源码，下载后

aliserver
windows的编译命令
``````
set GOOS=windows
set GOARCH=amd64
go build -ldflags="-H windowsgui -w -s" -o ./aliserver.exe ./
``````

alixby windows编译命令
``````
flutter build windows
``````


其它系统（linux mac）基本一致，具体编译命令请自行百度

aliserver是golang，编译命令就是golang的标准编译命令，在golang官网有
alixby是flutter，编译命令就是flutter的标准编译命令，在flutter官网有

所以，如果你学习过flutter和golang语言，你就不会问了，但如果你没学过这两种语言，需要看这两者的官方文档，按照官方教程先一步一步的配置语言编译环境

这个不属于小白羊项目的范围，需要你自己摸索了


v2.8.30 并未开源，使用的是typescript，可以自行asar解压修改webpack打包后的源码。
v2也不打算开源，因为开源的目的是共同进步，但因为我能力有限，编写的源码并不规范，大家也不喜欢给我pull，所以v2就不拿出来献丑了

**Comment by abcfy2** [comment]
多谢了

**Comment by Borber** [comment]
> v1.6.28时开源的，完整的源码，下载后
> 
> aliserver
> windows的编译命令
> 
> ```
> set GOOS=windows
> set GOARCH=amd64
> go build -ldflags="-H windowsgui -w -s" -o ./aliserver.exe ./
> ```
> 
> alixby windows编译命令
> 
> ```
> flutter build windows
> ```
> 
> 其它系统（linux mac）基本一致，具体编译命令请自行百度
> 
> aliserver是golang，编译命令就是golang的标准编译命令，在golang官网有
> alixby是flutter，编译命令就是flutter的标准编译命令，在flutter官网有
> 
> 所以，如果你学习过flutter和golang语言，你就不会问了，但如果你没学过这两种语言，需要看这两者的官方文档，按照官方教程先一步一步的配置语言编译环境
> 
> 这个不属于小白羊项目的范围，需要你自己摸索了
> 
> v2.8.30 并未开源，使用的是typescript，可以自行asar解压修改webpack打包后的源码。
> v2也不打算开源，因为开源的目的是共同进步，但因为我能力有限，编写的源码并不规范，大家也不喜欢给我pull，所以v2就不拿出来献丑了

中文开源环境还是没有英文的好, 不过 v2 还是考虑一下开源吧 pull 总会有的

**Comment by abcfy2** [comment]
对了，如果v2开源的话我会花时间可以PR一个github action看看，自动构建各平台的产品包
