### ISSUE TITLE
赞一下👍🏻

### ISSUE THREAD

**Issue by Lijingze2019** [liupan1890/aliyunpan#23]
https://b23.tv/ES8dif
之前还写了一下直接用mpv拉取阿里云盘的原视频，原来大佬已经做出来了哈哈

**Comment by Lijingze2019** [comment]
所以mpv用的是精简的吗？能自己写mpv.conf配置文件吗？或者直接用电脑上已经有的mpv

**Comment by Lijingze2019** [comment]
另外会考虑做移动端吗？flatter的好处我记得就是多端部署？这样的话能在播放视频的时候调移动端mpv（或其他播放器）吗？我记得onedrive有类似的功能

**Comment by liupan1890** [comment]
>直接用电脑上已经有的mpv


需要手动选择mpv路径，大部分用户很反感--（我就想一点就放，不关心是什么播放器），所以就没有这个功能。

>播放视频的时候调移动端mpv

小白羊只支持windows。mac也会有，不会支持安卓。因为我没精力管理这么多系统

**Comment by Lijingze2019** [comment]
> > 所以mpv用的是精简的吗？能自己写mpv.conf配置文件吗？或者直接用电脑上已经有的mpv
> 
> 哦，才仔细看，是完整版的mpv啊，配置文件也完全没问题，所以不打算加一点预先的设置吗？比如硬解，mpv默认是软解
> 
> 你可以自己直接配置mpv，只需要按照mpv官方说明里的路径，保存配置文件，让mpv启动时能够自动加载到就可以了
> 
> 印象里mpv默认会加载2个，一个是同目录下的，一个是c:/用户/xxx 文件夹下的，记不清了，看一下官方帮助文档吧
> 
> 我不会配置mpv，只是用来在线看一下视频，并没有配置的需求。软解硬解不都一样看吗？
> 我知道有些视频格式配合有些特定的设置可以提升清晰度，我只看mp4,mkv，都不看4K的--因为没有4K屏，所以从来没折腾过。。。。

确实，我只是考虑到会有一些用户存一些高分辨率高帧率的视频，比如4K 50fps，在我的笔记本上需要硬解才解码的动。软件占用CPU，硬解占用显卡独立的视频解码模块，所以有些时候硬解会剩很大CPU占用。mpv默认使用软解因为兼容性好。当然各有优劣。

可以用refer的“播放器”我知道的另外一个也就是ffplay了

**Comment by Lijingze2019** [comment]
能不能临时生成m3u8列表文件？像这样
![image](https://user-images.githubusercontent.com/52600662/121211917-77392d80-c8af-11eb-8ef9-147e7d2ab297.png)
这样mpv可以播放完整列表，听歌的时候可能更有用。但是阿里云盘的直链的变动不知道怎么处理好，不确定mpv加载m3u8的时候是不是实时刷新读取。列表上一个/下一个的控制应该是鼠标侧键或Shift+，Shift+。

**Comment by liupan1890** [comment]
1. mpv直接支持播放列表功能，并不需要通过绕路m3u8实现列表播放
2. 小白羊里不会集成播放列表功能，你不要把它想得太复杂，用过6盘小白羊的话你就知道了，我只习惯于提供简洁的功能，让他好用，我就满足了。开发源码的目的是让有特殊需求的用户去自己定制自己的需求。这样，我维护起来省力一点

**Comment by Lijingze2019** [comment]
👌🏽
