### ISSUE TITLE
v2.8.30 两个小BUG

### ISSUE THREAD

**Issue by hejie132500** [liupan1890/aliyunpan#230]
一、列表左侧勾选一个文件夹时，顶部不会出现菜单，必须选中两个或更多才会出现；
二、选中一个文件夹并将它移动到其它目录后，选中依然是一个不会变，再次选中一个文件夹时顶部显示“已选中 2/xx 个”，而实际只选中了一个，而由第一个BUG，这时顶部显示了菜单。

只选中一个文件顶部并不会出现菜单
![图片](https://user-images.githubusercontent.com/55620869/132622324-c8954ad2-b204-40c7-8556-591aab2b8dd7.png)

这是移动文件后的界面
![图片](https://user-images.githubusercontent.com/55620869/132622082-17bfd8d2-2a44-4c2f-b8f5-cf24d85e76ba.png)

这是移动文件后再次选中一个文件或文件夹的界面
![图片](https://user-images.githubusercontent.com/55620869/132622182-acbf5f93-d805-4a25-85e3-6a03e780ea5c.png)

**Comment by liupan1890** [comment]
嗯，收到。移动后那个确实是BUG

选中一个文件不出现菜单是故意这样设计的，但你只选中一个文件时，需要使用右键菜单

只有选中了多个文件以后，可以通过顶部菜单操作，也可以通过右键菜单操作

这样设计的目的是方便

我自己经常是这样，不知道什么时候点中了一个文件（比如在线看一个视频）

然后不久，看完了，需要导入新的视频，此时可以直接点击顶部导入

如果选中一个文件时，也显示顶部菜单。则此时我想导入，必须先取消选中这个文件才行

就是为了节省一次点击。也是为了推广右键菜单
