### ISSUE TITLE
原秒传链接被封失效，还有望复活吗？

### ISSUE THREAD

**Issue by Golubb** [liupan1890/aliyunpan#233]
看介绍是阿里方面做了更新，原来的链接全部失效了。不知道是否还有可能出新的秒传方式？

**Comment by liupan1890** [comment]
参见 https://github.com/liupan1890/aliyunpan/issues/225

现在从技术上看是不可能的

**Comment by gexiaosen** [comment]
感觉没可能了

**Comment by MOIX-1192** [comment]
![](https://files.catbox.moe/pth8zw.png)
脚本作者已经删除跑路了

**Comment by bilibini** [comment]
唉，可惜了
