### ISSUE TITLE
作者有计划做挂载本地盘的功能吗

### ISSUE THREAD

**Issue by touzi-xiansheng** [liupan1890/aliyunpan#234]
作者有计划做挂载本地盘的功能吗

**Comment by liupan1890** [comment]
在GitHub上已经有阿里云盘的webdav程序，另外也有现成的支持多种网盘挂在本地的程序了（你可以搜一下issue，有人提过，忘了叫啥了）

所以我并没有打算做本地盘的功能。已经有了，不需要我去做了
