### ISSUE TITLE
解压文件大小限制

### ISSUE THREAD

**Issue by liuluping0106** [liupan1890/aliyunpan#235]
经常手残点到几个g的压缩文件，然后程序就卡住了。
求问大佬，能不能添加一个自动解压大小限制，或者能打断施法也好！！！

**Comment by liupan1890** [comment]
回复我一下，是什么原因卡住

1.是压缩包里有很多文件时会卡住？
2.是压缩包里不管文件多少，只要体积大于XX就会卡住？

卡住的意思，是指什么？界面无反应？多长时间无反应？然后会显示压缩包内的文件列表对吧？

之后的版本会增加设置，可以自己选择是双击打开文件，还是单击打开文件（当前是默认单击打开）

**Comment by yayaleslie** [comment]
大佬，7Z后缀的格式可以支持吗

**Comment by liupan1890** [comment]
在线解压，只是调用官方的在线解压功能，但官方当前并不支持7z格式，所以小白羊也无法支持

但官方一直在升级，可能以后就支持7z了

但百度网盘这么多年了还是只支持zip 和 rar 所以也可能阿里云盘也一直不支持7z

仅从编程角度去思考

zip/rar/7zip
的在线解压功能无区别，7z解压功能也不涉及7z的使用版权问题

所以各大网盘不支持7z在线解压纯粹是服务问题，懒得做，而不是技术问题
