### ISSUE TITLE
秒传

### ISSUE THREAD

**Issue by liveskai** [liupan1890/aliyunpan#236]
https://www.bilibili.com/video/BV1164y1x7F3
https://t.bilibili.com/556264183990884490?tab=2

**Comment by rapmq0** [comment]
谢谢兄弟，已经冲了
![QQ图片20210910135152](https://user-images.githubusercontent.com/83964337/132806284-694b1c93-2309-49c2-98d1-7f33f5058877.png)
![QQ图片20210910135148](https://user-images.githubusercontent.com/83964337/132806285-dc027cf9-a332-41b8-a94d-6f021e2d9f5d.png)

**Comment by gexiaosen** [comment]
没必要口吐芬芳 真的没必要

**Comment by rapmq0** [comment]
> 没必要口吐芬芳 真的没必要

未经他人苦，莫劝他人善

**Comment by Anza7i** [comment]
这波的确是阿里太傻逼了，最起码也要给个时间让我们把文件下回来吧，吐了，不会再用了

**Comment by yayaleslie** [comment]
必须吐槽一波
![image](https://user-images.githubusercontent.com/19268555/132853661-f3f9de9b-f420-4bb3-99e4-79b175113c31.png)

**Comment by barnett2010** [comment]
操你妈的大傻逼。压缩包文档全要重传。操死你全家

**Comment by liupan1890** [comment]
@barnett2010  压缩包文档全要重传

你以前上传过的话（并且不是自己独一份的文件），仍然可以通过本地的文件秒传上去。但如果是自己创建的压缩包，并且本地文件已经删除了，那就可能需要你完整的重新上传上去了
