### ISSUE TITLE
创建秒传过程中能否中止

### ISSUE THREAD

**Issue by vtrayy** [liupan1890/aliyunpan#237]
本想右键点击移动，但总是因为点得太快而误点上面的创建秒传，只能等遍历完后右上角关掉，比较费时，能否提供中止功能？

**Comment by liupan1890** [comment]
1.当前创建秒传遍历时间较长是逻辑问题，已经在下个版本中修正，遍历更快了

2.因为阿里云盘近期似乎关闭了旧版秒传接口的秒传功能，所以在以后小白羊也会直接取消秒传功能，全面转向为官方分享功能的优化

**Comment by vtrayy** [comment]
好的
