### ISSUE TITLE
文件夹名包含.点导致的：移动文件失败，请重新下载

### ISSUE THREAD

**Issue by breathiness** [liupan1890/aliyunpan#238]
尝试了清除后再次下载、退出其他 aria2 程序、重启电脑。依然出现相同报错。
![图片](https://user-images.githubusercontent.com/11361630/132977161-c68e802e-4815-4885-9a30-d0df8e07acf7.png)

**Comment by liupan1890** [comment]
请问是第一次使用就出现了此错误吗？从来也没有成功的下载过？你是什么操作系统？

1.出现此问题的原因
下载时，aria2c进程会创建 “下载文件名”+".td" 的临时文件
下载结束，小白羊进程会重命名此文件为“下载文件名”
既下载完成最后会删除掉“.td”这个多余的，临时的后缀

提示移动文件失败，就是重命名执行失败。

重命名为什么会失败？
1.可能没有权限
2.可能有重名文件导致冲突
3.文件被其他程序打开（锁定）导致无法重命名
能想到的只有这3个原因。

**Comment by liupan1890** [comment]
另，有win11用户上报说，必须使用管理员权限运行小白羊，才能下载。但我在win11测试没有遇到此问题

**Comment by liupan1890** [comment]
另：如果你的aria自己修改设置为 auto-file-renaming=true 或者默认设置本来就是 auto-file-renaming=true
当遇到下载时aria2会对冲突文件自动重命名，那么小白羊就找不到最新的文件名是什么了，最终会导致显示上面的错误

所以你必须主动的设置auto-file-renaming=false （在启动aria2c.exe的命令行，或者 .conf配置文件里）

但只会在本地文件名有冲突的时候显示移动失败错误，因为大部分时候本地不存在重名文件，所以不会出现这个冲突，这也是基本不可能出现的情况

**Comment by breathiness** [comment]
> 请问是第一次使用就出现了此错误吗？从来也没有成功的下载过？你是什么操作系统？

我的电脑是 win10 21H1但是我估计跟这些没有关系啊。我

因为下载其他内容时都没有问题，只有这个分享会出现这种情况。之前跟之后下载的文件都可以正常完成下载。

这个文件直接在线点开是没问题的，应该也不是被和谐了。


这是分享链接:https://www.aliyundrive.com/s/ZTt9biVJ2rr

**Comment by liupan1890** [comment]
找出问题来了，是BUG，是我清理路径清理的不完整，正则表达式匹配错误，会在下个版本修正

当前，你需要修改导入后的文件夹名

'XX社区20套 精品收费写真.' 注意最后的点了吗？删掉.

改名为'XX社区20套 精品收费写真' 就正常了，结尾不能有点，下个版本会修正此问题

**Comment by breathiness** [comment]
原来如此，还真没注意到。谢谢了

**Comment by liupan1890** [comment]
v2.9.15已修正此问题
