### ISSUE TITLE
今天好像开始看不到网盘文件了 是只有我的号有这个情况吗？

### ISSUE THREAD

**Issue by simcatSL** [liupan1890/aliyunpan#24]
只能看到回收站文件 网盘根目录文件都看不到 刷新 重新登陆 重新下载安装了都不行

**Comment by ymg0827965** [comment]
我的正常

**Comment by d790043608** [comment]
我的正常

**Comment by liupan1890** [comment]
我刚测试了一下但没发现异常

难道是有隐藏BUG？不敢想，我再多试试

**Comment by simcatSL** [comment]
> 我刚测试了一下但没发现异常
> 
> 难道是有隐藏BUG？不敢想，我再多试试

我刚刚发现原因了。。。昨天一直登不上是因为我手机开着vpn扫码登陆的 这样登陆上之后就算vpn关了 电脑端的都不显示，关了重新扫码登陆就行了， 这算是个BUG么

**Comment by liupan1890** [comment]
恩给，你说的这个情况我也遇到过，原因是golang似乎对代理更新检测的不太准确
（你开VPN--golang走代理）（你关VPN--golang应该不走代理--但实际上golang还是走代理--最终走不通）

解决方式粗暴一点的就是直接关闭golang的代理检测，不管你开不开VPN我都不走，用真实IP访问，也就没事了
但是考虑到又有人需要走代理，默认我就没关闭代理检测，我也不知道怎么设置最合适。我再想想啊

当然啦，在设置里增加一个代理的开关也就可以了，但是我又纠结想让设置里简洁一点，怕这么多设置太乱了，关键是增加了这个设置，很多人也不知道怎么用，比如你遇到了无法显示，还是习惯直接重启程序就好了，不跟你说的话估计你也想不到是代理的问题，应该去设置里关闭代理对吧

**Comment by simcatSL** [comment]
> 恩给，你说的这个情况我也遇到过，原因是golang似乎对代理更新检测的不太准确
> （你开VPN--golang走代理）（你关VPN--golang应该不走代理--但实际上golang还是走代理--最终走不通）
> 
> 解决方式粗暴一点的就是直接关闭golang的代理检测，不管你开不开VPN我都不走，用真实IP访问，也就没事了
> 但是考虑到又有人需要走代理，默认我就没关闭代理检测，我也不知道怎么设置最合适。我再想想啊
> 
> 当然啦，在设置里增加一个代理的开关也就可以了，但是我又纠结想让设置里简洁一点，怕这么多设置太乱了，关键是增加了这个设置，很多人也不知道怎么用，比如你遇到了无法显示，还是习惯直接重启程序就好了，不跟你说的话估计你也想不到是代理的问题，应该去设置里关闭代理对吧

不过确实这个情况不影响使用 也很少有人会像我这样开着vpn扫码登陆云盘 影响应该不大的 您辛苦拉

**Comment by yoo799** [comment]
![1](https://user-images.githubusercontent.com/85617330/121337531-38f34b00-c94f-11eb-94a5-d3b1db3c274a.png)
我的是这样，换了几个地址都没办法，希望大神帮帮忙

**Comment by liupan1890** [comment]
![捕获](https://user-images.githubusercontent.com/67817756/121356356-57fbd800-c963-11eb-92fd-ed6776aa2886.PNG)


``````
115://浪潮之巅第4版.吴军.pdf|9155421|9F204F996CFDE3E5B5125EFC9BCCE928866F4C1E|6D11CAAC5541E382202799CE8F3881E8D0CC06DC
``````


仅支持115秒传链接，不支持115分享链接

**Comment by yoo799** [comment]
> ![捕获](https://user-images.githubusercontent.com/67817756/121356356-57fbd800-c963-11eb-92fd-ed6776aa2886.PNG)
> 
> ```
> 115://浪潮之巅第4版.吴军.pdf|9155421|9F204F996CFDE3E5B5125EFC9BCCE928866F4C1E|6D11CAAC5541E382202799CE8F3881E8D0CC06DC
> ```
> 
> 仅支持115秒传链接，不支持115分享链接

谢谢大神！懂了

**Comment by LuJiaWeiwei** [comment]
> 恩给，你说的这个情况我也遇到过，原因是golang似乎对代理更新检测的不太准确
> （你开VPN--golang走代理）（你关VPN--golang应该不走代理--但实际上golang还是走代理--最终走不通）
> 
> 解决方式粗暴一点的就是直接关闭golang的代理检测，不管你开不开VPN我都不走，用真实IP访问，也就没事了
> 但是考虑到又有人需要走代理，默认我就没关闭代理检测，我也不知道怎么设置最合适。我再想想啊
> 
> 当然啦，在设置里增加一个代理的开关也就可以了，但是我又纠结想让设置里简洁一点，怕这么多设置太乱了，关键是增加了这个设置，很多人也不知道怎么用，比如你遇到了无法显示，还是习惯直接重启程序就好了，不跟你说的话估计你也想不到是代理的问题，应该去设置里关闭代理对吧
那下载的时候应该不会走代理吧，这样不会消耗代理流量？
