### ISSUE TITLE
Aria2下载不能连续推送

### ISSUE THREAD

**Issue by BH2TYQ** [liupan1890/aliyunpan#242]
使用环境：Win/Mac版本客户端；架设在白群辉上的Aira2+AriaNg，容器名称：p3terx-aria2-pro,p3terx-ariang; 外网环境通过域名+端口推送任务
问题描述：使用小白杨推送下载任务，任务上限设定为最大，线程设置为最大，一次性批量下载超过50个时，仅能一次性向Aria2推送50个任务，后续任务在客户端中显示排队中，但在Aria2中无后续推送，即需要重新逐个下载可保证同一文件夹下可以下载完全（比如武林外传一共81集，全选后点击下载，前50个任务会直接推送到Aria2中，并可顺利完成下载，但后续31个一直显示排队中，暂停重新开始或优先下载也无法重新启动任务）
问题影响：同一文件夹下有多层目录且小文件极其多的情况下，下载后的文件不可用；仅能依靠打包后上传再下载
期望解决方案：1. 实现连续推送，保障文件下载完全 2. 在线打包功能也可解决

**Comment by liupan1890** [comment]
我去测试一下，看是哪里的BUG

**Comment by liupan1890** [comment]
忘了回复了，等明天的最新版试试吧，应该可以正常的连续推送才对

**Comment by liupan1890** [comment]
v2.9.15已修正此问题
