### ISSUE TITLE
不能用秒传之后，感觉阿里云那么大的空间没啥用了

### ISSUE THREAD

**Issue by gt562559842** [liupan1890/aliyunpan#243]
大文件又分享不起，也接收不了，就相当于个人小型网盘，裂开

**Comment by Anza7i** [comment]
现在就靠不限速口号撑着，不知道以后会员制会怎么搞

**Comment by ChloeKurumi** [comment]
封秒传简直就阿里败笔，还不如别出分享功能，大家用秒传多好.........百度和谐这么久了都还能秒传，阿里却因为sq理由和谐了，好像就没人再分享sq了一样......

**Comment by rapmq0** [comment]
限时的空间本来就没啥用啊，总会到期的
