### ISSUE TITLE
115迁移到阿里云盘秒传功能

### ISSUE THREAD

**Issue by bms8889990** [liupan1890/aliyunpan#244]
在吾爱上看到一篇帖子，好像可以通过这位作者的软件实现阿里云盘的秒传
先将115秒传链接导入到115，然后再使用这个软件上传到阿里云盘从而实现秒传
不知道这种秒传方式的原理是什么？
https://www.52pojie.cn/thread-1490131-1-1.html

**Comment by rapmq0** [comment]
![51a758d5af1140edc7845319593c98cb_scaled](https://user-images.githubusercontent.com/83964337/133100451-779658e6-6585-433e-9d65-381c9af9de2e.jpg)

**Comment by liupan1890** [comment]
顺嘴说一句，正规的115秒传链接插件，都是这样做的，因为115秒传时需要文件固定的1024字节数据，计算这些数据的sha1.
所以正常的115插件，创建的115秒传链接，都是4段的 
'115://文件名.mp4|1024|sha1|sha2'

估计阿里云盘开发人员也是参考的115这个方式，只是更改了数据长度为8字节，并加上了随机位置

**Comment by BrandonStudio** [comment]
@bms8889990 能否把原帖发出来？该帖似乎从第二页起仅对注册用户可见

**Comment by BrandonStudio** [comment]
>
> 如果是115分享链接的话，也可以不登陆，没有115网盘账号，破解出文件的下载地址就可以了，只下载那8个字节
>
@liupan1890 不登录也可以破解出文件的下载地址吗？如果是大于5GB的文件，免费用户似乎也无法获取该文件，这样的情况下也能破解文件的下载地址吗？

抱歉打扰您了。

**Comment by liupan1890** [comment]
我并没有深入研究过115----因为我平时不用115

不登录免费用户也不能下载，但并不一定说就不能获得下载地址，需要看115的具体是怎么限制的，我就是按照思路这么一说，真正具体的怎么解密出115的下载地址，我并没有尝试过，所以我也不清楚
