### ISSUE TITLE
关于挂载本地盘和视频播放的建议

### ISSUE THREAD

**Issue by carolzzn** [liupan1890/aliyunpan#245]
希望大佬可以做一个挂载本地的类似的脚本，因为我使用的挂载是来自于另外一个做了这个挂载的大佬@webdav-aliyundriver这个大佬，因为大部分人挂载到本地的目的就是为了看云盘里的电影电视剧，用potplayer播放有很好的是适配性，因为我用了大佬的小白羊的播放器，就突然产生了这个想法。希望大佬可以把这两个结合起来，也就不用小白羊内置的播放器了，可以使用本地的potplayer播放器了。也可以做到类似挂载的功能。感谢大佬的辛苦付出了

**Comment by liupan1890** [comment]
1.v2.8.30已经支持调用Potplayer了，看首页有教程

2.挂载已经有很多人在做了，已经有完善的工具，并不需要我去做了

**Comment by carolzzn** [comment]
感谢大佬的回复  我刚看到可以调用potplayer  谢谢

**Comment by nokaka** [comment]
最近，阿里云盘上线了会员中心，299一年20t，aliyunwebdav的项目配合rclone或者nextcloud挂载并加密使用还是很香的。
但是这几个webdav项目在文件上传和文件同步上存在诸多问题，例如大文件报错、同步报错、不支持sha1校验、只能通过文件大小判断文件修改、不支持断点续传。
这些项目上传方面特性不及作者的项目，希望作者能够考虑通过某些形式实现本地挂载。
