### ISSUE TITLE
又一个免费的2T云盘 希望有时间可以看看能不能基于小白羊做个客户端

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#246]
www.123pan.com
![360截图20210914002344115](https://user-images.githubusercontent.com/38945550/133121543-5c678681-d44a-4d3a-9dea-d85c3d73ff97.jpg)

也可以联系下官方看看能不能挣个外快

**Comment by ChloeKurumi** [comment]
我比较好奇你是怎么知道这网盘的？？我定期找有没有新网盘，都没看见.....

**Comment by iD2073** [comment]
这个123盘，会不会像下一个曲奇云盘？

**Comment by liupan1890** [comment]
应该是刚出的 联网备案时间2021-09-07
参照以前的6盘，有分享功能的，没有大公司做后台的，做不起来的

**Comment by rapmq0** [comment]
小公司 刚成立一个月 不靠谱啊

**Comment by Miluxs** [comment]
![image](https://user-images.githubusercontent.com/30521608/133279979-2ff5635c-17bd-4596-8c48-504b5e66169c.png)
![image](https://user-images.githubusercontent.com/30521608/133280131-19f5ddcb-7b43-4254-95d4-e71c1be4a43b.png)

**不能说一模一样，只能说一直不差**

**Comment by fohuhu** [comment]
这种网盘不敢用吧，存存电影可以，重要的文件还是算了吧
