### ISSUE TITLE
建议增加epub和mobi文件的阅读

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#247]
阿里云盘的移动端有一个书架功能，可以阅读epub和mobi文件，但是官方的pc端没有此功能，希望小白羊版能增加上，现打开epub是乱码，打开mobi是网页源代码

**Comment by liupan1890** [comment]
嗯，以后会尝试的

**Comment by aionyzq** [comment]
我最近使用一个叫Koodo Reader的电子书阅读器，体验还不错。首发在吾爱破解，不过也有缺点：1.暂时不支持阅读进度记忆；2.目前只有Windows客户端。

**Comment by ybbluesky** [comment]
> 我最近使用一个叫Koodo Reader的电子书阅读器，体验还不错。首发在吾爱破解，不过也有缺点：1.暂时不支持阅读进度记忆；2.目前只有Windows客户端。

谢谢，现电脑端就是用的这个软件
