### ISSUE TITLE
大量文件上传出现假死？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#248]
当大量的文件及子文件夹上传时，出现cpu占用99%，软件出现白色，大家是否有同样问题？

**Comment by liupan1890** [comment]
嗯，之前有issue了，明晚发布的新版就是针对数据库性能做的改进，可以修正此问题

**Comment by ybbluesky** [comment]
> 嗯，之前有issue了，明晚发布的新版就是针对数据库性能做的改进，可以修正此问题

那期待晚上的更新了

**Comment by liupan1890** [comment]
v2.9.15已修正此问题
