### ISSUE TITLE
文件加密、洗码功能

### ISSUE THREAD

**Issue by liao666brant** [liupan1890/aliyunpan#25]
文件加密、洗码功能
1.可以对文件快速洗码(1秒内)，给文件生成新的sha1码，然后再上传到网盘（视频洗码后不影响在线预览）
2.可以对文件快速完整加密，加密后的文件无法预览，保护隐私（视频无法预览和截图，图片/文本/Doc/Pdf等文件无法在线预览）
3.可以对加密后的文件，快速解密恢复为原始文件
——————
以上功能是否还未完成？
建议在上传时添加是否需要洗码功能，毕竟有些文件不会被和谐可以秒传也是不错的

**Comment by liupan1890** [comment]
是的，洗码还没上线

考虑到集成后用户容易误操作，洗码功能会以单独的小程序(exe)提供下载。毕竟也只有少数人用得到

放心吧，默认情况下，对你的文件没有影响
