### ISSUE TITLE
作者你好 忽然发现昨天开始小白羊生成的秒传全部失效 似乎秒传接口挂了

### ISSUE THREAD

**Issue by zhouxinhuagg** [liupan1890/aliyunpan#250]
作者你好 忽然发现昨天开始小白羊生成的秒传全部失效 似乎秒传接口挂了

**Comment by rapmq0** [comment]
![51a758d5af1140edc7845319593c98cb_scaled](https://user-images.githubusercontent.com/83964337/133547989-8fc6ebb9-7ca5-491e-93e7-99285489ad18.jpg)

**Comment by d790043608** [comment]
借楼问下文件洗白！在线改文件md5有没有办法实现？

**Comment by Anza7i** [comment]
> 借楼问下文件洗白！在线改文件md5有没有办法实现？

不可能的，阿里云目前没这样的接口

**Comment by liupan1890** [comment]
9月8号就挂了 ，参阅 https://github.com/liupan1890/aliyunpan/issues/225

**Comment by liupan1890** [comment]
>借楼问下文件洗白！在线改文件md5有没有办法实现？

阿里云盘不支持在线修改文件内容（似乎可以在线编辑文档，但支持格式有限，没细看。但肯定没有在线修改文件功能）
