### ISSUE TITLE
v2.9.15新版本的包被 Microsoft Defender 报严重威胁

### ISSUE THREAD

**Issue by GB1818** [liupan1890/aliyunpan#252]
之前 v1.6、v2.8都没有出现这种情况
下载的是 .7z 那个包

[了解更多信息](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fSabsik.TE.A!ml&threatid=2147780197)

![image](https://user-images.githubusercontent.com/29467754/133625787-d00987b8-5ccf-429b-a1ae-589b4163576a.png)

**Comment by ChloeKurumi** [comment]
应该不是文件的问题，我浏览器下载也报错，试了下，蓝奏网盘的文件都这样，应该是蓝奏的问题

**Comment by liupan1890** [comment]
因为自v2.8.1开始，所有版本都是 electron（100MB）+MPV（80MB） 不变，每次升级只是更新了app.asar文件

但v2.9.15更新了最新版本的aria2c (从v1.35 更新到 v1.36)


所以报毒，
原因一：可能是蓝奏云网址被拦截，

原因二：可能是因为aria2c v1.36 太新（24天前发布的），被误报。如果是这个，以后用的人多了会自动解除误报

明天我重新发布一下，先更换一下其他网盘试试

**Comment by liupan1890** [comment]
帮我试一下文叔叔 从文叔叔下载 https://ws28.cn/f/6etwl1cc0kg

我的电脑因为已经关闭了win10的更新，从哪里下载都没有报毒

**Comment by GB1818** [comment]
> 帮我试一下文叔叔 从文叔叔下载 https://ws28.cn/f/6etwl1cc0kg
> 
> 我的电脑因为已经关闭了win10的更新，从哪里下载都没有报毒


这个也报

**Comment by liupan1890** [comment]
我重新打包了一遍，请帮我测试一下蓝奏是否报毒（我又把aria2c.exe换回以前的1.35了）

**Comment by GB1818** [comment]
> 我重新打包了一遍，请帮我测试一下蓝奏是否报毒（我又把aria2c.exe换回以前的1.35了）


没问题了

**Comment by liupan1890** [comment]
收到，谢啦，看来确实是aria2c.exe的问题，那就先不升级了
