### ISSUE TITLE
希望增加跨网盘文件移动、复制功能

### ISSUE THREAD

**Issue by at2008** [liupan1890/aliyunpan#253]
希望增加跨网盘文件移动、复制功能，不知道是否有计划？

**Comment by ChloeKurumi** [comment]
想多了，所谓的跨网盘都是下载后再上传，要么就是利用秒传，但问题是阿里云秒传已经挂了.......
不过可以使用CloudDrive把阿里云挂载到本地使用........

**Comment by liupan1890** [comment]
并没有跨网盘文件的功能规划

**Comment by hongtucao8384** [comment]
跨网盘觉得意义不大，搞定同步盘优先级更高更有价值。

**Comment by at2008** [comment]
> 并没有跨网盘文件的功能规划

我的意思是阿里云盘跨账号文件移动、复制，之前说的估计会被误解为跨不同公司网盘。

**Comment by ybbluesky** [comment]
> > 并没有跨网盘文件的功能规划
> 
> 我的意思是阿里云盘跨账号文件移动、复制，之前说的估计会被误解为跨不同公司网盘。

同为阿里盘，用分享解决呀

**Comment by liupan1890** [comment]
账号间复制这个功能已经在规划中

但因为我近期没啥时间开发，所以进度较慢，以后会慢慢增加的！

人穷事多，要恰饭的
