### ISSUE TITLE
真实极限上传文件测试出了bug

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#255]
文件夹为：A---B---C------D,B文件夹内有10000个文件夹，每个c文件夹内有30-50个文件夹不等，每个d文件夹内1-10个文件不等，当程序运行一段时间内程序白屏，强行退出后重启程序正常，然后再运行一段时间出现如图：
![1631838213827](https://user-images.githubusercontent.com/34271895/133705058-8d4896c1-c4e9-4fe7-8f5e-6b5b3ae6124c.jpg)
只有重启程序，现在运行2小时还在解析文件夹，程序看起来正常。从昨天晚上到现在，程序运行过程中白屏和如图所示各出现一次，版本为2.9.15昨晚新版本

**Comment by ybbluesky** [comment]
发此文时又现了创建文件夹失败

**Comment by liupan1890** [comment]
我测试过数万文件的，但我没测试过1万文件夹的

当前阿里云盘，因为是每一个文件夹需要列一次文件，1万个文件夹大概需要列1小时这样（估算，没实际测过）

白屏，肯定是有BUG--也可能是内存不足导致的白屏，看你截图屏幕怎么这么小？你的电脑内存多大？（我是想分析一下是内存不足导致electron白屏还是因为代码BUG导致白屏）

创建文件夹失败，试试管理员权限运行。因为创建失败一般是权限问题，也可能是路径名问题，你把网盘里‘Isle of the lost(1721) ’这个文件夹的完整路径告诉我一下

（在网盘里这个文件夹上，右键，详情，拖选 位置，Ctrl + C）

**Comment by ybbluesky** [comment]
我再把详细情况说一下，我电脑是4g内存，I5，机器较老，图是手机远程截取的，所以较小，出现创建文件夹失败提示是程序运行一段时间后，已经上传了较多文件或者文件夹后会出现，今天已经出现了三次。出现提示后能出程序，然后重新上传，可以成功，我猜测是不是服务器有检测，一次上传太多会暂停上传？本地路径是这样
![image](https://user-images.githubusercontent.com/34271895/133734116-b8ffdd92-7edf-46dd-a9c6-c79bcbc369e0.png)
远程测是根目录下：
![image](https://user-images.githubusercontent.com/34271895/133734248-83036cf3-f1e3-46cc-985e-0ecf11077c87.png)

**Comment by ybbluesky** [comment]
> 我测试过数万文件的，但我没测试过1万文件夹的
> 
> 当前阿里云盘，因为是每一个文件夹需要列一次文件，1万个文件夹大概需要列1小时这样（估算，没实际测过）
> 
> 白屏，肯定是有BUG--也可能是内存不足导致的白屏，看你截图屏幕怎么这么小？你的电脑内存多大？（我是想分析一下是内存不足导致electron白屏还是因为代码BUG导致白屏）
> 
> 创建文件夹失败，试试管理员权限运行。因为创建失败一般是权限问题，也可能是路径名问题，你把网盘里‘Isle of the lost(1721) ’这个文件夹的完整路径告诉我一下
> 
> （在网盘里这个文件夹上，右键，详情，拖选 位置，Ctrl + C）

我初步猜测是官方的检测一次上传了太多文件与文件夹

**Comment by liupan1890** [comment]
额，我以为你说的下载呢，，，，，

那你先把同时任务数那里，设置为10个试试，设置为10个一般就不会触发官方的限制了

再v2.9.15里我把QPS限制放开为30了，因为遇到触发官方限制后，小白羊后台会休眠2秒后自动重试

可能我代码覆盖的不全，导致上传时创建文件夹时触发官方限制时没能正确处理（休眠重试）

稍后我再测试测试看看，是否是漏掉了

**Comment by liupan1890** [comment]
话说官方的QPS限制策略真是让我摸不着头脑，比如我昨天测试了一天，一次性上传 `162060个文件，264个文件夹  78.4GB`

除了第一次，之后都是秒传了,测试好几次，都没有触发官方的限制，后来开到30都没有触发。

触发时会返回429错误，但16万个文件秒传，也需要很长时间的，在这么长的时间里一直再疯狂的请求，他都不触发

**Comment by ybbluesky** [comment]
> 额，我以为你说的下载呢，，，，，
> 
> 那你先把同时任务数那里，设置为10个试试，设置为10个一般就不会触发官方的限制了
> 
> 再v2.9.15里我把QPS限制放开为30了，因为遇到触发官方限制后，小白羊后台会休眠2秒后自动重试
> 
> 可能我代码覆盖的不全，导致上传时创建文件夹时触发官方限制时没能正确处理（休眠重试）
> 
> 稍后我再测试测试看看，是否是漏掉了

谢谢你的回答，看来这个问题的确有不明原因，只有手动克服一下了

**Comment by liupan1890** [comment]
我确认了问题了，还是长时间后账号token失效，刷新后，没能正确的覆盖（数据库覆盖有延时，我刷新获取没有等待）。总之，下个版本会彻底修正这个问题的

**Comment by liupan1890** [comment]
发了v2.9.19 试一下，看BUG是否解决了

**Comment by teaper** [comment]
我是 archlinux 配合 aria2 进行下载，如果我本地配置的 aria2 启动有异常，那么也会这样无法下载，但是我配置好了 aria2 之后， 500 M  带宽的网速就体现出来了，贼快！😃
