### ISSUE TITLE
老哥，小白羊下载文件时，伴随着2到3MB/s的上传速度，能不能限制这个上传速度到一个比较小的值，如图

### ISSUE THREAD

**Issue by GJG666** [liupan1890/aliyunpan#257]
![image](https://user-images.githubusercontent.com/36781028/133730564-70c21357-c30d-4ddb-b885-a71363b9bf9e.png)

**Comment by GJG666** [comment]
使用的是默认模式下载，同时可下载10个文件，只是把每个文件的下载线程调到了16。

**Comment by rapmq0** [comment]
确实可以加个限速功能
![QQ截图20210917144353](https://user-images.githubusercontent.com/83964337/133736882-1771a5c1-7e68-436e-b812-99f4331d0ce3.png)

**Comment by GJG666** [comment]
这个功能既基础又实用，很多人都有这方面的需求，确实可以考虑考虑

**Comment by GJG666** [comment]
> 确实可以加个限速功能
> ![QQ截图20210917144353](https://user-images.githubusercontent.com/83964337/133736882-1771a5c1-7e68-436e-b812-99f4331d0ce3.png)

这个功能既基础又实用，很多人都有这方面的需求，确实可以考虑考虑

**Comment by mrhuzi** [comment]
P2P下载的，大家都限制上传速度，下载速度就慢了

**Comment by liupan1890** [comment]
因为下载时是完全调用aria2去下载的，只下载时：

1.aria2并没有P2P功能，所以不会存在分享流量
2.实际上并没有任何上传操作，下载时唯一能想到的就是联网请求这个操作，他的上传流量应该非常低才对，想要像截图中1MB/s的上传速度是不可能的（10*16=160链接，只是请求一下要下载，总流量我估算应该在10kb/s以内才正常）

我稍后会测试一下，看看问题在哪。不应该有上传流量的

**Comment by GJG666** [comment]
> 因为下载时是完全调用aria2去下载的，只下载时：
> 
> 1.aria2并没有P2P功能，所以不会存在分享流量
> 2.实际上并没有任何上传操作，下载时唯一能想到的就是联网请求这个操作，他的上传流量应该非常低才对，想要像截图中1MB/s的上传速度是不可能的（10*16=160链接，只是请求一下要下载，总流量我估算应该在10kb/s以内才正常）
> 
> 我稍后会测试一下，看看问题在哪。不应该有上传流量的

确实不应该，以前不是这样的，起码没有那么夸张，这次换了台新的电脑，只要下载速度起来了，上传速度就能跑到1到2MB/s，而且一直维持在这个范围，知道下载完毕

**Comment by GJG666** [comment]
> > 因为下载时是完全调用aria2去下载的，只下载时：
> > 1.aria2并没有P2P功能，所以不会存在分享流量
> > 2.实际上并没有任何上传操作，下载时唯一能想到的就是联网请求这个操作，他的上传流量应该非常低才对，想要像截图中1MB/s的上传速度是不可能的（10*16=160链接，只是请求一下要下载，总流量我估算应该在10kb/s以内才正常）
> > 我稍后会测试一下，看看问题在哪。不应该有上传流量的
> 
> 确实不应该，以前不是这样的，起码没有那么夸张，这次换了台新的电脑(但整体系统环境与之前无异)，只要下载速度起来了，上传速度就能跑到1到2MB/s，而且一直维持在这个范围，知道下载完毕

**Comment by liupan1890** [comment]
![上](https://user-images.githubusercontent.com/67817756/133759879-373c2e4b-68cb-4cf9-8c88-203d4cb4c11a.gif)


我刚刚测试了5分钟，没能发现上传问题

1. 使用小白羊下载 24个电影，平均3GB一个，10任务，16线程

如图，使用win10的资源管理器查看，加上任务管理器，加上小白羊自己显示的下载速度

小白羊下载速度40MB/s时 ,任务管理器显示当前上传1MB/s(9Mbps),资源管理器里aria2c.exe 上传速度为 1Kb/s到2Kb/s徘徊，小白羊.exe 上传速度为   0.2Kb/s 

2. 继续调整为20任务，16线程

区别不大

3. 然后，当我把小白羊关了（暂停下载），任务管理器里，上传速度也为0

总结：小白羊或aria2c.exe 并没有上传速度（1kb/s?可以忽略为0了），任务管理器显示的速度是计算了整个系统的上传速度，感觉应该还计入了回环速度，并不能准确体现小白羊的上传速度


任务管理器就是统计的小白羊上传1Mb/s 但资源管理器统计的是1kb/s 相差太大了，
纯理论上，资源管理器统计的是IP:端口的速度，即真实的外网互交速度，
纯编程角度上，aria2c.exe只是在下载，并没有设置上传的命令，此时能够产生的上行流量只是发送url的流量，1kb/s才正常
所以我还是感觉，纯属误报，计入了软件内部流量（注意aria本身是开启和绑定了一个本地端口，通过本地的http进行互交的）

**Comment by liupan1890** [comment]
我又做了一个测试，我的网络本身上传速度最大是4MB/s

我开着百度网盘（超级会员，很多文件一起上传，等待慢慢达到了4.4MB/s的最高速度）

开启小白羊下载

最终，百度网盘掉速为稳定4.1MB/s  并没有掉速为3.4MB/s 因为百度网盘本身上传速度就有波动（上传文件超过60%后会慢慢降速） ，所以据此也能说明，aria2c并没有占用1MB/s的上传速度。

**Comment by GJG666** [comment]
> ![上](https://user-images.githubusercontent.com/67817756/133759879-373c2e4b-68cb-4cf9-8c88-203d4cb4c11a.gif)
> 
> 我刚刚测试了5分钟，没能发现上传问题
> 
> 1. 使用小白羊下载 24个电影，平均3GB一个，10任务，16线程
> 
> 如图，使用win10的资源管理器查看，加上任务管理器，加上小白羊自己显示的下载速度
> 
> 小白羊下载速度40MB/s时 ,任务管理器显示当前上传1MB/s(9Mbps),资源管理器里aria2c.exe 上传速度为 1Kb/s到2Kb/s徘徊，小白羊.exe 上传速度为 0.2Kb/s
> 
> 1. 继续调整为20任务，16线程
> 
> 区别不大
> 
> 1. 然后，当我把小白羊关了（暂停下载），任务管理器里，上传速度也为0
> 
> 总结：小白羊或aria2c.exe 并没有上传速度（1kb/s?可以忽略为0了），任务管理器显示的速度是计算了整个系统的上传速度，感觉应该还计入了回环速度，并不能准确体现小白羊的上传速度
> 
> 任务管理器就是统计的小白羊上传1Mb/s 但资源管理器统计的是1kb/s 相差太大了，
> 纯理论上，资源管理器统计的是IP:端口的速度，即真实的外网互交速度，
> 纯编程角度上，aria2c.exe只是在下载，并没有设置上传的命令，此时能够产生的上行流量只是发送url的流量，1kb/s才正常
> 所以我还是感觉，纯属误报，计入了软件内部流量（注意aria本身是开启和绑定了一个本地端口，通过本地的http进行互交的）

非常感谢老哥的测试，刚才我用了两款专业的流量监测软件（glasswires、softperfect netmaster）测试了一会，确实发现，Aria2c.exe并没有真实的上传速度，看来确实是误报了。再次感谢老哥的测试！
![image](https://user-images.githubusercontent.com/36781028/133767574-54a29322-e20c-48ee-a48d-9cae2c68cd02.png)
