### ISSUE TITLE
网盘目录树拉取失败，重启和重新登陆都没用。。

### ISSUE THREAD

**Issue by saludossol** [liupan1890/aliyunpan#26]
![QQ截图20210610132248](https://user-images.githubusercontent.com/76832306/121469446-13b61980-c9ef-11eb-845c-c14170c3e20a.png)

**Comment by kk54250** [comment]
一样的问题

**Comment by liupan1890** [comment]
因为今天阿里云盘升级了，已发布新版本修正此问题了v1.6.10

**Comment by saludossol** [comment]
好滴，收到，辛苦了
