### ISSUE TITLE
突然报错无法使用，是我电脑出什么问题了吗

### ISSUE THREAD

**Issue by shemc** [liupan1890/aliyunpan#260]
突然就无法使用了，1.6还可以用，但是V2版都无法使用了，是我电脑出什么问题了

![小白羊](https://user-images.githubusercontent.com/44460073/133867949-fe58dcc4-bdc9-47d6-8a2a-e934db5b67cd.png)
吗
![2](https://user-images.githubusercontent.com/44460073/133867960-3a0773c6-f702-43ee-b42a-9d17b4dd9c54.jpg)

![3](https://user-images.githubusercontent.com/44460073/133867968-d4528849-fac4-44b6-beb5-0b0508e4b9d9.jpg)

![4](https://user-images.githubusercontent.com/44460073/133867976-daf0b133-a077-49c1-aec0-5c8aa5affb47.png)

![5](https://user-images.githubusercontent.com/44460073/133867977-f2fdab01-6dc8-479b-b04c-e911813b1129.png)

日志名称:          System
来源:            Microsoft-Windows-DistributedCOM
日期:            21.9.18 9:33:20
事件 ID:         10016
任务类别:          无
级别:            错误
关键字:           经典
用户:            PC2009122400PYF\smc
计算机:           PC2009122400pyf
描述:
应用程序-特定 权限设置并未向在应用程序容器 不可用 SID (不可用)中运行的地址 LocalHost (使用 LRPC) 中的用户 PC2009122400PYF\smc SID (S-1-5-21-1129715273-1690337115-2501898059-1001)授予针对 CLSID 为 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
、APPID 为 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 的 COM 服务器应用程序的 本地 激活 权限。此安全权限可以使用组件服务管理工具进行修改。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-18T01:33:20.059333500Z" />
    <EventRecordID>57595</EventRecordID>
    <Correlation />
    <Execution ProcessID="932" ThreadID="6920" />
    <Channel>System</Channel>
    <Computer>PC2009122400pyf</Computer>
    <Security UserID="S-1-5-21-1129715273-1690337115-2501898059-1001" />
  </System>
  <EventData>
    <Data Name="param1">应用程序-特定</Data>
    <Data Name="param2">本地</Data>
    <Data Name="param3">激活</Data>
    <Data Name="param4">{D63B10C5-BB46-4990-A94F-E40B9D520160}</Data>
    <Data Name="param5">{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}</Data>
    <Data Name="param6">PC2009122400PYF</Data>
    <Data Name="param7">smc</Data>
    <Data Name="param8">S-1-5-21-1129715273-1690337115-2501898059-1001</Data>
    <Data Name="param9">LocalHost (使用 LRPC)</Data>
    <Data Name="param10">不可用</Data>
    <Data Name="param11">不可用</Data>
  </EventData>
</Event>

**Comment by liupan1890** [comment]
1.系统事件中的错误信息，我不知道是否和小白羊有关。

2.第一张截图报错，是非期待的token，我怀疑是因为网络原因获取用户token时，返回的是错误的信息，导致未能正确解析

修正方法：
1.重启电脑重试（感觉你已经操作过了还是不行才发的issue）

2.打开`C:\Users\用户名\AppData\Roaming\alixby` 这个文件夹，把这个文件夹里的文件全部删除。重新打开小白羊即可
（等于清理掉小白羊的全部缓存数据/账号信息）。这个应该可以解决问题

**Comment by shemc** [comment]
> 1.系统事件中的错误信息，我不知道是否和小白羊有关。
> 
> 2.第一张截图报错，是非期待的token，我怀疑是因为网络原因获取用户token时，返回的是错误的信息，导致未能正确解析
> 
> 修正方法：
> 1.重启电脑重试（感觉你已经操作过了还是不行才发的issue）
> 
> 2.打开`C:\Users\用户名\AppData\Roaming\alixby` 这个文件夹，把这个文件夹里的文件全部删除。重新打开小白羊即可
> （等于清理掉小白羊的全部缓存数据/账号信息）。这个应该可以解决问题

删除C:\Users\用户名\AppData\Roaming\alixby 文件夹 解决问题 ，非常感谢！！！
