### ISSUE TITLE
打开长时间不用在后台，后来再打开界面就全白了，是怎么回事？

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#261]
BUG如题同上：

![1](https://user-images.githubusercontent.com/87513821/133884129-783d075b-2c0a-40b0-9236-2e9036f6f053.gif)

**Comment by liupan1890** [comment]
感觉应该是内存OOM，退出小白羊后重新打开应该就正常了吧？

我稍后排查一下，是否有内存占用过多的问题

**Comment by liupan1890** [comment]
在v2.9.24里有优化内存和数据库占用，应该可以减少白屏现象。如果有问题再重新提问吧
