### ISSUE TITLE
支持一下win7 32位吧

### ISSUE THREAD

**Issue by chesley-lhz** [liupan1890/aliyunpan#262]
家里百兆宽带 用网页版只能跑到两兆每秒 用官方只能几百kb 求求了搞个32位吧

**Comment by KHLFYY** [comment]
#130  这个支持32位吧……？你用的是v1.6吗 试试v2

**Comment by liupan1890** [comment]
请使用v2版本（今晚更新以后再下载，v2.9.15有BUG）

v2支持32位

v1采用flutter框架，本身无法支持32位

另：部分win7因为没有开启自动更新功能，导致win7里的.net 版本太低，使用electron可能会遇到白屏/花屏/无法正常使用

需要自行升级/安装最新版的.net
