### ISSUE TITLE
可不可以在秒传链接中加入直链的方法用以获取proof_code

### ISSUE THREAD

**Issue by bms8889990** [liupan1890/aliyunpan#263]
看到了一个开源项目，用的是在阿里云盘秒传链接中加入直链的方法用以获取文件的proof_code实现秒传功能
https://github.com/wxy1343/aliyunpan

**Comment by liupan1890** [comment]
嗯，我看了，很聪明的想法。但也有局限（因为阿里云盘的限制导致的局限）

1.直链的问题
如果文件本身是在阿里云盘里，然后创建这个文件的秒传链接+直链。那么这个秒传链接只在4小时内有效，超过4小时直链就失效了，比如重新创建秒传链接

所以就是，你不能把这个秒传链接发到论坛里，因为4小时就无效了。而其他人很难一直盯着，恰好在4小时内看到这个分享

如果这个文件是在115网盘里，我不知道115的链接多长时间有效，没研究过。但肯定也是有有效期的。有效期一般都不会太长，同上，

如果仅仅是几个熟人之间在Q群里分享，那就直接分享链接了，此种情境下秒传链接作用不大。

如果是在某个网站发布的永久有效的直链，以后阿里云盘会上线链接导入的功能（http 电驴  磁力 代下直接导入阿里云盘）。所以这种意义也不大，关键是这样的直连一般很难知道文件的sha1，无法创建秒传链接

**Comment by liupan1890** [comment]
2 速度的问题
一般导入，一个链接都是包含了几十上百个文件。导入的速度也快不起来。

**Comment by LucasZhao22** [comment]
> 嗯，我看了，很聪明的想法。但也有局限（因为阿里云盘的限制导致的局限）
> 
> 1.直链的问题
> 如果文件本身是在阿里云盘里，然后创建这个文件的秒传链接+直链。那么这个秒传链接只在4小时内有效，超过4小时直链就失效了，必须重新创建秒传链接
> 
> 所以就是，你不能把这个秒传链接发到论坛里，因为4小时就无效了。而其他人很难一直盯着，恰好在4小时内看到这个分享
> 
> 如果这个文件是在115网盘里，我不知道115的链接多长时间有效，没研究过。但肯定也是有有效期的。有效期一般都不会太长，同上，
> 
> 如果仅仅是几个熟人之间在Q群里分享，那就直接使用分享链接了，此种情境下秒传链接作用不大。
> 
> 如果是在某个网站发布的永久有效的直链，以后阿里云盘会上线链接导入的功能（http 电驴 磁力 代下直接导入阿里云盘）。所以这种意义也不大，关键是这样的直连一般很难知道文件的sha1，无法创建秒传链接

这个还是有一些意义的，可以用来分享一些官方分享不允许分享的影片，完全匿名的分享意义还是蛮大的

**Comment by KHLFYY** [comment]
> 这个还是有一些意义的，可以用来分享一些官方分享不允许分享的影片，完全匿名的分享意义还是蛮大的

想着靠“完全匿名”来分享“官方不允许的影片”，这种念头还是赶紧打消

**Comment by hummersyk** [comment]
我自己加了字幕重新压制的剧集，上传后没有分享过，现在只保留了秒传码，云盘和本地的源文件都删掉了，回收站也清了。

是不是就没办法找回了？没有任何人能访问到，变成"幽灵文件"了？

**Comment by liupan1890** [comment]
是，

1.你自己压制的，没有分享过，自你从网盘删除的那一刻起，就已经不能恢复了，虽然不知道阿里云盘具体的清理策略，但因为没有其他人引用这个文件，早晚会被自动清理掉的

2.当前秒传功能已经因为阿里云盘升级失效了

**Comment by xuecanlong** [comment]
> 嗯，我看了，很聪明的想法。但也有局限（因为阿里云盘的限制导致的局限）
> 
> 1.直链的问题
> 如果文件本身是在阿里云盘里，然后创建这个文件的秒传链接+直链。那么这个秒传链接只在4小时内有效，超过4小时直链就失效了，必须重新创建秒传链接
> 
> 所以就是，你不能把这个秒传链接发到论坛里，因为4小时就无效了。而其他人很难一直盯着，恰好在4小时内看到这个分享
> 
> 如果这个文件是在115网盘里，我不知道115的链接多长时间有效，没研究过。但肯定也是有有效期的。有效期一般都不会太长，同上，
> 
> 如果仅仅是几个熟人之间在Q群里分享，那就直接使用分享链接了，此种情境下秒传链接作用不大。
> 
> 如果是在某个网站发布的永久有效的直链，以后阿里云盘会上线链接导入的功能（http 电驴 磁力 代下直接导入阿里云盘）。所以这种意义也不大，关键是这样的直连一般很难知道文件的sha1，无法创建秒传链接

分享直接秒违规 而且分享有文件数量的限制 能不能出个导出某个目录的直链 然后可以给别人导入的
