### ISSUE TITLE
在线视频播放到一半播放器会停止响应

### ISSUE THREAD

**Issue by ty-peng** [liupan1890/aliyunpan#264]
只能通过任务管理器杀死进程，重新打开，但是一会播放器又会卡死

**Comment by liupan1890** [comment]
1.在线播放是调用MPV播放器，也可以自己换成Potplayer

2.在线播放分为 转码视频 和 原始文件 2种模式。转码是指m3u8 ts格式，阿里云盘转码后的视频，原始文件就是原始的视频文件

3.卡死，
原因一是可能网络不好无法继续播放。
原因二可能是播放原始文件时，原始文件的格式特殊或文件本身特殊（比如损坏/加密）导致播放到特定时间段就会卡死

**Comment by liupan1890** [comment]
解决方法一：
1.尝试播放其他视频，确认是所有视频都会卡死，还是特定的某个视频（或者某部电视剧的全部集）会卡死

2.尝试播放同一个视频的转码和原始模式

这2个操作都是为了排除特定视频文件的问题。这个不属于程序BUG

解决方法二：
尝试自己更换为Potplayer
