### ISSUE TITLE
建议可以设置上传与下载文件的格式

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#265]
有时目录中有很多文件，但是我们只需要在网盘保存特定一些格式文件，希望能出一个类似设置，可只上传下载特定文件格式文件

**Comment by KHLFYY** [comment]
可以用everything 官网：https://www.voidtools.com/zh-cn/

搜索出来你想要上传格式的文件 

然后将搜索后的文件上传 
---
个人觉得 开发这个功能……使用场景太少/很少有这样的需求

**Comment by ybbluesky** [comment]
需求可能是小众，但是实现了就可以有很多用法，保持了文件上传与下载文件夹一致，又减少了上传下载的数量，应该有一些人需要的。如果能同时设置下载的格式也就好了

**Comment by liupan1890** [comment]
这个功能不会增加，因为操作太复杂，影响用户体验

1.大部分用户用不到这个功能，因为他们上传前会自己手动的过滤要上传的文件（比如把要上传的文件移动到一个文件夹，比如只选择文件夹里的部分文件上传而不是上传整个文件夹）。
重点是即使有需要过滤的，也不是只想上传某些特定格式的文件。他只想上传某几个文件而这几个文件格式并不一定是一致的，他想排除掉某几个文件而这几个文件的格式可能包含了想要上传的文件

举个例子：XXX电视剧文件夹，里面有1-40集，都是MKV，他想上传1-10集，格式过滤没办法做到


2.就算极少数情况下，用到了这个过滤。那么再操作时也很繁琐

1.点击过滤按钮，2显示了当前文件涉及的全部的格式（可能几十种后缀名 .mkv .mp4 .mp3），3.勾选需要的格式（此时必须联动显示具体包含那些文件），4重复勾选查看检查确认。5.点击上传

下载同理，操作步骤过多，过于繁琐，不如自己直接在文件列表了批量的勾选具体想要下载的文件，操作更加简单，适应的情况更多（而不是仅仅格式过滤，例如上面只想下载1-5集），更加符合用户的习惯（大家一直都是勾选下载）

**Comment by ybbluesky** [comment]
> 这个功能不会增加，因为操作太复杂，影响用户体验
> 
> 1.大部分用户用不到这个功能，因为他们上传前会自己手动的过滤要上传的文件（比如把要上传的文件移动到一个文件夹，比如只选择文件夹里的部分文件上传而不是上传整个文件夹）。
> 重点是即使有需要过滤的，也不是只想上传某些特定格式的文件。他只想上传某几个文件而这几个文件格式并不一定是一致的，他想排除掉某几个文件而这几个文件的格式可能包含了想要上传的文件
> 
> 举个例子：XXX电视剧文件夹，里面有1-40集，都是MKV，他想上传1-10集，格式过滤没办法做到
> 
> 2.就算极少数情况下，用到了这个过滤。那么再操作时也很繁琐
> 
> 1.点击过滤按钮，2显示了当前文件涉及的全部的格式（可能几十种后缀名 .mkv .mp4 .mp3），3.勾选需要的格式（此时必须联动显示具体包含那些文件），4重复勾选查看检查确认。5.点击上传
> 
> 下载同理，操作步骤过多，过于繁琐，不如自己直接在文件列表了批量的勾选具体想要下载的文件，操作更加简单，适应的情况更多（而不是仅仅格式过滤，例如上面只想下载1-5集），更加符合用户的习惯（大家一直都是勾选下载）

有确是小众需要，我的意思不是通过手动来选取特定文件，而是程序批量自动选择符合要求的文件，如一个大的文件夹下我只下载xls和doc文件

**Comment by ybbluesky** [comment]
> 这个功能不会增加，因为操作太复杂，影响用户体验
> 
> 1.大部分用户用不到这个功能，因为他们上传前会自己手动的过滤要上传的文件（比如把要上传的文件移动到一个文件夹，比如只选择文件夹里的部分文件上传而不是上传整个文件夹）。
> 重点是即使有需要过滤的，也不是只想上传某些特定格式的文件。他只想上传某几个文件而这几个文件格式并不一定是一致的，他想排除掉某几个文件而这几个文件的格式可能包含了想要上传的文件
> 
> 举个例子：XXX电视剧文件夹，里面有1-40集，都是MKV，他想上传1-10集，格式过滤没办法做到
> 
> 2.就算极少数情况下，用到了这个过滤。那么再操作时也很繁琐
> 
> 1.点击过滤按钮，2显示了当前文件涉及的全部的格式（可能几十种后缀名 .mkv .mp4 .mp3），3.勾选需要的格式（此时必须联动显示具体包含那些文件），4重复勾选查看检查确认。5.点击上传
> 
> 下载同理，操作步骤过多，过于繁琐，不如自己直接在文件列表了批量的勾选具体想要下载的文件，操作更加简单，适应的情况更多（而不是仅仅格式过滤，例如上面只想下载1-5集），更加符合用户的习惯（大家一直都是勾选下载）

我的意思就是只想上传或者下载特定文件类型文件，如只想下载pdf和word文件，其它文件不下载或者上传
刚才又想了一下，从技术上应该难度不大，就是在上传或者下载的时候判断一下文件属性，如果是选中的文件类型，那就执行下载 或者上传，否则跳过则行

**Comment by liupan1890** [comment]
呃，我说的就是这个意思啊

你要上传pdf和word，那么，必须告诉小白羊“pdf”和“word”这2个字！小白羊才知道你只想上传pdf和word

然后你这个文件夹是想“pdf”和“word”，另外一个文件夹你可能只想“word”，另另外一个文件夹可能只想ppt，另另另外一个文件夹可能只想txt

所以，小白羊的程序里，你点击上传后，小白羊必须问你：当前文件夹里有（ppt,pdf，xls,doc,mp3）你要上传哪些？
你要手动的点击ppt，然后小白羊要列出所有的ppt文件，让你看一眼确认都是你想上传的（万一漏掉了一个统计.xls,你一看发觉了你就知道，哦，我还要勾选xls）。最后你确认了都是我想要上传的，只要ppt，不要其他的了，你要点击确认按钮

所以说操作太繁琐，体验不好

完了后，就如上，已经勾选了ppt，然后你就又发现，有10个ppt，但是其中一个ppt我不想要上传，怎么办？所以是不是所有的ppt前面还要有个勾选，可以取消指定的文件不上传？

你看，这个功能纯粹是为了开发而开发，根本不符合用户的使用场景和习惯

用户已经习惯了，在自己的电脑上，手动选择想要的文件，直接拖到小白羊里，而不是在小白羊里弹出3-4步的选择框确认那些文件要上传

**Comment by liupan1890** [comment]
重点就是，小白羊并不知道你只想下载ppt，你必须和小白羊互交操作（勾选ppt），小白羊才能知道你只想下载ppt

常用文件格式数百种，又有很多组合的情景（只要ppt，只要ppt和doc  只要pdf和txt），所以不能固定一个按钮：按钮名为只下载ppt。因为这个按钮作用太死，别人要pdf就不能用了

而是要弹窗，列出涉及的所有文件类型，然你勾选ppt和pdf，这个操作体验太差

**Comment by ybbluesky** [comment]
> 重点就是，小白羊并不知道你只想下载ppt，你必须和小白羊互交操作（勾选ppt），小白羊才能知道你只想下载ppt
> 
> 常用文件格式数百种，又有很多组合的情景（只要ppt，只要ppt和doc 只要pdf和txt），所以不能固定一个按钮：按钮名为只下载ppt。因为这个按钮作用太死，别人要pdf就不能用了
> 
> 而是要弹窗，列出涉及的所有文件类型，然你勾选ppt和pdf，这个操作体验太差

有这种想法肯定需要交互处理才行的
![image](https://user-images.githubusercontent.com/34271895/134103353-00046849-509d-422e-bc1b-20ca1c664b29.png)
 类似于这样，毕竟网盘是存资料的，有时不需要整个文件夹内容都上传或者下载

**Comment by liupan1890** [comment]
呃，所以我说这样的操作太繁琐，体验太差，不增加这个功能啊。。。
