### ISSUE TITLE
希望提供转码视频下载方式

### ISSUE THREAD

**Issue by sailing178** [liupan1890/aliyunpan#266]
由于电脑配置的因素，一些4k修复的观看和剪辑很吃力。网页下载会卡在99.9不动，单线程也不行，真的恶心死我了

**Comment by liupan1890** [comment]
呃，我没明白你的需求。

1.使用小白羊下载4K视频，跟电脑性能无关吧？不会卡99.9的。你说网页下载卡99跟小白羊也没关系啊？

2.电脑配置低直接使用小白羊观看原始文件确实会卡，但是你可以在设置里选择观看转码视频啊，这样就不卡了（因为转码视频清晰度是1080，感觉即使电脑配置低，也不会卡到不能流畅看，最多看视频的时候不能操作其他的软件了）

3.剪辑 小白羊也没有剪辑功能啊？阿里云盘也不提供剪辑功能啊？

4.单线程也不行。。。。我更加不知道指的是什么了。。。。

**Comment by liupan1890** [comment]
仅标题 “希望提供转码视频下载方式”

这个功能吧，确实无法提供

因为官方转码后的视频是m3u8 .一堆很小的ts文件，需要下载所有的ts然后合并。这个有很多专门的m3u8下载软件可以实现。但是小白羊并不打算提供这个功能，因为需要的人很少（一般都是下载原始文件），

而合并m3u8分为2种方式，

1：直接复制文件合并，勉强能用，但并不推荐，不科学
2：通过ff转码合并，才正确，那么小白羊必须集成40多MB的ff转码程序

为了一个很少用到的功能，增加40MB的安装包体积，不划算的

**Comment by sailing178** [comment]
> 呃，我没明白你的需求。
> 
> 1.使用小白羊下载4K视频，跟电脑性能无关吧？不会卡99.9的。你说网页下载卡99跟小白羊也没关系啊？
> 
> 2.电脑配置低直接使用小白羊观看原始文件确实会卡，但是你可以在设置里选择观看转码视频啊，这样就不卡了（因为转码视频清晰度是1080，感觉即使电脑配置低，也不会卡到不能流畅看，最多看视频的时候不能操作其他的软件了）
> 
> 3.剪辑 小白羊也没有剪辑功能啊？阿里云盘也不提供剪辑功能啊？
> 
> 4.单线程也不行。。。。我更加不知道指的是什么了。。。。

1.我不是用小白羊下载4K视频，我说的是网页idm下载会卡在99.9。导入直链试过aria ui，m3u8 cli都直接失效
2.电脑配置能够观看4k视频，我不是为了观看而需要转码文件
3.剪辑指的是对于4K视频导入PR剪辑的编码导出困难
4.单线程指的是对于“下载卡99.9有可能是因为多线程下载造成这方面的考虑”
5.我发这个issue，主要是想问问实现转码下载是否容易。或者说是不是转码文件不能下载

**Comment by sailing178** [comment]
换了台电脑，idm下载成功。我自行排查问题，多谢回答
