### ISSUE TITLE
请教：MPV播放视频的窗口大小问题

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#267]
小白羊v2.9.19版有个问题：分辨率很低的视频，播放窗口却很大，看上去很粗糙；分辨率很高的视频，播放窗口却比分辨率小。

记得老版本是按视频的实际分辨率显示的，看上去很直观，特别是不同来源的同一部片子，清晰度谁优谁劣，720P还是1080P，从窗口大小一眼就比较出来了。

请问这个要怎么设置呢？

**Comment by hummersyk** [comment]
> 这个播放方式已经取消了
> 
> 因为按这种实际大小方式的话，4k视频会直接超出屏幕。
> 
> 查看视频大小的话，应该可以用MPV查看视频属性，具体我不太会，但是应该有这个功能，你可以百度一下

超出屏幕的情况就默认全屏，如果可以的话就完美了。

MPV可以按快捷键 i 查看视频文件属性，但还是没有窗口大小来的直观啊。

**Comment by liupan1890** [comment]
可以使用Potplayer啊，没有对potplayer设置屏幕大小参数，所以你替换成potplayer就可以了，会按照视频大小或者potplayer的设置去显示
