### ISSUE TITLE
上传解析中的列表如果退出是否算上传成功？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#268]
![image](https://user-images.githubusercontent.com/34271895/134258324-c1373703-30ae-41f5-b578-4f92d79be231.png)
如果此时在托盘右键退出并停止下载，那列表中的是是否算上传成功，还有列表中文件数量与关闭程序重新打开后有较大区别，是什么原因？如图所示如果退出重新进入程序后列表 列表会有200000左右，比现在的总数会少

**Comment by liupan1890** [comment]
跟你退出的时机有关系

解析中，具体会执行如下操作：
1.列出文件夹下面的所有文件和文件夹（顶层，非递归）
2.保存到上传中列表，保存到数据库中
3.从上传中删除这一个文件夹，保存到已上传
4.执行上传，当遇到一个文件夹时重复上面操作

此时你退出小白羊，结果不可预估。你不知道是执行到哪一步了。但每一步都是使用的数据库事务提交，所以理论上不会出现一个文件夹里面的10000文件，只保存了5000个这种情况，要不1万条都加入到上传中，要不1万条保存了5000条时退出直接丢弃已经保存的5000条

**Comment by liupan1890** [comment]
1.列表中是否算上传成功？
看是否执行完了第3步，执行完了第3步，则显示上传完成（只是这一条文件夹的记录上传完成，该文件夹里面的文件和子文件仍在上传列表中）

2.退出后列表文件少
应该是因为没有全部保存完，部分为保存的数据被整体抛弃了，此时点击全部开始，因为该文件夹仍然是未上传状态，会重新解析上传，不会导致文件漏掉上传

**Comment by liupan1890** [comment]
如果你不放心，可以通过上传完成后，在文件夹上右键，查看详情，列出了具体的文件数量，跟本地对比一下就知道是否完整了

**Comment by ybbluesky** [comment]
> 1.列表中是否算上传成功？
> 看是否执行完了第3步，执行完了第3步，则显示上传完成（只是这一条文件夹的记录上传完成，该文件夹里面的文件和子文件仍在上传列表中）
> 
> 2.退出后列表文件少
> 应该是因为没有全部保存完，部分为保存的数据被整体抛弃了，此时点击全部开始，因为该文件夹仍然是未上传状态，会重新解析上传，不会导致文件漏掉上传
> 
> 3.会因为重复的这样操作导致一个文件夹里的文件被创建出很多重复的上传任务吗？
> 不会，因为上传任务创建时指定了主键，（文件本地路径+文件大小+要上传到的文件夹ID+用户ID），因为主键，即使对同一个文件多次解析创建上传任务，最终也只会显示和保存一条上传记录

了解了，但是对比太难了

**Comment by ybbluesky** [comment]
> 如果你不放心，可以通过上传完成后，在文件夹上右键，查看详情，列出了具体的文件数量，跟本地对比一下就知道是否完整了

哈哈，等待你的同步盘出来就是了，手动对比就算了
