### ISSUE TITLE
大文件上传续传bug

### ISSUE THREAD

**Issue by LucasZhao22** [liupan1890/aliyunpan#269]
在上传大文件时（>50G），遇到网络波动中断或者手动暂停开始，进度都会回到百分之十几，而不是续传

**Comment by liupan1890** [comment]
如果不能续传，应该是进度全部清零才对

不过说到50GB，我没测试过---我硬盘没有这么大的剩余空间。稍后我想办法删点文件试试

在上传前会联网列一次，已上传的片序号，10MB一个序号，50GB可能需要5K个，可能阿里云盘无法返回这么多的序号
如果是有BUG，应该是跟这个有关，我测试看看吧

**Comment by liupan1890** [comment]
我已经找到问题了，是阿里云盘api返回的数据格式问题，应该是数字返回的字符串，导致我第二次请求时请求数据格式错误，下个版本会修正此问题，仅影响超过10GB的数据的续传，不影响正常的文件上传

**Comment by liupan1890** [comment]
已经在v2.9.24里修正了此问题
