### ISSUE TITLE
打开程序就白屏了

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#272]
程序正在上传文件，数量有点多，突然白屏后，现打开程序一会儿又自动白屏，有什么方法解决呀？

**Comment by ybbluesky** [comment]
![image](https://user-images.githubusercontent.com/34271895/134480339-bb36539f-5c9f-4a59-8075-5970fd98a7d3.png)
 这个文件太大了，是不是由于上传的文件太多造成程序死了？那个是已经上传好了的，可以删除？
![image](https://user-images.githubusercontent.com/34271895/134480494-beeac5a0-c4a9-4c92-b953-c49a0b85bf9a.png)
这个 表是不是可以清除？

**Comment by liupan1890** [comment]
1. 可以清除

2.当前electron白屏主要普遍是因为内存oom导致，删除已上传记录确实可以缓解

3.因为会缓存网盘内全部文件列表（1.统计文件夹体积 2.加快文件列表的显示，例如点击包含1万文件的文件夹，如果命中缓存会立即显示反之大概需要50多秒才能显示  3.为了后面提供的缩略图列表功能缓存缩略图url）。如果你的网盘里超过10万个文件，这个文件的体积就会比较大

**Comment by liupan1890** [comment]
你网盘里有多少个文件？我看截图1GB了？下个版本会在设置里增加选项，是否缓存文件列表

**Comment by ybbluesky** [comment]
> 你网盘里有多少个文件？我看截图1GB了？下个版本会在设置里增加选项，是否缓存文件列表

极限测试，盘内文件有10万+以上，你说到缓存网盘功能，不知道官方的客户端是怎样实现的，发现官方的显示网盘文件比你的快得多。

**Comment by liupan1890** [comment]
官方只显示100个文件，然后等你下拉到底部时，再加载100个，以此类推

小白羊也是一次加载100个，但会等到全部加载后，再一起显示出来


举例：你的一个文件夹里1万个文件

官方：打开文件夹，加载100，显示100，没事了，

小白羊：打开文件夹，循环100次（加载100），显示1万，没事了

#

如果你想要下载第3000-第4000个文件（下载中间的1000个文件）

官方：打开文件夹，显示100，你手动滚动到底部，加载100，你手动滚动到底部。。。。手动执行40次，此时已经显示了4000个文件了，手动滚动到3000（你自己猜，或者数），勾选3000-4000，点击下载按钮

小白羊：打开文件夹，等待显示1万，手动滚动到3000（鼠标移动到勾选按钮上会显示第N个），勾选3000-4000，点击下载按钮


是两种理念，所以表现不同，各有各的想法

**Comment by KHLFYY** [comment]
个人觉得 小白羊现在显示方式比官方的强太多了 

要不找中间文件的时候 官方的还得翻好几次

现在这种挺好的

**Comment by liupan1890** [comment]
嗯，已经在规划了，之后的版本会取消加载中的占位，这样，就跟官方表现差不多了，但是会自动加载剩余文件

1.展现快
2.自动加载文件全

都可以兼顾
