### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#274]
上传文件，在远端文件上传上去了，也能查询到了，但是本地还在上传列表中。不知道是不是上传文件列表太大了，上传一文件后写入上传文件列表没有完成

**Comment by ybbluesky** [comment]
> 上传文件，在远端文件上传上去了，也能查询到了，但是本地还在上传列表中。不知道是不是上传文件列表太大了，上传一文件后写入上传文件列表没有完成

建议上传文件列表只保存一定数量，采用循环方式，后面的覆盖前面的，如只保存5000条记录

**Comment by liupan1890** [comment]
不知道呢，因为我没能测试到这个问题

在少量数据（1万文件），我并没能发现这个问题

其实我对测试，测试的也比较少，因为我没时间测试，所以都是拿一些少量的数据简单的测试，

我也不知道你的具体操作步骤，有的问题，必须按照特定的操作步骤，才能复现

不管怎样，这个BUIG并不影响使用，即使还在上传列表中，也没关系，点击全部开始，让他重新上传就好了（并不会真的上传，会秒传 ）。
