### ISSUE TITLE
调用potplayer播放视频无法显示mkv内嵌字幕

### ISSUE THREAD

**Issue by wubaolatiao** [liupan1890/aliyunpan#275]
请问下这个问题有解决方法吗

**Comment by liupan1890** [comment]
呃，没有

必须明确，调用potplayer只是把下载url传给Potplayer  （MPV一样）

potplayer怎么播放。能否播放，能否硬解，能否识别字幕。都是potplayer的事

你提到无法显示内嵌字幕，我感觉是

1.你的这个mkv文件有问题
2.你没有正确的操作potplayer选择字幕
3.内嵌字幕本身有问题

potplayer是支持内嵌字幕的，mpv也支持内嵌字幕，哪有播放器不支持内嵌字幕的

**Comment by wubaolatiao** [comment]
找到问题了，是点了优先播放转码视频导致的，切换回播放原始文件就OK了

**Comment by liupan1890** [comment]
嗯，对的，因为转码视频，是阿里云盘转码的，不支持部分内嵌字幕，也不支持语言（音轨）的切换
