### ISSUE TITLE
请问可以在应用的某个配置文件里面找到refresh_token吗？

### ISSUE THREAD

**Issue by uibooker** [liupan1890/aliyunpan#276]
第三方的应用比如webdav，alist需要refresh_token才可以，但是移动网页端的登录接口短信验证完后response信息拿不到，这个地址：https://media.cooluc.com/decode_token/
所以如题，请问作者可以可以在某个文件中找到refresh_token吗？

**Comment by liupan1890** [comment]
登录官方网页版，F12,localStorage 里面有token

或者在F12显示的命令行里输入：
localStorage['token']

**Comment by uibooker** [comment]
> 登录官方网页版，F12,localStorage 里面有token
> 
> 或者在F12显示的命令行里输入：
> localStorage['token']


嗯，这种方法可以拿到token，但是第三方应用需要的是一开始登陆的token，网页版的token权限不足

**Comment by liupan1890** [comment]
什么权限不足呢？

我一直是使用的这个token，请问是哪些操作权限不足？具体表现是什么？

**Comment by ydx1013** [comment]
网页版的封了

**Comment by liupan1890** [comment]
重点是封了什么功能？

小白羊已经涉及到了官方的大部分功能，
大部分API都可以使用网页版token调用，
准确的说是我没发现哪个api是不能通过网页版token调用的

所以我才想问，到底是哪个操作不能通过网页版token调用？封的是哪个操作？

**Comment by chen-7-c** [comment]
他的意思是网页获取到的token（除了扫码）是不能进行下载操作的。他想拿到小白羊的token去应用其它第三方有关阿里云盘的项目。

**Comment by chen-7-c** [comment]
> 重点是封了什么功能？
> 
> 小白羊已经涉及到了官方的大部分功能，
> 大部分API都可以使用网页版token调用，
> 准确的说是我没发现哪个api是不能通过网页版token调用的
> 
> 所以我才想问，到底是哪个操作不能通过网页版token调用？封的是哪个操作？

他的意思是网页获取到的token（除了扫码）是不能进行下载操作的。他想拿到小白羊的token去应用其它第三方有关阿里云盘的项目。

**Comment by liupan1890** [comment]
看来是有我不知道的功能

1.使用网页token，获取的下载链接，是可以下载的，但是必须附加http头  参见 https://github.com/liupan1890/aliyunpan/issues/271

小白羊一直使用的就是这种下载链接下载文件

2.看来是说扫码token是可以获取另外一种下载链接？可以直接下载的不需要附加http头的链接？

我没试过，但是感觉不是这样的吧？要是能直接下载的链接，那么，不就疯了吗？那么多在线影视网站，不得乐疯了。。。。。那么多游戏下载网站/视频下载网站/图片下载网站，都得乐疯了。因为当前是因为有http头的限制，直接从别的网站点击不能下载，才能限制住盗链啊

**Comment by chen-7-c** [comment]
> 看来是有我不知道的功能
> 
> 1.使用网页token，获取的下载链接，是可以下载的，但是必须附加http头 参见 #271
> 
> 小白羊一直使用的就是这种下载链接下载文件
> 
> 2.看来是说扫码token是可以获取另外一种下载链接？可以直接下载的不需要附加http头的链接？
> 
> 是我孤陋寡闻了，原来是可以生成无需http头的直连的，试试能否加在小白羊上

不好意思，可能我表达确实有问题..  就是手机获取到的token在网页里是可以下载的，但是网页端的token在网页端是不能下载的，点击下载链接会显示如上图那种情况。但是用手机获取到的token的链接，直接复制到idm也一样是不可以下载的，要加上http头。  我感觉还是同一种下载链接...

**Comment by liupan1890** [comment]
嗯，我以前是不知道还有这个区别，刚才看了源码了，接口是同一个，就是token不一样

当提供不同的token时

网页的返回的下载地址里包含了http头验证

app的token返回的下载地址不包含http头验证，所以可以直接下载

**Comment by uibooker** [comment]
> 嗯，我以前是不知道还有这个区别，刚才看了源码了，接口是同一个，就是token不一样
> 
> 当提供不同的token时
> 
> 网页的返回的下载地址里包含了http头验证
> 
> app的token返回的下载地址不包含http头验证，所以可以直接下载

那问一下大佬，可以在某个文件中找到refresh_token吗？

**Comment by liupan1890** [comment]
不能

按照他们讨论的https://github.com/Xhofe/alist/issues/88是说再登录过程中截取出特定的token，登录后的token不行

小白羊里都是登陆后的token，并没有在登录过程中截取，我也没试过。所以找不到

**Comment by uibooker** [comment]
> 不能
> 
> 按照他们讨论的[https://github.com/Xhofe/alist/issues/88是说再登录过程中截取出特定的token，登录后的token不行](https://github.com/Xhofe/alist/issues/88%E6%98%AF%E8%AF%B4%E5%86%8D%E7%99%BB%E5%BD%95%E8%BF%87%E7%A8%8B%E4%B8%AD%E6%88%AA%E5%8F%96%E5%87%BA%E7%89%B9%E5%AE%9A%E7%9A%84token%EF%BC%8C%E7%99%BB%E5%BD%95%E5%90%8E%E7%9A%84token%E4%B8%8D%E8%A1%8C)
> 
> 小白羊里都是登陆后的token，并没有在登录过程中截取，我也没试过。所以找不到

感谢大佬的解答，看过这个issue了，最后移动端登陆页面一直不成功，想到小白羊可以做好多事情，是不是小白羊的token权限更多一些，才发起issue问了下大佬能不能从小白羊里面找到token

**Comment by chen-7-c** [comment]
> > 不能
> > 按照他们讨论的[https://github.com/Xhofe/alist/issues/88是说再登录过程中截取出特定的token，登录后的token不行](https://github.com/Xhofe/alist/issues/88%E6%98%AF%E8%AF%B4%E5%86%8D%E7%99%BB%E5%BD%95%E8%BF%87%E7%A8%8B%E4%B8%AD%E6%88%AA%E5%8F%96%E5%87%BA%E7%89%B9%E5%AE%9A%E7%9A%84token%EF%BC%8C%E7%99%BB%E5%BD%95%E5%90%8E%E7%9A%84token%E4%B8%8D%E8%A1%8C)
> > 小白羊里都是登陆后的token，并没有在登录过程中截取，我也没试过。所以找不到
> 
> 感谢大佬的解答，看过这个issue了，最后移动端登陆页面一直不成功，想到小白羊可以做好多事情，是不是小白羊的token权限更多一些，才发起issue问了下大佬能不能从小白羊里面找到token

alist的群文件有网页获取token的软件（其实就是一个抓包），你可以试试。

**Comment by uibooker** [comment]
> > > 不能
> > > 按照他们讨论的[https://github.com/Xhofe/alist/issues/88是说再登录过程中截取出特定的token，登录后的token不行](https://github.com/Xhofe/alist/issues/88%E6%98%AF%E8%AF%B4%E5%86%8D%E7%99%BB%E5%BD%95%E8%BF%87%E7%A8%8B%E4%B8%AD%E6%88%AA%E5%8F%96%E5%87%BA%E7%89%B9%E5%AE%9A%E7%9A%84token%EF%BC%8C%E7%99%BB%E5%BD%95%E5%90%8E%E7%9A%84token%E4%B8%8D%E8%A1%8C)
> > > 小白羊里都是登陆后的token，并没有在登录过程中截取，我也没试过。所以找不到
> > 
> > 
> > 感谢大佬的解答，看过这个issue了，最后移动端登陆页面一直不成功，想到小白羊可以做好多事情，是不是小白羊的token权限更多一些，才发起issue问了下大佬能不能从小白羊里面找到token
> 
> alist的群文件有网页获取token的软件（其实就是一个抓包），你可以试试。

web.exe那个文件吗？还没试过，这次是从安卓手机上获取的。。。alist恢复使用了，谢谢提醒~

**Comment by pongfcnkl** [comment]
这类白嫖阿里带宽的目录文件列表程序好像用的手机上的refresh_token吧
