### ISSUE TITLE
分享转存有的没有成功，是不是官方有限制？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#277]
分享转存大量文件，有一些没有转存成功，是官方限制还是程序的BUG?

**Comment by liupan1890** [comment]
把连接告诉我去测试一下

**Comment by ybbluesky** [comment]
> 把连接告诉我去测试一下

https://www.aliyundrive.com/s/bwDLGoPfWYV

**Comment by liupan1890** [comment]
我测试了，是正常的，可以正确的全部导入12万多个文件

1.阿里云盘的分享，是异步导入的。当你点击了保存按钮，就等着吧

2.我测试是从7点19开始，一直到8点45，才终于全部导入成功

如果你遇到没有全部导入

1.可能是你太着急了，等几个小时再看，因为你的分享链接文件太多了

2.可能你网盘剩余空间不足，请查看阿里云盘官网帮助中心，空间不足时，剩余文件无法导入

**Comment by ybbluesky** [comment]
> 我测试了，是正常的，可以正确的全部导入12万多个文件
> 
> 1.阿里云盘的分享，是异步导入的。当你点击了保存按钮，就等着吧
> 
> 2.我测试是从7点19开始，一直到8点45，才终于全部导入成功
> 
> 如果你遇到没有全部导入
> 
> 1.可能是你太着急了，等几个小时再看，因为你的分享链接文件太多了
> 
> 2.可能你网盘剩余空间不足，请查看阿里云盘官网帮助中心，空间不足时，剩余文件无法导入

谢谢
