### ISSUE TITLE
又白屏了，是不是网盘内文件太多

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#279]
不知道是不是sqlite的结构对行有没有限制，现网盘内文件太多，很容易出现白屏，昨天下载文件时出现白屏就是由于下载列表可能文件太多造成的，手动清空下载文件列表后程序正常。现又出现打开文件夹时出现白屏，所以猜测会不会是文件数量太多列表太多而造成程序跨了？

**Comment by liupan1890** [comment]
是的，文件太多，导致浏览器因为内存不足而崩溃。我的网盘里只有14万个文件，其中最大的文件夹也只有3万个文件，所以没有遇到过白屏问题。在我电脑上小白羊内存占用大概为200MB上下（180-300），看一下你的电脑上小白羊进程的内存有多少告诉我，以及你最大的文件夹里包含多少个文件（不包括子文件夹，仅文件夹本身一级）

**Comment by ybbluesky** [comment]
> 是的，文件太多，导致浏览器因为内存不足而崩溃。我的网盘里只有14万个文件，其中最大的文件夹也只有3万个文件，所以没有遇到过白屏问题。在我电脑上小白羊内存占用大概为200MB上下（180-300），看一下你的电脑上小白羊进程的内存有多少告诉我，以及你最大的文件夹里包含多少个文件（不包括子文件夹，仅文件夹本身一级）

内存在小白羊在有大量文件上传时经常占用99%的cpu
内存占用500M左右，最大的文件数量不超过50个
但是file__0内文件有时会有1g

**Comment by ybbluesky** [comment]
![image](https://user-images.githubusercontent.com/34271895/134659418-cefc42a9-d892-4cb1-933e-b212d3391ee2.png)

**Comment by liupan1890** [comment]
你截图里，小白羊明明只占用了30%啊，没有99%啊。。。。

大量上传/下载时（尤其是小文件），因为会频繁的刷新界面，本来就是会导致CPU较高，解决方法是，切换到文件列表页面，不要呆在上传中页面，CPU占用会降低一半

那个1G的文件你可以手动删除掉，只会导致上传中和已上传和下载中和已下载队列数据被清空，对其他没有影响

**Comment by liupan1890** [comment]
另外，根据阿里云盘的API本身，上传文件需要计算文件的sha1,这个计算本身就是高CPU的，所以，这个是绝对没有任何解决办法的，除非彻底取消秒传功能，所有文件都强制走流量完整的上传，否则上传CPU无法降低。

你试试官方网页版，你试试官方PC，你就会发现，小白羊上传时的CPU是相对非常低的

注：比如上传一个1GB的文件，可能小白羊和官方客户端的CPU占用都是30%，但小白羊只需要几秒，官方客户端需要1.4*几秒
所以按时间平均一下，还是小白羊的占用低

**Comment by liupan1890** [comment]
在新的版本里已经增加了文件缓存的开关--自动统计文件体积

之后的版本会对文件夹特别多的这种情况进行一下优化

另外因为websql技术本身的问题，你的那个1GB的文件，提及不会变小（不支持自动收缩），所以当你下载完&&上传完全部文件后，最好自己手动删除掉这个文件，之后的版本，也会增加删除缓存文件数据库的功能

**Comment by ybbluesky** [comment]
> 在新的版本里已经增加了文件缓存的开关--自动统计文件体积
> 
> 之后的版本会对文件夹特别多的这种情况进行一下优化
> 
> 另外因为websql技术本身的问题，你的那个1GB的文件，提及不会变小（不支持自动收缩），所以当你下载完&&上传完全部文件后，最好自己手动删除掉这个文件，之后的版本，也会增加删除缓存文件数据库的功能

马上试一下新版本，谢谢
