### ISSUE TITLE
如何调用potplayer播放器

### ISSUE THREAD

**Issue by sdxjcb** [liupan1890/aliyunpan#282]
如何调用potplayer播放器，请告知一下设置步骤，谢谢！

**Comment by sdxjcb** [comment]
是已经自动调用了吗

**Comment by KHLFYY** [comment]
> 是已经自动调用了吗

看仓库里的 `使用potplayer.md`


https://github.com/liupan1890/aliyunpan/blob/main/%E4%BD%BF%E7%94%A8PotPlayer.md

**Comment by sdxjcb** [comment]
感谢大神，已解决

**Comment by liupan1890** [comment]
在v2.10.17开始，改成在设置里选择你电脑上的potplayer的安装位置了

比如选择C:\Potplayer\potplayer.exe
或者选择桌面上potplayer的桌面快捷方式图标即可。不需要像之前那样复制Potplayer整个文件夹到小白羊里面了
