### ISSUE TITLE
2.9.24版本还是没有开放搜索功能吗

### ISSUE THREAD

**Issue by sdxjcb** [liupan1890/aliyunpan#283]
2.9.24版本还是没有开放搜索功能吗？

**Comment by hongtucao8384** [comment]
开发速度比官方快很多了，作者也要养家糊口，耐心等 。

**Comment by hongtucao8384** [comment]
> 2.9.24版本还是没有开放搜索功能吗？

开发速度比官方快很多了，作者也要养家糊口，耐心等 。

**Comment by liupan1890** [comment]
没有，整个9月，基本上都是在处理秒传和性能问题

#### 第一个是秒传问题
下大力气，优化了秒传功能，支持TB级，数万文件级的秒传，
1，可以快速地导入
2，可以快速地显示全部文件
3，可以自由勾选文件导入

原来遇到几万个文件的，就会比较卡，也不能自由勾选，只导入勾选的文件
优化后一点也不卡了，也能自由勾选了

然后，就没有然后了，阿里云盘调整了

#### 第二个问题是性能问题

一般人不会遇到性能问题，但总有这么少数人，

1.一次性上传20万个文件
2.一次性下载几十万个文件/文件夹
3.网盘里一个文件夹里面直接包含几万个文件
4.一个分享链接里包含数万个文件

也就是小白羊了，官方客户端限制单次下载（点击一下下载按钮），也只能下载数千个文件--官方帮助里有，具体忘了

又要上传快，又要数量多。

优化前，一次 上传/下载 20万 文件会卡住2-3分钟（在保存上传列表），优化后一秒也不卡了
优化前，直接显示数万个文件的列表，有时会卡（勾选一个文件耗时300毫秒），优化后不会卡了，同样的几万个文件的列表勾选一个文件耗时20毫秒

总之，扣了又扣，改了又改。功能上反而一个月都没啥进度，我确实也没办法，一个人，又非全职，加上人到中年后生活中一堆事，体谅一下吧

**Comment by sdxjcb** [comment]
感谢大侠，做的已经够好了

**Comment by KHLFYY** [comment]
作者加油 

大家都支持您

开发慢慢来 理解作者

**Comment by ybbluesky** [comment]
> 没有，整个9月，基本上都是在处理秒传和性能问题
> 
> #### 第一个是秒传问题
> 下大力气，优化了秒传功能，支持TB级，数万文件级的秒传，
> 1，可以快速地导入
> 2，可以快速地显示全部文件
> 3，可以自由勾选文件导入
> 
> 原来遇到几万个文件的，就会比较卡，也不能自由勾选，只导入勾选的文件
> 优化后一点也不卡了，也能自由勾选了
> 
> 然后，就没有然后了，阿里云盘调整了
> 
> #### 第二个问题是性能问题
> 一般人不会遇到性能问题，但总有这么少数人，
> 
> 1.一次性上传20万个文件
> 2.一次性下载几十万个文件/文件夹
> 3.网盘里一个文件夹里面直接包含几万个文件
> 4.一个分享链接里包含数万个文件
> 
> 也就是小白羊了，官方客户端限制单次下载（点击一下下载按钮），也只能下载数千个文件--官方帮助里有，具体忘了
> 
> 又要上传快，又要数量多。
> 
> 优化前，一次 上传/下载 20万 文件会卡住2-3分钟（在保存上传列表），优化后一秒也不卡了
> 优化前，直接显示数万个文件的列表，有时会卡（勾选一个文件耗时300毫秒），优化后不会卡了，同样的几万个文件的列表勾选一个文件耗时20毫秒
> 
> 总之，扣了又扣，改了又改。功能上反而一个月都没啥进度，我确实也没办法，一个人，又非全职，加上人到中年后生活中一堆事，体谅一下吧

认领第二条

**Comment by liupan1890** [comment]
在v2.11.14里已经支持搜索文件了
