### ISSUE TITLE
v2.9.24上传速度偏低

### ISSUE THREAD

**Issue by kedyao** [liupan1890/aliyunpan#286]
目前我已知阿里云单任务单文件上传限速10M/s  所以我一直都是单任务单文件上传
今天更换为了v2.9.24 使用 之前用的旧版本 v1.6.29 
上传文件测试 发现上传速度不稳定偏低
下面使用的是同文件 网络为商宽200M对等宽带 
![宽带](https://user-images.githubusercontent.com/47054558/134763814-77ec7f81-794b-441e-a1c3-04f8b67d8510.png)

单任务新版本 网速在2-5M/s中浮动 在流量统计软件中 显示最高为6M/s
![单任务新版本](https://user-images.githubusercontent.com/47054558/134763673-2b5a816f-2c93-44a3-b87c-0c69ae8f7a1e.png)

旧版本  网速在9-10M/s中浮动  在流量统计软件中 显示最高为12M/s
![单任务旧版本](https://user-images.githubusercontent.com/47054558/134763758-62ed1983-cbf5-491d-a7d4-378e43c526bf.png)

**Comment by liupan1890** [comment]
这个还真不好解释

v1.6.x上传是通过golang执行的，
v2.x上传是通过js执行的（就是浏览器的上传）

因为我的网络上传速度最快也就4MB/s所以我还真的一直没有发现有这个问题

我记下了，以后会针对这个研究一下，看问题出在哪

**Comment by liupan1890** [comment]
当前，v2使用时，可以先通过多任务同时上传，应该还可以快一点

**Comment by aglent** [comment]
家宽粗略测试了 上传速度新版平均4MB/s 旧版平均6MB/s

**Comment by jkqxl** [comment]
上传是阿里限速了，跟软件没有关系，用阿里网页版测试下就知道了

**Comment by liupan1890** [comment]
在v2.11.28里优化了一下上传方式（以前是走xmlhttprequest，以后是走node）可能会提升一点上传速度

但，只要开启多个文件同时上传，就很容易满速上传了
