### ISSUE TITLE
2.9.24文件无法上传

### ISSUE THREAD

**Issue by LucasChen824** [liupan1890/aliyunpan#289]
大神，为啥用最新版上传文件一直显示排队中，无法进行实际上传，用1.6那个版本没问题，之前2.8.30版本还好好的
![1M176WH_TW38}%9A5A(RMU6](https://user-images.githubusercontent.com/91370885/134805808-788b2152-2697-4797-a741-de1c5256dbd2.png)

**Comment by liupan1890** [comment]
退出后重新打开试试

不知道啊，我这里刚刚试了一下，可以上传，所以可能是隐藏性的BUG

或者你就退回2.8.30先用着


我稍后再多测试测试，看我能否遇到这个BUG
最好说一下你是怎么操作的，直接拖几个文件上传就遇到这样了？还是已经上传了一部分文件后突然这样了？

**Comment by LucasChen824** [comment]
老哥,我把2.9.24卸了重新下2.8.30版本还是不行，现在点进传输里面上传中上传的文件都显示不出来。上传的方式就是小白羊里点上传选择文件这样上传的

**Comment by liupan1890** [comment]
本来就不行啊，v2.9.X的发布公告里写的很明白啊，v2.9.X更新了数据库，和旧版不兼容，用了新版，再切回旧版就看不到以前的上传记录了，只能重新选择文件上传
