### ISSUE TITLE
不能拖拽上传文件，望采纳

### ISSUE THREAD

**Issue by shenghan314** [liupan1890/aliyunpan#29]

**Comment by wenhairu** [comment]
这个其实无所谓，能上传就好😄

**Comment by liupan1890** [comment]
界面是采用flutter开发的，当前flutter还不支持文件拖拽操作--反正我是没找到它支持的地方

所以无法实现文件拖拽上传功能

**Comment by liupan1890** [comment]
一个好消息，我找到了支持window拖拽的flutter插件，下个版本应该会支持windows平台上的文件/文件夹拖拽上传

**Comment by nayaaaaa** [comment]
最新版的官方桌面版支持拖拽了

**Comment by liupan1890** [comment]
> 最新版的官方桌面版支持拖拽了

真的？我去看看。有网址不？

**Comment by liupan1890** [comment]
@nayaaaaa 告诉我网址啊啊啊啊啊啊啊啊啊啊，我找不到啊

**Comment by nayaaaaa** [comment]
> @nayaaaaa 告诉我网址啊啊啊啊啊啊啊啊啊啊，我找不到啊 

https://www.aliyundrive.com/
就是官网

**Comment by liupan1890** [comment]
怪我，我理解错了。。。我理解为Flutter最新版支持拖拽了。。。。。阿里云盘官方确实支持拖拽，win和mac都支持，electron就是好用。。。。
