### ISSUE TITLE
远程Aria2 Secret密码连接错误。

### ISSUE THREAD

**Issue by Azreulo** [liupan1890/aliyunpan#290]
如题，我一直使用Aria2作为主力下载，平时把Aria2安装成一个服务运行。

地址，密码肯定都没有问题的，AriaNg连接正常，但是在此软件的Aria设置中，总是提示连接失败，密码错误~

**Comment by liupan1890** [comment]
第一点：只支持http，不支持https。如果你aria是https，就不行

第二点：看你的aria密码怎么设置的
如果是在aria2c.conf里设置的，还好一点，如果你是在启动的命令行里设置的密码
``````
aria2c --rpc-secret=xxxxxx
``````
注意这里的密码里不能包含有特殊字符比如'^' 因为命令行里面，有一部分特殊字符会被转义，比如你的密码是'a^b' 在配置文件里没事，可以正确链接，在命令行里就不行，^是windows里的转义字符

**Comment by Azreulo** [comment]
Sorry，解决~
原因是我打开了另外一个软件，它也自带了一个Aria2，把我的服务顶了~

Thanks。

**Comment by liupan1890** [comment]
收到
