### ISSUE TITLE
是否考虑加入代理支持

### ISSUE THREAD

**Issue by Duan-rax** [liupan1890/aliyunpan#293]
迫于网络原因，在家一直开着全局代理，发现软件并不能走，网络不通或走直连

**Comment by Duan-rax** [comment]
已经成功，感谢

**Comment by Sanzo00** [comment]
请问mac端如何手动指定代理？

https://github.com/liupan1890/aliyunpan/issues/376#issuecomment-981738375

**Comment by liupan1890** [comment]
经确认，没有自动识别出系统的代理，是BUG
已经在最新的版本里修正了此BUG
并且还增加了备用的，强制的指定方式
请等v2.12.05发布后更新新版就好了
