### ISSUE TITLE
求下载功能

### ISSUE THREAD

**Issue by lanzhous** [liupan1890/aliyunpan#294]
视频有 优先转码播放的功能。提供选项：下载是否能加个 优先下载转码功能

**Comment by liupan1890** [comment]
暂未打算增加此功能

因为官方转码后的视频是m3u8 .一堆很小的ts文件，需要下载所有的ts然后合并。这个有很多专门的m3u8下载软件可以实现。但是小白羊并不打算提供这个功能，因为需要的人很少（一般都是下载原始文件），

而合并m3u8分为2种方式，

1：直接复制文件合并，勉强能用，但并不推荐，不科学
2：通过ff转码合并，才正确，那么小白羊必须集成40多MB的ff转码程序

为了一个很少用到的功能，增加40MB的安装包体积，不划算的

**Comment by lanzhous** [comment]
ffmpeg 外挂支持就行啦~ 阿里的转码技术可以的，mkv转码效率算不错的，加上支持全码率其实还挺不错的。如果过于繁琐的话就算了~ 至于会增加体积确实是不划算，能自己外挂ff的话有这个功能还是挺不错的。

**Comment by liupan1890** [comment]
是这样

如果支持此功能，那就需要在安装包里直接配置好ff，直接能用。（win/mac/linux 都要有），就好比MPV播放器是直接配置好的

因为不想附带ff，所以才不支持此功能

写一个教程让用户去自己配置ff，是不现实的。因为有3个系统了，我写不明白。
