### ISSUE TITLE
2.9.24 登陆失败

### ISSUE THREAD

**Issue by TUO-V** [liupan1890/aliyunpan#295]
以前都可以正常登录的，这次不知怎么回事登陆失败，两张截图是失败时的界面
第二张图提示要退出后重新登陆，请问在哪里退出呢？是否可以直接删除C:\Users\用户名\AppData\Roaming\alipay这个文件夹？
不知道这是不是会与我在国外链接阿里服务器不怎么顺畅有关，我苹果手机上打开阿里云盘时经常要求重新登陆或清理缓存（这个锅阿里背）
此问题出现在Win10上，我在Mac上使用时没出现问题
![2021-09-28_222629](https://user-images.githubusercontent.com/85728145/135193092-89f0c7e2-b4d5-47e4-a437-9d517940c37c.png)
![2021-09-28_222846](https://user-images.githubusercontent.com/85728145/135193095-882886cc-565c-4fb5-8541-d29a361c16a4.png)

**Comment by liupan1890** [comment]
1。怎么退出

点击顶部的头像，退出


2.为什么需要刷新token？
token正常情况下7200秒有效，小白羊运行中，会自动定时刷新

但，假如你在其他地方登录（概率），或者修改登录密码（必然），都会使原来的token失效，需要重新登录


3.是否可以直接删除C:\Users\用户名\AppData\Roaming\alipay这个文件夹？
可以

**Comment by TUO-V** [comment]
谢谢大佬，问题已解决
