### ISSUE TITLE
同一批文件，统计体积大小不一样

### ISSUE THREAD

**Issue by hongtucao8384** [liupan1890/aliyunpan#297]
同一批文件，统计的体积不一样
是因为统计比较耗资源，在后台慢慢统计吗？
![1632922673(1)](https://user-images.githubusercontent.com/55793584/135280116-07ab12b4-0f1a-415d-93da-e03cb7266862.png)

**Comment by liupan1890** [comment]
是的

根文件夹数量有关，是在后台，

1.每10分钟触发一次
2.每次对需要统计的文件夹列表，每300毫秒（大概吧，忘了是不是改成200了），触发统计一个文件夹

3.已经统计过的文件夹，72小时（不同的版本细节不一样，记得v2.9.24是72小时）内不会重复统计/重新统计

所以，如果你在文件夹里新上传了文件/新导入了分享，这个体积并不是准确的体积，会有较大误差


#

为什么这样做？因为我的网盘里有3000个文件夹，部分用户可能会有几万个文件夹。如果统计的比较频繁，比较浪费资源。

#
怎么立即强制刷新？在文件夹上右键，详情，刷新缓存。就可以立即同步的重新统计这个文件夹以及这个文件夹的所有子文件夹（递归），等加载的图标消失，就全部统计完了准确的大小了（3000个文件夹大概需要5-7分钟）
