### ISSUE TITLE
期待(批量)清理同名文件(夹)

### ISSUE THREAD

**Issue by dkdengkai** [liupan1890/aliyunpan#298]

**Comment by ybbluesky** [comment]
一看就是资料收集者

**Comment by liupan1890** [comment]
以后会有扫描重复文件的功能（sha1完全一致，不关心文件名是否一致，不关心文件路径）

1. 不会有清理同名文件夹的功能
因为这个容易导致误操作


2. 不会有清理同名文件的功能
因为这个容易导致误操作

**Comment by liupan1890** [comment]
希望能回复一下，什么样的情景，需要用到清理重名文件夹？重名文件？
