### ISSUE TITLE
阿里云盘本身不支持离线，这个离线是什么原理

### ISSUE THREAD

**Issue by cirnosaiko** [liupan1890/aliyunpan#3]
会导致被人肉吗

**Comment by liupan1890** [comment]
技术原理：
你提交磁力链接，客户端提交给aria下载，然后上传到阿里云盘+创建秒传链接，回复给你的客户端，客户端使用秒传链接保存文件

方式一：我自建一台Aria服务器（会注意屏蔽非法内容链接），大家作为测试使用，排队调用离线
方式二：根据教程你自搭建Aria服务器，随意离线

>会导致被人肉吗

人肉的意思是找我？不是太理解


实际上，在后期，会累积到一定量的数据（磁力链接-->秒传链接），直接进行磁力链接的转换，会减少对Aria的依赖，届时也许你就不需要自己搭建Aria服务器了

**Comment by WHYEX3** [comment]
要是知道bt种子里的每一个文件的sha1就好了，更改相应的字节大小和名称就可以拼出一个秒传链接了（可惜种子文件里不包含单个文件的sha1）另外阿里云盘的资源还挺多的，我计算了几年前下载的死种里的文件的sha1而拼凑出的秒传链接居然真的秒传了，不知道是不是115数据迁移的缘故

**Comment by cirnosaiko** [comment]
> 技术原理：
> 你提交磁力链接，客户端提交给aria下载，然后上传到阿里云盘+创建秒传链接，回复给你的客户端，客户端使用秒传链接保存文件
> 
> 方式一：我自建一台Aria服务器（会注意屏蔽非法内容链接），大家作为测试使用，排队调用离线
> 方式二：根据教程你自搭建Aria服务器，随意离线
> 
> > 会导致被人肉吗
> 
> 人肉的意思是找我？不是太理解
> 
> 实际上，在后期，会累积到一定量的数据（磁力链接-->秒传链接），直接进行磁力链接的转换，会减少对Aria的依赖，届时也许你就不需要自己搭建Aria服务器了

什么时候能上线呢，感觉离线功能会侵犯大厂的权利

**Comment by Andrew201801** [comment]
> 会导致被人肉吗
你快来看看这个
https://bbs.tampermonkey.net.cn/thread-427-1-1.html

**Comment by zsbai** [comment]
> 技术原理：
> 
> 你提交磁力链接，客户端提交给aria下载，然后上传到阿里云盘+创建秒传链接，回复给你的客户端，客户端使用秒传链接保存文件
> 
> 
> 
> 方式一：我自建一台Aria服务器（会注意屏蔽非法内容链接），大家作为测试使用，排队调用离线
> 
> 方式二：根据教程你自搭建Aria服务器，随意离线
> 
> 
> 
> >会导致被人肉吗
> 
> 
> 
> 人肉的意思是找我？不是太理解
> 
> 
> 
> 
> 
> 实际上，在后期，会累积到一定量的数据（磁力链接-->秒传链接），直接进行磁力链接的转换，会减少对Aria的依赖，届时也许你就不需要自己搭建Aria服务器了
> 
> 

我搭建了一台aria服务器，下载后却不知道怎么从服务器把文件上传到阿里云盘....可以请教下么？

**Comment by Andrew201801** [comment]
> > 技术原理：
> > 你提交磁力链接，客户端提交给aria下载，然后上传到阿里云盘+创建秒传链接，回复给你的客户端，客户端使用秒传链接保存文件
> > 方式一：我自建一台Aria服务器（会注意屏蔽非法内容链接），大家作为测试使用，排队调用离线
> > 方式二：根据教程你自搭建Aria服务器，随意离线
> > > 会导致被人肉吗
> > 
> > 
> > 人肉的意思是找我？不是太理解
> > 实际上，在后期，会累积到一定量的数据（磁力链接-->秒传链接），直接进行磁力链接的转换，会减少对Aria的依赖，届时也许你就不需要自己搭建Aria服务器了
> 
> 我搭建了一台aria服务器，下载后却不知道怎么从服务器把文件上传到阿里云盘....可以请教下么？

1、手动一个个用阿里云盘网页版把文件上传上去（手动狗头）
2、使用软件抓包，获取阿里云前后端交互的API，模拟登陆后使用API将文件上传

**Comment by WHYEX3** [comment]
我选第一个

**Comment by zsbai** [comment]
> > > 技术原理：
> > > 你提交磁力链接，客户端提交给aria下载，然后上传到阿里云盘+创建秒传链接，回复给你的客户端，客户端使用秒传链接保存文件
> > > 方式一：我自建一台Aria服务器（会注意屏蔽非法内容链接），大家作为测试使用，排队调用离线
> > > 方式二：根据教程你自搭建Aria服务器，随意离线
> > > > 会导致被人肉吗
> > > 
> > > 
> > > 人肉的意思是找我？不是太理解
> > > 实际上，在后期，会累积到一定量的数据（磁力链接-->秒传链接），直接进行磁力链接的转换，会减少对Aria的依赖，届时也许你就不需要自己搭建Aria服务器了
> > 
> > 
> > 我搭建了一台aria服务器，下载后却不知道怎么从服务器把文件上传到阿里云盘....可以请教下么？
> 
> 1、手动一个个用阿里云盘网页版把文件上传上去（手动狗头）
> 2、使用软件抓包，获取阿里云前后端交互的API，模拟登陆后使用API将文件上传

现在GitHub有一个python的上传项目，我现在用服务器离线，然后用python传上去，稍微有点麻烦，不过也还好

**Comment by fengshgx** [comment]
是类似oneindex配合aria以及onedrive那样吗，网盘换成了阿里云并且有秒传

**Comment by jiujiwuan** [comment]
文件怎么没有了？
