### ISSUE TITLE
右侧滑动条显示问题

### ISSUE THREAD

**Issue by linqiu919** [liupan1890/aliyunpan#300]
右侧的滑动条是否可以设计成默认不显示，有滑动操作时才显示？目前版本右侧的这个滑动条整体看着有点不协调。

**Comment by liupan1890** [comment]
明白你的意思了，但是并不能这样设计的

因为如果不一直显示着，部分用户，会认为不能滚动，找不到滚动条，或者认为只有那几条，看不到下面的记录

并不是所有人都知道鼠标移动上去会显示滚动条

**Comment by linqiu919** [comment]
理解了，看了一下百度网盘的，也是这样的设计，可能我被网页设计的思维影响了。
