### ISSUE TITLE
大约什么时候更新呀？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#303]
机器太差白屏，不知什么时候能更哟

**Comment by liupan1890** [comment]
参阅 https://github.com/liupan1890/aliyunpan/issues/251

初定 10.10

下个版本调整的比较大，所以初定

针对白屏问题作了很深入的调整，也确实分析出一个BUG，并彻底解决数据库文件过大的问题（应该维持在100MB以内）

**Comment by ybbluesky** [comment]
期待了，等
