### ISSUE TITLE
请问小白羊如何调用路由器的aria2下载呢

### ISSUE THREAD

**Issue by leechuy** [liupan1890/aliyunpan#304]
请问小白羊如何调用路由器的aria2下载呢

**Comment by liupan1890** [comment]
小白羊，设置，aria2 ,开启远程模式

路由器的配置/设置 需要自行摸索

**Comment by leechuy** [comment]
我一直用的v1.6.29 怪不得没看到

**Comment by leechuy** [comment]
请问远程下载地址是如何填写呢
我尝试了\\OPENWRT\Aria2\Aria2\Downloads和192.168.254.1\OPENWRT\Aria2\Aria2\Downloads呢
下载文件都显示aria2c创建文件夹失败

**Comment by leechuy** [comment]
请问远程aria2模式电脑关机后还会下载吗
今天开机看了传输列表全都报错了

**Comment by liupan1890** [comment]
比如你要下载100个文件

设置为同时下载5个文件

当前正在下载第1-5个文件

此时关机，
第1-5个文件仍然会下载，下次开机时，可能显示未下载完/进度/速度，都不要当真，点击重新开始，会立即显示已完成（既远程主机上/路由器上，已经成功下载完了）

第5-100个文件 ，不会下载

必须开着小白羊，才会正确的按照顺序，一个一个的下载第1-100个文件


为什么？不能直接把100个文件发给远程助记吗？

因为

1.阿里云盘的下载链接最多4小时内有效
比如你下载1万个文件，一次性把1万个文件发给远程主机，第1-1000个文件需要4个小时才能下载完，下载第1001个（以及以后的）文件时因为超时，所以报错

所以，必须是开始下载哪一个文件，当时才把这个文件的下载任务发给远程主机。所以必须一直开着小白羊


2.aira2的下载队列数量有限制

aria2本身对下载队列有最大数量的限制，小白羊内置的本地aria是设置为最多保存1000条，不知道你的远程主机上是怎么设置的，所以，如果你的设置数很低+一次下载1万个文件，就会导致aria出错，丢失


总之：必须开着小白羊，跟本地下载文件一样

**Comment by cikiChe** [comment]
难受，香菇。我还想着，挂着这个，然后下载呢
