### ISSUE TITLE
mac能否调用第三方播放软件吗？

### ISSUE THREAD

**Issue by sunnyadams** [liupan1890/aliyunpan#305]

**Comment by liupan1890** [comment]
暂时还不能

因为当前获取的播放地址，需要附加阿里云盘的http头才能访问。我不用mac，我只知道mac下mpv播放器支持附加

别的播放器我不知道

1.等以后想办法获取没有限制的播放地址

2.等以后发现其他支持设置http头的播放器

3.等以后小白羊假设本地代理绕过http头限制

当前，不行

**Comment by liupan1890** [comment]
在v2.10.31 windows系统，已经支持调用其它播放器
