### ISSUE TITLE
转码播放颜色灰暗，多线程IDM更快

### ISSUE THREAD

**Issue by rawchen** [liupan1890/aliyunpan#306]
4k转码1080P播放颜色灰暗
100Mbps带宽多线程速度3-5M/s，IDM更快，9-10M/s

**Comment by liupan1890** [comment]
1.转码灰暗

这个跟小白羊没有关系，是阿里云盘的转码，需要去阿里云盘帮助在线反馈


2.100Mbps带宽多线程速度3-5M/s

是说的你使用小白羊下载只有3-5MB/s的速度吗？我自己是300M宽带，小白羊下载可以跑满40MB/s的速度（16线程，下载大文件），在VPS上测试国内最高我跑到过稳定300MB/s，瞬时580MB/s的最高速度

你提到IDM更快，因为IDM默认开的线程更多（默认好像是128？忘了）。
但是，如果16线程不能跑慢速，说明不是单纯的下载工具的问题，应该是你所在地区，阿里云盘服务不好

**Comment by liupan1890** [comment]
注：VPS是北京地区的G口主机
