### ISSUE TITLE
新版是不是分享功能给取消了？

### ISSUE THREAD

**Issue by eatWh** [liupan1890/aliyunpan#31]

**Comment by liupan1890** [comment]
是的，前两天不是有人提示了，考虑到后期用的人多了，可能官方会警告（秒传绕过了官方审核）
所以我主动屏蔽掉了分享功能。

当前你仍然可以导入别人分享的秒传链接，小白羊不提供创建秒传链接的功能了

**Comment by arliong** [comment]
其实我是从别人的文章看到你有文件分享的功能找过来的, 结果还没有体验就屏蔽这个功能了. 
我也理解这个功能可能被滥用的坏处,可否做个折衷, 比如每个用户一个月只能分享某个数量(1-N)的外链? 
毕竟有这个功能, 确实是某种刚需, 数量卡一下又不至于威胁到软件的生存, 请斟酌 !

**Comment by liupan1890** [comment]
端午福利，会发布最后一次带秒传的版本，以后会彻底移除创建功能
