### ISSUE TITLE
播放器路径设置

### ISSUE THREAD

**Issue by lingchuanbo** [liupan1890/aliyunpan#312]
您好大神，希望小白羊增加一个播放器路径配置选项，可以吗？
目前用法需要拷贝到小白羊目录下，有点不便捷，因为其它地方也有个mpv，在拷贝一个过来，系统就多了一个，希望小白羊能做一个配置选项，谢谢！

**Comment by liupan1890** [comment]
在下个版本里会有路径选择，因为下个版本支持了其它播放器
