### ISSUE TITLE
误报请关闭这个问题

### ISSUE THREAD

**Issue by DifferentSparkler** [liupan1890/aliyunpan#317]
v2.9.24版本默认的缓冲目录是不是系统盘

       最近有几次用v2.9.24版本看高清视频的时候，由于系统盘空间不够大，导致看到一半电脑自动重启。
而且重启后软件也无法打开只能重新解压软件才能打开，还会丢失正在编辑的文档。

建议后期版本添加自定义设定缓冲目录。

**Comment by cc201855** [comment]
这个如果你使用的是potplayer的话，自己可以在potplayer的设置里面设置缓存位置

**Comment by liupan1890** [comment]
我感觉应该是用的Potplayer，因为mpv不会产生硬盘缓存，potplayer由用户提醒过我，我才知道会产生硬盘的缓存文件

参阅https://github.com/liupan1890/aliyunpan/issues/308

可以自己修改potplayer的缓存位置

**Comment by DifferentSparkler** [comment]
> 我感觉应该是用的Potplayer，因为mpv不会产生硬盘缓存，potplayer由用户提醒过我，我才知道会产生硬盘的缓存文件
> 
> 参阅#308
> 
> 可以自己修改potplayer的缓存位置


不好意思是误报了 是我电脑中勒索病毒了 每次重启的时候都是在用这个看 电视剧导致误报了

**Comment by DifferentSparkler** [comment]
Your important files are encrypted. Many of your documents, photos, passwords, databases and other files are no longer accessible because they have been encrypted. Maybe you are busy looking for way to recover your files , but do not waste your time. Nobody can recover your files without our decryption KEY (if somebody will tell that they can do it, they will also contact me and I will make the price so much expensive than if you contact directly).

                     !!!THE DATARECOVERY COMPANIES JUST WANT YOUR MONEY!!!
  !!DATA RECOVERY COMPANIES WILL ONLY INCREASE THE DECRYPTION TIME!!

Can i Recover My Files?
Sure. We guarantee that you can recover all your files safely and easily But You have not so enough time . So If you want to decrypt all your data, you need to pay .As fast you pay as fast all of your data will be back as before encryption.

Send e-mail to this address: yourdataok@tutanota.com

You have to pay for decryption in Bitcoins.

ATTENTION
Do not rename encrypted files.
Do not try to decrypt your data using third party software, it may cause permanent data loss.
Decryption of your files with the help of third parties may cause increased price (they add their fee to our) or you can become a victim of a scam.

If you want to try datarecovery company just ask for testfile.They have to give it for you if they can do something.

They will not.


Key Identifier:
343271632745582000
您的重要文件已加密。您的许多文档、照片、密码、数据库和其他文件已被加密，无法再访问。也许您正忙于寻找恢复文件的方法，但不要浪费时间。没有我们的解密密钥，任何人都无法恢复您的文件（如果有人告诉我他们可以恢复，他们也会联系我，我会让价格比您直接联系要贵得多）。
!!!数据恢复公司只想要你的钱！！！
!!数据恢复公司只会增加解密时间！！
我可以恢复我的文件吗？
当然我们保证您可以安全轻松地恢复所有文件，但您没有足够的时间。所以，如果你想解密你所有的数据，你需要付费。你付费的速度和加密前一样快，你所有的数据都会回来。
将电子邮件发送到此地址：yourdataok@tutanota.com
你必须用比特币支付解密费用。
注意
不要重命名加密文件。
不要尝试使用第三方软件解密数据，这可能会导致永久性数据丢失。
在第三方的帮助下解密您的文件可能会导致价格上涨（他们将他们的费用加到我们的费用中），或者您可能成为诈骗的受害者。
若你们想尝试数据恢复公司，只要要求测试文件。若他们能做些什么，他们必须给你们。
他们不会。
密钥标识符：
343271632745582000
