### ISSUE TITLE
v2.10.17 发布

### ISSUE THREAD

**Issue by liupan1890** [liupan1890/aliyunpan#318]
时间缘故 v2.10.17 还是半成品，部分功能被临时限制了（不能用），下个版本会恢复正常，使用中有哪里不正常的也不用在意，是因为还没做完，下个版本继续完善
虽然这么说让人很失望，但 v2.10.17 确实没做完就先发出来了，如果 v2.9.24 你正常使用没有卡顿，那就等这周日的 v2.10.24 版再更新也行

#

window / linux / mac 版：

从蓝奏下载 https://wwe.lanzoui.com/b01nqc4gd

更新方式：删除旧文件，下载新版解压即可

#

1. 优化文件列出逻辑，节约 50%的等待加载中时间
   一个文件夹里包含 17000 个文件时，打开文件夹 v2.9 需要 140 秒 v2.10 需要 48 秒。因为阿里云盘的架构，已经没有再进一步的优化空间了

2. 优化一个文件夹直接包含大量子文件夹时的卡顿和内存剧增问题
   一个文件夹里直接包含 17000 个子文件夹时，打开文件夹 v2.9 需要占用 700MB 内存， v2.10 需要占用 190MB 内存
   v2.9 当一个文件夹里包含 3000 个以上的子文件夹时，小白羊文件夹树会卡顿
   v2.10 无所谓多少个子文件夹，不会卡顿

3. 优化网盘包含有巨量文件夹时，启动后前几秒会卡顿的问题

4. 优化上下传记录的本地数据库体积
   长期大量上传下载会产生较大的本地记录数据，现在会自动清理

5. 修正统计文件夹体积功能的本地缓存和运行时内存占用
   开启统计文件夹体积功能后，我网盘里有 2 万个文件夹和 31 万个文件，v2.9 会产生 167MB 的缓存，v2.10 会产生 8MB 的缓存
   修正了一个会导致 CPU 和内存占用高的 BUG（用户账号 token 失效时，会因为定时统计功能导致 CPU 和内存占用很高）

6. 优化在线预览视频现在支持很多种播放器了
   当前只适配了 windows （测试了 MPV，Potplayer，VLC media player，KMPlayer，恒星播放器，SMPlayer）
   macos 和 linux 稍后会适配，现在仍旧只能用 mpv 播放器

7. 增加在线预览 word/excel/ppt/pdf 文件的功能
   当前，大部分音视频格式，大部分图片格式，word/excel/ppt/pdf/txt，200 余种常见文本格式 都可以在线预览了

8. 修正在文件夹里搜索后，拖动搜索结果里的文件上传，上传文件名错误的 BUG

9. 优化上传前的 sha1 校验，提升上传速度
   阿里云盘官方(网页+PC)上传一个 2.9GB 的电影，需要计算 sha1 值，用时 70 秒，v2.9 用时 20 秒，v2.10 用时 6 秒
   在我电脑上，每秒的计算速度计量，官方 40MB/s，v2.9 200+MB/s，v2.10 700+MB/s （注需要 m2 ssd 才能达到 700MB/s）

10. 美化了一下界面
11. 增加是否按照完整网盘路径保存的设置
12. 增加关闭窗口立即退出的设置
13. 增加双击才打开文件、文件夹的设置
14. 增加清理缓存的设置
15. 增加运行日志的设置
16. 文件夹树的宽度可以拖动调整了
17. 图片、Office、文本预览现在是单独窗口了
18. 修正一些文件格式识别不准确的 BUG

初步统计的当前不可用功能：重命名，在线解压，导入分享链接，文件夹详情，视频雪碧图，复制移动功能
这些都会在一周后的下次更新时恢复可用，下周还会增加：文件列表的缩略图模式、完整的分享功能

提示：上面提到的性能问题，当你的网盘内所有的文件夹仅仅直接包含少于 1000 个子文件夹，或者网盘内文件总数少于 10 万个，或者一次只上传、下载数千个文件，并不会感觉到。只有文件数量达到一定极限时才会体现

#

10.19 13:55:00更新
修正v2.10.17上传文件时卡在等待计算sha1的bug

#

10.22更新：
这周鸽了，这几天家里在吵架无心编码，本周更新鸽了鸽了 , 31日保证会更新的

#

10.28更新：
由用户反馈说，只选择一个文件删除，却删除了整个文件夹，我尚未明确是否是v2.10.x的BUG，为了避免其他用户误删除文件，已经临时删除了v2.10.19的安装包。大家如果正在使用v2.10.17/19 ,请留意先不要使用彻底删除功能。v2.9.x版本肯定不存在此问题可以放心使用

**Comment by ybbluesky** [comment]
等了一天，又要等哟

**Comment by liupan1890** [comment]
[在线预览视频支持的播放器.md](https://github.com/liupan1890/aliyunpan/blob/main/%E5%9C%A8%E7%BA%BF%E9%A2%84%E8%A7%88%E8%A7%86%E9%A2%91%E6%94%AF%E6%8C%81%E7%9A%84%E6%92%AD%E6%94%BE%E5%99%A8.md)

**Comment by yadex** [comment]
Linux版没上传阿

**Comment by at2008** [comment]
速度快了很多 赞一个！！！

**Comment by ybbluesky** [comment]
下载过程中，如果目录中有相同文件，会提示文件已经存在，能否优化一下，设置为自动跳过或者覆盖此文件？

**Comment by mali321321** [comment]
2.10.19版本热键处理有问题

在新建文件夹输入时按Backspce界面会返回。。。

**Comment by huangazhuang** [comment]
希望能早日新增阿里云盘 同步文件夹功能，就像百度盘的工作空间功能一样。
