### ISSUE TITLE
在线播放不能调整声音？

### ISSUE THREAD

**Issue by stonerockone** [liupan1890/aliyunpan#32]

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/121529245-cce81400-ca2e-11eb-98a4-06ff58987d41.png)


mpv播放器，百度一下，快捷键也能操作

**Comment by Lijingze2019** [comment]
https://mpv.io/manual/master/#interactive-control

**Comment by iD2073** [comment]
我发现播放窗口置顶快捷键“T”是无效的，不知道你们的能不能用，有时置顶只能借助别的小软件了，

**Comment by Lijingze2019** [comment]
> 我发现播放窗口置顶快捷键“T”是无效的，不知道你们的能不能用，有时置顶只能借助别的小软件了，

Shift+T是置顶开/关
我一直能用
