### ISSUE TITLE
不能上传 .DS_store 文件

### ISSUE THREAD

**Issue by QiTianzu** [liupan1890/aliyunpan#320]
上传了几万的文件，发现不管传几次都少几个文件，找了半天才发现是 .DS_store 文件没有上传上去，在小白羊中不管是上传包含 .DS_store 文件的文件夹还是单独上传 .DS_store 文件都无法上传 .DS_store 文件，在官方客户端中上传包含 .DS_store 文件的文件夹无法上传 .DS_store 文件，但单独上传可以上传成功。

**Comment by liupan1890** [comment]
是的,会被自动过滤，这个文件不重要
``````
if (filepath.endsWith('$RECYCLE.BIN')) continue
      if (filepath.endsWith('System Volume Information')) continue
      if (filepath.endsWith('Thumbs.db')) continue
      if (filepath.endsWith('desktop.ini')) continue
      if (filepath.endsWith('.DS_Store')) continue
``````

**Comment by liupan1890** [comment]
这个分人，对大部分人来讲，这个文件应该是被自动排除掉才对，因为大部分人不知道什么是 .DS_store 文件

10个人里只有2个人用mac，2个人里不一定有一个人知道什么是 .DS_store 文件

 .DS_store 文件:是mac系统自动产生的，文件夹的配置文件（比如文件夹里包含图片时，可以设置这个文件夹的封面是某一张图片），知道什么是 .DS_store 文件的100个人里，不知道有几个人会去手动的修改这个文件？因为这个文件是mac系统自动产生的


那么肯定会有更多的人，会有疑问，我就上传了一个文件夹，这个文件夹里就10张图片，怎么现在多出来一个 .DS_store 文件?
为了照顾大多数人，所以这个文件是被自动过滤掉的。因为大多数场景下，这个文件没有任何作用并且遇到强迫症的人，反而会想去清理掉网盘里的这个文件

如果你需要上传这个文件，可以试一下使用阿里云盘官方网页版上传。因为我猜你肯定也不是每一次都需要上传这个文件，应该是上传特定的文件夹时需要这个文件
