### ISSUE TITLE
自动播放器不能使用

### ISSUE THREAD

**Issue by lingchuanbo** [liupan1890/aliyunpan#322]
![image](https://user-images.githubusercontent.com/4213515/137893312-b302f49b-9fd2-47a5-8579-f5d4782b0183.png)
您好 新版本（2.10.19）自定义播放器不能使用，使用内置则正常！
自定义到内置路径也是不能使用!

**Comment by liupan1890** [comment]
这就很奇怪了，我刚试了一下我电脑上是正常的啊

**Comment by liupan1890** [comment]
我知道你不能播放的原因是什么（调用命令参数错误）
但是我不知道为什么

首先，使用“内置MPV播放器”的时候，如你录像中，名字是不正确的，说明调用参数没有正确的被识别（虽然能播放，但实际上是出错的）。正常的应该是这样的：（看窗口顶部 ）（原始文件模式——国土安全。。。。）
![无标题](https://user-images.githubusercontent.com/67817756/138022613-05964065-0f35-4cdb-99f6-7a85620b1cf9.png)

而你的录像里是（。。。。OSS2）说明调用参数是错误的

然后当你选择“自定义播放器时”，调用参数还是错误的（没有自动加引号），因为参数只有一个url，出错了就不能播放了

我的意思是，正常情况下，应该会自动处理调用参数---自动加引号，你的电脑上没有自动处理，导致参数错误

但是我不知道为什么你的电脑上没有自动处理加引号

回复我一下，你的电脑系统和版本，我安装一个试试看，问题在哪

**Comment by QiTianzu** [comment]
我是自定义为内置的MPV播放器不能播放，直接使用内置或自定义为PotPlayer可以播放。

**Comment by lingchuanbo** [comment]
![Honeycam 2021-10-21 14-13-13](https://user-images.githubusercontent.com/4213515/138221604-f87f53c3-f3d7-4161-9a57-574a43348341.gif)
我本地视频地址 加双引号是可以 启动mpv 播放的

**Comment by zhangsenpei** [comment]
我想改自定义播放器却没有这个选项，请问是什么原因呢

**Comment by liupan1890** [comment]
> 我想改自定义播放器却没有这个选项，请问是什么原因呢

@zhangsenpei 不是最新版吧，自v2.10才有，之前的版本没有

**Comment by liupan1890** [comment]
@lingchuanbo 

在v2.11.14里更新了调用方式，试一下，可能可以修正你这样路径问题导致不能调用的情况

如果试了有问题/或者没有问题，开新issue告诉我一下结果
