### ISSUE TITLE
上传超过97GB的文件时会显示网络错误无法上传

### ISSUE THREAD

**Issue by LucasChen824** [liupan1890/aliyunpan#326]
![ZN1BM)L)0ZRIZ%6NM $3B7](https://user-images.githubusercontent.com/91370885/138079563-cc83d157-8925-4b37-850b-aa80302b4dae.png)
多次重启软件和电脑都无法修复。网络是正常的，不知道出了什么情况？

**Comment by liupan1890** [comment]
你是上传啊，我还以为是下载。。

等下个版本，我把这个显示休整一下，然后把上传出错时都记录到日志里，以后再出错，我就知道是怎么回事了，也就能针对性的修复了。当前，因为也看不到具体的错误信息，上传时也有好几个接口的调用，不知道具体是哪一个接口出的错。所以并没啥有用的信息去分析啊

**Comment by liupan1890** [comment]
已经在v2.11.07里修正了此问题，现在已经可以上传大文件了
