### ISSUE TITLE
Win7第二次执行不能打开,提示: 已停止工作

### ISSUE THREAD

**Issue by arliong** [liupan1890/aliyunpan#33]
第一次运行阿里云盘小白羊版v1.6.6.exe, 可以看到界面提示手机app扫码.当时没有扫, 电脑没有关机, 但是退出小白羊, 第二天就发现打不开, 下载最新的v1.6.10.exe,也是一样. 

错误信息如下:

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	阿里云盘小白羊版v1.6.10.exe
  应用程序版本:	1.0.0.0
  应用程序时间戳:	60c1ee28
  故障模块名称:	flutter_windows.dll
  故障模块版本:	0.0.0.0
  故障模块时间戳:	608b242a
  异常代码:	40000015
  异常偏移:	000000000091c30b
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0cc9
  其他信息 2:	0cc9a80ddcb658055df6cc2ae0b32f41
  其他信息 3:	18a6
  其他信息 4:	18a611c89a3b596f9d61fe54dfdbe304

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by liupan1890** [comment]
这个issue真的难道我了，当前支持winows7 x64版，因为你第一次可以运行，说明是64位没错。我自己的开发机也是win7,但没有遇到这种崩溃的时候

仅从错误信息上分析，故障模块名称: flutter_windows.dll属于flutter基础模块，不是我的代码，是谷歌flutter基础模块，也没有其他详细的信息了，我实在不知道从哪里下手。。。

你可以试试把整个文件夹都删掉，重新解压。再运行试试看

当前使用的是flutter2.0.6 从下个版本开始就更新为flutter2.2.1了，可能升级后你就能运行了。总之：未知BUG我也无能为力

**Comment by arliong** [comment]
我回忆了一下, 第二天我还更新安装了最新版本的华硕网盘. 其他就没有做什么了

我确实是剂案整个文件夹都删除,重新解压, 试过了.6 和.10的两个版本, 甚至我还是从D盘换到了C盘. 我没有设计到谷歌类的东西.

如果太麻烦, 我也只能换机器看看了

**Comment by liupan1890** [comment]
并不是麻烦不麻烦，而是我不知道从哪里下手，

有的BUG，我一看就知道是哪里的问题，然后可以去修正
这个BUG我看不出是哪里的问题，不知道怎么去修正啊

**Comment by arliong** [comment]
ok. 我换了台 win10的机器可以正常使用,暂时不敢再安装华硕云盘. 我关闭这条了, 謝謝你
