### ISSUE TITLE
一个想法：彻底解决“删除、彻底删除”功能的矛盾，文件无法恢复问题

### ISSUE THREAD

**Issue by jkqxl** [liupan1890/aliyunpan#336]
突然有一个想法，猜测可能会解决 彻底删除 后，无法恢复问题

很简单，在上传文件时，同时在本地txt文件创造“秒传链接”，因为 彻底删除 的目的是为了节省单用户网盘空间，但即使真的 彻底删除 后，在官方大数据还有备份，所以可以通过此方法找回 误删文件

测试软件：阿里云盘小白羊版v1.6.29
测试1：10G视频文件，1s创造“秒传链接”
测试2：下载好原文件后，不论网盘是否删除原文件，结果，使用“秒传链接”解析成功，秒传失败；直接上传下载好原文件，秒传成功（删除原文件一样的结果，说明这似乎是软件功能问题，不是秒传问题；具体使用的是导入秒传的“秒传文件TXT”功能）

其它问题：复制相同文件似乎无效
其它可能问题：因为“秒传链接”文件二导致的保密问题，不确定是否重要，毕竟电脑如果被病毒入侵，网盘账号密码都可能丢失，实在不行，每个用户对其进行单独加密

因为秒传链接本来就是网盘要增加的功能，所以再对其深入使用也不算什么

最后，就目前本人测试，实现的可能性很高，但本人不是网盘专业开发者，具体还要作者进一步测试

**Comment by jkqxl** [comment]
@liupan1890

关于用户 需求改变

**如果用户习惯，每次在网盘都 彻底删除 文件，需求改变 的情况就几乎不会出现

如果用户习惯，每次在网盘都 删除 文件，不在乎垃圾站是否有文件，土豪用户有大额空间等，确实用户会出现 需求改变 的情况，但在这种情况下，用户因为不使用 彻底删除，那是否有彻底删除的按钮就无所谓了

最后，真的希望软件作者可以深入考虑下，像我上面说的那样，保留一步的 彻底删除 选项，是利大于弊的。**

**Comment by jkqxl** [comment]
@liupan1890

关于用户 需求改变

**- 如果用户习惯，每次在网盘都 彻底删除 文件，需求改变 的情况就几乎不会出现
 
- 如果用户习惯，每次在网盘都 删除 文件，不在乎垃圾站是否有文件，土豪用户有大额空间等，确实用户会出现 需求改变 的情况，但在这种情况下，用户因为不使用 彻底删除，那是否有彻底删除的按钮就无所谓了

所以，只展现一种删除方式，但可以让用户选择是否使用其中一种（删除、彻底删除），相比展现两种删除方式，可以让不同需求用户更有针对性，也更加高效，同时也不失安全性。

最后，真的希望软件作者可以深入考虑下，像我上面说的那样，保留一步的 彻底删除 选项，是利大于弊的。**

**Comment by liupan1890** [comment]
我真的明白“彻底删除”这个按钮很有用，

因为我自己都是，一直使用彻底删除，然后就不用删除到回收站了（因为还要去二次删除，麻烦）

但吸取教训，怕了，所以最后还是取消了

无关逻辑，无关其他，仅仅就是增加一点点（微乎其微）的安全性

大家都是这样的，有，很方便，一直用

没有？挺麻烦（并不是每次都要删除2遍，基本都是定期清理回收站，定期的意思是网盘空间不足了，就想起来清空回收站了），但也能用

**Comment by jkqxl** [comment]
好吧，也许大多数人都不喜欢这个功能。
退而求其次，是否可以增加“定期清理回收站功能”，时间跨度从1h、4h、8h、1天、7天、一个月等。

这个功能，应该所有都是需要的。

**Comment by liupan1890** [comment]
在v2.11.07里已经增加了定期清理回收站的设置，会有缓解
