### ISSUE TITLE
加载特别慢

### ISSUE THREAD

**Issue by Ozzy-hzy** [liupan1890/aliyunpan#337]
点击一个目录后，一直是加载中差不多10秒，点击一个视频，好久才能跳出播放器开始播放，
想知道配置文件放在哪个目录，试试清除配置文件有没有用，因为之前没用这种问题

**Comment by Ozzy-hzy** [comment]
> 如果是使用的v2.9.x
> 
> 可能是在计算文件夹体积，导致的卡顿
> 
> 在v2.9.x里，比较激进，既多个文件夹同时并发，争取最短的时间内计算完所有文件夹的体积，尽早显示出来
> 
> 如果你的网盘里文件夹特别多（近万个），确实会明显感觉到，当时比较卡（会卡几分钟到十几分钟），不是界面卡，是列文件时间变长
> 
> 同时也会在本地C:\Users\用户名\AppData\Roaming\alixby\database里生成体积比较大的数据库文件
> 
> 在v2.10.x开始，改变了思路，是一个文件夹一个文件夹的去计算。 把计算体积，安排在很长的时间里，这样，就感觉不出卡顿了，不会影响列文件的时间 同时也取消了本地数据库缓存，不再生成体积较大的数据库文件了 （当然v2.10.x有BUG，还是等周日发布新版再尝试吧）
> 
> 可以尝试，在设置里，关闭计算文件夹体积的功能

今天用突然加载又正常了（云盘里文件文件夹确实很多，有16t左右），可能真的是网络问题。。。用的是联通校园网

**Comment by liupan1890** [comment]
恢复了就好

我也在不断地改进思路，让小白羊更快一点！
