### ISSUE TITLE
期待周末版，有什么新功能呀？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#340]
如问题，建个群大家平时好交流吧

**Comment by liupan1890** [comment]
确实有必要，但我没有群

出误删BUG后，这两天我重新梳理了一遍所有的代码，所以周日也没啥新功能

我时间有限，开发起来其实挺慢的

**Comment by iD2073** [comment]
周日又要鸽了？

**Comment by ybbluesky** [comment]
应该不会鸽的

**Comment by liuluping0106** [comment]
求问什么时候出文件同步啊

**Comment by Techoc** [comment]
不如建个tg群一起讨论

**Comment by liupan1890** [comment]
没说要鸽啊。。。。

@liuluping0106  我很早就想要出文件同步功能了，但是，这不是各种问题吗（操作数十万文件时的性能，本地数据库体积，显示文件夹大小），所以一直没时间做，我也没办法啊。

**Comment by Borber** [comment]
> 没说要鸽啊。。。。
> 
> @liuluping0106 我很早就想要出文件同步功能了，但是，这不是各种问题吗（操作数十万文件时的性能，本地数据库体积，显示文件夹大小），所以一直没时间做，我也没办法啊。

大佬加油! 祝身体健康
