### ISSUE TITLE
播放器选择

### ISSUE THREAD

**Issue by zhangsenpei** [liupan1890/aliyunpan#343]
请问如何设置MPC-HC作为视频播放使用呢，有特殊的需要

**Comment by liupan1890** [comment]
第一步：下载MPC-HC

C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe

第二步：选择mpc-hc64.exe

小白羊-设置-UI-播放软件-自定义播放器-选择播放器-选择C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe

**Comment by zhangsenpei** [comment]
![image](https://user-images.githubusercontent.com/79370772/139626663-85e457e1-229c-4911-9b38-81b6927ac420.png)
![image](https://user-images.githubusercontent.com/79370772/139626685-60b192ef-ac47-437c-9075-7415ba678168.png)
为何我的UI设置里面没有选择播放器的功能

**Comment by zhangsenpei** [comment]
> 第一步：下载MPC-HC
> 
> C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe
> 
> 第二步：选择mpc-hc64.exe
> 
> 小白羊-设置-UI-播放软件-自定义播放器-选择播放器-选择C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe

![image](https://user-images.githubusercontent.com/79370772/139626814-e6dd1dd8-3c72-475c-82c8-25bc5fabdfff.png)
![image](https://user-images.githubusercontent.com/79370772/139626822-86ce6490-5a20-4445-b35a-6a8e20a96dd1.png)
我的Ui设置里面没有选择播放器选项哦

**Comment by QiTianzu** [comment]
> > 第一步：下载MPC-HC
> > C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe
> > 第二步：选择mpc-hc64.exe
> > 小白羊-设置-UI-播放软件-自定义播放器-选择播放器-选择C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe
> 
> ![image](https://user-images.githubusercontent.com/79370772/139626814-e6dd1dd8-3c72-475c-82c8-25bc5fabdfff.png) ![image](https://user-images.githubusercontent.com/79370772/139626822-86ce6490-5a20-4445-b35a-6a8e20a96dd1.png) 我的Ui设置里面没有选择播放器选项哦

你这是2.9版本的，2.10才支持选择自定义播放器

**Comment by zhangsenpei** [comment]
> > > 第一步：下载MPC-HC
> > > C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe
> > > 第二步：选择mpc-hc64.exe
> > > 小白羊-设置-UI-播放软件-自定义播放器-选择播放器-选择C:\Users\xxx\Desktop\MPC-HC.1.7.13.x64\mpc-hc64.exe
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79370772/139626814-e6dd1dd8-3c72-475c-82c8-25bc5fabdfff.png) ![image](https://user-images.githubusercontent.com/79370772/139626822-86ce6490-5a20-4445-b35a-6a8e20a96dd1.png) 我的Ui设置里面没有选择播放器选项哦
> 
> 你这是2.9版本的，2.10才支持选择自定义播放器

哪里有2.10的版本，没看到过哦

**Comment by liupan1890** [comment]
https://github.com/liupan1890/aliyunpan/issues/342
