### ISSUE TITLE
上传下载的后缀过滤很爽，但是更细一点就更完善了

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#344]
![image](https://user-images.githubusercontent.com/34271895/139606437-8c42c519-8d93-4bdd-8ef4-ef07d0f5cde9.png)
已经有了过滤的列表， 如果增加一个只包含的列表就更完美了，就是只上传与下载列表中的文件

**Comment by liupan1890** [comment]
你这个思路并不太好

1.过滤并不是常用功能，为了一个不常用的功能，增加2种设置项，太占地方，不好

2.在过滤时，其实【不要上传哪些，和只上传哪些】，是正反一致的
有的时候确实只想上传某文件
有的时候确实只想过滤某些文件

有2种设置，就需要在设置里来回切换折腾，这对用户习惯不友好。不如强制为一种（按照字面，是选择的过滤掉这种），这样，不论是上传还是过滤，按照一个思路去解决，虽然有的时候很麻烦（需要自己统计出所有不要上传的格式），但操作习惯上更好

**Comment by liupan1890** [comment]
最开始想过，这里是选择配置文件，具体的规则在配置文件里去配置，
（规则 可以是只上传，也可以是过滤）
（可以创建多个规则文件，方便切换）

但是，实际问题是，
1.需要创建规则文件，有很多人，不知道怎么创建 xxx.ini文件，只会创建xxx.txt文件
2.需要编写规则（一个后缀一行，在后缀前增加！既过滤，没有！既只上传），很多人学不会怎么去写规则，写的不对，程序出错

考虑到减少大家的学习成本，最后改成的现在这样，一个一个添加
考虑到有的文件可能会包含！容易造成误过滤，最后统一为只过滤了

**Comment by ybbluesky** [comment]
> 一个后缀一行，在后缀前增加！既过滤，没有！既只上传

了解了，OK
