### ISSUE TITLE
同步盘功能

### ISSUE THREAD

**Issue by liuluping0106** [liupan1890/aliyunpan#345]
咳咳，又来问同步盘功能什么时候上线了？或者能不能先上线个备份盘，就每隔一天自动把一个文件夹上传一遍。#224 
希望小白羊越来越好！

**Comment by liupan1890** [comment]
嗯，那这周我安排看看，这周日或者下周日会上线

**Comment by ybbluesky** [comment]
高效，这功能也爽，不知道检查相同文件功能什么时候能出呀？

**Comment by liuluping0106** [comment]
也不至于太复杂吧，根据时间戳同步我感觉就能满足大部分需求了。

**Comment by ybbluesky** [comment]
网盘做同步盘还是有很多问题，如果个人使用建议用坚果云，个人办公使用一般够用了，还有文件 版本控制

**Comment by Jingzhenzxz** [comment]
> 咳咳，又来问同步盘功能什么时候上线了？或者能不能先上线个备份盘，就每隔一天自动把一个文件夹上传一遍。#224 希望小白羊越来越好！

我最渴望的就是这个功能哈哈。
