### ISSUE TITLE
关于最新发布的“小白羊版Win v2.10.31”，使用发现的一些不足之处

### ISSUE THREAD

**Issue by jkqxl** [liupan1890/aliyunpan#346]
Win v2.10.31 相比原来的 Win v2.9.24

1. **左侧文件夹树、右侧文件夹**
- **文件界面 ，没有之前的美观：**左侧文件夹树界面的收藏、回收站、网盘竖排排列，布局不合理，不美观（没必要像收缩左侧菜单那样排列）；不知道是不是我的错觉，文件夹树的文件图标、图标间隔变得更大了，体验不如之前；折叠图标变成深色（建议，未展开为透明浅色，展开深色，亦或者使用之前版本的图标三角灰色）、文件夹图标变成浅色（颜色应该加深，浅色没有实体感觉，没有点击感），整体更加刺眼；

- **使用体验1**：点击文件夹、折叠图标，会卡顿一下才打开下级文件（左右两侧同时打开），不论文件多少都会出现，文件夹多的卡顿更明显，及其影响使用体验，之前版本没有（右侧打开文件夹也一样）
**【重新测试发现，老版本是先打开左侧文件夹树，卡顿一下，再打开右侧文件夹，因为注意力是集中在左侧，在目光从左侧到右侧后，右侧已经打开，所以没发现。新版本是左右两侧同时打开，因为注意力集中在左侧，所以左侧卡顿特别明显】**

**建议，实际使用时，从左侧文件夹树打开最后需要的右侧文件夹，之后打开右侧文件，是先要打开左侧多级文件夹下的某个文件，右侧文件夹卡顿慢一些没关系，但左侧文件夹树打开卡顿，每次点一下卡顿一下，使用体验很不好**

- **使用体验2**：仅当左侧的选中项在当前级别文件夹，才可以折叠，选中项在更下一级别时，前一级别、前前级别等，都无法折叠。

- **关于打开压缩包功能，有些分享的压缩包资源，不希望被别人在线解压打开**：如果可以实现，请求增加设置“分享压缩包无法打开”，不行就算了
- **双击打开文件夹功能**：对于左侧的文件夹树来说，双击打开，毫无意义，因为在没有文件夹拖拽的情况下，它就不需要被在不打开右侧文件列表的情况下被选中
- **左侧文件夹树和右侧文件列表的互动关联**：如果未来增加了文件夹拖拽，请同时增加“开启或关闭互动关联的选项”
- **右侧文件列表的网盘地址功能**：不清楚该功能的意义何在。为了打开上级目录？与联动功能重复，且打开根部网盘会弹出地址，还得再打开一次（win文件夹系统则没有互动关联）。为了快速粘贴，定位搜索地址？目前无法粘贴，无法搜索，无搜索历史记录
- **最后关于 彻底删除 功能**：或许大多数人都不喜欢这个功能，当前版本也已经取消，那再一次退而求其次，是否可以增加“定期清理回收站功能”，时间跨度从1h、4h、8h、1天、7天、一个月等

**Comment by ybbluesky** [comment]
个人觉得这个软件比官方的好多了，特别是大量文件的情况下，回收站有必要设置定期清空？如果不喜欢或者用起不爽完全可以用官方版

**Comment by liuluping0106** [comment]
关于打开压缩包功能，有些分享的压缩包资源，不希望被别人在线解压打开。什么叫不希望被在线打开，就感觉很奇怪，你分享了，别人是在线看，下载看有什么区别来。
另外，明明作者到现在没有请喝咖啡链接，为啥感觉你的口气好像在说win11orMacOS的感觉。u1s1，个人开发者软件全部按作者本人的需求来都ok，怎么好像作者求着你一样。

**Comment by liuluping0106** [comment]
关于打开压缩包功能，有些分享的压缩包资源，不希望被别人在线解压打开。什么叫不希望被在线打开，就感觉很奇怪，你分享了，别人是在线看，下载看有什么区别来。
另外，明明作者到现在没有请喝咖啡链接，为啥感觉你的口气好像在说win11orMacOS的感觉。u1s1，个人开发者软件全部按作者本人的需求来都ok，怎么好像作者求着你一样。

**Comment by rapmq0** [comment]
左侧的收藏、回收站、网盘竖排排列，是最合理的，你懂不懂软件？谁会喜欢一会横排一会竖列的操作？

**Comment by chen-7-c** [comment]
..不希望压缩包被别人打开，你加密不行么..

**Comment by liupan1890** [comment]
比较详细的建议了，我一点点回复啊

>**文件界面 ，没有之前的美观：**左侧文件夹树界面的收藏、回收站、网盘竖排排列，布局不合理，

呃，这是之前有人说过，横排的不习惯，所以现在又改成竖排了，因为其他文件夹都是竖排，如果收藏夹回收站是横排，就是2种操作习惯了，不如全部竖排更熟悉。用惯了其实也就差不多

>文件夹树的文件图标、图标间隔变得更大了，体验不如之前；

图标没变。但文字周围的间距，空间，可点击区域 都变大了，是因为v2.9的间隔太紧凑，容易误点

>折叠图标变成深色（建议，未展开为透明浅色，展开深色，亦或者使用之前版本的图标三角灰色）、文件夹图标变成浅色（颜色应该加深，浅色没有实体感觉，没有点击感），整体更加刺眼；

这个我倒是没想到，因为展开图标太小了，感觉该不该颜色都不显眼，另外当前选中的那一个文件夹的展开图标已经变色了（同文件夹名都是蓝色），展开不展开的图标再变色，就有点乱了，没有主次了

文件夹图标的颜色是为了和右侧文件列表里统一，左边，右边，都是文件夹，颜色统一语义一致，便于理解

**Comment by liupan1890** [comment]
>点击文件夹、折叠图标，会卡顿一下才打开下级文件（左右两侧同时打开）

在v2.9里是一次性全部加载的，因为已经加载了，所以展开时很少有卡顿
但是，如果一个文件夹里面直接包含2-3千个文件夹时，展开这个文件夹，会导致整个界面卡顿，这个没办法，是因为显示的文件夹太多了

在v2.10里采用了虚拟树+按需加载，所以是每次点击展开时才异步加载，有一个加载的步骤所以出现了卡顿

其实不是卡顿，是一个蓝色的转圈的加载中动画，有时因为加载的太快，就一闪而过，就感觉像卡了一下似的

这个卡顿的时间，跟是否刚启动有关，如果是刚启动软件，点击一个文件夹，需要联网读取一下，会更慢
启动了1-2分钟后，此时后台已经自动的加载了全部文件夹，点击一个文件夹，会很快

下来我在想办法，看看能否在快一点


>使用体验2：仅当左侧的选中项在当前级别文件夹，才可以折叠，选中项在更下一级别时，前一级别、前前级别等，都无法折叠

这个是故意设计成这样的
如果需要折叠（当前选中项的某个父文件夹），要先点击选中这个文件夹，然后再点击折叠图标就好了

有一个潜在的意识
就是左侧树要明显的直观的显示出右侧文件列表对应的文件夹
就是再左侧能看到，一个蓝色的选中的文件夹，同时你也会明白右侧正在显示的文件列表就是这个文件夹里面的

如果点击父文件夹，都会自动折叠，会隐藏当前选中的文件夹（蓝色的）

所以，设计为，别的文件夹都可以随便折叠，**只有** 包含有选中的文件夹（蓝色的）的这一路层级上的父文件夹，不能折叠，需要先切换（选中父文件夹）再折叠

**Comment by liupan1890** [comment]
>关于打开压缩包功能，有些分享的压缩包资源，不希望被别人在线解压打开

这个功能，当你分享了文件，别人保存了，自然是想怎么操作就怎么操作，没办法限制的。当前阿里云盘仅支持在线解压zip和rar，你需要打包为7z压缩格式，这样谁也不能在线解压了

>双击打开文件夹功能：对于左侧的文件夹树来说，双击打开，毫无意义

左侧树没有双击功能，只有右侧的文件列表，在设置里开启了双击后，才能双击


>右侧文件列表的网盘地址功能

1.作用就是快速跳转
2.当用户把窗口宽度拖到非常小，左侧树会自动收缩起来，此时最方便的就是顶部这里进行文件夹的跳转
3.作用是直观的看一下，当前文件的目录层级，知道这个文件属于哪个文件夹

>且打开根部网盘会弹出地址，还得再打开一次
顶部右侧的网盘（根目录）不能点击，他是鼠标移动上去，自动弹出下拉菜单单机双击都没有效果
下来菜单，是在文件层级很深或者文件夹名字超级长时，会导致顶部全是省略号，此时只能通过下拉菜单才能直观的完整的看到文件夹名


>最后关于 是否可以增加“定期清理回收站功能”，时间跨度从1h、4h、8h、1天、7天、一个月等

我感觉没必要，自动清理的时间跨度，长了没用用户自己就手动清理去了。短了不安全，自动的删除这样的功能我是不敢做的，需要让用户自己手动删除

1.只是点一下“清理回收站”，操作不麻烦
2.用户自己删了，后悔了，怪自己，自动清理的话，用户后悔了，会怪我的

**Comment by liuyun198833** [comment]
前面说的图标变了说的可能不是文件夹图标，可能是展开图标。之前是三角形图标（看上去确实更好看些），现在是 > 符号。是不是考虑展开速度的问题从图标改成符号了？

> 图标没变。

**Comment by jkqxl** [comment]
首先回复某些人的言论

@ybbluesky
什么叫做不喜欢或者用起不爽完全可以用官方版，您是不是认为我一天就是闲着没事干，才花几个小时测试软件、写答复的。还是说，您认为目前版本已经是、永远是世界上最好用的网盘版本了。照您这么说，软件作者在GitHub上形成的问题社区也都是浪费时间了啦，我以及一些人的问题回复都是吃饱了撑的，你之前在**大家是否存在显示已经上传完毕**上的问题反馈也承认是自我打脸喽。

@liuluping0106 
看你的头像、言论就知道是年轻人，年轻人嘛，狂一些没什么，我理解。
> 个人开发者软件全部按作者本人的需求来都ok，怎么好像作者求着你一样。
我回复的反馈都是尽可能在客观的基础上，并认为至少一部分人或大部分人需要才进行反馈的，但软件作者最后是否采纳，那又是另一个问题了，我也从未说过作者必须采纳，我只是认为开放性的讨论有益于解决从理论到现实的一系列问题。
当然你放心，你在GitHub上发表的网站，我个人是绝对会不去看的。

@rapmq0 
> 左侧的收藏、回收站、网盘竖排排列，是最合理的
左侧的收藏、回收站、网盘竖排排列，是最合理的，小白杨文件夹树合并的情况下也是合理的，百度等大部分网盘也是这样的，但在文件夹树展开的情况下，上面的竖排排列就不那么合理了。
> 谁会喜欢一会横排一会竖列的操作？
这么说你非常讨厌上一个版本 v2.9.24，但可惜嘴上说讨厌，身体却是诚实的。

@chen-7-c
> 不希望压缩包被别人打开
我的原话是，不希望被别人在线解压打开。当然，也是我没有说清楚。我曾经看过这样一篇文章，里面讲“在线解压会造成压缩包里面的数据上传，这样带密码压缩就没有意义了”，我也不确定里面将的是真是假，所以我也说，不行就算了。
> 加密不行么
**在分享加密压缩包，是必定要分享密码的，在网页上打开网盘网址后，在线解压、下载或保存到网盘线解压、下载，我之前发表的看法是主要强调 在网页上打开网盘网址的在线解压，没注意是否与本地在线解压有不同。**

**但阿里网盘区别于百度网盘的一大优势就在于，可以在网页上打开网盘网址后 直接下载，所以在此基础上我认为，加密的文件就不应该在线解压打开，它只能也只应该在下载到本地电脑打开，这样数据就绝对是保密的**

**Comment by jkqxl** [comment]
@liupan1890 

> 文件界面美观问题

其实随意，这不是重点，之前的观点只是为了全面，凑数而已

> 图标没变。但文字周围的间距，空间，可点击区域 都变大了，是因为v2.9的间隔太紧凑，容易误点

实际上间隔大小不是问题，重要的是文件夹与文件夹之间要有所区别，重要的是这个区别是什么，区别明显就不容易误点。
建议，将文件夹树的文件夹背景改成，鼠标所在文件的所在列，并且选择明显的区别颜色。

> 加载的太快，就一闪而过

我的是固态硬盘，在线看20g蓝光视频也很流畅，应该不是设备问题

刚启动网盘，点击文件夹树的文件，停顿一下大概1s左右，左右两侧同时刷新打开文件（我说的卡是指停顿，不是刷新）
等待1~2分，左侧还是会停顿，但有所改善，右两侧貌似完全不会停顿
没道理在文件夹数量特别多的情况下不卡顿，而在我这个几百个文件夹就卡顿的吧

> 设计为，别的文件夹都可以随便折叠，只有 包含有选中的文件夹（蓝色的）的这一路层级上的父文件夹，不能折叠

有两个映射，从左侧文件夹树→右侧文件夹列（映射1）、右侧文件夹列←左侧文件夹树（映射2）
我个人认为，映射1，借助左侧文件夹树，从众多的文件夹具体定位到某一文件，是文件夹树最重要的功能；映射2，从右侧文件夹定位到左侧文件夹树的目的是为了回退上层文件夹，它的功能与回退按钮、网盘地址功能重复，平时不会使用，并不重要。左右两侧文件夹必须对应，不能折叠上层文件夹，影响到映射1的使用，使用体验很不好。

> 关于打开压缩包功能

联系我之前有关回复，使用网盘就有数据泄露的风险，但如果可以，有必要把泄露的可能性降到最低。

> 网盘地址功能

确实没想到它可以在网盘界面缩小下使用，我主要用来返回上层文件夹
希望可以把 如图 ，网盘、网盘下拉地址列分开
![网盘地址](https://user-images.githubusercontent.com/72729140/139827086-c633b114-68c8-43f9-87e2-7a6863724cb8.png)

**Comment by liupan1890** [comment]
>网盘的个性发展应该在“取其精华，去其糟粕”的基础上，而不是在对其精华熟视无睹，闷头独自发展

这句给我的感触挺深。。。会是我以后开发的方向

**Comment by liupan1890** [comment]
先说基本可以不用继续讨论的

# 
>文件夹数量特别多的情况下不卡顿，而在我这个几百个文件夹就卡顿的吧

这个卡顿，以后我再想办法优化

>关于打开压缩包功能

这个属于阿里云盘提供的正常功能，无法做出限制

>定期清理回收站功能

其实感觉阿里云盘后期也会自动增加回收站内文件多少天后自动过期的功能的。那我之后的版本里加个设置吧，10天，20天，30天，自己选择。会定期清理回收站内超期的文件
（注意不是每10天自动清空回收站，而是仅仅把文件删除到回收站**超过10天的文件**，自动清理掉）


>关于间隔问题

这个无伤大雅，因为现在有了很多触屏平板，我就有surface pro ，好多年前出的了，在这种平板上面使用小白羊时，有的时候是手指触摸的，间距/图标按钮 特别小的时候，操作并不是很精准

**Comment by iD2073** [comment]
建议，将文件夹树的文件夹背景改成，鼠标所在文件的所在列，并且选择明显的区别颜色

这个我不是很明白，帮我做个效果图？
（选择明显的区别颜色我明白，以后会改一下，明显一点）
（将文件夹树的文件夹背景改成，鼠标所在文件的所在列）我没明白是怎么样

![image](https://user-images.githubusercontent.com/87513821/139853851-8ebbdae5-aa89-41ff-bdd5-574d8183afd6.png)

我是觉得还是像这样标示所在的路径是最直观的，

**Comment by iD2073** [comment]
现在的目录树并不能完美的标示自己所在哪个目录下，得细看才可以，其实就是不改，就这样也已经很不错了，比官方的强百倍了，感谢小哥

**Comment by liupan1890** [comment]
@iD2073  这个效果我不会做

其实不是说完全做不出来，而是，
1. 跟虚拟树本身性能有冲突，需要自AltData起一直向上反向的遍历全部父节点，当层级比较深的时候，就有性能问题（这个不重要，性能问题可以花时间认真抠）

2. 跟滚动有关联，因为是虚拟树，滚动后这些节点就被删除了，滚回来又会被重新创建，当重新创建AltData的时候就要考虑到重新执行一次遍历全部父节点（又有性能问题）

总结一下就是，特别小的这个一个，但需要抠很多时间，但我没有时间去抠
因为一堆功能还没做出来，没有这么细节的时间了

等3-4个月以后，我估计就没啥事可做了，也就有时间去抠这个细节了

**Comment by jkqxl** [comment]
@liupan1890 

> 还是要提一下关于间隔的问题

其实建议，将有关间隔的 PC与平板 设置分开，因为很难找到一个合适的尺度，既满足PC，同时又满足平板。可以设置这样一个开关，开启（作用，增大文件夹大小、间隔，适应平板），关闭即为PC原版。
文件夹树的功能是为了快速定位文件夹，如果文件夹的大小、间隔设置的较大，那么在你一眼看去就无法快速定位文件夹，并排文件夹又多，你还得多看几眼重复定位。当然，多层文件无法快速定位，也与我下面讲的多层文件结构显示不清楚有关

> 网盘地址功能,下拉和网盘分开

使用 回退按钮，只能回退临近的上层文件夹。网盘地址的功能，在目前不是主要用来查看文件地址，而是用来回退 上上上等层级 的文件夹。
但当我要通过网盘地址回退到 根部目录-网盘，我点击了 网盘，但弹出的却是 网盘地址的下拉列表，没有达到我的目的，造成操作浪费。网盘类似我的电脑，现在**无法再 点击网盘-回退**，应该将 点击网盘 之后的操作，还原成v9版，但为了保留 网盘地址的下拉列表功能，所以我才说要将两个功能分开。**点击或鼠标移动到上面之后的下拉列表，那就是另一个问题了。**

> 建议，将文件夹树的文件夹背景改成，鼠标所在文件的所在列，并且选择明显的区别颜色

这个确实是我的表达失误，写的东西多，有时候脑海里想的是这样，写就成了另一个样子
在鼠标放到文件夹上去时（未选中）或选中文件夹，显示如图红色框宽度的背景。
![c](https://user-images.githubusercontent.com/72729140/140048071-d01a77ce-f05c-46ab-800e-cd86d9bfa0b3.png)

> 不能折叠上层文件夹，影响到映射1的使用

1. 一个是由于使用习惯问题：为了在视觉上可以 清晰、快速定位到 所需文件（防止眼花缭乱），经常习惯性只保留一个折叠展开列，因此需要折叠该文件的上层文件。
2. 使用过程中的 舒适、丝滑：本来一步就可以到位，为什么还要画蛇添足的增加一步，在我使用过的所有 文件系统，没有一个是不可以一步直接 折叠上层文件夹的。
3. 我也不明白，为什么 左侧文件树 要一直显示 被选中的文件夹，尤其是当我已经**不需要它显示**的时候。v9版，折叠后再展开，也不影响它显示啊

**Comment by liupan1890** [comment]
>其实建议，将有关间隔的 PC与平板 设置分开

确实可以这样做，但现在，设置里已经有28个设置项了。一个网盘，主要就是上下传，28个设置项？v1.6只有6个设置项
为了这么简单的东西，不值得增加一个设置项。因为差的没多少（高700像素时 2.9===25--2.10===21）
![无标题](https://user-images.githubusercontent.com/67817756/140053288-69302737-f4ee-4ec3-969b-962b7d61e0c4.png)

>如果文件夹的大小、间隔设置的较大，那么在你一眼看去就无法快速定位文件夹

我感觉v2.9间隔太小反而不容易看清文件夹名，需要认真看文字
如果想要多显示几个文件夹，你应该把窗口拉的高一点

**Comment by liupan1890** [comment]
>网盘地址功能,下拉和网盘分开

下个版本分开

>在鼠标放到文件夹上去时（未选中）或选中文件夹，显示如图红色框宽度的背景

下个版本，已经改了

**Comment by jkqxl** [comment]
@liupan1890 
其它关于左侧文件夹树发现的问题

1. 关于 左侧文件夹树，层级清晰显示的问题：v9版比起v10版，要好很多，与@iD2073所发图片，效果类似 。如图所示
![a1](https://user-images.githubusercontent.com/72729140/140052406-672b075e-e0e8-413a-bd17-82fbcf6f79a7.png)
![a2](https://user-images.githubusercontent.com/72729140/140053006-cec30ec9-6166-4585-bc96-75726123e577.png)

2.关于 文件夹树的网盘折叠无效
收藏、回收站、网盘所在显示的折叠级别，没什么用，如果取消，并整体将文件树往左移，还可以节省空间
![d](https://user-images.githubusercontent.com/72729140/140053419-61a7fc48-eab8-4787-8fa5-c2bd15aa5261.png)

**最后，关于临时加载、全部加载导致的卡顿（点击停顿1s左右）的解决办法，猜想**
全部加载在有大量文件夹时会卡顿，临时加载不会在有大量文件夹时卡顿，但在加载任何文件都可能出现轻微卡顿，这是个什么问题呢，其实是类似游戏、网页的缓存问题
**我的建议是，分级缓存（级，是指文件夹树的层级），先缓存2个级别（1级、2级），到点击打开第1级文件夹的同时，再缓存2个级别（3级、4级），以此类推，具体缓存几个级别待测试**

**Comment by jkqxl** [comment]
> 其实建议，将有关间隔的 PC与平板 设置分开

相信我，随着版本更新，设置项还要增多，也不差这一个。没人会讨厌设置项变多，如果讨厌，那选默认设置即可。如果因为设置项太多而放弃使用软件，那也只是默认设置的问题。

**Comment by liupan1890** [comment]
>不能折叠上层文件夹

其实这个完全是我的个人习惯，针对这个问题我需要更多人的反馈，看大家都是怎么想的

#

光说我自己啊，在v2.9里是可以折叠的，如下图
![无标题](https://user-images.githubusercontent.com/67817756/140055026-a5838411-b52f-421d-897d-a9dbc0e5c202.png)

折叠了，然后我就不知道UPLOADTEST-副本55这个文件夹在哪了
（可以通过右侧顶部路径看出来，也可以点击刷新让他显示，也可以。。。。。）

但是，我什么也不点，什么也不看，
### 我只看左侧树，我不知道UPLOADTEST-副本55的父级路径是哪一个
如果我不看右侧顶部路径的话（因为有时候文件夹名较长/层级较深/窗口较窄  顶部路径都是...）
我只能凭记忆，或者一个一个的展开试，最终才能知道UPLOADTEST-副本55是在哪个文件夹下面（怎么展开）

这让我很苦恼，因为我的网盘里文件夹特别多，（大概3万多个文件夹）

因为这个，我在v2.10里就强制父级不可收缩，这样不论何时，我只需要滚动一下左侧树，就肯定能看到当前选择的文件夹的完整的展开路径

然后根据这个去继续操作

# 

最终就是，可能我自己的习惯不能代表大家，我需要更多人的反馈去参考

**Comment by iD2073** [comment]
其实我也觉得三角的那个比大于号的那个好看，直观还不容易搞错，本人建议指代表个人观点，改不改都很好已经很满足了

**Comment by iD2073** [comment]
我建议点刷新不折叠，比如可以双击
![image](https://user-images.githubusercontent.com/87513821/140056643-63bddf7d-20de-46a7-984c-91e6ca37d764.png)按钮折叠，我觉得这样比较好，刚开始可能很多人不知道，做个说明自然就都知道了

**Comment by liupan1890** [comment]
那我下次换回三角（只换图标，不换联线，因为连线涉及改动的居多，巨麻烦）

刷新自动折叠，是之前有人强烈跟我提的

**Comment by iD2073** [comment]
建议，新建时间文件夹，能再加个参数，，比如可以新建   2021-11-03 001     再点新建时间文件夹就自动 2021-11-03 002  ……  后面以需要形式展示，时间形式也要保留，给个设置的参数让用户自己去设置就好，

**Comment by iD2073** [comment]
> 那我下次换回三角（只换图标，不换联线，因为连线涉及改动的居多，巨麻烦）
> 
> 刷新自动折叠，是之前有人强烈跟我提的

其实还是原来的那个线和三角计较好，不改就不改吧，已经很不错了，辛苦小哥

**Comment by iD2073** [comment]
> > 不能折叠上层文件夹
> 
> 其实这个完全是我的个人习惯，针对这个问题我需要更多人的反馈，看大家都是怎么想的
> 
> 光说我自己啊，在v2.9里是可以折叠的，如下图 ![无标题](https://user-images.githubusercontent.com/67817756/140055026-a5838411-b52f-421d-897d-a9dbc0e5c202.png)
> 
> 折叠了，然后我就不知道UPLOADTEST-副本55这个文件夹在哪了 （可以通过右侧顶部路径看出来，也可以点击刷新让他显示，也可以。。。。。）
> 
> 但是，我什么也不点，什么也不看，
> 
> ### 我只看左侧树，我不知道UPLOADTEST-副本55的父级路径是哪一个（或者说我不能直接看到右侧的文件的完整层级）
> 如果我不看右侧顶部路径的话（因为有时候文件夹名较长/层级较深/窗口较窄 顶部路径都是...） 我只能凭记忆，或者一个一个的展开试，最终才能知道UPLOADTEST-副本55是在哪个文件夹下面（怎么展开）
> 
> 这让我很苦恼，因为我的网盘里文件夹特别多，（大概3万多个文件夹）
> 
> 因为这个，我在v2.10里就强制父级不可收缩，这样不论何时，我只需要滚动一下左侧树，就肯定能看到当前选择的文件夹的完整的展开路径
> 
> 然后根据这个去继续操作
> 
> 最终就是，可能我自己的习惯不能代表大家，我需要更多人的反馈去参考

如果折叠，应该是所在的目录不折叠，其他无关的目录折叠起来才对

**Comment by liupan1890** [comment]
>如果折叠，应该是所在的目录不折叠，其他无关的目录折叠起来才对

现在就是这样子的，但jkqxl 说的是所在目录问什么不能折叠，他需要能折叠

**Comment by iD2073** [comment]
那就众口难调了，有点不和逻辑

**Comment by iD2073** [comment]
> 建议，新建时间文件夹，能再加个参数，，比如可以新建 2021-11-03 001 再点新建时间文件夹就自动 2021-11-03 002 …… 后面以序列号形式展示，时间形式也要保留，给个设置的参数让用户自己去设置就好，
> 
> 比如：yyyy-mm-dd ### #代表数字，几位代表几位数，这样很方便，
> 
> > 新建议最好新开issue，有时候回复我看不到。
> 
> 我明白你的意思，自动增加的数字（格式不重要），关键是数字的起始/重置 比如你在"day1"里面需要创建2021-11-03 001,2021-11-03 002.2021-11-03 003 然后你在"day2"里面需要创建2021-11-03 001,2021-11-03 002.2021-11-03 003（这个时候就需要把数字重置重新从1开始） 然后你在"day2"里面需要创建2021-11-03 005,2021-11-03 006.2021-11-03 007（这个时候就需要把数字起使变成从5开始）
> 
> 然后。。。可能在不同的文件夹创建需要连续 在"day1"里面需要创建2021-11-03 001,2021-11-03 002.2021-11-03 003 在"day2"里面需要创建2021-11-03 004
> 
> 然后。。。可能在不同的文件夹创建需要重新开始 在"day1"里面需要创建2021-11-03 001,2021-11-03 002.2021-11-03 003 在"day2"里面需要创建2021-11-03 001
> 
> 然后。。。可能在不同的文件夹创建需要不同的长度 在"day1"里面需要创建2021-11-03 001,2021-11-03 002.2021-11-03 003 在"day2"里面需要创建2021-11-03 00001
> 
> 明白我的意思吧，就是情况多种多样，并不是简单的 设置一个规则“YYYY-MM-DD NUM”就行了，还需要好几个配合的设置（重置按钮/起始数字输入框/数字长度输入框/不同文件夹是否累计的勾选）
> 
> 就是不考虑那么多的情况，最起码重置按钮必须有吧？不能一直涨
> 
> 整这么复杂的设置，仅仅是为了自动增加数字，就不划算了（学习成本高）

不需要，一个日期不管从哪个文件夹里新建都自动延续，这个不用管，我也理解你的意思，那样太麻烦

**Comment by liupan1890** [comment]
好

**Comment by iD2073** [comment]
我刚才测试一下在阿里云盘里一直新建文件夹，还真不支持连续新建，在和彩云里是可以连续新建文件夹并自动加上序号的，其实日期+序号就是相当于把原来的新建+序号中的新建替换成日期了，这个应该是能实现的，和彩云是自动1、2、3、4……的新建，百度网盘的是，新建文件夹后加完整日期和时间，

**Comment by jkqxl** [comment]
> 不能折叠上层文件夹

网盘的各个功能就应该是互补的，重复性功能没多大意义。
网盘网址就是为了查看文件地址，那对于文件地址太长可以增加 鼠标移动到地址上 展开显示地址的功能，或者层级太多就展开显示，总之应该在地址上面想办法，而不是修改文件树的该功能
如果非要在 文件树显示 已经选中的文件地址，那可以 像选中文件那样增加的上层文件的背景，这样只要不重新选中其它文件，就能直接找到该文件的上层文件如图
![Snipaste_2021-11-03_20-42-20](https://user-images.githubusercontent.com/72729140/140061954-cc951078-5bac-499c-838f-826908c6987c.png)

> 那就众口难调了，有点不和逻辑

我的使用习惯是与windows文件夹系统一致的，而你们是要修改该习惯

**Comment by liupan1890** [comment]
>网盘网址就是为了查看文件地址

![无标题](https://user-images.githubusercontent.com/67817756/140455325-47d3f658-d02f-4410-b3c7-2c5be630835b.png)

有时候路径确实没有作用

>那对于文件地址太长可以增加 鼠标移动到地址上 展开显示地址的功能

能在左边一眼看到，为什么要移动一下鼠标？太麻烦了啊


>如果非要在 文件树显示 已经选中的文件地址，那可以 像选中文件那样增加的上层文件的背景

会给用户意识上造成混乱，收缩后，因为1 2 是蓝色背景的，会让人误认为当前选中的是1 2 （实际上是 1 2--3--1,选中的是1）


展开就先这样吧，实施效果，如果有很多人都在反馈不方便，那就改回去。
刚刚改成这样，总要看看大家的反馈是怎么样的


是更容易识别了，还是操做更不方便了
有的时候就是这样啊，不能全占，只是看哪方面更优

而优不优也是实际摸索出来的，不是主观上想象的，总要试错的

**Comment by iD2073** [comment]
我知道系统的资源管理器那个目录树路径是不跟随的，这个和那位网友说的一样，但是这个微软的事，我比较反感不跟随，因为容易找不到自己所在的文件夹在哪，虽然地址栏也能看到，如果不跟随，观察同级的其他目录就不直观了，因为这个所以我比较热衷于Directory Opus的原因，因为它就是跟随的，非常方便，日常能用Directory Opus的基本不用系统自带的管理器，太烂了，，，
我个人观点还是希望保留跟随目录自动展开，

**Comment by liupan1890** [comment]
在v2.11.07里，修改了展开图标，分开了网盘和下拉，增加了自动清理回收站设置，修改了选中行的背景，修改了刷新按钮不折叠(增加了顶部折叠按钮)
