### ISSUE TITLE
可以同时运行两个小白杨吗？

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#347]
两个账号，有些视频大同小异，想进行播放比对，官方的客户端播放视频实在是太渣了，也不能加载字幕。

所有想同时开两个小白杨。

**Comment by jkqxl** [comment]
@hummersyk c

旧版如Win v2.9.24，应该是可以加载外挂字幕的（之前看过一个帖子，讨论过这个问题），播放都是原画质，渣不渣的问题

新版Win v2.10.31windows可以加载多种播放器如Potplayer，也没这个问题

其它，字幕要想加载，字幕名称必须与对应视频 一样

**Comment by liupan1890** [comment]
不能的

因为小白羊使用的是electron，也就是浏览器，用到了内置的websql数据库，这个数据库经测试对多开支持的不行，在多开情况下频繁报错锁死

所以小白羊并不能双开。不过有一些沙盒软件，可以对程序多开
另外像vm虚拟机的unity模式也能达到多开的效果

**Comment by 236507** [comment]
切换账户不影响播放呀，如果只是对比视频把播放器设置成多开就好了
