### ISSUE TITLE
图标错误

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#348]
APK文件识别成ZIP了
![QQ截图20211101211551](https://user-images.githubusercontent.com/83964337/139677546-c5f3258e-cecc-4629-a103-5279467783fb.png)

**Comment by rapmq0** [comment]
还有BAT文件的图标是TXT

**Comment by liupan1890** [comment]
当前识别是根据阿里的mime去匹配的

apk本来就是zip，因为没有专门找apk的图标。如果不显示zip，那就需要显示灰色的文件图标
但是，你把.apk，改成.zip是可以在线解压的。要不我改成灰色的文件图标？

bat的图标是txt
这个是对的，因为可以在线预览的文本类文件都是txt图标，比如ini,c,js,css
是为了强调这个文件可以在线预览

**Comment by liupan1890** [comment]
我已经更新了apk/txt/iso/exe/torrent的图标，下个版本会修正此问题

**Comment by vxbmtu94516** [comment]
阿里云盘网页版识别的图标是压缩包
![image](https://user-images.githubusercontent.com/89058555/140296336-e6fc614e-2bed-4710-8175-cad70e14d86a.png)

小白羊却只有一个识别出来了
![image](https://user-images.githubusercontent.com/89058555/140296512-652b7125-d758-4792-ac1e-aa4c608d27c5.png)

**Comment by liupan1890** [comment]
apk的图标问题，已经在v2.11.07里修复
