### ISSUE TITLE
大家是否存在显示已经上传完毕，但是关闭程序重新打开后发现上传列表中还有文件？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#349]
上传文件数量有点多，大家是否存在显示已经上传完毕，但是关闭程序重新打开后发现上传列表中还有文件？

**Comment by ybbluesky** [comment]
刚才确认，此bug的确存在

**Comment by liupan1890** [comment]
1. 是上传完立即退出？还是等一会才退出？
2. 退出前，上传列表是空的吗？
3. 上传文件多少？会触发此BUG？
4. 少量文件上传时是否会触发？
5. 那么重新打开后，发现**上传中**列表中还有文件，留意一下网盘里，是已经存在此文件了（只是上传记录没删除）？还是根本没有上传这些文件？

**Comment by ybbluesky** [comment]
是上传较长时间后退出的，退出前上传列表已经为空，上传文件量不一定，最开始上传了近20万个文件后重新打开列表中有1500个左右又存在，再次上传完后又退出再显示有约50个，上传少量文件没有试过是否触发此现象，没有查询网盘里是否已经有了文件，没有仔细注意文件是否有关联，也许可能是上传记录没有删除

**Comment by ybbluesky** [comment]
是上传较长时间后退出的，退出前上传列表已经为空，上传文件量不一定，最开始上传了近20万个文件后重新打开列表中有1500个左右又存在，再次上传完后又退出再显示有约50个，上传少量文件没有试过是否触发此现象，没有查询网盘里是否已经有了文件，没有仔细注意文件是否有关联，也许可能是上传记录没有删除

**Comment by liupan1890** [comment]
说一下你的操作步骤吧

我下午测试了一次，

创建smalltxt文件夹，在这个文件夹里创建了40万个txt文件（内容是随机生成的，超级小的，txt文件）
直接拖动smalltxt文件夹到网盘根目录

顺利的上传完以后，等了10多分钟（不重要），然后退出，然后重启，但是上传中列表是空的，已上传完列表是5000条（自动清理），我没能复现这个BUG

是不是你的包含了很多文件夹呢？具体的操作步骤是什么？
是一次性拖选20万个文件（没有文件夹）
还是拖动一个文件夹，文件夹里包含大量文件夹和大量文件呢？


按说上传中已经是空的，重启也应该是空的啊

**Comment by ybbluesky** [comment]
我的目录结构A-B-C-D这种的，上传的是a目录，里面的自动上传的，以后如果再碰到这种情况再反馈吧，的确可能不好复现

**Comment by liupan1890** [comment]
好吧，我稍后再试试多级嵌套的情况

**Comment by liupan1890** [comment]
那个啥，我找到问题了，是因为主键冲突

当上传文件时，会给这个文件一个ID

这个ID是根据文件信息算出来的（文件名/大小/路径/上传位置等等）
算出来的是一个伪随机的字符串，为了减少数据库体积，这个字符串不是很长

结果当有10万个以上的文件在上传中列表里，就有大概万6的概率冲突（具体和文件名+路径有关系）

总之，在文件数量超过10万时会有较小的概率，因为主键重复的冲突导致此BUG（概率的问题）

下个版本会增加主键长度和计算方式，避免冲突

**Comment by ybbluesky** [comment]
> 那个啥，我找到问题了，是因为主键冲突
> 
> 当上传文件时，会给这个文件一个ID
> 
> 这个ID是根据文件信息算出来的（文件名/大小/路径/上传位置等等） 算出来的是一个伪随机的字符串，为了减少数据库体积，这个字符串不是很长
> 
> 结果当有10万个以上的文件在上传中列表里，就有大概万6的概率冲突（具体和文件名+路径有关系）
> 
> 总之，在文件数量超过10万时会有较小的概率，因为主键重复的冲突导致此BUG（概率的问题）
> 
> 下个版本会增加主键长度和计算方式，避免冲突
> 
> 这个BUG也跟用户操作方式有关系
> 
> 比如你先上传1万，然后再上传1万，就很难出现
> 
> 比如你一次上传10万，可能就会碰到（跟文件名+路径）有关，
> 
> 所以藏得比较深啊

是否会有文件漏掉上传的情况呀？

**Comment by liupan1890** [comment]
我测试的时候，文件是全部上传上去了，这个BUG会导致重复的文件（第二个文件）上传时，重复的向数据库里写入上传记录，最终导致重启后会残留。

但因为只有在文件超级多的时候，才容易碰撞冲突，所以具体是否会真的漏文件，我也不敢保证

**Comment by liupan1890** [comment]
已经在v2.11.07里修正了此错误

**Comment by ybbluesky** [comment]
> 已经在v2.11.07里修正了此错误

问题仍然存在
