### ISSUE TITLE
上传文件进度能不能看到

### ISSUE THREAD

**Issue by jayleejaylee** [liupan1890/aliyunpan#35]

**Comment by jayleejaylee** [comment]
找到了 ，在下载 tab 页下

**Comment by jayleejaylee** [comment]
请问有断点续传功能吗

**Comment by liupan1890** [comment]
下载：有断点续传功能

上传：
当你上传文件时，没有点击彻底退出的情况下，有断点续传功能。但是因为没测试出阿里云盘上传链接的有效期，所以当前是设置为4小时内恢复上传会断点续传。

举例子：
1：00 你开始上传XXX.rar (15GB)
2：00 你点击暂停上传 （上传了5GB）
3：30 你点击这个文件的上传按钮（或者开始全部按钮）恢复上传，此时会断点续传
4：00 你点击暂停上传 （上传了8GB）
4：50 你点击这个文件的上传按钮（或者开始全部按钮）恢复上传，此时会断点续传（只要是5点前恢复，都会尝试断点续传）
结果一：
10：00 上传到了8GB，你点击暂停上传。11：00你点击恢复，此时不会断点，会重新开始
结果二：
10：00上传到了8GB，12：00上传到了10GB

总之：有断点续传，只要程序不退出。如果没能正确开始断点续传，一般是因为上传URL超期失效了，此时无法断点续传了

**Comment by jayleejaylee** [comment]
Ok 懂了  谢谢 ，软件牛逼，阿里原版的真的是垃圾，传文件数量一多就卡死
