### ISSUE TITLE
问一下“重复文件扫描”进度

### ISSUE THREAD

**Issue by vtrayy** [liupan1890/aliyunpan#351]
因为两个月的官方分享活动，存了不少文件，尤其是几T的电子书，感觉有不少重复，问一下这个功能什么时候出来

**Comment by liuyun198833** [comment]
确实，除电子书外还有很多电影有重复，一直也在等重复文件扫描功能~

**Comment by ybbluesky** [comment]
> 因为两个月的官方分享活动，存了不少文件，尤其是几T的电子书，感觉有不少重复，问一下这个功能什么时候出来

希望能分享一下

**Comment by liupan1890** [comment]
呃，因为手头一堆活， 这个“重复文件扫描”我还没有安排计划，所以我也说不上来具体的日子
