### ISSUE TITLE
窗口播放视频是正常颜色 开全屏之后颜色就变了

### ISSUE THREAD

**Issue by zhwazz** [liupan1890/aliyunpan#352]
开全屏之后颜色就变了 截图去又是正常颜色

**Comment by zhwazz** [comment]
用potpalyer播放全屏正常

**Comment by liupan1890** [comment]
呃，抱歉，

因为播放是调用MPV播放器播放，
所以你说的这个是MPV播放器的问题，并不是小白羊的问题，所以无法修正
（如果是只有这个视频才这个样，那跟视频文件有关系--或者说MPV对这个视频的解析有问题）
（如果是全部视频都这样，那说明是MPV对你电脑的硬件支持有问题）

使用Potplayer正常，那就用Potplayer播放吧，自v2.10开始，已经支持很多播放器，可以用自己习惯的

**Comment by zhwazz** [comment]
> 呃，抱歉，
> 
> 因为播放是调用MPV播放器播放， 所以你说的这个是MPV播放器的问题，并不是小白羊的问题，所以无法修正 （如果是只有这个视频才这个样，那跟视频文件有关系--或者说MPV对这个视频的解析有问题） （如果是全部视频都这样，那说明是MPV对你电脑的硬件支持有问题）
> 
> 使用Potplayer正常，那就用Potplayer播放吧，自v2.10开始，已经支持很多播放器，可以用自己习惯的

谢谢大佬

**Comment by zhwazz** [comment]
显卡驱动问题
