### ISSUE TITLE
关于“文件夹置顶”有个大胆的想法

### ISSUE THREAD

**Issue by kudoushinichi6671** [liupan1890/aliyunpan#353]
不知道我所想的这个想法可不可行，就是文件夹可以设置置顶到第一个、第二个、第三个……
这样主要是想着有些文件夹在末尾或者中间不想每次浏览文件夹都往下面找，有了置顶会感觉好些，
当然同理置顶文件也可以考虑下(文件置顶应该也有需求，要是觉得没必要就不用加了)

**Comment by liupan1890** [comment]
可以有，以后会安排

**Comment by KHLFYY** [comment]
> 文件夹可以设置置顶到第一个、第二个、第三个

@kudoushinichi6671 

这个我是把文件夹前面加上01 02这种，然后按名称排序，文件夹就排好了。

![image](https://user-images.githubusercontent.com/76054116/140336351-2443381f-ecae-4d0f-b6c6-85f151052242.png)


当然这个有一些场景可能不能用（比如文件夹名不能改动）

目前我绝对这个方法还是挺好用

希望对你有所帮助

**Comment by kudoushinichi6671** [comment]
> 可以有，以后会安排

好的，期待

**Comment by kudoushinichi6671** [comment]
> > 文件夹可以设置置顶到第一个、第二个、第三个
> 
> @kudoushinichi6671
> 
> 这个我是把文件夹前面加上01 02这种，然后按名称排序，文件夹就排好了。
> 
> ![image](https://user-images.githubusercontent.com/76054116/140336351-2443381f-ecae-4d0f-b6c6-85f151052242.png)
> 
> 当然这个有一些场景可能不能用（比如文件夹名不能改动）
> 
> 目前我绝对这个方法还是挺好用
> 
> 希望对你有所帮助
多谢，这样挺好的，我原先想着是收藏然后再去收藏里点，不过小白羊收藏点文件夹的时候展开反应了很久

**Comment by liupan1890** [comment]
在v2.11.14里已经支持对文件/文件夹置顶了，
点击收藏反应很久，应该是只有第一次点击才慢（加载），之后点击会很快，只有涉及到修改文件名/收藏文件/取消收藏文件之类操作时会需要重新刷新慢

如果收藏功能有问题请开新的issue
