### ISSUE TITLE
关于文件查重的假想

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#354]
希望能实现：
1、盘内文件的查重。
2、导入分享的查重，与盘内文件查重，可选择只导入不重复的文件或者全部文件。
3、盘内文件与本地指定文件夹文件的查重。
4、更高级的话，在导入分享时的查重，同时查询盘内文件和本地指定文件夹文件是否重复。

**Comment by liupan1890** [comment]
当前还没做到文件查重功能

所以先不讨论，等以后做到了再说，你说的我会先记下来
