### ISSUE TITLE
占用 CPU 异常高，即使退出后台也无效，必须结束进程。时常出现。

### ISSUE THREAD

**Issue by vickychinghk** [liupan1890/aliyunpan#355]
![image](https://user-images.githubusercontent.com/63624554/140269369-e76585b3-3278-420a-bdc0-bac364c27ca9.png)

同时还会出现 多个 alidrive 进程的情况，有时会每个进程占用10%cpu，然后把电脑干废。
![Snipaste_2021-11-04_14-43-59](https://user-images.githubusercontent.com/63624554/140269622-c77b469b-3b5f-45f0-9e2a-9cd65d716c5b.png)

**Comment by liupan1890** [comment]
请问是哪一个版本？v2.10.31?

>出现 多个 alidrive 进程的情况

我数了一下，是9个，
v2.10.x 正常应该是5-6个
v2.9.x 正常应该是6-7个
v2.8.x 正常应该是6-8个

出现9个，一般是，
第一次运行小白羊比如出错了卡死了，然后你手动结束进程，然后重新打开小白羊
因为你手动结束进程时，结束的不对，所以第一个运行的小白羊没有完全退出（残留了1-2个窗口）
结束的不对--应该在每个aDrive进程上都结束一遍（其中一个是主进程，结束了他其他的都会自动结束）

如果不是这种情况，而是一打开就是9个进程，那是不正常的

不管你是用的哪一个版本，
v2.9会自动缓存文件夹体积，18%的CPU不算高，也不是一直18%，会持续一段时间，跟你网盘里文件夹数量/文件数量有关

v2.10也会自动缓存文件夹体积，但比v2.9资源占用降低了非常多，一般不会出现长时间超过10%的情况，持续时间同样跟你网盘里文件夹数量/文件数量有关

你可以尝试，在设置里，关闭统计文件夹体积功能，就不会这样了

**Comment by liupan1890** [comment]
补充一句，v2.8  v2.10 没事

v2.9.24有一个BUG，用户登陆状态失效后，可能会触发一个隐藏的BUG，会导致CPU占用很高，并持续很长时间（跟你网盘里文件夹数量/文件数量有关）

**Comment by vickychinghk** [comment]
> v2.9.24有一个BUG

确实是2.9.24。。。 我看最新好像没有 2.10？

**Comment by liupan1890** [comment]
https://github.com/liupan1890/aliyunpan/issues/342

周日会发v2.11.07

**Comment by vickychinghk** [comment]
> #342
> 
> 周日会发v2.11.07

没有看到 TAT

**Comment by liupan1890** [comment]
我想，在v2.11.07及以后的版本，已经修正了v2.9里性能问题，所以关闭此问题了
