### ISSUE TITLE
v2.10.31文件下载功能有bug

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#356]
“文件下载保存位置”，如果选择某个盘的根目录，比如 E: ，显示下载成功，下载记录里也有，但实际上E:上并没有文件。
如果选择的是子目录，比如 E:\xxxx ，则没有问题。

**Comment by ybbluesky** [comment]
我下载目录设置为G盘，没有此现象

**Comment by ybbluesky** [comment]
> 我下载目录设置为G盘，没有此现象，是不是自己硬盘权限设置问题？

**Comment by liupan1890** [comment]
我去试一下

**Comment by liupan1890** [comment]
确实是，我一选择文件夹我就知道了，是错误的去掉了结尾的斜杠

下个版本修正

**Comment by liupan1890** [comment]
v2.11.07已修正此错误
