### ISSUE TITLE
不知道大家发现一个秘密没有

### ISSUE THREAD

**Issue by 957057** [liupan1890/aliyunpan#358]
小白羊可以看阿里云网盘里显示封禁的视频

**Comment by liupan1890** [comment]
1. 不论哪个版本，都可以在设置里，选择 优先转码视频 ，然后可以在线预览 某些视频
2.v2.10.31 不用管设置，会自动识别出需要使用 优先转码的视频

**Comment by hummersyk** [comment]
> 小白羊可以看阿里云网盘里显示封禁的视频

封禁的视频好像只是在手机端不能播放吧，PC端是可以的。

**Comment by QiTianzu** [comment]
> > 小白羊可以看阿里云网盘里显示封禁的视频
> 
> 封禁的视频好像只是在手机端不能播放吧，PC端是可以的。

手机端2.2.3.3之后的版本才不能播放
