### ISSUE TITLE
请问可以添加下载完成自动关机的功能吗？

### ISSUE THREAD

**Issue by Yatiru** [liupan1890/aliyunpan#359]
如题，不知道可以吗

**Comment by liupan1890** [comment]
程序上当然可以实现，但实际上，尚未打算增加此功能

win/mac 自动关机我回了，但linux我还不会，所以等以后有时间了，我查查资料，再做这个功能吧

**Comment by Yatiru** [comment]
> 程序上当然可以实现，但实际上，尚未打算增加此功能
> 
> win/mac 自动关机我回了，但linux我还不会，所以等以后有时间了，我查查资料，再做这个功能吧

谢谢大佬，期待新的版本。
