### ISSUE TITLE
不支持Linux系统吗？

### ISSUE THREAD

**Issue by mymine** [liupan1890/aliyunpan#36]
不支持Linux系统吗？支持下国产Linux系统吧

**Comment by liupan1890** [comment]
说一下系统名，我去适配看看

**Comment by mymine** [comment]
统信deepin和uos。

**Comment by mymine** [comment]
> 说一下系统名，我去适配看看
统信deepin和uos。

**Comment by liupan1890** [comment]
嗯，收到，我有时间时会抓紧跟进的！耐心等一下

**Comment by mymine** [comment]
> 嗯，收到，我有时间时会抓紧跟进的！耐心等一下

好的

**Comment by pcy190** [comment]
能支持一下Ubuntu就更好了

**Comment by liupan1890** [comment]
说一下进度啊

我前几天就试过Ubuntu 20.04了，能够打包编译运行，就是效果不行
如下图，最基本的Flutter示例程序，Flutter最新版v2.2.1 (现在是2.2.2了)，顶部菜单时隐时现，基本上就是丢失的，拖动窗口残影严重也就算了，拖动完不动的时候，界面渲染的都不完整，丢失了很多。这样的体验，发出来就是挨骂的。等我有时间再试试其他的系统

![linux](https://user-images.githubusercontent.com/67817756/122859445-9ffd0080-d34e-11eb-80fa-58d0b7df291c.gif)

**Comment by mymine** [comment]
好的

**Comment by Borber** [comment]
大佬大佬 现在不是换 electron 了吗？ 应该对linux 支持好很多了吧 archlinux 怒求支持！ 爱你

**Comment by jemyzhang** [comment]
@liupan1890 能告知一下ubuntu下的编译方法吗？

**Comment by Borber** [comment]
> @liupan1890 能告知一下ubuntu下的编译方法吗？

等 electron版本吧 应该就直接完美支持了

**Comment by jemyzhang** [comment]
> > @liupan1890 能告知一下ubuntu下的编译方法吗？
> 
> 等 electron版本吧 应该就直接完美支持了

个人以为，electron太过于庞大，不如flutter吧

**Comment by Borber** [comment]
> > > @liupan1890 能告知一下ubuntu下的编译方法吗？
> > 
> > 
> > 等 electron版本吧 应该就直接完美支持了
> 
> 个人以为，electron太过于庞大，不如flutter吧

![image](https://user-images.githubusercontent.com/30563826/124693760-893fd780-df12-11eb-9284-2d6300bb3897.png)

作者已经开始转向 electron了 至于 他俩的对比  flutter 的 desktop 还在 beta， 现阶段没有electron稳定 很理解作者的决定 现阶段几十m的空间还是不缺的

**Comment by ViokingTung** [comment]
Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin

**Comment by ViokingTung** [comment]
> > > > @liupan1890 能告知一下ubuntu下的编译方法吗？
> > > 
> > > 
> > > 等 electron版本吧 应该就直接完美支持了
> > 
> > 
> > 个人以为，electron太过于庞大，不如flutter吧
> 
> ![image](https://user-images.githubusercontent.com/30563826/124693760-893fd780-df12-11eb-9284-2d6300bb3897.png)
> 
> 作者已经开始转向 electron了 至于 他俩的对比 flutter 的 desktop 还在 beta， 现阶段没有electron稳定 很理解作者的决定 现阶段几十m的空间还是不缺的

是啊，Electron已经成功了好多应用了，flutter还在完善版本

**Comment by 0x5c0f** [comment]
> Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin

我`fedroa`真的就不配参与么

**Comment by Borber** [comment]
> > Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin
> 
> 我`fedroa`真的就不配参与么

Arch yyds

**Comment by ViokingTung** [comment]
> > > Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin
> > 
> > 
> > 我`fedroa`真的就不配参与么
> 
> Arch yyds

Fedora卡的一批，用了一段时间之后就不用了，Arch系的用过manjaro，滚动更新滚挂了，话说回来，Linux桌面版肯定开发使用的居多，尤其深度学习的居多，这个Ubuntu虽然支持较好，但考虑到还有其他的国产软件的办公环境，我选择deepin！虽然也老出事故，emmmm

**Comment by Borber** [comment]
还好吧 我确实是 java 开发 推荐直接使用 arch 而非 manjaro （便捷的代价往往更大 我也使用过 深有体会） deepin
可能不太对我的审美 kde 我自己可以美化的很漂亮 以及 我只会使用 pacman 包管理 so...

ViokingTung ***@***.***> 于2021年7月13日周二 下午5:06写道：

**Comment by 0x5c0f** [comment]
> > > > Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin
> > > 
> > > 
> > > 我`fedroa`真的就不配参与么
> > 
> > 
> > Arch yyds
> 
> Fedora卡的一批，用了一段时间之后就不用了，Arch系的用过manjaro，滚动更新滚挂了，话说回来，Linux桌面版肯定开发使用的居多，尤其深度学习的居多，这个Ubuntu虽然支持较好，但考虑到还有其他的国产软件的办公环境，我选择deepin！虽然也老出事故，emmmm

卡的一批?   我用了快5年了,没发现卡过啊?

**Comment by Borber** [comment]
> > > > > Electron开发的话，可以打一个Linux的包，应该国内使用最多的发行版是Ubuntu和deepin
> > > > 
> > > > 
> > > > 我`fedroa`真的就不配参与么
> > > 
> > > 
> > > Arch yyds
> > 
> > 
> > Fedora卡的一批，用了一段时间之后就不用了，Arch系的用过manjaro，滚动更新滚挂了，话说回来，Linux桌面版肯定开发使用的居多，尤其深度学习的居多，这个Ubuntu虽然支持较好，但考虑到还有其他的国产软件的办公环境，我选择deepin！虽然也老出事故，emmmm
> 
> 卡的一批? 我用了快5年了,没发现卡过啊?

哇 肯定是大佬 我才用了 两三年

**Comment by 0x5c0f** [comment]
`fedora`作为`redhat`系列先行版，除了一些bug外，一切正常，也非常好用 (虽然我想切到`deepin`了), 快来加入`fedora`大军吧

**Comment by chenzaichun** [comment]
> @liupan1890 能告知一下ubuntu下的编译方法吗？

我简单编译了一下，然后可以正常运行主界面，但是 `下载` 和 `在线查看视频` 功能不能正常使用:

os version:

```
 cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

flutter version
```
 flutter --version
Flutter 2.2.3 • channel stable • git@github.com:flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

代码引用的是 `main` 分支 ` commit `a78f785d`

首先编译 `aliserer`:

```
go get
go build
```

完成后，会有 `aliserver` 的binary生成，可以运行。

```
 ./aliserver
Port: localhost:29385
```

然后编译 flutter 客户端, 进入 `alixby` 目录, 添加桌面支持

```sh
cd alixby
flutter create --platforms=windows,macos,linux
```

这里输出就省略了，这里有个文件路径大小写问题 (`lib/pagepan/PanFileList.dart b/alixby/lib/pagepan/PanFileList.dart`)，修复一下:

```diff
diff --git a/alixby/lib/pagepan/PanFileList.dart b/alixby/lib/pagepan/PanFileList.dart
index 0a457be8..36ea704b 100644
--- a/alixby/lib/pagepan/PanFileList.dart
+++ b/alixby/lib/pagepan/PanFileList.dart
@@ -4,7 +4,7 @@ import 'package:alixby/states/Global.dart';
 import 'package:alixby/utils/Loading.dart';
 import 'package:alixby/pagepan/ImageDialog.dart';
 import 'package:alixby/pagepan/TextDialog.dart';
-import 'package:alixby/pagepan/UnRarDialog.dart';
+import 'package:alixby/pagepan/UnrarDialog.dart';
 import 'package:alixby/utils/StringUtils.dart';
 import 'package:bot_toast/bot_toast.dart';
 import 'package:flutter/rendering.dart';
```

因为代码depends有没有启用 `sound-null-safety` 的情况，所以运行的时候暂时规避掉。

```sh
flutter run --no-sound-null-safety
```

这个时候能正常运行，使用app扫码登录了。

![image](https://user-images.githubusercontent.com/127616/126324641-3b77649f-bb4d-422e-921d-f0212c4cda74.png)

**Comment by chenzaichun** [comment]
> 说一下进度啊
> 
> 我前几天就试过Ubuntu 20.04了，能够打包编译运行，就是效果不行
> 如下图，最基本的Flutter示例程序，Flutter最新版v2.2.1 (现在是2.2.2了)，顶部菜单时隐时现，基本上就是丢失的，拖动窗口残影严重也就算了，拖动完不动的时候，界面渲染的都不完整，丢失了很多。这样的体验，发出来就是挨骂的。等我有时间再试试其他的系统
> 
> ![linux](https://user-images.githubusercontent.com/67817756/122859445-9ffd0080-d34e-11eb-80fa-58d0b7df291c.gif)

大佬是用的虚拟机吗？我这边没有感觉到明显的卡顿。

大佬方便的时候能将你适配好的linux版本代码push上来吗？

**Comment by Borber** [comment]
> > 说一下进度啊
> > 我前几天就试过Ubuntu 20.04了，能够打包编译运行，就是效果不行
> > 如下图，最基本的Flutter示例程序，Flutter最新版v2.2.1 (现在是2.2.2了)，顶部菜单时隐时现，基本上就是丢失的，拖动窗口残影严重也就算了，拖动完不动的时候，界面渲染的都不完整，丢失了很多。这样的体验，发出来就是挨骂的。等我有时间再试试其他的系统
> > ![linux](https://user-images.githubusercontent.com/67817756/122859445-9ffd0080-d34e-11eb-80fa-58d0b7df291c.gif)
> 
> 大佬是用的虚拟机吗？我这边没有感觉到明显的卡顿。
> 
> 大佬方便的时候能将你适配好的linux版本代码push上来吗？

后面就是electron了 不存在兼容性问题

**Comment by liupan1890** [comment]
非常抱歉，我一直没注意到这个issue的回复。


@chenzaichun

1.下载不能用
因为你没有启用aria2c进程，可以看一下windows版本里的aria2c.conf 这个配置文件，就知道端口/密码了。然后自己在启动的时候调用启动一个aria2c进程就可以了

再windows版我是c++里调用的启动，
在mac版我是/utils/darwin.go 里面的RunAria
在linux版，应该是调用utils/linux.go 里面的RunAria

2.在线播放不能用
linux特殊，需要自己手动安装mpv播放器  sudo apt install mpv


3.适配linux的代码
没有。。。因为我当初测试了一下基本的flutter示例发现不理想，就没继续了，
另外托盘菜单不同的linux的UI，使用的还不一样，我没怎么深入的研究啊，就胡乱一说，对不对的别纠结，gome/gtk 吧，别的linux用的什么UI我也没了解，总之不同的UI，需要分别去适配托盘菜单
因为flutter没有托盘菜单的概念，手机，没有电脑的任务栏

但是aliserver的代码，除了托盘菜单，也没有需要适配的地方了。剩余代码都是通用的，唯一需要注意的文件路径，也已经注意了。所以也不需要适配的代码了

4.我使用的虚拟机，因为我用不到linux，所以只能临时装一个虚拟机测试。
我也没用过mac，是字面上的意思，我没摸过mac。我摸过iphone/ipad 但没摸过苹果笔记本或苹果电脑或苹果一体机

**Comment by liupan1890** [comment]
然后是大家讨论的linux版本问题
1.我已经打包了通用的electron linux 64 版本，理论上大家都可以用（就是用的electron官方linux x64 官方是Ubuntu上打包的）
2.我已经发布了linux自定义系统的打包教程，不管你是什么linux，只要electron支持，你能找到对应的electron，那就可以自己打包了。打包就是复制几个文件，操作很简单
3.新版还支持远程Aria2下载，这样针对只想把文件下载到VPS/NAS/docker的人就更简单了，NAS上运行aria2c就行了

so 常用的系统electron都支持了

**Comment by 0x5c0f** [comment]
> 然后是大家讨论的linux版本问题
> 1.我已经打包了通用的electron linux 64 版本，理论上大家都可以用（就是用的electron官方linux x64 官方是Ubuntu上打包的）
> 2.我已经发布了linux自定义系统的打包教程，不管你是什么linux，只要electron支持，你能找到对应的electron，那就可以自己打包了。打包就是复制几个文件，操作很简单
> 3.新版还支持远程Aria2下载，这样针对只想把文件下载到VPS/NAS/docker的人就更简单了，NAS上运行aria2c就行了
> 
> so 常用的系统electron都支持了

已测试`v2.8.8`现有开放功能在`fedora 32`完美运行。

**Comment by cdz-bash** [comment]
> > 然后是大家讨论的linux版本问题
> > 1.我已经打包了通用的electron linux 64 版本，理论上大家都可以用（就是用的electron官方linux x64 官方是Ubuntu上打包的）
> > 2.我已经发布了linux自定义系统的打包教程，不管你是什么linux，只要electron支持，你能找到对应的electron，那就可以自己打包了。打包就是复制几个文件，操作很简单
> > 3.新版还支持远程Aria2下载，这样针对只想把文件下载到VPS/NAS/docker的人就更简单了，NAS上运行aria2c就行了
> > so 常用的系统electron都支持了
> 
> 已测试`v2.8.8`现有开放功能在`fedora 32`完美运行。

大佬，大约什么时候更新linux版本的
