### ISSUE TITLE
Mac OS 在线无法播放视频

### ISSUE THREAD

**Issue by faboxe** [liupan1890/aliyunpan#360]
点击网盘中的视频，格式为mp4跟mpv的，转圈结束后无任何反应
是需要将Mac版本升级到最新os系统才能解决吗？
另外我看可以使用iina的URL播放视频，请问应该如何操作？
谢谢
版本：v2.0.31
os:11.3.1 M1芯片

**Comment by liupan1890** [comment]
![iina](https://user-images.githubusercontent.com/67817756/140630376-1699f6ef-5cae-4626-97db-7aa2d2ceedee.gif)

**Comment by liupan1890** [comment]
这只是临时的过渡的方式，等以后针对mac适配后，就可以正常选择xxx.app了

**Comment by faboxe** [comment]
> 这只是临时的过渡的方式，等以后针对mac适配后，就可以正常选择xxx.app了

谢谢回复。我尝试了一下，发现显示iina出现‘意外退出’报错（但我本身是可以从启动台正常打开使用iina的），这种应该是属于app的证书问题吗？

**Comment by zronghui** [comment]
> > 这只是临时的过渡的方式，等以后针对mac适配后，就可以正常选择xxx.app了
> 
> 谢谢回复。我尝试了一下，发现显示iina出现‘意外退出’报错（但我本身是可以从启动台正常打开使用iina的），这种应该是属于app的证书问题吗？

我试了下，也不行。提示“无法打开文件或流”
此外，能不能把播放器的视频名设置成云盘里的文件名，而不是链接的形式。就像是 iina+ 里面实现的效果
![image](https://user-images.githubusercontent.com/15062201/140648398-f751b9de-6646-42e0-a53b-781e1ff25513.png)

iina+ 的效果：
![hUUYSRK](https://i.imgur.com/hUUYSRK.png)

**Comment by liupan1890** [comment]
1. 关于不能播放，这个问题我不知道是为什么，因为我不用mac，更没有m1，所以都是虚拟机安装的macos做测试。我的电脑是正常的（如上截图）

因为我的电脑正常，所以我也没办法遇到“不能播放”，遇不到，就没办法找原因。。。。死循环

2.等以后，恢复了视频雪碧图功能时，在顶部有复制下载链接的按钮，到时候可以点一下复制，然后在iina里自己粘贴打开。这个属于iina正常操作，不会出问题了

3.视频名称标题

部分视频文件，文件里面，自己带着标题信息，iina+可以读取出此标题信息显示。如果文件本身没有附带标题信息，就读不出来了。而iina不支持读取内置的标题。所以不显示

我也没办法让他显示，内置的mpv是通过命令，让他正常显示的

**Comment by liupan1890** [comment]
在v2.11.14里，已经更新了mac下对播放软件的支持

方式一：在设置里选择 IINA MKPlayer VLC 总有一个是可用的


方式二：在视频文件上，右键，详情，会显示雪碧图，在顶部，又复制m3u8 复制原始链接 按钮，点击复制后，找一个播放软件，把地址粘贴进去就能播放了
