### ISSUE TITLE
阿里云盘是否已限制连接数

### ISSUE THREAD

**Issue by sailing178** [liupan1890/aliyunpan#362]
小白杨16线程，IDM32线程均只能拉出4线程
![image](https://user-images.githubusercontent.com/89731041/140633980-9ac8ddc6-906c-440a-bd43-e564b80bbd18.png)

**Comment by Borber** [comment]
? 为啥关了 没有限制吗?

**Comment by sailing178** [comment]
> ? 为啥关了 没有限制吗?

clash中的开的全局，切换规则已恢复
