### ISSUE TITLE
呜呜呜大佬为什么插件我这边不能用啊

### ISSUE THREAD

**Issue by XNPP** [liupan1890/aliyunpan#364]
![`AG}31Z A036W %`E}T(1CF](https://user-images.githubusercontent.com/90998795/140729745-1f7bf4ff-e16e-4e70-8b5d-f10adb6d1340.png)
其实我也不知道是不是大家都是这样，**如有见解请指正QAQ**

**Comment by KHLFYY** [comment]
插件还没有完成

现在都不能用的

只是一个功能介绍而已

不要着急 作者在一个个写

**Comment by XNPP** [comment]
> 插件还没有完成
> 
> 现在都不能用的
> 
> 只是一个功能介绍
> 
> 不要着急作者在一个个写

谢谢，明白了qwq
