### ISSUE TITLE
压缩包能分享吗

### ISSUE THREAD

**Issue by cddehsy** [liupan1890/aliyunpan#365]
压缩包能分享吗

**Comment by liupan1890** [comment]
这个要问阿里云盘了

**Comment by aionyzq** [comment]
本来可以在小白羊客户端内自动加密上传，下载识别解密。但是容易被阿里整活，不值当。方法多的是，我们用户自己解决就行。

**Comment by liupan1890** [comment]
@aionyzq   这个以后会有的，不过，阿里以后早晚会开放压缩包的分享功能的，所以其实作用也不大
