### ISSUE TITLE
上传bug

### ISSUE THREAD

**Issue by xslh** [liupan1890/aliyunpan#367]
![2021-10-31 22-01-57 的屏幕截图](https://user-images.githubusercontent.com/13762136/141166621-bd351fee-da1f-4f8d-8f66-cdabb5e74874.png)
这是出错截屏。我分析这些文件应是linux中的链接文件

**Comment by liupan1890** [comment]
如果你是说“合并文件出错”这个报错

这个没事，

先说错误了：等一分钟会自动重新上传，或者你也可以自己手动选中后点击上传，立即重新开始上传

然后是报错“合并文件出错”
这个是阿里云盘的问题，阿里云盘的服务器，会偶发这个错误，

>阿里云盘使用的是阿里云PDS服务
正常的上传流程中，上传完文件后，需要合并一次。阿里云盘自己，偶发在合并时会返回404错误，最后提示合并文件失败
正常上讲，不应该有404错误，而是合并结果--合并成功/合并失败。但阿里云盘会偶发404找不到

>猜测原因是，正常的上传文件时，对于小文件，阿里云盘还有一个不需要合并的流程，既获取地址，上传，好了（没有合并）
这是小文件优化策略，但时阿里云盘没有正确的去处理这个情况，所以偶发会404

>参见 https://help.aliyun.com/document_detail/175888.html  小文件单分片上传


在下个版本里我已经修正为捕获这个错误后重试一次合并，能修正大部分这个错误，顺利合并文件

**Comment by liupan1890** [comment]
看到你用的是v2.10.31，，，推荐跟着发布及时更新v2.11.07，因为07里对百万级上传做了很多优化，想你一次性上传2.6万个文件，v2.11.07会更加流畅（我忘了是否在07里就已经增加了捕获这个错误后重试了，反正我本地版本v2.11.14是加了）

**Comment by 957057** [comment]
为什么这个不能创建秒传

**Comment by KHLFYY** [comment]
> 为什么这个不能创建秒传

秒传早就没了啊 

那都是九月份的事了

参见 #225

**Comment by 957057** [comment]
什么时候恢复秒传

**Comment by KHLFYY** [comment]
> 什么时候恢复秒传

阿里云盘官方把秒传接口关闭了

基本就是断绝了这条路

除非官方想恢复

（当然 不会这么想的 毕竟秒传减少了空间占用 阿里云盘以后卖的就是空间）

**Comment by xslh** [comment]
感谢作者辛勤付出！使用11.07版也是同样错误，等待计算sha1这个错误始终有，一直停留在那里不再上传。

**Comment by liupan1890** [comment]
能否帮我贴一下，那些等待计算sha1的文件的完整路径？（贴一个文件的就行），另外这个文件确定是链接文件吗？

我稍后zailinux上试试看啊，可能是读取文件失败了。我再试试看，是哪里的问题

**Comment by xslh** [comment]
![2021-11-13 19-42-57 的屏幕截图](https://user-images.githubusercontent.com/13762136/141642732-ab2f6194-868d-4bee-b4ea-53a1bc75f314.png)
![2021-11-13 19-45-19 的屏幕截图](https://user-images.githubusercontent.com/13762136/141642736-e1677f0e-eadf-4b6d-87bc-1a6aa52434cd.png)

我刚检查了一下，确实是链接文件，合并文件错误应该是linux的链接文件，指向一个普通文件。等待计算sha1错误应该是链接文件指向一个文件夹， 是一个文件夹链接。

**Comment by xslh** [comment]
建议增加一个选项决定是否上传linux链接文件

**Comment by liupan1890** [comment]
收到，因为平时不用linux，没注意到软连接的问题！在下个版本里会针对链接文件进行检测，会正确的上传链接文件本身，而不是去上传/读取 链接指向的文件

>建议增加一个选项决定是否上传linux链接文件

下个版本会加上的，但请注意，链接文件本身，会造成很多不可预知的后果，比如你选择不上传软连接，等以后下载后一运行发现有路径找不到之类。或者上传了软连接文件，但以后下载后一运行发现路径错误之类。这些都是软链接本身导致的问题

感觉到时候用起来会很麻烦

**Comment by liupan1890** [comment]
刚刚试了一下，
发现支持软连接文件，需要修改的地方挺多，
今晚更新的v2.11.14是直接屏蔽了软连接文件的上传。如果确实需要上传软连接，请先将文件夹打包成压缩包，然后在上传就可以了（注意：测试ubu系统下，直接压缩为zip，不会包含软连接文件，需要压缩为7z格式，才会包含软连接）

等以后有空了，我再的增加软连接文件的上传支持

**Comment by xslh** [comment]
完美！！！

**Comment by liupan1890** [comment]
今天做软连接上传

结果发现了新问题

因为小白羊是使用electron的，只能通过node.js去读取文件

nodejs 只有2种方式读取

1. fs.readFile() 只能读取文件内容（软链接，会读取目标文件的内容）
2. fs.readlink() 读取软连接文件的值 （目标文件路径，比如  down\file.mp4）

所以小白羊能读取/上传

但是，把上传的软链接文件下载下来，只会得到一个文本文件，并不会得到一个软链接文件。即点击此文件无法链接到目标文件

因为是需要执行创建软链接的命令，重新创建软链接。但是已经上传的文件，无法标识这是一个软链接文件。也无法在下载时察觉这是一个软链接文件重新自动调用命令创建软链接

结论：虽然上传了，但是下载时不能恢复。也就是没有实际意义了

所以，以后的版本里，小白羊也只是直接过滤掉软链接文件。需要用户自己在上传前压缩为7zip格式的压缩包，才能正确的恢复软链接


一般，用户也不需要上传软链接文件，一位内软连接都是安装程序自己创建的。并不需要用户保留


比如你上传了mysql。实际上，
1.打7z压缩包后上传。下载后能恢复
2.直接上传mysql的安装包，下载后重新安装

一般，重新安装才是推荐的，因为安装时会有一些 软件设置/环境变量/软链接路径/权限配置/服务创建 

有的软件打包/上传/下载/解压/恢复后，也不能正确的运行了
