### ISSUE TITLE
bug 最近版本 linux下双击什么反应都没有

### ISSUE THREAD

**Issue by ask-github** [liupan1890/aliyunpan#368]
centos 8

**Comment by liupan1890** [comment]
收到，我会去检查，如有问题会在11.14里修正

**Comment by liupan1890** [comment]
我是使用ubu20.04，测试是正常的，

请问，是否你关闭了设置里的
![无标题](https://user-images.githubusercontent.com/67817756/141667822-9e495192-3c5a-4fe2-a476-754e65c85d88.png)


,默认是关闭的，在设置里删除全部数据也会导致设置恢复默认项

如果没有勾选，请勾选，就可以双击打开了
如果已经勾选，还不能双击，请继续留言，我再去安装一个cent测试

**Comment by ask-github** [comment]
第一次启动就不行, 什么反应都没有, 更没有设置的情况了

我是centos8, ub可以的话, 我试试ub

**Comment by ask-github** [comment]
试验了ub, 也是什么反应也没有, 但是github desktop能跑
能否不要中文, linux下无法输入dir路径

**Comment by ask-github** [comment]
试了一下ubuntu 20.04. 双击文件, 什么反应都没有

**Comment by ask-github** [comment]
这个是怎么跑的

**Comment by liupan1890** [comment]
我猜，可能你是说的，在cent下，双击视频文件不能在线播放

如果是，

检查你是否安装了MPV播放软件（默认是MPV，不需要设置）

安装命令 `sudo apt install mpv`

安装后，单击，视频文件名（强调名字，字上，单击），即可触发在线播放（小白羊顶部还会显示2秒的Loading弹出提示）

你可以参照上面链接，使用其他的播放软件，但需要在设置里修改设置



#

如果是 说视频文件/图片文件/office文件，文件名上单击都没有任何反应，那就是程序BUG了，但从没有用户跟我反馈过这个BUG，我想这个几率不大

**Comment by ask-github** [comment]
> 我猜，可能你是说的，在cent下，双击视频文件不能在线播放
> 
> 如果是，
> 
> 检查你是否安装了MPV播放软件（默认是MPV，不需要设置）
> 
> 安装命令 `sudo apt install mpv`
> 
> 安装后，单击，视频文件名（强调名字，字上，单击），即可触发在线播放（小白羊顶部还会显示2秒的Loading弹出提示）
> 
> 你可以参照上面链接，使用其他的播放软件，但需要在设置里修改设置
> 
> 如果是 说视频文件/图片文件/office文件，文件名上单击都没有任何反应，那就是程序BUG了，但从没有用户跟我反馈过这个BUG，我想这个几率不大

不是, 是这个软件就打不开

**Comment by liupan1890** [comment]
打不开的话也有很多可能

1.你没有给程序文件执行权限

![无标题](https://user-images.githubusercontent.com/67817756/141681517-76a0892c-5d4b-47a0-a3f6-45224536c5c5.png)


2. 小白羊所在目录，路径里有特殊字符（比如有人遇到路径名里有#，就白屏）

常见的就是这样了 ，不管是ubu，cent也有人在用，还有其他的linux

因为小白羊本身就是一个比较普通的electron程序，electron对linux支持的还可以的

**Comment by liupan1890** [comment]
注意，没有UI的，服务器版本的linux是无法运行的。需要基本的UI支持

**Comment by ask-github** [comment]
用strace追踪了一下
原因是这个
如何解决
write(2, "[1002270:1114/210207.470557:FATAL:electron_main_delegate.cc(252)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.\n", 151) = 151

**Comment by liupan1890** [comment]
好厉害，我就不会用strace

回到问题，其实我也没遇到过这个错误，查了一下，说是转到普通用户下执行，或者给程序加上 --no-sandbox 参数

你等我一下，我去试试看。最后告诉你结果

**Comment by ask-github** [comment]
换了用户, 又遇到这种错误
./xiaobaiyang 
$ The futex facility returned an unexpected error code

**Comment by liupan1890** [comment]
尝试方案一：下载这个添加了no-sandbox参数的版本，替换掉 阿里小白羊版Linux v2.11.14/electron/resources/app.asar

[applinuxsandbox.zip](https://github.com/liupan1890/aliyunpan/files/7533803/applinuxsandbox.zip)



尝试方案二：在小白羊所在目录下，进入electron目录，打开终端，运行如下命令：

``````
test@ubuntu:~/桌面/阿里小白羊版Linux v2.11.14/electron$ ./electron --no-sandbox
``````

**Comment by liupan1890** [comment]
两种方案，选一个试试看。

**Comment by ask-github** [comment]
好的, 感谢

**Comment by liupan1890** [comment]
>./xiaobaiyang

应该是直接双击  `阿里小白羊版Linux v2.11.14/阿里云盘小白羊版`启动，./xiaobaiyang是什么命令？

强调啊，小白羊是UI程序，不能在无UI的命令行里运行的

**Comment by liupan1890** [comment]
你别感谢啊，咱们得解决问题，你得告诉我结果啊

**Comment by liupan1890** [comment]
不过，这个肯定是chrome的锅，可能换个electron版本就好了。真的，我发布的版本里linux是用的electron v13.1.7

如果那两个方案都不行，你跟我说，我再换个electron最新的版本试试（也就是更新了chrome版本了）

**Comment by liupan1890** [comment]
https://wss1.cn/f/6vnkqufc980 复制链接到浏览器打开

这个是electron 15.3.1版本的，如果上面方案不行，就试试这一份

最后突然想到提示一句，小白羊打包的是linux x64版本，无法再x86版linux上运行，无法在arm64 / armv7l cpu上运行

**Comment by ask-github** [comment]
用方案一解决了 electron --no-sandbox

因为linux不好输入中文, 很麻烦

root运行, 什么显示都没有, 就退出了, strace才看到是no-sandbox问题, 给你一个强字

**Comment by liupan1890** [comment]
applinuxsandbox.zip替换文件的方案你试过了吗？我关心这个，如果这个可以的话，以后就都会在代码里加上

不然linux用electron --no-sandbox命令启动太麻烦了，双击直接运行多方便

**Comment by ask-github** [comment]
> applinuxsandbox.zip替换文件的方案你试过了吗？我关心这个，如果这个可以的话，以后就都会在代码里加上
> 
> 不然linux用electron --no-sandbox命令启动太麻烦了，双击直接运行多方便

applinuxsandbox.zip, yes it is ok. my linux machinse has no chinese input method.

if run this app in linux UI as root. must add param --no-sandbox. it is easy to reproduse

thanks very much. this app is work fine

**Comment by ask-github** [comment]
give a more advise.

the chinese file name is not easy to luanch in console even if in linux UI. 

thanks

**Comment by liupan1890** [comment]
感谢你的回复，也对我帮助很大，以后的版本都会采用applinuxsandbox.zip这种。避免类似问题

------
关于中文文件名，
原因是，

1.小白羊并未考虑其它语言的支持（因为阿里云盘仅在中国大陆访问正常，国外速度很慢。并且小白羊也只是个人软件，没有精力去维护多语言版本）

2.进对于中文用户来说，如果是一个英文名（例如xiaobaiyang）。那么有的人并不会立即明白需要双击这个文件启动。是为了让部分不太懂linux的用户，一眼看去，就知道去点哪个

3.补充说明一点，其实当你使用时，完全没必要去运行“阿里云盘小白羊版”这个文件。他只是一个壳，它的作用是命令行下启动 electron/electron 这个文件。因为linux下的electron文件，双击不能启动，必须要命令终端里 输入 electron去启动它

所以你可以直接在命令里运行 electron/electron 这个文件，忽视“阿里云盘小白羊版”这个文件


这点也是与2对应，部分新接触linux的用户---说的就是我---并不习惯终端--命令--运行。我习惯找到文件，双击，运行---windows用户通病？
