### ISSUE TITLE
请问怎样调整自带MPV的字幕大小呢

### ISSUE THREAD

**Issue by goeway** [liupan1890/aliyunpan#369]
请问怎样调整自带MPV的字幕大小呢，不知按到什么键了，字幕变得超级大

**Comment by goeway** [comment]
没了睬自问自答好了：shift+F 字体减小 shift+G 字体增大

**Comment by liupan1890** [comment]
呃，我也不知道，百度一下MPV快捷键就好了

或者切换其他的自己熟悉的播放软件

再v2.11.14里，已经支持win/mac/linux选择自定义了
