### ISSUE TITLE
希望增加这个功能，本地文件验证SHA1，获取脚本分享链接，实现秒传。

### ISSUE THREAD

**Issue by zhangbolins** [liupan1890/aliyunpan#37]
aliyunpan://阿里网盘脚本分享工具.exe|DB3BEE202D57CAE158A5A85347FB599674904220|613888|application/x-msdos-program

阿里云盘秒传方法：
1.安装7-zip  https://sparanoid.com/lab/7z/
2.安装油猴脚本插件，安装阿里云盘油猴脚本
3.选择要上传的文件右键 选CRC SHA 选SHA-1
4.复制名称，SHA1，大小，粘贴替换到下面文字

小委托人.mp4
aliyunpan://小委托人.mp4|3907CC0B8C5453EACDDBF429A8A93AA255E13CC8|2568199396|application/oct-stream

名称：小委托人.mp4
SHA1：3907CC0B8C5453EACDDBF429A8A93AA255E13CC8
大小：2568199396

格式如下：
aliyunpan://文件名称|SHA1|文件大小|application/oct-stream

注意：中间有竖线间隔，如果阿里云盘服务器没有上传的文件，会失败，有的话直接妙传，不用等好旧的验证。
5.最后到阿里云盘网页提取。

#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/12/25/025 22:53
# @Author  : H
# @File    : getFileFeatures.py

"""批量获取文件夹中各个文件的MD5、SHA1、SHA256"""

import hashlib
import os
import sys

def getFileFeatures(dirpath):
   path = os.getcwd() + "\\" + dirpath

   subpaths = []
   datas = {} # 结果存为json，以便后需
   if os.path.exists(path):
       # 路径存在
       if os.path.isdir(path):
           # 获得的路径为文件夹
           for root, dirs, files in os.walk(path):
               for file in files:
                   subpaths.append([file, os.path.join(root, file)])
       else:
           # 获得的路径为文件
           file = path.split("\\")[-1]
           subpaths.append([file, path])

       for i in subpaths:
           f = open(i[1], "rb")
           rb = f.read()
           data = {'MD5': hashlib.md5(rb).hexdigest(),
                   'SHA1': hashlib.sha1(rb).hexdigest(),
                   'SHA256': hashlib.sha256(rb).hexdigest()}
           datas[i[0]] = data
           f.close()
       with open("filefeatures.txt", "a")as f:

           for k, v in datas.items():
               f.writelines("filename:\t" + k + "\n")
               print("[+]succeed get the teatures of " + k)
               for key, value in v.items():
                   f.writelines(key + ":\t" + value + "\n")
               f.writelines("\n")

   else:
       print("Folder does not exist")

if sys.argv:
   print("""
  _     _      _     _      _     _      _     _      _     _      _     _   
 (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)  
  / ._. \      / ._. \      / ._. \      / ._. \      / ._. \      / ._. \   
__\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__ 
(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
  || K ||      || I ||      || L ||      || L ||      || E ||      || R ||   
_.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._ 
(.-./`-'\.-.)(.-./`-'\.-.)(.-./`-'\.-.)(.-./`-'\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
`-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-' 
   
======  function:  Get the characteristics of file or files in folder ========

=>=>=>=>=>usage :  python getFileFeatures.py file/dir     <=<=<=<=<=<=<=<=<=<=
   """)
   if len(sys.argv) == 2:
       getFileFeatures(sys.argv[1])
   else:
       print("[-]Usage errors")

**Comment by WHYEX3** [comment]
好家伙，代码都写好了

**Comment by WHYEX3** [comment]
好家伙，代码都写好了

**Comment by liupan1890** [comment]
我有点懵

程序的功能是，计算出本地文件的sha1，拼接出aliyunpan://这样的链接，这个我明白

但是，下面的我没明白，
>如果阿里云盘服务器没有上传的文件，会失败，有的话直接妙传，不用等好旧的验证。
5.最后到阿里云盘网页提取。

你到底是需要什么呢？
你想要根据本地文件，得到一堆可以使用的aliyunpan://这样的链接，然后发给别人？
（你直接用小白羊把本地文件秒传到阿里云盘，然后用浏览器插件生成aliyunpan://这样的链接就可以了）

你想要根据本地文件，秒传到阿里云盘？
（这个小白羊或者官方客户端都已经实现了，应该不是）


难道你是想说，根据本地文件，只想得到aliyunpan://这样的链接，然后发给别人。
但是如果用小白羊全选文件上传，遇到能秒传的当然1秒传完了，遇到不能秒传的（阿里云盘不存在的），可能需要上传很久，你就不想上传了，直接跳过这个文件。
反正最终就是从这一堆文件，挑出/检查出 能秒传的，生成aliyunpan链接，就行了。剩下不能秒传的文件就不管了。
你只想要这部分秒传文件的aliyunpan链接---我想了好几遍才想到你应该是这个意思
（这个，小白羊已经不再支持创建秒传链接了。上传文件能够秒传是正常的上传功能。创建秒传链接就不正常了，不敢想，不敢做啊）
