### ISSUE TITLE
有个小功能（外挂字幕）希望能够支持，谢谢作者!

### ISSUE THREAD

**Issue by Scorpionida** [liupan1890/aliyunpan#370]
同级目录下同名.ass字幕文件在播放视频时，播放器字幕按钮是灰色的，也无法手动选择字幕文件。
希望添加视频播放器的外挂字幕的支持，谢谢！辛苦了！！！

**Comment by liupan1890** [comment]
抱歉，这个功能无法实现

1.字幕是在网盘里，所以，需要小白羊先自动下载字幕到你的电脑上，
--这个自动下载的操作，一般会被报病毒

2.字幕和视频必须文件名完全一致，差一个字母都不行（实际上很多字幕名和视频文件名并不是完全一致，而是近似）
--所以能自动加载字幕的机会很少

3.mpv播放器支持命令外挂字幕，但其他的大部分播放器并不支持命令里指定字幕
--所以不能支持其它播放器


综上，无法实现，需要你自己手动下载字幕，然后拖放到播放窗口上，就可以显示字幕了

**Comment by Scorpionida** [comment]
现在可以使用“将字幕文件拖放到窗口上”的方法可以使用外挂字幕文件了，多谢！！！

**Comment by liupan1890** [comment]
另外,v2.11.14里对播放器支持也有调整，可以支持更多播放软件了

**Comment by snow212-cn** [comment]
> 3.mpv播放器支持命令外挂字幕，但其他的大部分播放器并不支持命令里指定字幕 --所以不能支持其它播放器

问题是现在mpv播放器外挂网盘字幕你的小白羊也不支持
