### ISSUE TITLE
关于分享功能的一些小想法

### ISSUE THREAD

**Issue by aww0517** [liupan1890/aliyunpan#372]
作者晚上好. 特一个小小的建议.分享功能方面,
可否增加 分享搜索.功能. 有些人的分享连接 很多. 可能有几百上千条. 
想找到其中某一条时,非常困难. 如果能增加所有功能,便捷的找出来.应该很棒. 

 以及分享数据展示,目前官方仅能查看自己的 分享连接数量,
 无法查看自己全部的分享连接 
共计获得多少浏览 下载 及转存.希望能增加此功能.

最后一句. 白羊YYDS

**Comment by liupan1890** [comment]
收到，下个版本会加上

**Comment by liupan1890** [comment]
v2.11.16 搜索，总计数，按 预览/下载/转存数排序 已添加
