### ISSUE TITLE
2.11.14 被Windows安全中心报毒，级别为“严重”

### ISSUE THREAD

**Issue by Samachurl** [liupan1890/aliyunpan#373]
![image](https://user-images.githubusercontent.com/48409650/141686098-15606958-ef2f-4d86-9fcf-9a8fdec7fbe7.png)

**Comment by liupan1890** [comment]
这就很尴尬了，以前遇到过更新最新版的aria2报毒，然后我就换回旧版aria2了

但是v2.11.14和v207比，没有什么区别啊，只是代码更新啊。。。。

我也不知道报毒的具体原因，并且杀软报毒，他也不告诉你具体的原因啊，怎么整改？

**Comment by liupan1890** [comment]
可以通过通用补丁去升级，因为通用补丁只有一个app.asar文件，不包含exe文件，应该不会被报毒

**Comment by jkqxl** [comment]
Windows安全中心经常性抽风，我火绒没问题
