### ISSUE TITLE
云盘分享网站添加

### ISSUE THREAD

**Issue by dawnmaner** [liupan1890/aliyunpan#374]
看到新版小白羊功能很振奋，作为白羊粉谢谢开发者提供这么好用的软件，看到新版软件上有个分享功能，里面有些阿里云盘分享网站，看到网上有个新生阿里云盘资源分享论坛很有特点 alifree.net  看到创建一个月就已经6K人了很厉害，论坛形式互娱一体，有很多字幕组在论坛发布原创阿里云资源，希望开发者也把这个alifree加入到软件分享里面。

**Comment by liupan1890** [comment]
收到，稍后就会加上

**Comment by jjandnn** [comment]
@liupan1890  我是今天刚看到这个工具，很不错。说几句体会，不合适，勿怪。
就分享站这个功能，我觉得你可以保留发布的权限，但是使用上的修改添加可以留给用户。几个站的站址都失效更新了，眼下只能打开浏览器导入……
插件部分同上，基础你来，其他，可以让大家来。当然，你不想变成油猴那样。忽略。
阿里之所以这次摧枯拉朽：简化再简化。避免走百度的路，照这样下去，将来收费也没问题，因为体验上用当年360杀百度的极简主义必胜。而避开所有工作功能就等于回避了谷歌盘的强项，这也是在web3.0阶段的自我认知。
优秀软件，就是简单至极，垂直体验无敌，但，又有足够空间留给高阶用户与合作方。
祝好，新年快乐！
