### ISSUE TITLE
2.11.14 不能通过系统代理登录了？

### ISSUE THREAD

**Issue by cui-wei** [liupan1890/aliyunpan#376]
win10系统，2.9.24 版本时还可以登录。  新版不行了？

**Comment by liupan1890** [comment]
跟系统代理无关，因该是跟登录功能有关

有三种登陆方式，短信，密码，扫码
都尝试一下吧

在v2.9.24 (和以前)，是正常登录的

在v2.11.x开始，为了捕获apptoken ，登录方式做了调整，因为调整，有时候，有的登录方式会失败，换其他的登录方式就行了

有的登录方式会失败，具体表现为，今天可以用账号密码登录，明天可能不行，需要用短信/扫码登陆

失败是随机的（看是否会触发阿里云盘的验证），而不是固定的。所以也不能说就是不能账号密码登陆了，可能过一会重新尝试又可以了，也可能连续几天都不行，必须使用其他方式登陆

总之：三种方式，一个不行换一个，全都不行，退出小白羊，重新打开，重试

跟代理无关，跟地域有关，比如国外就容易失败，国内就容易成功

**Comment by cui-wei** [comment]
并没有看到3种登录方式的页面。

[https://imgtu.com/i/Ifpmwj](url)

**Comment by liupan1890** [comment]
抱歉，issue太多，没注意到你的回复

如图，是单纯的网络问题，打不开阿里云盘的登录网页。我以为你说的是点击账号密码后还不能登录那种情况呢

打不开登录网页（https://auth.aliyundrive.com/v2/oauth/authorize?login_type=custom&response_type=code&redirect_uri=https%3A%2F%2Fwww.aliyundrive.com%2Fsign%2Fcallback&client_id=25dzX3vbYqktVxyX&state=%7B%22origin%22%3A%22*%22%7D）

确实可能是因为代理导致的。但是v2.9.24和v2.11.x都是基于Electron，都没有在代码里设置/修改 任何代理的选项

所以我也不是很清楚为什么没走代理。

---

electron一般不会识别出pac代理。只有全局代理(安驱动的那种)才能默认识别

但是可以在启动时，手动指定代理地址。这样不管是全局还是非全局还是IE代理，都无所谓了

手动指定代理步骤：
1. 给`阿里云盘小白羊版v2.exe`创建快捷方式
2. 修改快捷方式的属性--目标，增加代理信息(--proxy-server=192.168.31.74:8888)
``````
D:\alixby\阿里云盘小白羊版v2.exe  --proxy-server=192.168.31.74:8888
``````
3. 双击快捷方式启动小白羊即可

**Comment by Sanzo00** [comment]
> 

我在mac端也无法使用代理下载文件，代理工具使用的是Qv2ray，开的全局代理。

想问下mac端如何手动指定代理？

**Comment by liupan1890** [comment]
经确认，没有自动识别出系统的代理，是BUG
已经在最新的版本里修正了此BUG
并且还增加了备用的，强制的指定方式
请等v2.12.05发布后更新新版就好了

**Comment by liupan1890** [comment]
已在v2.12.05里修正系统代理被错误覆盖的BUG
