### ISSUE TITLE
云盘资源网站添加

### ISSUE THREAD

**Issue by guochangxin1999** [liupan1890/aliyunpan#377]
希非常喜欢阿里云网盘有个网盘网站希望添加一下
网址http://rjdq.huofh.club

**Comment by liupan1890** [comment]
看了一下，内容过少，暂不添加。如果以后资源多了（指的是阿里云盘分享资源多），请再次提交

请理解，并不是我故意卡你。这个网站内我只看到了不足200条资源--大略一扫而已，并没有真的统计

请等阿里云盘的分享资源超过5千条以后，您再联系我，我就会立即添加了


一般来讲，各大云盘的分享链接为固定长度的数字字母，可以通过采集软件，去自动生成特定格式的链接，然后采集，然后就能得到巨量的分享内容了。。。。所以.。。。。
