### ISSUE TITLE
除了单选和全选，希望能增加多选

### ISSUE THREAD

**Issue by malou9** [liupan1890/aliyunpan#38]
需要删除一些文件，发现只有单选和勾顶部的全选，不能多选

希望能增加多选功能

**Comment by liupan1890** [comment]
win / mac

方式一：按住键盘上Ctrl键，点击一个文件，再点击一个文件，再点击一个文件---一共选择3个文件
方式二：点击第4个文件，按住键盘上Shift键，再点击第7个文件---会自动选择4-7这几个文件（4，5，6，7）

可以重复，多次，混合，Ctrl / Shift 多选文件
就是标准的windows文件管理器多选文件的操作，用过windows的都会用了

这个功能一直有，在首页的操作录像中，也明确的标注了按住Shift键多选文件，所以。。。

**Comment by liupan1890** [comment]
举例：100个文件，
选择1，3，5，7，9
按住Ctrl，点击1，3，5，7，9即可

选择1，3，5，7，9，10，11，12，13，14，15，16，17，18，19，20
按住Ctrl，点击1，3，5，7，9，松开Ctrl，按下Shift，点击20，松开Shift


选择1，3，5，7，9，10，11，12，13，14，15，16，17，18，19，20，22，23，24，25（不选21）
按住Ctrl，点击1，3，5，7，9，松开Ctrl，按下Shift，点击25，松开Shift，按下Ctrl，点击21，松开Ctrl


选择1...........20，22，24，26，28
点击1，按下Shift，点击20，松开Shift，按下Ctrl，点击22，24，26，28，松开Ctrl

选择1.........80，82......100（就是不要81）
方式一：点击全选，按住Ctrl，点击81，松开Ctrl
方式二：点击1，按下Shift，点击100，松开Shift，按住Ctrl，点击81，松开Ctrl
方式三：点击1，按下Shift，点击80，松开Shift，按住Ctrl，点击82，松开Ctrl，按住Shift，点击1000，松开Shift

**Comment by malou9** [comment]
哦，明白了，怪我眼瞎~·哈哈
