### ISSUE TITLE
能否获取 文件的链接，不是分享，这样我就能从一个文件夹调转到另一个文件夹？

### ISSUE THREAD

**Issue by hongtucao8384** [liupan1890/aliyunpan#380]
![image](https://user-images.githubusercontent.com/55793584/141803467-ab1af6eb-626d-4f3e-bc43-0bb07b34f92a.png)

**Comment by hongtucao8384** [comment]
我是想这样，我在word中直接插入这个文件夹的链接，点一下就跳转到对应的文件夹

**Comment by liupan1890** [comment]
复制链接，最终得到的链接是什么？粘贴一个我看看
