### ISSUE TITLE
提个建议，纯一家之言。个人觉得似乎小白羊没有自己的特色？花大力气优化上传未必有效的说

### ISSUE THREAD

**Issue by jun-wwx** [liupan1890/aliyunpan#382]
我也是一路跟着版本迭代过来的，站在产品的角度来说，个人倾向严重哈。

阿里盘作为一个新网盘上传的需求我认为没有下载的需求大，大多数人现在就当一个备份盘或者资料盘，百度的地位一时半会撼动不了。

我私以为小白羊不一定下大力气优化上传，{主要原因是每次本版大更新对我来说没有太大的提升，体验上来说。。。

我个人的一家之言是可以在下载好好优化的基础上，可以开发一些一招鲜吃遍天的功能。

重复文件扫描，批量重命名，除了Aria加下载方式，这样的独有的特色功能作为我这样只把阿里云当备份盘的人来说是比较期待的。

以上

**Comment by liupan1890** [comment]
嗯，确实是这样

自7月-11月，这三个月做了什么了？
基本上总结为，

``````

从单次点击，下载十万个文件，会卡几十秒
到
从单次点击，下载100万个文件，不会卡十几秒

``````

``````

从单个文件夹直接包含1千个文件夹时，文件树会卡，软件会卡
到
单个文件夹直接包含几千个文件夹时，文件树不卡，软件不卡

``````

然后呢？没啥了，剩下的都是细枝末节

（期间7-8月还有针对秒传功能的各项优化，和秒传屏蔽后的删除）

我也不知道自己一天天在干啥。。。。。。

批量重命名已经在2.9.24里有了，功能已经很全面了，这个就不说了


重复文件扫描是6月份立的项，11月份过半还没开始做，
按现在的进度，大概会在一个月以后开始着手做

**Comment by jun-wwx** [comment]
@liupan1890 

hey bro   

我本意不是指责呀，别丧就是了。

我是一路看着你各种动态edit过来的。

我本身也只是学生，我只是觉得哈，

>1.你要自信，已经很OKOK了。阿里云现在的客户端做的就是一坨屎，下载动不动断掉，我天天看群里吐槽，小白羊一路过来我觉得就像一个孩子一样慢慢迭代。相比之下已经很牛逼了
>2.我觉得你要慢一慢缓一缓的。梳理一些哲学论方法论的东西了。要抓主要矛盾的嘛
>
>我觉得产品更新其实就是两方面：debug和开发新功能(创造新bug,hhhhhh
>
>网盘的核心是存储，存储带来的核心是上传和下载。单单做好这个已经很不容易了。
>
>今年校招阿里云搞得很凶，题外话一句liupan你要注意一下准备好正规军碾脸上的准备。比如秒传，或者开发新功能，很容易从项目组组内直接把你某个功能断了，害，为爱发电确实难，跑题了跑题了

其实总的来说我是觉得客户端优化功能已经很完善了，再快其实极端的快那是阿里云项目组的事，如果是为爱发电，何不做一些更接地气的功能？大公司可恶就可恶在明知道很好就是不做，此处点名批评微信和张小龙，太狗屎了。

我觉得为爱发电就这点好，力所能及不被项目组的搞得前提下做一点让自己开心的东西。

我甚至觉得你建议听得太多了，建议像张小龙学习，我就是个臭个人开发的，路人的建议听一听，想做做不想做说一个技术有限做不了。

夹带私货时间，开这个issue本意是想催一下重复文件扫描哈哈哈哈，说着说着跑题了。

主要我也是搞ai的，经常和国外的项目打交道，说得好高级。本身也是学生，其实就是github学东西不懂的就直接发邮件麻烦人家。我也算见了不少半路夭折的个人项目了。

毛主席告诉我们要抓住主要矛盾的主要方面，个人开发者，能力范围内把自己搞开心就好，为爱发电嘛。

现在sb这么多，别被传播焦虑了，讲究一个论迹不论心。你做出这个已经很厉害了，坚持自己的想法慢慢debug本身就很好了。

以上

（再次催一下重复文件扫描，差点忘了hhhhh

**Comment by ybbluesky** [comment]
楼主的优化其实正是官方版本的短板，超官方几条街

**Comment by jun-wwx** [comment]
> 
> 
> 楼主的优化其实正是官方版本的短板，超官方几条街

哈哈哈哈对啊，我只是想表达现在其实优化的很好了，再优化就是出十分力有一份效果的瓶颈期了，不想前期一份力一份效果那么明显了

**Comment by liupan1890** [comment]
收到，

其实也是我的问题

我没有按照产品去做小白羊，而是按照兴趣去做的

区别是这样

产品：
需要争取产品用户多，所以，自然是，哪些功能有用，做哪些。哪些对提升用户体验重要，优先做哪些

重点是，有较完善的，开发计划，和线路，和目标
就好比写小说，要先列大纲，职业作家，虽然拖稿，但也会一天两更+存稿

兴趣：
想到啥做啥，哪里感兴趣就做哪里。完全没有计划是一方面，也完全没有规划
计划是说这周做什么，规划是说那些功能可以怎么做

说到底就是自由散漫，大家习惯了就好

**Comment by jjjyyyllll** [comment]
> 收到，
> 
> 其实也是我的问题
> 
> 我没有按照产品去做小白羊，而是按照兴趣去做的
> 
> 区别是这样
> 
> 产品： 需要争取产品用户多，所以，自然是，哪些功能有用，做哪些。哪些对提升用户体验重要，优先做哪些
> 
> 重点是，有较完善的，开发计划，和线路，和目标 就好比写小说，要先列大纲，职业作家，虽然拖稿，但也会一天两更+存稿
> 
> 兴趣： 想到啥做啥，哪里感兴趣就做哪里。完全没有计划是一方面，也完全没有规划 计划是说这周做什么，规划是说那些功能可以怎么做
> 
> 说到底就是自由散漫，大家习惯了就好

现在只想要一个可以离线下载的功能  支持种子和磁链就好

**Comment by KHLFYY** [comment]
> 现在只想要一个可以离线下载的功能 支持种子和磁链就好

在官方上线之后 小白羊才会去做离线下载（调用官方接口）
