### ISSUE TITLE
不知道小白羊能否把桌面端的阅览室搞起来

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#385]
各人口味不同，不知道小白羊能否把桌面端的阅览室搞起来，毕竟官方版本只有移动端才有阅览室功能，而桌面端暂时没有，如果能用桌面端阅读epub，mobi文件，如果再与官方移动端能阅读记录并在或者同步就完美了，不知道技术上能不能实现

**Comment by liupan1890** [comment]
不能

官方的阅览室，就是简单的，把epub下载到手机里，然后，官方app里继承了阅读插件

就比如你在手机里安装一个静阅天下.apk 然后下载一个epub，最后从静月天下里打开这个epub

所以，无法同步阅读记录，因为不同阅读软件的阅读记录，保存的格式并不一致。也无法统用

----

关于小白羊集成阅览室

没有这个意义，你直接下载epub，然后在电脑里阅读就可以了。随便安装一个阅读软件都可以
