### ISSUE TITLE
请问这个图标什么意思？（红圈中间斜划链）有截图

### ISSUE THREAD

**Issue by NormanOnGithub** [liupan1890/aliyunpan#388]
![image](https://user-images.githubusercontent.com/38353997/142289489-af226b1a-4866-4b4f-b364-34e155eeafdc.png)
中间那个图标（红色），是不是被禁了？但是可以 播放也可以下载。官方网页版也能播放
若是被禁的视频，会一直能播放吗？

**Comment by KHLFYY** [comment]
请看 #371 的2楼

**Comment by liupan1890** [comment]
371有说明，被禁止分享了
