### ISSUE TITLE
有没有什么办法用自己的服务器 做一个 离线下载

### ISSUE THREAD

**Issue by cynzsm** [liupan1890/aliyunpan#390]
首先感谢六哥的小白杨，个人感觉非常好用  并且一直在用  官方的以前也就 搜索用下，
11.16版本出了搜索，以后就可以把官方的卸载了
===========分割线==========
我的想法是 
一台服务器  win2008 系统的 
在服务器上 安装 aria2  和 小白杨
 我在家里电脑上远超让aria2 下载 然后再上传到阿里云上。

不知道六哥可以实现不？？我想这个功能应该不难把~

**Comment by liupan1890** [comment]
分成2部分

第一部分：离线下载
这个因为本身就是需要你自己去配置离线下载的电脑的。所以怎么离线，怎么下载（是用aria下载，还是用迅雷下载，还是百度网盘下载，这个就不管啦）。总之你先弄好了下载到一个文件夹里

第二部分：自动上传
小白羊以后会有自动同步的功能，指定好文件夹，设置好仅上传。就可以了


所以你的需求是可以实现的，只是小白羊开发速度慢，还没有做出文件同步功能，等等看吧

**Comment by cynzsm** [comment]
嗯~  那如果 下载到一半的时候  同步了 怎么办？

**Comment by liupan1890** [comment]
这个跟下载有关系。

1.小白羊下载的，中间文件，全部是.td  可以在小白羊设置里，增加.td文件的过滤
百度网盘是downloading
迅雷是.td
aria的话好像是原文件名，这个比较麻烦。但是aria自己支持，下载后调用命令，你可以自己配置一下，这个命令，下载到Down1,下载完命令里写移动到Down2 小白羊里设置为同步Down2就行了

只说aria，所有的网盘同步都是这样，用下载完后命令，去触发上传的

**Comment by cynzsm** [comment]
好的   那就 静等 同步功能啦~~
