### ISSUE TITLE
大家是否存在显示已经上传完毕，但是关闭程序重新打开后发现上传列表中还有文件？ #349

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#391]
#349的问题测试还没有完全修复。还是有此问题存在

**Comment by liupan1890** [comment]
最好说一下你的详细的操作步骤，我需要按照步骤，让问题在我电脑上重现，这样我才能发现真正的原因。

因为我近期在正常使用时，没有发现过这个问题（因为我日常就是，，导入，，在线，，偶尔下载，我基本不上传文件）

**Comment by ybbluesky** [comment]
> 最好说一下你的详细的操作步骤，我需要按照步骤，让问题在我电脑上重现，这样我才能发现真正的原因。
> 
> 因为我近期在正常使用时，没有发现过这个问题（因为我日常就是，，导入，，在线，，偶尔下载，我基本不上传文件）

我是正常上传A--B---C-----D这种模式的文件夹上传，其中d中是正常的文件，a可能有6000个，每个b与c各有10个或者20个，d中文件为3-6个，我整个上传a文件夹，程序正常显示上传完成，上传列表中也无数据，但是退出程序后重新打开程序，发现上传列表中又有数据存在，也可继续上传。

**Comment by liupan1890** [comment]
那么重新打开时，剩余的文件数量多吗？是只有文件还是只有文件夹还是都有？
剩余的文件名字有什么相似的地方吗？可以感觉到规律吗？

这些文件/文件夹的命名有什么规律吗？
比如A叫什么呢？B叫什么呢？C叫什么呢？D叫什么呢？A/B/C 里有文件吗？还是全是文件夹只有D里才有文件？

具体的文件名有什么规律吗？
A/B/C/D/文件名/会有特殊字符吗？有哪些？

我是想要按照你的完整的目录去测试。有的时候，可能就是一点细节不同，这点细节导致的BUG

**Comment by liupan1890** [comment]
如果方便的话，在A目录下，打开cmd

``````
dir /b /s >1.txt
``````

会把所有文件（完整路径+文件名）
输出到A/1.txt里，把1.txt贴给我

如果不方便就算了，这不是强制要求。我只是想完全重复一下，更加简单的重先BUG

**Comment by ybbluesky** [comment]
> 如果方便的话，在A目录下，打开cmd
> 
> ```
> dir /b /s >1.txt
> ```
> 
> 会把所有文件（完整路径+文件名） 输出到A/1.txt里，把1.txt贴给我
> 
> 如果不方便就算了，这不是强制要求。我只是想完全重复一下，更加简单的重先BUG

1.txt
https://www.aliyundrive.com/s/hDqacnQKfbT

文件其实可能300个在列表中

**Comment by liupan1890** [comment]
好的，我已经下载了，可以取消分享了

我稍后会多次测试，最终争取解决BUG

**Comment by ybbluesky** [comment]
> 好的，我已经下载了，可以取消分享了
> 
> 我稍后会多次测试，最终争取解决BUG

好的，关闭此话题

**Comment by liupan1890** [comment]
我没说关闭此话题啊。。。。


我周日测试了大半天，

根据1,txt里的文件列表，在本地，完整的创建了1.txt里面的所有目录和文件（文件全部是128KB随机填充的）

使用v2.11.14测试了3遍上传，使用v2.11.16测试了5遍上传

但是都没能触发这个BUG。最后实在是不知道怎么办了，我又翻了一遍代码，也没能找到问题，因为最近时间是在是有限，这个BUG只能先搁置了

注：
1.  在创建文件时，1.txt里有261条文件，文件名中包含? ，不知道是cmd命令输出时编码问题，还是在你电脑上真的有路径包含?因为windows不允许路径包含?所以感觉是编码问题，使用中文？替换掉了
2. v2.11.14上传途中因为我的分享BUG白屏过一次，后来删除分享就正常了
3.上传操作就是网盘根目录创建一个新的文件夹，然后把Calibre Book Library拖放上传到这个新文件夹里

![无标题](https://user-images.githubusercontent.com/67817756/142824558-43b05bec-8d3b-43a7-8bbe-92597d1f1215.png)

**Comment by liupan1890** [comment]
包含?的文件示例：(无法确认是否和这些文件名有关，因为无法真的创建这些文件，只能创建替换?后的)
D:\Calibre Book Library\Calibre Library_EnglishBook\Zo? Ferraris\Finding Nouf (793)
D:\Calibre Book Library\Calibre Library_EnglishBook\Zo? Ferraris\Finding Nouf (793)\cover.jpg
D:\Calibre Book Library\Calibre Library_EnglishBook\Zo? Ferraris\Finding Nouf (793)\Finding Nouf - Zo? Ferraris.epub
D:\Calibre Book Library\Calibre Library_EnglishBook\Zo? Ferraris\Finding Nouf (793)\Finding Nouf - Zo? Ferraris.mobi
D:\Calibre Book Library\Calibre Library_EnglishBook\Zo? Ferraris\Finding Nouf (793)\metadata.opf
D:\Calibre Book Library\Calibre Library_EnglishBook\?leen Frisch\Essential System Administration, 3r (5062)
D:\Calibre Book Library\Calibre Library_EnglishBook\?leen Frisch\Essential System Administration, 3r (5062)\cover.jpg
D:\Calibre Book Library\Calibre Library_EnglishBook\?leen Frisch\Essential System Administration, 3r (5062)\Essential System Administration - ?leen Frisch.epub
D:\Calibre Book Library\Calibre Library_EnglishBook\?leen Frisch\Essential System Administration, 3r (5062)\Essential System Administration - ?leen Frisch.mobi
D:\Calibre Book Library\Calibre Library_EnglishBook\?leen Frisch\Essential System Administration, 3r (5062)\metadata.opf
D:\Calibre Book Library\Calibre Library_EnglishBook\?zkaya, ?zen\Arduino Computer Vision Programmin (14296)
D:\Calibre Book Library\Calibre Library_EnglishBook\?zkaya, ?zen\Arduino Computer Vision Programmin (14296)\Arduino Computer Vision Program - ?zkaya, ?zen.epub
D:\Calibre Book Library\Calibre Library_EnglishBook\?zkaya, ?zen\Arduino Computer Vision Programmin (14296)\cover.jpg
D:\Calibre Book Library\Calibre Library_EnglishBook\Р”С?Р? Р?РёР?Р?Р?Р?С?\The Fall of Hyperion (hc-2) (14663)
D:\Calibre Book Library\Calibre Library_EnglishBook\Р”С?Р? Р?РёР?Р?Р?Р?С?\The Fall of Hyperion (hc-2) (14663)\cover.jpg
D:\Calibre Book Library\Calibre Library_EnglishBook\Р”С?Р? Р?РёР?Р?Р?Р?С?\The Fall of Hyperion (hc-2) (14663)\metadata.opf
D:\Calibre Book Library\Calibre Library_EnglishBook\Р”С?Р? Р?РёР?Р?Р?Р?С?\The Fall of Hyperion (hc-2) (14663)\The Fall of Hyperion (hc-2) - Р”С?Р? Р?РёР?Р?Р?Р?С?.epub

**Comment by ybbluesky** [comment]
应该txt的格式有问题，真实的文件名为Arduino Computer Vision Program - Özkaya, Özen.epub，上传成功了的，不是Arduino Computer Vision Program - ?zkaya, ?zen.epub

**Comment by ybbluesky** [comment]
此问题以后再说吧，谢谢大佬的解释
