### ISSUE TITLE
建议 小白羊 任务栏 图标 点击一次弹出主窗口

### ISSUE THREAD

**Issue by at2008** [liupan1890/aliyunpan#392]
现在是双击弹出

是否可以修改为单击，减轻指头的疲劳 i😊

**Comment by liupan1890** [comment]
收到，下个版本里改

**Comment by ybbluesky** [comment]
哈哈，这个疲劳也增加不了多少嘛

**Comment by KHLFYY** [comment]
还是点一次习惯一点
︿(￣︶￣)︿

**Comment by liuyun198833** [comment]
是否设置成快捷键显示主窗口，如Alt+X (shift+alt+X) 。这样弹出主窗口会比较方便，不然每次去任务栏去找，然后还得单击~

**Comment by KHLFYY** [comment]
> 是否可以设置成快捷键显示主窗口？如Alt+X (shift+alt+X) 。这样弹出主窗口会比较方便，不然每次去任务栏去找，然后还得单击~

不知道作者是否会加热键   
感觉会让小白羊设置项变多
作者好像不太像让小白羊变得太复杂
（毕竟是个绿色软件）

---

如果确实有这个需求
**要加的话 希望默认留空（不预设热键**

因为
习惯用热键的人 预设可能会和别的软件热键冲突
不用的人 自然就不会去使用
我个人是不用的
而且有的时候莫名其妙就按出点什么 就会很恼……

**Comment by liupan1890** [comment]
全局热键的话，很容易冲突。所以不加了

**Comment by at2008** [comment]
> 哈哈，这个疲劳也增加不了多少嘛

大部分软件任务栏图标都是点一下，习惯性的也是去点一次小白杨，然后反应过来，应该点两次，总共要点三次，关键是不符合习惯。i😂
