### ISSUE TITLE
左侧目录树，焦点在子目录时，无法点击左侧三角图标收缩目录树

### ISSUE THREAD

**Issue by at2008** [liupan1890/aliyunpan#393]
左侧目录树，焦点在子目录时，无法点击左侧三角图标收缩目录树。
焦点在同级目录、当前目录时，可以收缩当前目录树。

建议点击哪个三角图标就收缩、展开那个目录。

**Comment by liupan1890** [comment]
是我设计的这样的逻辑，要求当前选中的文件夹，被一直展示，不允许被收缩隐藏

所以不是BUG，是故意这样设计的

**Comment by at2008** [comment]
好的，明白了，似乎有道理，感谢您的付出！
