### ISSUE TITLE
小白羊挺住！！！

### ISSUE THREAD

**Issue by kudoushinichi6671** [liupan1890/aliyunpan#394]
网页已经开始出现限制了，分享的网页没有下载的按钮了，而网盘内的100M以上的文件
要使用客户端才能下载，不知道会不会针对小白羊，特地来此友情提醒下

**Comment by liupan1890** [comment]
哦，感谢提醒，我倒是没注意到这点（这几天没用网页版），看后期官方怎么具体限制吧。但是只要官方客户端可以下载，无非就是跟着版本更新的事，这个问题不大

只有说官方客户端，不能下载，那小白羊肯定不能下载的，想来不会的。

**Comment by kudoushinichi6671** [comment]
好的，我是担心官方用对付秒传链接那样，想个其他办法来对付小白羊，但愿是我想多了,想来官方也不会做的那么绝

**Comment by chen-7-c** [comment]
网页早这样了.. 要想下载也算简单，打断点...  但是其实没什么意义。
