### ISSUE TITLE
同一文件夹的视频或者音频能连续播放加好了！

### ISSUE THREAD

**Issue by ddunniu** [liupan1890/aliyunpan#396]
同一文件夹的视频或者音频能连续播放加好了！看个电视剧看完一集又从头来了，得关掉播放器，再回到小白羊里找到下一集点击！！

**Comment by sailing178** [comment]
电视剧连续播放需求+1

**Comment by liupan1890** [comment]
这个需求，做不到啊

1.播放是调用播放器，既，对播放器说：Hi，放一下xxx
2.大部分播放器都不支持，一次说：Hi,放一下xxx xxx2 xxx3 xxx4
3.播放地址有4个小时的有效期。比如一次播放10集，其实到了第5集就不能播放了
4.小白羊无法知道，播放器是否播放完一集了，因为放完一集后，播放器不会跟小白羊说一声：hei，我放完了

综上，仅从播放软件角度，无法实现，批量播放。即使特定的播放软件成功实现了播放列表，也无法连续播放超过4个小时

阿里云盘是内置的播放插件，只播放转码后的视频，因为内置，所以可以连续播放。
小白羊是调用外置的播放软件，所以无法连续播放

是逻辑问题
