### ISSUE TITLE
请问开发者能不能添加一个纯色版的主题？

### ISSUE THREAD

**Issue by Jingzhenzxz** [liupan1890/aliyunpan#397]
Hello！请问开发者能不能添加一个纯色版的主题？我感觉颜色太多反而有点不美观。一个小建议哈哈哈。

**Comment by liupan1890** [comment]
纯色的主题，意思是？是说哪里的颜色太多？需要详细的说一


我理解纯色主题，是说所有的界面，只有黑白两色，除此之外没有其他颜色是吗？
我想到，
1.一些按钮，现在都是蓝紫色的，你是想把它们全部变成黑色？
2.一些文件名前面的图标，是各种颜色的，你是想把他们全部变成黑色？
3.文件名鼠标移动上去会变蓝色，你是想不变色？
4.设置里一些按钮是有颜色的，你是想把他们全部变成黑色？
5.一些操作结果提示，前面会有带颜色的图标，你是想把他们全部变成黑色？

纯色具体是指什么？难道是指windows里面的高对比度模式？

**Comment by Jingzhenzxz** [comment]
> 纯色的主题，意思是？是说哪里的颜色太多？需要详细的说一
> 
> 我理解纯色主题，是说所有的界面，只有黑白两色，除此之外没有其他颜色是吗？ 我想到， 1.一些按钮，现在都是蓝紫色的，你是想把它们全部变成黑色？ 2.一些文件名前面的图标，是各种颜色的，你是想把他们全部变成黑色？ 3.文件名鼠标移动上去会变蓝色，你是想不变色？ 4.设置里一些按钮是有颜色的，你是想把他们全部变成黑色？ 5.一些操作结果提示，前面会有带颜色的图标，你是想把他们全部变成黑色？
> 
> 纯色具体是指什么？难道是指windows里面的高对比度模式？

你好，我的大致思路是统一所有非黑非白颜色的色调，尤其是要去掉橙色、黄色和红色这些看起来和蓝紫色冲突的颜色。然后尽量让引入的颜色（如蓝紫色）**成块**出现，这意味着尽量少给细字体和细线条上色。
另外我感觉小白羊的导航栏中的图标有点大，而且第一个和最右边那三个图标比较尖锐，更加显眼。我认为第一个图标的位置值得商榷，且它和后三（或四）个图标都应该变小变紧凑变细。还有可以考虑像官方那样给“小白羊”这三个字加点艺术感。
我不会亲自调试所以我说不了太多，sorry。

**Comment by liupan1890** [comment]
收到，我对美工类并不涉及，所以完全是个人审美去做的。根本不能讲细节。因为细节上问题确实很多，比如有个别图标比其他的图标都小1个像素，比如有的地方的灰色文字，跟背景对比度不太合适，太浅或太深

这些是确实存在的。只是我不去管而已---没时间，也没能力

关于色彩统一，我反而不是这么看的，当都是黑色和蓝色时，操作成功/操作失败提示呢？有些地方就是要强调色啊，没有主次了

所以其实不是纯色的问题，而是色彩虽然丰富了，但搭配/配合的不够好的问题。就好比说穿衣搭配，红色裤子配绿色上衣，就是感觉不搭

但偏偏，我没啥美工的概念，就拿一个简单的配色，颜色有几个度，冷热色调什么的，我都不懂。所以，我也不会继续去改了---因为改不好，不懂就是不懂了，我也就能做做功能，美观上确实把握不住啊。。。
