### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by TUO-V** [liupan1890/aliyunpan#398]
最近几个版本（好像是从九月还是十月下旬开始）都出现无法登陆的问题

比如用手机端扫屏幕上的二维码并点击登陆后二维码显示已失效（如图），无法登陆，重新刷新二维码再尝试登录依旧显示二维码失效
<img width="800" alt="iShot2021-11-20 18 26 17" src="https://user-images.githubusercontent.com/85728145/142743895-d4aeed6c-123f-40ca-92ba-8125dcd37799.png">

用短信登录也无法登陆，账号登录暂时没尝试

在官方的阿里云盘上可以用二维码登陆

电脑是 MacBook Air (Retina, 13-inch, 2019)，系统版本为 Monterey 12.1 Beta 3 (11C5039b)

另外，我现在在国外，不知是否与登陆地点有关

**Comment by liupan1890** [comment]
是的，自v2.10.x开始，为了支持自定义播放软件，修改了登录的流程

自2.10.x开始的版本，登录时，如果遇到了阿里云盘登录验证，会登录失败

v2.9.24是可以正常通过登录验证的

账号密码的登录验证表现为，登录按钮上方出现滑动验证条
短信和扫码的登录验证，表现为登陆后无反应

原因是新的登录流程做的不够完善。--是因为我遇不到登录验证，所以没有完善
之后的版本我会再完善一下，就好了。当前是BUG

登录验证是类似随机触发的，一般一个电脑第一次登录时容易触发，在国外登录时容易触发

**Comment by TUO-V** [comment]
谢谢大佬

感觉大佬回复issue好快

**Comment by xr825** [comment]
一样，在国外，怎么都登录不了!好烦啊，扫码后就一直转圈关了重新就是二维码失效

**Comment by liupan1890** [comment]
嗯，下个版本我好好调试一下，找个国外的代理。只要完善了就好了，不是什么大问题。只是简单的我遇不到登陆前验证。阿里这个对常用电脑很少触发

**Comment by liupan1890** [comment]
在v2.11.28里已经支持登录时的二次验证，试一下吧，有问题再发新的issue
