### ISSUE TITLE
文件名排序问题

### ISSUE THREAD

**Issue by cc201855** [liupan1890/aliyunpan#399]
排序的时候，当文件超过10时，是从1，10，11...排序的，然后才是2，20，21。
![image](https://user-images.githubusercontent.com/44330197/142763471-c21519be-8644-4ec3-bf62-0187031b8f1e.png)

**Comment by KHLFYY** [comment]
这个是软件的机器思维的问题
（但是windows10 确实能识别这样的 按照人的思维排序
应该也是后期人为调整的排序逻辑）

不知道排序这个 是不是使用的官方的
如果小白羊是自己的代码实现的排序 
应该相对改起来比较容易

其实好多软件都是这样
所以为了避免这个问题
好多人写序号都是 01 02 这样开始
（我自己也是这样）
可以手动把这几个文件改一改
以后也养成 01 02 （或者001 002）这种写序号的习惯
避免这种问题

**Comment by liupan1890** [comment]
收到，是BUG，下个版本修正此问题

**Comment by liupan1890** [comment]
在v2.11.28里已经修正此BUG
