### ISSUE TITLE
自动更新

### ISSUE THREAD

**Issue by lz0709** [liupan1890/aliyunpan#40]
希望可以增加就是点击下载自动更新，而不是从GITHUB上下载压缩包再覆盖，GUITHUB的网确实慢了点

**Comment by liupan1890** [comment]
不都是在蓝奏下载吗？为什么在github上下载？

因为是个人软件，并没有花钱买windows上的企业证书对软件进行签名，

增加自动更新功能，win10很容易就误报说是病毒，所以不会增加自动更新功能，只有版本更新提示
