### ISSUE TITLE
需求一个功能

### ISSUE THREAD

**Issue by andywang1011** [liupan1890/aliyunpan#401]
能不能将账号信息和数据库分开，账号信息放在运行程序同目录下，方便各设备之间同步。

**Comment by liupan1890** [comment]
各设备间同步

没get到你的点


----

如果是多个设备需要登录同一个账号，就是简单的重复登录就好了。一般登陆一次后，很少会掉。就是可以一直用，

一个月在2台电脑上，登录2次的操作  对比 `一个月在2台电脑上，完整复制2次安装包` 。我怎么感觉登录比复制文件简单呢？

>你不知道哪个文件是用户登录信息文件，所以你要完整复制整个小白羊安装目录。就算你知道，你也要单独复制这个文件，发送到另外一台电脑，粘贴到正确的位置。所以，重新登录不是比复制文件方便？

----
如果是指同步其他数据（我的分享，网盘内文件列表，这些并不需要同步，仅仅是登陆账号就有了）（上下传记录 这个没有同步的意义，因为你2台电脑路径不一致，同步了也没法用）


---

所以可能需要你详细的描述一下你的需求

**Comment by andywang1011** [comment]
感谢你的回复，你解说后我也觉得没有必要了。
