### ISSUE TITLE
删除提示遮挡 文件路径，建议改在状态栏或者移动到标题栏

### ISSUE THREAD

**Issue by 236507** [liupan1890/aliyunpan#402]
![image](https://user-images.githubusercontent.com/93651002/142797010-e37b3aba-d227-4535-a946-7de33233e9b8.png)

**Comment by liupan1890** [comment]
这个提示吧，确实找不到特别合适的地方

1.比现在的位置还要上移（标题栏），首先不够显眼，然后在有多条提示时跟现在一样，不解决根本问题

2.移动到底部状态栏，首先特别不显眼基本上就是注意不到了，还没法解决多条提示的问题

所以，遮挡确实存在，但我没有合适的方法。（包括缩短提示时间，也会让新手，感觉看不清就没了）

**Comment by 236507** [comment]
![image](https://user-images.githubusercontent.com/93651002/142822824-2c3bd3fe-1804-44d4-98b6-04a5dc37e3bd.png)

把提示显示在地址栏右侧【类似文档排版的右侧对齐】，走马灯或滚动提示可以解决多条问题，不知道会不会好一点？谢谢回复

**Comment by liupan1890** [comment]
那我以后放到右侧吧，但不考虑走马灯，因为逻辑上，多个提示是没有任何关联的，走马灯会感觉有关联

**Comment by liupan1890** [comment]
经测试，放在右边会遮挡住设置对话框的关闭按钮

所以还是在中间，往上调整了一下，只有一个消息时，不影响地址栏
