### ISSUE TITLE
现在官方手机端有了个笔记功能，后续有兴趣会做个一样的吗？

### ISSUE THREAD

**Issue by hongtucao8384** [liupan1890/aliyunpan#403]

**Comment by yatchaulam** [comment]
估计大概率不会

**Comment by liupan1890** [comment]
以后会有的

官方的思路其实比较独特
笔记功能是给所有人新开了一个网盘，然后这个网盘里只存放笔记。

相册功能也是给所有人新开了一个网盘，然后这个网盘里只存放相册数据（照片/视频）

不知道以后还会有啥
