### ISSUE TITLE
大佬，可不可以做一个类似pcs go的精简客户端呐，这个客户端还是太大了

### ISSUE THREAD

**Issue by Jieoz** [liupan1890/aliyunpan#404]
有一个极低配置的下载机也想用。
么么哒

**Comment by ybbluesky** [comment]
用网页版算了

**Comment by liupan1890** [comment]
没有这个打算

还是找一找其他的已经成熟的阿里云盘命令行工具吧，这样的更加合适一点。

小白羊的体积其实没有超过5MB。（代码体积3MB，aria2体积3MB，MPV播放器80MB，Electron 200MB）
但框架体积确实大，有什么办法呢
