### ISSUE TITLE
bug 2w多文件，上传的时候，经常卡住

### ISSUE THREAD

**Issue by ask-github** [liupan1890/aliyunpan#405]
要重启才行
<img width="231" alt="9037AB44-A728-4D17-ADA8-C90CFDE3D8A1" src="https://user-images.githubusercontent.com/72971953/142862827-1e128683-8a20-44aa-9dac-22cccc222788.png">

**Comment by CONAN-ZDD** [comment]
一下上传两万多文件不卡才怪

**Comment by ask-github** [comment]
为啥要卡，2w文件很正常，排队就行
你的一定会卡的思维哪里来的

**Comment by ask-github** [comment]
我的同步文件夹任务，又卡住了，哎，麻烦

**Comment by ask-github** [comment]
我认为这才是用户核心诉求，其他都是附加值

**Comment by CONAN-ZDD** [comment]
等慢慢优化吧，毕竟是一个人做

**Comment by ask-github** [comment]
卡住了，重试还不行，要关掉app，重开，又是连不上aria一直跳

**Comment by ask-github** [comment]
11 07哪里下载

**Comment by liupan1890** [comment]
能详细说一下嘛？感觉不太正常，因为v2.11.x我测试了，一次性上传1百万个文件，不会有卡顿的。

2W的话，太少了，怎么会卡顿呢？肯定是有因为哪里不正常（比如有BUG）

你是什么系统？小白羊是什么版本？卡住，是卡在哪里（什么操作）？

比如是拖放文件后就卡住了？
比如是上传时，一直卡，点什么都反应慢？

**Comment by liupan1890** [comment]
顺便，为什么问1107？那个很早就被删除了，最新的是v2.11.16 是最新版卡想切换回旧版？

**Comment by liupan1890** [comment]
想到一个BUG，在之前（忘了具体哪个版本号），会遇到小文件，一直显示计算sha1的BUG，需要重启小白羊才能继续，但继续后还是很容易出现。

如果你是说的这个BUG，这个跟卡没关系，是执行BUG，用最新版本就行了，已经修正了

**Comment by ask-github** [comment]
经过多次测试, v2.9.24版本可以一次性上传2w多文件, 
但是11.26就经常卡住, 界面就是上面的截图,
系统是centos8

**Comment by ask-github** [comment]
我再多试几次 11.16

**Comment by ask-github** [comment]
![image](https://user-images.githubusercontent.com/72971953/143391816-57ac610f-7e4a-44f4-b9f5-83dc984af8d8.png)
必现, 又卡住了

**Comment by liupan1890** [comment]
设置--运行日志

里面是否有错误提示呢？

看截图是卡在解析中。解析中是像请求阿里云盘上传地址。可能阿里云盘当时忙？
或者是有BUG，但我没测试到BUG，注意如果是大陆以外，网速会比较慢。国内网速都还挺快的

v2.9.24 和 v2.11.16在上传上确实是不一样的。为了支持超过97.6GB的单个文件，v2.11.16对上传做了改动。我稍后去看看，是否和这个有关---感觉没关系，因为我测试了很多次百万文件上传，都没遇到卡住不动的时候

卡住以后，你怎么操作？重启小白羊就又正常了?留意一下小白羊是否内存占用过高了？正常上传2W文件，内存应该在600MB以内才正常

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/143406512-3a3dd2dc-3f84-427c-9bd7-d7c671220ec4.png)

如图，如果运行日志里包含500错误，就是单纯的网络问题。如果没有，说明是BUG。但也没有其他人反应上传卡住的BUG啊？
v2.11.16的下载量约为6000次

**Comment by liupan1890** [comment]
今天测试，还真遇到一个错误，结果就是上传队列卡住不上传了，在运行日志里，可以看到

``````
 sqlerror:there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space
``````

意思是，c盘空间不足，数据无法写入数据库。需要清理C盘以后 才能正常

centos8的话是需要清理 设置-高级-缓存路径 
路径显示的所在盘。需要清理出一点空间（几百兆）才能正常运行
你看一下运行日志，是这个错误吗

**Comment by ask-github** [comment]
![CEAADC48-EB85-4C3C-BD4F-E41A34A1B74F](https://user-images.githubusercontent.com/72971953/143428290-c2da24a4-e65f-49d3-9dc2-428e8b626c56.jpeg)
没有这个错误，今天还有这种错误
9.24，一直都能工作，我勉强能用

**Comment by liupan1890** [comment]
先说创建文件失败600这个错误

不知道为什么你的运行日志里没有错误，因为在我的代码里，出现600错误，会记录到运行日志里
600错误是网络错误，一般发生在网络超时30秒都没有收到服务器响应的时候。
既，小白羊像阿里云盘发送了一个请求（创建文件），结果30秒后都没有收到阿里云盘的回复，超时自动断开了

这个说明你当前的网络，跟阿里云盘链接的不顺畅。这个跟v2.9.24还是v2.11.16无关，网络不好都不好。
如果网络好，不会出现600错误。而是50x错误或者40x错误-具体的操作错误信息

### 请问是否使用的国外网络？(阿里云盘并不支持国外)

这个错误也能解释，上面的卡在上传无反应---实际上不是没反应，而是在等待阿里云盘返回（等待30秒，就感觉是没反应，像卡住了，30秒后会显示错误信息，1分钟后会自动重新启动重新上传）


-----

然后是计算sha1可能文件拒绝访问

请问是在上传本地硬盘上的文件吗？
这个是因为读取不到这个文件，常见于 
1. 文件被删除
2. 读取网络共享路径里的文件但网络临时不好读取中
3. 这个文件当时已经被别的程序打开了

如果是一过性报错（第一次报错，第二次正常）不用管他，因为有自动重试，最终还是会上传上去的

**Comment by liupan1890** [comment]
今天找了一台centos8虚拟机做测试，果然发现了问题，上传文件时，部分文件夹是需要权限访问的，会报错，因为没有捕获到部分报错，会导致上传中队列，像卡死一样，没有反应。

----

下个版本会修正因读取权限原因导致的报错卡死。但不能访问的文件仍然不能访问，因为没有权限

如果你想要上传那些没有访问权限的文件

方案一：修改这些文件的权限，让普通用户有权访问（可以在上传中队列中/设置-运行日志中 看到哪些文件无权访问）

方案二：使用su用户权限运行小白羊,比如终端中输入如下命令：
``````
sudo '/home/test/桌面/阿里小白羊 版Linux v2.11.28/阿里云盘小白羊版'
``````

**Comment by ask-github** [comment]
我一直都是root启动，这个app里面会切换用户吗

**Comment by liupan1890** [comment]
不会。app启动后无法切换用户

今天在做发布前的长效测试。结果在centos里又发现了新BUG，心真累

事情原因是内存不足，新为centos的内存是1GB的（便宜），长期大量上传文件时
（主要是看上传的文件体积）

当上传一个文件时，需要用到10MB的内存缓存。当调整为60文件并发上传时，也就是需要60*10==600MB的内存缓存区
结合小白羊本身运行时占用的300MB内存，总占用内存剧增到约1GB。但是没有1GB的内存（系统还会占用一部分内存）

所以，就内存崩溃了（表现为上传中列表中文件卡住，没有上传进度）

当前版本的解决方案是调小并发数量。避免内存占用过多。实际上，只要系统显示的内存占用超过80%，就会不太稳定了。我的电脑是win10,只要内存占用超过80%基本上就会各种异常，死机，浏览器崩溃


所以，可能你遇到的，一直都是内存不足。就是这么简单的问题。

**Comment by liupan1890** [comment]
1.上传的单个文件体积<10MB时，会占用文件体积的内存，上传的单个文件体积<80GB时，会占用10MB内存，上传的单个文件体积>80GB时会占用更多内存(10MB-20MB)

2.小白羊是2个页面，

1个主页面可以看到上传中列表（就是小白羊界面）
另1个后台页面是不可见的后台执行上传操作的页面，上传文件时此页面会占用较多内存

上传文件时，遇到内存不足时，是这个后台页面占用较多内存，所以也是它先崩溃（被系统强制回收内存导致崩溃）。
主页面没有崩，正常显示，但已经无法正常上传，只能重启小白羊。才能继续上传

**Comment by liupan1890** [comment]
今天下午，我会优化一下上传的代码，将单个文件上传占用的临时内存，调整为1MB以内，这样可以避免内存不足的崩溃。所以今天发布可能又要鸽了。。。
