### ISSUE TITLE
可不可以加一个返回上一级菜单的快捷键

### ISSUE THREAD

**Issue by CONAN-ZDD** [liupan1890/aliyunpan#406]
返回按钮有点小，而且习惯了windows文件管理的alt＋左键返回，希望可以加一个快捷键

**Comment by liupan1890** [comment]
当前是按BackSpace 键返回父文件夹

那我下个版本增加Alt+左箭头的快捷键

**Comment by CONAN-ZDD** [comment]
好的好的，原来BackSpace也可以返回

**Comment by liupan1890** [comment]
在v2.11.28里以支持Alt+左箭头返回父文件夹
