### ISSUE TITLE
我把logo源文件修改了，但是没有完全修改

### ISSUE THREAD

**Issue by CONAN-ZDD** [liupan1890/aliyunpan#407]
![image](https://user-images.githubusercontent.com/50905610/142881371-76a75d8b-098c-448a-b878-58ab3dc9e4dc.png)
###### 右边和Google drive一样的图标就是修改之后的，但是dock栏上的图标修改不了
如图，我把软件目录里的logo改了，现在只有托盘的logo变了，dock上的图标没有用。

其他的软件只要把快捷方式的图标改了，dock的图标也会跟着变，但是小白羊不可以，不知道为什么

**Comment by liupan1890** [comment]
在windows上，

\阿里云盘小白羊版v2\resources\app.png 是dock的图标 替换这个文件就好了

\阿里云盘小白羊版v2\resources\app.ico 是任务栏托盘图标

**Comment by CONAN-ZDD** [comment]
怪不得，我只改了ico文件
