### ISSUE TITLE
bug 一直在跳 无法连接aria

### ISSUE THREAD

**Issue by ask-github** [liupan1890/aliyunpan#408]
rt
11.16

**Comment by ask-github** [comment]
我不需要aria，有办法吗

**Comment by liupan1890** [comment]
小白羊需要使用aria才能下载

提示不能连接到aria，是因为aria没有正确的运行

请问是什么系统呢？小白羊在windows上自带的aria2.exe是32位的，适用于win7-win10 32/64位系统（不适用于arm）

一般，aria无法正确运行，在排除不适用的系统后

1.权限问题
2.杀毒软件误杀
3.aria启动时需要占用29384端口，如果此端口被占用，则无法启动

（一般，重启电脑，然后先不要开启其他软件，先开启小白羊，这样就保证端口不会被占用了）

**Comment by ask-github** [comment]
centos8 kde 系统, 有时候好, 有时候不好
不好的时候, 我看看端口问题

**Comment by liupan1890** [comment]
如果是，小白羊启动后，是正常的，运行一段时间，突然提示aria2断开

这个可能是aria2的问题。

1.aria2 运行中突然出错崩溃了（下载文件时出错了？）

2.在启动aria2时传了一个参数--小白羊pid。为的是当小白羊退出时，aria2跟随一起结束退出。centos8 kde 系统我没测试过，假如该系统，对长期不操作的进程休眠，可能会导致aria2检测不到小白羊进程，主动退出

**Comment by liupan1890** [comment]
在v2.11.28里已经增加本地aria启动失败时，自动重启一次的逻辑
