### ISSUE TITLE
mac版 提示无法连接到后台

### ISSUE THREAD

**Issue by memooooo0201** [liupan1890/aliyunpan#41]
系统版本是Mojave

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/121847468-301dc300-cd1b-11eb-8186-d6abbbfd9962.png)


macOS Mojave(mac OS 10.14)

我只有10.15，刚刚测试，是通过的。还有最新的11.4也是正常的。
一般这个跟系统版本无关，只跟你的电脑本身有关（比如你安装了那些软件啊，有哪些设置啊之类可能会有冲突）

如图：正常运行会启动3个进程(阿里云盘小白羊版，aliserver,aria2c)
提示无法连接到后台 说明aliserver和aria2c没有运行，为什么不知道，有时候彻底退出后重新打开就好了

在阿里云小白羊版v1.6.13.app/Contents/Resources/Debug.log 是运行日志，你也可以看一下是否有出错退出的日志

**Comment by memooooo0201** [comment]
谢谢回复，用了sudo xattr命令后可以正常使用了👍
