### ISSUE TITLE
疑似bug：文件名排序问题

### ISSUE THREAD

**Issue by obtoo** [liupan1890/aliyunpan#410]
小白羊的排序结果和阿里云盘网页版的排序结果不一致（根据文件名排序）
看了网页版的返回结果，json数据的顺序和网页版的展现一致
但是和小白羊展现的不一致，不知道是不是接口参数更新了
小白羊的文件名升序排序结果
![image](https://user-images.githubusercontent.com/28035207/142976441-c49d5d44-e7c5-4583-8a1a-4e3663a22739.png)
阿里云盘网页版文件名升序排序结果
![image](https://user-images.githubusercontent.com/28035207/142976510-0b46a2ce-aade-4988-b32a-40d590266c2a.png)
看了接口返回的数据，第七条数据的 "name" 值是 "S01E03 加更： ....."，同页面展示的结果一致，而不是前端做了别的处理
故推测官方的文件排序接口的参数或许有所变更，小白羊这里没有同步

**Comment by liupan1890** [comment]
因为官方对1,10,2这种排序并不准确，所以小白羊显示时是自己重新排序的，所以和官方排序顺序确实是不一致的。

是有什么情景需要和官方排序一致吗？

**Comment by obtoo** [comment]
没有特殊的需求，就是看到这种现象，以为是维护过程中没有注意到的情况
测试了几个官方的排序，从汉字到数字，重排序之后有些更合理了
感谢作者的付出

**Comment by liupan1890** [comment]
在v2.11.28里已经修正此BUG (直接是数字名时，没能正确排序，字母等开头包含数字名时可以正确排序)
