### ISSUE TITLE
新功能建议：【文件管理-批量打标签功能】-官方没有的功能希望小白羊能做

### ISSUE THREAD

**Issue by liuyun198833** [liupan1890/aliyunpan#412]
@liupan1890 

文件比较多的时候分类是个比较麻烦的问题，尤其是一个文件涉及多个分类维度，所以想到用标签对文件进行管理。之前看到过有类似功能的文件打标签软件，附图如下。希望小白羊作者可以考虑开发相关功能~

另：有了标签功能就相当于解决了文件搜索的**过滤功能**~

![](https://i.loli.net/2021/11/23/1pldvmHCUa6kjfe.png)

**Comment by liupan1890** [comment]
这个问题吧，关键是阿里云盘

1.阿里云盘API其实支持文件标签功能，但是网页版/PC端/手机端 都没有直接提供标签功能。所以需要等官方。看他们以后怎么使用标签功能（我现在用了，可能跟官方以后的用法不一样，导致数据冲突，我的数据会被清理）

2.不使用阿里云盘的API，而是直接本地数据打标签，会有个问题，既不能多端同步，你在公司电脑登录，家里电脑打的标签全没了。这个就不合适了，来回打标签？

除此之外，还有个美观的问题，如图，很不美观（比较乱）。但怎么美观？我不知道，设计不出一个比较美观的界面。这也是不想做的原因


所以这个标签，以后再说吧，现在不考虑

**Comment by rapmq0** [comment]
啥玩意 你直接用文件夹分类不行吗

**Comment by liuyun198833** [comment]
@liupan1890   感谢作者回复，那就看官方api中的标签功能最后怎么用吧，最后小白羊所有功能开发完后作者再看情况决定~

**Comment by liuyun198833** [comment]
> 啥玩意 你直接用文件夹分类不行吗

是这样，有时文件夹不太好分类，比如一部电影，它是国产片，武侠片，导演张艺谋，主演李连杰，甄子丹，梁朝伟，张曼玉等。这时候如果用文件夹分类就得电影→国产片→武侠片→张艺谋→?
到演员这个层面就不好分了，如果你有李连杰电影合集，甄子丹电影合集，梁朝伟电影合集，那最后这个电影改放哪分类比较好。如果有标签功能，直接文件夹用到两级，电影→国产片，把电影放到国产片这个文件夹中，之后的电影类型，导演，演员信息用标签就可以了。
