### ISSUE TITLE
能否增量上传？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#413]
文件太多，能否只上传没有的文件和目录？

**Comment by liupan1890** [comment]
不能

因为你文件太多，具体多少，其实并没有个准确的（每一次都不一样），也很难界定目录形式（几千个文件夹，但每个文件夹里只包含1-2个文件/几百个文件夹但每个文件夹里包含数千个文件）

从程序逻辑上，很容易做到，检查网盘里这个文件夹下面有哪些文件，然后和本地匹配
但从阿里云盘上，很难做到。

因为阿里云盘一次只能列出200个文件，这个限制导致文件夹下数量很多时会列很长时间（一百万文件需要列3个多小时）
因为阿里云盘对访问频率限制的很低，当有几千个文件夹时，也需要很长时间才能一个一个的列出来

因此，从实际执行的角度去统计

1.当文件夹很多时，还好
2.当文件很多时，很不好

综合一下，就不如现在，一个一个文件去上传。开60文件同时上传，会自动跳过已存在的完全一致的文件。

也就是，现在默认，本身就是，增量上传的。只是文件很多时，已存在的那些文件还要执行一遍可能会导致最终上传时间比较长

但是，即使开发了增量上传功能，因为需要列出网盘文件匹配本地，这个操作时间也很长，增量上传功能并不能节省很多时间。没有了实际使用的意义

**Comment by ybbluesky** [comment]
收到，谢谢解答

**Comment by liupan1890** [comment]
多说一句，

同步盘功能，会支持增量上传，因为会在本地数据库里存储本地文件的列表/修改时间/sha1

抛开同步功能，当直接上传文件操作时

1.不增量
所有文件都执行完整的上传操作
不管网盘里是否存在同名文件，执行的操作是：计算文件sha1,调用一次秒传。成功就完了。不成功继续真的上传

2.增量
读取到网盘内存在的文件。判断网盘已存在同名同体积的文件
执行的操作是：计算文件sha1,调用一次秒传。成功就完了。不成功继续真的上传

如上，不论是否增量。都会执行计算文件sha1,调用一次秒传

操作流程上无法节省时间，

大文件计算sha1会用时较长并且CPU狂飙
但是，不计算sha1就无法确认本地和网盘中是完全一致的文件。可能只是名字+体积一样，内容却不一样。即使再加上本地文件的修改时间和网盘中文件的上传时间去判断，也无法确保文件一致。必须计算sha1


以后在设置里会增加上传时，根据时间跳过选项，只要你自己明确知道文件未修改过，开启此设置，会加快一点点上传速度

**Comment by rapmq0** [comment]
上传上去再删除重复文件

**Comment by ybbluesky** [comment]
> 多说一句，
> 
> 同步盘功能，会支持增量上传，因为会在本地数据库里存储本地文件的列表/修改时间/sha1
> 
> 抛开同步功能，当直接上传文件操作时
> 
> 1.不增量 所有文件都执行完整的上传操作 不管网盘里是否存在同名文件，执行的操作是：计算文件sha1,调用一次秒传。成功就完了。不成功继续真的上传
> 
> 2.增量 读取到网盘内存在的文件。判断网盘已存在同名同体积的文件 执行的操作是：计算文件sha1,调用一次秒传。成功就完了。不成功继续真的上传
> 
> 如上，不论是否增量。都会执行计算文件sha1,调用一次秒传
> 
> 操作流程上无法节省时间，
> 
> 大文件计算sha1会用时较长并且CPU狂飙 但是，不计算sha1就无法确认本地和网盘中是完全一致的文件。可能只是名字+体积一样，内容却不一样。即使再加上本地文件的修改时间和网盘中文件的上传时间去判断，也无法确保文件一致。必须计算sha1
> 
> 以后在设置里会增加上传时，根据时间跳过选项，只要你自己明确知道文件未修改过，开启此设置，会加快一点点上传速度

限制本地文件的时间，可以满足一部分人的需要

**Comment by liupan1890** [comment]
在v2.11.28里，以增加 上传文件时网盘内存在同名文件直接跳过的选项
