### ISSUE TITLE
清空回收站后左侧没有同步更新回收站的列表

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#415]
如题

**Comment by liupan1890** [comment]
呃，我确实没看懂

清空回收站后---应该是说点击了清空回收站按钮，等它，很长时间后，提示清空完成

左侧--是指哪？文件夹树？

没有同步更新--是说没有刷新

回收站的列表--这个是什么意思呢？是没有刷新哪里？

截个图吧，一眼就看明白了，是说点击清空回收站以后，右侧显示的回收站内文件列表，这个列表没有刷新（清空）吗？左侧？

**Comment by ybbluesky** [comment]
> 

左侧回收站不是有文件列表吗，清空回收站文件列表没有涮新

**Comment by ybbluesky** [comment]
> 

左侧回收站不是有文件列表吗，清空回收站文件列表没有涮新

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/143197557-395d05dd-b390-4ecc-9850-c575e88c280b.png)


左侧？v2.11.16 ? 没有啊

**Comment by ybbluesky** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/143197557-395d05dd-b390-4ecc-9850-c575e88c280b.png)
> 
> 左侧？v2.11.16 ? 没有啊

回收站中有一次出现了文件列表，但是后来又没重现了，不知道引起的原因，也不影响使用，关闭此话题
