### ISSUE TITLE
linux版本在centos7下双击无反应

### ISSUE THREAD

**Issue by sw586** [liupan1890/aliyunpan#416]

**Comment by liupan1890** [comment]
参阅https://github.com/liupan1890/aliyunpan/issues/368
不知道是否一个问题。

最终解决方法
尝试方案二：在小白羊所在目录下，进入electron目录，打开终端，运行如下命令：

``````
test@ubuntu:~/桌面/阿里小白羊版Linux v2.11.14/electron$ ./electron --no-sandbox
``````

命令是 ./electron --no-sandbox 啊，前面的是终端里显示的路径

**Comment by liupan1890** [comment]
注：我发布的是linux 64 位，在x86上无法运行，在arm等cpu上无法运行

**Comment by sw586** [comment]
> 

可能是这个问题

**Comment by liupan1890** [comment]
你的是x86系统，是绝对无法运行的，(一般重新装个x64就好了，如果是虚拟主机，直接一键换系统)

如果确实需要x86请参阅自行打包：https://github.com/liupan1890/aliyunpan/blob/main/v2%E5%B0%8F%E4%BC%97%E7%B3%BB%E7%BB%9F%E8%87%AA%E8%A1%8C%E6%89%93%E5%8C%85.md
