### ISSUE TITLE
没有钱, 项目是走不远的

### ISSUE THREAD

**Issue by ask-github** [liupan1890/aliyunpan#417]
来点捐款?

**Comment by liupan1890** [comment]
虽然我自己是用爱发电的，但我并不喜欢捐款的形式，他违背了公平的原则。大家都在用，少数人付费，大部分人免费用，总是不那么公平

小白羊是6月上线的，到12月的话不足半年。期间因为工作没时间，开发的功能也很少。也不值得大家付费支持

以后再说吧

**Comment by juncheng45** [comment]
一个人都比阿里整个团队做得好，他们就不觉得丢脸吗

**Comment by ask-github** [comment]
> 一个人都比阿里整个团队做得好，他们就不觉得丢脸吗

话不能这么多, 阿里团队也不是只做客户端的, 还有服务端, 以及其他

**Comment by jkqxl** [comment]
做不好的原因，只是不是真的非常非常想做好这个产品，大部分人只是在恰饭而已，并没有竭尽一切，发挥主观能动性。
