### ISSUE TITLE
关于使用v2进行文件上传异常

### ISSUE THREAD

**Issue by carolzzn** [liupan1890/aliyunpan#419]
[我平常一直把v2挂着，使用的是路由模式，但是今天在上传的时候，发现和v2一块用的时候显示流量都走了v2，但实际上并没有走，所以客户端显示的也是异常的速度，和平常不挂v2上传的显示异常。并且上传的时候速度也有问
![QQ图片20211125192618](https://user-images.githubusercontent.com/78587901/143433452-682d5bd6-0e8f-4433-bad6-b690c6fa734e.jpg)
![QQ图片20211125192629](https://user-images.githubusercontent.com/78587901/143433460-be71c6b5-2632-415b-b59a-86f58fcb858e.jpg)
![QQ图片20211125192625](https://user-images.githubusercontent.com/78587901/143433473-a46a22e3-1b0d-4da9-b182-646b17d094d5.jpg)
题

**Comment by liupan1890** [comment]
关于代理问题

小白羊使用electron，并没有特殊设置。所以完全按照electron的默认代理策略运行。
默认代理策略是什么我也不知道

如果你想要让流量走代理

方式一：
在小白羊.exe上创建快捷方式，在快捷方式属性--目标 里，附加参数 
``````
--proxy-server=192.168.31.74:8888
``````
完整的快捷方式属性--目标：
``````
D:\alixby\aae\aDrive.exe --proxy-server=192.168.31.74:8888
``````


方式二：开启全局代理（v2我没用过，不知道他的全局代理是怎么实现的，一般tap的全局最好用）

**Comment by liupan1890** [comment]
如果仅仅是想反映一下代理流量显示不准确的问题，这个我也不知道怎么去修正（小白羊里显示的上传网速，其实并不够准确，仅是参考）
