### ISSUE TITLE
iso 格式能支持播放吗

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#42]
大佬：
iso 格式能支持播放吗

![image](https://user-images.githubusercontent.com/19268555/121866907-f86e4580-cd31-11eb-926c-7d8d750e5cf6.png)

**Comment by liupan1890** [comment]
随便选择一个文件，点击创建秒传链接，点击创建，点击复制aliyunpan://

把最终的aliyunpan://链接回复给我

我需要一个文件做一下测试，看mpv是否可以正常工作

实际上。mpv是支持iso的，但是，但是，iso并不是一个格式！！
dvd/ bd/ 蓝光 /多种3D 都可以打包为iso mpv已知的问题是对dvd导航菜单（选择章节）支持的不太友好

所以，最终怎么样，还是看你的iso是哪个格式。可能直接可以播放，可能完全不能播放，取决于iso的格式

**Comment by yayaleslie** [comment]
aliyunpan://STILL BEYOND SACD08 光辉岁月 8860860.iso|F02AF50A1D58DE0B453051BB2C3D12AF2DE3E9A1|1829634048|

**Comment by liupan1890** [comment]
呃，抱歉刚看到。我去测试，应该会再下个版本支持的！

**Comment by liupan1890** [comment]
我测试过了，MPV播放器不支持播放此iso

实际上，因为 mpv已知的问题是对dvd导航菜单（选择章节）支持的不太友好，也就导致了播放的都是错误的章节。比如上面光辉岁月，正确的章节是演唱会，但mpv只识别出17个无效的章节(播放时长只有几秒)，最后就自动退出了。根本没有播放演唱会的内容。所以无法实现自动播放（通过针对每一个iso文件手动的调节播放参数，有时候也能勉强播放，但是不可能针对任意的iso自动调节播放参数，所以还是不行）

总结：使用MPV无法顺利的在线播放iso文件，需要使用专门的dvdplayer软件，或者jiangiso加载为虚拟光驱后再播放
