### ISSUE TITLE
在分享界面无法显示分享的内容

### ISSUE THREAD

**Issue by DAGUAGUAGUA** [liupan1890/aliyunpan#420]
具体如图，需要重启小白羊才能恢复

![10](https://user-images.githubusercontent.com/95030519/143439872-37ccf430-68ca-426e-85ed-04762d920a8e.gif)

**Comment by liupan1890** [comment]
收到，这肯定是BUG，我稍后检查一下，会在下个版本修正

**Comment by liupan1890** [comment]
这个BUG是怎么触发的？就是你先点什么，后点什么，就空白了？
在设置--运行日志里是否有错误记录呢？

我测试的时候，没翻车啊。。。可能和链接有关系（应该有错误日志）

**Comment by DAGUAGUAGUA** [comment]
点啥我还真不记得了，日志显示的错误如下
![image](https://user-images.githubusercontent.com/95030519/143671257-c3156900-d744-4adb-821d-13cc789e95d2.png)

**Comment by DAGUAGUAGUA** [comment]
还有一个小问题就是当一个文件夹分享出去以后，修改这个文件夹的名字，小白羊的分享列表里不能同步更新，具体如图所示，一开始分享的文件的文件名为2021，后来改成樊登读书会音频，小白羊并没有同步更新，希望作者大大下个版本能加入这个功能

![image](https://user-images.githubusercontent.com/95030519/143680359-a38db4da-0ccb-4fb7-85b4-780a366f8abe.png)

**Comment by liupan1890** [comment]
1. 等你再遇到不显示的话，你再告诉我吧，可能不太容易遇到

---
2. 分享名，你点一下刷新，显示的就是最新的分享名，跟阿里云盘网页版是一样的
注意，这个名字，官方就是保存了第一次分享时的第一个文件的名字（2021年）。你之后修改文件名（改成樊登），这个分享名并不会自动跟着修改。是一直是这个名字（2021年）

这个名字有什么用我也不知道，但是不管第一个文件是文件还是文件夹，修改文件的名字或修改文件夹的名字。分享名都不会自动跟着更新

官方也没有提供修改这个名字的按钮。---当然，在小白羊里可以自己修改这个分享名

![无标题](https://user-images.githubusercontent.com/67817756/143771401-567ffce2-2e03-478d-a0e4-0d8532150841.png)

**Comment by liupan1890** [comment]
这里并不会做成同步的自动更新，因为文件名修改的时候，并不知道哪些分享链接是根据这个文件来命名的
（1.列出全部分享链接2.查询是否是改名的这个文件3.更新分享名）
这里的联系太弱，所以并不打算提供自动更新的功能（官方也没有）

**Comment by DAGUAGUAGUA** [comment]
收到
