### ISSUE TITLE
希望可以加个Aria2断开无限自动重连的功能

### ISSUE THREAD

**Issue by YYJavaGit** [liupan1890/aliyunpan#421]
有些时候NAS性能不够网络占用太高等情况会导致Aria2的接口超时的情况
但是Aria2其实是没有死掉的 只是接口暂时没法请求 等文件下载结束后就可以正常连接了 而这时候小白羊已经自动断开连接了 导致后续文件无法继续下载 需要手动恢复 
所以希望可以加个断开无限自动重连的按钮啥的 让用户来决定是否开启无限重连

**Comment by liupan1890** [comment]
嗯，收到，会在下个版本里添加 断线自动重连的选项

**Comment by jkqxl** [comment]
还有，不知道v16版本解决没有，如果Aria2断开会无限提示小弹窗，叠加遮蔽“新建等”标题行，其实 不提示或仅提示一次 即可，毕竟最下面的状态栏会显示Aria2是否断开

**Comment by liupan1890** [comment]
嗯，在下个版本也会一起修改掉，只提示一次 （因为以前的版本没有底部状态栏，这个属于遗留问题）

**Comment by liupan1890** [comment]
在v2.11.28里已经支持aria断开后自动重连

aria断开提示，修正为约5-8秒提示一次
