### ISSUE TITLE
CDBao镜像网站打不开了

### ISSUE THREAD

**Issue by orzli** [liupan1890/aliyunpan#422]
请问是关了嘛，偶尔还进去下点音乐，今天发现打不开了。

**Comment by liupan1890** [comment]
最近一周，有流量攻击，我的服务器宽带只有2M,网卡日志里，每天网络都是满载的，
因为小白羊和CDbao在一个服务器，已经影响到小白羊的正常访问了。
所以关闭了CDbao镜像服务

其实平时真的很少有人在用，不知道是得罪谁了。。。
