### ISSUE TITLE
大佬，关于违禁视频，哈希值

### ISSUE THREAD

**Issue by bilibili2077** [liupan1890/aliyunpan#423]
大佬，小白羊既然能打开看封禁的视频文件，那应该也能下载到本地吧，播放视频的缓存也不知道在哪里，还有网上找了许多更改MD5的工具，要么不好用要么闪退，不知大佬何时能把这个小程序写出来！

**Comment by liupan1890** [comment]
1.下载
在网盘里，视频文件上，右键，详情。
会打开该视频的雪碧图（都是违规图例），点击M3U8下载，会复制M3U8下载链接，

最后，自己找一个M3U8下载软件，下载就好了。小白羊不会提供M3U8下载功能，因为正规的M8U8下载，下载后得到一堆小文件，需要附带ffmpeg，执行合并文件。ffmpeg体积40多MB，小白羊体积装不下（不正规的就是直接文件合并，也能看，但不正规）
----
2.播放缓存，需要看你使用的是什么播放软件，每个软件缓存位置都不一样，缓存也不一定是视频文件，研究这个没啥用，思路不对

---
3.改MD5，在下个版本里（明天发布），已经提供了常见视频文件格式的洗码功能。

**Comment by iD2073** [comment]
我有那个小软件
