### ISSUE TITLE
已经选择了跳过同名文件，但是上传显示还在计算has值呢？

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#426]
如题

**Comment by liupan1890** [comment]
嗯，是逻辑BUG，计算hash比跳过 流程早
不过确实是有优化的，现在也节省了一次联网对比的时间（这个对比是有频率限制的，简单的一个联网也可能会需要2秒多）

下个版本我调整一下流程，会取消hash的计算

**Comment by liupan1890** [comment]
在v2.11.29里已修正此BUG
