### ISSUE TITLE
优先下载小文件

### ISSUE THREAD

**Issue by Lwife** [liupan1890/aliyunpan#428]
**需求：**
当大文件和小文件混合下载的时候希望可以优先下载小文件。
**场景描述：**
比如当视频文件和字幕文件同时下载的时候可以优先下载字幕文件，相较于动辄好几十个G的视频文件相比，大部分字幕基本只有几十K，就可以优先下载字幕文件（如果可以自定义这个大小那自然是perfect）。
**原因：**
当大量文件同时下载的时候，如果大文件排在前面，就会在大文件下载完成之前一直不会下载小文件。虽然可以手动选择优先下载，但是当小文件大量存在，大文件也不少的时候列表中待下载文件就会堆积很多，给人的直观体验很差（虽然从总下载用时来说并不会改善）。

**Comment by liupan1890** [comment]
收到，以后会增加设置项，勾选后会优先下载小文件（小于100MB）

没有想直接按照文件大小排序后再下载，是因为当一次性下载数十万个文件时，文件排序会产生明显的性能问题

**Comment by liupan1890** [comment]
优先下载小文件已经在v2.12.01里增加，可以去置顶的v2.11.29发布 issue 里更新了
