### ISSUE TITLE
我按大佬说的用m3u8下载不了违禁视频

### ISSUE THREAD

**Issue by bilibili2077** [liupan1890/aliyunpan#429]
上个帖子按大佬说的视频详情页能打开正常文件和禁止分享的视频都能用m3u8下载，但是封禁的视频提示无法预览该文件，但是能播放，还有就是小白羊播放器进度条下面有一串网址，我把网址一个字母一个打上去可以用m3u8把违禁视频下载下来，但是很费时，想复制进度条下面的网址复制不了，折腾了很久也没能把网址复制过来，求助大佬有什么方法能下载！

**Comment by liupan1890** [comment]
[app.zip](https://github.com/liupan1890/aliyunpan/files/7615630/app.zip)


是我忘了加了屏蔽了，你下载这一份，替换 阿里云盘小白羊版v2\resources\app.asar
就能详情--M3U8了

**Comment by liupan1890** [comment]
补充一句，无法分享的视频，仍然可以正常下载。违禁的不能下载只能通过M3U8下载

**Comment by 957057** [comment]
复制地址用IDM完美下载
