### ISSUE TITLE
【BUG/优化】任务栏进度显示

### ISSUE THREAD

**Issue by KHLFYY** [liupan1890/aliyunpan#430]
我发现上传/下载文件的时候
小白羊在任务栏的进度提示 一会多一会少  反复横跳

我猜一下 
这个是用`当前下载速度`计算的`进度`吗
我觉得这样可能会导致反复横跳

如果是的话 有一个思路是
用百分比【已下(上)载量/总下(上)载量】来表示进度
不知道可不可行

如果不是的话 还请作者找一找是否存在这个bug

**Comment by KHLFYY** [comment]
好像把鼠标悬停在任务栏的小白羊图标上时 
更容易触发
![image_240](https://user-images.githubusercontent.com/76054116/143807628-53080332-b044-4b21-87cc-b4174c637202.png)

**Comment by liupan1890** [comment]
这个不是BUG，也跟鼠标无关，确实跟当前下载/上传速度有关

但不要纠结是否横跳，是否准确

这个进度只是用来提示你：当前正在下载
然后你最小化窗口（不是关闭窗口），干别的，想起来了看一眼任务栏，
没有进度条了你就知道下载/上传完了


仅仅是一个提示作用。

-----

那么为什么不进一步做的准确一点呢？能一眼看出是否快下载完了？

跟计算方式有关系：

--假如是根据文件体积去计算显示--
1.需要知道全部文件的总体积
2.需要知道最近几秒的平均速度
3.需要知道要下载的文件夹的体积

--假如是根据文件数量去计算显示--
1.需要知道全部文件的数量
2.需要知道要下载的文件夹里包含的文件数量

存在的问题：
假如一次性下载几十万个文件，那么每一秒更新下载速度时，都需要遍历几十万个文件计算，比较费性能
对于要下载的文件夹，没有轮到真的下载它时，是无法知道他包含多少个子文件/子文件夹的，也不知道它的体积
有的时候会遇到本地已经存在这个文件（之前下载过）会导致下载进度不准确
有的时候会遇到上传时秒传/大文件需要长时间计算sha1 会导致上传进度不准确

综上：
想要准确的预估整体传输速度，很麻烦，就算是认真折腾一顿，还是不准确的，只是相对准确一点点了。作用不大

**Comment by KHLFYY** [comment]
明白了 OK
