### ISSUE TITLE
是不是只有我觉得1.6.29的UI最好看？

### ISSUE THREAD

**Issue by China-Huanghe** [liupan1890/aliyunpan#431]
![image](https://user-images.githubusercontent.com/77739994/143807108-1a396a0f-5af5-4dc3-a202-c689fad7e10d.png)
YYDS

**Comment by KHLFYY** [comment]
我个人还是觉得新的更好一点
更加简洁轻量

旧的有一点花哨

但是审美这东西  仁者见仁智者见智

**Comment by iD2073** [comment]
NO

**Comment by liupan1890** [comment]
美工这个我真的不擅长，也不认识愿意免费帮我设计一整套UI的前端，所以只能自己硬头皮抄了。不够好看这点我认

**Comment by 957057** [comment]
已经很棒了

**Comment by iD2073** [comment]
阴阳脸非常不好看
