### ISSUE TITLE
windows V.2.11.29 文件完整路径过长导致无法下载

### ISSUE THREAD

**Issue by Lwife** [liupan1890/aliyunpan#433]
如图所示：
文件存放：
![文件存放](https://user-images.githubusercontent.com/44720162/144156596-53447f11-0d12-454c-9021-44ca70c2bc9f.png)
下载文件
![文件名过程无法下载](https://user-images.githubusercontent.com/44720162/144156476-ccfc798e-c92d-4c3d-a27e-caca686572a7.png)

当文件的完整路径（包含文件夹路径）过长时提示aria2c创建文件夹失败，当把该文件存放到上一级目录，或者其他稍短的目录中时即可正常下载。

**Comment by liupan1890** [comment]
收到，其实已经做了路径太长时，丢弃一级父路径的循环检测了，但似乎没能正确的执行。我去检查一下代码，会在下个版本中修复此问题

话说为什么你的下载速度只有2M/s?是你宽带问题还是你限速了还是小白羊没能满速的下载？我下载都是40+MB/s

**Comment by liupan1890** [comment]
需要你回复我出错的这个文件的完整路径

我测试了一下超长路径，并没有发现问题

网盘内文件：
\2021-11-29 18-12-072021-11-29 18-12-072021-11-29 18-12-072021-11-29 18-12-07\文件夹一文件夹一文件夹一文件夹一文件夹一文件夹一文件夹一\文件夹二文件夹二文件夹二文件夹二文件夹二\文件夹三文件夹三文件夹三文件夹三文件夹三文件夹三文件夹三\文件夹四文件夹四文件夹四文件夹四文件夹四文件夹四\文件夹五文件夹五文件夹五文件夹五文件夹五文件夹五文件夹五\123456789\223456789\延安精神放光芒（1）宝塔山下的相聚.mp4

下载时，最终下载到：
D:\xbydown\2021-11-29 18-12-072021-11-29 18-12-072021-11-29 18-12-072021-11-29 18-12-07\文件夹一文件夹一文件夹一文件夹一文件夹一文件夹一文件夹一\文件夹二文件夹二文件夹二文件夹二文件夹二\文件夹三文件夹三文件夹三文件夹三文件夹三文件夹三文件夹三\文件夹四文件夹四文件夹四文件夹四文件夹四文件夹四\文件夹五文件夹五文件夹五文件夹五文件夹五文件夹五文件夹五\延安精神放光芒（1）宝塔山下的相聚.mp4

注意：123456789\223456789 这两个文件夹被丢弃了，为了能够下载
并没有出现因为路径超长导致的报错

所以可能是别的原因，需要你回复我这个报错的文件的网盘内的完整的路径（最好是登陆阿里云盘网页版，然后直接拖选文件夹名字复制，避免一些特殊字符打错）。我按照这个路径去创建文件测试一下

**Comment by liupan1890** [comment]
哦，我测试出来了，是BUG。对超长路径时，如果是在最后的文件上点击下载，能够正确处理。如果是在第一级目录上点击下载，会报错。下个版本会修复此问题

**Comment by liupan1890** [comment]
路径BUG已经在v2.12.01里修正，可以去置顶的v2.11.29发布 issue 里更新了

**Comment by Lwife** [comment]
> 话说为什么你的下载速度只有2M/s?是你宽带问题还是你限速了还是小白羊没能满速的下载？我下载都是40+MB/s

限速了，因为我一般只会在后台进行下载，而且也不着急，就让他在后台慢慢跑呗，而且这样可以保证下载时看 YouTube 和游戏的时候不会受影响。
