### ISSUE TITLE
最上面的第一第二张图片预览总是显示不完整

### ISSUE THREAD

**Issue by iD2073** [liupan1890/aliyunpan#434]
![image](https://user-images.githubusercontent.com/87513821/144346589-bfa669d7-cd3d-4361-8656-08238f51b96e.png)

弹窗之类的窗口、菜单应该允许出界

**Comment by hongtucao8384** [comment]
美女不错

**Comment by liupan1890** [comment]
收到，我之后调整一下！（其实并不是弹窗，所以无法超出窗口，会调整为过高时自动在下方显示）

**Comment by liupan1890** [comment]
已在v2.12.05里修正此问题
