### ISSUE TITLE
视频播放能否调用html5在线播放器？(只是一个新功能小建议)

### ISSUE THREAD

**Issue by kangpou** [liupan1890/aliyunpan#436]
例如https://github.com/MoePlayer/DPlayer

用网页在线播放器一方面可以节省空间，不用另外安装本地播放器；
另一方面似乎能看弹幕。。。

呃，DPlayer不知道支不支持外挂字幕。。。

ps：小白羊非常棒，⭐️和膝盖已奉上。

**Comment by obtoo** [comment]
本地也能看弹幕的呀，如果你有弹幕文件的话
比如我就是B站下载弹幕文件，然后本地potplayer + 弹幕文件看的人生一串第三季
本地播放器不是比在线播放器更稳定么。而且有绿色版免安装的播放器可以选择
网页播放器的话为什么不直接采用阿里网盘在线观看的方式呢
potplayer很好用的，可以尝试一下

**Comment by liupan1890** [comment]
呃，是这样

当然可以直接使用Dplayer的。
假设我们使用Dplayer

1.只能播放部分格式的转码视频(就是阿里云盘网页版里能播放的那些视频)
至于视频的内嵌字幕，也跟阿里云盘网页版完全一致，部分视频有，部分视频内嵌字幕无法识别
弹幕的话不太好支持（是看Dplayer是否支持，如果支持加载弹幕文件的话+你自己下载了弹幕文件）

2.一些格式的视频不能播放（阿里云盘不支持的视频格式不能播放）
因为Dplayer并不支持播放多种格式的视频，基本就是只能播放mp4/m3u8，需要阿里云盘支持转码的，他才能播放

3.一些2k/4k高清视频可能不够清晰（转码为了网络流畅会降低清晰度）

4.一些多语的视频，无法选择音轨。一些内嵌多字幕的视频无法选择字幕

----

所以，即使使用了Dplayer，我们也还是要内置集成MPV播放器。用来让其他有需要的人，可以播放任意格式或者切换音轨等等。

然后还是要有自定义播放软件功能，因为很多人并不太习惯使用MPV播放器。每个系统上，都有流行的播放软件

-----

既然不论怎么样都需要集成播放软件，那么DPlayer就没有必要了。会造成用户选择困难
播放这个视频，是用Dplayer放M3U8,还是用MPV放M3U8,还是用MPV放原始画质？

所以一开始就没有集成Dplayer  

----

总结一句话：对于部分用户的需求，必须提供本地播放器。而提供了本地播放器后就不需要集成Dplayer了，功能被覆盖了

**Comment by kangpou** [comment]
感谢大大解惑以及耐心说明！
