### ISSUE TITLE
学习你的代码，能否上传一份有注释的么

### ISSUE THREAD

**Issue by zhengge791254521** [liupan1890/aliyunpan#437]
看到了你的项目，想要学习下关于上传逻辑的部分，但没有注释看着很烧脑啊，如果能上传一份有注释的代码就好了，感激不尽

**Comment by liupan1890** [comment]
呃，，，个人，，，，，没有那么多的注释的。。。。

又不是多人合作开发或者上班正式开发程序。。全部代码都是我自己写的，也是自己看，所以没有必要弄注释了。。。。

主要是，我每天能写代码的时间不多，所以能少打几个字就少打几个字了，

跟在公司上班，按开发文档写功能，确实还是不一样的。。。

**Comment by zhengge791254521** [comment]
关于下载的工具area2,  没太搞明白那个啊。 虽然看了下文档。还是一知半解的。 本地启动area的话，那个host是localhost， port可以随机生成么，还是需要自己在本地用node启动一个server才行，我看你的代码，并没有启动，只是主进程执行了一些命令。 小白对这一块实在不懂啊
