### ISSUE TITLE
希望能添加数据库路径自定义的功能

### ISSUE THREAD

**Issue by Sakura1338** [liupan1890/aliyunpan#438]
如果在v2版本中的数据库路径只能被放置在AppData\Roaming路径下，对于有系统盘还原程序的电脑就不是特别友好了。希望能添加一个自定义数据库路径的功能，比方说在程序目录下放置一个conifig.ini文件来进行指定
![image](https://user-images.githubusercontent.com/61232882/144618519-de7575a7-90fe-4bc7-a9ca-25aea823562e.png)

**Comment by liupan1890** [comment]
下载替换 [1203.zip](https://github.com/liupan1890/aliyunpan/files/7653264/1203.zip)


参见 https://www.yuque.com/liupan1890/xiaobaiyang/lg9s3b 缓存位置设置

**Comment by Sakura1338** [comment]
万分感谢！
