### ISSUE TITLE
为什么GPU使用率一直这么高，这个软件长时间占用我的HD630集显40-60%的使用率

### ISSUE THREAD

**Issue by jayleejaylee** [liupan1890/aliyunpan#44]

**Comment by liupan1890** [comment]
当你开启小白羊后，有3个进程
1.阿里云盘小白羊版.exe  (负责UI渲染 flutter)
2.aliserver.exe (负责管理下载上传任务 golang)
3.aria2c.exe (负责下载 c++)

当您提到GPU使用率一直这么高，我想是阿里云盘小白羊版.exe这个进程，因为其他进程不涉及GPU

那么请观察一下回复我，
1：是在所有的页面都很高，还是在下载列表页面很高？
2：点击最小化/X号，关闭了窗口 （后台仍在正常下载），还高吗？


如果是所有页面都很高，那可能是flutter渲染的问题，并不是我编写程序的问题
如果是只在某一个页面很高（比如下载列表页面），那就是我程序写的有问题，等你回复我是哪一个页面占用高我就能针对的去检查了

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/121990866-1b036b80-cdd1-11eb-8a9d-a8d4f702b552.png)

我看了一下，在我的电脑上占用不高。不操作时基本是0，有频繁的操作时（比如大量下载时，打开下载列表页面，此页面在频繁刷新下载进度）也只有2-4%，很少有15%以上的时候

**Comment by liupan1890** [comment]
临时性的解决办法就是，当你操作完，比如点击下载后，或者平时不操作时，就点击X号关闭窗口，等需要操作时就右击托盘图标显示主界面。关闭窗口后肯定就不会有GPU占用了。flutter的更新频率并不高，可能之后几个版本也无法解决此BUG---此BUG应该不是普遍性的

**Comment by jayleejaylee** [comment]
阿里云盘小白羊版.exe 这个进程占用率高
只要停留在上传中这个界面，占用率就高
其他界面GPU占用率都正常

![sshot-1](https://user-images.githubusercontent.com/20895760/121992222-cc0b0580-cdd3-11eb-9e13-41cda877c833.png)

**Comment by liupan1890** [comment]
那么是否有大量的上传任务呢？
1.有很多已经上传完成的任务---已上传页面
2.有很多正在上传中的任务--正在上传页面

我想应该是频繁刷新上传进度造成的(1秒刷新一遍)，但是实际上也不应该出现，因为每一遍只会更新20条记录（只更新能看到的20条记录，就算你有1万条正在上传，实际都不更新，没有影响才对）。我稍后会检查正常上传页面的代码，看是否可以优化性能
