### ISSUE TITLE
视频文件洗码功能是自动进行的吗

### ISSUE THREAD

**Issue by jimodeniuren** [liupan1890/aliyunpan#440]
好像在上传的时候并没有发现有选项可以选

**Comment by jimodeniuren** [comment]
哦不对发现有插件

**Comment by liupan1890** [comment]
不是，是你自己手动操作的

自己选择视频，自己点击洗码，自己上传

自动操作：是小白羊帮助某些人绕开阿里云盘限制
手动操作：是某些人自己绕开阿里云盘限制

举个例子：
卖刀？合理。用户买刀后干啥？跟我无关对吧？

卖刀的同时自动帮助xxx，不合理

**Comment by potus2030** [comment]
这个功能一言难尽，是对网络与存储功能的极大浪费。不建议增加这个功能。咱不能把网盘都玩死对不对。
