### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by guochangxin1999** [liupan1890/aliyunpan#441]
软件大全论坛自上次以后坛友们加了几千资源希望能通过
http://rjdq.huofh.club

**Comment by liupan1890** [comment]
好的，稍后会加上

**Comment by walker8** [comment]
> 好的，稍后会加上

借楼推荐一个乐愚社区[https://bbs.leyuz.net](https://bbs.leyuz.net) ，学习和软件类资源比较丰富

**Comment by liupan1890** [comment]
@walker8  你好，
1. 小白羊内只是推荐了几个阿里云盘分享网站，并未增加综合类网站
2. 小白羊的用户其实并不太多，宣传效果极其有限

**Comment by walker8** [comment]
> @walker8 你好，
> 
> 1. 小白羊内只是推荐了几个阿里云盘分享网站，并未增加综合类网站
> 2. 小白羊的用户其实并不太多，宣传效果极其有限

好吧~_~不过软件确实很好用
