### ISSUE TITLE
程序无法正常关闭

### ISSUE THREAD

**Issue by MoonAsked** [liupan1890/aliyunpan#447]
https://user-images.githubusercontent.com/61685920/144848179-385ac5d1-37ef-4d41-9d1b-abe6c6caa6bd.mp4

<img width="598" alt="截屏2021-12-06 下午8 51 01 1" src="https://user-images.githubusercontent.com/61685920/144849284-22fc5b70-d113-4c2e-ba60-a4aaf25ab295.png">

  出了个bug，无法正常退出程序，包括程序坞和快捷键 com + q
  只能通过强制退出类似win任务管理器关闭程序，最大的问题是关机的时候因为这个关不掉，电脑也关不了
  另外重新装了一下程序，没有解决，不过数据暂时没有删，删了要重新登陆三个号麻烦，先提出来看下情况👀👀

**Comment by liupan1890** [comment]
右上角，小白羊图标，彻底退出小白羊

在下个版本会恢复quit退出功能

是因为之前有人说过花+Q退出容易误按，所以2.12.05里是修改成花+Q隐藏（最小化），右上角任务栏图标里的彻底退出才是退出

另，如果不习惯，也可以在设置里，勾选关闭窗口后立即退出小白羊  选项。勾选后点击小白羊界面上的X就退出了（默认点击X是隐藏-最小化窗口）

会在下个版本里恢复quit

**Comment by MoonAsked** [comment]
谢谢大佬解答，下面是我的疑问，可以不用看，不重要，只是发泄下。

挺不清楚这个快捷键为啥会容易误触，mac其他所有我用过的软件都是这个快捷键方式退出的，难道用这个软件的人不用其他软件么，或者用其他软件就不会误触么，有点开喷的味道，舒缓下心理
