### ISSUE TITLE
使用自定义播放软件可以保留播放进度或者自动跳转播放进度吗？

### ISSUE THREAD

**Issue by oliverxu1** [liupan1890/aliyunpan#448]
使用自定义播放软件可以保留播放进度或者自动跳转播放进度吗？

**Comment by liupan1890** [comment]
保留播放进度或者自动跳转播放进度，总结就是在指定的时间开始播放

使用自定义播放器，从程序上将，就是对你自己选择的播放软件说一句：hi，放一下url

有的播放软件，支持设置从指定的时间开始播放 （hi，跳转到00：10：00，放一下url）
有的播放软件不支持从指定的时间开始播放

但是，不同的播放软件，调用的具体参数都不一样。这个是因为不同的播放软件是由不同的作者制作的

我也没有经历去翻一遍所有的播放软件，检查它是否支持时间参数，

所以，最终结果是不行

**Comment by sofish0** [comment]
那自带的那个也不支持吗
