### ISSUE TITLE
希望可以增加webdav协议的支持，非常期待这个上线，支持大佬。

### ISSUE THREAD

**Issue by burtton99** [liupan1890/aliyunpan#45]
希望可以增加webdav协议的支持，非常期待这个上线，支持大佬。

**Comment by liupan1890** [comment]
我记得在github上看到过，一混我告诉你网址。webdav我没接触过，，，不懂啊，以后有时间我研究一下

**Comment by liupan1890** [comment]
https://github.com/zxbu/webdav-aliyundriver

**Comment by burtton99** [comment]
> https://github.com/zxbu/webdav-aliyundriver

嗯嗯，这个看过的，但是更希望能出一个阿里云盘原生支持的webdav协议。就像国内的坚果云盘，目前国内就坚果云盘支持，但是会限制流量和上传文件的次数。
我自己没有服务器基础搭建这个网站里面说的这些，谢谢啦。

**Comment by liupan1890** [comment]
鞥，后期我会研究一下！争取加上

**Comment by zhuaohong** [comment]
之前6pan也支持webdav，可惜6pan倒了。

**Comment by liupan1890** [comment]
昨天研究了一下webdav

最后决定放弃了

1. 通过webdav复制（下载）文件到本地时，只能单线程http下载，一方面下载速度并不稳定，另一方面是出错时无法自动重新下载，
比如你复制了一个4GB的文件到D盘，可能需要半小时，这半个小时里就一直显示windows的复制窗口，不能关闭。
比如你复制了一个文件夹到D盘，那么如果复制过程中某一个文件复制失败了，不会自动重新下载

2.通过webdav上传文件夹时，也比较容易出错

3.不论是上传还是下载，webdav的操作都无法融合进小白羊的上传/下载列表页面里。

4.webdav要求小白羊开机自动启动（这样开机后才能自动挂载），并且一直保持在后台运行（这样才能随时操作挂载的磁盘）

虽然挂载成本地磁盘操作时确实十分方便，但主要还是适合文件的重命名/移动操作 ，复制文件操作，上传文件夹操作，下载文件操作都需要特殊处理并且不够稳定优雅

如上，最后就放弃了，不会继续去研究实现webdav功能了

**Comment by burtton99** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的吧，既然大佬这样说了，那就这样吧。主要我的用途也比较单一，就是有个笔记软件支持这个webdav协议，我是希望能保存到自己可信赖的网盘里面。目前国内就坚果云支持，但是官方做了文件数量同步限制，一旦笔记多起来，就会锁住。那可以再提一个本地同步盘的需求嘛，大佬。
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                350174676
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月30日 ***@***.***> 写道： 



昨天研究了一下webdav
最后决定放弃了

通过webdav复制（下载）文件到本地时，只能单线程http下载，一方面下载速度并不稳定，另一方面是出错时无法自动重新下载，
比如你复制了一个4GB的文件到D盘，可能需要半小时，这半个小时里就一直显示windows的复制窗口，不能关闭。
比如你复制了一个文件夹到D盘，那么如果复制过程中某一个文件复制失败了，不会自动重新下载

2.通过webdav上传文件夹时，也比较容易出错
3.不论是上传还是下载，webdav的操作都无法融合进小白羊的上传/下载列表页面里。
4.webdav要求小白羊开机自动启动（这样开机后才能自动挂载），并且一直保持在后台运行（这样才能随时操作挂载的磁盘）
虽然挂载成本地磁盘操作时确实十分方便，但主要还是适合文件的重命名/移动操作 ，复制文件操作，上传文件夹操作，下载文件操作都需要特殊处理并且不够稳定优雅
如上，最后就放弃了，不会继续去研究实现webdav功能了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liupan1890** [comment]
本地同步盘 正在做
