### ISSUE TITLE
用这个图标吧

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#452]
![image](https://user-images.githubusercontent.com/83964337/145009754-9cb1710a-0c67-40c8-9ad8-882f1aad279c.png)
![RoundCornerImage](https://user-images.githubusercontent.com/83964337/145009769-42a7f2d5-1306-4cec-b850-977f3aa5b562.png)

**Comment by liupan1890** [comment]
呃，我理解的是，你想让我把小白羊的图标替换成这个图片对吧

但是，这个图片吧和阿里云盘官方相似度过高。可能会有版权纠纷，所以无法使用

就好比 康师傅 康帅傅 后者一般被认为属于假冒品牌了，必然会有版权纠纷的

**Comment by jjjyyyllll** [comment]
不用

**Comment by mylyed** [comment]
这个太丑了
