### ISSUE TITLE
小白羊有没有兴趣开发群晖版本？

### ISSUE THREAD

**Issue by n1900n** [liupan1890/aliyunpan#458]
入了一台群晖，下载方面电脑的使用率大大降低，依靠手机就行，非常方便。不知道小白羊有没有兴趣开发群晖版本？自己现在是通过群晖虚拟了个windows系统然后再使用。迅雷官方也在开发和改进群晖的版本，这也算是一种趋势或者说尝试？仅仅是个提议，最后感谢小白羊的开发者，开发了这么好用的一个软件！

**Comment by liupan1890** [comment]
呃，我从来没有用过群晖，手里也没有群晖，

因为没有真机测试，开发的程序可能会有很多BUG

所以并没有开发群晖版本的打算

**Comment by ifree8** [comment]
> 

安卓TV版 有计划吗？这个需求还是挺大的

**Comment by gbm777** [comment]
其实只要开发 linux版本就行
