### ISSUE TITLE
好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [liupan1890/aliyunpan#46]
![image](https://user-images.githubusercontent.com/53843550/122224191-74a98a00-cee6-11eb-9b33-560e176d3317.png)

[收录地址](https://www.macwk.com/soft/aliyun-drive-xiaobaiyang)

**Comment by macwkcom** [comment]
如果开发者觉得不合适，回复我一下，我把它下掉。

**Comment by liupan1890** [comment]
感谢收录，可以帮我宣传的，开源软件，版权开放，没有不合适的。

注：已测最新M1是不兼容的，只有X86处理器的mac可用

**Comment by macwkcom** [comment]
> 感谢收录，可以帮我宣传的，开源软件，版权开放，没有不合适的。
> 
> 注：已测最新M1是不兼容的，只有X86处理器的mac可用

不对呀，我是使用了三台测试机测试的，一台 10.15.7，一台 intel 11.2，一台 m1 11.3 测试的，都可以用呀。12 倒是真闪退。

**Comment by liupan1890** [comment]
12 倒是真闪退  嗯，说的就是他

因为界面是flutter开发的，而flutter有专门的M1版本，
正常情况应该是，我有一台M1,安装flutter开发工具，打包发布
但是我没有。。。。。。无解了，只能靠转译，但转译后有的版本会闪退，我也没有条件测试具体哪些版本会闪退

**Comment by macwkcom** [comment]
我现在完全不处理任何和 12 相关的问题，这系统还处于开发阶段，只能算是个半成品。

**Comment by liupan1890** [comment]
厉害，我看了您的网站，太厉害了，我不用mac，但我也感受得到网站的认真，不是那些用一堆堆的软件（旧版本）胡乱堆砌的，站长很用心啊。。。。厉害了

**Comment by macwkcom** [comment]
> 厉害，我看了您的网站，太厉害了，我不用mac，但我也感受得到网站的认真，不是那些用一堆堆的软件（旧版本）胡乱堆砌的，站长很用心啊。。。。厉害了

你这夸的我都有些不好意思了呀。

还有一件事情，小白羊我在打包的时候我用我自己的证书签名了一下。

另外，我还有一个疑问，应用名称为何包含了版本号呀，在 macOS 里面这个应用名称太长了：`阿里云盘小白羊版v1.6.3`。

![image](https://user-images.githubusercontent.com/53843550/122233545-bf2f0480-ceee-11eb-8975-2b1bc9cfbace.png)

**Comment by liupan1890** [comment]
关于名称里的版本号，你可以直接去掉的，直接改成阿里云盘小白羊版就可以的。没有影响

如果签名后的app更容易安装（最起码不需要先在终端里输入命令后才能运行），那么我可以把MAC版本的下载地址链接到你的网站，让大家直接使用你签名后的版本。我没有证书，以后也不可能给小白羊签名的。

不知道你愿意吗

**Comment by macwkcom** [comment]
> 关于名称里的版本号，你可以直接去掉的，直接改成阿里云盘小白羊版.app就可以的。没有影响
> 
> 如果签名后的app更容易安装（最起码不需要先在终端里输入命令后才能运行），那么我可以把MAC版本的下载地址链接到你的网站，让大家直接使用你签名后的版本。我没有证书，以后也不可能给小白羊签名的。
> 
> 不知道你愿意吗

这感情是好啊，这不是我愿意不愿意的事情，而是你喜不喜欢的事情，哈哈哈。

**Comment by liupan1890** [comment]
好的，等我明天有空了会链接过去。

**Comment by macwkcom** [comment]
> 好的，等我明天有空了会链接过去。

给个联系方式呗，咱们后面在那儿聊呀，在这儿还是不怎么方便😁，这儿不方便发你可以发到我的邮箱 macwk.com@gmail.com

**Comment by liupan1890** [comment]
已发

**Comment by macwkcom** [comment]
历害的开发者以及很愉快的沟通。
