### ISSUE TITLE
【建议】文件大小的显示改为两位小数位

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#469]
刚才看了下网盘总容量，小白羊是“6.9TB / 7.4TB”，感觉还有500G；阿里是“6.94TB / 7.35TB”，其实只剩410G，相差了90G，误差还是有点大了吧。

在具体文件大小的显示上也是一样，有时几个文件明明不是一样大小的，看上去变成同样大小了，不利于快速判断是否文件有重复（同一文件不同文件名）。

不知道为什么小白羊设计为只显示一位小数？改为两位更符合习惯，也更精确。

**Comment by liupan1890** [comment]
好的，以后会修改为2位小数

为什么？是因为我认为一位就够了，所以就显示的一位
