### ISSUE TITLE
无法连接到Aria2 localhost:29384

### ISSUE THREAD

**Issue by ShimmeringLight** [liupan1890/aliyunpan#470]
![image](https://user-images.githubusercontent.com/33362058/146148659-b978e7d8-e169-4d4e-995c-850dbb2756e6.png)
经查 natstat  -ano | findstr "29384"无信息

系统：Windows 10

**Comment by liupan1890** [comment]
请问是第一次使用小白羊吗？还是以前可以正常使用，今天遇到的这个错误？

错误原因是aria2c.exe没有正确的运行

提到natstat无信息，可以排除因为端口29384被占用导致的aria2c.exe无法运行

除此之外，还有一些原因会导致aria2c.exe无法运行

1.路径钟有特殊字符
2.没有运行的权限
3.系统杀软误杀aria2c.exe这个文件

可以先自己查看一下是否存在 “阿里云盘小白羊版v2\resources\aria2c.exe” 这个文件，双击此文件是否可以运行（在任务管理器钟是否有aria2c.exe进程）

然后还可以试一下重启电脑（因为没有办法了，瞎试试看）

因为aria2c.exe这个文件，是使用的非常普遍的（很多软件在使用他），一般和win10版本无关。仅仅和你电脑环境有关系

**Comment by ShimmeringLight** [comment]
已重启解决……
