### ISSUE TITLE
Windows 10 专业版21H1打开之后汉字出现方框框

### ISSUE THREAD

**Issue by wanglaihuai** [liupan1890/aliyunpan#48]
全英文目录，没有空格。
font文件夹的字体也安装到系统了。
如图所示：
![Snipaste_2021-06-18_12-53-41](https://user-images.githubusercontent.com/21361266/122508365-76816380-d034-11eb-826e-b49918bd107c.png)

**Comment by liupan1890** [comment]
这就是个严重的BUG了，第一次有人提交。。

首先：font文件夹下字体不需要安装，因为是自动从文件加载的，不是从系统加载的。所以不需要你手动安装到系统

然后：出现方框肯定就是字体问题。但是在我的电脑（或者说那么多用的人的电脑上）并没有发现方框，说明还是跟你的电脑有很大关系（比如你下载的安装包字体文件损坏了--几率很小，比如你的系统安装了一些字体可能会冲突了，比如你系统安装了某些字体软件会强制覆盖软件的字体啦，等等等等，总之还是需要具体到你电脑去分析）

最后，方框是因为找不到这个字，无法显示，只能用方框替代。但是即使字体文件损坏，应该会显示操作系统的默认字体里面的文字才对（表现为2种字，有的字大有的字小，或者有的字粗一点有的字细一点），偶尔几个字方框才对。但你这是大多数字都是方框


等我去测试一下字体损坏或者丢失的情况下flutter的渲染结果。稍后回复

**Comment by liupan1890** [comment]
请尝试手动删除

阿里云盘小白羊版\data\flutter_assets\assets\fonts\OPPOSans-R.ttf

这个文件，默认采用的是这个字体。但经过我测试确认，直接删除此文件后，会自动加载系统默认字体显示

你试一下删除后，重新打开软件（注意一定要在系统托盘图标上右键鼠标，显示`显示主界面`和`彻底退出并停止下载`点击`彻底退出按钮`  正确退出后重新打开小白羊。。如果你不知道那就重启电脑，删除OPPOSans-R.ttf，最后打开小白羊）

看看删除自带的字体后是否能够正常显示

注：不要删除iconfont.ttf 它是小图标们的字体

**Comment by liupan1890** [comment]
鞥，我还真找到了BUG，等晚上我在这里给你上传一份修正版你试试。

**Comment by liupan1890** [comment]
[阿里云盘小白羊版切换字体.zip](https://github.com/liupan1890/aliyunpan/files/6676963/default.zip)
