### ISSUE TITLE
Aria2下载到远程时会加上网盘内的全路径

### ISSUE THREAD

**Issue by Madao1994** [liupan1890/aliyunpan#481]
使用aria2下载到远程服务器的时候，会自动在下载地址后面加上网盘内的路径，并且没有地方修改，比如从网盘下载电影到nas电影文件夹，本来像直接下载到电影文件夹下面，实际上会在电影文件夹下面创建网盘的文件路径，希望可以增加一个每次下载的时候可以输入下载路径的功能，并且可以不加上网盘路径

**Comment by liupan1890** [comment]
设置--传输--文件下载保存位置--新建下载任务时按照网盘完整路径保存

我知道你是说的aria远程下载，但取消此勾选，aria远程，也会生效，会取消附加网盘完整路径

强调：仅对取消勾选后的，新建的任务有效。之前已经创建的下载任务，仍然是按照之前的设置（完整路径）

**Comment by Madao1994** [comment]
是这里这个配置吧，我试了一下，本地下载没问题，确实每次都会弹出对话框让我选择下载位置,但是aria远程下载没有效果，是我打开的方式不对吗，我使用的版本是 v.2.9.24-windows
![alidrive](https://user-images.githubusercontent.com/21969904/146679322-e24a7fd9-973d-47a8-9742-9a9a6a03481f.png)

**Comment by liupan1890** [comment]
是你使用的版本不对，v2.9.24不支持aria下载时取消网盘完整路径，需要使用v2.12.05才有这个选项

**Comment by Madao1994** [comment]
明白了,感谢
