### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by wzfliuy** [liupan1890/aliyunpan#486]
1、希望在上传的时候保留文件夹的层数，比如我上传的文件夹是1，里面有子文件夹2-10，我希望我在“上传中”可以看到1，然后点击进去可以看到1-10，和官方一致。这样做的好处是，我现在上传的文件夹是500g的，但是我的移动硬盘不够大我需要边上传边删除，如果是有层次的文件夹系统我可以很清楚的看到哪个文件夹已经上传完毕在本地可以删除。
2、希望可以出一个功能按钮，在删除完毕自动删除本地文件，也是针对于上面同样的使用情况。

**Comment by liupan1890** [comment]
收到，不过咱们需要讨论一下，"上传的时候保留文件夹的层数"

--

500G的移动硬盘，上传一部分，删除一部分。。。

问题一：那么为什么不先选择一个（几个）子文件夹上传。等全部上传完，然后删除。重新选择其他子文件夹上传呢？
既：手动在网盘创建一个文件夹1，选择硬盘上的2，3子文件夹上传。上传完，删除2，3.继续选择硬盘上4，5子文件夹上传

--

问题二：为什么不等500GB全部上传完以后，一次删除500G呢？
我明白肯定是一边往移动硬盘里复制新的文件（需要先删除腾出空间），一边上传文件
但是为什么不能等500G全部上传完了以后，再往移动硬盘里复制新的文件呢？500GB，家庭千兆光纤应该也需要6-7个小时才能上传完

**Comment by wzfliuy** [comment]
> 收到，不过咱们需要讨论一下，"上传的时候保留文件夹的层数"
> 
> --
> 
> 500G的移动硬盘，上传一部分，删除一部分。。。
> 
> 问题一：那么为什么不先选择一个（几个）子文件夹上传。等全部上传完，然后删除。重新选择其他子文件夹上传呢？ 既：手动在网盘创建一个文件夹1，选择硬盘上的2，3子文件夹上传。上传完，删除2，3.继续选择硬盘上4，5子文件夹上传
> 
> --
> 
> 问题二：为什么不等500GB全部上传完以后，一次删除500G呢？ 我明白肯定是一边往移动硬盘里复制新的文件（需要先删除腾出空间），一边上传文件 但是为

**Comment by wzfliuy** [comment]
我的使用场景是这样的：
     我在一家即将关闭的网盘A上有差不多2t文件（开始我并不知道有多少，因为不显示使用容量，这是我下载到现在估计出来的），最大的一个文件夹是509G，其它的有50g，120g，200g，还有两个未知容量的文件夹。宽带是100M光纤。
        我现在有个1T的移动硬盘，需要先把网盘A里面的文件下载到移动硬盘上，然后把移动硬盘上的文件上传到阿里云网盘上。所以最优解是先下载上传删除小一些的文件夹，不断的腾出空间保证下载和上传的不间断。    
       但由于我最开始的容量估计错误，以为1T的移动硬盘可以完全装的下，而且听说阿里网盘不限速，所以直接下载上传的509g的文件夹，通过24小时不间断的挂机应该很快可能完成任务。
       但是我没有料到不限速的阿里网盘并没有达到预期的使用目标，我现在用小白羊的上传（开启了同时上传60个任务，509g这个文件夹中有几十万个文件）速度波动是80kb,120kb，160kb，200kb，瞬间在1m的速度然后马上又跳到80kb，我已经上传了3天三夜，只上传了200g。而且由于小白羊在上传中界面没有文件夹的层次结构，是一大堆单个文件，我并不知道哪些文件夹已经上传成功，无法停止改用按小文件夹分批次的上传方法继续。
       我也曾使用阿里网盘的官方客户端一起上传，文件夹为55g，现在卡在了上传到22g，开一整天也不动，一直转圈。
       当前的情况是我只开了小白羊上传，速度还是如上，下载早就已经停止了，只等什么时候小白羊把这个509g的文件夹上传完成再继续。而且在上传过程中出现数十个文件红色显示“读取文件失败（已删除/没权限/锁定中）”也不知道具体是啥原因。

**Comment by liupan1890** [comment]
抱歉一直没注意到你的回复

1.正常情况下，在国内上传时，不应该上传速度只有200kb，我上传都是满速5MB/s (300M移动，30MB上行)
不要仅仅看到小白羊界面上显示200kb/s就认为上传速度是200kb/s
因为对秒传文件，对超小体积文件，小白羊统计的上传速度并不准确。看任务管理器里面的网络上传也有一定参照意义，但秒传的文件，是不需要消耗流量的

你可以尝试用阿里云盘网页版上传一个大文件，看看上传速度。这是真正的上传速度。如果网页版上传3MB/s,小白羊上传只有200kb/s那说明是小白羊有问题，我本地测试，小白羊和网页基本一致

2.使用阿里网盘的官方客户端一起上传，文件夹为55g，现在卡在了上传到22g
阿里云盘官方客户端，对大量文件并不支持，官方的帮助是说，一次只能上传1000个文件，不管文件大小，只管文件数量。实际测试，当超过1万个文件（也跟文件夹数量有关）时，一般官方客户端就不太合适了，可能会失败，可能会卡，

如果是上传大量小体积文件（几MB一个）还是推荐小白羊，速度更快

3.只等什么时候小白羊把这个509g的文件夹上传完成再继续
不需要，只要你上传过一次，以后上传这个文件都是秒传的，秒传速度非常快。
所以，此时你完全可以，删除小白羊内剩余的全部上传中任务。

然后，然后再你的阿里云盘里新建一个文件夹，重新把509G文件上传到这个新建的文件夹里（不要一次整个拖过去，而是自己分批的，选择几个子文件夹，分批上传），这样可以达到你想要分批的知道具体的上传进度的目的，也可以达到你上传一部分，删除一部分的目的。以前上传过的那部分文件，并没有白白浪费时间，重新上传是秒传的

4.在上传过程中出现数十个文件红色显示“读取文件失败
那就是读取文件失败了，为什么？原因有很多，一般是这个文件当时被别的程序打开了（比如正巧被杀毒软件扫描，比如正巧你正在下载中还没下载完），不用在意，稍后会自动重试。实在不行，就拔掉移动硬盘稍后重新插上，小白羊会自动重试错误的任务

需要特别提示，假设你之前用的是百度网盘，从百度网盘下载一个电影，此时是下载到“d:\baidudownloads\xxx.mp4.downloading”,等到这个电影下载完会被百度网盘客户端重命名为“d:\baidudownloads\xxx.mp4”

如果你在这个电影下载中时，手动选择整个“d:\baidudownloads\"文件夹到小白羊上传，小白羊会创建“d:\baidudownloads\xxx.mp4.downloading”的上传任务，
1.此时xxx.mp4.downloading正在被百度网盘客户端打开，所以小白羊会显示失败
2.等一个小时电影下载完了，xxx.mp4.downloading文件没了，所以小白羊还会显示失败
