### ISSUE TITLE
列出文件列表时能否提供一个选项只列出被屏蔽的文件

### ISSUE THREAD

**Issue by mali321321** [liupan1890/aliyunpan#488]
列出文件列表时能否提供一个选项只列出被屏蔽的文件

**Comment by mali321321** [comment]
另外，任务栏的进度提示不准，我刚开始任务进度条就满了：

![tempsnip](https://user-images.githubusercontent.com/84053987/147377024-5fafb4da-1243-4aec-9d3d-a5854f525696.png)

**Comment by liupan1890** [comment]
1. 任务栏提示，仅用作下载状态提示（有任务正在下载中/全部任务已下载完），并非准确的进度提示
2. 列出文件列表时能否提供一个选项只列出被屏蔽的文件（违禁文件？）（因为被屏蔽的文件，数量很少，所以没有实用性）

以后会有全盘扫描的功能，可以指定扫描出全盘内的违禁文件/禁止分享状态文件/重复文件
