### ISSUE TITLE
V 2.12.05  删除一个26TB的文件夹后从回收站恢复时特别慢的问题

### ISSUE THREAD

**Issue by ifree8** [liupan1890/aliyunpan#489]
V 2.12.05  误删除文件夹，因为文件夹数据多，26T，后来从云盘客户端恢复，结果只有一个目录出现，空间没有减少，数据不见了，能找回吗？

**Comment by ifree8** [comment]
26T的数据不见了....

**Comment by liupan1890** [comment]
>后来从云盘客户端恢复，结果只有一个目录出现，空间没有减少

我理解为，假设你的网盘有30TB，已用29TB，
你删除了一个文件夹（里面包含很多文件/文件夹，总体积为26T）
当你在小白羊内删除后，此文件夹，会被移入回收站，并且你的网盘已用空间不会减少（仍旧是29TB）
这是因为阿里云盘的回收站是占用网盘空间的。

**也就是说是正常的删除操作**


>数据不见了，能找回吗？

在回收站里，恢复这个文件夹即可，这个文件夹里面包含的文件/文件夹（26T），会自动恢复

1.但是，阿里云盘对文件操作比较慢，可能会出现，你点击还原文件后，网盘里只有一个空的文件夹，过几秒/几分钟刷新，会显示出一部份文件，过几小时以后刷新，会显示出全部文件。这个是阿里云盘恢复慢的问题，并非程序问题

2.如果你点击还原后，长时间后，文件（26T）仍然没有全部恢复，甚至仍然是空的文件夹，那么请联系阿里云盘官方客服，这个仍然是阿里云盘的问题，和客服咨询一下，是否阿里云盘不支持恢复这么多的文件

再小白羊V 2.12.05里没有彻底删除的按钮，所有，所有删除的文件都可以从回收站恢复，不会出现你点击删除，文件就丢失的情况

同时，只要你网盘已用空间一直是29TB，那就说明你的文件仍然在，（回收站/网盘）并没有丢失
能想到的极端情况是，阿里云盘的恢复文件功能有问题，没有正确的恢复（比如恢复用时很久，或者文件太多恢复时队列溢出，或者恢复文件时会检查网盘剩余空间，剩余空间1TB少于26TB导致的无法恢复）

但即使无法恢复，那么回收站里文件也应该不会丢失

---

需要提示的是，在小白羊设置--网盘--自动清理回收站 设置项，默认不开启，用户可以手动开启，选择2天-30天
比如选择2天，则当你删除文件夹后，此时文件夹是在回收站，并且，网盘占用空间仍然是29TB，2天后，当你打开小白羊后，会自动从回收站清理掉这个文件夹，清理后，网盘占用空间会变为3TB

如果你开启了此设置选择2天，并且2天以后才想起来恢复文件，那么此时文件可能已经被清理（彻底删除），确实无法从回收站看到，也无法恢复，网盘占用空间会变为3TB

**Comment by liupan1890** [comment]
总结：
1.v2.12.05没有彻底删除功能，你删除的文件可以在回收站看到，并可以恢复
>如果没有回复，等一下再看，或者联系官方客服，咨询汇报这个BUG，此BUG不是小白羊的问题，是阿里云盘官方回收站功能问题

2.如果你手动开启了自动清理回收站功能，并且满足间隔天数，并且开启着小白羊客户端，那么可能会被自动清理，无法恢复
>因为你提到，空间没有减少，感觉不是这个情况

**Comment by ifree8** [comment]
好的，感谢用心回复，我看到了文件夹陆续出现了，只能说官方的恢复太慢了

**Comment by liupan1890** [comment]
嗯，误报就好，幸亏不是真的文件丢失，那后果就太灾难了

**Comment by liupan1890** [comment]
另，提示一句，你是直接删除的一个文件夹（26T），
如果你是删除的里面的一堆子文件夹，然后再回收站里恢复一堆文件夹，会比较快

阿里云盘是，一个文件夹，作为一个任务，然后去执行这个任务

你的情况是，一次要恢复26T文件

如果是先删除的一堆子文件夹，再恢复，阿里云盘是同时执行多个文件夹恢复的任务，也就是多个任务分别单独的同时执行，那么恢复的就比较快

完全搞不懂阿里云盘为什么这样设计，在移动文件/复制文件/导入分享链接/从回收站恢复文件 时，都是超级慢

**Comment by ifree8** [comment]
是的，这或许后期会改善，毕竟目前的问题 太多要处理
