### ISSUE TITLE
Win 7 启动直接黑屏卡死

### ISSUE THREAD

**Issue by xiaokaixuan** [liupan1890/aliyunpan#49]
![image](https://user-images.githubusercontent.com/7234473/122542294-1d79f580-d05d-11eb-80af-0d060f09700f.png)

**Comment by liupan1890** [comment]
抱歉，这种黑屏卡死属于flutter本身的BUG。因为用的是最新的Flutterv2.2.1 BUG确实有很多

我的开发机也是Win7 
![无标题](https://user-images.githubusercontent.com/67817756/122560855-b1ef5280-d073-11eb-91c9-02dec6133133.png)


你等我给你上传一份v6.1.10试试看，用的是Flutter v2.0.6

**Comment by liupan1890** [comment]
https://ws28.cn/f/5p3us9kaelq 复制链接到浏览器打开

**Comment by pkids** [comment]
`https://ws28.cn/f/5p3us9kaelq 复制链接到浏览器打开`

大佬好！这个连接下载不了了，我是win7 32位系统的，下载通用版提示执行不了，想下载这个版本碰碰运气，但是提示文件已过期，能不能再提供一个链接，我下载试试呀？

**Comment by liupan1890** [comment]
> `https://ws28.cn/f/5p3us9kaelq 复制链接到浏览器打开`
> 
> 大佬好！这个连接下载不了了，我是win7 32位系统的，下载通用版提示执行不了，想下载这个版本碰碰运气，但是提示文件已过期，能不能再提供一个链接，我下载试试呀？

UI采用的Flutter，
Flutter不支持32位。它支持64位的windows,macox,linux,甚至它支持arm处理器，但是，它不支持任何的32位。所以很抱歉的是我也无法提供32位可运行的程序

**Comment by xiaokaixuan** [comment]
@liupan1890 过期了 能否再补下链接  我看下能不能用？Win 7 x64

**Comment by liupan1890** [comment]
直接下载v1.6.21就可以了

**Comment by xiaokaixuan** [comment]
还是不行 。双击启动，先白屏，半秒后黑屏卡死。。。

**Comment by liupan1890** [comment]
v1.6.10试过了吗？他是Flutter 2.0.6 

https://github.com/liupan1890/aliyunpan/releases/download/v1.6.10/Win.v1.6.10.zip

**Comment by xiaokaixuan** [comment]
> v1.6.10试过了吗？他是Flutter 2.0.6
> 
> https://github.com/liupan1890/aliyunpan/releases/download/v1.6.10/Win.v1.6.10.zip

也不行。算了，这是老问题了，上次遇到一个项目也是这个问题，最后放弃Flutter了。

**Comment by Sailing168** [comment]
同win7需求
