### ISSUE TITLE
蓝奏云链接访问不了

### ISSUE THREAD

**Issue by STAOY** [liupan1890/aliyunpan#490]
链接访问不了的朋友把lanzoui.com改成lanzous.com或者lanzoux.com试试

**Comment by liupan1890** [comment]
蓝奏就是这样，经常性会遇到无法访问，大部分时候并不是所有人都无法访问，而是分地区的，部分人无法访问

等几天就又恢复正常了

**Comment by liupan1890** [comment]
我刚才测试，又能访问了，可能又是临时性故障（被屏蔽）
