### ISSUE TITLE
期待出一个tv版的

### ISSUE THREAD

**Issue by YangHaHabiu** [liupan1890/aliyunpan#494]
其他出一个电视盒子的客户端

(虽然今天已经看到有人发了tv版客户端 但没开源 反编译还混淆了)

**Comment by ifree8** [comment]
我来附上 第三方开放的安卓TV版，供小白羊 参考
阿里云盘TV版现世（第三方）1.0.6.apk
https://www.aliyundrive.com/s/QrjDAGKBCy2 提取码：zscc

**Comment by YangHaHabiu** [comment]
> 我来附上 第三方开放的安卓TV版，供小白羊 参考 阿里云盘TV版现世（第三方）1.0.6.apk https://www.aliyundrive.com/s/QrjDAGKBCy2 提取码：zscc

请问你是apk的作者不 这个apk反编译代码是混淆了的 如果你是作者能开源不 谢谢

**Comment by ifree8** [comment]
> > 我来附上 第三方开放的安卓TV版，供小白羊 参考 阿里云盘TV版现世（第三方）1.0.6.apk https://www.aliyundrive.com/s/QrjDAGKBCy2 提取码：zscc
> 
> 请问你是apk的作者不 这个apk反编译代码是混淆了的 如果你是作者能开源不 谢谢

不好意思 ，我不只是作者

**Comment by YangHaHabiu** [comment]
> > > 我来附上 第三方开放的安卓TV版，供小白羊 参考 阿里云盘TV版现世（第三方）1.0.6.apk https://www.aliyundrive.com/s/QrjDAGKBCy2 提取码：zscc
> > 
> > 
> > 请问你是apk的作者不 这个apk反编译代码是混淆了的 如果你是作者能开源不 谢谢
> 
> 不好意思 ，我不只是作者

哈哈哈 期待作者开源或者小白羊搞一个吧 谢谢啦 这个apk我也安装了 不过我登录后官方的客户端就登录不上了 不知道啥问题

**Comment by liupan1890** [comment]
我没啥时间，当前电脑版小白羊我都尽一个月没更新了，不是兴趣降低了或者不想弄了，仅仅是工作没时间，这个月很累

实在没啥时间做TV版了，以后也只会聚焦在电脑客户端上，会开发更多的功能。

**Comment by YangHaHabiu** [comment]
> 

anyway 感谢感谢 哈哈哈

**Comment by tylvn** [comment]
> 我来附上 第三方开放的安卓TV版，供小白羊 参考 阿里云盘TV版现世（第三方）1.0.6.apk [aliyundrive.com/s/QrjDAGKBCy2](https://www.aliyundrive.com/s/QrjDAGKBCy2) 提取码：zscc

阿里云盘链接已失效
