### ISSUE TITLE
[Bug] aria2c创建文件时失败

### ISSUE THREAD

**Issue by FreedomFoolt** [liupan1890/aliyunpan#495]
version: v2.12.05 
问题：aria2c创建文件时失败

## 实例一
问题文件的位置：`F:\BaiduYunDownloads\01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）\分类图书合集\经典高品质：5000套优质书籍！（纯电子版，非扫描。每本书多种阅读格式！总116.8GB)\VOL146-150\人类简史（知识漫画）：人类的诞生（尤瓦尔·赫拉利新作，用漫画故事回看人类几百万年的史诗历程。将戏剧性叙事、分镜设计与丰富知识配合！全世界1600万人读过《人类简史》，会有更多人\人类简史（知识漫画）：人类的诞生（尤瓦尔·赫拉利新作，用漫画故事回看人类几百万年的史诗历程。将戏剧性叙事、分镜设计与丰富知识配合！全世界1600万人读过《人类简史》，97b11040.epub`

## 实例二
下载成功的文件：
```
F:\BaiduYunDownloads\01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）\分类图书合集\经典高品质：5000套优质书籍！（纯电子版，非扫描。每本书多种阅读格式！总116.8GB)\VOL201-205\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！）\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！） - [日]辻村深月.jpg
```
创建失败的文件：与上面下载成功的文件只是类型不一样，为`mobi`格式
```
F:\BaiduYunDownloads\01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）\分类图书合集\经典高品质：5000套优质书籍！（纯电子版，非扫描。每本书多种阅读格式！总116.8GB)\VOL201-205\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！）\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！） - [日]辻村深月.mobi
```
## 猜测
1、是否是文件夹名字过长的问题？
2、类型`mobi`的文件有问题，同样的文件名`opf`、`jpg`类型成功下载了？

**Comment by liupan1890** [comment]
>F:\BaiduYunDownloads\01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）\分类图书合集\经典高品质：5000套优质书籍！（纯电子版，非扫描。每本书多种阅读格式！总116.8GB)\VOL201-205\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！）\镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！） - [日]辻村深月.mobi

**193个字，所以不应该是路径长度导致无法创建文件，因为winodws下最长是255**我怀疑是包含不可见的特殊字符导致创建失败

我也在我的网盘里创建了这个路径和文件，可以正常下载。所以怀疑是否包含不可见的特殊字符

还可能因为本地有同名文件并且被打开中，导致文件不可写入，这种一般，稍后会重试，会成功下载

**Comment by liupan1890** [comment]
你可以自己尝试一下

测试一：把"镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！） - [日]辻村深月.mobi"重命名为 "test.mobi" 看能否正常下载

测试二：把"01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）"重命名为“电子书大合集”

测试三：在小白羊设置，下载，取消勾选“新建下载任务时，按照网盘完整路径保存”选项

就能找出问题在哪了

**Comment by FreedomFoolt** [comment]
> 你可以自己尝试一下
> 
> 测试一：把"镜之孤城（写给「少年的你」，直木奖作家辻村深月最催人泪下的作品，收获7项大奖，日本销售量突破55万册，豆瓣9.4分佳作！） - [日]辻村深月.mobi"重命名为 "test.mobi" 看能否正常下载
> 
> 测试二：把"01 电子书大合集（亚马逊Kindle镇店之宝，PDF古籍书库等）"重命名为“电子书大合集”
> 
> 测试三：在小白羊设置，下载，取消勾选“新建下载任务时，按照网盘完整路径保存”选项
> 
> 就能找出问题在哪了

我已经测试直接进入文件所属的当前文件夹下载成功。我现在尝试复现这个问题，从第一级文件夹开始下载，但这需要时间

**Comment by FreedomFoolt** [comment]
无法复现这个问题，只能搁置了
