### ISSUE TITLE
阿里云盘产品经理邀请你加入阿里云盘团队

### ISSUE THREAD

**Issue by zhangbolins** [liupan1890/aliyunpan#50]
你好，小白羊作者，谢谢你上次回复了我。
刚看了一个视频，阿里云盘产品经理期待你加入阿里云盘团队。
我很喜欢阿里云盘和小白羊，同时也希望你把阿里云盘做成优秀的产品。
产品经理是一位女士。
视频：
https://www.aliyundrive.com/s/BAzVbmhoCad

**Comment by liupan1890** [comment]
恩给，收到。感谢提醒
