### ISSUE TITLE
香港下載速度

### ISSUE THREAD

**Issue by Winwinchan** [liupan1890/aliyunpan#504]
我在香港用1000Mbps寬頻，香港ofca 測速約700Mbps. 
 之前用小白羊下載可達50-60MB/s, 12月起跌到2MB/s, 更新到2.12.02, 結果一樣，速度經常是2.3MB/s, 不會跳動，用官方版則由1.x-3.xMB/s. 12.02下面顯示aria2已連接，但貌似沒有。昨天試過直接由modem 入電腦，官方版23MB/s, 之後又回復2.3MB/s. 朋友用香港另一isp 小白羊25MB/s. 請問知道是什麼問題?

**Comment by liupan1890** [comment]
>12.02下面顯示aria2已連接，但貌似沒有

只有正确链接后，才能下载文件，如果没有正确链接，不能下载任何文件（显示失败&&一点速度都没有）

>之前用小白羊下載可達50-60MB/s, 12月起跌到2MB/s  ...另一isp 小白羊25MB/s

是阿里云盘的问题，阿里云盘对非大陆地区并不提供服务（并不是完全禁止访问，而是没有任何优化，所以导致速度慢）

>官方版23MB/s, 之後又回復2.3MB/s

我分析可能是缓存加速导致，就是你先下载一个文件，此时在你本地临近的缓存节点已经有这部分数据了，此时你切换官方版下载，会因为缓存速度很快，之后缓存的进度下载完，那些没缓存的数据就又慢下来了

---

正常的，比如百度网盘，他会在全国各地有很多的服务器，有很多节点，你在香港，那么一般是从香港的节点下载，或者邻近香港的节点比如深圳/上海节点下载

非正常的，就是阿里云盘，我个人分析（可能不准确），当前阿里云盘只提供了北京节点，任何地方的人下载都是从北京节点下载，香港也是访问北京，因为距离较远，比不上临近节点那种速度快

最后，你是香港，但香港也分为很多线路，有的是国际线路，有的是电信线路（泛指国内线路）
所以下载速度问题，是阿里云盘的问题，并非小白羊限速了（以前快现在慢，可能仅仅是因为你的宽带服务商线路切换了，我不知道瞎猜的）

解决办法：
当前，下载大的视频文件时，你可以在文件上右键，查看详情，复制下载链接，然后使用IDM之类下载，因为小白羊内置的aria2是官方编译版本，一个文件最大只支持16线程，IDM之类都是128-256线程，所以会加快下载速度

---

以后，小白羊会取消16线程的限制，配合你自己替换修改版aria2.exe可以达到更快的下载速度

注：为什么不直接内置修改版的aria2.exe?因为修改版使用人数较少，win10有时候会报毒。官方版aria2.exe限制16线程但一般大陆用户都能满速了，所以没必要替换，只有像你这样遇到不能满速的才需要替换

**Comment by Winwinchan** [comment]
謝謝回復。

"12.02下面顯示aria2已連接，但貌似沒有

只有正确链接后，才能下载文件，如果没有正确链接，不能下载任何文件（显示失败&&一点速度都没有）"

說貌似沒有，是因為能連上能下載，下面顯示aria2已連接localhost, 但用官方版下載速度1.x-3.xMB/s,
跟小白羊2.3MB/s差不多，看不到有多線程。我曾改小白羊為遠端，打開motrix將遠端設為localhost, 跑16線程，但仍然約2MB/s.
有趣的是小白羊幾乎全時間定在2.3MB/s, 而官方版或google drive下載速度是有上落。2.3MB/s好像人為限制。
"是阿里云盘的问题，阿里云盘对非大陆地区并不提供服务（并不是完全禁止访问，而是没有任何优化，所以导致速度慢）"
我問過isp中移動, 他們說沒作任何限速，他們開了1個阿里雲盤新帳號，用官方版下載速度20幾MB/s, 我朋友用電訊盈科也20幾MB/s,
唯獨我家2MB/s。之前正常時估計也20幾，用小白羊加上4線程就可達70MB/s.

"官方版23MB/s, 之後又回復2.3MB/s

我分析可能是缓存加速导致，就是你先下载一个文件，此时在你本地临近的缓存节点已经有这部分数据了，此时你切换官方版下载，会因为缓存速度很快，之后缓存的进度下载完，那些没缓存的数据就又慢下来了"

當時沒開小白羊，按中移動技術支援說將modem 線直插電腦，用官方版下載一套2G的電影，一直跑23MB/s,
幾分鐘下載完，應該不是緩存。其後我再拔掉網線插router, 再插電腦，無論小白羊或官方版都是約2MB/s. 我還以後是router
壞，但之後再直插電腦好幾次，換另一條網線，速度仍是約2MB/s。另外，我用手機官方app經家中wifi 只有1.xMB/s,
連商場wifi境然達9MB/s.

12月前正常，12月起變慢，若說阿里限制，為何我朋友及中移動測試時沒變慢? 若我帳號被限制，為何我在商場比家快很多? 若我router 或modem
壞，為何google drive 及ofca 測速正常? 幾種證據有些互相沖突，我是找不到合適解釋，亦不知如何解決。

在 2022年1月5日週三 21:10，liupan1890 ***@***.***> 寫道：

**Comment by liupan1890** [comment]
如你所说，对你遇到的这个情况，我其实也没有头绪

留意一下，当使用小白羊同时下载多个文件时，应该是 **n x 2m/s** 这样的话说明大概率是阿里云盘限速，每个文件限速2mb/s

如果是同时只下载一个文件，速度为2mb/s 并且 同时下载5个文件，5个文件的总速度还是2mb/s 那么说明大概率是你网络问题

**Comment by Winwinchan** [comment]
我試過在小白羊複制文件右鍵連結，用ndm 32線程下載，結果也是約2MB/s. 中移動的估計是阿里限制了他們部分ip, 剛好我那次直插及他們測試的ip
沒被限制，現時正追蹤哪些ip 不受限制。

在 2022年1月7日週五 19:21，liupan1890 ***@***.***> 寫道：

**Comment by Winwinchan** [comment]
阿里雲盤換了接口，小白羊用不了，請問可以更新一下嗎? 不然好多無主孤魂。

在 2022年1月5日週三 21:10，liupan1890 ***@***.***> 寫道：
