### ISSUE TITLE
关于软件再分发授权的问题

### ISSUE THREAD

**Issue by zhullyb** [liupan1890/aliyunpan#505]
虽然在仓库的「alixbyelectron v2.9.24 」目录下找到了 2.9.24 版本的源码，但没有最新版本的源码（而且也没有添加开源许可证），因此阿里云盘小白羊版在 针对Linux发行版 打包时应该遵守闭源软件的规范，我需要向您申请再分发许可。虽然我相信作者您应该会同意我们打包并传播您软件的请求，但出于礼貌我还是来申请一下。
打包过程中，我们不会通过逆向等手段对程序进行任何修改，但会根据需要进行 去除软件自带的的依赖库并更换为发行版源内的依赖库、添加图标 等操作。打包完成后，将打完的包通过我们的分发渠道进行分发。

**Comment by liupan1890** [comment]
可以的，小白羊是开源软件，你可以随意地使用，修改

不要有版权顾虑，不要有许可顾虑，完全的随意使用

个人开源项目，并不会去考虑这么多限制

注：在下个版本（v3.1.x）发布时，会同步最新的v3.x的源码上来
因为我网络访问github并不是太顺畅，个人项目也不是那么注重源码协作，所以源码的更新确实非常随性
