### ISSUE TITLE
大佬新年好~~新版本批量重命名快了吧？

### ISSUE THREAD

**Issue by Michael-J-ScofieldOVO** [liupan1890/aliyunpan#507]
特别需要批量重命名  老版本还能用   但响应速度上比不了新版本   期待新版本批量重命名

**Comment by hummersyk** [comment]
+1

**Comment by liupan1890** [comment]
抱歉，因为工作上的事，最近一个月都没多少时间编码，这两天到是编了不到6小时，但因为较长时间不写代码了，重新刷了一遍现有代码，想要重新梳理一遍，减少代码的复杂度和减少bug，所以本周还是无法更新，等下周日吧，会有较多功能的完善上来

我一个月跑下来工资也就5千，有家庭，生活上比较拮据，所以虽然不想跑，但也不敢辞职或被辞职，之前几个月编码时间太多了请了很多假，所以已经是长期业绩垫底+请假第一，虽然12月将近全勤跑了一个月保住了饭碗，但现在也不敢请假，业余时间确实太少了，我们也没有周六日，每个月也没有假期，正常可以请4天假（是的，周日不上班？需要请假），我的时间太少了，我不知道如何解决这个问题，所以只能委屈大家多等等我了

非是不想，实是不能。底层生活就是这么艰难

**Comment by ybbluesky** [comment]
> 抱歉，因为工作上的事，最近一个月都没多少时间编码，这两天到是编了不到6小时，但因为较长时间不写代码了，重新刷了一遍现有代码，想要重新梳理一遍，减少代码的复杂度和减少bug，所以本周还是无法更新，等下周日吧，会有较多功能的完善上来
> 
> 我一个月跑下来工资也就5千，有家庭，生活上比较拮据，所以虽然不想跑，但也不敢辞职或被辞职，之前几个月编码时间太多了请了很多假，所以已经是长期业绩垫底+请假第一，虽然12月将近全勤跑了一个月保住了饭碗，但现在也不敢请假，业余时间确实太少了，我们也没有周六日，每个月也没有假期，正常可以请4天假（是的，周日不上班？需要请假），我的时间太少了，我不知道如何解决这个问题，所以只能委屈大家多等等我了
> 
> 非是不想，实是不能。底层生活就是这么艰难

可以给一个二维码，大家自愿付费

**Comment by Michael-J-ScofieldOVO** [comment]
> 

l

> 抱歉，因为最近工作上的事情，已经知道了多少时间编码，这聪明到是编了不到6小时，但因为需要时间不写代码了，重新刷了一遍已经存在代码，想要重新开始马上，减少代码的复杂度和虫子，所以本周可以还是下周日吧，有更新，功能等的改进
> 
> 我吃饭跑下来工资已经五千了，有家庭，生活上比较，所以，虽然不想跑，但也不敢放弃或放弃，饮食编码时间了很多假，所以是长期的业绩垫底+，虽然12月请假全勤跑了一个目的地保住了碗饭，但现在也不敢请假，空闲时间确实太少了，我们也没有周六日，每天也没有假期，正常可以请4天假（是的，周日不上班？需要请假），我的时间太少了，我不知道如何解决这个问题，所以只能委屈大家等等我了
> 
> 非是不愿意，实是不能。

很是理解，我们也只是玩玩 但是却要大佬付出很多时间，非常感谢~ 赞同楼上说的 ，尽一份力~
