### ISSUE TITLE
老生常谈--愿开源有力量

### ISSUE THREAD

**Issue by Borber** [liupan1890/aliyunpan#508]
作者确实辛苦了, 但目前我们除了祝福也没有别的可以帮助的方法, 还是提一下以前很多人就讲过的东西吧
1. 可以添加自己的捐献渠道, 但并不为此做出更新保证, 仅为单纯热心之举. 如果不想添加到程序里, 也是可以添加到项目的 `README` 中, 这是很多开源作者都采取的行为, 也不会导致反感. 可以列出捐献名单, 做出适当反馈
2. 积极提交`commit`, 只有维持最新的代码, 才会有人愿意共同协作, 提交`pr`. 即使是有些不成熟的功能, 或者可能需要退回的代码也无所谓, 不用有太大的心理负担. 你是项目的主持人, 你拥有仓库的所有权利. 这不是考试, 也不是面试, 如果你认为这个代码是有价值的, 只要没有 `release` 也并不会影响大家的使用. 
3. 建立开源社区, 以及建立项目路线图, 清晰的产品方向, 细分的功能, 会方便更多的人参与建设这个项目, 以及让大家了解到你的幸苦, 肉眼可见的进度也会缓和大家催更的焦急情绪.

这里我想举个例子, 也是国人创建的一个开源项目: [Logseq](https://github.com/logseq/logseq)

就满足了上面三点, 
1. 在README中放上捐献地址, 并列出来
2. 积极的提交, 每天少则几个, 多则几十个
3. 提供简易的开发教程, 积极的欢迎大家的贡献, 目前以及接受了近 `1k` 的`pr`了, 以及路线图 [roadmap](https://trello.com/b/8txSM12G/logseq-roadmap)

愿 小白羊原来越好, 作者工作顺利, 事事如意

**Comment by Pluto-ldc** [comment]
加油加油💪🏻

**Comment by liupan1890** [comment]
本质上，
1.是因为我并没有开源项目的管理经验，并没能在4.7kStar上，发展出对应的pr，其实pr对开源项目的持续非常非常重要
2.是因为小白羊功能简单，代码也简单，加上我代码可能并不是太规范，所以并没有吸引大家专注于小白羊的代码

这两点，现在，短期内，也没有大幅提升的可能，

代码规范需要大厂任职后被强制学习。
开源社区合作/管理经验，需要慢慢接触慢慢学习。

钱的话，我也没有经验一个完全免费的开源项目，会有多少打赏，
如果非要量化，我开发6个月，每个月因为开发会减少1千块的工资（外卖员，送餐时间==工资，很好量化），我不知道是否会收到6千的打赏，我也没有说认为大家就应该给我6千打赏弥补我的工资，只是随便举个例子，不要有人来拿我说的这句话较真。我的意思只是说，不知道会收到多少打赏但感觉没啥意义。

我这几天已经在恢复编码了，会慢慢恢复到之前的更新速度，因为小白羊现在虽然功能还有很多想法没有实现，但基础的架构/代码已经固定，简单的BUG已经都遇到了，常见的性能问题也已经都在解决了，所以后期实现插件功能时还是比较简单的，只是需要堆时间罢了，我会努力的，

开源代码的更新，会在下个版本发布时同步上来的

**Comment by Borber** [comment]
> 

其实不规范没关系的, 大家甚至可以因此多很多能参与进来进行贡献的机会, 我们可以帮忙整理代码. 

大佬真的强, 向大佬学习, ( 我是菜鸡 java 在学rust) 但自己编码热情真的比不上大佬. 兴趣来了可能一天能编码个五六小时, 但颓废的时候就不想打开IDE 😥
