### ISSUE TITLE
怎么获取文件下载链接？

### ISSUE THREAD

**Issue by QiTianzu** [liupan1890/aliyunpan#509]
视频可以通过详情复制下载链接，那其它类型的文件如何获取下载链接呢？

**Comment by liupan1890** [comment]
其他文件当前还不能获得下载链接，是因为其他格式的文件详情功能还没有做完，等以后做完了，就可以同视频文件一样复制了

或者使用旧版本(v2.9.24),虽然有BUG但文件详情功能是完整的
