### ISSUE TITLE
打不开，重新打开很多次也没用

### ISSUE THREAD

**Issue by HankMo** [liupan1890/aliyunpan#51]
![image](https://user-images.githubusercontent.com/60347960/122576541-5bd6db00-d084-11eb-8333-ec773c27bca7.png)

**Comment by liupan1890** [comment]
当程序启动时，会启动3个进程

1.阿里云盘小白羊版.exe
2.aliserver.exe
3.aria2c.exe

出现图中提示，是因为aliserver.exe没有正确运行。
在`阿里云盘小白羊版\data\Debug.log` 是运行日志。请把内容贴上来我看一下（放心，没有任何隐私信息），里面可能包含了出错信息说明aliserver.exe为什么没能运行

**Comment by HankMo** [comment]
![image](https://user-images.githubusercontent.com/60347960/122586193-ede3e100-d08e-11eb-809e-1d41bd63c500.png)
没有Debug.log
 我win10没杀毒 我卸载了

**Comment by liupan1890** [comment]
这就很奇怪了，你这样操作
1.双击阿里云盘小白羊版.exe
2.双击data\aliserver.exe

1和2的操作不要间隔太久（别超过10秒）

就是自动调用aliserver.exe没有成功，所以需要你手动双击aliserver.exe

这样肯定就会有debug.log了。操作完看你能否正常使用。

如果能正常使用，那就彻底退出，测试只双击阿里云盘小白羊版.exe 能否正常使用

1.可能第一次运行被阻止
2.可能时程序BUG识别aliserver.exe的路径出错没找到正确的路径调用启动。我稍后会检查一下代码看怎样确保能够正确的识别出aliserver.exe的位置
