### ISSUE TITLE
关于增加快捷键建议

### ISSUE THREAD

**Issue by rojunghwa** [liupan1890/aliyunpan#510]
请问能不能增加 Ctrl+c/v/x  复制 粘贴 剪切文件(夹),以及 F2重命名文件(夹)  这几个快捷键 的功能

**Comment by liupan1890** [comment]
F2已经有了啊？？？？

Ctrl+c/v/x 复制 粘贴 剪切文件(夹) 以后会有的

**Comment by rojunghwa** [comment]
好的，我没注意到F2已经有了，只试了ctrl的组合键就以为F2也没做
