### ISSUE TITLE
建议修改上传时，sha1计算的数量

### ISSUE THREAD

**Issue by huiyy-cn** [liupan1890/aliyunpan#511]
默认是同时计算3个sha1，但是速度太慢了。三个同时计算只有10M/s
要是能改成1个就好了。在1个的时候sha1计算能达到100M/s

**Comment by liupan1890** [comment]
先说解决方案：在小白羊设置里，选择“同时运行1个文件” 就可以限制为计算1个了

------

是否可以说一下你的使用环境？

多文件计算sha1降速，常见于机械硬盘和老旧的U盘

现在常见的 sata SSD/ m2 SSD 不会出现降速，比如我的笔记本多文件同时上传时sha1计算速度总和为1500MB/s，
因为大家现在速度都挺快的，限制为1个会导致大部分人不能全速计算，所以不能强制设置为1个文件计算。

近5年内购买的机械硬盘很难出现计算sha1降速（降速也是降低到100M/s以上）
老旧的机械硬盘（正常读取速度只有150M/s-80M/s）很难出现计算sha1降速（降速也是降低到80M/s以上）

#

插在USB2口上的、本身只支持USB2.0的老旧 USB移动硬盘,容易出现计算sha1降速，（降速后30MB/s-60MB/s）
插在USB2口上的、本身只支持USB2.0的老旧U盘，正常连续读取速度只有20MB/s-30MB/s ,容易出现计算sha1降速，（降速后3MB/s-10MB/s）

#

你提到3个文件同时计算，只有10M/s，不知道文件是存放在哪种硬盘上？一般很难出现这样的情况，我感觉你是有误解

1.虽然一个文件10M/s 但3个文件总速度是30M/s了
2.只有超过5MB的文件才会显示计算速度，超过300MB的文件才会被限制为3文件并发（6MB-299MB的文件并不限制并发）

所以，如果是在上传几十个100-200MB的文件并且小白羊设置里“同时运行30个文件”，那么实际上可能有30个文件在同时计算sha1,此时总的计算速度远远超过30MB/s

**Comment by huiyy-cn** [comment]
机械硬盘是没有ssd等固态速度快。但是存储冷数据还是机械的可靠啊。
如果限制只1个传输的话，效率会很慢。
比如，100个2G以上的文件，我设置上传30，如果sha1只计算1个的话，很快就可以计算出来，匹配就继续计算下一个，不然就开始上传.继续计算下一个，不影响上传的数量。

我试来试去都是1个文件sha1计算快几倍
