### ISSUE TITLE
【建议】目前官方版本也是32位的，是否小白羊会率先推出64位原生版本？

### ISSUE THREAD

**Issue by RobertChou** [liupan1890/aliyunpan#519]
目前只有32位版本的pc软件已经不多了，是否小白羊会率先推出64位原生版本？

**Comment by liupan1890** [comment]
1.当前小白羊使用的是electron，你可以直接下载electron官方发布的x64版本，然后复制小白羊目录下的resources文件夹即可运行原生64位，其他版本(arm / armx64 )同理一样

2.当前小白羊直接套用的阿里云盘官方exe程序，是为了减少win上杀毒软件误报，除此之外并没有其他意义

不知道对你来说原生64位的意义是什么？32位和64位有什么区别吗？不是在说64位更适合64位系统性能更好吧？性能问题全都是代码优化的锅，不在于位数

**Comment by RobertChou** [comment]
> 

理论上64位比32位应用能使用更多的内存，原生64位应用性能更好，当然这个只是理论上，也是趋势，你说的性能是代码优化的锅，也没错。

**Comment by liupan1890** [comment]
呃，我也不是理解得很深啊，仅仅是作为探讨，不要多想

1.理论上64位比32位应用能使用更多的内存

针对于小白羊来讲，
在日常使用，小白羊内存在200-400MB左右
在一次性上传/下载一百万个文件时，内存占用约800MB，下个版本对内存还有优化，目标是百万文件会控制在300-500MB内存这样

32位支持3.5GB内存，完全够用了

2.原生64位应用性能更好

这个并不是的，从计算机原理上来说，32位程序，创建一个int变量，只需要分配/读写 32位的内存。64位程序就需要翻倍，
这个导致64位性能比32位程序性能普遍要低很多，但是因为大家都知道64位性能太低了，不可能真的让他的性能比32位降低一倍，所以各种编译器都在针对64位优化--遇到可以使用32位就能满足的时候，使用32位。

既虽然是64位的程序，但实际上，大量的底层编译后的汇编代码，都是使用32位的。

然后还有一部分代码，确实是需要64位的（存储一个大数，32位一次存不下，需要读写2次。64位只需要读写一次，这样的情况64位才快）

最后综合一下，大部分程序，总体上32位变量更多，64位较少，所以此时对比同一个程序的32位和64位运行速度，基本可以忽略性能差异（强调，科学运算类，AI训练类，大数据类，程序，是64位更快，因为大部分运算是大数运算）

总结一句还是：程序的性能差异，无法通过一句64位性能更好或者32位性能更好去判断。大部分程序还是32位更快，64位理论更慢但是因为大量的编译器优化提速，就感觉不到慢了

现在流行64位不是因为它快，是因为现在内存太便宜，32位不支持3.5GB以上，没办法，操作系统才都开发为64位。
仅个人理解

**Comment by wsy1074** [comment]
好奇问一下，现在arm平台的系统都强制要求从35位转向64位，高通最新处理器的部分核心已经不支持32位的程序了，这不是说明64位的程序的运行效率更高，更省电吗？

**Comment by liupan1890** [comment]
> 好奇问一下，现在arm平台的系统都强制要求从35位转向64位，高通最新处理器的部分核心已经不支持32位的程序了，这不是说明64位的程序的运行效率更高，更省电吗？

计算机，最本质上，可以理解为读取-计算-存储
那你理解为下楼取快递吧，规定你一次只能拿一个快递，
现在你有10个快递，需要拿几次？拿10次。
然后现在变成有20个快递了，需要拿几次？拿20次。
那么，
拿20次会比拿10次快吗？不会，拿10次用10分钟，拿20次自然需要20分钟
拿20次会比拿10次省力气吗？不会，拿10次消耗10卡路里，拿20次自然需要消耗20卡路里

那么怎么办？程序员去想办法优化

>arm平台的系统都强制要求从32位转向64位

是因为当前，技术在发展，
CPU在降价，所以计算速度更快了（以前i5只有双核，现在i5都是4核，R5是6核）
内存在降价，大家都用大内存了(现在千元手机16GB内存，08年3千元器件手机0.5GB内存)

最早8086CPU是16位，后来都升级为32位了，道理是一样的。

**Comment by liupan1890** [comment]
还是补充一下吧，这个问题（32/64）现在讨论是没有意义的

在几十年前，程序员愿意花费半个小时的时间，去优化代码，仅仅为了减少一个变量的创建

同一个程序，创建一个变量，和创建两个变量，哪个好？
创建一个变量好，可以节省50%的时间，也就是性能翻一倍，差距超级大。

但是到了现在，哪个好？无所谓了，没有人关心，创建一个变量和创建两个变量的问题，因为科技进步了
