### ISSUE TITLE
你会加入阿里云盘团队吗？

### ISSUE THREAD

**Issue by hongshuang1234** [liupan1890/aliyunpan#52]
我不知道你会加入阿里云盘团队吗？阿里云盘团队应该是一个非常好得团队，希望你可以加入。如果加入了千万记得告诉我们啊！

**Comment by liupan1890** [comment]
我大学是学的软件开发，然后毕业当程序员，然后公司疫情期间倒闭（不是因为疫情），成为美团

那么问一下我为什么当美团呢？是因为找不到工作啊

那么结合我自身情况，想一下我能不能加入阿里云盘呢？不太现实对吧。阿里是大厂，我连985都不是

网上大家都说美团里什么大神都有，是真的，大家只是找不到工作而已。我们队里就有研究生


为了生活，勤奋务实一点，也不错

**Comment by LittleTurtle2333** [comment]
@liupan1890 美团比开发还赚钱吗？我看好多开发都去送外卖了

**Comment by yayaleslie** [comment]
@liupan1890 开发确实苦逼，送外卖貌似也不错，不过大佬这技术，送买外屈才了

**Comment by LittleTurtle2333** [comment]
@yayaleslie 据说美团7w硕士和17w研究生:joy:

**Comment by hongshuang1234** [comment]
@liupan1890 话说你们这些技术大佬都去送外卖去了，像我们这样的产品经理岂不是马上要失业了！

**Comment by hongshuang1234** [comment]
@LittleTurtle2333 看来我们这些产品经理快失业了，我们设计完的东西没有技术去实现，我们真的离失业不远了！

**Comment by LittleTurtle2333** [comment]
@hongshuang1234 美团永远向你招手，:joy:

**Comment by hongshuang1234** [comment]
@liupan1890 话说您在哪个城市啊？我看看是否可以帮您内推，真心希望您可以继续做技术！

**Comment by hongshuang1234** [comment]
@LittleTurtle2333 曾经有机会去美团做产品经理的机会，但是我放弃了，现在追悔莫及啊！

**Comment by yayaleslie** [comment]
@LittleTurtle2333 要不是我是路痴，我也不做开发，送外卖去了😂

**Comment by hongshuang1234** [comment]
@yayaleslie 完了，这技术大佬都去送外卖，看来我们真的要失业了！看来可能真的要去选择美团了！

**Comment by LittleTurtle2333** [comment]
关键是大佬，如何边送外卖，边学习Flutter+Go+Vue这三个新技术，还能用这三个家伙写项目。这不累哭，是不是有点屈才了

**Comment by liupan1890** [comment]
呵呵呵，感谢大家的关心

**Comment by LittleTurtle2333** [comment]
@liupan1890 现在才下班？太辛苦了

**Comment by liupan1890** [comment]
没有，在适配相册，然后发现阿里云盘是把  网盘，相册，保险箱 三个功能独立的，等于你注册了3个账号，一个账号是云盘，一个账号是相册。。。

我以前的代码都是只提供云盘，所以现在代码需要改动的比较多。这两天正头疼呢。不说了，该睡了

**Comment by chenzhiguo** [comment]
小伙子，有兴趣来京东么？

**Comment by xiaoxiaohuangya** [comment]
老哥 有兴趣加入携程嘛 不卷的！感谢你的工作～
