### ISSUE TITLE
每天上班第一件事就是来看看大招放出来没有

### ISSUE THREAD

**Issue by China-Huanghe** [liupan1890/aliyunpan#521]

**Comment by China-Huanghe** [comment]
新版本的程序图标能不能改回那个A啊？这阿里云的图标是真的丑
![截图_20220520100505](https://user-images.githubusercontent.com/77739994/150251826-c18f7944-9ec2-4d3e-be43-f39623ea4b83.png)
![截图_20220520100549](https://user-images.githubusercontent.com/77739994/150252013-3d0aa18c-361e-404e-b27e-53d687f50ee5.png)

**Comment by liupan1890** [comment]
大招还在开发中，

图标：
为了减少windows上用户，下载小白羊后会误报为病毒，所以套用的经过阿里云盘签名的electron程序，而没有使用自己打包的electron程序，所以不能更换程序的图标（更换后签名会掉）

1.使用electron官方发布的的程序--会误报病毒
2.使用我自己编译的electron程序--大概率会误报病毒
3.使用阿里云盘签名后的electron程序--基本不会误报病毒

区别就是，签名，
签名是花钱买的，阿里云盘的是企业签名，大概1万块/年
一个病毒程序经过签名，也会被认为是正常程序
一个正常长须不经过签名，大部分会被报告为病毒，需要作者联系微软杀毒上报误报，提供一些认证资料，解除误报

**Comment by China-Huanghe** [comment]
了解，那还是继续期待大招吧

liupan1890 ***@***.***> 于 2022年1月20日周四 下午9:46写道：

**Comment by jjandnn** [comment]
我激动了1小时了…… @liupan1890 条件反射先融合，再看内容，哈哈哈，啪啪啪，抽打自己。

**Comment by liuyun198833** [comment]
@liupan1890 
不知道大佬能不能年前更新一波，给大家来个节前福利~![18D58719](https://user-images.githubusercontent.com/16303973/150906235-34720d7d-c143-4384-8c0e-546456ef1093.png)

**Comment by atroot-sudo** [comment]
一样一样！

**Comment by andywang1011** [comment]
我也是天天来看大招进度的

**Comment by zpyg** [comment]
> 我也是天天来看大招进度的

+1

**Comment by wg96644364** [comment]
每过一段来康康大招出了没有哈哈
