### ISSUE TITLE
功能建议~

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [liupan1890/aliyunpan#523]
强烈建议大佬加一个上传时自动洗码并上传的功能（就在本来的洗码功能上加个选项就行吧）
今天去盘里找电影在电视上看...然后就发现变成违规文件了...翻了一下盘里又有一堆文件就给违规了
我自己存的东西现在不拿出去分享了...但是别人分享同样的文件被某些小鬼举报了之后我的文件也会跟着挂...还好大部分电脑里都有备份 已经重新洗码并上传了（今天因为这个事把人整傻了）
**强烈建议大佬加一个上传时自动洗码并上传的功能！
强烈建议大佬加一个上传时自动洗码并上传的功能！
强烈建议大佬加一个上传时自动洗码并上传的功能！**（谢谢啦~）

**Comment by KHLFYY** [comment]
这个功能不会加的

参看：https://github.com/liupan1890/aliyunpan/issues/440#issuecomment-986154012

**Comment by YaeSakuraQvQ** [comment]
> 这个功能不会加的
> 
> 参看：[#440 (comment)](https://github.com/liupan1890/aliyunpan/issues/440#issuecomment-986154012)

哦哦 懂了 行吧
谢~
