### ISSUE TITLE
偶尔出现视频不加载

### ISSUE THREAD

**Issue by Doddddd** [liupan1890/aliyunpan#526]
![image](https://user-images.githubusercontent.com/88972478/151469678-fe6b9498-18d2-4aa4-9317-58f756d14c79.png)
每隔几天就会出现一次

**Comment by liupan1890** [comment]
不知道是否和视频长度有关？当前阿里云盘生成的URL有效期只有4个小时，比如一个6小时的纪录片，播放到4小时以后就会卡住，需要关闭，重新播放，拖动播放进度到4小时

不知道是否和播放软件的缓存策略有关，可以尝试更换为自定义播放器（比如Potplayer）

**Comment by Doddddd** [comment]
> 不知道是否和视频长度有关？当前阿里云盘生成的URL有效期只有4个小时，比如一个6小时的纪录片，播放到4小时以后就会卡住，需要关闭，重新播放，拖动播放进度到4小时
> 
> 不知道是否和播放软件的缓存策略有关，可以尝试更换为自定义播放器（比如Potplayer）

应该不是视频长度的问题，我没有过连续播放同一个视频超过4小时；
mpv用习惯了，先更新一下试试；
多谢解答，期待大招。
