### ISSUE TITLE
视频详情里面的错误

### ISSUE THREAD

**Issue by antaluqi** [liupan1890/aliyunpan#527]
违规文件，可以正常播放，但很多这些视频的视频详情点进去提示是：错误的文件（视频时长错误），两个链接按钮也看不见了，但有时候卡一下，还是能点到这个按钮的，主要是想获取m3u8链接

**Comment by plus-32** [comment]
我也遇到一样问题，但用potplayer播放器能在标题信息里看到
![批注 2022-01-29 181230](https://user-images.githubusercontent.com/77501897/151657084-3fc09631-bdef-44f0-8aa0-8ad9014cccf8.jpg)

**Comment by liupan1890** [comment]
收到！是BUG，会在下个版本里修正此问题！

**Comment by antaluqi** [comment]
> 我也遇到一样问题，但用potplayer播放器能在标题信息里看到 ![批注 2022-01-29 181230](https://user-images.githubusercontent.com/77501897/151657084-3fc09631-bdef-44f0-8aa0-8ad9014cccf8.jpg)

只能点击使用默认播放器播放，怎么用potplayer播放呢？

**Comment by plus-32** [comment]
> > 我也遇到一样问题，但用potplayer播放器能在标题信息里看到 ![批注 2022-01-29 181230](https://user-images.githubusercontent.com/77501897/151657084-3fc09631-bdef-44f0-8aa0-8ad9014cccf8.jpg)
> 
> 只能点击使用默认播放器播放，怎么用potplayer播放呢？

用2.12.05版本在设置的UI里有选项

**Comment by antaluqi** [comment]
> > > 我也遇到一样问题，但用potplayer播放器能在标题信息里看到 ![批注 2022-01-29 181230](https://user-images.githubusercontent.com/77501897/151657084-3fc09631-bdef-44f0-8aa0-8ad9014cccf8.jpg)
> > 
> > 
> > 只能点击使用默认播放器播放，怎么用potplayer播放呢？
> 
> 用2.12.05版本在设置的UI里有选项

找到了，感谢！
