### ISSUE TITLE
大佬，辛苦了，新年快乐，有两个问题

### ISSUE THREAD

**Issue by jingyill** [liupan1890/aliyunpan#528]
顺便问下，文件洗码的记录在哪里看？还有就是上传下载的清除全部可以加一个确认窗口吗？

**Comment by liupan1890** [comment]
你好

1.戏码记录
没有洗码的记录功能，就是简单的选择文件夹，洗码这个文件夹下面的全部文件

这个洗码记录，我感觉没啥用啊，看这个记录的意义是什么呢？是多次操作洗码文件吗？因为可能要洗码的文件其实比较多，我感觉根据记录去辨别是否洗码了，也很困难。


2 可以加一个确认窗口吗
以后的版本里会加上确认提示。不过我感觉没必要，反而让操作更繁琐了，这个全部清理按钮误点的概率很小吧
