### ISSUE TITLE
您好，有安卓电视用的app吗？

### ISSUE THREAD

**Issue by TVqj3237** [liupan1890/aliyunpan#529]

**Comment by zpyg** [comment]
可以看看这个 [阿里云盘 TV 版](https://www.52pojie.cn/thread-1567412-1-1.html)

下载链接：
下载：https://wwi.lanzout.com/b04692nvg   密码: appn

**Comment by DAGUAGUAGUA** [comment]
这个可以在线看4K吗

**Comment by zpyg** [comment]
> 这个可以在线看4K吗

应该可以

**Comment by liupan1890** [comment]
你好，我怕没有精力去开发维护安卓版本了

**Comment by tylvn** [comment]
> 可以看看这个 [阿里云盘 TV 版](https://www.52pojie.cn/thread-1567412-1-1.html)
> 
> 下载链接： 下载：[wwi.lanzout.com/b04692nvg](https://wwi.lanzout.com/b04692nvg) 密码: appn

蓝奏云链接已失效

**Comment by pu-007** [comment]
> > 可以看看这个 [阿里云盘 TV 版](https://www.52pojie.cn/thread-1567412-1-1.html)
> > 下载链接： 下载：[wwi.lanzout.com/b04692nvg](https://wwi.lanzout.com/b04692nvg) 密码: appn
> 
> 蓝奏云链接已失效

最新链接 [蓝奏云](https://wwd.lanzouf.com/iAaTS0455kch) 密码:8m6m

项目官网: https://aliyunpantv.gitlab.io/

**Comment by SongFuKang** [comment]
> 
谢谢
