### ISSUE TITLE
我相信你能加入阿里云盘团队的，阿里云盘运营小姐姐小罗的微信号Lymore0301z

### ISSUE THREAD

**Issue by zhangbolins** [liupan1890/aliyunpan#53]
作者你好，我相信你能加入阿里云盘团队的，不是985也没关系，产品经理都期待你去阿里云盘团队。
你做的小白羊这么好，阿里云盘就是缺少你这样优秀的程序员。
我几个朋友也是做程序员的，虽说在大厂工作辛苦，可工资挺好，工作稳定。

我把阿里云盘运营小姐姐小罗的微信号告诉你，你愿意去阿里云盘团队的话就联系她吧。
Lymore0301z

**Comment by liupan1890** [comment]
感谢你的厚爱，我是在3线小城市，有儿有女，年纪不大
一方面可能需要我离开家去北上广
另一方面阿里云盘当前采用的是js和c++  我用的是dart和golang 入职程序员的希望真不大。做背调，看学历，看经验，看年龄，看技术。哪一项我也不够出色。

你想我自己想找个5K的程序员都面试不上，所以我就不去阿里自取其辱了。

再次感谢，但现实却是比较现实

**Comment by HeiSir2014** [comment]
> 感谢你的厚爱，我是在3线小城市，有儿有女，年纪不大
> 一方面可能需要我离开家去北上广
> 另一方面阿里云盘当前采用的是js和c++  我用的是dart和golang 入职程序员的希望真不大。做背调，看学历，看经验，看年龄，看技术。哪一项我也不够出色。
> 
> 你想我自己想找个5K的程序员都面试不上，所以我就不去阿里自取其辱了。
> 
> 再次感谢，但现实却是比较现实 

可以要求在家办公，😄

**Comment by d790043608** [comment]
> 感谢你的厚爱，我是在3线小城市，有儿有女，年纪不大
> 一方面可能需要我离开家去北上广
> 另一方面阿里云盘当前采用的是js和c++ 我用的是dart和golang 入职程序员的希望真不大。做背调，看学历，看经验，看年龄，看技术。哪一项我也不够出色。
> 
> 你想我自己想找个5K的程序员都面试不上，所以我就不去阿里自取其辱了。
> 
> 再次感谢，但现实却是比较现实

热爱比啥都厉害！加油持续关注...

**Comment by xionger-096** [comment]
捉着你好，我发现github上好像有人冒充你项目的作者。https://github.com/azureplus/aliyunpan

**Comment by liupan1890** [comment]
> 捉着你好，我发现github上好像有人冒充你项目的作者。https://github.com/azureplus/aliyunpan

额，不知道有哪些冒充的行为？

他在哪里宣传他是作者了？--这就是冒充了，但不知道能有啥好处。。。

还是你搜小白羊搜到他看到这个代码跟我的一样所以感觉他在冒充？---这个是误会了，因为他fork了我的代码，有80多人都fork过了，就是在这80多个人的主页都能看到这个项目，这是github的功能，不属于冒充。

**Comment by xionger-096** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月21日(星期一) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liupan1890/aliyunpan] 我相信你能加入阿里云盘团队的，阿里云盘运营小姐姐小罗的微信号Lymore0301z (#53)





  
捉着你好，我发现github上好像有人冒充你项目的作者。https://github.com/azureplus/aliyunpan
  
额，不知道有哪些冒充的行为？
 
他在哪里宣传他是作者了？--这就是冒充了，但不知道能有啥好处。。。
 
还是你搜小白羊搜到他看到这个代码跟我的一样所以感觉他在冒充？---这个是误会了，因为他fork了我的代码，有80多人都fork过了，就是在这80多个人的主页都能看到这个项目，这是github的功能，不属于冒充。

**Comment by DifferentSparkler** [comment]
> 感谢你的厚爱，我是在3线小城市，有儿有女，年纪不大
> 一方面可能需要我离开家去北上广
> 另一方面阿里云盘当前采用的是js和c++ 我用的是dart和golang 入职程序员的希望真不大。做背调，看学历，看经验，看年龄，看技术。哪一项我也不够出色。
> 
> 你想我自己想找个5K的程序员都面试不上，所以我就不去阿里自取其辱了。
> 
> 再次感谢，但现实却是比较现实

兴趣是最好的老师，个人感觉可以尝试一下，可以先去面试一下万一过了呢，公司每次招的新人也不一定什么都会的，也是边工作边学习的。
