### ISSUE TITLE
我这登录之后为什么看不了相册啊？

### ISSUE THREAD

**Issue by EmberBurning** [liupan1890/aliyunpan#533]
[如图，我没法访问相册
![屏幕截图(62)](https://user-images.githubusercontent.com/70953327/152538667-85057b34-6b00-4206-946c-257042d33d8d.png)

**Comment by liupan1890** [comment]
你好，因为相册功能暂未开发，所以不能使用

**Comment by EmberBurning** [comment]
> 你好，因为相册功能暂未开发，所以不能使用

ok，我先换回之前的版本用
