### ISSUE TITLE
希望添加文件违规批量删除操作

### ISSUE THREAD

**Issue by uuuuuuuuuup** [liupan1890/aliyunpan#535]
比如我们存的一些资源被其他人分享，导致和谐不能观看，源文件被替换成官方的净网视频，但是由于数量太多删除起来比较麻烦，作者可以在时间精力充裕的情况下考虑添加此功能，我觉得和文件查重类似，是不是可以统一合并在一个功能下。

**Comment by liupan1890** [comment]
你好

是的，此功能，会和文件查重/空文件夹，一起上线，当前尚在开发中，所以并未提供

**Comment by liupan1890** [comment]
v3里已经提供了
