### ISSUE TITLE
两个功能可否做一下

### ISSUE THREAD

**Issue by AidienQ** [liupan1890/aliyunpan#536]
1、希望可以在“已上传”页面添加“清空记录并删除本地文件”按钮
2、上传文件计算sha1后如果不能秒传就自动暂停 以此类推 先给能秒传的上传上去，不能秒传的再统一用网速上传（做个按钮）

**Comment by AXBNG** [comment]
第二个倒是蛮实用，至于第一个.......手动删一下不费多大力气

**Comment by liupan1890** [comment]
你好

1.删除本地文件

删除文件，比较敏感，可能会遇到用户误删除的情况，所以小白羊并未提供删除本地文件的操作，请用户手动删除文件
清空记录，已经有了

2.先给能秒传的上传上去

下个版本会在设置里增加一个开关“上传中 优先秒传，跳过不能秒传的任务”

**Comment by AidienQ** [comment]
> 



> 第二个倒是蛮实用，至于第一个.......手动删一下不费多大力气

**Comment by AidienQ** [comment]
> 第二个倒是蛮实用，至于第一个.......手动删一下不费多大力气

因为我的磁盘分区多上传的文件夹和文件也多，想上传完就给删了免得占空间，想着正是配合着第二个功能秒传上去点快捷键就直接给本地文件给删了，省的一个分区一个文件夹的找哪些秒传上去了哪些没有，既然考虑到会误删的情况那就算了叭

**Comment by AidienQ** [comment]
> 你好
> 
> 1.删除本地文件
> 
> 删除文件，比较敏感，可能会遇到用户误删除的情况，所以小白羊并未提供删除本地文件的操作，请用户手动删除文件 清空记录，已经有了
> 
> 2.先给能秒传的上传上去
> 
> 下个版本会在设置里增加一个开关“上传中 优先秒传，跳过不能秒传的任务”

好的，感谢

**Comment by tangchuqi** [comment]
建议还是开发一个选项"删除正在下载的任务，是否删除本地文件(可续传的一半的文件)"，以及"删除已完成任务，是否删除本地文件"，若同时传输多个文件，一些已完成，一些未完成，删除下载任务的时候，会产生很多废弃没用的文件占空间，本地再去寻找删除很费时间。针对您说的，由于删除本地文件比较敏感，我不太认同，因为文件本来就是阿里下载的（并非用户创作，没了可以再下），没下完就删除or下完了删除勾选'删除本地文件'属于用户的行为，小白羊不用对其完整性做保证。无论任务是否完成，用户应该该目录下的需要的文件进行剪切保存打其他目录（迅雷idm之类的都有此类功能）只要保证客户端删除的文件都是客户端产生的or目录下的，而不是其他非客户端产生的文件，就没有风险，若用户对其下载目录的文件进行修改or覆盖后保存，再不小心删除，这属于用户没保障数据安全的操作（用户勾选'删除本地文件'）
