### ISSUE TITLE
老大，什么时候可以更新一波？

### ISSUE THREAD

**Issue by hongtucao8384** [liupan1890/aliyunpan#538]

**Comment by liupan1890** [comment]
新年新版本(v3了)，为了提升开源代码的体验，在认真的重构代码。也有一些新想法需要尝试。所以我暂时也没有明确的更新时间

我最近几天都是平均开发5个小时左右，进度还不够快，多等我一些时间

因为现有版本功能并没有特别重大的问题，所以也不着急

**Comment by atroot-sudo** [comment]
稳中求进，大佬加油！

**Comment by ydwg** [comment]
致敬！感谢！
