### ISSUE TITLE
什么时候支持Docker版呢？

### ISSUE THREAD

**Issue by SeeDLL** [liupan1890/aliyunpan#54]
希望能支持一下能用web控制的版本，这样的话，就能打包到docker里，在用网页打开操作配置登录什么的，这样的话，如果把这个docker部署到私人VPS上，就能妥妥的实现 [webdav协议的支持](https://github.com/liupan1890/aliyunpan/issues/45)，同时也能对[Linux的版本提供支持](https://github.com/liupan1890/aliyunpan/issues/36)

感觉如果能打包到docker，可玩性大大的提高了很多

**Comment by liupan1890** [comment]
鞥，当前我确实没时间做linux版本。因为近期阿里云盘官方上线后开放了相册，再调整相册功能

web控制的版本：
实际上，Flutter可以打包成web，但是有一部分功能无法通过web实现，具体没细想。

webdav的支持
这个webdav跟vps没关系，你可以在自己的电脑直接webdav .启动软件架设一个本地webdav代理， 比如上传文件是直接从本地传到网盘。
如果是在vps上架设webdav服务，那么用法一是本地文件先传到VPS，再从VPS传到网盘。这个不合适。用法二是文件下载到VPS然后通过webdav自动上传到网盘。这个跟webdav没啥关系了，以后会出同步盘功能可以自动同步上传

linux版本
前几天我其实也在编译linux版本，结果吧十分不理想。在ubuntu 20.04 编译完运行时，窗口必须活动，如果窗口不活动（比如你把鼠标挪到其他窗口上），那么小白羊的窗口就绘制的丢三落四。是flutter本身的问题。flutter已经推出2年了，但是重大的BUG一大堆，也是没有好的办法。所以就先放下了，等flutter下个版本更新时我再试试


小白羊是开源软件，也希望有能力的可以自己fork定制

**Comment by SeeDLL** [comment]
好的，支持你啊，大佬，哈哈，其实细细想了下，我的想法还是不太适合，主要是偏后台了，有点像rclone那样的后端程序挂载Google Drive网盘那样的，放到vps上，用处大大的。知识能力有限，现在暂时坐等诸位大佬继续完善了。
