### ISSUE TITLE
移动端是否有在线播放支持内嵌字幕的客户端或者方式

### ISSUE THREAD

**Issue by shelken** [liupan1890/aliyunpan#543]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by liupan1890** [comment]
有的，官方app我没留意过，似乎是可以加载同目录下字幕的？？忘了

有很多第三方开发的安卓版阿里云盘apk，是支持手动选择字幕的，也支持调用很多手机上的播放软件播放，百度，安卓，阿里云盘即可

**Comment by shelken** [comment]
> 有的，官方app我没留意过，似乎是可以加载同目录下字幕的？？忘了
> 
> 有很多第三方开发的安卓版阿里云盘apk，是支持手动选择字幕的，也支持调用很多手机上的播放软件播放，百度，安卓，阿里云盘即可

不过我是ios。囧；
