### ISSUE TITLE
大佬考不考虑做个webUI版

### ISSUE THREAD

**Issue by LadyReze** [liupan1890/aliyunpan#544]
基于docker运行，文件下载使用客户端浏览器或容器路径

我的工作室使用阿里云盘跟NAS同步，除了备份还经常需要分享里面的文件，就希望所有人都可以访问云盘账户。由于登陆限制做不到每个设备都登陆，如果有web端开放给所有人就很好了。

现在使用命令行客户端加ssh脚本勉强解决，但希望能有更方便简单的解决方案。

**Comment by liupan1890** [comment]
alist

https://github.com/Xhofe/alist

**Comment by LadyReze** [comment]
> alist
> 
> https://github.com/Xhofe/alist

这个工具的分享功能是基于生成直链，我想要和官方链接形式一样的分享功能

**Comment by liupan1890** [comment]
所有人都可以访问云盘账户，并且可以创建分享链接，这个功能小白羊并没有

**当前小白羊是基于electron运行的，并不能直接改为nodejs+docker**

docker一般没有GUI，electron并不适合长期运行（比如我电脑上的360浏览器，如果一直开着不关机，大概2周内会自动崩溃，原因不明，但从侧面说明electron适合每天开关机的这种情景而不适合服务器上长期运行，服务器上内存也是个限制）

所以，小白羊并不能很简单的直接转型服务器端，需要大量的修改代码，我有限的时间都去维护现在的小白羊了，所以并不打算开发webui版本
