### ISSUE TITLE
要是后端go代码能规范点就好了

### ISSUE THREAD

**Issue by daofeng2015** [liupan1890/aliyunpan#55]
多用用go的接口,少用函数式调用,还有api的返回也不应该直接写死

**Comment by liupan1890** [comment]
你好，
感谢建议，能具体说说吗？

1.提到了多用接口--实际上我印象里aliserver代码里一处接口也没用过。
我以前是做c#的，面向对象，go接口其实也就是多态，但是aliserver里没有对多态的需求。

你原来有一个鸭子，你现在又有一个大黑鸭，好了整个接口，共享同样的方法--吃饭，减少代码行数，以后也好管理

但我印象里aliserver的代码里没有大黑鸭--没有多态的需求，或者说即使有一处两处最多了，有一处，直接复制一遍代码就好了，没有必要整接口吧？为了最多减少100行代码--强行上接口？

2.当前aliserver里其实都是函数试调用。为的是好写，开发速度快，有很多地方的代码也都是简单的复制复制。并没有好好的整理。比如文件列表，文件夹列表，其实都是调用列表接口，一种是把调用接口的代码提取出来复用，一种是直接完整复制粘贴。还是复制快--但是我知道不对

这只是因为我没时间做，当前还处于功能快速开发的阶段，等功能全部定型了完善了，才能进入实在闲着没事干就优化代码的阶段。到时候会注意重新整理一遍代码


3.返回也不应该写死
这个我没理解透，可以多说说

还是希望能具体的说一说，比如这段代码xxxx应该怎么怎么样，哪里xxx方法应该把返回值改成xxx
这样我也好理解，也方便我改。

好比你说一句：界面太丑，改好看点
首先我也不知道具体是哪里丑，然后确实也是没时间改，好看是需要时间去抠细节的。比如界面的背景颜色，当前是单一白色，实际应该做成配色加磨皮，但我没时间去抠细节了////以后会一点点完善的
