### ISSUE TITLE
能不能在播放视频文件的时候右键选择原始文件或转码视频

### ISSUE THREAD

**Issue by QiTianzu** [liupan1890/aliyunpan#554]
播放转码的 m3u8 调进度有进度条动，画面不动的情况。

**Comment by liupan1890** [comment]
这个设置是在APP设置页面，可以自己选择播放原始文件还是播放转码视频

是统一的设置，设置后，所有视频播放都会根据这个设置来处理，你可以在APP设置里去修改

我明白可能你是想仅对这一个视频生效

但是，很可惜，右键菜单，面积有限，放不下这2个不常用的选项。所以不会在右键菜单种增加

还是只能在APP设置里修改

**Comment by QiTianzu** [comment]
好吧
