### ISSUE TITLE
大神不开个收款码吗

### ISSUE THREAD

**Issue by hcliu987** [liupan1890/aliyunpan#557]
大神不开个收款码吗,表达下心意

**Comment by iD2073** [comment]
希望能放出一个基础功能能用的版本，比如详情和批量重命名，其他功能可以慢慢完善

**Comment by iD2073** [comment]
希望能放出一个基础功能能用的版本，比如详情和批量重命名，其他功能可以慢慢完善

**Comment by sunnyadams** [comment]
大佬有机会开一个捐赠吧，让我们表达一下谢意

**Comment by hcliu987** [comment]
> 谢谢，不用了，功能太简陋，不好意思接收捐赠
> 
> 正在努力的开发v3,会丰富功能和提升开源代码的使用体验

我都不介意你介意什么

**Comment by J0EST1N** [comment]
打多打少是个缘，一杯奶茶钱还是可以的
