### ISSUE TITLE
能添加文件去重功能吗

### ISSUE THREAD

**Issue by WangY1628** [liupan1890/aliyunpan#56]
之前因为软件不稳定有很多文件重复了，没法完全文件信息的话比对相似文件名也可，谢谢大佬！

**Comment by liupan1890** [comment]
#### 1.之前因为软件不稳定有很多文件重复了

这个能详细说说吗？是程序有BUG？
你怎么操作的？很多文件重复具体是指什么？
我意识里，小白羊在上传文件时，在导入秒传连接时，如果同目录下有同名的文件，会先检查是否一致，一致跳过上传，不一致覆盖上传。阿里云盘官方客户端和网页是采用的自动重命名(名字后面加20210622_53435这种时间戳)，你说的很多文件重复，

1. 说的你用网页上传导致的自动重命名文件重复吗？
2. 还是小白羊程序BUG？
3. 还是说在不同的文件夹下面有很多相同的文件（你自己手动往几个文件夹里上传了相同的文件）

#### 2.你想达到的去重效果是什么？
1.如果是同一个文件夹里有很多名字不同但内容(sha1)相同的文件，那就是想自动删除这些重复的文件？

涉及到删除文件，肯定还是需要你自己勾选确认删除的，我不敢做这种自动检查出重复文件后自动删除的功能。
最后肯定是自动检查出重复文件，弹窗，问你要删除哪些保留哪些。
说实话，这样的去重功能很鸡肋--跟你自己看文件名手动选择删除，操作步骤并没减少多少。

2.如果是不同的文件夹下面，有很多同名或者不同名，但内容相同的文件，那就是你自己选择删除？

这个涉及到范围问题，列出你网盘的全部文件然后进行查重，最后弹窗让你选择？
（1.不涉及隐私，列文件是在你电脑上列，正常的操作，不涉及隐私泄露）
（2.关键问题是如果你网盘里文件很多，短时间列出全部文件，阿里云盘的API有访问次数限制，很容易失败，也就是需要等几分钟才能全部列出来，而不是等几秒就能列出来，你点一下查重要等加载中，几分钟后才弹窗显示结果）

详细的回复我一下，看怎样查重最合适

**Comment by carolzzn** [comment]
对比文件名去重可以吗？通过这个来判断

**Comment by liupan1890** [comment]
> 对比文件名去重可以吗？通过这个来判断

其实我更关心她提到的“软件不稳定有很多文件重复了”是怎么回事

对比文件名当然是可以的，也应该对比sha1值，

**Comment by WangY1628** [comment]
> #### 1.之前因为软件不稳定有很多文件重复了
> 这个能详细说说吗？是程序有BUG？
> 你怎么操作的？很多文件重复具体是指什么？
> 我意识里，小白羊在上传文件时，在导入秒传连接时，如果同目录下有同名的文件，会先检查是否一致，一致跳过上传，不一致覆盖上传。阿里云盘官方客户端和网页是采用的自动重命名(名字后面加20210622_53435这种时间戳)，你说的很多文件重复，
> 
> 1. 说的你用网页上传导致的自动重命名文件重复吗？
> 2. 还是小白羊程序BUG？
> 3. 还是说在不同的文件夹下面有很多相同的文件（你自己手动往几个文件夹里上传了相同的文件）
> 
> #### 2.你想达到的去重效果是什么？
> 1.如果是同一个文件夹里有很多名字不同，但内容(sha1)相同的文件，那就是想自动删除这些重复的文件？
> 
> 涉及到删除文件，肯定还是需要你自己勾选确认删除的，我不敢做这种自动检查出重复文件后自动删除的功能，怕误删。
> 最后肯定是自动检查出重复文件，弹窗，问你要删除哪些保留哪些。
> 说实话，这样的去重功能很鸡肋--跟你自己看文件名手动选择删除，操作步骤并没减少多少。
> 
> 2.如果是不同的文件夹下面，有很多同名或者不同名，但内容相同的文件，那就是弹窗你自己选择删除？
> 
> 这个涉及到范围问题，列出你网盘的全部文件然后进行查重，最后弹窗让你选择？
> （1.不涉及隐私，列文件是在你电脑上列，正常的操作，不涉及隐私泄露）
> （2.关键问题是如果你网盘里文件很多，短时间列出全部文件，阿里云盘的API有访问次数限制，很容易失败，也就是需要等几分钟才能全部列出来，而不是等几秒就能列出来，你点一下查重要等加载中，几分钟后才弹窗显示结果）
> 
> 详细的回复我一下，看怎样查重最合适

文件名重复不是由小白羊导致的，因为我还没有用小白羊上传过文件，应该是在用之前的官方客户端的时候不稳定导致卡死然后我关闭后重复上传由软件自动命名的，在一个文件夹下有很多相同的文件。
想要达到的效果一个就是我这种误传导致大量文件重复；在一个随着分享功能用的人越来越多，很有可能网盘中的不同目录下会存在着相同的文件，占用空间，就像现在的百度云盘。
去重的范围的话，我想大概就是您说的那样了。选中在某一个文件夹下进行去重，解决的大概就是像我这样的问题；全盘去重解决资源重复占用空间的问题。展示出来的话，如果可以的话我设想是小白羊自动把用户可能要删除的文件选中，然后由用户浏览确认一遍防止误删，省去了点击选中的时间
大佬这么认真的回复让我有点受宠若惊了( ﹡ˆoˆ﹡ )

**Comment by liupan1890** [comment]
明白，收到，我之后会增加去重功能的，就是可能比较晚，耐心等等我,
