### ISSUE TITLE
下载时遇到了大量任务都一直显示启动中但是没有下载

### ISSUE THREAD

**Issue by BeauChu** [liupan1890/aliyunpan#560]
Hi 大佬，我打开后点下载一直显示启动中，然后尝试过手动更换最新的aria2版本，也更换过电脑，还是无法下载

2022/2/28 2:30 update     尝试了更换账号发现正常了，应该是我的账号问题导致的

![photo_2022-02-27_20-54-37](https://user-images.githubusercontent.com/50692750/155883200-7cd1eb43-114b-4f67-9f4b-e8546a85c4ce.jpg)

日志如下：

27 20:55:57 : success : 小白羊启动
27 20:34:07 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:33:57 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:31:05 : success : 小白羊启动
27 20:22:59 : success : 小白羊启动
27 20:13:02 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:12:10 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:10:06 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:07:37 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:07:24 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:05:36 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:05:09 : warning : HttpError3 400 undefined Request failed with status code 400
27 20:00:24 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2010饭网\E18 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:24 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2021凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:23 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2020凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:22 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2018凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:22 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2019凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:22 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2017凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:22 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2015凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:22 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2016凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:21 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2014凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:20 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2012饭网 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:20 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2013凤凰天使 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:20 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2011饭网 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:20 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2010饭网 ENOENT: no such file or directory, mkdir '\\?'
27 20:00:19 : danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man ENOENT: no such file or directory, mkdir '\\?'
27 19:58:47 : success : 小白羊启动

**Comment by liupan1890** [comment]
报错danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2010饭网\E18 ENOENT: no such file or directory,

不知道是否 W是移动硬盘因为没插着所以报错？这个错误我记一下，以后创建前先检测一下

启动中这个错误，我还没查出问题是哪，你提到更换账号后不报错，
那么理论上，假设是原账号有问题，也应该显示：生成下载链接失败，而不是一直显示启动中

在下个版本里，我会对此问题进行进一步的分析，看问题到底是在哪里。

你上报的错误信息，对我很有帮助

**Comment by BeauChu** [comment]
> 报错danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2010饭网\E18 ENOENT: no such file or directory,
> 
> 不知道是否 W是移动硬盘因为没插着所以报错？这个错误我记一下，以后创建前先检测一下
> 
> 启动中这个错误，我还没查出问题是哪，你提到更换账号后不报错， 那么理论上，假设是原账号有问题，也应该显示：生成下载链接失败，而不是一直显示启动中
> 
> 在下个版本里，我会对此问题进行进一步的分析，看问题到底是在哪里。
> 
> 你上报的错误信息，对我很有帮助

Hi 大佬，目前账号已经恢复，估计是我大概这三天内下载了15T左右3W多个文件导致的

**Comment by BeauChu** [comment]
> 我的也出现相同的问题，换一个账号就可以正常下载了。

Hi Guys，目前我的账号在24小时候已经恢复正常，您也可以安心等待一下

**Comment by liupan1890** [comment]
收到!!!

**Comment by zephyr-y** [comment]
看来阿里云开始限制下载了。具体限制规则不清楚。

**Comment by takeTrace** [comment]
> > 报错danger : AriaAddUrl创建文件夹失败：W:\阿里云盘\综艺\经典综艺-Runinng man\RM2010饭网\E18 ENOENT: no such file or directory,
> > 不知道是否 W是移动硬盘因为没插着所以报错？这个错误我记一下，以后创建前先检测一下
> > 启动中这个错误，我还没查出问题是哪，你提到更换账号后不报错， 那么理论上，假设是原账号有问题，也应该显示：生成下载链接失败，而不是一直显示启动中
> > 在下个版本里，我会对此问题进行进一步的分析，看问题到底是在哪里。
> > 你上报的错误信息，对我很有帮助
> 
> Hi 大佬，目前账号已经恢复，估计是我大概这三天内下载了15T左右3W多个文件导致的

+1, 我也是晚上挂着下载大数量的文件, 早上起来就都是启动中了, 下什么都是启动中(2.9.x版本是正在解析), 但是没有15T, 感觉可能是对短时间下载大量文件做了限制. 
建议可以在大量文件时做提示, 做个下载优先级....
