### ISSUE TITLE
会有去重功能吗？

### ISSUE THREAD

**Issue by LIUBANGJIAN** [liupan1890/aliyunpan#561]
大佬，现在阿里空间不够用了，可以开发去重复文件功能吗？

**Comment by liupan1890** [comment]
在v3里就会提供了，最近几天其实正在做这个（去重/查违规文件/查禁止分享/查空文件夹）

功能好做，但卡在性能上了，我网盘里存放了3万个文件夹，89万个文件

最开始，查重一次需要20分钟这样，因为需要列出89万个文件（分布并不均匀），阿里云盘列文件很慢

折腾了一周了，现在大概在5-15分钟，还在想办法，想要更快一点

**Comment by xircom1996** [comment]
感谢大佬！！！！！

**Comment by fohuhu** [comment]
感谢大佬，辛苦
