### ISSUE TITLE
大佬慢慢做吧，阿里要出vip了，感觉又快收割了，说不得又跑路了

### ISSUE THREAD

**Issue by jun-wwx** [liupan1890/aliyunpan#562]

**Comment by TPAXcc** [comment]
？什么思维？收费就会跑路？不收费给你免费用一辈子是吧

**Comment by Borber** [comment]
> ？什么思维？收费就会跑路？不收费给你免费用一辈子是吧

因为之前有过阿里云盘停运的事情

**Comment by liupan1890** [comment]
收费不收费问题不大，有百度在前，阿里想来会差异竞争的。

**Comment by prodcd** [comment]
收就收吧，毕竟阿里运营需要不小的成本。一个付费用户要养好几个免费用户。

**Comment by jkqxl** [comment]
想知道vip有什么用，虽然目前的不限速上传下载确实达不到满网速

至于限速收费，这个是企业版，个人版我不认为阿里会是这个套路

**Comment by prodcd** [comment]
其他网站看到的，不知真假。
![](https://qnam.smzdm.com/202202/28/621c6bee4ca712060.jpg_e1080.jpg)

**Comment by TPAXcc** [comment]
@prodcd 肯定不是的，alyd VIP 没有任何要分级的消息

**Comment by TPAXcc** [comment]
@jkqxl 容量？
