### ISSUE TITLE
作者能不能顺手开发个像clouddrive一样挂载网盘到本地的功能？那个不开源，不放心。

### ISSUE THREAD

**Issue by wsy1074** [liupan1890/aliyunpan#565]

**Comment by liupan1890** [comment]
呃，
clouddrive当前只支持windows吧，应该是不支持mac/linux因为我之前试用的时候，发现会注册windows服务，这个是windows系统才有的（并不是说注册服务不好啊）

小白羊更希望通过插件提供一些附加的功能，（比如文件查重，和链接转存）
侧重点不一样，程序的逻辑也不一样，所以我也并没有开发本地挂载的计划，就好像我也没有开发TV版/手机版的计划

**Comment by lackluster1** [comment]
clouddrive有docker版本

**Comment by kkksa528** [comment]
clouddrive有docker版本，mac和nas可以安装，本地映射软件有很多，github好几个开源的，个人认为体验最好的还是付费raidrive（win，功能强大支持所有国外网盘，也有clouddrive（win+docker后续会放出全部代码，解决了国内网盘挂载，可以说网盘挂载现在只要会搜索加思考，win和mac平台都要很好的软件，实在不会选择只要花钱什么都有的Google drive（我吹爆，体验一流，作者没必要开发已有的功能，现在想的是如何完善客户端界面，优化体验，发挥win mac Linux全平台的优势，做好这些自然有人会用，同时个人支持今后mac平台收费
