### ISSUE TITLE
我有个大胆的想法，【本地观看云端加密的视频】，可行吗？

### ISSUE THREAD

**Issue by yuankeyuan** [liupan1890/aliyunpan#566]
大佬你好，【本地观看云端的加密视频】，技术上可行吗？比如对关键帧进行加密，这样可以绕过网盘检测从而保证了文件不会丢失，然后本地播放的时候，在播放器边传输并对关键帧进行解密，这样也能很好的保护个人隐私...
不知技术上是否可行，仅仅是一个想法

**Comment by prodcd** [comment]
比如在文件头加些特殊字符，再换个扩展名，让阿里云不知道这是个视频文件，然后边下载边播放。
但进度条能不能用不好说。

**Comment by liupan1890** [comment]
技术上讲，确实是可行的，因为只需要 加/解 密很小一部分数据就可以了

但实际上并不太现实。

问题一：你需要自己加密上传视频
你无法要求，**原始分享者**，也使用小白羊，加密后，上传视频。

因为，原始分享者要面向大众分享，而不是面向小白羊使用者分享。假设一个人没有使用小白羊，那就看不了这个视频

所以，你只能自己执行，下载--加密--上传，这个操作。
且加密后的视频，无法用网页版在线预览，必须只能使用小白羊去播放
很快你就会烦了

问题二：我无法保证会维护小白羊十几年
一旦我停止维护小白羊，那么，除非有其他人接力。不然总有一天，会因为阿里云盘官方接口升级，导致现在的小白羊v2.x无法使用。

假设，你使用小白羊加密了一堆视频，然后4-5年后，小白羊不能用了，这些视频自然也无法播放了


---
其实现在小白羊已经提供了，视频洗码功能，你对视频洗码后上传，只要不分享，一般就会一直有效。

关于保护隐私，当你对视频洗码后上传，阿里云盘会认为这个视频全网唯一，属于一个人自己独有的文件，这类文件基本不会被审查---因为审查是需要用电脑审查的，用电==花钱。很少有网盘会审核一个用户独有的文件，太烧钱了。

主流网盘都是审核有人分享的文件

**Comment by yuankeyuan** [comment]
> 技术上讲，确实是可行的，因为只需要 加/解 密很小一部分数据就可以了
> 
> 但实际上并不太现实。
> 
> 问题一：你需要自己加密上传视频 你无法要求，**原始分享者**，也使用小白羊，加密后，上传视频。
> 
> 因为，原始分享者要面向大众分享，而不是面向小白羊使用者分享。假设一个人没有使用小白羊，那就看不了这个视频
> 
> 所以，你只能自己执行，下载--加密--上传，这个操作。 且加密后的视频，无法用网页版在线预览，必须只能使用小白羊去播放 很快你就会烦了
> 
> 问题二：我无法保证会维护小白羊十几年 一旦我停止维护小白羊，那么，除非有其他人接力。不然总有一天，会因为阿里云盘官方接口升级，导致现在的小白羊v2.x无法使用。
> 
> 假设，你使用小白羊加密了一堆视频，然后4-5年后，小白羊不能用了，这些视频自然也无法播放了
> 
> 其实现在小白羊已经提供了，视频洗码功能，你对视频洗码后上传，只要不分享，一般就会一直有效。
> 
> 关于保护隐私，当你对视频洗码后上传，阿里云盘会认为这个视频全网唯一，属于一个人自己独有的文件，这类文件基本不会被审查---因为审查是需要用电脑审查的，用电==花钱。很少有网盘会审核一个用户独有的文件，太烧钱了。
> 
> 主流网盘都是审核有人分享的文件

懂了，谢谢大佬回复，既然可以加密的话，我想应该也可以使用同样的加密算法还原成未加密的文件，即使官方调整接口后小白羊不能使用了，也可以下载到本地再还原。不过也确实存在很多问题。
1.需要先加密再上传
2.需要专门定制小白羊或者播放器来解密
3.工作量大
4.可能会有各种未知的bug（比如视频上传到网盘被偷偷转码，或者因为各种原因无法还原为原视频）

**Comment by prodcd** [comment]
> 技术上讲，确实是可行的，因为只需要 加/解 密很小一部分数据就可以了
> 
> 但实际上并不太现实。
> 
> 问题一：你需要自己加密上传视频 你无法要求，**原始分享者**，也使用小白羊，加密后，上传视频。
> 
> 因为，原始分享者要面向大众分享，而不是面向小白羊使用者分享。假设一个人没有使用小白羊，那就看不了这个视频
> 
> 所以，你只能自己执行，下载--加密--上传，这个操作。 且加密后的视频，无法用网页版在线预览，必须只能使用小白羊去播放 很快你就会烦了
> 
> 问题二：我无法保证会维护小白羊十几年 一旦我停止维护小白羊，那么，除非有其他人接力。不然总有一天，会因为阿里云盘官方接口升级，导致现在的小白羊v2.x无法使用。
> 
> 假设，你使用小白羊加密了一堆视频，然后4-5年后，小白羊不能用了，这些视频自然也无法播放了
> 
> 其实现在小白羊已经提供了，视频洗码功能，你对视频洗码后上传，只要不分享，一般就会一直有效。
> 
> 关于保护隐私，当你对视频洗码后上传，阿里云盘会认为这个视频全网唯一，属于一个人自己独有的文件，这类文件基本不会被审查---因为审查是需要用电脑审查的，用电==花钱。很少有网盘会审核一个用户独有的文件，太烧钱了。
> 
> 主流网盘都是审核有人分享的文件


加密可以使用现有技术，保证与客户端无关。比如WinRAR加密成自解压文件。
解密播放，可以在单个文件的右键菜单中增加这个功能。由用户自己选择边下载边播放，不限制扩展名。

甚至可以考虑，在文件头增加一个mp4短片，表明这是一个小白羊专用视频格式。后边直接跟着WinRAR压缩文件，就像jpg+rar那种格式。最终扩展名还是mp4，这样官方客户端用户能直接播放，但只有几秒，提示去下载小白羊。不知道阿里云官方会不会容忍。

**Comment by hummersyk** [comment]
> 其实现在小白羊已经提供了，视频洗码功能，你对视频洗码后上传，只要不分享，一般就会一直有效。

“视频洗码”的原理是什么呢？就是在文件头加一些不影响播放的字节吗？

**Comment by prodcd** [comment]
> > 其实现在小白羊已经提供了，视频洗码功能，你对视频洗码后上传，只要不分享，一般就会一直有效。
> 
> “视频洗码”的原理是什么呢？就是在文件头加一些不影响播放的字节吗？

文件末尾加字节，目的只是改变了整个文件的hash，但听说网盘都是把文件切开存放，比如256M一份hash，这样还是可以知道原文件是哪个。
文件头加字节，会导致整个文件读写一遍，大文件会很慢。

**Comment by hummersyk** [comment]
> 文件末尾加字节，目的只是改变了整个文件的hash，但听说网盘都是把文件切开存放，比如256M一份hash，这样还是可以知道原文件是哪个。
> 文件头加字节，会导致整个文件读写一遍，大文件会很慢。

如果是这样，那小白羊的洗码功能岂不是没用了吗？

**Comment by prodcd** [comment]
> > 文件末尾加字节，目的只是改变了整个文件的hash，但听说网盘都是把文件切开存放，比如256M一份hash，这样还是可以知道原文件是哪个。
> > 文件头加字节，会导致整个文件读写一遍，大文件会很慢。
> 
> 如果是这样，那小白羊的洗码功能岂不是没用了吗？

很多规则都是靠“猜”和“测”的，有没有用，要从技术和政策两个方面去看。也许是技术方面官方并没有像我说的那样切开文件算hash，也许是官方对于没有分享的文件睁一眼闭一眼，也许官方压根就不审核未分享文件。只能说这功能现在还可用。

**Comment by liupan1890** [comment]
>但听说网盘都是把文件切开存放，比如256M一份hash，这样还是可以知道原文件是哪个

呃，你说的是底层的文件存储方式，阿里云盘并不会根据这个去审查文件。审查文件都是对完整文件进行审查的

比如有10个文件，都是同一个视频洗码后的文件，底层存储时每个文件被分割为10个分片

分片目的是，节省最终的存储空间（最终使用的存储空间是 9+10）
（9--前9个分片内容完全一致，10--10个文件的最后一个分片）
（如果不采用分片存储，最终使用的存储空间是 10+10+10。。。=10x10）

但是，单独拿出任何一个分片，都是没有任何意义的字节数据，无法审查。
并且出于对用户隐私的保护策略。也不会单独拿出任何一个分片来做审查操作（因为可能会碰巧有多个文件的某个分片数据完全一致，分片体积越小碰撞概率越大）

所以，当前洗码还是有用的，
有用是因为，阿里云盘不会去针对未分享的文件进行审查。洗码后的文件不分享时，自然是安全有效的

没有洗码的文件，
比如用磁力下载的一个视频。你能下载到，别人也能下载到。
你不分享出去，别人可能会上传到阿里云盘后分享出去。
只要有人分享，就会被审查，被封后就会连累到你网盘里的同样的这个文件。

洗码只是为了不被别人连累，仅此而已

**Comment by thinkmore123x** [comment]
当然可以啊，稍等，我翻翻我之前回的一个帖子，就有提到这个需求，已经完美满足了，O(∩_∩)O哈哈~

**Comment by thinkmore123x** [comment]
云盘里放小姐姐，同时满足在线播放的愿望？？还要抗封杀？？
你们真的不知道吗？你们的这种需求，早有老司机搞出更好的方案啦，O(∩_∩)O哈哈~ 秉承爱好者的分享精神，拿走不谢！

分享地址：http://myshare.wmz.im

免费的小软件，好东西我也不藏着掖着了，好事做到底，把软件的特色也转贴过来，看看是不是你们要的？？

1、视频文件加密：加密后，每个文件都有自己的指纹，即便是同一源文件，不同瞬间不同人加密结果截然不同，可抵抗网盘平台的hash检测和连坐封杀； 
2、支持在线播放：加密后，借助Alist挂载网盘，加密视频可支持在线播放，且可抵抗平台的预览审查和抽帧审查，完美抗封杀； 
3、低速带宽播放：借助视频切片，可在低带宽网络下，实现网络流畅播放；且不限云盘，所有主流的云盘（只要Alist支持），都没问题，总算可以充分利用那些不限速的网盘看视频了！ 
4、支持离线播放：加密后的视频文件，可离线保存，除了本软件，还可基于主流知名开源播放器——VLC播放器，右键—>使用VLC media Player播放。数据安全，再无后顾之忧！

-----------------
我的补充理解：
1、根据 “可抵抗平台的预览审查和抽帧审查，完美抗封杀” 这样的描述，说明不怕平台预览审查和抽帧审查。而对于“可抵抗网盘平台的hash检测和连坐封杀”这样的描述，我理解是强调 “加密后，每个文件都有自己的指纹，即便是同一源文件，不同瞬间不同人加密结果截然不同”，因而可以防止“连坐封杀”的意思。
2、至于，针对性举报，这个就不好说了。如果举报后，是系统自动审查，按“可抵抗平台的预览审查和抽帧审查“的说法，应该可以过。对于人工下载来播放查看，那肯定会被发现了，因为本身这就是“加密后支持播放”的能力表现啊。
3、我个人的经验是，加密后上传的文件夹名字做了改名，你赤果果的名字放哪里，真当别人敏感词检测是吃素的啊，那已经不是视频加密的事儿了。
4、目前，我从115迁移的3T多的文件还好，没有发生被抽帧检查封杀的事情。当然，我没分享，因为一旦分享被举报，人工审查多半就GG了，但他们那个“不会被连坐”说法，让我并不担心被拖累。

**Comment by thinkmore123x** [comment]
这段时间有点兴奋啊，总忍不住要分享，(⊙o⊙)…

**Comment by zhuzhe1983** [comment]
我之前的老板干过差不多的事情，魔改了mkv的封包逻辑，然后出了个自己的视频解码器。然后还是调用的h265，h264之类的解码。[scm](https://baike.baidu.com/item/SCM%E6%A0%BC%E5%BC%8F/6334914?fr=aladdin)

所以只要小白羊里面带的这个播放器，能够调用小白羊内置的视频编码器（dll），播放非mkv（私有文件名）比如 .avid 这样的自定义扩展名视频文件，云盘就无法识别和封杀。如果云盘对所有的文件都尝试解包，也可以使用魔改的mkv，在封包时候，搞一些密码之类的鉴权（参考DRM），然后尝试播放的时候，需要密码（密码通过论坛和群传播，不放在云盘里面，类似微信群的加密pdf）。
