### ISSUE TITLE
大佬能否加个搜索所有违禁文件的功能！

### ISSUE THREAD

**Issue by bilibili2077** [liupan1890/aliyunpan#571]
文件有多有乱，不知道那个文件夹里的文件哪天就成违禁文件了，一个文件一个文件的找又费事费力，想着大佬能做个功能，跟搜索功能一样，一搜就能把所有违规文件罗列出来，这样好洗码替换掉！

**Comment by aionyzq** [comment]
这个一直在大佬的日程上，不过我主账号被阿里禁止分享功能了也没等到更新就是了。o(╯□╰)o

**Comment by liupan1890** [comment]
呃，v3里就会有了，已经做了

**Comment by aionyzq** [comment]
有个功能我通过TC文件管理器的批量创建文件夹和鼠标点击器脚本实现了...
那就是防止被官方封禁分享功能后无法分享文件的方法——提前创建5000个文件夹并分享
事情挺简单，创建分享一大堆空文件夹罢了。就是讨不讨打就不知道了。

**Comment by liupan1890** [comment]
v3里已提供了 网盘内 违规文件/禁止分享文件 的扫描功能
