### ISSUE TITLE
关于播放swf的问题

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#573]
v2.9.24不能播放swf格式的视频，用的PotPlayer，但是下载到本地用PotPlayer是可以放的。

**Comment by liupan1890** [comment]
你好 

这个跟视频格式本身有关，因为swf，并非视频格式，而是flash封装格式，他是给脚本动画的一种格式，

有的视频，为了加密或者特殊目的（不知道什么目的），会封装为swf格式，这个也比较少见

此时，本身就是不应该可以直接在线播放的，因为播放时需要读取完整的swf文件中的特定位置的数据

一般的视频格式，都是封装为流格式，可以理解为第一分钟的视频数据在前面，第二分钟的视频数据在后面。所以可以在线边下边播

swf，封装时，会有很多封装方式，不一定是第一分钟的视频数据在前面，第二分钟的视频数据在后面这样

总之：这是正常的现象，因为是swf

**Comment by hummersyk** [comment]
原来是这样，学习了，感谢回复。
