### ISSUE TITLE
[与小白羊无关]ali已限制每天的下载额度，本贴仅为同样遇到限制的各位，用来反应情况与统计数据

### ISSUE THREAD

**Issue by GJG666** [liupan1890/aliyunpan#574]
①、第一种限制机制(会员机制正式收费以后，本限制基本被第二种限制机制所取代)：每日下载量或者24小时内的下载量(两种判定方式暂时未实验出具体是哪种)，达到1TB至1.5TB区间内的上限(这是我个人测得的上限区间，但具体数值尚不清楚)，会被限制下载。据实验，同一账号，第一次限制下载会在24小时后自动解除，第二次限制下载一周后自动解除。

②、第二种限制机制：短时(1~2小时内)检测到持续性的大量下载(我账号测试的是达到100G，有人反映三四百G，也有人反映60G就被限制了)大概率会遭到禁止下载的限制，至于限制何时自动解除，猜测是跟第一种限制的自动解除时间规律一致，即第一次限制下载会在24小时后自动解除，第二次限制下载一周后自动解除

注：开通超级会员或者普通会员可以解除下载限制 (已实验)。

被限制下载了以后：
该账号使用第三方客户端会被禁止下载任何文件，无论大小，包括webdav挂载后无法源码播放或者用小白羊源码播放，据反映，有用户可以使用官方PC客户端或手机端下载，但有人所有客户端都不可以下载。

本贴用于统计同样遇到下载限制的各位，大概是怎么样的情形触发了下载限制。

自会员正式收费以后，额度限制开始变本加厉，之前是每天下载不能超1T，现在是几个小时之内不能超过多少额度。这不是重点，重点是一禁止就是一周不能下载，除非开会员，彻底成了给会员铺路的机制
(3.27日更新)

**Comment by BeauChu** [comment]
Hi Guys，我也是同样的情况，2月27日凌晨开始，第一次一天接触，第二次目前还是无法下载

**Comment by BOT4214** [comment]
我觉得这是合理的

**Comment by BOT4214** [comment]
“达到1TB至1.5TB区间”......你也好意思说出来

**Comment by GJG666** [comment]
> “达到1TB至1.5TB区间”......你也好意思说出来你

> “达到1TB至1.5TB区间”......你也好意思说出来

净他妈说废话，我在意的是它进行下载限制？我有说它进行限制不合理了？我在意的是它明明已经更新了下载限额的机制，却没有做任何公开声明！致使遇到此问题的所有人都还蒙在鼓里

**Comment by NansenLH** [comment]
> > “达到1TB至1.5TB区间”......你也好意思说出来你
> 
> > “达到1TB至1.5TB区间”......你也好意思说出来
> 
> 净他妈说废话，我在意的是它进行下载限制？我有说它进行限制不合理了？我在意的是它明明已经更新了下载限额的机制，却故意不对此做任何公开说明！致使遇到此问题的所有人都还蒙在鼓里

对于限制没有任何规则说明, 没有任何提醒, 就是单纯的让所有下载都显示失败, 粗暴简陋的产品设计和实现, 很难让人理解阿里作为国内的大厂行为竟然如此低级.
另外几乎没有客服, 提交工单也没有任何反馈

**Comment by aionyzq** [comment]
目测阿里云盘作为一个网盘服务会在连续亏损3年内落幕，如果非法将用户隐私数据用于阿里AI项目，可能会存活更久一点。但就目前的运营方针来看，充斥着阿里系一贯视用户为韭菜的理念。限制下载额度仅是一个信号，是阿里云盘对用户权利（知情权）漠视的信号；但这样的信号之前早已出现。譬如私自扫描用户相册内未分享的照片，进行敏感照片屏蔽；对部分它认为违规的分享文件屏蔽，分享链接依然存活却无任何形式的通知，但会在达到某个阈值后直接对用户账号封禁。

**Comment by liupan1890** [comment]
呃，都不用激动，限制不透明是常见操作，百度网盘也没说过超多少流量会限速（百度超会，一定流量后也会被限速的）

感觉是因为这个限制是随着时间，经常变动的，可能不是太好量化/公开


：超限后无任何提醒

可能是我的锅，因为我也没测试过一天1TB流量，可能超限后接口返回错误信息了，但因为我没遇到过，所以小白羊没显示提示。


：私自扫描用户相册内未分享的照片，进行敏感照片屏蔽

根据阿里云盘的官方说法，是不会私自扫描用户文件的

注1：一些公开的违规视频，在你的网盘内突然别屏蔽，并不是阿里云盘扫描了你的网盘内的文件，而是别人分享这个文件后被审查，违禁后，阿里云盘全网根据相同的sha1/size 自动屏蔽的，不需要扫描你网盘里的文件的内容

注2：如果是你自己拍摄的照片且从未分享过，仍然被设置为违禁文件，则说明偷偷扫描了文件内容了，但一般真的没人敢这么做，都是注1的情况

**Comment by GJG666** [comment]
> 呃，都不用激动，限制不透明是常见操作，百度网盘也没说过超多少流量会限速（百度超会，一定流量后也会被限速的）
> 
> 感觉是因为这个限制是随着时间，经常变动的，可能不是太好量化/公开
> 
> ：超限后无任何提醒
> 
> 可能是我的锅，因为我也没测试过一天1TB流量，可能超限后接口返回错误信息了，但因为我没遇到过，所以小白羊没显示提示。
> 
> ：私自扫描用户相册内未分享的照片，进行敏感照片屏蔽
> 
> 根据阿里云盘的官方说法，是不会私自扫描用户文件的
> 
> 注1：一些公开的违规视频，在你的网盘内突然别屏蔽，并不是阿里云盘扫描了你的网盘内的文件，而是别人分享这个文件后被审查，违禁后，阿里云盘全网根据相同的sha1/size 自动屏蔽的，不需要扫描你网盘里的文件的内容
> 
> 注2：如果是你自己拍摄的照片且从未分享过，仍然被设置为违禁文件，则说明偷偷扫描了文件内容了，但一般真的没人敢这么做，都是注1的情况

：可能是我的锅，因为我也没测试过一天1TB流量，可能超限后接口返回错误信息了，但因为我没遇到过，所以小白羊没显示提示。
老哥，你不用往小白羊身上揽。用官方任何客户端，限制期间内无论下载任何文件都只会提示下载已失败，第一次限制24小时后解除，第二次限制一周后解除，这都是各位实际实验出来的，而官方不给任何说法，这口锅小白羊不背

**Comment by gairy** [comment]
> 我提交工单反馈这个下载限制的问题后，得到客服的回复内容如下:"您好！目前云盘“流量下载异常”判定由后台系统自动判定，暂无明确人工说明，一般情况下如果您使用例如爬虫、外挂抓包工具导致短时较大流量下载都会触发系统监测机制，用户的正常上传和使用不受此监测机制影响。" 
不知道小白羊的下载机制是否会带有爬虫或者外挂抓包工具的性质呢，大神能否确认规避一下，多谢！

**Comment by gairy** [comment]
> 呃，都不用激动，限制不透明是常见操作，百度网盘也没说过超多少流量会限速（百度超会，一定流量后也会被限速的）
> 
> 感觉是因为这个限制是随着时间，经常变动的，可能不是太好量化/公开
> 
> ：超限后无任何提醒
> 
> 可能是我的锅，因为我也没测试过一天1TB流量，可能超限后接口返回错误信息了，但因为我没遇到过，所以小白羊没显示提示。
> 
> ：私自扫描用户相册内未分享的照片，进行敏感照片屏蔽
> 
> 根据阿里云盘的官方说法，是不会私自扫描用户文件的
> 
> 注1：一些公开的违规视频，在你的网盘内突然别屏蔽，并不是阿里云盘扫描了你的网盘内的文件，而是别人分享这个文件后被审查，违禁后，阿里云盘全网根据相同的sha1/size 自动屏蔽的，不需要扫描你网盘里的文件的内容
> 
> 注2：如果是你自己拍摄的照片且从未分享过，仍然被设置为违禁文件，则说明偷偷扫描了文件内容了，但一般真的没人敢这么做，都是注1的情况

我提交工单反馈这个下载限制的问题后，得到客服的回复内容如下:"您好！目前云盘“流量下载异常”判定由后台系统自动判定，暂无明确人工说明，一般情况下如果您使用例如爬虫、外挂抓包工具导致短时较大流量下载都会触发系统监测机制，用户的正常上传和使用不受此监测机制影响。"
不知道小白羊的下载机制是否会带有爬虫或者外挂抓包工具的性质呢，大神能否确认规避一下，多谢！

**Comment by ningcol** [comment]
昨天我用webDav同步电影，我看了下，应该是达到1T了，今天早上发现全是失败，后面我用网页、mac端、安卓端发现都无法下载

**Comment by PYXXXX** [comment]
想知道在开通超级会员之后限制会放宽或解除吗？

**Comment by GJG666** [comment]
> 想知道在开通超级会员之后限制会放宽或解除吗？

![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)

**Comment by PYXXXX** [comment]
> > 想知道在开通超级会员之后限制会放宽或解除吗？
> 
> ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)

本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。

**Comment by GJG666** [comment]
> > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > 
> > 
> > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> 
> 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。

两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载

**Comment by ningcol** [comment]
> > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > 
> > > 
> > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > 
> > 
> > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> 
> 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载

普通会员可以么？

**Comment by GJG666** [comment]
> > > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > > 
> > > > 
> > > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > > 
> > > 
> > > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> > 
> > 
> > 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载
> 
> 普通会员可以么？

那暂时就不清楚了，我只开了超会

**Comment by ningcol** [comment]
> > > > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > > > 
> > > > > 
> > > > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > > > 
> > > > 
> > > > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> > > 
> > > 
> > > 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载
> > 
> > 
> > 普通会员可以么？
> 
> 那暂时就不清楚了，我只开了超会

我的还在被限制着，官方客户端都不行，我提交反馈，他们说是客户端问题，没有限制我

**Comment by GJG666** [comment]
> > > > > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > > > > 
> > > > > > 
> > > > > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > > > > 
> > > > > 
> > > > > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> > > > 
> > > > 
> > > > 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载
> > > 
> > > 
> > > 普通会员可以么？
> > 
> > 
> > 那暂时就不清楚了，我只开了超会
> 
> 我的还在被限制着，官方客户端都不行，我提交反馈，他们说是客户端问题，没有限制我

当然，你可以开个普会试试看，如果解除了，即坐实了对你的账号做了限制，也可以说明普会可以解除下载限制，如果没解除，就当为其他人舍身取义了属于是

**Comment by PYXXXX** [comment]
> > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > 
> > > 
> > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > 
> > 
> > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> 
> 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载

我已经在24h内使用第三方客户端（小白羊）下载了超过300G文件，目前官方客户端和小白羊的所有功能都正常。看来阿里确实针对VIP政策限制了普通用户。

**Comment by ningcol** [comment]
我的现在了，过了两三天了，还在被限制

**Comment by ningcol** [comment]
[贴吧有人在说这个问题](https://tieba.baidu.com/p/7773618417?pn=1  )

**Comment by ningcol** [comment]
> > > > > > > > 想知道在开通超级会员之后限制会放宽或解除吗？
> > > > > > > 
> > > > > > > 
> > > > > > > ![photo_2022-03-26_12-45-20](https://user-images.githubusercontent.com/36781028/160225042-b665040f-d732-48c3-9e66-6a1da77c772a.jpg)
> > > > > > 
> > > > > > 
> > > > > > 本来对下载流量的限制官方就没有予以说明的。我看到这个会员权益表了，并且我已经开通超级会员，主要是想知道开通超级会员后有没有改善。多谢回复。
> > > > > 
> > > > > 
> > > > > 两天内没下东西，刚才下了100G的剧集，突然就被限制下载了，开了超会，限制秒解除，我现在再测试下24小时内跑个1T多的量还会不会被限制下载
> > > > 
> > > > 
> > > > 普通会员可以么？
> > > 
> > > 
> > > 那暂时就不清楚了，我只开了超会
> > 
> > 
> > 我的还在被限制着，官方客户端都不行，我提交反馈，他们说是客户端问题，没有限制我
> 
> 当然，你可以开个普会试试看，如果解除了，即坐实了对你的账号做了限制，也可以说明普会可以解除下载限制，如果没解除，就当为其他人舍身取义了属于是 (手动滑稽)

我这边显示直接被封禁，也没说几天几天啥的，你的是有告诉你几天解除限制么？

**Comment by raydoom** [comment]
刚才试了12块钱的会员，可以解除限制，正在下载文件，不知道会不会再封禁

**Comment by xxsmirror** [comment]
> 目测阿里云盘作为一个网盘服务会在连续亏损3年内落幕，如果非法将用户隐私数据用于阿里AI项目，可能会存活更久一点。但就目前的运营方针来看，充斥着阿里系一贯视用户为韭菜的理念。限制下载额度仅是一个信号，是阿里云盘对用户权利（知情权）漠视的信号；但这样的信号之前早已出现。譬如私自扫描用户相册内未分享的照片，进行敏感照片屏蔽；对部分它认为违规的分享文件屏蔽，分享链接依然存活却无任何形式的通知，但会在达到某个阈值后直接对用户账号封禁。

  预言家，现在直接非会员限速
