### ISSUE TITLE
作者您好，可以考虑使用最新的 SDK 封装类库

### ISSUE THREAD

**Issue by mingcheng** [liupan1890/aliyunpan#575]
如题，我根据云盘接口撸了个比较抽象的云盘 SDK，并认真做了测试用例以及文档说明。

应该这块可能会减轻些您这边的开发工作：  https://github.com/mingcheng/aliyundrive  希望对你有用，感谢并期待回复。

**Comment by Borber** [comment]
赞, 昨天刚在推上刷到大佬

**Comment by liupan1890** [comment]
很好的库

可惜，当前小白羊已经转为typescript
