### ISSUE TITLE
提一个建议：拖动下载

### ISSUE THREAD

**Issue by DrZhang1208** [liupan1890/aliyunpan#576]
建议在云盘里往桌面拖动，自动创建一个下载到桌面的下载任务。
看电影用外挂字幕的时候直接把字幕下载到桌面，也不用去找了

https://user-images.githubusercontent.com/97793620/157397413-38b19d7b-0b8f-4330-9f3c-e018771fff41.mp4

**Comment by adjjckjckla** [comment]
支持！！！

**Comment by liupan1890** [comment]
收到，这个功能确实很方便，而且electron也支持拖放，完美。。。

会增加此功能的！

**Comment by liupan1890** [comment]
这两天在研究这个拖放，现结果如下

1.从本地拖放到小白羊，上传。这个已经有了，不需讨论。

2.从小白羊拖放文件/文件夹到本地（任意文件夹里）

先说结论：此功能当前无法实现

---

分析的过程
小白羊的界面是基于electron开发的，直到今天electron的当前最新版本，也不支持第2种拖放操作。主要是权限的问题

1.electron支持拖放文件到本地任意位置

>electron是支持拖放文件的，但是，它的逻辑是，拖放一个文件`（文件或url路径）`，到一个本地文件夹（比如桌面），此时会触发原生拖放事件，自动下载或者自动复制`（文件或url路径）`对应的文件内容到系统临时文件夹(Temp)，然后让操作系统去复制（从Temp复制到桌面）

既，electron，拖放。如果是拖放的url，会去下载这个文件到本地Temp文件夹里
比如你在小白羊里拖放一个电影文件，扔到桌面
第一步：先下载这个电影文件到Temp文件夹里
第二步：从Temp复制这个电影文件到桌面
实际使用中，假如电影文件体积较大(1GB),那么这个拖放需要很长时间（几分钟到十分钟）
所以这个逻辑是不适合实际使用的

electron的拖放，适合拖放本地存在的文件，而不适合网盘里存在的文件

2.electron不支持拖放文件夹到本地

仅支持拖放文件，不支持拖放文件夹，原因参见上面，文件夹没有url可以去下载

3.其他的替代方案
electron原生的拖放不可用，有替代方案是，使用文件监听模块，监听指定的文件夹（比如桌面），监听到桌面内文件变动且文件名是一个特殊的文件名（自己设定的，比如XBY.Drop）,则触发后继任务，下载选中文件到桌面

但是这个方案局限性很大，既只有被监听的文件夹才能响应拖放，没有监听的（比如D:\Download\）文件夹无法响应拖放操作

----

对于其他GUI，拖放仅仅是一个很简单的操作，只要监听一下系统事件，执行复制操作就可以了。但是因为小白羊是基于electron的，electron因为安全权限原因，并未开放给我去监听系统层面的事件，所以小白羊也无法实现拖放操作

我需要获取拖放结束时，拖放到的路径（比如桌面），但electron因为安全，不告诉我这个路径。所以我没法继续

**Comment by hellodigua** [comment]
感谢调研，产品也给我提了一个这样的需求，发现你已经研究过了
