### ISSUE TITLE
Mac端扫码登录好像有点问题...

### ISSUE THREAD

**Issue by zsbai** [liupan1890/aliyunpan#58]
如题，一直是二维码失效
<img width="518" alt="截屏2021-06-23 下午1 16 52" src="https://user-images.githubusercontent.com/62942942/123039753-47e4fd80-d425-11eb-94f8-cddc1323dfd8.png">
一直刷新一直失效，刚下载完的时候扫码是可以用的，然后登陆几分钟后出现拉去文件失败，重启软件后就一直二维码失效了

**Comment by zsbai** [comment]
cookie登陆也一直是 登陆失败请重试 ，诶很奇怪

**Comment by liupan1890** [comment]
背景信息：
小白羊运行时，会启动3个进程，
1.alixby（阿里云盘小白羊v1.6.21）---仅仅是UI界面
2.aliserver ----负责所有操作
3.aria2c ---负责下载


仔细看红色的刷新二维码按钮，底下有浅色的字：网络错误

有2种情况会导致此错误：
1.你的电脑不能上网（具体的是指aliserver这个进程不能联网。有的时候会因为你的电脑代理设置导致，有的时候是你手动设置了防火墙禁止aliserver进程联网，有的时候是真的整个电脑都不能上网）
2.aliserver没有运行，或者启动后几秒立即自动退出了

当 aliserver不能上网，或者 aliserver被结束进程。此时无论扫码还是cookie都无法登陆，准确的说整个程序都没有可以正常操作的。


在 `阿里云盘小白羊v1.6.21.app/Contents/Resources/Debug.log` 这是运行日志，贴上来我看看是否有退出的报错

**Comment by zsbai** [comment]
这里是log：
2021/06/23 12:57:06 main.go:25: 



aliserver start 

2021/06/23 12:57:06 DBHelper.go:17: Start Path /Applications/阿里云盘小白羊.app/Contents/Resources/

2021/06/23 12:57:06 main.go:47: all userdata loaded

2021/06/23 12:57:06 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/23 12:57:06 GoServer.go:40: Port: localhost:29385

2021/06/23 12:57:06 Aria2.go:47: Aria2ConnectError Post "http://localhost:29386/jsonrpc": dial tcp [::1]:29386: connect: connection refused

2021/06/23 12:57:28 ApiLogin.go:87: apiMiniLogin client_id= 25dzX3vbYqktVxyX

2021/06/23 13:15:15 AutoTask.go:30: aliserver check stop

2021/06/23 13:15:15 GoServer.go:57: Shutting down server:  interrupt

2021/06/23 13:15:15 main.go:66: aliserver exit

2021/06/23 13:15:16 main.go:25: 



aliserver start 

2021/06/23 13:15:16 DBHelper.go:17: Start Path /Applications/阿里云盘小白羊.app/Contents/Resources/

2021/06/23 13:15:17 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 13:15:17 main.go:47: all userdata loaded

2021/06/23 13:15:17 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/23 13:15:17 GoServer.go:40: Port: localhost:29385

2021/06/23 13:15:17 Aria2.go:47: Aria2ConnectError Post "http://localhost:29386/jsonrpc": read tcp [::1]:57906->[::1]:29386: read: connection reset by peer

2021/06/23 13:15:25 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:15:37 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:15:40 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:15:48 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:16:09 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:16:12 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:16:14 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:16:17 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:16:45 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:17:00 main.go:25: 



aliserver start 

2021/06/23 13:17:00 main.go:30: Start Break An instance is already running

2021/06/23 13:17:00 DBHelper.go:17: Start Path /Applications/阿里云盘小白羊.app/Contents/Resources/

2021/06/23 13:17:00 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 13:17:00 main.go:47: all userdata loaded

2021/06/23 13:17:00 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/23 13:17:00 GoServer.go:40: Port: localhost:29385

2021/06/23 13:17:00 GoServer.go:45: Start ServerError:  listen tcp 127.0.0.1:29385: bind: address already in use

2021/06/23 13:17:00 Aria2.go:57: connectSuccess http://localhost:29386/jsonrpc 1.35.0

2021/06/23 13:17:00 GoServer.go:57: Shutting down server:  interrupt

2021/06/23 13:17:00 main.go:66: aliserver exit

2021/06/23 13:17:02 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 13:18:33 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 13:18:35 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 13:19:09 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 15:39:41 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 15:39:44 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 15:39:47 AutoTask.go:30: aliserver check stop

2021/06/23 15:39:47 GoServer.go:57: Shutting down server:  interrupt

2021/06/23 15:39:47 main.go:66: aliserver exit

2021/06/23 15:45:24 main.go:25: 



aliserver start 

2021/06/23 15:45:24 DBHelper.go:17: Start Path /Applications/阿里云盘小白羊.app/Contents/Resources/

2021/06/23 15:45:24 ApiLogin.go:279: ApiTokenRefresh code= 0  client_id= 

2021/06/23 15:45:24 main.go:47: all userdata loaded

2021/06/23 15:45:24 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/23 15:45:24 GoServer.go:40: Port: localhost:29385

2021/06/23 15:45:24 Aria2.go:47: Aria2ConnectError Post "http://localhost:29386/jsonrpc": dial tcp [::1]:29386: connect: connection refused

2021/06/23 15:45:27 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 16:10:41 ApiLogin.go:87: apiMiniLogin client_id= 

2021/06/23 16:38:54 ApiLogin.go:87: apiMiniLogin client_id=

**Comment by liupan1890** [comment]
``````
2021/06/23 15:45:24 ApiLogin.go:279: ApiTokenRefresh code= 0 client_id=

2021/06/23 15:45:27 ApiLogin.go:87: apiMiniLogin client_id=

2021/06/23 16:10:41 ApiLogin.go:87: apiMiniLogin client_id=

2021/06/23 16:38:54 ApiLogin.go:87: apiMiniLogin client_id=
``````

看到这几行日志，说明，当时(2021/06/23 16:38:54) aliserver这个进程无法访问https://www.aliyundrive.com/sign/in 这个网址
也就是aliserver这个进程无法联网

为什么无法联网？我也不知道。这个跟你电脑有关系，常见的就是比如你电脑里有VPN/代理，设置问题，比如开启/关闭 VPN

解决方法就是，点击小白羊，在屏幕最上方，左上角，点击阿里云盘小白羊版，点击彻底退出。最好检查一下进程管理器，确认没有aliserver这个进程了。然后重新打开小白羊 一般就行了

**Comment by liupan1890** [comment]
另外我看到你的日志里
Start Path /Applications/阿里云盘小白羊.app/Contents/Resources/

在v1.6.10之前的版本，现在已经都不正常登陆了，因为当时阿里云盘更新了api

只有v1.6.10和v1.6.13和v1.6.21可以正常登陆

是否是因为你用的是旧版？所以无法登录

**Comment by zsbai** [comment]
检查了版本号，是新版v1.6.21，我也是昨天下载的应该不会是旧版
我当前用的是surge代理，但当我关闭surge，并彻底退出后还是无法登陆
我也尝试完全退出了几次小白羊，并且重装了一遍，问题依旧....

**Comment by zsbai** [comment]
艹我突然发现问题所在，我使用surge的请求查看器想找到小白羊是否请求了阿里的登录网址，然后什么都没发现，我以为小白羊的通信方式比较底层然后我打开了surge的增强模式，然后小白羊就能够正常联网了，也能正常刷出二维码了
当我关闭增强模式小白羊立刻出现网络错误，看来实锤了是这个的问题，但我也没想到原因是什么

**Comment by zsbai** [comment]
<img width="631" alt="截屏2021-06-23 下午11 05 25" src="https://user-images.githubusercontent.com/62942942/123121139-80adc280-d477-11eb-8923-4b010c5342fd.png">
重装了几遍发现还是这样，必须打开增强模式小白羊才能联网，我好迷惑啊，这个issue就先关掉了，原来是我的问题

**Comment by liupan1890** [comment]
你可以翻一下源码，小白羊的底层http请求是直接调用的golang的http（net包），并没有其他的封装。

golang在windows上具体是怎么实现的我也没看过源码深究。

所以，不知道为什么必须是增强模式，理论上应该会自动检测并使用代理才对

**Comment by liupan1890** [comment]
另外不知道你试没试过重启电脑

有的时候，有的代理，在退出时，可能系统并没有正确清理，比如我用Fiddler，他会去设置IE代理，正常退出Fiddler就没事，如果是强制退出，那么此时IE代理仍然是走代理（代理已经退出），导致是联网失败

golang'的net包已知的问题是，他不会自动更新代理，你开启代理，他能检测到并使用代理，你关闭代理--正常的关闭，golang检测不到，仍然走代理。（正确的应该是检测到代理设置变化，不走代理了）

**Comment by zsbai** [comment]
> 另外不知道你试没试过重启电脑
> 
> 有的时候，有的代理，在退出时，可能系统并没有正确清理，比如我用Fiddler，他会去设置IE代理，正常退出Fiddler就没事，如果是强制退出，那么此时IE代理仍然是走代理（代理已经退出），导致是联网失败（重启也不管用，必须去手动设置IE代理，或者重新打开Fiddler再正确推出）
> 
> golang'的net包已知的问题是，他不会自动更新代理，你开启代理，他能检测到并使用代理，你关闭代理--正常的关闭，golang检测不到，仍然走代理。（正确的应该是检测到代理设置变化，不走代理了）

暂时没试过重启电脑，由于常年不关电脑，重启要重新打开很多东西🤣我把手上的工作弄完重启一下试试，万分感谢

**Comment by zsbai** [comment]
> 另外不知道你试没试过重启电脑
> 
> 有的时候，有的代理，在退出时，可能系统并没有正确清理，比如我用Fiddler，他会去设置IE代理，正常退出Fiddler就没事，如果是强制退出，那么此时IE代理仍然是走代理（代理已经退出），导致是联网失败（重启也不管用，必须去手动设置IE代理，或者重新打开Fiddler再正确推出）
> 
> golang'的net包已知的问题是，他不会自动更新代理，你开启代理，他能检测到并使用代理，你关闭代理--正常的关闭，golang检测不到，仍然走代理。（正确的应该是检测到代理设置变化，不走代理了）

突然想起来这个，来反馈一下，重启电脑后一切恢复正常，看起来确实是go的问题，万分感谢
