### ISSUE TITLE
自定义播放器（如potplayer）的时候，可以加载网盘的字幕吗

### ISSUE THREAD

**Issue by zzxnmq** [liupan1890/aliyunpan#581]
如题，大佬看见可以解答一下吗

**Comment by liupan1890** [comment]
不能自动的加载显示网盘内的字幕文件，

1.视频内嵌的可以正常显示
2.外挂的字幕文件，点一下下载，然后把下载完的字幕文件，拖放到 播放器上(内置MPV/自定义Potplayer)都支持


--

总结：把字幕下载到本地，拖放到播放器上

**Comment by zzxnmq** [comment]
好的好的，十分感谢
