### ISSUE TITLE
日志一直显示mSpeedEvent找不到GID是什么意思呢，每秒跳一下

### ISSUE THREAD

**Issue by itKelis** [liupan1890/aliyunpan#583]
[](url)
![image](https://user-images.githubusercontent.com/14844805/158119413-ee2a39bd-e33e-4808-89e0-3a22a8413396.png)
一秒钟会跳一次，会是什么问题呢

**Comment by liupan1890** [comment]
这是下载中的任务进度丢失导致的

但是，这个错误不重要，主要是调试时用到的，可能是忘了注释掉这个了

--

方式一：在下载中列表，点击全部暂停，然后点击 全部下载（恢复正常的下载），会消除此错误
方式二：退出小白羊，重新打开，会消除此错误

--

注：对正在下载的任务，会每秒读取一次下载进度，偶尔会出现下载进度丢失的情况
比如 aria2崩溃了
比如 此任务已经下载完成，但没有正确的回调
比如 重复的开始/暂停此任务，可能导致下载进度gid被覆盖

一般情况，这个错误不重要，可以忽略掉了

**Comment by itKelis** [comment]
谢谢大佬
