### ISSUE TITLE
好期待V3啊，每天都来看一下。

### ISSUE THREAD

**Issue by PingKuWang** [liupan1890/aliyunpan#585]
V3是不是使用React+AntD了呀，我在V3个看到了这个引用，作者可以聊聊使用的技术吗？

**Comment by liupan1890** [comment]
呃
在v2.8.30-v2.9.25 是用的ts+quasar(VUE)
在v2.10.x- v2.12.x 是用的ts+antd(REACT)

v3在2021年12月19日-2022年1月10日是使用的ts+antd(REACT)
v3在2022年1月23日开始正式切换为ts+arco-design-vue(VUE)

--

程序功能代码都是ts，
quasar/antd/arco-design-vue 只是UI库
当然更换UI库基本上需要推到重写25%的代码
v3因为是更新大版本，所以基本是推到重写了40%的代码和优化重构了20%的底层功能代码

所以v3的时间，我把握不住了，拖得有点久了。但我仍在敲代码，没有停，是值得期待的

--

等v3第一个版本发布时，会同步更新v3的全部源码的

**Comment by PingKuWang** [comment]
感谢回复，辛苦了

**Comment by jjjyyyllll** [comment]
> 呃 在v2.8.30-v2.9.25 是用的ts+quasar(VUE) 在v2.10.x- v2.12.x 是用的ts+antd(REACT)
> 
> v3在2021年12月19日-2022年1月10日是使用的ts+antd(REACT) v3在2022年1月23日开始正式切换为ts+arco-design-vue(VUE)
> 
> --
> 
> 程序功能代码都是ts， quasar/antd/arco-design-vue 只是UI库 当然更换UI库基本上需要推到重写25%的代码 v3因为是更新大版本，所以基本是推到重写了40%的代码和优化重构了20%的底层功能代码
> 
> 所以v3的时间，我把握不住了，拖得有点久了。但我仍在敲代码，没有停，是值得期待的
> 
> --
> 
> 等v3第一个版本发布时，会同步更新v3的全部源码的

大佬辛苦了，期待
