### ISSUE TITLE
按网盘结构下载文件能直接跳过已经下载的文件吗?

### ISSUE THREAD

**Issue by ybbluesky** [liupan1890/aliyunpan#587]
希望如果目录文件存在，就直接跳过

**Comment by ybbluesky** [comment]
或者如果md5不同，可以让用户批量设置下载 时是以远程文件还是本地文件为主跳过

**Comment by liupan1890** [comment]
当前，小白羊，按照网盘结构下载时，

1.检查本地是否存在同名文件
2.存在，继续检查（本地/网盘）文件大小是否一致

--

如果本地存在同名且大小一致，则直接返回下载成功

--

如果本地存在同名且大小不同，返回错误信息（本地存在重名文件请手动删除）

1.你手动删除本地文件后，可以重新开始下载任务，继续下载
2.或者手动删除这个下载任务（不下载了）

--

如果本地不存在则正常下载

--

是检查的文件，不检查文件夹。对于文件夹，也就是检查这个文件夹下面的每一个文件

**Comment by liupan1890** [comment]
>如果目录文件存在，就直接跳过

1.如果文件存在就直接跳过（现在就是这样的，存在同名，不下载，让用户手动选择）

2.如果目录存在就直接跳过（现在没有提供这个功能，我没意识到这个功能的作用，如果你需要这个功能，请详细的说一下为什么需要这个功能，特别是什么情况下会有很多人都会需要这个功能）

--

>如果md5不同，可以让用户批量设置下载 时是以远程文件还是本地文件为主跳过

这样的设置，感觉会增加用户下载的操作（选择困难症）（不是很好理解的选项）（看到这个开关不知道应该是打开还是关闭）

**Comment by ybbluesky** [comment]
> 当前，小白羊，按照网盘结构下载时，
> 
> 1.检查本地是否存在同名文件 2.存在，继续检查（本地/网盘）文件大小是否一致
> 
> --
> 
> 如果本地存在同名且大小一致，则直接返回下载成功
> 
> --
> 
> 如果本地存在同名且大小不同，返回错误信息（本地存在重名文件请手动删除）
> 
> 1.你手动删除本地文件后，可以重新开始下载任务，继续下载 2.或者手动删除这个下载任务（不下载了）
> 
> --
> 
> 如果本地不存在则正常下载
> 
> --
> 
> 是检查的文件，不检查文件夹。对于文件夹，也就是检查这个文件夹下面的每一个文件

这样的逻辑哟，那我提的意见就没有意义了，谢谢
