### ISSUE TITLE
以后会出DOCKER或者群晖套件版本吗

### ISSUE THREAD

**Issue by ljjwy168** [liupan1890/aliyunpan#59]
大佬有时间的话 能否研究下DOCKER或者群晖套件 这样我们这群下载党下东西就不用转2手了 直接从群晖里就上传下载了

**Comment by liupan1890** [comment]
额，是这样

1.DOCKER属于linux。
2.如果实现DOCKER，需要我重新用html写一遍UI，或者说当前UI编译为web版本--可以但也有部分细节不兼容
3.后台进程alserver因为是golang也是支持直接编译出linux的，这个问题不大
4.群晖 我没用过，所以一点也不了解。是真的一点也没接触过，只知道是个路由器系统，也就是linux（说这个是说我没有群晖，我编译出linux都不知道怎么测试，不测试仅仅编译通过了实际使用必然有一堆问题--会不兼容的地方）


因为我每天也不是有很多时间能够编程，当前因为小白羊刚上线一个月，所以也有很多功能在排队等着我做。所以我现在一点适配群晖的想法也没有，linux经过测试效果也不理想，暂时先搁置住了。

等我把想要实现的功能全部都做完了，在适配linux设置群晖吧。但也要看最后的web到底能兼容到什么地步。

排队的功能：导入阿里云/115 **分享** 链接，文件同步，聚合搜索。
偶发的BUG：每天都有新BUG被提出

所以，你看，确实安排不过来。但是小白羊本身是开源的，是真的开源，所有的代码都在github上，如果有能力，你也可以自己试一下，帮我减少了工作了。我会合并

**Comment by ljjwy168** [comment]
好的 谢谢大佬 那我继续用PC版本
