### ISSUE TITLE
MPV播放器如何将字幕移动到黑边上？

### ISSUE THREAD

**Issue by luxiyourbro** [liupan1890/aliyunpan#591]

**Comment by liupan1890** [comment]
默认时，按下键盘  上的 ` r `  和 ` R ` 调整字幕位置(r上移 R下移)
不过，一般推荐你在设置里选择 自定义播放器--Potplayer，然后就可以右键鼠标，自由的调整字幕位置大小颜色了

**Comment by luxiyourbro** [comment]
> 

这个我知道，但是r只能调节到影片画面内下方，不能调到画面外部的下方

**Comment by DrZhang1208** [comment]
你可以去查一下，网上mpv的教程

**Comment by luxiyourbro** [comment]
已解决，关闭。

**Comment by Artemis2179** [comment]
请问这个怎么解决啊，教程找不到啊，怎么都挪不动，就在画面里
