### ISSUE TITLE
阿里开始会员收费后，小白羊会怎样？

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#593]
据说阿里云盘开始VIP会员收费后，非会员播放视频只支持720P了，会员和超级会员也只有1080P。
这个是通过服务器端还是客户端来限制的？

如果是服务器端，那小白羊也会被限制吧。

如果是客户端，那小白羊就可以绕开这个限制了？如果小白杨能绕开，那阿里还会允许小白羊的存在？

**Comment by prodcd** [comment]
先确认VIP内容再说吧

**Comment by Sunovn** [comment]
> 先确认VIP内容再说吧
已经有图片了

**Comment by Sunovn** [comment]
![79f359894a4ab26643409921b0c9bdc4](https://user-images.githubusercontent.com/91693891/159628496-7c8366ec-99ef-4199-9dbe-468dbcf5bbad.jpg)

**Comment by Sunovn** [comment]
如果强制原始视频还能用就没什么影响了，不然还得像以前一样，下载之后再放

**Comment by liupan1890** [comment]
这么早就有截图了？你们怎么就这么厉害呢？？？

>VIP会员收费后，非会员播放视频只支持720P了

这一点对小白羊的使用影响不大，最主要是影响手机客户端，而不是PC/网页端
视频在线预览时，可以选择`播放转码视频` 还是 `播放原始文件`，720P限制的是`转码视频`

- PC上一般大家会选择`播放原始文件`(清晰度更高，支持切换音轨，支持显示/切换内嵌字幕)
- 如果选择`转码视频`，那么需要看阿里云盘是怎么限制的了，可能可以绕过，可能绕不过

总之：播放原始文件就可以继续高清了（阿里云盘并不限制文件下载速度，播放原始文件也没有那么卡）

--

看了一下截图，

1. 在百度的培养下，有很多很多的人，已经接受了付费用网盘了，大家接受不了的，是约200/年的价格

2. 阿里云盘的会员，就已经够用了，更贵的超级会员意义不大。估计约100/年？反正不可能会员就卖到199/年，毕竟还有个超级会员呢，这个联系到上面的问题了，估计很多人会付费的，也就是一点不受影响了

--

**Comment by zhaoxuyan** [comment]
> 这么早就有截图了？你们怎么就这么厉害呢？？？
> 
> > VIP会员收费后，非会员播放视频只支持720P了
> 
> 这一点对小白羊的使用影响不大，最主要是影响手机客户端，而不是PC/网页端 视频在线预览时，可以选择`播放转码视频` 还是 `播放原始文件`，720P限制的是`转码视频`
> 
> * PC上一般大家会选择`播放原始文件`(清晰度更高，支持切换音轨，支持显示/切换内嵌字幕)
> * 如果选择`转码视频`，那么需要看阿里云盘是怎么限制的了，可能可以绕过，可能绕不过
> 
> 总之：播放原始文件就可以继续高清了（阿里云盘并不限制文件下载速度，播放原始文件也没有那么卡）
> 
> --
> 
> 看了一下截图，
> 
> 1. 在百度的培养下，有很多很多的人，已经接受了付费用网盘了，大家接受不了的，是约200/年的价格
> 2. 阿里云盘的会员，就已经够用了，更贵的超级会员意义不大。估计约100/年？反正不可能会员就卖到199/年，毕竟还有个超级会员呢，这个联系到上面的问题了，估计很多人会付费的，也就是一点不受影响了
> 
> --
> 
> 补充1：其实我经常用阿里云盘手机版看视频（特指投屏到电视），此时开会员很有用（1080P）,我网盘账号16T容量，但大都是1年期的，一年后剩下3T不够用，所以我必然是开会员的。只希望拼多多给力一点。
> 
> 补充2：在拼多多上4.5元/年夸克云盘，7元/月百度网盘超级会员账号，是真的香

@liupan1890 PDD上7元/月百度网盘超级会员账号没找到呢 求链接 感谢

**Comment by hummersyk** [comment]
> 总之：播放原始文件就可以继续高清了（阿里云盘并不限制文件下载速度，播放原始文件也没有那么卡）

我的担心是：不买阿里会员的前提下，还可以播放原始文件吗？阿里难道没有技术手段来限制播放原始文件吗？不花钱还能看原始文件，增加了流量占用，直接侵害到他的利益了呀。

**Comment by gordonzhgang** [comment]
[阿里云盘会员中心](https://www.aliyundrive.com/drive/membership)
![image](https://user-images.githubusercontent.com/33444551/159830098-84661d9c-eddf-4ce9-86da-79bc46fde304.png)

**Comment by RobertChou** [comment]
求PDD卖家啊

**Comment by liupan1890** [comment]
> > 总之：播放原始文件就可以继续高清了（阿里云盘并不限制文件下载速度，播放原始文件也没有那么卡）
> 
> 我的担心是：不买阿里会员的前提下，还可以播放原始文件吗？阿里难道没有技术手段来限制播放原始文件吗？不花钱还能看原始文件，增加了流量占用，直接侵害到他的利益了呀。

概念：：在线播放原始文件,就是下载文件

- 阿里云盘无法检测出，你是边下边播，还是正常下载。
- 阿里云盘只知道你要下载这个文件
- 无论是否是会员，都可以不限速的下载

 (PS1:播放软件，边下边播，和你手动下载完这个文件然后双击播放是完全一样的)
mpv播放器是把文件下载到内存里（或者临时文件里）
Potplayer是把文件下载到临时文件里 (C:\Users\yonghu\AppData\Local\Temp)

 (PS2:从技术角度讲，其实是可以知道你是边下边播的)
因为每个播放软件都有自己的User-Agent，MPV还支持伪装User-Agent
阿里云盘可以根据User-Agent去屏蔽掉边下边播
但阿里云盘当前并没有这样做+MPV播放器可以伪装为浏览器
所以上面就直接说无法检测出了，理解意思就好

 (PS3:阿里云盘会对当天下载流量过大的账号限速)
有用户反馈是2TB/天，这个限制一般来说可以忽略掉了

--

总之：能下载，能播放

**Comment by hummersyk** [comment]
> 在线播放原始文件,就是下载文件

这么说我就明白了，感谢答疑！继续支持小白羊！

**Comment by nokaka** [comment]
最近，阿里云盘上线了会员中心，299一年20t，aliyunwebdav的项目配合rclone或者nextcloud挂载并加密使用还是很香的。
但是这几个webdav项目在文件上传和文件同步上存在诸多问题，例如大文件报错、同步报错、不支持sha1校验、只能通过文件大小判断文件修改、不支持断点续传。
这些项目上传方面特性不及作者的项目，希望作者能够考虑通过某些形式实现本地挂载。

**Comment by AXBNG** [comment]
> > 总之：播放原始文件就可以继续高清了（阿里云盘并不限制文件下载速度，播放原始文件也没有那么卡）
> 
> 我的担心是：不买阿里会员的前提下，还可以播放原始文件吗？阿里难道没有技术手段来限制播放原始文件吗？不花钱还能看原始文件，增加了流量占用，直接侵害到他的利益了呀。

到时候能就是能不能就是不能呗，现在问来问去有什么意义，小白羊又没收你钱你杞人忧天个什么劲

**Comment by taribenma** [comment]
阿里云盘开始会员收费后，可以预见，接下来签到续期容量的任务肯定要取消了，原来送的容量将陆续到期，所以我现在特别期待新版小白羊的批量删除违规视频、重复文件去重、多账号网盘内容迁移这几个功能。

**Comment by liupan1890** [comment]
批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。

但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动

可能是我想要的太多，（因为v2.12已经提供了标准的常用的功能了），
在v3开发中我主要是在尝试一些之前没有的新功能，比如
- 文件加密免和谐
- 可维持7天的秒传分享链接
- alimc文件功能
- 自定义标签快捷访问功能
- 更快的上传下载性能
- 减少本地数据体积
- 更快速的文件列表
- 取消aria2依赖
- 百度网盘秒传链接导入
- 版本自动更新
- 订阅的公众号相关功能
- 整理推荐热门公众号
- 更好的键盘操作支持
- 更好的列表选择支持
- 在线打包网盘内的文件/文件夹为zip压缩包
- 视频/图片文件的meta属性(分辨率/码率)
- 在线编辑doc
- 增加网页版播放器
- 支持相册相关功能
- 支持放映室相关功能

等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。
总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想

所以大家要有心理准备，说不准就是5-6月份去了

**Comment by prodcd** [comment]
> 批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。
> 
> 但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动
> 
> 可能是我想要的太多，（因为v2.12已经提供了标准的常用的功能了）， 在v3开发中我主要是在尝试一些之前没有的新功能，比如
> 
> * 文件加密免和谐
> * 可维持7天的秒传分享链接
> * alimc文件功能
> * 自定义标签快捷访问功能
> * 更快的上传下载性能
> * 减少本地数据体积
> * 更快速的文件列表
> * 取消aria2依赖
> * 百度网盘秒传链接导入
> * 版本自动更新
> * 订阅的公众号相关功能
> * 整理推荐热门公众号
> * 更好的键盘操作支持
> * 更好的列表选择支持
> * 在线打包网盘内的文件/文件夹为zip压缩包
> * 视频/图片文件的meta属性(分辨率/码率)
> * 在线编辑doc
> * 增加网页版播放器
> * 支持相册相关功能
> * 支持放映室相关功能
> 
> 等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。 总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想
> 
> 所以大家要有心理准备，说不准就是5-6月份去了

大佬威武，很多人都在期待V3版本，但为什么大佬不是把各项功能一个一个完成，而要全部完成才发布？

另外我也有些奇奇怪怪的脑洞功能想和大佬说下，望大佬参考。

1. 公共空间。类似网盘每个帐号只保存文件索引而不是文件内容，或者说类似PT，有个公共空间。每个人都可以共享出来一部分网盘空间，由小白羊客户端备份公用数据，大家都能随时把公用空间的数据保存到私有空间中。只有有需要时才拿回来，平时不占用网盘空间。需要小白羊客户端每次启动都检查公共空间里各数据的备份份数，或者有专门的服务器，自动调节备份数量。
2. 利用阿里云盘压缩视频。有些视频我这并不需要高码流，想导出一份低码流视频，本地性能有限，编码时间太长。不着急的话可以上传到阿里云盘，等阿里云盘压缩好以后下载回来。
3. 百度导入。很多人都有百度网盘导入到阿里云盘的需求。可以增加积分类的设定，建立个平台发布任务，有需要的人支付积分，别人认领任务，返回分享链接，获得积分奖励。
4. 在本地或网盘中，缓存上传过的压缩包里面的文件内容。有的压缩包很大，忘记里面都有些什么文件，又不想整个下载，可以从缓存中预览压缩包的文件结构。

以上内容，如果影响V3发布时间，请忽略！

**Comment by taribenma** [comment]
> 批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。
> 
> 但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动
> 
> 可能是我想要的太多，（因为v2.12已经提供了标准的常用的功能了）， 在v3开发中我主要是在尝试一些之前没有的新功能，比如
> 
> * 文件加密免和谐
> * 可维持7天的秒传分享链接
> * alimc文件功能
> * 自定义标签快捷访问功能
> * 更快的上传下载性能
> * 减少本地数据体积
> * 更快速的文件列表
> * 取消aria2依赖
> * 百度网盘秒传链接导入
> * 版本自动更新
> * 订阅的公众号相关功能
> * 整理推荐热门公众号
> * 更好的键盘操作支持
> * 更好的列表选择支持
> * 在线打包网盘内的文件/文件夹为zip压缩包
> * 视频/图片文件的meta属性(分辨率/码率)
> * 在线编辑doc
> * 增加网页版播放器
> * 支持相册相关功能
> * 支持放映室相关功能
> 
> 等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。 总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想
> 
> 所以大家要有心理准备，说不准就是5-6月份去了

望眼欲穿啊，不如把已经做出来的功能整合一下，先来个V2.5？

**Comment by KHLFYY** [comment]
> > 批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。
> > 但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动
…………
> > * 在线编辑doc
> > * 增加网页版播放器
> > * 支持相册相关功能
> > * 支持放映室相关功能
> > 
> > 等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。 总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想
> > 所以大家要有心理准备，说不准就是5-6月份去了
> 
> 望眼欲穿啊，天天盼着V3出来，能不能把已经做出来的功能整合一下，先来一版更新？

附议，希望作者能先发布一个 v3 让大家先用着

**Comment by Sunovn** [comment]
> > 批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。
> > 但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动
> > 可能是我想要的太多，（因为v2.12已经提供了标准的常用的功能了）， 在v3开发中我主要是在尝试一些之前没有的新功能，比如
> > 
> > * 文件加密免和谐
> > * 可维持7天的秒传分享链接
> > * alimc文件功能
> > * 自定义标签快捷访问功能
> > * 更快的上传下载性能
> > * 减少本地数据体积
> > * 更快速的文件列表
> > * 取消aria2依赖
> > * 百度网盘秒传链接导入
> > * 版本自动更新
> > * 订阅的公众号相关功能
> > * 整理推荐热门公众号
> > * 更好的键盘操作支持
> > * 更好的列表选择支持
> > * 在线打包网盘内的文件/文件夹为zip压缩包
> > * 视频/图片文件的meta属性(分辨率/码率)
> > * 在线编辑doc
> > * 增加网页版播放器
> > * 支持相册相关功能
> > * 支持放映室相关功能
> > 
> > 等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。 总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想
> > 所以大家要有心理准备，说不准就是5-6月份去了
> 
> 大佬威武，很多人都在期待V3版本，但为什么大佬不是把各项功能一个一个完成，而要全部完成才发布？
> 
> 另外我也有些奇奇怪怪的脑洞功能想和大佬说下，望大佬参考。
> 
> 1. 公共空间。类似网盘每个帐号只保存文件索引而不是文件内容，或者说类似PT，有个公共空间。每个人都可以共享出来一部分网盘空间，由小白羊客户端备份公用数据，大家都能随时把公用空间的数据保存到私有空间中。只有有需要时才拿回来，平时不占用网盘空间。需要小白羊客户端每次启动都检查公共空间里各数据的备份份数，或者有专门的服务器，自动调节备份数量。
> 2. 利用阿里云盘压缩视频。有些视频我这并不需要高码流，想导出一份低码流视频，本地性能有限，编码时间太长。不着急的话可以上传到阿里云盘，等阿里云盘压缩好以后下载回来。
> 3. 百度导入。很多人都有百度网盘导入到阿里云盘的需求。可以增加积分类的设定，建立个平台发布任务，有需要的人支付积分，别人认领任务，返回分享链接，获得积分奖励。
> 4. 在本地或网盘中，缓存上传过的压缩包里面的文件内容。有的压缩包很大，忘记里面都有些什么文件，又不想整个下载，可以从缓存中预览压缩包的文件结构。
> 
> 以上内容，如果影响V3发布时间，请忽略！
你说的都很有用

**Comment by Sunovn** [comment]
> > 批量删除违规视频、重复文件去重、多账号之间网盘内容复制 已经做完了，在v3第一个版本发布时就可用了。
> > 但v3的发布时间，还要延后，因为考虑适配云盘VIP更新后的一些改动
> > 可能是我想要的太多，（因为v2.12已经提供了标准的常用的功能了）， 在v3开发中我主要是在尝试一些之前没有的新功能，比如
> > 
> > * 文件加密免和谐
> > * 可维持7天的秒传分享链接
> > * alimc文件功能
> > * 自定义标签快捷访问功能
> > * 更快的上传下载性能
> > * 减少本地数据体积
> > * 更快速的文件列表
> > * 取消aria2依赖
> > * 百度网盘秒传链接导入
> > * 版本自动更新
> > * 订阅的公众号相关功能
> > * 整理推荐热门公众号
> > * 更好的键盘操作支持
> > * 更好的列表选择支持
> > * 在线打包网盘内的文件/文件夹为zip压缩包
> > * 视频/图片文件的meta属性(分辨率/码率)
> > * 在线编辑doc
> > * 增加网页版播放器
> > * 支持相册相关功能
> > * 支持放映室相关功能
> > 
> > 等等各种奇奇怪怪的，脑洞功能，有些想法很好，但开发后又觉得不理想。 总之是来来回回的折腾。v3我已经做了2个多月了，但功能的开发进度还是不理想
> > 所以大家要有心理准备，说不准就是5-6月份去了
> 
> 大佬威武，很多人都在期待V3版本，但为什么大佬不是把各项功能一个一个完成，而要全部完成才发布？
> 
> 另外我也有些奇奇怪怪的脑洞功能想和大佬说下，望大佬参考。
> 
> 1. 公共空间。类似网盘每个帐号只保存文件索引而不是文件内容，或者说类似PT，有个公共空间。每个人都可以共享出来一部分网盘空间，由小白羊客户端备份公用数据，大家都能随时把公用空间的数据保存到私有空间中。只有有需要时才拿回来，平时不占用网盘空间。需要小白羊客户端每次启动都检查公共空间里各数据的备份份数，或者有专门的服务器，自动调节备份数量。
> 2. 利用阿里云盘压缩视频。有些视频我这并不需要高码流，想导出一份低码流视频，本地性能有限，编码时间太长。不着急的话可以上传到阿里云盘，等阿里云盘压缩好以后下载回来。
> 3. 百度导入。很多人都有百度网盘导入到阿里云盘的需求。可以增加积分类的设定，建立个平台发布任务，有需要的人支付积分，别人认领任务，返回分享链接，获得积分奖励。
> 4. 在本地或网盘中，缓存上传过的压缩包里面的文件内容。有的压缩包很大，忘记里面都有些什么文件，又不想整个下载，可以从缓存中预览压缩包的文件结构。
> 
> 以上内容，如果影响V3发布时间，请忽略！

你说的都很有用

**Comment by hummersyk** [comment]
批量重命名！
批量重命名！！
批量重命名！！！
就是因为它，我一直在用2.9.24，对于文件名强迫症患者来说，它是第一重要的功能！

**Comment by liupan1890** [comment]
批量重命名在v3里也已经做完了，会在v3第一个版本发布时可用

**Comment by liupan1890** [comment]
>1.公共空间

这个空间容量可能比较大，并且也会带来一些问题（版权），最后也确实无法保证某个文件一定百分百能取回。所以不太可行

>2.利用阿里云盘压缩视频 

以后会开发一下内置的m3u8转码后视频的下载合并功能

>3.百度导入

人员不可控，所以暂时仅考虑导入百度秒传链接这个方向，等以后功能稳定了再考虑。其实等以后，感觉这个功能也不是必须的功能了，阿里云盘内的资源很多了

>4.在本地或网盘中，缓存上传过的压缩包里面的文件内容

对于4GB以内的压缩包（忘了阿里云盘支持的压缩包大小了），可以通过直接在线解压功能（解压前会显示压缩包内文件列表让你选择）直接看到有哪些文件。

对于过大的文件，或者其他的压缩包格式(7z/分片压缩)，这个功能确实有用，
会考虑在上传压缩包前，先解析压缩包文件列表（生成一个压缩包tree.txt文件），与压缩包文件同时上传
这样网盘里有2个文件，一个压缩包，一个txt目录。这个功能需要排在最后了

**Comment by Smithssss** [comment]
阿里云盘最头疼的是分享链接总是有些东西无法分享和获取，搞死我了，想了想如果可以把分享链接复制到v3版本，让小白羊进行解析，就像115秒存一样，然后再从115或百度中秒存过来。
咱这应该不违反阿里的利益吧，咱还用了更多的容量了呢，可不是以前的小内存秒传，咱这叫秒存，不过是分享中间多绕了一圈，不一定全部都中就是。

**Comment by yuankeyuan** [comment]
> 批量重命名！ 批量重命名！！ 批量重命名！！！ 就是因为它，我一直在用2.9.24，对于文件名强迫症患者来说，它是第一重要的功能！

工具：clouddrive（挂载）+Bulk Rename Utility（批量命名软件）
着急的话可以用clouddrive挂载工具挂载到本地，然后再用软件比如Bulk Rename Utility可以批量重命名。我自己在网上抄了一些递归文件夹+重命名的代码，批量重命名还挺好用的。但是，文件查重非常慢，我发现他是把整个文件下载下来在去查重的，我那20T网课要查重到地老天荒！连续两周我每天都来看一眼更新了文件查重没

**Comment by liupan1890** [comment]
> 阿里云盘最头疼的是分享链接总是有些东西无法分享和获取，搞死我了，想了想如果可以把分享链接复制到v3版本，让小白羊进行解析，就像115秒存一样，然后再从115或百度中秒存过来。 咱这应该不违反阿里的利益吧，咱还用了更多的容量了呢，可不是以前的小内存秒传，咱这叫秒存，不过是分享中间多绕了一圈，不一定全部都中就是。

在v3里提供了文件加密的功能，可以分享任意文件（文件体积不变），接收者可以直接在线解密（1秒内恢复原始文件）

**Comment by liupan1890** [comment]
> > 批量重命名！ 批量重命名！！ 批量重命名！！！ 就是因为它，我一直在用2.9.24，对于文件名强迫症患者来说，它是第一重要的功能！
> 
> 工具：clouddrive（挂载）+Bulk Rename Utility（批量命名软件） 着急的话可以用clouddrive挂载工具挂载到本地，然后再用软件比如Bulk Rename Utility可以批量重命名。我自己在网上抄了一些递归文件夹+重命名的代码，批量重命名还挺好用的。但是，文件查重非常慢，我发现他是把整个文件下载下来在去查重的，我那20T网课要查重到地老天荒！连续两周我每天都来看一眼更新了文件查重没

在v3里文件查重经历了多次优化，我整个网盘包含130万个文件，大概需要半小时。
关键是网课的花都是视频，文件查重时可以选择只对视频文件查重，查重一遍整个网盘应该在3-10分钟这样就查完了
