### ISSUE TITLE
没有国内手机号如何使用呢

### ISSUE THREAD

**Issue by uxth** [liupan1890/aliyunpan#595]
有办法用国外手机号注册吗？

**Comment by liupan1890** [comment]
你好，是阿里云盘本身不支持国外手机号码注册

当前阿里云盘只在国内提供服务，必须使用国内的手机号码才能接收到短信验证码。
并且即使你在国外，借用国内的手机登录了，在国外使用时体验也不好，下载速度很慢，反应比较卡。
国内我下载一个文件是70MB/s(600兆光纤) 国外大家反馈一般在2MB/s以下

**Comment by uxth** [comment]
非常感谢。
看来在国外想要使用阿里云盘非常困难。
