### ISSUE TITLE
软件什么时候能出正式版

### ISSUE THREAD

**Issue by QRQF001** [liupan1890/aliyunpan#6]

**Comment by QRQF001** [comment]
2021-05-24冒个泡，大佬软件什么时候能发

**Comment by omy2000** [comment]
永远支持大佬

**Comment by liupan1890** [comment]
今天完成了下载功能，明天会测试一下，可能的话把上传也做了，争取后天（27日）上传一份开发版本，可以让大家勉强用用，上传时会一同上传源码。

开发计划是：
本周实现阿里云盘全部功能（应该就还差移动复制，文本/音乐/视频/图片预览）
下周实现分享功能--我规划的分享功能不少
下下周是维护，把上两周的能发现的BUG改改
之后就是离线功能了

排的挺满，想的挺香，实际看情况吧，一般实际都会比预想慢很多，有很多情况预料不到吗

**Comment by gantz-ops** [comment]
@liupan1890 考虑到某些冷门资源离线很慢，想问问是不是可以考虑集成一下115网盘的离线下载功能。如果大佬感兴趣可以私聊我，我这边可以提供免费的115会员号

**Comment by WHYEX3** [comment]
大佬加油

**Comment by liupan1890** [comment]
已发布 v1.5.25 开发中版本仅供测试

**Comment by QRQF001** [comment]
很早之前就已经 Star 了
