### ISSUE TITLE
v3会有同步盘功能么？OneDrive太难用了

### ISSUE THREAD

**Issue by Doddddd** [liupan1890/aliyunpan#601]

**Comment by liupan1890** [comment]
会有，单向/双向/增量/多个文件夹  
但是，近期阿里云盘官方本身在搞同步盘功能了
所以在观望官方的进度，因为官方上线同步盘功能，可能会提供一些同步盘的接口

最开始我做的同步盘是基于自己的逻辑去同步的，调用文件上传接口/文件列表接口
官方可能会推出一些同步盘专用的接口

所以应该等官方同步盘上线后，使用官方提供的同步盘专用的接口，使同步盘功能符合官方的规划

--

总之：会有，并且肯定会更丰富

**Comment by Doddddd** [comment]
> 会有，单向/双向/增量/多个文件夹  
> 但是，近期阿里云盘官方本身在搞同步盘功能了
> 所以在观望官方的进度，因为官方上线同步盘功能，可能会提供一些同步盘的接口
> 
> 最开始我做的同步盘是基于自己的逻辑去同步的，调用文件上传接口/文件列表接口
> 官方可能会推出一些同步盘专用的接口
> 
> 所以应该等官方同步盘上线后，使用官方提供的同步盘专用的接口，使同步盘功能符合官方的规划
> 
> --
> 
> 总之：会有，并且肯定会更丰富

期待！

**Comment by luxiyourbro** [comment]
Onedrive 哪里难用了，说说看

**Comment by Doddddd** [comment]
> Onedrive 哪里难用了，说说看

1、卡、占用高，也可能是我电脑性能太弱
2、每次上传1g以上大文件都会失败好几次
3、mklink不方便
4、如果不一直挂在后台，会出现旧文件覆盖新文件
