### ISSUE TITLE
违规视频可以播放，但是无法查看详情了

### ISSUE THREAD

**Issue by xuxudong1110** [liupan1890/aliyunpan#605]
本来违规视频可以看到详情里面的M3u8地址的，现在打开详情都是
![image](https://user-images.githubusercontent.com/49015852/160735816-7e60a5aa-aefe-44d2-9c8a-5790f366b9f6.png)

**Comment by liupan1890** [comment]
你好

是的，这是v2.12的BUG，会在v3里修复此问题
