### ISSUE TITLE
阿里会封掉第三方客户端吗？小白羊如何规避？

### ISSUE THREAD

**Issue by hummersyk** [liupan1890/aliyunpan#607]
据说（只是据说）已经有人因为用小白羊被封号了，当然大概率是因为过度下载，属于使用不当吧。

但是从阿里的条款来说，他是有权封掉非官方客户端的，我觉得小白羊有必要采取一些规避措施吧，不然前功尽弃了岂不是可惜了？

![1](https://user-images.githubusercontent.com/89259789/160951210-b9016b60-c8d8-43c9-9200-4b058aac503f.jpg)

![2](https://user-images.githubusercontent.com/89259789/160951212-6616f1c8-2827-4f08-b4e0-6c43d0523620.jpg)

**Comment by liupan1890** [comment]
1. 阿里云盘官方和我有沟通，官方并不打击/抑制 第三方客户端，官方允许第三方的存在
2. 
3. 近期确实有用户因为使用小白羊二被限制下载（参阅 https://github.com/liupan1890/aliyunpan/issues/597 ），主要是当设置为太多文件同时下载时容易触发官方的限制（也可以对应上面第一张截图中的不合理方式高频访问系统）
4. 
5. 电脑软件，已经发布的版本，我也无法修改/调整。但会在以后的v3版本中对”高频访问“进行主动的限制/调整。使其符合官方的规划
6. 
7. 并不需要避归，因为如果以后政策改变了，官方回联系到我，我自然会停止小白羊版本的维护/下载


--

任何产品，都会明确的提示用户：不推荐使用第三方，后果自负。

**Comment by hummersyk** [comment]
跟官方有过沟通就好啊。用户协议总是按保障自己最大利益来制定，实际不会这么严。

小白羊对”高频访问“进行限制确实是必要的，毕竟因为这个被封号就没得玩了。

期待V3！

**Comment by prodcd** [comment]
官方把客户端做好用些不就得了，连个排序都那么烂，就别怪用户转第三方。

**Comment by FlashloverAgustin** [comment]
感谢解答，放心了些

**Comment by xuxudong1110** [comment]
还不是大佬开发的小白羊比官方自己的好用，而且听说项目组邀请大佬去阿里工作，大佬竟然选择不去

**Comment by KHLFYY** [comment]
> 还不是大佬开发的小白羊比官方自己的好用，而且听说项目组邀请大佬去阿里工作，大佬竟然选择不去


开发语言不同

**Comment by blibilijojo** [comment]
> 

人家之前就是程序员，可能是受不了程序员这个职业把
