### ISSUE TITLE
github release 可否更新一下

### ISSUE THREAD

**Issue by zema1** [liupan1890/aliyunpan#608]
我 watch 了github release，这样一有更新我会收到邮件，似乎已经有好几个版本只在览奏网盘有，可否同步传一下 release。感谢~

**Comment by liupan1890** [comment]
你好

因为v2.10-v2.12 是测试版本，所以没有发布release

会在v3的第一个版本发布时，同步更新源码/release，以后的版本更新也会同步release的

**Comment by zema1** [comment]
感谢回复，我觉得这种情况和 github 的  pre release 比较像，可以考虑用一下。

不管怎样，这是一个很棒的项目，我只是比较期待新版罢了🙈
