### ISSUE TITLE
提示框

### ISSUE THREAD

**Issue by Wsy1084048874** [liupan1890/aliyunpan#61]
提示更新的框一直显示，咋关掉它呢

**Comment by liupan1890** [comment]
你用的是v1.6.21吗？不是的话请升级，是的话那就是有BUG，理论上你点击彻底退出后重新打开就好了

如果推出还不行，那就把整个文件夹删掉，重新下载一份

我感觉大概率是因为你没有下载最新版所以才有更新提示框

**Comment by Wsy1084048874** [comment]
我用的1.6.13版本，因为可以分享链接，就没更新。打开主界面更新提示一直在，想给它关掉或者不要自动检查更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月25日(星期五) 上午9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liupan1890/aliyunpan] 提示框 (#61)





 
你用的是v1.6.21吗？不是的话请升级，是的话那就是有BUG，理论上你点击彻底退出后重新打开就好了
 
如果推出还不行，那就把整个文件夹删掉，重新下载一份
 
我感觉大概率是因为你没有下载最新版所以才有更新提示框

**Comment by liupan1890** [comment]
哦，因为程序是写死的，所以无法让他不要检查更新，

你这样操作
1.点击设置
2.点击浅色模式--切换为深色模式
3.点击神色模式--切换到浅色模式
好了，更新提示消失了，每一次打开程序都要这样操作一遍
