### ISSUE TITLE
大佬，v3版本中请多加一些注释，谢谢

### ISSUE THREAD

**Issue by zhengge791254521** [liupan1890/aliyunpan#610]
如题，我也在做批量上传下载的功能，之前参考了你的案例。 但我这边基本上文件超过500个就特别卡。（大概是我菜）

另外引入area2之后。windows中 360就经常问候。时不时还把area给我当病毒删了

**Comment by liupan1890** [comment]
1. 基本上文件超过500个就特别卡

应该是你代码的问题，js，500循环，不会卡的。数千个也不会明显卡，
超过几千，就应该分成2个队列了，
第1个队列最多1000个然后是正在执行的（刷新进度），
第2个队列是剩余的任务，但是不刷新。队列1快空的时候从队列2提取补满

2.另外引入area2之后。windows中 360就经常问候

这个无法避免，所以v1的时候我还用flutter/go ，v2就切换到electron了。v3里再尝试弃用aria2了。因为阿里云盘不限速+开始限制并发文件数量 ，aria2优点（多线程/性能）用不到了，js下载就满足了。

js一般不会报毒了

或者，买个证书自己给aria2.exe签名一下，就可以稳定的用了

**Comment by zhengge791254521** [comment]
好的，了解。我目前也是在electron上做项目。确实很多细节考虑不到，之前看你的代码，有很多地方还是有参考的，就是没有注释是个挠头的地方。 另外v2.12.5 和v3会开源么。
