### ISSUE TITLE
Aria2c未知错误

### ISSUE THREAD

**Issue by PYXXXX** [liupan1890/aliyunpan#611]
在使用香港网络环境下载时频繁出现此问题，想知道是否与这点有关？（ping阿里云盘时也会出现丢包）
![image](https://user-images.githubusercontent.com/85445850/161374092-776e1a5e-92b2-4b81-8843-a0da03f14a13.png)

**Comment by liupan1890** [comment]
怀疑是网络不太好，导致的超时断线，你可以看一下下载速度是否稳定（是一直保持1MB/s还是上下浮动非常剧烈）

仅从截图去分析
```
1.小白羊把下载任务推送给aria2
2.aria2去下载
3.小白羊刷新进度
```
现在是aria2下载过程中间出错了，
如果是每15-20分钟固定的时间失败一次/自动重试/固定间隔失败/自动重试/.... 说明时下载链接的问题
如果是下载中，下载速度剧烈波动，长时间速度为10kb/s以内，会因速度过低自动断开失败

**Comment by PYXXXX** [comment]
> 

是您说的网络波动问题。下载速度会在0-30m/s间反复波动，怀疑是阿里云盘针对腾讯云香港节点作出的限制（阿里云香港节点不存在此问题），感谢解答。
