### ISSUE TITLE
[建议] 使用Windows系统窗口框架

### ISSUE THREAD

**Issue by Doddddd** [liupan1890/aliyunpan#613]
<img width="253" alt="{2A4A0790-C18C-4FC2-9323-9EF206345E62}" src="https://user-images.githubusercontent.com/88972478/161415900-d3faf75a-794e-4ebb-8871-130f580b8ad9.png">

**Comment by liupan1890** [comment]
呃，其实我没看懂

1.是否在说，希望支持如图上面，点击后自动调整窗口大小（比如点击第一个，把小白羊窗口调整为桌面一半大小）？

win11?这个属于系统的特性吧?

2.是否在说使用特定的GUI框架开发小白羊？
比如WinUI? WPF?

**Comment by Doddddd** [comment]
> 呃，其实我没看懂
> 
> 1.是否在说，希望支持如图上面，点击后自动调整窗口大小（比如点击第一个，把小白羊窗口调整为桌面一半大小）？
> 
> win11?这个属于系统的特性吧?
> 
> 2.是否在说使用特定的GUI框架开发小白羊？
> 比如WinUI? WPF? 
其实我也不太懂，只是看到https://github.com/Icalingua-plus-plus/Icalingua-plus-plus这个项目有这个功能，也是用electron开发的
