### ISSUE TITLE
大佬，v3啥时候能更新啊，今年或者半年内可以吗

### ISSUE THREAD

**Issue by blibilijojo** [liupan1890/aliyunpan#614]
从去年就开始看了

**Comment by jjjyyyllll** [comment]
是 也是等了好久了 不会搁浅了吧

**Comment by liupan1890** [comment]
v3正在开发中

原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整，
1.需要对一些免费/VIP有区别的功能进行调整
（比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）

2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能

这样一来，就有很多功能都需要调整了

so ,v3发布慢，也不光是我因为工作很少有时间开发，
很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间

--

插旗，尽量赶在4月30日前发布

**Comment by jjjyyyllll** [comment]
> v3正在开发中
> 
> 原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整， 1.需要对一些免费/VIP有区别的功能进行调整 （比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）
> 
> 2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能
> 
> 这样一来，就有很多功能都需要调整了
> 
> so ,v3发布慢，也不光是我因为工作很少有时间开发， 很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间
> 
> --
> 
> 插旗，尽量赶在4月30日前发布

感谢大佬的辛苦开发和抽空解答

**Comment by taribenma** [comment]
感谢大佬的辛苦开发和抽空解答，对V3版本非常期待。

**Comment by dectn** [comment]
> v3正在开发中
> 
> 原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整， 1.需要对一些免费/VIP有区别的功能进行调整 （比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）
> 
> 2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能
> 
> 这样一来，就有很多功能都需要调整了
> 
> so ,v3发布慢，也不光是我因为工作很少有时间开发， 很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间
> 
> --
> 
> 插旗，尽量赶在4月30日前发布

原来如此，致敬大佬！

**Comment by zaqzaq0125** [comment]
> v3正在开发中
> 
> 原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整， 1.需要对一些免费/VIP有区别的功能进行调整 （比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）
> 
> 2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能
> 
> 这样一来，就有很多功能都需要调整了
> 
> so ,v3发布慢，也不光是我因为工作很少有时间开发， 很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间
> 
> --
> 
> 插旗，尽量赶在4月30日前发布

感谢大佬

**Comment by EchoGroot** [comment]
感谢大佬

**Comment by snow212-cn** [comment]
> v3正在开发中
> 
> 原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整， 1.需要对一些免费/VIP有区别的功能进行调整 （比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）
> 
> 2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能
> 
> 这样一来，就有很多功能都需要调整了
> 
> so ,v3发布慢，也不光是我因为工作很少有时间开发， 很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间
> 
> --
> 
> 插旗，尽量赶在4月30日前发布

脸疼不

**Comment by EchoGroot** [comment]
> > v3正在开发中
> > 原来是打算4月初发布第一个测试版本，但因为近期阿里云盘调整， 1.需要对一些免费/VIP有区别的功能进行调整 （比如导入分享链接，原来是一键保存，现在要先去分用户是否是VIP账号，免费账号需要自动分割导入）
> > 2.需要对阿里云盘的“访问频次限制”进行详细的测试和调整，主要涉及下载功能
> > 这样一来，就有很多功能都需要调整了
> > so ,v3发布慢，也不光是我因为工作很少有时间开发， 很多功能一遍一遍的来回调整，也是一件很麻烦的事，这个浪费了大量的时间
> > --
> > 插旗，尽量赶在4月30日前发布
> 
> 脸疼不

给你用就不错了，还叽叽歪歪，你没延过期？
