### ISSUE TITLE
自动统计文件夹体积相关问题

### ISSUE THREAD

**Issue by yansheng836** [liupan1890/aliyunpan#615]
## 1.文件夹体积统计

安装的是最新版，默认已经设置文件夹体积统计功能，但是好像没有具体显示（不知道是不是文件比较多的原因，现在应该总的是2T左右），想了解下这个统计策略是怎么样的？实时统计，还是会将统计结果进行保存，当有变动时进行更新？

![image](https://user-images.githubusercontent.com/45334066/161433875-08fdbcd6-bf88-4805-b120-5ee941cc03c1.png)
![image](https://user-images.githubusercontent.com/45334066/161433978-ff778622-49fb-4900-8999-a4c9f5437e81.png)

## 2.进入文件夹，加载文件内容很慢

虽然文件夹中内容不多，容量也不大，但是进来回加载很长时间，不知道是什么原因？（不知道是否是受问题1影响？）

![image](https://user-images.githubusercontent.com/45334066/161433889-50cb82ab-4c44-4fdf-ab2a-707db1c95ab7.png)

**Comment by liupan1890** [comment]
你好

截图是v2.9.24 (9月24发布的)最新版是v2.12.5

在v2.9.24发布时，阿里云盘当时并不支持文件夹大小，所以是通过遍历文件夹内文件后统计文件大小这种方式实现的
会缓存（72H），一般是在启动后第一次登陆后（包括启动后自动登录），会延时执行一遍统计文件夹大小，跟网盘体积无关，跟文件和文件夹数量有关，第一次统计时会很占性能（每个文件夹都需要执行一遍）

最近阿里云盘收紧了访问频次限制，此时，会遇到你截图中一直在加载中的问题（因为1秒就让访问十几次，如果正在统计文件夹体积，则会导致截图中加载文件的请求被拒绝访问，会自动重试，最终表现为加载很慢）

一路小版本号，更新到v2.12.5时，已经对统计文件夹体积功能做了很多优化，也可以自主设置缓存有效时长，
统计文件夹体积功能会比v2.9表现好特别多

--

最后，阿里云盘近期已经提供了官方的 文件夹体积  接口，理论上应该去调用此接口获取文件夹体积了

**Comment by yansheng836** [comment]
感谢解惑，我还以为release里面是最新版，找到v2.12.5了，已体验该功能，确实体验提高很多，感谢。:rose:
