### ISSUE TITLE
万一小白羊哪天不能用了，大佬简单说一下原理，我自己该如何用mpv等播放器实现变下边播

### ISSUE THREAD

**Issue by luxiyourbro** [liupan1890/aliyunpan#616]
比如哪天，小白羊不能用了，阿里也没有限制速度，可以正常下载，我该怎么像现在这样边下边播？

比如我需要会哪些技能？

**Comment by Sunovn** [comment]
感觉是读取下载链接，然后用MPV或者POT都能在线看

**Comment by yuankeyuan** [comment]
我没直接试过，我云一下：
1.提取视频链接（下载直链）
2.播放器里输入视频地址，即可在线观看。
我在potplayer播放器里可以直接打开和彩云网盘里的视频，只要找到视频下载地址，我只需要提取出下载地址，就像百度网盘提取直链一样。
我挺希望小白羊能加上提取直链这个功能的。

**Comment by liupan1890** [comment]
播放原始文件原理：
1.读取文件的下载地址（下载链接）（这个是阿里云盘的api https://api.aliyundrive.com/v2/file/get_download_url）
2.使用cmd命令运行mpv `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`

其它播放器同理，看一下播放器的参数列表，使用cmd运行

注：
1.使用网页版登录阿里云盘后，get_download_url需要加referrer才能访问
 `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`
2.使用APP登陆后，get_download_url不需要加referrer
 `mpv.exe "get_download_url"`

播放转码文件原理
1.读取文件的下载地址（下载链接）（这个是阿里云盘的api https://api.aliyundrive.com/v2/file/get_video_preview_play_info）
2.使用cmd命令运行mpv `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`

--

>我挺希望小白羊能加上提取直链这个功能的

在v2.12里，针对视频文件，右键-查看详情（视频雪碧图）页面，有复制下载链接的按钮
在v3里会给其他类型文件增加复制下载链接的按钮的

**Comment by luxiyourbro** [comment]
> 播放原始文件原理： 1.读取文件的下载地址（下载链接）（这个是阿里云盘的api [https://api.aliyundrive.com/v2/file/get_download_url）](https://api.aliyundrive.com/v2/file/get_download_url%EF%BC%89) 2.使用cmd命令运行mpv `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`
>

通过API读取下载链接，这个有没有什么详细的文档可以学习，或者作者简单再介绍一下，搜了一下，还要什么宝塔面板Linux环境，解码 RefreshToken ，搞不太懂。如果可以的话请简单介绍一下怎么实现，如果难度太大或没时间请直接忽略。

**Comment by yuankeyuan** [comment]
> > 播放原始文件原理： 1.读取文件的下载地址（下载链接）（这个是阿里云盘的api [https://api.aliyundrive.com/v2/file/get_download_url）](https://api.aliyundrive.com/v2/file/get_download_url%EF%BC%89) 2.使用cmd命令运行mpv `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`
> 
> 通过API读取下载链接，这个有没有什么详细的文档可以学习，或者作者简单再介绍一下，搜了一下，还要什么宝塔面板Linux环境，解码 RefreshToken ，搞不太懂。如果可以的话请简单介绍一下怎么实现，如果难度太大或没时间请直接忽略。

我之前学过后端java的springboot，也玩过一周的python爬虫，略懂一点。
api就是后端springmvc提供的数据接口，你不需要知道它怎么写，你只需要找到该接口就行（浏览器中按F12慢慢找）
类似https://xxx/xxx/xxx/xxx 这样的就是接口，作者也告诉你了。【第一步：找接口】
简单说一下原理：直接向后端接口发送请求，一般情况下，接口就会响应数据给你（这里会把下载地址返回给你）。
如果没给数据的话，应该是做了一些反爬虫手段。常见的反爬虫手段：
1.检验UA（校验是否是一个正常的浏览器访问）
⭐2.检验cookie或者token（检验是否登录，大部分情况只看这个，重点）
3.是否有相关权限（有些功能需要开通会员）

> 一句话就是，他要什么，你就给什么。【第二步：发请求】

我这里直接访问get_download_url，没给下载地址，显示AccessTokenInvalid，说明请求头里要带上这个AccessToken。
实现的手段有很多，你熟悉哪个用哪个。
1.你可以用python爬虫的方式，爬取到下载地址，再调用mpv播放器即可。
2.使用前端框架（vue，react等等）发送get请求。

我前端只学过一个axios。vue我只学了两三天，所以我也帮不上什么忙。但我感觉整个流程挺简单的，会发请求就行。把服务器想要的装进请求头或者请求体中，然后发送get请求要数据。服务器不给你数据肯定是有原因的，它要啥你给啥，服务器最终就会给你数据。

想法很美满：其实我一直想做视频加密的功能，视频在本地加密然后上传到云端，保证了数据安全，同时又可以在线观看。
现实很骨干：我编程水平太烂，对视频的编解码我不知如何下手

**Comment by yuankeyuan** [comment]
> > 播放原始文件原理： 1.读取文件的下载地址（下载链接）（这个是阿里云盘的api [https://api.aliyundrive.com/v2/file/get_download_url）](https://api.aliyundrive.com/v2/file/get_download_url%EF%BC%89) 2.使用cmd命令运行mpv `mpv.exe --referrer=https://www.aliyundrive.com/ "get_download_url"`
> 
> 通过API读取下载链接，这个有没有什么详细的文档可以学习，或者作者简单再介绍一下，搜了一下，还要什么宝塔面板Linux环境，解码 RefreshToken ，搞不太懂。如果可以的话请简单介绍一下怎么实现，如果难度太大或没时间请直接忽略。

写出能用的功能倒是很简单，难点是写好看的界面。不说好看，写个能用的界面都已经难倒一大批人了，很多人只会用黑窗口cmd。我之前学的那个框架vue，axios好像是用node上跑的，每次启动需要：
1.在cmd黑窗口npm run
2.再打开浏览器，输入主页地址
麻烦的很，想写出鼠标双击就能执行的，就像小白羊这样的，至少需要好几年功力。

**Comment by yggww** [comment]
API直链下载也会被限速吗有没有人测速一下
