### ISSUE TITLE
网传第三方大量下载要被封号？

### ISSUE THREAD

**Issue by Dyxtl** [liupan1890/aliyunpan#617]

**Comment by jkqxl** [comment]
@liupan1890

那会影响上传吗，目前在设置中的 上传/下载 ，是一起设置的。
如果不影响上传，每次临时修改都会很麻烦

**Comment by liupan1890** [comment]
>那会影响上传吗

1.在设置里，设置为同时执行5个文件
此时，上传或者下载，都是，最多5个文件同时执行（注：在机械硬盘上，同时执行数有时会突破5个达到6-10个这样，是保存文件卡导致的BUG）

--

在3月31日，我测试的，设置为60文件同时执行,仅仅下载了800多个大文件，就受限当天不能下载了（第二天自动恢复了）
在3月31日，我测试的，设置为3文件同时执行,下载了900GB大文件，没有被限制

--

今天我测试的，设置为60文件同时执行，上传1万个小文件后，没有被限制
今天我测试的，设置为60文件同时执行，下载大量大文件后，没有被限制

所以当前官方具体是怎么样的配额，我也不清楚，可能又放宽了。
保险起见就是
下载时设置为同时执行3个文件（可以满速下载了）
上传时随意

**Comment by prodcd** [comment]
估计主要问题是“大量下载”，而不是“第三方”。

**Comment by AhmadHomnYoua** [comment]
> 

一万个小文件啊🤣，感觉如果可以这么坚持下去，百度也会有着急的时候，要不太安逸了

**Comment by jkqxl** [comment]
@liupan1890

如果以后的 上传， 继续不受限制，那希望v3版的小白杨可以改成分开设置，省的有时候大容量文件上传时还得修改

**Comment by GitCourser** [comment]
> @liupan1890
> 
> 如果以后的 上传， 继续不受限制，那希望v3版的小白杨可以改成分开设置，省的有时候大容量文件上传时还得修改

支持这个建议, 希望新版上传下载分开设置

**Comment by liupan1890** [comment]
收到，会分开的
