### ISSUE TITLE
有源码编译启动教程吗

### ISSUE THREAD

**Issue by iamxvbaba** [liupan1890/aliyunpan#62]
有源码编译启动教程吗

**Comment by iamxvbaba** [comment]
(⊙o⊙)？ 我看到了，是单独启动了go程序，我以为是类似hover那样的。

**Comment by liupan1890** [comment]
1.aliserver 源码需要你按照正常的golang教程，配置环境，编译出正确的系统版本就好了
2.alxby 源码需要你按照正常的flutter教程，配置环境，编译出正确的系统版本就好了
3.最后按照小白羊的目录架构正确的复制文件到正确的位置就好了


1.https://www.runoob.com/go/go-environment.html
2.https://flutter.cn/docs/get-started/install
3.下载对应系统的最新版v1.6.21的压缩包，根据压缩包里每个文件的位置，自己复制就好了

**Comment by iamxvbaba** [comment]
> 1.aliserver 源码需要你按照正常的golang教程，配置环境，编译出正确的系统版本就好了
> 2.alxby 源码需要你按照正常的flutter教程，配置环境，编译出正确的系统版本就好了
> 3.最后按照小白羊的目录架构正确的复制文件到正确的位置就好了
> 
> 1.https://www.runoob.com/go/go-environment.html
> 2.https://flutter.cn/docs/get-started/install
> 3.下载对应系统的最新版v1.6.21的压缩包，根据压缩包里每个文件的位置，自己复制就好了

感谢。
