### ISSUE TITLE
软件能不能显示aria2推送过来的任务和速度?

### ISSUE THREAD

**Issue by lwj528** [liupan1890/aliyunpan#620]
小白杨aria2很稳定,,我经常用别的脚本推送过来aria2下载(如下载百度网盘),能否让软件显示 速度 和任务

**Comment by liupan1890** [comment]
你好

并不支持显示其他程序的推送任务，因为这个本身和小白羊并没有关系啊

>小白羊aria2很稳定

这个我没想到，小白羊就是使用的aria2官方的1.35版本，所以并不存在比其他版本稳定的理由。
你可以复制一份小白羊的aria2c.exe文件，然后配合一些aria2UI去使用，这样就可以看到全部的下载任务了

**Comment by ocean521** [comment]
但是为什么小白羊的下载任务，在其他aria2UI里看不见呢，设置的问题么？
