### ISSUE TITLE
小白虚心求问

### ISSUE THREAD

**Issue by zxc3974** [liupan1890/aliyunpan#621]
开发大大您好，我观察到在线看视频的时候小白羊会将该视频全部缓存，不知这些缓存是写入了硬盘写入了内存还是去了哪里？非计算机专业小白求问

**Comment by jkqxl** [comment]
设置中，高级，不是有缓存路径吗

**Comment by liupan1890** [comment]
在线看视频，分为2种情况

1.使用内置的MPV播放器
mpv播放器默认缓存应该是缓存到内存里，因为我并没有去设置mpv的缓存路径。我也没仔细去看mpv官网的文档

2.使用其他播放器
这个需要看播放器自己的设置。
比如使用的Potplayer播放器，Potplayer默认是把文件缓存到临时文件夹里(一般是C:\Users\yonghu\AppData\Local\Temp),并且可以在Potplayer的设置里，修改此路径（配置-存档-临时存储）
如果是自定义的其他播放器，需要问这个播放器，我也不知道，不过一般都是临时文件夹（因为此文件夹内的文件，是可以由系统自动清理的）


--

如果是想通过缓存的文件去找回视频，这个一般不太可行。因为有的播放软件并不是完整的缓存整个文件，而是缓存播放的数据，比如你没播放完，那就只下载了一部分。

如果是想清理缓存，这个一般不需要。因为重启电脑后，一般都会被系统自动的清理(临时文件夹下的文件会被系统合理的自动清理)

--

>设置中，高级，不是有缓存路径吗

这里缓存的是
1.一些图片的缩略图（浏览器缓存，无法打开）
2.上传/下载的任务数据
3.文件夹大小缓存数据
4.一些其他的electron程序运行中产生的缓存文件

**Comment by luxiyourbro** [comment]
MPV是缓存在内存，因为我观察任务管理器内存占用，关闭MPV，内存会释放

**Comment by yuankeyuan** [comment]
> 开发大大您好，我观察到在线看视频的时候小白羊会将该视频全部缓存，不知这些缓存是写入了硬盘写入了内存还是去了哪里？非计算机专业小白求问

在线看视频使用mpv播放器比较好，直接从内存里读写，不经过硬盘。potplayer播放器就相当于边下载到磁盘再边观看了。
- 现在内存够大了，网速也够快了，能用内存就用内存。
- 而且通过观察任务管理器，我发现mpv播放器的缓存机制是，如果你在线观看2G的视频，mpv不会一次性把2G读到内存中（即使你网速很快），而是从你当前观看的地方先缓存10分钟左右的视频，你看一点，它再加载一点，看过的地方，mpv会自动把内存中的缓存清了，所以内存的占用一般也就200M-300M，这个机制挺不错的。

**Comment by Sunovn** [comment]
> 在线看视频使用mpv播放器比较好，直接从内存里读写，不经过硬盘。potplayer播放器就相当于边下载到磁盘再边观看了。
> 
> * 现在内存够大了，网速也够快了，能用内存就用内存。
> * 而且通过观察任务管理器，我发现mpv播放器的缓存机制是，如果你在线观看2G的视频，mpv不会一次性把2G读到内存中（即使你网速很快），而是从你当前观看的地方先缓存10分钟左右的视频，你看一点，它再加载一点，看过的地方，mpv会自动把内存中的缓存清了，所以内存的占用一般也就200M-300M，这个机制挺不错的。

那怎么让pot也使用这样的机制，MPV的界面不如Pot，所以之前一直用Pot
