### ISSUE TITLE
没看懂为啥要 换成web套壳，dart不好吗

### ISSUE THREAD

**Issue by icetech233** [liupan1890/aliyunpan#622]
没看懂为啥要 换成web套壳，dart不好吗

**Comment by liupan1890** [comment]
呃，这点就说起来搞笑了

使用dart开发的第一版，一个月左右吧，win10自带杀毒软件报毒

之前也开发过很多客户端(C++ 的  golang的  C#的)

我的经验是，只要开发便携版软件(没有安装包，没有安装的步骤，没有卸载的步骤)
百分百会被报毒的，只是时间早晚和概率高低的事

大部分时候是，在第一台电脑上不报毒，在另外一台电脑上报毒，这两台电脑没有任何区别（系统版本+杀软版本完全一致）
总之就是，随机的报毒，绕不过，解决不了这个问题

这一点你先不要去纠结小白羊是否是真的病毒，你先假设小白羊是无辜的好吧

怎么才能让小白羊百分百不报毒呢？
开发过PC软件的人都知道，花钱，买证书，对软件签名。就好了。很简单
但是，我没钱

那怎么办呢？哦，用electron好了

你说这个理由搞笑不搞笑？

优点：flutter开发后只有10MB
win10报毒

优点：flutter开发后多平台可以用
win10报毒

优点：flutter运行效率比js高
win10报毒

优点千千万，win10报毒，不能运行，我没钱能怎么办呢

**Comment by Borber** [comment]
不好😎

**Comment by jkqxl** [comment]
确实

**Comment by AhmadHomnYoua** [comment]
> 呃，这点就说起来搞笑了
> 
> 使用dart开发的第一版，一个月左右吧，win10自带杀毒软件报毒
> 
> 之前也开发过很多客户端(C++ 的 golang的 C#的)
> 
> 我的经验是，只要开发便携版软件(没有安装包，没有安装的步骤，没有卸载的步骤) 百分百会被报毒的，只是时间早晚和概率高低的事
> 
> 大部分时候是，在第一台电脑上不报毒，在另外一台电脑上报毒，这两台电脑没有任何区别（系统版本+杀软版本完全一致） 总之就是，随机的报毒，绕不过，解决不了这个问题
> 
> 这一点你先不要去纠结小白羊是否是真的病毒，你先假设小白羊是无辜的好吧
> 
> 怎么才能让小白羊百分百不报毒呢？ 开发过PC软件的人都知道，花钱，买证书，对软件签名。就好了。很简单 但是，我没钱
> 
> 那怎么办呢？哦，用electron好了
> 
> 你说这个理由搞笑不搞笑？
> 
> 优点：flutter开发后只有10MB win10报毒
> 
> 优点：flutter开发后多平台可以用 win10报毒
> 
> 优点：flutter运行效率比js高 win10报毒
> 
> 优点千千万，win10报毒，不能运行，我没钱能怎么办呢

很实在，挺好，无私的为大伙做出来这个软件就很厉害了，做到哪里是哪里，感谢。

**Comment by gexiaosen** [comment]
购买签名多少钱 可否内置一个众筹渠道，集资购买签名

**Comment by Borber** [comment]
> 购买签名多少钱 可否内置一个众筹渠道，集资购买签名

没这个必要啊, 为啥非要用 flutter?

**Comment by liupan1890** [comment]
签名的话，

windows:

分为很多品牌和规格，品牌不一样，价格不一样，能提供的信任度也不一样
标准的版本价格一般在5000/年
高级的版本价格一般在8000/年


mac:
Apple Developer Program 会员,99美元/年

--

集资购买签名的话

没有必要，只要代码逻辑正确，加上优化到位，以当前的电脑性能，很难遇到“性能卡顿”。
UI的美观角度，跟编程语言关系不大了

**Comment by icetech233** [comment]
报不报毒  又无所谓，我在的公司花钱买证书，是为了白名单，没有证书也能用啊，nsis 做安装包也可以

**Comment by icetech233** [comment]
公司隔壁项目就是 flutter 和go 没有遇到报毒，而且win10 杀毒可以关闭的

**Comment by icetech233** [comment]
我确实有C#  wpf 开发的项目，但是我看不懂 api里面的一堆 key，哪里来的

**Comment by motto123** [comment]
辛苦作者了，太难了
