### ISSUE TITLE
能否上传一下v2.12.05的代码呢，我看很多功能都是v2.9.24没有的，尤其是自定义播放器。

### ISSUE THREAD

**Issue by zhengge791254521** [liupan1890/aliyunpan#628]
如题，想要参考学习一下。我也在处理视频格式播放问题

**Comment by liupan1890** [comment]
会在v3发布时，同步v3的源码，到时候以后看最新版的吧

--

注：视频最主要的是使用app登录获得的token，这样获取的下载地址没有referer的限制
除此之外v2.9.24和v2.12.x 在线播放就没区别了
v2.9.24 网页登陆，需要referer，仅极少数播放软件支持(mpv ,vlc)
v2.12.x app登录,不需要referer，很多播放软件支持

**Comment by zhengge791254521** [comment]
好的，多谢大佬。另外v3发布时候可以的话麻烦多一点注释。之前看v2.9.24的时候，学到很多。拜谢大佬
