### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by Lyh9812** [liupan1890/aliyunpan#63]
win10系统，打开exe文件后提示严重错误，无法连接到后台进程，退出程序后再次打开还是一样的提示。
![image](https://user-images.githubusercontent.com/76611116/123510398-cd7ade80-d6ad-11eb-83de-0cb38d5d79b9.png)

**Comment by liupan1890** [comment]
https://github.com/liupan1890/aliyunpan/issues/51

**Comment by liupan1890** [comment]
你这样操作
1.注意一下任务管理器里是否有阿里云盘小白羊.exe进程，有的话先强制结束掉
2:删除掉data\app.lock这个文件，可能是因为没有读取这个文件的权限导致跳过启动
3.双击阿里云盘小白羊版.exe
4.双击data\aliserver.exe

3和4的操作不要间隔太久（别超过10秒）

就是自动调用aliserver.exe没有成功，所以需要你手动双击aliserver.exe

这样肯定就会有debug.log了。操作完看你能否正常使用。

如果能正常使用，那就彻底退出，测试只双击阿里云盘小白羊版.exe 能否正常使用

1.可能第一次运行被阻止
2.可能时程序BUG识别aliserver.exe的路径出错没找到正确的路径调用启动。我稍后会检查一下代码看怎样确保能够正确的识别出aliserver.exe的位置
