### ISSUE TITLE
反馈错误

### ISSUE THREAD

**Issue by ydhh** [liupan1890/aliyunpan#633]
1.这两天有时无法打开文件夹，重启后又可以
2.今天删除的文件不生效，必须去官方网页版删除【我没有安装官方客户端没有测试】

**Comment by hongtucao8384** [comment]
> 1.这两天有时无法打开文件夹，重启后又可以 2.今天删除的文件不生效，必须去官方网页版删除【我没有安装官方客户端没有测试】

对，试了，也是这样？

**Comment by Sherman-Liu** [comment]
可以复现，目前确实出现了同样问题。

**Comment by liupan1890** [comment]
已发布v2.12.14修正版本
