### ISSUE TITLE
不能删除，移动，改名了

### ISSUE THREAD

**Issue by jzx765** [liupan1890/aliyunpan#634]
只用了这几个功能，上传下载暂时没问题，其他还有没有啥问题不太清楚

**Comment by hongtucao8384** [comment]
> 只用了这几个功能，上传下载暂时没问题，其他还有没有啥问题不太清楚

对，也遇到这样情况.是否是官方限制？

**Comment by ifree8** [comment]
估计是官方开始下手了，我也是刚刚遇到这个情况，无法删除，不能改名，其他还未测试

**Comment by hummersyk** [comment]
估计是接口什么的有改动了？

**Comment by linsuperr** [comment]
新建文件夹还可以，但是删除复制移动不能用了

**Comment by Sakura1338** [comment]
一样，目前暂时下了官方端来用

**Comment by liupan1890** [comment]
呃，大家不要多想，仅仅是官网升级了。。。已发布v2.12.14修正版本
