### ISSUE TITLE
假如以后小白羊不能用了，那么如何用potplayer播放网盘的原始文件呢？

### ISSUE THREAD

**Issue by twl6592** [liupan1890/aliyunpan#636]
是不是要找到视频的下载直链？那么如何获取直链呢？
求用potplayer在线播放原始文件的教程

**Comment by TEL3345678** [comment]
用CloudDrive，可以让阿里云盘挂载到本地磁盘，就可以看了。

**Comment by DifferentSparkler** [comment]
> 用CloudDrive，可以让阿里云盘挂载到本地磁盘，就可以看了。

但是有个严重的问题CloudDrive很占用带宽

**Comment by yuankeyuan** [comment]
> 是不是要找到视频的下载直链？那么如何获取直链呢？ 求用potplayer在线播放原始文件的教程

是的，只需要寻找到视频的下载直链，在potplayer里ctrl+u输入地址就行。
其实这是ffmpeg的功能，如果你下载了ffmpeg的话，你直接ffplay "视频直链地址" 也可以在线观看视频，直接网络-内存，不经过磁盘。
所以难点在于，怎么获取视频下载直链。
这样单个单个看还是挺麻烦的，用clouddrive挂载到本地磁盘比较方便。
如果阿里权限做的比较好的话，比如先判断一下是否会员，不是会员最多给720p的链接，这样非会员是看不了原始文件。

**Comment by twl6592** [comment]
> 

对欧，这是个简单的办法

**Comment by twl6592** [comment]
> 用CloudDrive，可以让阿里云盘挂载到本地磁盘，就可以看了。
对欧，这是个简单的办法

**Comment by twl6592** [comment]
> > 是不是要找到视频的下载直链？那么如何获取直链呢？ 求用potplayer在线播放原始文件的教程
> 
> 是的，只需要寻找到视频的下载直链，在potplayer里ctrl+u输入地址就行。 其实这是ffmpeg的功能，如果你下载了ffmpeg的话，你直接ffplay "视频直链地址" 也可以在线观看视频，直接网络-内存，不经过磁盘。 所以难点在于，怎么获取视频下载直链。 这样单个单个看还是挺麻烦的，用clouddrive挂载到本地磁盘比较方便。 如果阿里权限做的比较好的话，比如先判断一下是否会员，不是会员最多给720p的链接，这样非会员是看不了原始文件。

感谢。
确实挂载简单。不过小白羊更新了，暂时用不上了
