### ISSUE TITLE
现在所有操作都提这个错误

### ISSUE THREAD

**Issue by peterdocter** [liupan1890/aliyunpan#638]
14 16:03:26 : warning : HttpError3 400 HttpMediaTypeNotSupportedException Request failed with status code 400
14 15:59:27 : warning : HttpError3 400 HttpMediaTypeNotSupportedException Request failed with status code 400

**Comment by jasgdja876** [comment]
说好的允许第三方存在呐？al的嘴，骗人的鬼

**Comment by liupan1890** [comment]
呃，大家不要多想，仅仅是官网升级了。。。已发布v2.12.14修正版本
