### ISSUE TITLE
聚合搜索框

### ISSUE THREAD

**Issue by QAQ5555** [liupan1890/aliyunpan#64]
聚合搜索框偶发无法删除文字

**Comment by liupan1890** [comment]
感谢反馈，这是一个已知的BUG，偶发无法删除文字，偶发输入汉字会自动输入拼音（hanzi汉字），偶发无法切换输入法

这都是Flutter本身的已知BUG，是因为当前Flutter对桌面端支持并不完善导致的。暂无解决方案
