### ISSUE TITLE
帮助使用文档

### ISSUE THREAD

**Issue by DoraemonBBX** [liupan1890/aliyunpan#640]
突然发现帮助使用文档不见了

**Comment by liupan1890** [comment]
如果你是说点击帮助文档后，显示语雀的登录界面，看不到帮助文档（登陆后可见）

是因为昨晚修改了帮助文档后，语雀在审核。

很早以前不登录语雀即可看到公开的文档，自2-3月开始语雀开始更新为部分分享文档可见，部分文档登录后才可见

会在v3里切换为国外的文档网站的，这样就不需要登录了

**Comment by mandarine250** [comment]
ooooo  还没有审核通过啊原来（一直登录的）

谢谢作者大大的解答

**Comment by DoraemonBBX** [comment]
> 如果你是说点击帮助文档后，显示语雀的登录界面，看不到帮助文档（登陆后可见）
> 
> 是因为昨晚修改了帮助文档后，语雀在审核。
> 
> 很早以前不登录语雀即可看到公开的文档，自2-3月开始语雀开始更新为部分分享文档可见，部分文档登录后才可见
> 
> 会在v3里切换为国外的文档网站的，这样就不需要登录了

ooooo 还没有审核通过啊原来（一直登录的）

谢谢作者大大的解答

**Comment by DoraemonBBX** [comment]
> 如果你是说点击帮助文档后，显示语雀的登录界面，看不到帮助文档（登陆后可见）
> 
> 是因为昨晚修改了帮助文档后，语雀在审核。
> 
> 很早以前不登录语雀即可看到公开的文档，自2-3月开始语雀开始更新为部分分享文档可见，部分文档登录后才可见
> 
> 会在v3里切换为国外的文档网站的，这样就不需要登录了

帮助文档消失了 是不是忘了更换链接啊大佬
![image](https://user-images.githubusercontent.com/81815312/164960343-c4e28535-9cdb-49e7-b631-b802ef1b7fe0.png)

**Comment by liupan1890** [comment]
帮助文档已经因为被举报，被语雀删除了，以后会在github的wiki里重新制作一份帮助文档
