### ISSUE TITLE
投稿阿里云盘分享网站-万人迷吧

### ISSUE THREAD

**Issue by feichangmiren** [liupan1890/aliyunpan#641]
在分享链接搜索那里看到的可以投稿网站，我投稿一个搜索网站，挺好用的，希望能收录！
![image](https://user-images.githubusercontent.com/92327137/163671399-aceb1923-dcfd-422b-a968-419e2fd678da.png)
网站名称：万人迷吧
网站地址：wanrenmi8.com
网站简介：阿里云盘资源搜索引擎、阿里云盘论坛导航、阿里云盘资源分享、一些其他软件分享网站导航。
如图：
![image](https://user-images.githubusercontent.com/92327137/163671363-5396c140-80f6-419d-949a-38362fb8f65f.png)

**Comment by leopardciaw** [comment]
这个有意义。

**Comment by liupan1890** [comment]
已收录

注:因为gitee近期调整了访问限制，旧版(v2.12.14之前的版本)已无法获取最新数据，所以不会显示收录后的。但新版及以后会正确更新显示

**Comment by snow212-cn** [comment]
这个网站现在只剩第一个up云搜能搜，其它都点不动了，垃圾网站

**Comment by heihei1634** [comment]
谢谢了！有事和我联系啊！

**Comment by heihei1634** [comment]
谢谢了！有事和我联系啊！
