### ISSUE TITLE
请教一下，关于“导入分享 ”没反应，是不是我哪里弄错了？

### ISSUE THREAD

**Issue by pkids** [liupan1890/aliyunpan#643]
小白羊界面中有：新建、上传、导入分享 按钮。

我点击”导入分享“，弹出了个对话框，自动识别我刚才复制的阿里云分享链接，选择了文件和导入位置后就等待，但是等待了一天一夜，阿里云盘里对应的位置还是没有这部电影，去”阿里云盘小白羊客户端--分享--导入过的分享“里，复制了这个链接，在浏览器里一键转存了。

是不是我对小白羊的”导入分享“存在什么误解啊？本来不想占用资源的，用了右上角的搜索，搜索了一下 导入分享 ，没看到同类型帖子，所以只好发个帖子请教下了。

谢谢啦！

**Comment by ZHQSM** [comment]
用最新版的   原来的不行了

**Comment by pkids** [comment]
是的，用的正是2.12.14版

**Comment by liupan1890** [comment]
![shareok](https://user-images.githubusercontent.com/67817756/163800368-aa1b4303-7166-4677-8241-450935fb4166.gif)


我第一反应是有BUG，但我测试了一下，勾选文件后点击保存（直接保存勾选的，按路径保存勾选的，一件保存全部）都是正常的，你再试一下(注意必须是2.12.14)

**Comment by pkids** [comment]
感谢感谢，我太菜了，我没有勾选前面的打勾框框。。。。所以没保存下来，现在知道我哪里出错了！
