### ISSUE TITLE
关于调整字幕问题

### ISSUE THREAD

**Issue by chenf2333** [liupan1890/aliyunpan#645]
请问下如何更改字幕速度

**Comment by liupan1890** [comment]
默认的MPV播放器不支持调整字幕的时间轴，请使用自定义播放器，选择支持的播放器就好了

**Comment by chenf2333** [comment]
> 默认的MPV播放器不支持调整字幕的时间轴，请使用自定义播放器，选择支持的播放器就好了

好的，谢谢你
