### ISSUE TITLE
上传下载的地方 应该修改为60 怎么开启啊是

### ISSUE THREAD

**Issue by haoxiangta** [liupan1890/aliyunpan#650]
上传下载的地方 应该修改为60 怎么开启啊是 看到 那地方 点开之后 1-5的选项也改不了 不知道咋改

**Comment by liupan1890** [comment]
因为近期之前阿里云盘官方开始限制访问频次（开60文件同时下载，可能会触发官方限制，禁止你账号当日下载功能----禁止多日下载功能），所以当前调整为1-5

只是过渡

会在v3里恢复更高的同时下载数量的
