### ISSUE TITLE
可以开发个查询重复文件的功能吗?

### ISSUE THREAD

**Issue by xlenco** [liupan1890/aliyunpan#651]

**Comment by Sunovn** [comment]
官方有，你在手机上看看

**Comment by liupan1890** [comment]
1.官方APP现在就有这个功能了

2.再v3里也有这个功能了

**Comment by fohuhu** [comment]
ios版没看到这个功能啊

> 1.官方APP现在就有这个功能了
> 
> 2.再v3里也有这个功能了

**Comment by liupan1890** [comment]
v3.05.23现在已经提供了重复文件扫描功能，先扫描，然后勾选，删除
