### ISSUE TITLE
请求支持保存百度云盘的分享链接

### ISSUE THREAD

**Issue by gobiking** [liupan1890/aliyunpan#66]

**Comment by liupan1890** [comment]
这个从技术上暂无法实现

1.百度提供了文件的MD5值
2.115网盘提供了文件的SHA1值
3.阿里云盘需要文件的SHA1值

所以，可以通过115网盘的秒传链接，或者115网盘的分享链接，尝试秒传到阿里云盘
无法通过百度分享链接的文件MD5值，去尝试秒传到阿里云盘

SHA1值，必须本地有这个完整的文件，才能计算出来。所以也就是，只能先从百度网盘下载这个文件到本地电脑上，再计算出SHA1值，最后尝试秒传到阿里云盘

百度的限制是非VIP不让高速下载，所以无法从百度网盘下载这个文件到本地电脑上---（没有百度网盘的VIP账号）

总结：技术上无法实现此功能
