### ISSUE TITLE
[Bug] aria2c写入文件失败

### ISSUE THREAD

**Issue by loongcheung** [liupan1890/aliyunpan#663]
version: v2.12.14

使用Aria2下载，视频文件会报“aria2c写入文件失败”错误，测试图片或者其他小文件都正常

<img width="890" alt="image" src="https://user-images.githubusercontent.com/25630765/166098138-fb156f55-5932-4d1f-a050-a3d9166dc157.png">

**Comment by liupan1890** [comment]
理论上应该只有2种情况：1。全部文件可以下载  2.全部文件都不能下载

遇到这种部分文件不能下载的。
1.可能是目标分区已满（在我的电脑看一下你下载保存的位置，是否分区已经被沾满了，剩余硬盘空间不足4.8GB）
2.可能是这一个文件（或者这个文件所在的文件夹）文件名有特殊字符导致的无法创建(可以尝试把这个文件复制到网盘根目录，修改这个文件的文件名为test.mp4，然后下载。看能否正常下载)
3.可能是目标分区是FAT32分区（常见于U盘，FAT32分区的U盘，最大只能创建4GB以内的文件，超过4GB需要使用NTFS分区）（在下载保存的分区上右键属性，能看到文件系统：FAT32）
4.可能是你的账号被设置了磁盘配额（windows系统，可以对指定账号设置磁盘配额，就是你的账号在某个分区，总共可以使用多少GB，超过配额后即使分区有剩余空间，你也无法继续写入，别人才可以写入）

--

总之，感觉可能是1和2的情况。试一下？

**Comment by loongcheung** [comment]
目前看是我的机器问题，issue关了
