### ISSUE TITLE
这个红色图标是什么意思？

### ISSUE THREAD

**Issue by Doddddd** [liupan1890/aliyunpan#666]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/88972478/166621407-9be8ccd4-9b8f-4ce4-88ed-65dec202e067.png">

**Comment by licsber** [comment]
被屏蔽了 违规文件

**Comment by Doddddd** [comment]
> 被屏蔽了 违规文件
可是下载和在线观看（在小白羊和网页版）都正常

**Comment by Doddddd** [comment]
> 被屏蔽了 违规文件

可是下载和在线观看（在小白羊和网页版）都正常

**Comment by jjjyyyllll** [comment]
> > 被屏蔽了 违规文件
> 
> 可是下载和在线观看（在小白羊和网页版）都正常

不能分享

**Comment by Doddddd** [comment]
> > > 被屏蔽了 违规文件
> > 
> > 可是下载和在线观看（在小白羊和网页版）都正常
> 
> 不能分享

懂了
