### ISSUE TITLE
Mac版本问题

### ISSUE THREAD

**Issue by williamleecn** [liupan1890/aliyunpan#67]
### 1 代码没有支持macos, 
1.1 源码没有macos目录及相关文件,要调用flutter create --platforms=macos,并修改
macos/Runner/DebugProfile.entitlements和macos/Runner/Release.entitlements,并要加上
`<key>com.apple.security.network.client</key>
    <true/>
`
不然无连接aliserver

1.2 lib/api/GoServer.dart的runServer没有调用,而且判断Platform.isWindows,说明只能运行在window下,缺失macos代码

## 2 Bug
2.1 lib/pagepan/MoveDialog.dart 159 行
应该写成
`
itemHeight: 32<=kMinInteractiveDimension?kMinInteractiveDimension:32, 
`
或
`itemHeight: kMinInteractiveDimension, `
不建议为了一个项目修改公共组件

2.2 aliserver/download/downmanage.go 243行
连接断开时,Aria2Rpc=nil 报错

**Comment by liupan1890** [comment]
1.mac代码，我去翻翻，一会贴上来
MainFlutterWindow.swift
``````
import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {


  override func awakeFromNib() {

    let ali=Bundle.main.bundlePath+"/Contents/Resources/aliserver"
    if (access(ali,0)<0){
      let alert=NSAlert()
      alert.messageText="找不到aliserver"
      alert.runModal()
    }else{
      let aliserver=Process()
      aliserver.launchPath=ali
      aliserver.launch()
    }

    let flutterViewController = FlutterViewController.init()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    super.awakeFromNib()
  }
}

``````
2.kMinInteractiveDimension 这样写没用，默认是48，不改编译通不过

3.	之后的版本我会加上判断
if Aria2Rpc != nil {
		Aria2Rpc.ForcePauseAll()
	}

**Comment by williamleecn** [comment]
### 3  dropfiles_window 0.0.2不支持null safety
但github上最新是0.1.2支持 null safety(pub.dev上还是0.0.2),需要切换到git

**Comment by liupan1890** [comment]
mac你直接去掉这个插件就可以，记得是main.dart里，删除掉相关的20行代码就行。mac用不到这个
