### ISSUE TITLE
希望可以加入违规文件扫描功能

### ISSUE THREAD

**Issue by xwpl** [liupan1890/aliyunpan#676]
云盘文件违规机制越来越严格，而且封禁了也没提示。常常要用了才发现文件已经被封禁，能不能出一个扫描云盘里已经被封禁文件的功能?

**Comment by hongtucao8384** [comment]
> 

关键是数据加密，不要被阿里云盘扫描。

**Comment by sailing178** [comment]
支持

**Comment by liupan1890** [comment]
v3里可以使用“扫描违规文件”功能了，先扫描，然后勾选，移动/删除
