### ISSUE TITLE
可否增加阿里云  总空间及显示使用空间状态功能

### ISSUE THREAD

**Issue by hqhbaby** [liupan1890/aliyunpan#678]
可否增加阿里云  总空间及显示使用空间状态功能

**Comment by Sunovn** [comment]
> 可否增加阿里云  总空间及显示使用空间状态功能

点击头像

**Comment by liupan1890** [comment]
在v3.05.23里已经支持了

![无标题](https://user-images.githubusercontent.com/67817756/169837096-864776ca-6ae6-4092-83b4-5ec47a47579a.jpg)

**Comment by hqhbaby** [comment]
在左边导行栏左边直接显示  更直观

liupan1890 ***@***.***> 於 2022年5月23日週一 下午10:03寫道：
