### ISSUE TITLE
[feature]: 是否可以加个一键复制列表所有文件下载链接的功能

### ISSUE THREAD

**Issue by loongcheung** [liupan1890/aliyunpan#679]
如题，谢谢

**Comment by liupan1890** [comment]
当前只可以 一个文件一个文件的复制 （在v3里统一支持在 文件--右键--更多--属性 页面，点击复制下载链接按钮）

但不支持批量的复制

1.阿里云盘的下载链接仅4小时有效
2.以后会支持批量选中文件后批量显示“属性”，会在这个批量属性页面提供批量复制按钮

**Comment by loongcheung** [comment]
明白了，谢谢，期待v3
