### ISSUE TITLE
115sha1

### ISSUE THREAD

**Issue by clarkance** [liupan1890/aliyunpan#68]
115转存不支持按目录导入，导致不同目录下相同文件名和扩展名的文件转存失败

**Comment by liupan1890** [comment]
鞥，115暂时无法做到按目录导入，
1是当前115秒传插件的格式无法保证统一，
2是可能有的人会手动拼接字符串导致最终统计文件路径时比较复杂，
3是阿里云盘当前的目录，必须要一个一个，一层一层的先创建好，之后才能开始导入文件，这个耗时可能会比较久，体验不太好

所以我就没有做按目录导入的功能

在下个版本会支持导入115分享链接，这样就可以按目录导入了（分享链接里面的目录）
