### ISSUE TITLE
能否增加便捷版，数据什么的直接保存在根目录

### ISSUE THREAD

**Issue by realcirno** [liupan1890/aliyunpan#680]
Win10 ×64

**Comment by Doddddd** [comment]
resources文件夹里新建文本文档，重命名为userdir.config，里面填数据路径

**Comment by realcirno** [comment]
> resources文件夹里新建文本文档，重命名为userdir.config，里面填数据路径

能否说一下怎么填么？小白用户

**Comment by Doddddd** [comment]
> > resources文件夹里新建文本文档，重命名为userdir.config，里面填数据路径
> 
> 能否说一下怎么填么？小白用户

![{5C369771-54AD-4275-8D8B-DBF4CE5312B7}.png](https://user-images.githubusercontent.com/88972478/168429061-a556f2b5-56ec-40c9-9a70-00d8d950e91c.png)

**Comment by realcirno** [comment]
好像没效果，建议作者能直接内置配置文件

**Comment by myfingerhurt** [comment]
Update:
After removing the tailing newline, it is working now

@realcirno 
@Doddddd 

Unfortunate it doesn't working, app refuses to start. Had to delete the `userdir.config` file

![image](https://user-images.githubusercontent.com/12622279/195098772-4ae35281-4ece-4e2b-90f6-8d9d6590c541.png)

![image](https://user-images.githubusercontent.com/12622279/195098328-ff191c7b-3a7d-47ea-954f-f653dec9aef6.png)
