### ISSUE TITLE
期待3.0更新

### ISSUE THREAD

**Issue by gexiaosen** [liupan1890/aliyunpan#687]
阿里自身的备份盘（还不是同步盘）做的一塌糊涂，希望大佬做的能够让人眼前一亮。什么时候能够更新呀

**Comment by liupan1890** [comment]
呃，不是我说，阿里官方的同步盘确实真的不太好。功能太少，不能指定文件夹，不能指定同步方向，不能指定备份周期。。。

我会试试看！

**Comment by gexiaosen** [comment]
> 呃，不是我说，阿里官方的同步盘确实真的不太好。功能太少，不能指定文件夹，不能指定同步方向，不能指定备份周期。。。
> 
> 我会试试看！

现在还不是同步 只能本地到云端，不能云端到本地，并且备份是全量备份，同一个文档修改一下会增加一个新的文件，不是覆盖备份的
