### ISSUE TITLE
聚合搜索是文本精确匹配，似乎可以用正则匹配这类的

### ISSUE THREAD

**Issue by LuJiaWeiwei** [liupan1890/aliyunpan#69]
感觉目前的精确搜索还可以再改进一下

**Comment by LuJiaWeiwei** [comment]
例如用户将两个关键词用空格隔开，是希望这两个关键词中间可以隔任意长字符，而每个关键词都得连在一起出现

**Comment by liupan1890** [comment]
哦，当前搜索语法是 
空格 ------ or
加号 ------ and

搜索 `a b` 搜索包含a或者包含b
搜索 `a+b` 搜索包含a并且包含b
不关心顺序，只检测是否包含

**Comment by LuJiaWeiwei** [comment]
> 哦，当前搜索语法是
> 空格 ------ or
> 加号 ------ and
> 
> 搜索 `a b` 搜索包含a或者包含b
> 搜索 `a+b` 搜索包含a并且包含b
> 不关心顺序，只检测是否包含

哦哦，原来是这样，似乎可以在下一版里加点说明呢

**Comment by liupan1890** [comment]
嗯，收到！会加上
