### ISSUE TITLE
无法登陆 账号密码登陆不行 扫描也不行

### ISSUE THREAD

**Issue by kunpeng9** [liupan1890/aliyunpan#693]
![天若_20220524170232](https://user-images.githubusercontent.com/44609485/169993973-350f18a4-d617-4ba2-931e-082b4c849c6d.png)

![天若_20220524170356](https://user-images.githubusercontent.com/44609485/169994186-96aef109-77d5-4453-8005-7b17cf32facf.png)
验证码登陆还是不行

**Comment by liupan1890** [comment]
抱歉，因为阿里云盘官网的版本升级导致旧版已经无法正常使用了，请使用新版 v2.12.14 或者 v3.05.23
