### ISSUE TITLE
希望新增文件的直接剪切复制黏贴

### ISSUE THREAD

**Issue by wf5599** [liupan1890/aliyunpan#698]
文件夹多的情况下移动文件到文件夹 找文件夹很麻烦 现在移动的时候后那个列表又不能搜索

**Comment by liupan1890** [comment]
可能我理解的不是很准确。你可以在全盘搜索，搜索出你想要移动的文件，然后批量勾选，拖放到左侧文件树里指定文件夹里

![sm](https://user-images.githubusercontent.com/67817756/170287977-da5cb503-2422-4fc6-927e-b21e0a69bb48.gif)

**Comment by wf5599** [comment]
好的 这样也行 谢谢 辛苦啦
