### ISSUE TITLE
请问大佬能否开发出安卓TV版？

### ISSUE THREAD

**Issue by pkids** [liupan1890/aliyunpan#70]
使用大佬开发的pc版小白羊阿里云盘非常惬意，觉得阿里云盘速度快但是空间小，平时倒腾一下电影挺不错的，反正看完就删，因为平时也逛留言板，好像听说这个小白羊阿里云盘是基于阿里云盘网页版的权限做出来的，想问下大佬如果等pc版功能都开发全了以后，有空的时候能否也弄个简单的安卓tv版出来，主要用来看电影的，相册和保险柜功能都可以不用加进去。

**Comment by pkids** [comment]
因为百度网盘这么多年了，前段时间说他们也出了TV版，忽然大家直呼真香，所以觉得如果小白羊也出个阿里云盘TV版，估计大家也会觉得香~

**Comment by liupan1890** [comment]
这个难度比较大，不是技术上有难度，是精力上

1.当前TV机顶盒的系统版本很多，从安卓4.2到安卓11都有（4.2，4.7，5，6，7，8，9，10），还有比较新的鸿蒙
2.当前TV机顶盒芯片版本很多，arm32,arm64v7,arm64v8,x86,x86_64,等

所以如果上TV，那么就需要我分别编译很多次，每一次版本升级都要编译十几次，也就是一整天的时间都在编译。复制文件。

你比如当前PC版支持windows和mac
每次版本升级，我都要这样做：
1.在win7上编译aliserver,编译alixby,复制aliserver到alixby对应位置，复制mpv到对应位置，复制aria2c.exe到对应位置，压缩打包
2.把所有源码复制到U盘，打开macos虚拟机，把所有代码复制到mac，编译aliserver,编译alixby,复制aliserver到alixby对应位置，复制mpv到对应位置，复制aria2c到对应位置，压缩打包，把压缩包复制到U盘
3.从U盘复制mac版压缩包，上传win版，上传mac版

整体操作下来就2小时过去了，一天我可能只有2-3小时能碰电脑。

如果上安卓tv，估计一整天都在打包。
所以说了，不是技术上的困难，是精力上

另外一点，tv和电脑操作习惯不一样，所以界面上也要按照tv去修改很多地方。所以实际上最终就要分开PC版和TV版的代码
那么以后每一次升级版本，都要同时修改两个版本的重复代码，

总之：没时间去做啦


另外，从实际上去理解，小白羊只是官方的DIY，只是为了操作更加方便。像安卓手机端，iphone手机端，TV端，都应该寄希望于官方去开发。对官方来讲，一个PC端就不知道有多少程序员在开发了。想安卓端是另外的一个团队，iphone端是另外一个团队，网页版也是另外一个团队。一个团队少说也有3-5人。全职开发，还都是有能力的大牛。

我一个人也就只能专注PC了

**Comment by pkids** [comment]
好的大佬，刚收到邮件提醒，看到回复得这么详尽，有点感动！谢谢您的聆听~以后会一直支持小白羊的~~

**Comment by keyboydg** [comment]
其实我也很期待
