### ISSUE TITLE
跪求从百度网盘导入功能！！！

### ISSUE THREAD

**Issue by YtcBB** [liupan1890/aliyunpan#702]
跪求从百度网盘导入功能！！！
跪求从百度网盘导入功能！！！
跪求从百度网盘导入功能！！！

**Comment by hongtucao8384** [comment]
> 跪求从百度网盘导入功能！！！ 跪求从百度网盘导入功能！！！ 跪求从百度网盘导入功能！！！
冲一个月会员，自己下载就行啦。

**Comment by liupan1890** [comment]
这个功能啊，他确实是有限制的，不是很简单

1.百度网盘法务部很厉害，对于调用百度网盘公开API的行为会主动发律师函
2.百度网盘导入，因为网盘数据数据不互通，也就是`先从百度网盘下载一个文件，然后上传到阿里云盘`这样的流程。自动化操作

但是因为百度网盘下载速度的问题：
非会员速度很慢，导入很慢，不实用，
会员呢就直接自己下载整个文件夹然后上传整个文件夹了，也并不需要这个导入功能

综上，不太具有开发的现实意义。一般推荐pdd购买一周的共享会员账号，自行下载和上传（因为上传时很多文件都可以秒传，所以主要问题还是下载）

**Comment by AXBNG** [comment]
你去把百度法务部搞定，然后贡献自己的超会账号
