### ISSUE TITLE
希望增加对夸克云盘的支持

### ISSUE THREAD

**Issue by fengguowudi** [liupan1890/aliyunpan#708]
毕竟都是阿里家的（
大佬这个需求可以把它排在最后，之后有时间再加上就好。（没时间就算了）
主要是目前夸克的官方客户端就是web套层浏览器上传还不稳定，太恶心了。

**Comment by ghost** [comment]
跟是不是一家的又没啥关系，作者哪有那精力同时搞两个......要不你试试掏赞助费让大佬给你私人定制个？hhh

**Comment by liupan1890** [comment]
抱歉啊，真的没有精力啊，v3(v2)是开源的，看看有其他人愿意做一个不

或者等我把v3做完善了以后再考虑其他平台吧
