### ISSUE TITLE
软件CPU占用较高

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/aliyunpan#71]
希望可以优化一下

**Comment by liupan1890** [comment]
占用高具体是多高？

比如我的机子是笔记本低频i5
1. 界面
正常情况下，在软件UI界面，所有页面不操作时（比如文件列表页面，没有快速滚动列表时），CPU占用应该在3%以下（0%-3%）
只有当有下载中的任务并且打开了下载中/上传中页面，此时因为每秒都要刷新下载速度/下载进度。CPU应该在5%左右

2.aliserver进程，一般CPU在无操作0%.有操作1%

3.aria2c.exe进程
有大量下载任务时，CPU在10%-15%，无下载或少量下载或总的下载速度<10MB/s时CPU一般在2%-5%

特殊情况
1.当有上传任务时，因为上传文件前需要计算sha1值，此时aliserver进程CPU一般是25%-50%
2.当勾选下载后校验sha1，aria2c.exe进程会在30%-40%

总结：大量满速下载时确实会占用较多CPU，但我对比官方PC端感觉还是比官方的占用少
但是如果没有操作/没有下载/没有上传 这时应该不占用CPU才对

备注：Flutter有BUG，我知道的是在部分windows上会出现不操作但CPU已知占用25%的情况（4核CPU25%，2核CPU50%）

既然提到了，应该是在你电脑大量长期占用了过多的CPU，请回复一下你的具体的表现

**Comment by Sailing168** [comment]
也许是情况错误，更新至最新版已解决
