### ISSUE TITLE
能否期盼一下给nas开发一个web+linux版本的。

### ISSUE THREAD

**Issue by fantasyjqc** [liupan1890/aliyunpan#711]
现在已有的这个linux版本需要桌面环境，是否可以期待什么时候大佬能做一个web+linux版本的，毕竟nas基本都是没有桌面环境的，类似于aria2-web那种。

**Comment by bilibili2077** [comment]
V3的版本开发了半年，现在发布的是体验版，有许多BUG要修改，一个人的能力有限，你说的给NAS的版本不可能给做的，除非你出巨资，要不就你再等个三四年后再提下兴许大佬有空！

**Comment by bilibili2077** [comment]
V3的版本开发了半年，现在发布的是体验版，有许多BUG要修改，一个人的能力有限，你说的给NAS的版本不可能给做的，除非你出巨资，要不就你再等个三四年后再提下兴许大佬有空！

**Comment by fantasyjqc** [comment]
> V3的版本开发了半年，现在发布的是体验版，有许多BUG要修改，一个人的能力有限，你说的给NAS的版本不可能给做的，除非你出巨资，要不就你再等个三四年后再提下兴许大佬有空！

我只是提这么个意见而已，现在的版本本身也是基于electron打包的。

**Comment by GitCourser** [comment]
#609 这个就是自己做的放nas上用的

**Comment by liupan1890** [comment]
我自己没有nas啊，所以其实开发nas版本，需要闭着眼开发

1.我不知道nas的文件路径
2.我不知道nas的架构（nas的CPU种类太多了）
3.我不了解群晖之类的系统

所以，不要指望我啦，做程序也需要将基本法，没有实物真的一头雾水啊

**Comment by fantasyjqc** [comment]
> 我自己没有nas啊，所以其实开发nas版本，需要闭着眼开发
> 
> 1.我不知道nas的文件路径 2.我不知道nas的架构（nas的CPU种类太多了） 3.我不了解群晖之类的系统
> 
> 所以，不要指望我啦，做程序也需要将基本法，没有实物真的一头雾水啊

感谢大佬回复叻，其实就像这个用docker做还是可以的，这样可以忽略很多跟环境相关的东西

> #609 这个就是自己做的放nas上用的

这样就不需要考虑文件路径，构架的话只需要依赖的包在相应的构架下有且兼容，或者是大佬只做x86的也是ok的，毕竟现在大部分nas都是x86，或者是arm64，他这个docker他是用的vnc，相当于是开了一个带桌面的linux。

**Comment by fantasyjqc** [comment]
> #609 这个就是自己做的放nas上用的

挺不错的，用也是OK的，挺不错的，如果能脱离vnc就更完美了。嘿嘿

**Comment by prodcd** [comment]
有Docker映射成WebDAV的，挂到nas上用也挺方便。
