### ISSUE TITLE
投稿阿里云盘资源站点-知识船仓（zscc.ysepan.com）

### ISSUE THREAD

**Issue by feichangmiren** [liupan1890/aliyunpan#715]
超800T阿里云盘资源免费分享，站长每天更新阿里云盘最新资源，用了很长时间了一直是免费开放使用，希望能够收录。
永硕E盘地址：zscc.ysepan.com
密码：zscc
![image](https://user-images.githubusercontent.com/92327137/170828958-e63ca410-00af-443b-8848-da9a6e76ff96.png)

**Comment by feichangmiren** [comment]
资源每天更新，大都是一手最新上传资源，一直在使用的一个站点，很不错，推荐收录

**Comment by liupan1890** [comment]
收到，稍后我会收录上去的

**Comment by MXGMXG** [comment]
密码不对了

**Comment by leopardciaw** [comment]
密码不对了

**Comment by GswiWHZW3nFDpmRV** [comment]
知识船仓·公益共建·致终身学习者（暂停一段时间，后续开放）
http://zscc.ysepan.com/login.aspx?d=zscc

**Comment by feichangmiren** [comment]
最新密码：ifree
