### ISSUE TITLE
2.14版本登录遇到 Invalid origin 提示

### ISSUE THREAD

**Issue by yashika** [liupan1890/aliyunpan#720]
![2022-06-01_18-18.png](https://s2.loli.net/2022/06/01/2XohAgIlD71en4W.png)

Ubuntu 20

**Comment by liupan1890** [comment]
我想你是这样操作的

1.下载v2.9.24
2.运行v2.9.24
** 没有点击彻底退出 **
3.下载v2.12.14
4.运行v2.12.14

因为此时v2.9.24仍在运行，此时运行v2.12.14是直接显示v2.9.24的

解决方案：退出v2.9.24,然后再运行v2.12.14即可

v2.9.24因为版本比较旧，阿里云盘官方已经升级API域名，导致无法正常使用了

**Comment by snowdream** [comment]
遇到同样的问题。

**Comment by yashika** [comment]
判断非常准确，厉害。是我大意了。谢谢。

发自我的iPhone
