### ISSUE TITLE
今天 登录不了了

### ISSUE THREAD

**Issue by snail2sky** [liupan1890/aliyunpan#726]
![image](https://user-images.githubusercontent.com/49757958/171992622-42b6bbc9-5116-4cbb-acde-b04c284ba2f7.png)
用了密码登陆，扫码登录和短信验证码登录，都报这个错误

**Comment by Dashan-IZ** [comment]
> ![image](https://user-images.githubusercontent.com/49757958/171992622-42b6bbc9-5116-4cbb-acde-b04c284ba2f7.png) 用了密码登陆，扫码登录和短信验证码登录，都报这个错误

window / linux / mac 版：

从蓝奏下载 https://wwe.lanzoui.com/b01nqc4gd

更新方式：删除旧文件，下载新版解压即可

注：如果遇到登录后无反应，登录不成功，请尝试重新登录几次就好了，有概率会登录后不跳转成功页面

**Comment by Dashan-IZ** [comment]
> > ![image](https://user-images.githubusercontent.com/49757958/171992622-42b6bbc9-5116-4cbb-acde-b04c284ba2f7.png) 用了密码登陆，扫码登录和短信验证码登录，都报这个错误
> 
> window / linux / mac 版：
> 
> 从蓝奏下载 https://wwe.lanzoui.com/b01nqc4gd
> 
> 更新方式：删除旧文件，下载新版解压即可
> 
> 注：如果遇到登录后无反应，登录不成功，请尝试重新登录几次就好了，有概率会登录后不跳转成功页面

更新到最新版，阿里换api了所以旧版本登录不上了，

**Comment by snail2sky** [comment]
嗦嘎，难怪&nbsp; &nbsp;感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月4日(星期六) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liupan1890/aliyunpan] 今天 登录不了了 (Issue #726)





   
 用了密码登陆，扫码登录和短信验证码登录，都报这个错误
  
window / linux / mac 版：
 
从蓝奏下载 https://wwe.lanzoui.com/b01nqc4gd
 
更新方式：删除旧文件，下载新版解压即可
 
注：如果遇到登录后无反应，登录不成功，请尝试重新登录几次就好了，有概率会登录后不跳转成功页面
  
更新到最新版，阿里换api了所以旧版本登录不上了，
