### ISSUE TITLE
扫描违规文件疑似出现bug，扫描被终止

### ISSUE THREAD

**Issue by xwpl** [liupan1890/aliyunpan#727]
扫描违规文件出现错误提示Cannot read properties of undefined (reading 'parent_file_id)，如下图所示，已知没有列出所有违规文件，似乎是因为错误扫描中断了
![qxlarge-dsc-E451A7D26613E5AF8C9BB45832AB3D36(1)](https://user-images.githubusercontent.com/30231628/171996759-2ff2f550-d131-4888-be2f-91e80f72e722.jpg)

**Comment by liupan1890** [comment]
这肯定是BUG了，

我的网盘里扫描没有出现这个BUG，所以可能这个BUG跟网盘内目录结构有关系，我稍后再多测试一下，看到底是哪里出现的BUG

方便的话给我贴一下log。

1.你是否在扫描过程中，在网盘选项卡里删除过文件夹？
2.退出小白羊，重新打开，等待左下角显示“加载全部文件夹...”,等待这个提示消失。然后打开扫描页，开始扫描。不进行任何操作等待扫描完成。看是否能够顺利的完成扫描不报错？

**Comment by xwpl** [comment]
![Screenshot_2022-06-11-17-57-15-875_相册](https://user-images.githubusercontent.com/30231628/173183123-1cae11c5-3b74-4f19-9ee9-fe304f4a194d.png)
日志是这里嘛，好像并不会记录这次报错。扫描时没有任何操作，而且是打开软件很久以后，多次尝试均报错。是在列出文件的过程中报错的。
