### ISSUE TITLE
希望转存可以支持115的json文件

### ISSUE THREAD

**Issue by xuxudong1110** [liupan1890/aliyunpan#73]
感谢大佬这个软件，比官方的好用

**Comment by liupan1890** [comment]
你需要提供一下json文件，我需要知道它是什么格式的

你应该是使用插件生成的json文件，但是因为115网盘的插件非常多，有的能创建json，有的不能。关键是每个插件创建的json格式根本不一样，所以支持json的意义不大，基本上也就是给你一个人用。

今天晚上会发布新版本，新版本里已经支持直接导入115分享链接

所以，推荐你直接在自己的115网盘里创建分享链接/或者直接找到别人的分享链接，然后导入分享链接，而不是导入json文件

**Comment by lingchuanbo** [comment]
是不是可以反过来115支持阿里导入呢

**Comment by liupan1890** [comment]
> 是不是可以反过来115支持阿里导入呢

1.导入时怎么实现的？答案是调用秒传接口

阿里云盘的秒传接口需要1.文件sha1  2.文件大小  3.文件名（不重要，随便编一个都行）
所以只要有文件sha1和文件大小就好了。115提供了每个文件的sha1 所以可以从115获取信息，调用阿里云盘秒传保存进去。当然这是碰运气的，成功前提是有人在阿里云盘上传过这个文件

2.是不是可以反过来115支持阿里导入呢

当然是可以的。
115的秒传接口，需要1.文件sha1 2 文件前1024k的sha1值--具体是不是1024我忘了，以前看过  3.文件大小
阿里云盘提供了文件的sha1值，文件大小。你再下载这个文件的前1024K，然后计算出sha1值，最后就可以调用115网盘的秒传存进去了。当然这是碰运气的，成功前提是有人在115网盘上传过这个文件

**Comment by xuxudong1110** [comment]
好的，谢谢大佬
