### ISSUE TITLE
文件备份功能

### ISSUE THREAD

**Issue by wqcblog** [liupan1890/aliyunpan#730]
大佬能否考虑开发一个文件备份功能
相当于数据库备份功能，导出一个文件(包含创建文件夹和文件，小白羊能读取它进行恢复)
这个用途是空间存满了，可以将暂时用不到的文件列表导出一份这样的备份，需要时直接恢复即可。
这个和分享不同的是，网盘中的目录可以删除，只需有这样一份备份文件。
和秒传不同的是它包含文件夹的创建操作，和文件是有层级关系的。
我想账号间复制是否是类似这样的逻辑实现呢？ 这样功能是否可以提出来呢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by liupan1890** [comment]
先备注一下，自21年9月，因为阿里云盘官方升级，已经无法通过秒传链接的形式秒传文件了。
现在想要秒传文件，必须你的电脑上存在这个文件（完整的文件），才能正确秒传
因为秒传时，需要随机的读取这个文件的8个字节的数据（理解为一个西瓜上要随机的扎一个针眼大小的洞取样）

---

1.文件备份功能
相当于数据库备份功能，导出一个文件(包含创建文件夹和文件，小白羊能读取它进行恢复)

功能上当然可以，但是导出的备份文件，就等于打了一个压缩包，体积很大并没有减少。所以无法节省网盘空间。
比如你备份一个100GB的电视剧（80多集）.那么备份文件就是100GB。所以没有备份的意义了

以前因为可以创建秒传链接，100GB的电视剧可以备份为100kb的秒传链接。现在不可以了


---


2.账号间复制

比如复制账号A的某一个文件，先读取这个文件的sha1值和下载链接，然后秒传到账号B。秒传时通过下载链接下载这个文件的8字节数据。就可以成功秒传了。

当复制很多文件/文件夹时，是软件自动的去一个一个的复制文件/创建文件夹

这是因为以前阿里云盘并没有推出好友分享功能。部分文件不能分享。所以规划的账号间复制功能。但是现在阿里云盘在测试还有分享功能，不限制文件格式。那么以后肯定就直接使用好友分享功能了。账号间复制功能意义不大了

**Comment by wqcblog** [comment]
好的 谢谢解答  我所提到的这个备份目的 是为了解决存储空间不足的问题
我以为仍然可以秒传，备份的仅是秒传链接，而不是庞大的文件。官方限制了，那就没办法了，谢谢
