### ISSUE TITLE
关于登录

### ISSUE THREAD

**Issue by BienBoy** [liupan1890/aliyunpan#731]
小白羊的登录怎么实现的，是内嵌的官方登录页面然后监听返回的token，还是找到了相应的api，直接发送请求。
我看源码发现之前的现在的登录的实现方式好像更改过。

**Comment by liupan1890** [comment]
是内嵌的官方网页登录页，面然后监听返回的token

1.在2.9是内嵌的网页登录页
2.在2.12开始是内嵌的app网页登录页

区别是返回的token不一样，网页登录token带referer参数，app网页登录页token不带referer参数
