### ISSUE TITLE
115sha的共享链接为什么取消了呢

### ISSUE THREAD

**Issue by Symmetrier** [liupan1890/aliyunpan#739]
之前在1.6的版本还是支持115sha的，现在似乎不支持了。共享链接只能导入阿里云自带链接

**Comment by Symmetrier** [comment]
才知道作者的不容易，非常感谢作者~
作者快发个赞助码吧~

**Comment by Symmetrier** [comment]
这里测试的版本是2.12.14

**Comment by jerryfangr** [comment]
> 这里测试的版本是2.12.14

之前作者是借助阿里跟115存的同一空间的漏洞转存的。

但B站的一个货直接捅出来，给阿里云官方举报了。
然后你懂的，阿里云修改了云盘的存取方式漏洞不存在了。
由此衍射的115转存功能，自然直接GG，作者也就移除了。

如无必要，建议close issue，这个repo下的无效issue属实有点多了。
或许作者可以考虑开个讨论什么的

**Comment by liupan1890** [comment]
因官方接口升级，所以被取消了。

当前，想要转存115的sha1，需要登录115账号（转存时需要当时生成有效的115下载链接），出于账号安全方面的考虑，没有继续提供此功能了

**Comment by liupan1890** [comment]
关于无效issue

已经在慢慢关闭了，从260-关到160了，会随着v3的进一步发布更新，陆续关闭一些。这个日期很近了

**Comment by Symmetrier** [comment]
好的，谢谢作者（b站那货给爷爬
