### ISSUE TITLE
洗码功能的原理

### ISSUE THREAD

**Issue by rewjx** [liupan1890/aliyunpan#74]
您好，请问洗码是指的改变文件的sha1值吗？如果是，要改变sha1值，必须改变文件本身的数据吧。那什么时候对文件数据进行恢复呢，是必须要用您的工具下载恢复之后才能正常使用原文件吗?谢谢。

**Comment by liupan1890** [comment]
当前并未提供此功能，只是在规划中，以后会慢慢实现，并且是独立工具，跟小白羊本身无关

1.洗码：是修改文件内容，导致sha1修改
洗码是针对视频文件来说的，就是修改视频文件最后1MB的某2个字节。（注：只修改2byte，不是修改1MB）
视频文件都是流式存储的，所以一般最后1MB存储着最后1秒钟的画面，修改2字节，最好的时候只是最后一秒画面中某一个像素变色--肉眼看不到。最坏的时候是最后1秒到3秒的视频无法观看

因为最后一分钟基本上都是字母，所以没有实际的影响，所以不需要恢复文件，没有恢复的实际意义

2.加密：是修改大部分文件内容，导致sha1修改
加密是使用加密工具异或修改部分文件内容，针对所有类型文件，修改后文件无法正常读取，需要下载后使用加密工具再加密一次（就是反加密，也就是解密）。跟打包压缩（带密码或不带密码）的区别是，1.加密无法自动在线解压2.加密速度快
