### ISSUE TITLE
帮助文档挂了，有最新的地址吗，主要是想学怎么用aria2

### ISSUE THREAD

**Issue by TFTree** [liupan1890/aliyunpan#747]
还是说aria2和小白杨的联动是只能远程挂在服务器上用，今天刚刚开始用aria2（而且是装在自己电脑上本地使用的，mac系统），还不是很懂，求大佬指教，还有就是为啥我往aria2那里填写参数，好像并不能保存？一关闭就没有了

**Comment by TFTree** [comment]
还是说aria2和小白杨的联动是只能远程挂在服务器上用，今天刚刚开始用aria2（而且是装在自己电脑上本地使用的，mac系统），还不是很懂，求大佬指教，还有就是为啥我往aria2那里填写参数，好像并不能保存？一关闭就没有了

**Comment by TFTree** [comment]
刚才自己试了一下，我好像懂了，把参数填好然后切换远程模式就可以了，之前不能保存大概是因为参数没填全而且没切换模式，点击下载就会自动推送到aria2上面。接下来如果要切回来就点击切回本地模式就好了，不过还有一点不懂就是为什么直接在阿里云盘上下载被称为本地模式，希望有大佬可以解答

**Comment by TFTree** [comment]
还有就是我自己使用本地模式和远程模式速度差不多，如果aria2实际装在本地而不是服务器上的话是不是没有必要切换成aria2的远程模式呢

**Comment by TFTree** [comment]
不得不说,aria2用的真是太爽了

**Comment by PingKuNet** [comment]
> 还有就是我自己使用本地模式和远程模式速度差不多，如果aria2实际装在本地而不是服务器上的话是不是没有必要切换成aria2的远程模式呢

原本的设计是应该是这样的，aria2的远程模式是推送到远程电脑下载，不是下载到本机电脑所以叫远程。

**Comment by TFTree** [comment]
> > 还有就是我自己使用本地模式和远程模式速度差不多，如果aria2实际装在本地而不是服务器上的话是不是没有必要切换成aria2的远程模式呢
> 
> 原本的设计是应该是这样的，aria2的远程模式是推送到远程电脑下载，不是下载到本机电脑所以叫远程。

谢谢大佬，懂了！

**Comment by liupan1890** [comment]
你好

1.默认情况下，你下载了小白羊，解压，运行，可以下载文件了
此时，你应该没有aria的概念（小白羊内置了aria，会自动调用，已经配置好了，不需要你执行任何操作）

--

2.特殊情况下，你希望把文件下载到其他电脑上（一般是指nas），可以在其他电脑上自己配置aria,自己运行aria,然后在小白羊的设置里修改aria的地址，通过远程链接的方式，把文件下载到其他电脑上
注：一般来讲，这个功能作用不大，因为你可以直接在远程电脑上下载小白羊，解压，运行，下载文件。不需要在本地运行小白羊然后下载到远程。这个功能适合远程电脑无法运行electron程序的情况，比如无UI的linux系统/dockers/nas/网络共享磁盘

--

不需要在你的电脑上自己配置和运行aria，然后让小白羊去链接，这个有点绕了

**Comment by TFTree** [comment]
> 

作者亲自回答！！！
谢谢大佬，懂了
我原先以为这样会快点...

**Comment by aiyolo** [comment]
怎么样能够在浏览器中打开小白羊的aria2本地管理页呢
