### ISSUE TITLE
短期直链的功能

### ISSUE THREAD

**Issue by wqcblog** [liupan1890/aliyunpan#750]
作者您好，阿里云盘下载获取的下载链接是否有对账户的认证？比如有时候需要给别人发一个文件，能否获取一个短期的直链，别人可以直接下载无需登录。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by liupan1890** [comment]
首先是下载链接是否有对账户的认证 -- 没有

阿里云盘生成的下载链接（https://bj29.cn-beijing.data.alicloudccp.com/5fbe39ae701d433be8af48298..........lO6qMnw%2F3trCugHZGk%3D&x-oss-signature-version=OSS2）,
1.有最长有效期限制（小白羊生成的是4小时有效，官方网页版生成的一般是15分钟有效，其他第三方库页基本都是4小时有效，因为官方限制最长就是4小时）
2.有header防盗链限制（referer = 'https://www.aliyundrive.com/'）

没有对账户的认证（既并不是说只有登录了你的账号才能下载，是任何人都可以下载）

阿里云盘还有另外一种下载链接，一般并没有人使用，只是备注一下，（https://api.aliyundrive.com/v2/file/download?t=1656002892&drive_id=234556&file_id=5fbe39ae701d433be8af48298......），这种链接有账户认证，需要登录**你的**账号才能下载

---

然后是 能否获取一个短期的直链，别人可以直接下载无需登录 -- 能
1.默认官方网页版获取的下载链接是有验证的（简单理解就是不能）（实际上是可以使用IDM下载，下载时填写referer = 'https://www.aliyundrive.com/'参数即可）

2.小白羊v2.12.14 可以在文件--详情--复制下载链接（仅视频类文件支持），复制到下载链接，可以直接下载
3.小白羊v3可以在文件--属性--复制下载链接（所有文件都支持），复制到下载链接，可以直接下载
注：小白羊，下载链接，可以直接下载，4小时有效

**Comment by hangxj** [comment]
原来小白有直链功能，因为一直用小白直接下载，没有限速，所以没去看过
