### ISSUE TITLE
Mac版一直显示无法连接后台

### ISSUE THREAD

**Issue by uni-pai** [liupan1890/aliyunpan#76]

**Comment by uni-pai** [comment]
debug.log里显示以下错误：
aliserver start 

2021/06/30 22:00:35 DBHelper.go:17: Start Path /Applications/阿里云盘小白羊版.app/Contents/Resources/

2021/06/30 22:00:35 main.go:47: all userdata loaded

2021/06/30 22:00:35 GoServer.go:40: Port: localhost:29385

2021/06/30 22:00:35 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/30 22:00:35 GoServer.go:45: Start ServerError:  listen tcp 198.18.1.71:29385: bind: can't assign requested address

2021/06/30 22:00:40 Aria2.go:47: Aria2ConnectError Post "http://localhost:29386/jsonrpc": read tcp 198.18.0.1:55714->198.18.1.71:29386: read: connection reset by peer

2021/06/30 22:00:40 GoServer.go:57: Shutting down server:  interrupt

2021/06/30 22:00:40 main.go:66: aliserver exit

**Comment by liupan1890** [comment]
GoServer.go:45: Start ServerError: listen tcp 198.18.1.71:29385: bind: can't assign requested address

小白羊启动时会有3个进程
1小白羊.app ----UI
2.aliserver  ----- 操作
3.aria2c ---- 下载

Debug.log里面的日志，说明aliserver无法启动绑定到29385端口，所以最后自动退出

那么为什么不能绑定这个端口呢？
1.有别的程序已经占用了这个端口了---很少见
2.之前重复启动小白羊，导致端口被占用

可以尝试的操作：
操作一：
1.在进程管理器里，看一下是否有aliserver这个进程，全部结束掉
2.重新打开小白羊
操作二：
重启电脑，先打开小白羊，再打开其他的软件（避免这个端口被别的软件占用）

**Comment by uni-pai** [comment]
以上两个操作都尝试了，但依旧是无法连接后台。
进行了以下尝试：
1. 进程管理器中反复排查没有aliserver这个进程。
2. 通过lsof未查询到占用29385端口的进程。
<img width="606" alt="image" src="https://user-images.githubusercontent.com/56943441/124003574-b1f33900-da09-11eb-9a69-37da3bc75985.png">

**Comment by liupan1890** [comment]
``````
func ListenServer() {
	port := "localhost:" + Port
	srv = &http.Server{Addr: port, Handler: &Router{}}
	log.Println("Port:", port)
	println("Port:", port)
	err := srv.ListenAndServe()

	if err != nil && err != http.ErrServerClosed {
		log.Println("Start ServerError: ", err)
		quitChan <- os.Interrupt //最后触发退出信号
	}
}
``````

你的这个情况很特殊啊，你是从哪里下载的？

1. 首先是Debug.log日志的问题，它提示的是 listen tcp 198.18.1.71:29385  这就不对，因为我代码里写的是localhost:29385
2. 然后是lsof 我在mac 10.15 上输出如下：
``````
clean@cleandeMac ~ % sudo lsof -nP -iTCP:29385
lsof: WARNING: can't stat() vmhgfs file system /Volumes/VMware Shared Folders
      Output information may be incomplete.
      assuming "dev=33000002" from mount table
COMMAND    PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
alixby    1696 clean   16u  IPv4 0x1485132e7f21338b      0t0  TCP 127.0.0.1:50621->127.0.0.1:29385 (ESTABLISHED)
alixby    1696 clean   18u  IPv4 0x1485132e7e5e3fcb      0t0  TCP 127.0.0.1:50615->127.0.0.1:29385 (ESTABLISHED)
alixby    1696 clean   19u  IPv4 0x1485132e7f25012b      0t0  TCP 127.0.0.1:50618->127.0.0.1:29385 (ESTABLISHED)
aliserver 1697 clean   10u  IPv4 0x1485132e7fc07fcb      0t0  TCP 127.0.0.1:29385->127.0.0.1:50615 (ESTABLISHED)
aliserver 1697 clean   13u  IPv4 0x1485132e7ed5838b      0t0  TCP 127.0.0.1:29385 (LISTEN)
aliserver 1697 clean   14u  IPv4 0x1485132e7fd6fb0b      0t0  TCP 127.0.0.1:29385->127.0.0.1:50621 (ESTABLISHED)
aliserver 1697 clean   19u  IPv4 0x1485132e7fc61b0b      0t0  TCP 127.0.0.1:29385->127.0.0.1:50618 (ESTABLISHED)
``````

重点： TCP 127.0.0.1:29385 (LISTEN)

所以现在的问题也就搞明白了，localhost本来应该是解析为127.0.0.1 在你电脑上却解析为198.18.1.71 这是不正常的。因为198.18.1.71属于外网IP，不是系统的内环IP，

请回复一下你的系统版本，是否支持IPv4 是否启用了IPv6?
小白羊并不支持IPv6

**Comment by liupan1890** [comment]
``````
aliserver start 

2021/06/30 18:36:50 DBHelper.go:17: Start Path /Users/clean/Desktop/阿里云盘小白羊版.app/Contents/Resources/

2021/06/30 18:36:50 main.go:47: all userdata loaded

2021/06/30 18:36:50 Aria2.go:27: LaunchAria2c http://localhost:29386/jsonrpc S4znWTaZYQ!i3cp^RN_b false

2021/06/30 18:36:50 GoServer.go:40: Port: localhost:29385

2021/06/30 18:36:50 Aria2.go:47: Aria2ConnectError Post "http://localhost:29386/jsonrpc": dial tcp [::1]:29386: connect: connection refused

2021/06/30 18:37:03 ApiLogin.go:87: apiMiniLogin client_id= 25dzX3vbYqktVxyX
``````

这是我mac 10.15上面的Debug.log
可以看到，直接显示的GoServer.go:40: Port: localhost:29385 这样才正确。因为localhost是系统内环，不受防火墙/联网权限的限制。而在你的电脑上，因为解析成了IP，导致受到联网权限的限制，绑定本地端口没有权限，所以绑定失败了

**Comment by uni-pai** [comment]
感谢，找到问题了。host有问题，我重置为默认内容就好了。
