### ISSUE TITLE
希望增加广告

### ISSUE THREAD

**Issue by SSLDY** [liupan1890/aliyunpan#760]
感觉小白羊很好用啊，希望能增加个广告啥的，毕竟维护和开发用爱发电不长久，要是有可以回血又无伤大雅的方式，请尽管上。
比如小白羊2.12.14，软件首页“插件”的右边可以多增加个“推广”，我想大多数人也不会有啥反感的。里面放点淘宝联盟之类的带返利的推广或者外卖红包，像什么京东联盟、多多进宝、多麦联盟、、、

**Comment by icetech233** [comment]
脑残真的多

**Comment by SSLDY** [comment]
> 脑残真的多

就讨厌你们这种吃白食的人，只会是伸手党，以为别人付出都是应该的。
不过也能理解，林子大了什么鸟都有，茅坑多了什么屎都有，就不知道您是那酌母鸟还是那些粪呢？哦对了，你是那些蛆，吃屎长大的，所以喜欢吃免费的屎，其他东西也不例外。
还有见过连阿里云盘官方限速都要咒人家死户口本，真是活到狗身上去了，合着人家就要免费提供不限速得给你们呗，一千兆家宽就给你们跑满一千兆服务器带宽，哟，阿里云机器带宽都是免费的吗？能随时随地跑满带宽，那还不抢网速，其他人体验都不用管咯？你们俩就是一家人，不是一家人不进一家门，你们就结婚算了，每天互相击剑，其乐无穷，反正都是蛆，不算同性恋。

**Comment by ghr1025** [comment]
脑残真的多,喜欢慷他人之慨

**Comment by SSLDY** [comment]
> 脑残真的多,喜欢慷他人之慨

**Comment by SSLDY** [comment]
> 脑残真的多,喜欢慷他人之慨
感觉全世界都得围着他转的人是这样想的，不仅喜欢当吸血鬼白嫖党，还是铁公鸡一毛不拔，增加个广告页碍着你们什么事了？只是各取所需而已，是强制弹屏广告吗？你们啥都没付出，就想着开发者无限付出？人家有义务一直维护这种0收益项目吗？哪天不管了，你们用什么？你是脑子长屁股上面了吗？还是活到狗身上去了？

**Comment by SSLDY** [comment]
> 脑残真的多,喜欢慷他人之慨

我就问一句，你们凭什么啊？凭你们喜欢用这软件，就得人家尽力给你弄个绿色无广告软件，还得时常更新修bug，凭什么啊？凭你们是龟孙子吗？

**Comment by ghr1025** [comment]
> > 脑残真的多,喜欢慷他人之慨
> 
> 我就问一句，你们凭什么啊？凭你们喜欢用这软件，就得人家尽力给你弄个绿色无广告软件，还得时常更新修bug，凭什么啊？凭你们是龟孙子吗？

那你知道为啥阿里不来找他吗，是因为他们不知道吗，一但有收益，律师函就来了

**Comment by SSLDY** [comment]
> > > 脑残真的多,喜欢慷他人之慨
> > 
> > 
> > 我就问一句，你们凭什么啊？凭你们喜欢用这软件，就得人家尽力给你弄个绿色无广告软件，还得时常更新修bug，凭什么啊？凭你们是龟孙子吗？
> 
> 那你知道为啥阿里不来找他吗，是因为他们不知道吗，一但有收益，律师函就来了

你说的是有那么一点道理。之前的pandownload是死在公开收费模式，但是被干掉给理由是隐私问题。

要我说只要不把收益直接跟软件绑定挂钩就完全可以规避这种风险。多重变现渠道多了去了。加多个菜单叫分享，里面放点日常需要的一些没有aff的常用链接网站导航，小说站、视频站、在多加个外卖红包领取链接站，都是分享，谁能知道谁有收益。大不了放个开发者主页网站，里面介绍作开发者的几款软件，不加小白羊，再留个赞助方式就行了。只要不傻傻的在软件上留下收款码就没事。

退一万步来说，如果要搞你，别说有没有收益了，阿里云都直接律师函，如果只是方便阿里云盘用户使用，那没问题，甚至很乐意。现在阿里云是卖空间和提供基础速度，如果要大幅度突破限速，那就直接GG，影响到他们收益才是最关键的，只要不踩红线压根没事，甚至放任你自行diy，他们也说了，禁止变动阿里云盘的功能或运行效果，你要突破限速，那就是增加他们服务器成本，那才有事。

**Comment by RiverChu0** [comment]
https://github.com/mengzonefire/rapid-upload-userscript/issues/38

**Comment by Takenforgranted** [comment]
一个那么多star的开源项目的创收有很多种方式，你偏偏要选择广告。

是不是因为你妈看了劣质避孕套的广告买了个化工残渣超标的假货才生出来你这么个脑残玩意儿？这也导致你对广告如此的感恩戴德。

**Comment by nekohalawrence** [comment]
广告不好吧，换一个方式也可以的
