### ISSUE TITLE
为什么无法创建妙传链接

### ISSUE THREAD

**Issue by liveskai** [liupan1890/aliyunpan#79]
# 为什么无法创建妙传链接

**Comment by liupan1890** [comment]
因为之前有用户反映过，不应该有创建秒传的功能。因为此功能突破了官方审核限制，容易被官方追责。所以就去掉了秒传链接创建功能。

但是保留了创建秒传文件的功能啊

**Comment by liveskai** [comment]
> 因为之前有用户表现过，不应该有创建秒传的功能。因为这样突破了官方审核限制，容易被官方追责。所以就取消了秒传链接创建功能。
> 
> 但是保留了创建秒传文件的功能啊

秒传链接好用

**Comment by liupan1890** [comment]
确实是，但是等到以后官方会开放分享功能，还是以官方的分享功能为准吧
