### ISSUE TITLE
希望能够允许自定义播发器

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/aliyunpan#8]
需要像六盘小白羊一样的播放器自定义！谢谢

**Comment by liupan1890** [comment]
在阿里云网盘公测前期，允许直接下载，所以此时可以用迅雷或者其他（IDM）直接下载，
同理，可以调用很多款播放软件去播放（调用播放器.exe --url）

当前阿里云网盘的下载地址大部分都启用了referrer验证，所以现在你不可以直接调用其他播放器播放，必须播放器本身支持设置referrer参数才行（mpv播放器可以设置），我没有研究过其他播放器是否支持设置referrer

所以，你应该把你想使用的播放器直接说出来，大部分播放器都不支持设置referrer，大部分播放器都不能调用。你说一下你的播放器我去看一下

另外，不知道mpv哪里不好呢？

**Comment by Sailing168** [comment]
我用的MPV我用的是MPV-EASY-Player，也就是个UI优化。mpv元界面看着不舒服，mpv很好用
链接：http://d0.ananas.chaoxing.com/download/bf645048b9b0b5e5f4cc234a51467741?at_=1622260523188&ak_=9bfa6a659c8120aeeec0b92832406dc2&ad_=e1058cdd796a4e5abe3d3700ce331fd2&fn=MPV-EASY Player.7z

**Comment by liupan1890** [comment]
我看了，

1.本质上还是mpv
2.是通过让mpv加载自定义的脚本，实现的GUI

经过测试，
MpvEasyPlayer.exe 并不能通过命令方式调用--它不支持
但是，你可以通过参考官方的https://github.com/422658476/MPV-EASY-Player，上面详细介绍了怎样一步一步的定制mpv

简单理解就是把一些脚本文件复制到指定的目录，然后mpv启动时会自动加载，实现MPV-EASY-Player的GUI效果

针对小白羊mpv是在  ` 阿里云盘小白羊版\data\MPV\` 这个目录下，你可以试着按照官方教程去复制文件配置小白羊自带的mpv，实现MPV-EASY-Player的GUI效果

我没有精力去做这件事，需要你自己动手试试了，看https://github.com/422658476/MPV-EASY-Player上面的教程并不是很复杂，主要是根据mpv的版本去复制好对应的文件，放在正确的位置，肯定需要摸索一下了

**Comment by Sailing168** [comment]
好的，谢谢
比心
