### ISSUE TITLE
能不能开发秒传到天翼云

### ISSUE THREAD

**Issue by tianjiaoshanzai** [liupan1890/aliyunpan#80]
好像里面内容更丰富一些

**Comment by liupan1890** [comment]
我平时不用天翼云盘，没研究过天翼的秒传接口。刚刚搜索看了一下，据说是天翼秒传使用文件的MD5值，阿里云盘只提供sha1值，技术上无法实现sha1转md5。必须完整下载整个文件后才能计算md5值

也就是无法实现115直接秒传天翼，无法实现阿里云盘直接秒传天翼
