### ISSUE TITLE
请教下各位：上传和下载记录是保存在哪里的？

### ISSUE THREAD

**Issue by yansheng836** [liupan1890/aliyunpan#809]
上传和下载记录是不是保存在哪个文件？
（相关代码好像是这里）

https://github.com/liupan1890/aliyunpan/blob/b0bc8b8210eaff683d161ed06fb5398ca1162dc1/packages/renderer/src/setting/SettingDebug.vue#L95-L109

**Comment by PingKuNet** [comment]
你好，首先你查看的这个V3版本，上传和下载记录还没有实现

另外下载记录并没有直接保存在 “文件” 中，而是保存在DB中，
这个DB是Electron 基于 Chromium 自带的DB，
如果你做过前端开发，就应该知道浏览器中的DB，那是一个原理，
那个，那个，我在这个基础上完善了一下，有上传和下载记录的V3版在这里
https://github.com/PingKuNet/aliyunpan

不过你也可以查看V2的源码，也是有上传和下载记录的实现代码，存储的代码实现有一点点不太一样

**Comment by yansheng836** [comment]
> 

了解，感谢解惑 🌹
