### ISSUE TITLE
大佬你好，能不能提供个上传前调用某个程序的功能？

### ISSUE THREAD

**Issue by SupernovaCooper** [liupan1890/aliyunpan#81]
上传前调用某个exe，然后把经过这个exe加密之后的结果文件上传，这样保密性更强，也杜绝了他人查看文件的可能（即便网盘被别人登录，看到的全是加密后的目录和文件）。

简单一点，比如：自动调用WinRAR，然后打个加密的压缩包后再上传。

同类软件有AirExplorer，它目录也可以加密，并且在软件内浏览的时候可以自动解密目录，看起来就跟没加密一样，这个是个非常安全方便的功能。只是它不支持阿里云盘。

用网盘作为一种容灾措施来备份NAS的资料，明文的话有些比较敏感的资料，所以非常需要这种可以自定义加密的功能。谢谢。

**Comment by liupan1890** [comment]
额，这个功能吧，其实要说实现起来也不难。但是确实有问题：

**第一点是 ：每一个软件的调用命令都是不一样的。不能内置写死调用命令**

所以比较可行的方案就是，调用一个bat脚本文件。传入文件路径
用户，你自己，编写脚本文件，去调用你想调用的程序，比如你在bat里写winrar.exe -x -file 去打包

那么问题来了，大部分用户不会编写bat脚本。这个怎么解决？
我把常用的软件脚本都写一遍？但比如AirExplorer，我都没听过。。。。因为我平时没有用到过

**第二点是：没有运行结果的回调**

还是拿压缩包举例子，当你调用压缩时，源文件xx,mp4变成了xx.rar (其他软件同理，除非是直接操作源文件的软件，不然都会生成一个新文件)

首先小白羊无法知道什么时候压缩打包完，比如xx.mp4有4GB，打成压缩包需要1分钟。但是小白羊无法知道1分钟后打包完了，也就是说winrar压缩完后不会通知小白羊

然后也无法知道打包后的文件是xx.rar(无法知道新文件的完整路径)。那么怎么知道要上传那个文件呢？

所以，我没能想到正确的操作流程，能够完善的实现你想要的效果

你可以想一下，然后回复我怎么设计最合适

**Comment by SupernovaCooper** [comment]
感谢大佬回复。
**关于第一点，第三方程序的调用：**
其实不需要考虑那么多，只是提供这个能力就行。因为这应该算是高级一点的开放能力了。
就像你说的调用脚本，提供这么个设置项，需要的人可以根据自己的需求自己写个程序来实现自己的加密、压缩等等。简单说就是，有这么个输入框，里面我可以输入我要调用的程序 + 参数，比如我输入 C:\my_encrypt\encrypt.exe -FilePath -param1 - param2 之类的，相当于把文件路径传递给这个exe，然后这个exe怎么操作就无所谓了，最终只要它给返回处理后的路径，然后就可以继续上传动作了，否则线程一直等待这个exe返回，因为可能处理非常耗时。

**第二点关于回调结果：**
调用exe后可以一直等待返回结果。按照我的认识，小白羊上传应该是一个单独的线程吧？只是现在在线程上传时，先调用第三方exe，把相关参数传递给第三方，然后阻塞等待这个exe或者bat执行完毕然后拿到结果。
只是一般exe可能返回值只是0或者其他数字，因此可能需要用户手动通过自己写bat来返回加密后的文件路径了。
我不确定exe或者bat能不能直接给小白羊返回个字符串，因此有两种方案：

1.如果不可以可能就略麻烦，可能需要小白羊向第三方程序提供2个参数，一个是%sourceFile%原始文件路径（告诉第三方程序需要被处理的文件路径），另一个就是%output%处理后存放的路径（第三方处理完毕后小白羊来读取上传的文件路径），这样第三方程序就可以知道需要把处理后的文件保存到指定路径，然后再返回0，小白羊就可以继续上传了。

2.如果可以直接返回字符串给小白羊，那就可以定义1个参数：%sourceFile%原始文件路径（告诉第三方程序需要被处理的文件路径），然后第三方exe或者bat直接返回处理后的文件路径就好了。

这两个方式的差别，一个是由小白羊定义要保存的加密后的临时文件路径，一个是由第三方自由处理加密后的临时文件路径。不过不管怎样，能让小白羊接收到就可以实现目的。


另外关于这个功能可以延伸一下，针对特定目录进行加密、压缩上传之类的等等，因为全部加密的话，有些不重要的目录里文件又大，加密又耗时耗资源，就非常蛋疼了，比如目前我用AirExplorer，加密上传一次跑一个礼拜都跑不完（它需要加密每个文件，然后跟网盘里的文件对比md5或者sha1。。。太蛋疼了。。。这就有另一个需求啦，每个加密文件可以上传一个同名的原始文件的.sha1文件，这样下次对比时就不需要加密后再去对比网盘里的文件了。）

还有就是，这个需求目前应该比较小众，或者说没有人意识到这样做的意义：
首先文件给了网盘，网盘说是各种保障后台他们看不到原文件，可是谁知道呢？照片什么的他们真的不会拿去训练AI之类的嘛？我反正是表示怀疑的。其次一旦网盘被别人登录了，别人是可以看到明文的，个人感觉这非常不安全。除了我说的那个AirExplorer之外，貌似没有可以加密上传的网盘客户端。也许当这个功能铺开了之后，估计大家会意识到这样做的好处了吧。话说回来，加密后上传估计各个网盘非常不希望这种事情发生，因为这相当于在他们的硬盘上存了一堆对他们没啥利用价值的文件啦。。。

之前想自己做个客户端实现这些功能，但是今天发现已经有不少完成度很高的了，我若再造轮子能力不够还浪费时间，所以只是把自己的需求和想法提出来，希望继续和大佬探讨，也希望大佬能加以实现。

**Comment by SupernovaCooper** [comment]
![image](https://user-images.githubusercontent.com/30821254/124307948-1db8db80-db9b-11eb-84db-ec278abd198d.png)

**Comment by liupan1890** [comment]
我的意思，其实是想说，这个功能卡的很死

就像你说的，有输入框，你可以手写参数。然后等待被调用的程序运行结束返回。

到这里思路都是很好的

第一个问题：你可以自己手写参数，但大部分人不会。这个怎么办？普适性做不到，你无法要求大部分人都会写命令参数，比如winrar `rar a -hp123 c:\eee.rar e:\software\office2003.nrg` 大部分人并不知道应该写-hp 或者应该先写 rar输出路径，还是先写原始文件路径，它写成  `rar a -hp123  e:\software\office2003.nrg c:\eee.rar` 这样就是错的

第二个问题：每一个软件的返回都是不一样的
我们是拿winrar举例子讨论，如果换一个软件呢，立马就大变样了
方式1.等待软件执行结束输出返回结果
winrar执行成功后，并不会返回打包后的文件路径，而是直接退出。同理其他软件一般也都不会返回“新文件”的路径
方式2.调用时传入“新文件”的路径
winrar是支持传入打包rar路径的，或者说必须输入，但其它软件呢？无法确保其他软件也支持传入这个参数吧

我说的死，意思就是，必须针对特定的一个软件，去开发编写好上传前调用命令和下载后调用命令，这个软件是固定的，不能更换的。（输入参数/输出参数）

**所以我感觉咱们讨论“增加上传前调用指定命令的功能”，方向是错误的**

**我们应该讨论“增加上传前加密的功能”**，也就是完全按照你的需求去实现这个功能，这样不用考虑“被调用”的程序的参数问题，也不用考虑大家会不会编写脚本的问题，也不用考虑等待/返回结果的问题

但是之前也有人问过我，意思是不希望内置洗码/加密功能。所以之后我就修改了readme.md，规划中的洗码/加密功能会改成独立的小工具。主要顾虑是现在可以加密上传，等以后小白羊万一不能用了，文件就不能解密了。如果是提供了独立的加密小工具，那就一直可以用了。

如果你是只需要“加密”。那么现在可以自己写脚本批量把需要上传的文件加密（winrar打压缩包），以后也可以手动操作规划中的加密小工具去加密

我知道你想实现的是，上传前自动加密，下载后自动解密。这样的内置好的，自动化的功能。但是就像上面提到的，万一以后小白羊不能用了呢（我也不知道为什么小白羊不能用，只是假设，万一）这些已经加密的文件不就丢失了。所以最合适的方法还是有个小工具（比如winrar这种现成的，类似的，加密工具有很多）自己手动操作最保险。

换成你自己先把需要加密的文件全部加密好，然后再使用小白羊批量上传。这个操作虽然是手动的，但是也非常简单。你还能选择那些文件加密，哪些不需要加密。而不是统一的自动加密。我感觉比自动加解密逻辑要简单清晰

**Comment by SupernovaCooper** [comment]
1.大部分人不会写参数写脚本，这个确实是，只是不一定所有功能要考虑全部用户是否会使用吧。尽最大可能的提供了一种能力，至于怎么使用，就是用户的问题了，但多一个功能总是好的吧。。比如word，提供了若干功能，不会考虑每一个用户是否都用到全部功能以及他们到底会不会用吧。。

2.软件的返回值这个不同，也不要紧，只要按照小白羊定好的要求，返回0或者是返回一个路径即可啊。至于第三方软件怎么适配怎么写脚本以及怎么加密、压缩的过程，我们不需要关心啊。我们只要在最大能做到的程度里提供这些功能即可。
3.如果上面两条解决了，就相当于不用针对一个特定的软件开发了。类似于提供了个接口的方式，按照接口要求，用户自由发挥就可以兼容绝大多数软件了吧。

4.关于方向的问题，其实对于我来说这是同一个方向，我想小白羊提供“上传前调用指定命令或程序的功能”来实现自己的“上传前加密”。为什么会说成“能不能提供个上传前调用某个程序的功能”，是因为这个功能比“上传前加密”要更有拓展性，我上传前调用一个bat，bat里可以做很多操作，比如本地做记录之类的等等，“上传前加密”只是它的一个**具体实现**，**一个子集**。

5.“上传前加密”这个功能可以单独做，但是它与“上传前调用命令”这个功能并不冲突，**还是非常强烈建议提供这种拓展能力**。再者举个例子，比如word的宏，就是一种拓展呀。

6.关于小白羊如果不能用了可能引发的问题，如果是内置加密算法，内置加密，那可能就真不能用了。反而如果是我自己通过其他程序加密的，依然可以解密啊，只不过是用其他客户端下载下来再通过自己写的脚本或者是程序解密，只是恢复数据的时候多了一些手动操作的过程，但是并不会导致文件丢失啊。

7.关于手动操作，如果整个过程我都是手动操作，那就失去这个问题的讨论价值了啊。

8.我的使用场景是这样的：NAS里保存了大量资料，现在使用的AirExplorer，支持计划任务，每个周指定时间自动执行加密后上传到百度云，一般情况下不会去下载，因为这只是我的一个容灾方案（万一NAS被人偷了之类的。。。）。几个T的文件，已经不是说过程简单不简单的问题了。。。。。。。。。。。。。。而且写个脚本全部加密后保存到某个目录再通过小白羊去上传这个目录，也不实际啊，几个T复制一份硬盘就满了啊。。。。

**Comment by liupan1890** [comment]
是我没考虑到你的数据量，还有操作流程。原来是NAS和自动执行计划任务

我想到了一个比较可行的思路。之后小白羊会增加“同步盘”功能，我想你的需求可以通过同步盘功能去实现。


比如你有一堆文件（.doc.mp3.mp4）,
1.设置了同步盘只上传.rar文件。
2.设置同步盘定期调用脚本(rar.bat)
--bat的功能是用户自己编写的。假设在rar.bat里会自动遍历目录，对指定文件打包成rar。
--这样就实现了定时把部分文件打包成rar
--当然也可以你自己写一个小程序，然后bat里只写一句调用小程序的命令。这样实现哪些功能完全是你自己决定了
3.设置同步盘上传后删除源文件选项

最终同步盘会自动上传rar文件，上传完还会删除清理空间

这样一来，唯一的问题就是你的数据**增量**同步的问题了。
1.比如你的小程序里记录了那些文件打包过，或者打包时生成一个.bak的记录文件
2.比如你写一个脚本定期复制需要上传的文件到同步文件夹


同步盘的功能：
1.定期执行指定脚本/程序/cmd命令
2.可以设置自动同步的文件格式（过滤文件）
3.自动同步指定目录里的文件（可以设置方向，比如只上传，只下载，上传和下载）
4.可以设置上传后是否删除源文件
5.可以设置上传是否覆盖还是自动重命名

等等吧，还没全想好，


实际上，我感觉只是因为现在AirExplorer可能还不支持阿里云盘，等以后他肯定会支持的。你已经用惯了AirExplorer，等以后它支持阿里云盘后，你也就不需要小白羊去自动同步了。
