### ISSUE TITLE
大佬好，两个功能建议。

### ISSUE THREAD

**Issue by pkids** [liupan1890/aliyunpan#82]
大佬好，前几天看到更新1.6.29版本，支持拖拽到小白羊里上传了，觉得好棒！我家2台电脑，一台用官方pc版，一台用小白羊，有两个建议：

1、小白羊版本的列表能否支持直接显示缩略图啊，对比了官方版和小白羊版，觉得直接能看到相册里的缩略图会更好一些，您也知道相册直接点备份，备份上去的都是一长串数字或者字母的图片或者视频，其实从文件名真的很难判断出是不是自己想要点开的那个文件。在网盘界面里这个问题就会没那么严重了，毕竟网盘上传的文件一般我们都会归类好或者重命名好。

2、期待打破壁垒：小白羊吸引我的地方就是 业界大拿个人开发+绿色+很精简，我不知道我的第二条建议是否可取，作为小白羊热心用户在b站刷到一个第三方软件，点开软件后输入百度云账户和阿里云账户，软件会罗列出百度云中的文件列表，勾选要同步的文件，点击传送就能下载到本地+上传到阿里云+删除本地文件+执行下一个，我觉得既然小白羊是第三方开发软件，市场上也有这样成功的第三方软件，小白羊能否也加上去或者更优化下，变成能实现输入阿里云分享链接+验证码，就能自动在后台下载到本地，然后上传到阿里云，甚至成熟之后让用户可选择是否开通小白羊会员，会员可以自动下载到小白羊服务器，然后从小白羊服务器中转传输到阿里云，诸如此类的。

【百度网盘一键迁移阿里云盘！-哔哩哔哩】https://b23.tv/KmLD85   这个是我刷到的那个视频。

以上都是热心用户不成熟的建议，如果有可取之处，请大佬记一笔，以后有空了考虑下，如果不可取就当作和网友聊天，我会一直支持小白羊的。

**Comment by liupan1890** [comment]
百度网盘一键迁移阿里云盘 确实很厉害啊

不过我确实有2点顾虑，需要跟你探讨

**1.百度法务问题**
嗯，你没看错，如果小白羊提供了百度分享链接下载的功能，就会收到百度法务的警告。我为什么这么说呢？因为我之前开发了6盘小白羊第一版，当时6盘提供百度链接下载功能，而我开发了一款6盘的美化UI。然后我就收到了百度法务的邮件，提示我在未授权的情况下，提供了百度分享链接下载功能，侵犯了百度的合法权益，要求我关闭项目。然后6盘小白羊第一版就彻底停止更新了

那么问题来了，
第一功能是6盘提供的（后期6盘已经公开宣传停止百度链接人工带下服务了--当然只是宣传实际在背后仍然提供着）。
第二我也没任何收费。
百度就是这么咄咄逼人。

**2.下载速度问题**
方式一：你登录你自己的百度账号，使用自己的百度账号下载。
如果你是百度超会当然可以快速下载（不一定是满速，看账号流量/状态）。
如果你是普通会员，前几GB还够快，之后触发限速我印象里是100kb/s最高了。

对于普适性的，当然默认大家都不是百度超会，那么这个速度真的没法用

方式二：通过百度分享链接分享，小白羊服务器代下
参见上面法务原因，不会提供此方式。另外我的服务器也没这么高的带宽

方式三：通过百度分享链接分享，小白羊调用各种第三方接口实现解析，然后用解析url下载
参见上面法务原因，不会提供此方式。另外调用第三方解析，也确实有隐私方面的顾虑

所以你看，想法是很好的，但我自从6盘小白羊第一版之后，我就不再开发百度相关的程序了。不敢。可能也是因为当时Pandownload刚被抓，所以当时百度管的严。现在风声可能已经过去了不管了。但是我就是个送外卖的，不想跟百度折腾。感觉你看到了我说的这些，会理解我的。并不是我不重视大家的留言。

**Comment by liupan1890** [comment]
关于缩略图的问题

其实功能上能够实现的，但是设计上我没有实现。是因为官方提供的很完善了，我以为大家用小白羊都是为了满速下载的，

有一点小白羊和官方不同
官方呢是一次最多显示100条记录，只有你滚动到底部然后再继续加载。
小白羊呢是会加载全部文件，

问题在于阿里的缩略图url有效期只有15分钟--5月底我开发的时候确认的15分钟。
我需要考虑一下怎么才能避免超时失效

另外，官方是electron，也可以看作浏览器，
electron本身就支持图片的缓存。所以官方PC显示缩略图不会有性能问题--因为谷歌已经解决了图片的性能问题
小白羊呢是Flutter，它本身对显示一堆图片的这种，性能并不好，也不支持图片的缓存，所以还要考虑性能这方面怎么优化一下

所以，一个很简单的功能，但想要实现细节还是挺多的。我之后会研究一下再看。

**Comment by liupan1890** [comment]
能否说一下，你对缩略图 具体的操作/需求呢？我按照需求去考虑/规划/上线功能

我知道你是在相册里，然后想看缩略图，然后呢？
你是为了找到某一张图片？把他下载到本地？

因为网页版有缩略图，可以快速的找到某一张图片。如果你只是想看这张图片的内容，或者把这张图片下载到电脑上，其实完全可以直接使用网页版，操作更加方便，而且阿里云盘肯定会支持到人像/海报/扫描图这种的AI智能识别智能分类功能。

只有批量的想下载图片到电脑（备份手机图片到电脑），才需要用到小白羊，而这个时候，并不太关心具体是拿一张图片。都是批量选择下载，偶尔的也可以通过点击图片名，直接使用小白羊查看大图（不是缩略图功能，是在线查看图片）

所以我希望你能回复一下你具体的使用场景（想要干什么，怎么操作的，因为小白羊当前没有缩略图所以那一步操作遇到障碍不太方便了）

**Comment by pkids** [comment]
谢谢老大详细的解答，我对缩略图的具体操作和需求是：

1、觉得有缩略图的相册会比较适合一般用户使用习惯，我也知道网页版阿里云盘和官方pc阿里云盘有这个功能了，但是出于对小白羊的喜爱，希望小白羊也能拥有直接显示缩略图的功能，这样对于那些只用小白羊的用户来说，会大大提升使用体验（但是听老大说了用的程序框架不一样，开发起来挺费事的，有点后悔自己没事给你找事做，嘤嘤嘤。）；

2、没缩略图使用起来的不方便之处就是看文件名猜不出照片内容，其实相册备份就是为了回忆，一件很温馨的事，没有太多着急批量选中下载的情绪在里面，就是打开软件翻着相册，看着过往点点滴滴，哪个缩略图触动自己的回忆，可以双击打开，仔细看看，如果站在这样的使用场景，估计就能理解我提出这个建议的初衷了。

小白羊已经很完美了，特别是支持拖拽上传之后。因为喜爱，所以看到一些比较有意思或者觉得提升体验的功能，想要小白羊也能拥有，因此提建议啦！  ^_^

**Comment by pkids** [comment]
对了，顺便提一下，使用小白羊打开图片，默认图片是多大就显示多大，比如图片是1920*1024px尺寸的，但是我们的小白羊软件只能显示出图片的一小部分（也许是1920*980px），剩下的部分得下拉才能看到。阿里云pc官方版是会根据软件的窗口大小，自动缩放的，我觉得会略微提升使用体验度，打开照片，默认就能等比缩放看到100%内容，而不是需要下拉才能看到下半部分图片，不知道这个图片显示上能否优化，改起来会不会比较难。

**Comment by liupan1890** [comment]
1.关于增加缩略图的意义我也理解到了，后期我会想办法实现的。技术上复杂不怕，做程序吗就是各种折腾

2.关于在线浏览图片大小问题
首先我是根据自己的需求去做的在线预览，我的需求是看漫画。因为漫画都是长图，所以最好的就是现在这样宽度放到最大，然后能上下滚动。如果是按照阿里云盘那样默认按照长宽最合适的确保显示整张图片，看漫画就看不清字，必须手动操作（点一下放大按钮之类）让他宽一点，看下面的内容时再向下滚动一下

所以，为了节省这个点一下的步骤，我做成了现在这个样子。因为漫画都是几十张，几百张一本。也就是节省了几十下的点击，关键是浏览体验。你想你看完了这一张，点击下一张，然后立即就看或者是需要再点一下才能看，这个体验是不一样的。

这个地方我决定先不改，这个跟需求有关，按说我应该在设置里增加一个设置项，让用户选择是按照图片宽还是按照图片高去显示，但是我又不愿意在设置里有很多设置项，用户看着就感觉很麻烦

然后是Flutter的操作问题。Flutter是适合手机的操作的，你比如图片的放大缩小，他是触控屏那种两个手指头缩放操作，对于电脑来说就很尴尬，没有触控。只能通过鼠标中轮滚动操作放大缩小，但电脑的习惯鼠标中轮滚动是上下滚动图片。Flutter还有一个奇葩的地方是拖动操作不支持双向，要不横向拖动，要不竖向拖动，不支持横向和竖向一起拖动。比如阿里云盘当前的拖动鼠标批量选中功能，Flutter就实现不了，因为你是斜着拖动鼠标选中一个长方形的区域。我也不知道他为啥这样设计，总之是很奇葩。所以当前图片预览也没有放大缩小的功能

**Comment by pkids** [comment]
嗯嗯，谢谢大佬~

**Comment by liupan1890** [comment]
我决定了，抛弃Flutter切换成Electron了，这样就可以完美的实现缩略图功能了。下个版本的小白羊里会增加你想要的缩略图，也会增加在线预览图片的大小的设置项。努力！加油！

**Comment by pkids** [comment]
谢谢大佬，奥力给~

**Comment by pkids** [comment]
门外汉觉得框架换了，肯定改起来是个大工程吧！好期待下个版本~

**Comment by liupan1890** [comment]
缩略图已在v2.10.31上线
