### ISSUE TITLE
希望可以自定义播放器

### ISSUE THREAD

**Issue by rapmq0** [liupan1890/aliyunpan#83]
建议在设置里加个自定义播放器路径的功能

**Comment by liupan1890** [comment]
这个解释一下
阿里云盘当前限制了下载链接请求时必须附带referrer头。我只知道MPV播放器支持传入referrer参数。其他的播放器不支持传入此参数，所以也就无法播放（QQ播放器，迅雷播放器，暴风影音，Potplayer都不支持）

你想要调用自定义的播放器，必须先确认这个播放器支持命令行里接收和设置referrer参数

如果是其他的GUI版本的MPV播放器，你可以试着直接替换掉`data\MPV\mpv.exe`

换句话说，其实在设置里加个自定义播放器路径的功能，你可以直接把自己的播放器复制到`data\mpv`这个文件夹，并且修改播放器名为mpv.exe就可以了。根本不需要在设置里增加修改
如果你替换了可能也不能播放，是因为
1.调用的命令参数不支持
2.播放器没有附带referrer

``````
//当前调用mpv.exe的命令：
--user-agent="aliyun" --force-window=yes --referrer=https://www.aliyundrive.com/  "url"
``````
