### ISSUE TITLE
Windows10运行小白羊V2.12.14即出现发生未定义的异常，小白羊将自动退出

### ISSUE THREAD

**Issue by q527596142** [liupan1890/aliyunpan#839]
![QQ截图20221104205955](https://user-images.githubusercontent.com/116608589/200122774-c17306aa-dd29-4af7-ac2b-c85b63356a4c.png)
![QQ截图20221105214322](https://user-images.githubusercontent.com/116608589/200122961-7f1e2b9d-8977-4ab0-b1ad-3d4da9397a1f.png)
![QQ截图20221105214445](https://user-images.githubusercontent.com/116608589/200122963-35273914-468c-46d3-8019-05e899b358c7.png)
如图，另下的Aria2显示可以连接，启动小白羊显示Aria2本地连接已断开。
自己尝试过一些办法，都没奏效。如安装Windows运行文件、重装小白羊、覆盖aria2c.exe文件等。
网上搜寻也没找到解决办法，本人还没试过重装系统，嫌麻烦（也未必有效），希望能有不重装系统解决这个问题，正常运行小白羊的方法。
希望作者或者各位大神能出一个详细解决方案，多谢。

**Comment by PingKuNet** [comment]
重新检查一下文件位置是否正确:
D:\Program Files (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\resources\aria2c.exe

另外下载的是否覆盖在这个目录
D:\Program Files (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\resources\

如果确认无误，那么尝试将整个阿里云盘放置在其它位置，一个不带空格和小括号的路径下

**Comment by q527596142** [comment]
> 重新检查一下文件位置是否正确：D:\程序文件 (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\resources\aria2c.exe>> 另外下载的是否覆盖在目录D:\程序文件 (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\资源\>> 如果确认无误，那么尝试将整个阿里云盘放置在其他位置，一个不带空格和小括号的路径下

**Comment by q527596142** [comment]
> 重新检查一下文件位置是否正确: D:\Program Files (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\resources\aria2c.exe
> 
> 另外下载的是否覆盖在这个目录 D:\Program Files (x86)\阿里云盘小白羊版\阿里云盘小白羊版v2\resources\
> 
> 如果确认无误，那么尝试将整个阿里云盘放置在其它位置，一个不带空格和小括号的路径下

感谢回复。
文件位置正确，
Aria2文件目录未被覆盖，
无论将软件安装在任何位置，路径没有空格和小括号，运行小程序都会显示发生未定义的异常，小白羊将自动退出弹窗，并不断显示Aria2本地连接已断开。
我想这可能是本地Aria2设置的错误。

**Comment by q527596142** [comment]
另一台主机使用没有任何问题，这是一台笔记本，刚发现连阿里云盘官方软件都无法下载，软件内鼠标旁一直是漏斗在闪烁，我估计是某个支持下载的程序被限制了，真是无语。如果实在没有解决办法可能只有等下刷下系统试试了。

**Comment by PingKuNet** [comment]
怎么感觉有点像安全软件拦截了呢

**Comment by AXBNG** [comment]
win10、win11从未遇到过此问题，你是不是用了什么杀软导致了拦截

**Comment by q527596142** [comment]
全盘扫描了下木马，自动清除关机，第二天开机屏幕狂闪，于是重装系统，完了小白杨即可正常使用，此报错自始至终没有找到原因与解决办法，但是重装系统即可。

**Comment by woodee** [comment]
我也遇到了这个，只能当播放器了
