### ISSUE TITLE
严重问题

### ISSUE THREAD

**Issue by zhangbolins** [liupan1890/aliyunpan#84]
聚合搜索里搜索关键词2020，会出来av视频，这涉嫌涉黄。
作者看到后把这个留言删掉，然后解决问题吧。

**Comment by xiaolai1995** [comment]
搜av也能出来....

**Comment by liupan1890** [comment]
收到，因为都是大家导入115的时候如果勾选分享，会定期自动导入。我稍后会对导入进行限制，可能需要人工排除掉一些涉X的。今晚我先整体全部清理掉

**Comment by liupan1890** [comment]
已经基本清理干净了

**Comment by Devinss** [comment]
这位反馈的大兄弟你还不如去看新闻联播吧！

**Comment by Devinss** [comment]
> 已经基本清理干净了

大佬，现在清理完之后，资源几乎没有，很喜欢这个聚合搜索，能把这个没有清理的版本或者预留没有清理的版本给有需要的同学吗？

**Comment by liupan1890** [comment]
因为现在愿意分享的人并不多，或者说因为默认是不分享的，大家也没有习惯专门去点一下勾选分享，所以现在能够搜索到的资源确实很少

等以后资源会越来越多的！

**Comment by liupan1890** [comment]
现在搜索是没有分类的，所以可能什么都能搜索出来，等以后我会给资源加上分类，这样搜索时结果会更准确。大家的需求我都会认真考虑的

**Comment by yayaleslie** [comment]
> 这位反馈的大兄弟你还不如去看新闻联播吧！

说得对，好不容易 有人愿意分享一些资源，让大家搜索，多方便，我导入链接时候，想到了就会勾上分享

**Comment by omy2000** [comment]
zhangbolin  章勃零？

**Comment by liupan1890** [comment]
不是，都是为了正规发展，为了小白羊好，大家不要乱刷了
