### ISSUE TITLE
建议：给文件加 tag 标记

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/aliyunpan#85]
想法来源：
文件很多但又属于一类【意思就是在同一个文件夹下】，这时候标记很重要，譬如：哪些看过了 就打个【已读或已看的标记】，哪些质量较好，就打个 【好 等级标签】，我是经常遇到

之前用 gd-driver 的时候，有个类似的功能不错，可以给文件夹改颜色，来达到标记的功能，所以希望大佬也加一个给文件做标记的功能，颜色也好，打文字tag也好，感觉很实用

![360截图172905076610491](https://user-images.githubusercontent.com/19268555/124370741-50eb8f80-dcad-11eb-9c9a-dd446faee03c.png)

**Comment by liupan1890** [comment]
嗯，这个想法好，我之后会研究一下，是标记好看，还是改颜色好看。要项目好区分，又要考虑别太花里胡哨的吸引眼球。

总之以后会加上这个功能的

**Comment by yayaleslie** [comment]
哦哦 大佬辛苦

**Comment by liupan1890** [comment]
先别关，开着，因为我好记者有这个功能需要做。因为在大改，这个功能上线会比较慢，我怕忘了，开着吧

**Comment by liupan1890** [comment]
文件名颜色标记功能已在v2.8.1.pre里实现，只支持8种颜色的标记，应该够用了
