### ISSUE TITLE
秒传文件txt可能被阿里云和谐吗？

### ISSUE THREAD

**Issue by lansal** [liupan1890/aliyunpan#86]
博主你好，txt因为变相增加了阿里云的容量，阿里云会不会和谐这个功能

**Comment by liupan1890** [comment]
百度云盘运营了好几年了，也一直没有和谐百度秒传链接脚本。
115云盘运营了好几年了，也一直没有和谐115秒传链接脚本
阿里云盘更加开放，所以不会和谐的
