### ISSUE TITLE
> 奶牛快传 https://cowtransfer.com/s/96dbff1c378f48

### ISSUE THREAD

**Issue by IBluemingU** [liupan1890/aliyunpan#860]
> 奶牛快传 https://cowtransfer.com/s/96dbff1c378f48
> 
> 文叔叔 https://www.wenshushu.cn/f/8dvclhee571
> 
> v3.05.23.alpha 开发人员测试版本已发布（可以与v2.12.14共存一起使用，互不影响）
> 
> 经过整理，我已经上传了v3.05.23.alpha 开发人员测试版。很尴尬的是，由于时间原因，开发进度很慢。此版本中部分重要功能缺失（上传和下载功能），并不适合日常使用。我仍在努力开发，会慢慢将缺失的功能补上来
> 
> 1. Fix 偶发的登录后显示空白窗口的 BUG
> 2. Fix 登录太多账号时切换账号弹窗不能正确显示的 BUG
> 3. 优化长时间不用后需要重新登录的问题
> 4. Fix 偶发的下载中显示空白列表的 BUG
> 5. Fix 多次弹出升级提示窗口的 BUG
> 6. Fix 目录下超过 200 个文件夹不能显示的 BUG
> 7. 重制 APP 设置页面，分组设置，配置保存到 setting.config
> 8. 优化快捷键(现在很多操作都支持键盘快捷键)
> 
> --
> 
> ### v3.05.23.alpha 新增加的功能
> 文件恢复，放映室，网页版播放器，彻底删除菜单，文件属性菜单，所有列表支持右键菜单，整盘高级搜索，文件快速筛选，右侧文件拖放移动，文件标记，文件夹快捷方式，我订阅的公众号，重复文件清理，扫描大文件，扫描重复文件，扫描违规文件，扫描空文件夹，网盘相册间复制，批量重命名
> 
> --
> 
> 此版本尚未经过完善的功能测试，如果遇到任何异常，请主动给我发issue，在下个版本里会立即修复。同时开源代码已同步到v3 分支
> 
> .
> 
> PS:近期大家发的issue我都会认真看，但因为网络原因，回复的不是很及时，请见谅
> 
> --
> 
> [v2.12.14 发布公告](https://github.com/liupan1890/aliyunpan/issues/639)

**Comment by xiaozhi1218** [comment]
链接失效了，麻烦重发一下
