### ISSUE TITLE
每次打开的位置都在右下角

### ISSUE THREAD

**Issue by CONAN-ZDD** [liupan1890/aliyunpan#87]
希望可以加入分辨率适配，以及记忆上次的位置和大小，调节完大小和位置之后，退出重新打开又跑到右下角了，大小也初始化了

**Comment by liupan1890** [comment]
收到，下个版本会支持记忆窗口大小

**Comment by CONAN-ZDD** [comment]
感谢大佬

**Comment by liupan1890** [comment]
记忆窗口大小功能已在v2.8.1.pre里实现，调整窗口大小再退出，重新打开时大小不变

但是位置都是默认屏幕中心，避免有时把窗口移动到最底部（几乎看不到的位置）后，移动不回来
