### ISSUE TITLE
【403】大佬忙不忙，大佬啥时候更新

### ISSUE THREAD

**Issue by QYG2297248353** [liupan1890/aliyunpan#877]
HttpError4 status=403 code=UserDeviceIllegality message=Request failed with status code 403
![image](https://user-images.githubusercontent.com/56836951/219047758-1da7fa0b-bf45-4acb-81f8-07d52479b229.png)

**Comment by yuanjie408** [comment]
和你一样的错误，2.12.14版本  ARM处理器

**Comment by LIUBANGJIAN** [comment]
大佬早就弃坑了，应该不会更新了。
