### ISSUE TITLE
反馈个bug

### ISSUE THREAD

**Issue by CONAN-ZDD** [liupan1890/aliyunpan#88]
聚合搜索在有输入内容的时候权限，然后不删除，直接输入新的关键词（这是我自己的习惯，不知道别人有没有），这样输入的话会出现重复输入的bug，求大佬有时间看看这个bug能不能修复呀

**Comment by liupan1890** [comment]
这个是Flutter本身的BUG，暂无修复方案。所以我下个版本就不用Flutter了，换Electron了，会修正此问题

同样已知的问题是输入时很多操作都不方便/不正常  比如想拖选几个字。比如输入法切换等等吧，总之一个输入框问题一大堆。
