### ISSUE TITLE
万星技术类作者找不到程序员工作?

### ISSUE THREAD

**Issue by buffge** [liupan1890/aliyunpan#882]
现实中一千star的都能直接甩面试官脸上砸他了,我是想不通 是不是你所在城市岗位太少 多的不说 找个3w的很轻松吧 哪怕是没学历

**Comment by softlgl** [comment]
> 现实中一千star的都能直接甩面试官脸上砸他了,我是想不通 是不是你所在城市岗位太少 多的不说 找个3w的很轻松吧 哪怕是没学历

兄弟，你可能不太了解国内市场

**Comment by TcDhlPro** [comment]
> 现实中一千star的都能直接甩面试官脸上砸他了,我是想不通 是不是你所在城市岗位太少 多的不说 找个3w的很轻松吧 哪怕是没学历

现实跟网上的感受是真的有区别的

**Comment by buffge** [comment]
> > 现实中一千star的都能直接甩面试官脸上砸他了,我是想不通 是不是你所在城市岗位太少 多的不说 找个3w的很轻松吧 哪怕是没学历
> 
> 兄弟，你可能不太了解国内市场

哥们 我可能写不出万星技术类作品 但是我找3w的很随便 而且我学历也不好. 都能写出这种作品 面试不把面试官唬得一愣一愣的

**Comment by hellolxc** [comment]
莫名的有点伤感

**Comment by buffge** [comment]
> 莫名的有点伤感

我感觉不是他找不到 而是他性格方面问题,只要去面试肯定能上班 而且待遇不会低

**Comment by softlgl** [comment]
每个人的性格不一样，每个人对公司的理解也不一样，去个外包月薪3w问题不大，或者去个996的公司等等，但是工作不仅仅是钱或者不仅仅是为了钱，发展也很重要，当然每个人的目标不一样，在这里能赚3w，到了后面的公司是否能继续赚钱呢，或者对自己以后的提升怎么样等等吧。有的公司确实不需要看学历啥的，但是我觉得这种公司毕竟还是少数，或者是否可以被大部分称得上好公司。总之，每个人对公司的环境，或者自身的现实情况不一样，大可不必说的这么自然而然。

**Comment by buffge** [comment]
> 每个人的性格不一样，每个人对公司的理解也不一样，去个外包月薪3w问题不大，或者去个996的公司等等，但是工作不仅仅是钱或者不仅仅是为了钱，发展也很重要，当然每个人的目标不一样，在这里能赚3w，到了后面的公司是否能继续赚钱呢，或者对自己以后的提升怎么样等等吧。有的公司确实不需要看学历啥的，但是我觉得这种公司毕竟还是少数，或者是否可以被大部分称得上好公司。总之，每个人对公司的环境，或者自身的现实情况不一样，大可不必说的这么自然而然。

我认为你说的对,是我肤浅了

**Comment by wuqinqiang** [comment]
> > 每个人的性格不一样，每个人对公司的理解也不一样，去个外包月薪3w问题不大，或者去个996的公司等等，但是工作不仅仅是钱或者不仅仅是为了钱，发展也很重要，当然每个人的目标不一样，在这里能赚3w，到了后面的公司是否能继续赚钱呢，或者对自己以后的提升怎么样等等吧。有的公司确实不需要看学历啥的，但是我觉得这种公司毕竟还是少数，或者是否可以被大部分称得上好公司。总之，每个人对公司的环境，或者自身的现实情况不一样，大可不必说的这么自然而然。
> 
> 我认为你说的对,是我肤浅了

不是你肤浅，说明你还很年轻

**Comment by saintdianabless** [comment]
喜欢编程和不想工作是编程不冲突. 
如果你运气好碰到的项目正好是你热爱的还好. 
否则随便找个开发岗, 就是折磨. 每天用熟透的知识解决无限的问题, 工作上学不到新东西, 就很累.

**Comment by onvz** [comment]
这万星就是一行亮晶晶的资历啊

**Comment by hoochanlon** [comment]
偷笑.jpg 。很正常啦。这是加分，不是必要。

当初我自己，也和你一样也是这样想。但失业一年半载，然后出来工作一两年，发现安心过日子，比什么都好。

**Comment by fishered** [comment]
感触颇深  
有些时候，有些公司的岗位不是干活 而是噩梦 它会影响人的心态 
再或者 中国这个人情社会 有时候技术水平高低真的很重要吗 仁者见仁吧
