### ISSUE TITLE
我有意愿协助作者解决已存在bug，但是看一个PR都没有，估计作者也没时间CR。

### ISSUE THREAD

**Issue by gaozhangmin** [liupan1890/aliyunpan#888]
我有意愿协助作者解决已存在bug，但是看一个PR都没有，估计作者也没时间CR。

**Comment by charley008** [comment]
你要不自己fork一个 再发出来吧。用了几款其他软件都不好用

**Comment by Bssn520** [comment]
> 你要不自己fork一个 再发出来吧。用了几款其他软件都不好用

赞同🫡
