### ISSUE TITLE
内置搜索功能坏了吗

### ISSUE THREAD

**Issue by barnett2010** [liupan1890/aliyunpan#89]
大佬，好多关键字不能搜索了，比如四个英文的？端口5282出问题了吗

**Comment by liupan1890** [comment]
吓得我赶紧试了一下，四个字母，搜索`ming` 可以正常搜索出结果

所以为什么你说坏了呢？搜索结果少是因为当前分享的内容少，以后搜搜结果会慢慢增多的

**Comment by liupan1890** [comment]
哦，我反应过来了，你是说某些涉H的搜索不到了是吗？如果是参阅https://github.com/liupan1890/aliyunpan/issues/84
如果确实遇到BUG，请继续留言反馈

**Comment by barnett2010** [comment]
@liupan1890 感谢大佬的回复，理解删除的决定，
不知能不能求一份未删除前的秒传txt的分享。
里番资源不好找呀 :)

**Comment by liupan1890** [comment]
这个很难给你，注意不是不想给你

1.有很多用户分享了115秒传/阿里云盘秒传  这些秒传链接都一条一条的存放在数据库里
2.会不定期的（我手动点一下），把这些秒传格式化为一个一个的文件导入到搜索列表里
3.当时我是手动的批量的删除的部分资源（比如delete from xx where title like '%AV%'）
删除的时候并不是一次就能删除干净了，而是用了很多次，尝试了很多关键字

首先我删除前也没有备份数据--没有备份的意义
然后也删除的比较紧张/赶时间

那么删除了以后就是没有了（虽然可以通过重新全部解析一遍秒传链接全部重新生成）

最关键的是：我也不知道哪些文件是，哪些不是，所以也就是需要我再一遍手动的筛选出来这些是的，发给你

筛选一遍大概要半小时多，而且比如最终有了2K条记录，直接发给你你也没法直接用

所以说难度很大，我也没时间做这个，因为决定要UI大改，时间很紧
