### ISSUE TITLE
阿里云盘小白羊v3.23.120722

### ISSUE THREAD

**Issue by odomu** [liupan1890/aliyunpan#892]
阿里云盘小白羊v3修复版
https://github.com/odomu/aliyunpan/releases/

**Comment by cyao2q** [comment]
感谢大佬，这个版本看着好看 下面那个基于旧版改造的UI不习惯

**Comment by prajna0** [comment]
牛逼

**Comment by AjianNie** [comment]
祖国人：谁才是真的英雄

**Comment by AjianNie** [comment]
兄弟们有macOS版吗？

**Comment by YouthguyZ** [comment]
> 感谢大佬，这个版本看着好看 下面那个基于旧版改造的UI不习惯

用来嘛 能下载视频和在线观看吗

**Comment by Lsiyu7** [comment]
如何更改自己的播放器，不喜欢
sources文件夹里面的mpv播放器

**Comment by cyao2q** [comment]
> > 感谢大佬，这个版本看着好看 下面那个基于旧版改造的UI不习惯
> 
> 用来嘛 能下载视频和在线观看吗

可以 上传 下载 播放 都正常

**Comment by lrs95** [comment]
这版本确实比之前那个v2的好用

**Comment by pianfang** [comment]
> 兄弟们有macOS版吗？

同问啊～

**Comment by ybbluesky** [comment]
有没有x86版本可用的哟？

**Comment by AromanRon** [comment]
一直加载用户信息，不能用啊

**Comment by YouthguyZ** [comment]
隐私安全性怎么样 不会出现网上那种云盘泄露视频问题吧！！！

**Comment by gtyler-study** [comment]
一直在加载用户信息，不能使用。
登录正常。

**Comment by lrs95** [comment]
> 一直在加载用户信息，不能使用。 登录正常。

你们真的不看注意事项吗
注意

该版本与原版V3不兼容，请先做好数据备份
由于功能不完善，下载前请先在【设置】【传输】中设置好【下载文件保存的位置】
如果使用过原版V3，要进行“重置”才能正常使用，请前往[设置->高级选项->删除全部数据]
新账号首次登录，请使用扫码登录，如果卡在二次验证后的跳转中页面，请尝试“重置”后，扫码登录

**Comment by andywang1011** [comment]
![image](https://user-images.githubusercontent.com/40266446/221342078-2da16029-3977-4a2f-89e6-476a25a1160c.png)
不能用，下载、播放视频都不行，“视频地址解析失败”

**Comment by hackershi** [comment]
可以用了

**Comment by xun188** [comment]
期待MAC版本

**Comment by Superdreamyan** [comment]
牛的牛的🐂

**Comment by goeway** [comment]
太好了，又可以愉快地看视频了

**Comment by shuaiyewl** [comment]
【2023-02-25再次更新】阿里云盘小白羊版v3修复版 v3.10.24

上一版修复版 还保留了内置MPV，这一版删了，删了也好，本来大家也基本就需要上传下载功能，再说还可以指定本地播放器，还有内置网页播放器。
