### ISSUE TITLE
希望支持在线预览HEIC格式图片

### ISSUE THREAD

**Issue by eliotxu** [liupan1890/aliyunpan#91]
希望作者大大支持 iPhone 拍照后的 HEIC 格式图片 在线预览功能，谢谢

**Comment by liupan1890** [comment]
收到！忽略了。。。
不过有可能不能直接浏览原图（HEIC），可能最后是浏览缩略图。具体的图片大小我之后研究一下，尽量预览最大的图片

**Comment by eliotxu** [comment]
谢谢，感谢您的辛苦付出，期待作者大大更多优秀的作品！
