### ISSUE TITLE
1

### ISSUE THREAD

**Issue by samoayk** [liupan1890/aliyunpan#911]

**Comment by Yvan-W** [comment]
在某些方面上，你是个人才

**Comment by whevether** [comment]
心里阴暗的人看啥都是黑暗的。  当你某一天为柴米油盐发愁的时候你就知道生活是多么艰难了。

**Comment by yijianpeng** [comment]
> 心里阴暗的人看啥都是黑暗的。 当你某一天为柴米油盐发愁的时候你就知道生活是多么艰难了。

大佬怎么了？

**Comment by samoayk** [comment]
软件我也再用，我只是把心里想的说出来了，如果在这个网站也是不能有丝毫质疑权威的，那我闭嘴。
我的出发点就以下几个，欢迎交流
1、小白羊早于官方PC版本。且计划中的好多功能未开发。（官方试水且有些功能、资源以官方名义来做是违法的）
2、小白羊没有开源。之前就有人在他说压力大，可能不做的时候，提出如果方便公开代码，可以后续开发的，没公开。
3、有介绍工作的，而且是有明确履历的人。（作为普通人，一个陌生人看我可怜，想请我吃饭，我不想这样，那我也会寒暄一下，没有错吧。忙到完全不看、不关心自己曾经辛辛苦苦写的代码，也许吧。）

最后这个只是补充。没见过任何形式作者的真容（如果是有但是我不知道，可以告诉我，如果没有，普通人不想在网络曝光我也理解）

**Comment by samoayk** [comment]
> 嘴上积点德 实在没话说 可以闭嘴

嗯。你也是
