### ISSUE TITLE
亲测MAC可用版本v3.10.25

### ISSUE THREAD

**Issue by gaozhangmin** [liupan1890/aliyunpan#917]
https://github.com/gaozhangmin/aliyunpan
后期计划长期维护，有问题可以提issue。计划将API替换成官方api。

**Comment by chengnan049** [comment]
好耶！

**Comment by luoguanping** [comment]
没见到编译版呀？

**Comment by gaozhangmin** [comment]
我正在开发基于官方APi的版本，等等我开发完成吧。

**Comment by luoguanping** [comment]
期待！

**Comment by gaozhangmin** [comment]
基于Open api的代码开发完成了，
我申请了阿里云平台的账号，但是没有人联系我，现在的情况是有没有人能提供个阿里云平台账号

**Comment by chengnan049** [comment]
> 基于 Open api 的代码开发完成了， 我申请了阿里云平台的账号，但是没有人联系我，现在的情况是有没有人能提供个阿里云平台账号

好耶！

**Comment by gaozhangmin** [comment]
> > 基于 Open api 的代码开发完成了， 我申请了阿里云平台的账号，但是没有人联系我，现在的情况是有没有人能提供个阿里云平台账号
> 
> 好耶！

@chengnan049 没有open api的账号，调不了api。

**Comment by chengnan049** [comment]
> > > 基于 Open api 的代码开发完成了， 我申请了阿里云平台的账号，但是没有人联系我，现在的情况是有没有人能提供个阿里云平台账号
> > 
> > 
> > 好耶！
> 
> @chengnan049 没有 open api 的账号，调不了 api。

去小白羊评论区或者隔壁 Alist 等蹭一蹭（或许不会同意的吧，毕竟有用户名呢，出事儿了可不敢担责）
