### ISSUE TITLE
请问离线下载功能什么时候安排？

### ISSUE THREAD

**Issue by WHYEX3** [liupan1890/aliyunpan#93]
请问离线下载功能什么时候安排？

**Comment by d790043608** [comment]
+1

**Comment by liupan1890** [comment]
不知道
1.当前正在版本的大改动，预计需要半个月
这次大改，是真的有巨大的提升。细节太多，使用体验会有很大的提升（误报病毒，mac损坏，美观度，流畅度，无法连接到后台进程等等之前易发的错误都会被彻底解决）。
2.待增加的新功能
同步盘，重复文件扫描，文件洗码工具

3.最后才轮到离线功能。因为离线功能需要花钱比较多，所以安排在最后了

**Comment by lansal** [comment]
大哥是不是被阿里邀请去开发了

**Comment by iD2073** [comment]
已经半个月过去了，还是没有消息，很期待新版本哦，1.6.29功能也不错，就是没有缩略图显示很遗憾
