### ISSUE TITLE
创建Aria任务失败连接断开

### ISSUE THREAD

**Issue by wangjt23** [liupan1890/aliyunpan#939]
#### 版本
系统版本：ubuntu22.04；x86_64
小白羊版本：XBYDriver-3.12.1-linux-amd64.deb
#### 问题
不下载的时候会显示Aria已连接
![image](https://github.com/liupan1890/aliyunpan/assets/95030095/a209b2d6-5379-4f95-baac-a43161af12f7)
一开始下载立马报错，并显示Aria断开
![image](https://github.com/liupan1890/aliyunpan/assets/95030095/0b2287c7-450f-4d26-97b3-09ee60025263)

![image](https://github.com/liupan1890/aliyunpan/assets/95030095/71b28577-bb01-4771-931a-b1c7d8a6b425)
#### 运行日志
![image](https://github.com/liupan1890/aliyunpan/assets/95030095/7303bde0-911b-45d7-ba29-63176ee6dffa)

**Comment by MichaelMaiii** [comment]
Replace with local aria2：
```
sudo apt install aria2
cd /opt/小白羊云盘/resources/engine
sudo mv aria2c aria2_bak
sudo ln /usr/bin/aria2c
```
Refer to https://blog.csdn.net/a541972321/article/details/134212306

**Comment by donggua1118** [comment]
win版本的也是这个问题，奇了怪了

**Comment by wzc0066** [comment]
> Replace with local aria2：
> 
> ```
> sudo apt install aria2
> cd /opt/小白羊云盘/resources/engine
> sudo mv aria2c aria2_bak
> sudo ln /usr/bin/aria2c
> ```
> 
> Refer to https://blog.csdn.net/a541972321/article/details/134212306

非常感谢，问题获得完美解决，已经可以正常下载了！
小白羊云盘 真是好好东西！
之前一直在寻找可以在Linux下使用的客户端软件，有一个命令行折腾了下不好用就放弃了。
没想到这次查找竟然找到这么个宝贝！

百度现在都已经这么落寞了，都还提供了官方的百度云盘客户端软件。
阿里云盘这么大的体量，着实不应该在平台通用性方面节省成本。
建议小白羊云盘团队去跟阿里云盘协商，让他们出点钱把这个项目收了，让小白羊云盘 一朝转正！
