### ISSUE TITLE
Win10启动报错

### ISSUE THREAD

**Issue by windfsy** [liupan1890/aliyunpan#94]
启动后就会显示找不到alisever.exe
![image](https://user-images.githubusercontent.com/86504603/124535042-0fdbb280-de48-11eb-96d7-306c36f8e536.png)
然后就会卡在启动服务...
![image](https://user-images.githubusercontent.com/86504603/124535100-271aa000-de48-11eb-8277-9d566b8bc9c0.png)

**Comment by windfsy** [comment]
补充一点 ，aliserver.exe 并没有丢失
![image](https://user-images.githubusercontent.com/86504603/124535274-6e089580-de48-11eb-8022-b79de608f025.png)

**Comment by windfsy** [comment]
难道是因为我开着阿里官方的客户端吗？😂

**Comment by windfsy** [comment]
在压缩包里运行就一点事也没有

**Comment by yikwing** [comment]
我mac也有这个问题了 debug.log日志
<img width="901" alt="iShot2021-07-06 11 22 55" src="https://user-images.githubusercontent.com/20245290/124537473-88dd0900-de4c-11eb-929c-f6667e77fddb.png">

**Comment by liupan1890** [comment]
> 在压缩包里运行就一点事也没有

你的报错，是找不到文件，既然检查了aliserver.exe文件存在，说明是没有权限运行（1.可能是没有访问权限 2.可能是文件被杀毒软件锁定不能执行 3.可能是我不知道的原因）

我留意到你把小白羊复制到了Programs Files文件夹里面了。可能跟这个有关，比如你复制到D:/xxx/下面就没事可以运行。因为Programs Files属于系统文件夹，在此文件夹内，创建文件/文件夹/访问文件 确实有可能会遇到权限问题！Programs Files对权限要求比较高。

你试一下把小白羊解压到非C盘，可能就好了，只是猜测

**Comment by liupan1890** [comment]
> 我mac也有这个问题了 debug.log日志
> <img alt="iShot2021-07-06 11 22 55" width="901" src="https://user-images.githubusercontent.com/20245290/124537473-88dd0900-de4c-11eb-929c-f6667e77fddb.png">

你的这个问题有人之前遇到过，跟你一样是listen tcp 198.18.1.19：29385 出错，正确的应该是listen tcp 127.0.0.1：29385

参阅https://github.com/liupan1890/aliyunpan/issues/76

**Comment by windfsy** [comment]
> > 在压缩包里运行就一点事也没有
> 
> 你的报错，是找不到文件，既然检查了aliserver.exe文件存在，说明是没有权限运行（1.可能是没有访问权限 2.可能是文件被杀毒软件锁定不能执行 3.可能是我不知道的原因）
> 
> 我留意到你把小白羊复制到了Programs Files文件夹里面了。可能跟这个有关，比如你复制到D:/xxx/下面就没事可以运行。因为Programs Files属于系统文件夹，在此文件夹内，创建文件/文件夹/访问文件 确实有可能会遇到权限问题！Programs Files对权限要求比较高。
> 
> 你试一下把小白羊解压到非C盘，可能就好了，只是猜测

能不能开发安装版的，这样是不是就能解决这些问题呢？

**Comment by windfsy** [comment]
> > 在压缩包里运行就一点事也没有
> 
> 你的报错，是找不到文件，既然检查了aliserver.exe文件存在，说明是没有权限运行（1.可能是没有访问权限 2.可能是文件被杀毒软件锁定不能执行 3.可能是我不知道的原因）
> 
> 我留意到你把小白羊复制到了Programs Files文件夹里面了。可能跟这个有关，比如你复制到D:/xxx/下面就没事可以运行。因为Programs Files属于系统文件夹，在此文件夹内，创建文件/文件夹/访问文件 确实有可能会遇到权限问题！Programs Files对权限要求比较高。
> 
> 你试一下把小白羊解压到非C盘，可能就好了，只是猜测


现在这个问题解决了

但是上传多个大文件(21个1GB以上的文件)的速度貌似比官方的慢
我把文件通过小白羊盘、百度网盘、阿里云盘一起上传，结果百度竟然是最快的，阿里第二，小白羊第三，主要原因应该是在于百度读取文件速度比较快，阿里和小白羊都要等半天才能开始上传，希望这个能够加强一下🚀🚀🚀🚀

**Comment by liupan1890** [comment]
关于上传速度
1.小白羊的上传，跟官方的上传区别不大，慢也慢不到哪去。都在合理范围内（意思是假如官方上传需要10分钟，小白羊就算是慢也就是8-9分钟的事，快或慢1分钟）

2.上传时，官方默认是几个文件同时上传我没留意，小白羊最多可以设置为9个文件同时上传。如果你的上传宽带极大，可以通过9文件同时上传的方式达到最大上传速度。这点比官方肯定快，因为官方没有9个文件这么多

3.不要同时开着百度，阿里，小白羊同时上传。因为这样测试不准。有一个网络竞争的问题
比如说你先点百度的上传，此时他就会先占用大量的带宽，你再点阿里云盘的上传，此时阿里云盘会上传速度很慢，需要慢慢的跟百度竞争，之后的上传速度一般都是早启动的有优势。
1.这个涉及到TCP协议的设计，传输速度是需要网络中间（路由/服务器/发送方）互相协商的。
2.这个涉及到Windows下CPU/线程资源竞争的问题
3.这个涉及到硬盘读写竞争的问题
总之这样测试不准确


举个常见的例子，你先复制一堆文件（从D盘复制到C盘）。然后立即又复制另外一对文件（从D盘到F盘）。你会看到这2个队列的复制速度不一样，并不是平分的，一个复制速度快，一个复制速度慢，并且不是固定的会一直变动

**Comment by windfsy** [comment]
> 关于上传速度
> 1.小白羊的上传，跟官方的上传区别不大，慢也慢不到哪去。都在合理范围内（意思是假如官方上传需要10分钟，小白羊就算是慢也就是8-9分钟的事，快或慢1分钟）
> 
> 2.上传时，官方默认是几个文件同时上传我没留意，小白羊最多可以设置为9个文件同时上传。如果你的上传宽带极大，可以通过9文件同时上传的方式达到最大上传速度。这点比官方肯定快，因为官方没有9个文件这么多
> 
> 3.不要同时开着百度，阿里，小白羊同时上传。因为这样测试不准。有一个网络竞争的问题
> 比如说你先点百度的上传，此时他就会先占用大量的带宽，你再点阿里云盘的上传，此时阿里云盘会上传速度很慢，需要慢慢的跟百度竞争，之后的上传速度一般都是早启动的有优势。
> 1.这个涉及到TCP协议的设计，传输速度是需要网络中间（路由/服务器/发送方）互相协商的。
> 2.这个涉及到Windows下CPU/线程资源竞争的问题
> 3.这个涉及到硬盘读写竞争的问题
> 总之这样测试不准确
> 
> 举个常见的例子，你先复制一堆文件（从D盘复制到C盘）。然后立即又复制另外一对文件（从D盘到F盘）。你会看到这2个队列的复制速度不一样，并不是平分的，一个复制速度快，一个复制速度慢，并且不是固定的会一直变动

好吧，那还是感谢了
