### ISSUE TITLE
在线解压出现空白页

### ISSUE THREAD

**Issue by windfsy** [liupan1890/aliyunpan#96]
https://user-images.githubusercontent.com/86504603/124699388-49322200-df1d-11eb-8304-10796a9e33ab.mp4
如视频所示

**Comment by windfsy** [comment]
https://user-images.githubusercontent.com/86504603/124699388-49322200-df1d-11eb-8304-10796a9e33ab.mp4

**Comment by liupan1890** [comment]
收到！是我忘了给解压结果提示这个弹窗适配黑色背景了。。。
虽然很难看（浅色模式是正常的）但并不影响实际解压操作

会在下个版本中修复的
