### ISSUE TITLE
请求新增多开 或者 多账户切换功能

### ISSUE THREAD

**Issue by kedyao** [liupan1890/aliyunpan#97]

**Comment by liupan1890** [comment]
嗯收到，以后会增加多账户切换功能（切换后不会影响之前的下载/上传任务）

多开就不支持了，倒不是我想要限制多开

mac下并不允许应用多开（虽然能绕开，但mac的模式就是这样，不推荐多开）
windows下倒是没有这个设计，但是为了统一，就都不支持多开了

另外因为是调用的aria2实现的下载功能，多开时会比较混，所以从设计上也不想支持多开，容易出BUG

**Comment by liupan1890** [comment]
多账号登陆功能已在v2.8.1.pre里实现
