### ISSUE TITLE
能开发一个安卓TV版本吗？

### ISSUE THREAD

**Issue by omy2000** [liupan1890/aliyunpan#98]
大佬，如题，解决电视机上看片子的痛点，ios也不需要，家里一般都安卓智能电视。

**Comment by WHYEX3** [comment]
https://github.com/liupan1890/aliyunpan/issues/70

**Comment by liupan1890** [comment]
> #70

如题，没有时间做TV

**Comment by iD2073** [comment]
真有很希望能有过tv版，

**Comment by iD2073** [comment]
不过也能理解，必定免费，你也很辛苦，可以价格赞助的二维码，大家都可以赞助一下你
