### ISSUE TITLE
希望能批量导入阿里云盘分享链接

### ISSUE THREAD

**Issue by zhangbolins** [liupan1890/aliyunpan#99]
导入分享里一次只能导入一条阿里云盘分享链接，很多资源一个个导入太麻烦了，希望能批量导入阿里云盘分享链接。

**Comment by liupan1890** [comment]
以后会增加批量导入的功能的,我记下了

**Comment by liupan1890** [comment]
这个功能本周开发时，尝试了一下，最终放弃了

当前阿里云盘的分享链接，支持最多15级文件嵌套和最多4000个文件，但以后阿里还会进一步放开限制

这样如果单条分享链接内包含很多文件时，会导致 导入分享链接时，单条链接需要较长时间解析文件列表

另外大家的网盘空间也有限，所以很多导入时都是需要先筛选一些文件最终保存的

所以，批量导入分享链接功能，最终还是放弃了，因为导入时间不可控，可能几十秒，可能要等十几分钟，这个体验不好。当前还是只提供单条分享链接的导入功能
